/* Создание таблицы типов фирм */

CREATE TABLE /*PREFIX*/FIRM_TYPES
(
  FIRM_TYPE_ID VARCHAR(32) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(250),
  PRIORITY INTEGER NOT NULL,
  PRIMARY KEY (FIRM_TYPE_ID)
)

--

/* Создание просмотра таблицы типов фирм */

CREATE VIEW /*PREFIX*/S_FIRM_TYPES
AS
SELECT * FROM /*PREFIX*/FIRM_TYPES

--

/* Создание процедуры добавления типа фирмы */

CREATE PROCEDURE /*PREFIX*/I_FIRM_TYPE
(
  FIRM_TYPE_ID VARCHAR(32),
  NAME VARCHAR(100),
  DESCRIPTION VARCHAR(250),
  PRIORITY INTEGER
)
AS
BEGIN
  INSERT INTO /*PREFIX*/FIRM_TYPES (FIRM_TYPE_ID,NAME,DESCRIPTION,PRIORITY)
       VALUES (:FIRM_TYPE_ID,:NAME,:DESCRIPTION,:PRIORITY);
END;

--

/* Создание процедуры изменения типа фирмы */

CREATE PROCEDURE /*PREFIX*/U_FIRM_TYPE
(
  FIRM_TYPE_ID VARCHAR(32),
  NAME VARCHAR(100),
  DESCRIPTION VARCHAR(250),
  PRIORITY INTEGER,
  OLD_FIRM_TYPE_ID VARCHAR(32)
)
AS
BEGIN
  UPDATE /*PREFIX*/FIRM_TYPES
     SET FIRM_TYPE_ID=:FIRM_TYPE_ID,
         NAME=:NAME,
         DESCRIPTION=:DESCRIPTION,
         PRIORITY=:PRIORITY
   WHERE FIRM_TYPE_ID=:OLD_FIRM_TYPE_ID;
END;

--

/* Создание процедуры удаления типа фирмы */

CREATE PROCEDURE /*PREFIX*/D_FIRM_TYPE
(
  OLD_FIRM_TYPE_ID VARCHAR(32)
)
AS
BEGIN
  DELETE FROM /*PREFIX*/FIRM_TYPES 
        WHERE FIRM_TYPE_ID=:OLD_FIRM_TYPE_ID;
END;

--
