/* Создание таблицы блокировок */

CREATE TABLE /*PREFIX*/LOCKS
(
  LOCK_ID VARCHAR(32) NOT NULL,
  APPLICATION_ID VARCHAR(32) NOT NULL,
  ACCOUNT_ID VARCHAR(32),
  DATE_BEGIN TIMESTAMP NOT NULL,
  DATE_END TIMESTAMP,
  METHOD VARCHAR(100),
  OBJECT VARCHAR(100),
  DESCRIPTION VARCHAR(250),
  IP_LIST VARCHAR(1000),
  PRIMARY KEY (LOCK_ID),
  FOREIGN KEY (APPLICATION_ID) REFERENCES /*PREFIX*/APPLICATIONS (APPLICATION_ID),
  FOREIGN KEY (ACCOUNT_ID) REFERENCES /*PREFIX*/ACCOUNTS (ACCOUNT_ID)
)

--

/* Создание просмотра таблицы блокировок */

CREATE VIEW /*PREFIX*/S_LOCKS
(
  LOCK_ID,
  APPLICATION_ID,
  ACCOUNT_ID,
  DATE_BEGIN,
  DATE_END,
  METHOD,
  OBJECT,
  DESCRIPTION,
  IP_LIST,
  APPLICATION_NAME,
  USER_NAME
)
AS
  SELECT L.*,
         A.NAME AS APPLICATION_NAME,
         AC.USER_NAME
    FROM /*PREFIX*/LOCKS L
    JOIN /*PREFIX*/APPLICATIONS A ON A.APPLICATION_ID=L.APPLICATION_ID
    LEFT JOIN /*PREFIX*/ACCOUNTS AC ON AC.ACCOUNT_ID=L.ACCOUNT_ID

--

/* Создание процедуры добавления блокировки */

CREATE PROCEDURE /*PREFIX*/I_LOCK
(
  LOCK_ID VARCHAR(32),
  APPLICATION_ID VARCHAR(32),
  ACCOUNT_ID VARCHAR(32),
  DATE_BEGIN TIMESTAMP,
  DATE_END TIMESTAMP,
  METHOD VARCHAR(100),
  OBJECT VARCHAR(100),
  DESCRIPTION VARCHAR(250),
  IP_LIST VARCHAR(1000)
)
AS
BEGIN
  INSERT INTO /*PREFIX*/LOCKS (LOCK_ID,APPLICATION_ID,ACCOUNT_ID,DATE_BEGIN,DATE_END,METHOD,OBJECT,DESCRIPTION,IP_LIST)
       VALUES (:LOCK_ID,:APPLICATION_ID,:ACCOUNT_ID,:DATE_BEGIN,:DATE_END,:METHOD,:OBJECT,:DESCRIPTION,:IP_LIST);
END;

--

/* Создание процедуры изменения блокировки */

CREATE PROCEDURE /*PREFIX*/U_LOCK
(
  LOCK_ID VARCHAR(32),
  APPLICATION_ID VARCHAR(32),
  ACCOUNT_ID VARCHAR(32),
  DATE_BEGIN TIMESTAMP,
  DATE_END TIMESTAMP,
  METHOD VARCHAR(100),
  OBJECT VARCHAR(100),
  DESCRIPTION VARCHAR(250),
  IP_LIST VARCHAR(1000),
  OLD_LOCK_ID VARCHAR(32)
)
AS
BEGIN
  UPDATE /*PREFIX*/LOCKS
     SET LOCK_ID=:LOCK_ID,
         APPLICATION_ID=:APPLICATION_ID,
         ACCOUNT_ID=:ACCOUNT_ID,
         DATE_BEGIN=:DATE_BEGIN,
         DATE_END=:DATE_END,
         METHOD=:METHOD,
         OBJECT=:OBJECT,
         DESCRIPTION=:DESCRIPTION,
         IP_LIST=:IP_LIST
   WHERE LOCK_ID=:OLD_LOCK_ID;
END;

--

/* Создание процедуры удаления блокировки */

CREATE PROCEDURE /*PREFIX*/D_LOCK
(
  OLD_LOCK_ID VARCHAR(32)
)
AS
BEGIN
  DELETE FROM /*PREFIX*/LOCKS
        WHERE LOCK_ID=:OLD_LOCK_ID;
END;

--
