/* Создание процедуры разблокировки исходящего сообщения */

CREATE PROCEDURE /*PREFIX*/UNLOCK_OUT_MESSAGE
(
  OUT_MESSAGE_ID VARCHAR(32),
  SENDED INTEGER,
  DATE_OUT TIMESTAMP
)
AS
BEGIN
  IF (SENDED<>0) THEN BEGIN

    IF (DATE_OUT IS NULL) THEN
      DATE_OUT=CURRENT_TIMESTAMP;

    UPDATE /*PREFIX*/OUT_MESSAGES
       SET DATE_OUT=:DATE_OUT,
           LOCKED=NULL
     WHERE OUT_MESSAGE_ID=:OUT_MESSAGE_ID;

  END ELSE BEGIN

    UPDATE /*PREFIX*/OUT_MESSAGES
       SET LOCKED=NULL
     WHERE OUT_MESSAGE_ID=:OUT_MESSAGE_ID;

  END

END;

--
