/* Создание таблицы населенных пунктов */

CREATE TABLE /*PREFIX*/LOCALITIES
(
  LOCALITY_ID VARCHAR(32) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  PREFIX VARCHAR(10),
  PRIMARY KEY (LOCALITY_ID)
)

--

/* Создание просмотра населенных пунктов */

CREATE VIEW /*PREFIX*/S_LOCALITIES
AS
SELECT * FROM /*PREFIX*/LOCALITIES

--

/* Создание процедуры добавления населенного пункта */

CREATE PROCEDURE /*PREFIX*/I_LOCALITY
(
  IN LOCALITY_ID VARCHAR(32),
  IN NAME VARCHAR(100),
  IN PREFIX VARCHAR(10)
)
BEGIN
  INSERT INTO /*PREFIX*/LOCALITIES (LOCALITY_ID,NAME,PREFIX)
       VALUES (LOCALITY_ID,NAME,PREFIX);
END;

--

/* Создание процедуры изменения населенного пункта */

CREATE PROCEDURE /*PREFIX*/U_LOCALITY
(
  IN LOCALITY_ID VARCHAR(32),
  IN NAME VARCHAR(100),
  IN PREFIX VARCHAR(10),
  IN OLD_LOCALITY_ID VARCHAR(32)
)
BEGIN
  UPDATE /*PREFIX*/LOCALITIES L
     SET L.LOCALITY_ID=LOCALITY_ID,
         L.NAME=NAME,
         L.PREFIX=PREFIX
   WHERE L.LOCALITY_ID=OLD_LOCALITY_ID;
END;

--

/* Создание процедуры удаления населенного пункта */

CREATE PROCEDURE /*PREFIX*/D_LOCALITY
(
  IN OLD_LOCALITY_ID VARCHAR(32)
)
BEGIN
  DELETE FROM /*PREFIX*/LOCALITIES 
        WHERE LOCALITY_ID=OLD_LOCALITY_ID;
END;

--
