/* Создание таблицы предприятий */

CREATE TABLE /*PREFIX*/FIRMS
(
  FIRM_ID VARCHAR(32) NOT NULL,
  FIRM_TYPE_ID VARCHAR(32) NOT NULL,
  PARENT_ID VARCHAR(32),
  SMALL_NAME VARCHAR(250) NOT NULL,
  FULL_NAME VARCHAR(250) NOT NULL,
  INN VARCHAR(12),
  PAYMENT_ACCOUNT VARCHAR(20),
  BANK VARCHAR(250),
  BIK VARCHAR(20),
  CORR_ACCOUNT VARCHAR(20),
  PHONE VARCHAR(250),
  FAX VARCHAR(250),
  EMAIL VARCHAR(100),
  SITE VARCHAR(100),
  OKONH VARCHAR(20),
  OKPO VARCHAR(20),
  KPP VARCHAR(20),
  DIRECTOR VARCHAR(250),
  ACCOUNTANT VARCHAR(250),
  CONTACT_FACE VARCHAR(250),
  INDEX_LEGAL VARCHAR(10),
  STREET_LEGAL_ID VARCHAR(32),
  HOUSE_LEGAL VARCHAR(10),
  FLAT_LEGAL VARCHAR(10),
  INDEX_POST VARCHAR(10),
  STREET_POST_ID VARCHAR(32),
  HOUSE_POST VARCHAR(10),
  FLAT_POST VARCHAR(10),
  PRIMARY KEY (FIRM_ID),
  FOREIGN KEY (FIRM_TYPE_ID) REFERENCES /*PREFIX*/FIRM_TYPES (FIRM_TYPE_ID),
  FOREIGN KEY (STREET_LEGAL_ID) REFERENCES /*PREFIX*/STREETS (STREET_ID),
  FOREIGN KEY (STREET_POST_ID) REFERENCES /*PREFIX*/STREETS (STREET_ID),
  FOREIGN KEY (PARENT_ID) REFERENCES FIRMS/*PREFIX*/ (FIRM_ID)  
)

--

/* Создание просмотра таблицы предприятий */

CREATE VIEW /*PREFIX*/S_FIRMS
AS
  SELECT F.*,
         FT.NAME AS FIRM_TYPE_NAME,
         F1.SMALL_NAME AS PARENT_SMALL_NAME,
         S1.NAME AS STREET_LEGAL_NAME,
         S1.PREFIX AS STREET_LEGAL_PREFIX,
         L1.LOCALITY_ID AS LOCALITY_LEGAL_ID,
         L1.NAME AS LOCALITY_LEGAL_NAME,
         L1.PREFIX AS LOCALITY_LEGAL_PREFIX,
         S2.NAME AS STREET_POST_NAME,
         S2.PREFIX AS STREET_POST_PREFIX,
         L2.LOCALITY_ID AS LOCALITY_POST_ID,
         L2.NAME AS LOCALITY_POST_NAME,
         L2.PREFIX AS LOCALITY_POST_PREFIX
    FROM /*PREFIX*/FIRMS F
    JOIN /*PREFIX*/FIRM_TYPES FT ON FT.FIRM_TYPE_ID=F.FIRM_TYPE_ID
    LEFT JOIN /*PREFIX*/STREETS S1 ON S1.STREET_ID=F.STREET_LEGAL_ID
    LEFT JOIN /*PREFIX*/LOCALITIES L1 ON L1.LOCALITY_ID=S1.LOCALITY_ID
    LEFT JOIN /*PREFIX*/STREETS S2 ON S2.STREET_ID=F.STREET_POST_ID
    LEFT JOIN /*PREFIX*/LOCALITIES L2 ON L2.LOCALITY_ID=S2.LOCALITY_ID
    LEFT JOIN /*PREFIX*/FIRMS F1 ON F1.FIRM_ID=F.PARENT_ID


--

/* Создание процедуры добавления предприятия */

CREATE PROCEDURE /*PREFIX*/I_FIRM
(
  IN FIRM_ID VARCHAR(32),
  IN FIRM_TYPE_ID VARCHAR(32),
  IN PARENT_ID VARCHAR(32),
  IN SMALL_NAME VARCHAR(250),
  IN FULL_NAME VARCHAR(250),
  IN INN VARCHAR(12),
  IN PAYMENT_ACCOUNT VARCHAR(20),
  IN BANK VARCHAR(250),
  IN BIK VARCHAR(20),
  IN CORR_ACCOUNT VARCHAR(20),
  IN PHONE VARCHAR(250),
  IN FAX VARCHAR(250),
  IN EMAIL VARCHAR(100),
  IN SITE VARCHAR(100),
  IN OKONH VARCHAR(20),
  IN OKPO VARCHAR(20),
  IN KPP VARCHAR(20),
  IN DIRECTOR VARCHAR(250),
  IN ACCOUNTANT VARCHAR(250),
  IN CONTACT_FACE VARCHAR(250),
  IN INDEX_LEGAL VARCHAR(10),
  IN STREET_LEGAL_ID VARCHAR(32),
  IN HOUSE_LEGAL VARCHAR(10),
  IN FLAT_LEGAL VARCHAR(10),
  IN INDEX_POST VARCHAR(10),
  IN STREET_POST_ID VARCHAR(32),
  IN HOUSE_POST VARCHAR(10),
  IN FLAT_POST VARCHAR(10)
)
BEGIN
  INSERT INTO /*PREFIX*/FIRMS (FIRM_ID,FIRM_TYPE_ID,PARENT_ID,SMALL_NAME,FULL_NAME,INN,PAYMENT_ACCOUNT,
                               BANK,BIK,CORR_ACCOUNT,PHONE,FAX,EMAIL,SITE,OKONH,OKPO,KPP,DIRECTOR,ACCOUNTANT,
                               CONTACT_FACE,INDEX_LEGAL,STREET_LEGAL_ID,HOUSE_LEGAL,FLAT_LEGAL,
                               INDEX_POST,STREET_POST_ID,HOUSE_POST,FLAT_POST)
       VALUES (FIRM_ID,FIRM_TYPE_ID,PARENT_ID,SMALL_NAME,FULL_NAME,INN,PAYMENT_ACCOUNT,
               BANK,BIK,CORR_ACCOUNT,PHONE,FAX,EMAIL,SITE,OKONH,OKPO,KPP,DIRECTOR,ACCOUNTANT,
               CONTACT_FACE,INDEX_LEGAL,STREET_LEGAL_ID,HOUSE_LEGAL,FLAT_LEGAL,
               INDEX_POST,STREET_POST_ID,HOUSE_POST,FLAT_POST);
END;

--

/* Создание процедуры изменения предприятия */

CREATE PROCEDURE /*PREFIX*/U_FIRM
(
  IN FIRM_ID VARCHAR(32),
  IN FIRM_TYPE_ID VARCHAR(32),
  IN PARENT_ID VARCHAR(32),
  IN SMALL_NAME VARCHAR(250),
  IN FULL_NAME VARCHAR(250),
  IN INN VARCHAR(12),
  IN PAYMENT_ACCOUNT VARCHAR(20),
  IN BANK VARCHAR(250),
  IN BIK VARCHAR(20),
  IN CORR_ACCOUNT VARCHAR(20),
  IN PHONE VARCHAR(250),
  IN FAX VARCHAR(250),
  IN EMAIL VARCHAR(100),
  IN SITE VARCHAR(100),
  IN OKONH VARCHAR(20),
  IN OKPO VARCHAR(20),
  IN KPP VARCHAR(20),
  IN DIRECTOR VARCHAR(250),
  IN ACCOUNTANT VARCHAR(250),
  IN CONTACT_FACE VARCHAR(250),
  IN INDEX_LEGAL VARCHAR(10),
  IN STREET_LEGAL_ID VARCHAR(32),
  IN HOUSE_LEGAL VARCHAR(10),
  IN FLAT_LEGAL VARCHAR(10),
  IN INDEX_POST VARCHAR(10),
  IN STREET_POST_ID VARCHAR(32),
  IN HOUSE_POST VARCHAR(10),
  IN FLAT_POST VARCHAR(10),
  IN OLD_FIRM_ID VARCHAR(32)
)
BEGIN
  UPDATE /*PREFIX*/FIRMS F
     SET F.FIRM_ID=FIRM_ID,
         F.FIRM_TYPE_ID=FIRM_TYPE_ID,
         F.PARENT_ID=PARENT_ID,
         F.SMALL_NAME=SMALL_NAME,
         F.FULL_NAME=FULL_NAME,
         F.INN=INN,
         F.PAYMENT_ACCOUNT=PAYMENT_ACCOUNT,
         F.BANK=BANK,
         F.BIK=BIK,
         F.CORR_ACCOUNT=CORR_ACCOUNT,
         F.PHONE=PHONE,
         F.FAX=FAX,
         F.EMAIL=EMAIL,
         F.SITE=SITE,
         F.OKONH=OKONH,
         F.OKPO=OKPO,
         F.KPP=KPP,
         F.DIRECTOR=DIRECTOR,
         F.ACCOUNTANT=ACCOUNTANT,
         F.CONTACT_FACE=CONTACT_FACE,
         F.INDEX_LEGAL=INDEX_LEGAL,
         F.STREET_LEGAL_ID=STREET_LEGAL_ID,
         F.HOUSE_LEGAL=HOUSE_LEGAL,
         F.FLAT_LEGAL=FLAT_LEGAL,
         F.INDEX_POST=INDEX_POST,
         F.STREET_POST_ID=STREET_POST_ID,
         F.HOUSE_POST=HOUSE_POST,
         F.FLAT_POST=FLAT_POST
   WHERE F.FIRM_ID=OLD_FIRM_ID;
END;

--

/* Создание процедуры удаления предприятия */

CREATE PROCEDURE /*PREFIX*/D_FIRM
(
  IN OLD_FIRM_ID VARCHAR(32)
)
BEGIN
  DELETE FROM /*PREFIX*/FIRMS
        WHERE FIRM_ID=OLD_FIRM_ID;
END;

--