/* Создание таблицы профилей */

CREATE TABLE /*PREFIX*/PROFILES
(
  ACCOUNT_ID VARCHAR(32) NOT NULL,
	APPLICATION_ID VARCHAR(32) NOT NULL,
  PROFILE LONGBLOB,
  PRIMARY KEY (ACCOUNT_ID,APPLICATION_ID),
  FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS (ACCOUNT_ID),
  FOREIGN KEY (APPLICATION_ID) REFERENCES APPLICATIONS (APPLICATION_ID)
)

--

/* Создание просмотра таблицы профилей */

CREATE VIEW /*PREFIX*/S_PROFILES
AS
SELECT P.*,
       AC.USER_NAME AS USER_NAME,
			 AP.NAME AS APPLICATION_NAME
  FROM /*PREFIX*/PROFILES P
	JOIN /*PREFIX*/ACCOUNTS AC ON AC.ACCOUNT_ID=P.ACCOUNT_ID
	JOIN /*PREFIX*/APPLICATIONS AP ON AP.APPLICATION_ID=P.APPLICATION_ID
			
--

/* Создание процедуры добавления профиля */

CREATE PROCEDURE /*PREFIX*/I_PROFILE
(
  IN ACCOUNT_ID VARCHAR(32),
  IN APPLICATION_ID VARCHAR(32),
  IN PROFILE LONGBLOB
)
BEGIN
  INSERT INTO /*PREFIX*/PROFILES (ACCOUNT_ID,APPLICATION_ID,PROFILE)
       VALUES (ACCOUNT_ID,APPLICATION_ID,PROFILE);
END;

--

/* Создание процедуры изменения профиля */

CREATE PROCEDURE /*PREFIX*/U_PROFILE
(
  IN ACCOUNT_ID VARCHAR(32),
  IN APPLICATION_ID VARCHAR(32),
  IN PROFILE LONGBLOB,
  IN OLD_ACCOUNT_ID VARCHAR(32),
  IN OLD_APPLICATION_ID VARCHAR(32)
)
BEGIN
  UPDATE /*PREFIX*/PROFILES P
     SET P.ACCOUNT_ID=ACCOUNT_ID,
         P.APPLICATION_ID=APPLICATION_ID,
         P.PROFILE=PROFILE
   WHERE P.ACCOUNT_ID=OLD_ACCOUNT_ID
	   AND P.APPLICATION_ID=OLD_APPLICATION_ID;
END;

--

/* Создание процедуры удаления профиля */

CREATE PROCEDURE /*PREFIX*/D_PROFILE
(
  IN OLD_ACCOUNT_ID VARCHAR(32),
	IN OLD_APPLICATION_ID VARCHAR(32)
)
BEGIN
  DELETE FROM /*PREFIX*/PROFILES 
        WHERE ACCOUNT_ID=OLD_ACCOUNT_ID
				  AND APPLICATION_ID=OLD_APPLICATION_ID;
END;

--