/* Создание таблицы ролей пользователя */

CREATE TABLE /*PREFIX*/ACCOUNT_ROLES
(
  ROLE_ID VARCHAR(32) NOT NULL,
	ACCOUNT_ID VARCHAR(32) NOT NULL,
  PRIMARY KEY (ROLE_ID,ACCOUNT_ID),
  FOREIGN KEY (ROLE_ID) REFERENCES /*PREFIX*/ACCOUNTS (ACCOUNT_ID),
  FOREIGN KEY (ACCOUNT_ID) REFERENCES /*PREFIX*/ACCOUNTS (ACCOUNT_ID)
)

--

/* Создание просмотра таблицы ролей пользователя */

CREATE VIEW /*PREFIX*/S_ACCOUNT_ROLES
AS
SELECT AP.*,
       R.USER_NAME AS ROLE_NAME,
			 A.USER_NAME AS USER_NAME
  FROM /*PREFIX*/ACCOUNT_ROLES AP
	JOIN /*PREFIX*/ACCOUNTS R ON R.ACCOUNT_ID=AP.ROLE_ID
	JOIN /*PREFIX*/ACCOUNTS A ON A.ACCOUNT_ID=AP.ACCOUNT_ID
			
--

/* Создание процедуры добавления роли пользователю */

CREATE PROCEDURE /*PREFIX*/I_ACCOUNT_ROLE
(
  IN ROLE_ID VARCHAR(32),
  IN ACCOUNT_ID VARCHAR(32)
)
BEGIN
  INSERT INTO /*PREFIX*/ACCOUNT_ROLES (ROLE_ID,ACCOUNT_ID)
       VALUES (ROLE_ID,ACCOUNT_ID);
END;

--

/* Создание процедуры изменения роли у пользователя */

CREATE PROCEDURE /*PREFIX*/U_ACCOUNT_ROLE
(
  IN ROLE_ID VARCHAR(32),
  IN ACCOUNT_ID VARCHAR(32),
  IN OLD_ROLE_ID VARCHAR(32),
  IN OLD_ACCOUNT_ID VARCHAR(32)
)
BEGIN
  UPDATE /*PREFIX*/ACCOUNT_ROLES AR
     SET AR.ROLE_ID=ROLE_ID,
         AR.ACCOUNT_ID=ACCOUNT_ID
   WHERE AR.ROLE_ID=OLD_ROLE_ID
	   AND AR.ACCOUNT_ID=OLD_ACCOUNT_ID;
END;

--

/* Создание процедуры удаления роли у пользователя */

CREATE PROCEDURE /*PREFIX*/D_ACCOUNT_ROLE
(
  IN OLD_ROLE_ID VARCHAR(32),
	IN OLD_ACCOUNT_ID VARCHAR(32)
)
BEGIN
  DELETE FROM /*PREFIX*/ACCOUNT_ROLES 
        WHERE ROLE_ID=OLD_ROLE_ID
				  AND ACCOUNT_ID=OLD_ACCOUNT_ID;
END;

--