/* Создание таблицы отчетов */

CREATE TABLE /*PREFIX*/REPORTS
(
  REPORT_ID VARCHAR(32) NOT NULL,
  ENGINE VARCHAR(100) NOT NULL,
  REPORT LONGBLOB NOT NULL,
  PLACE INTEGER NOT NULL,
  PRIMARY KEY (REPORT_ID),
  FOREIGN KEY (REPORT_ID) REFERENCES /*PREFIX*/INTERFACES (INTERFACE_ID)
)

--

/* Создание просмотра таблицы заданий */

CREATE VIEW /*PREFIX*/S_REPORTS
AS
  SELECT R.*, 
         I.NAME AS INTERFACE_NAME
    FROM /*PREFIX*/REPORTS R
    JOIN /*PREFIX*/INTERFACES I ON I.INTERFACE_ID=R.REPORT_ID

--

/* Создание процедуры добавления задания */

CREATE PROCEDURE /*PREFIX*/I_REPORT
(
  IN REPORT_ID VARCHAR(32),
  IN NAME VARCHAR(100),
  IN DESCRIPTION VARCHAR(250),
  IN INTERFACE_TYPE INTEGER,
  IN ENGINE VARCHAR(100),
  IN REPORT BLOB,
  IN PLACE INTEGER
)
BEGIN
  INSERT INTO /*PREFIX*/INTERFACES (INTERFACE_ID,NAME,DESCRIPTION,INTERFACE_TYPE,MODULE_NAME,MODULE_INTERFACE)
       VALUES (REPORT_ID,NAME,DESCRIPTION,INTERFACE_TYPE,NULL,NULL);
  
    INSERT INTO /*PREFIX*/REPORTS (REPORT_ID,ENGINE,REPORT,PLACE)
       VALUES (REPORT_ID,ENGINE,REPORT,PLACE);
                 
END;

--

/* Создание процедуры изменения задания */

CREATE PROCEDURE /*PREFIX*/U_REPORT
(
  IN REPORT_ID VARCHAR(32),
  IN NAME VARCHAR(100),
  IN DESCRIPTION VARCHAR(250),
  IN INTERFACE_TYPE INTEGER,
  IN ENGINE VARCHAR(100),
  IN REPORT BLOB,
  IN PLACE INTEGER,
  IN OLD_REPORT_ID VARCHAR(32)
)
BEGIN
  UPDATE /*PREFIX*/INTERFACES I
       SET I.INTERFACE_ID=REPORT_ID,
           I.NAME=NAME,
           I.DESCRIPTION=DESCRIPTION
     WHERE I.INTERFACE_ID=OLD_REPORT_ID;
  
  UPDATE /*PREFIX*/REPORTS R
     SET R.REPORT_ID=REPORT_ID,
         R.ENGINE=ENGINE,
         R.REPORT=REPORT,
         R.PLACE=PLACE
   WHERE R.REPORT_ID=OLD_REPORT_ID;
     
END;

--

/* Создание процедуры удаления задания */

CREATE PROCEDURE /*PREFIX*/D_REPORT
(
  IN OLD_REPORT_ID VARCHAR(32)
)
BEGIN
  DELETE FROM /*PREFIX*/REPORTS
        WHERE REPORT_ID=OLD_REPORT_ID;
  
  DELETE FROM /*PREFIX*/INTERFACES
        WHERE INTERFACE_ID=OLD_REPORT_ID;
END;

--