/* Создание таблицы прав интерфейсов */

CREATE TABLE /*PREFIX*/PERMISSIONS
(
  PERMISSION_ID VARCHAR(32) NOT NULL,
  ACCOUNT_ID VARCHAR(32) NOT NULL,
  INTERFACE_ID VARCHAR(32) NOT NULL,
	RIGHT_ACCESS VARCHAR(250) NOT NULL,
	VALUE VARCHAR(250) NOT NULL,
  PRIMARY KEY (PERMISSION_ID),
  FOREIGN KEY (ACCOUNT_ID) REFERENCES /*PREFIX*/ACCOUNTS (ACCOUNT_ID),
  FOREIGN KEY (INTERFACE_ID) REFERENCES /*PREFIX*/INTERFACES (INTERFACE_ID)
)

--

/* Создание просмотра таблицы прав интерфейсов */

CREATE VIEW /*PREFIX*/S_PERMISSIONS
AS
   SELECT P.*, 
          A.USER_NAME AS USER_NAME,
          I.NAME AS INTERFACE_NAME
     FROM /*PREFIX*/PERMISSIONS P
     JOIN /*PREFIX*/ACCOUNTS A ON A.ACCOUNT_ID=P.ACCOUNT_ID
		 JOIN /*PREFIX*/INTERFACES I ON I.INTERFACE_ID=P.INTERFACE_ID

--

/* Создание процедуры добавления права */

CREATE PROCEDURE /*PREFIX*/I_PERMISSION
(
  IN PERMISSION_ID VARCHAR(32),
  IN ACCOUNT_ID VARCHAR(32),
	IN INTERFACE_ID VARCHAR(32),
  IN RIGHT_ACCESS VARCHAR(250),
	IN VALUE VARCHAR(250)
)
BEGIN
  INSERT INTO /*PREFIX*/PERMISSIONS (PERMISSION_ID,ACCOUNT_ID,INTERFACE_ID,RIGHT_ACCESS,VALUE)
       VALUES (PERMISSION_ID,ACCOUNT_ID,INTERFACE_ID,RIGHT_ACCESS,VALUE);
END;

--

/* Создание процедуры изменения права */

CREATE PROCEDURE /*PREFIX*/U_PERMISSION
(
  IN PERMISSION_ID VARCHAR(32),
  IN ACCOUNT_ID VARCHAR(32),
	IN INTERFACE_ID VARCHAR(32),
  IN RIGHT_ACCESS VARCHAR(250),
	IN VALUE VARCHAR(250),
  IN OLD_PERMISSION_ID VARCHAR(32)
)
BEGIN
  UPDATE /*PREFIX*/PERMISSIONS P
     SET P.PERMISSION_ID=PERMISSION_ID,
         P.ACCOUNT_ID=ACCOUNT_ID,
         P.INTERFACE_ID=INTERFACE_ID,
         P.RIGHT_ACCESS=RIGHT_ACCESS,
				 P.VALUE=VALUE
   WHERE P.PERMISSION_ID=OLD_PERMISSION_ID;
END;

--

/* Создание процедуры удаления права */

CREATE PROCEDURE /*PREFIX*/D_PERMISSION
(
  IN OLD_PERMISSION_ID VARCHAR(32)
)
BEGIN
  DELETE FROM /*PREFIX*/PERMISSIONS
        WHERE PERMISSION_ID=OLD_PERMISSION_ID;
END;

--