/* Создание таблицы блокировок */

CREATE TABLE /*PREFIX*/LOCKS
(
  LOCK_ID VARCHAR(32) NOT NULL,
  APPLICATION_ID VARCHAR(32) NOT NULL,
  ACCOUNT_ID VARCHAR(32),
  DATE_BEGIN DATETIME NOT NULL,
  DATE_END DATETIME,
  METHOD VARCHAR(100),
  OBJECT VARCHAR(100),
  DESCRIPTION VARCHAR(250),
  IP_LIST VARCHAR(1000),
  PRIMARY KEY (LOCK_ID),
  FOREIGN KEY (APPLICATION_ID) REFERENCES /*PREFIX*/APPLICATIONS (APPLICATION_ID),
  FOREIGN KEY (ACCOUNT_ID) REFERENCES /*PREFIX*/ACCOUNTS (ACCOUNT_ID)
)

--

/* Создание просмотра таблицы блокировок */

CREATE VIEW /*PREFIX*/S_LOCKS
AS
  SELECT L.*,
         A.NAME AS APPLICATION_NAME,
         AC.USER_NAME
    FROM /*PREFIX*/LOCKS L
    JOIN /*PREFIX*/APPLICATIONS A ON A.APPLICATION_ID=L.APPLICATION_ID
    LEFT JOIN /*PREFIX*/ACCOUNTS AC ON AC.ACCOUNT_ID=L.ACCOUNT_ID

--

/* Создание процедуры добавления блокировки */

CREATE PROCEDURE /*PREFIX*/I_LOCK
(
  IN LOCK_ID VARCHAR(32),
  IN APPLICATION_ID VARCHAR(32),
  IN ACCOUNT_ID VARCHAR(32),
  IN DATE_BEGIN DATETIME,
  IN DATE_END DATETIME,
  IN METHOD VARCHAR(100),
  IN OBJECT VARCHAR(100),
  IN DESCRIPTION VARCHAR(250),
  IN IP_LIST VARCHAR(1000)
)
BEGIN
  INSERT INTO /*PREFIX*/LOCKS (LOCK_ID,APPLICATION_ID,ACCOUNT_ID,DATE_BEGIN,DATE_END,METHOD,OBJECT,DESCRIPTION,IP_LIST)
       VALUES (LOCK_ID,APPLICATION_ID,ACCOUNT_ID,DATE_BEGIN,DATE_END,METHOD,OBJECT,DESCRIPTION,IP_LIST);
END;

--

/* Создание процедуры изменения блокировки */

CREATE PROCEDURE /*PREFIX*/U_LOCK
(
  IN LOCK_ID VARCHAR(32),
  IN APPLICATION_ID VARCHAR(32),
  IN ACCOUNT_ID VARCHAR(32),
  IN DATE_BEGIN DATETIME,
  IN DATE_END DATETIME,
  IN METHOD VARCHAR(100),
  IN OBJECT VARCHAR(100),
  IN DESCRIPTION VARCHAR(250),
  IN IP_LIST VARCHAR(1000),
  IN OLD_LOCK_ID VARCHAR(32)
)
BEGIN
  UPDATE /*PREFIX*/LOCKS L
     SET L.LOCK_ID=LOCK_ID,
         L.APPLICATION_ID=APPLICATION_ID,
         L.ACCOUNT_ID=ACCOUNT_ID,
         L.DATE_BEGIN=DATE_BEGIN,
         L.DATE_END=DATE_END,
         L.METHOD=METHOD,
         L.OBJECT=OBJECT,
         L.DESCRIPTION=DESCRIPTION,
         L.IP_LIST=IP_LIST
   WHERE L.LOCK_ID=OLD_LOCK_ID;
END;

--

/* Создание процедуры удаления блокировки */

CREATE PROCEDURE /*PREFIX*/D_LOCK
(
  IN OLD_LOCK_ID VARCHAR(32)
)
BEGIN
  DELETE FROM /*PREFIX*/LOCKS
        WHERE LOCK_ID=OLD_LOCK_ID;
END;

--
