/* Создание таблицы заданий */

CREATE TABLE /*PREFIX*/TASKS
(
  TASK_ID VARCHAR(32) NOT NULL,
  APPLICATION_ID VARCHAR(32) NOT NULL,
  ACCOUNT_ID VARCHAR(32),
  INTERFACE_ID VARCHAR(32),
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(250),
  DATE_BEGIN DATETIME NOT NULL,
  DATE_END DATETIME,
  SCHEDULE INTEGER NOT NULL,
  PRIORITY INTEGER NOT NULL,
  ENABLED INTEGER NOT NULL,
  PROC_NAME VARCHAR(100),
  COMMAND_STRING VARCHAR(250),
  REPEAT_ENABLED INTEGER NOT NULL,
  REPEAT_TYPE INTEGER,
  REPEAT_VALUE INTEGER,
  REPEAT_COUNT INTEGER,
  DAY_FREQUENCY INTEGER,
  WEEK_FREQUENCY INTEGER,
  MONDAY INTEGER NOT NULL,
  TUESDAY INTEGER NOT NULL,
  WEDNESDAY INTEGER NOT NULL,
  THURSDAY INTEGER NOT NULL,
  FRIDAY INTEGER NOT NULL,
  SATURDAY INTEGER NOT NULL,
  SUNDAY INTEGER NOT NULL,
  MONTH_DAY INTEGER,
  JANUARY INTEGER NOT NULL,
  FEBRUARY INTEGER NOT NULL,
  MARCH INTEGER NOT NULL,
  APRIL INTEGER NOT NULL,
  MAY INTEGER NOT NULL,
  JUNE INTEGER NOT NULL,
  JULY INTEGER NOT NULL,
  AUGUST INTEGER NOT NULL,
  SEPTEMBER INTEGER NOT NULL,
  OCTOBER INTEGER NOT NULL,
  NOVEMBER INTEGER NOT NULL,
  DECEMBER INTEGER NOT NULL,
  DATE_EXECUTE DATETIME,
  RESULT_STRING VARCHAR(250),
  PRIMARY KEY (TASK_ID),
  FOREIGN KEY (APPLICATION_ID) REFERENCES /*PREFIX*/APPLICATIONS (APPLICATION_ID),
  FOREIGN KEY (ACCOUNT_ID) REFERENCES /*PREFIX*/ACCOUNTS (ACCOUNT_ID),
  FOREIGN KEY (INTERFACE_ID) REFERENCES /*PREFIX*/INTERFACES (INTERFACE_ID)
)

--

/* Создание просмотра таблицы заданий */

CREATE VIEW /*PREFIX*/S_TASKS
AS
  SELECT T.*,
         A.NAME AS APPLICATION_NAME,
         AC.USER_NAME,
         I.NAME AS INTERFACE_NAME
    FROM /*PREFIX*/TASKS T
    JOIN /*PREFIX*/APPLICATIONS A ON A.APPLICATION_ID=T.APPLICATION_ID
    LEFT JOIN /*PREFIX*/ACCOUNTS AC ON AC.ACCOUNT_ID=T.ACCOUNT_ID
    LEFT JOIN /*PREFIX*/INTERFACES I ON I.INTERFACE_ID=T.INTERFACE_ID

--

/* Создание процедуры добавления задания */

CREATE PROCEDURE /*PREFIX*/I_TASK
(
  IN TASK_ID VARCHAR(32),
  IN APPLICATION_ID VARCHAR(32),
  IN ACCOUNT_ID VARCHAR(32),
  IN INTERFACE_ID VARCHAR(32),
  IN NAME VARCHAR(100),
  IN DESCRIPTION VARCHAR(250),
  IN DATE_BEGIN DATETIME,
  IN DATE_END DATETIME,
  IN SCHEDULE INTEGER,
  IN PRIORITY INTEGER,
  IN ENABLED INTEGER,
  IN PROC_NAME VARCHAR(100),
  IN COMMAND_STRING VARCHAR(250),
  IN REPEAT_ENABLED INTEGER,
  IN REPEAT_TYPE INTEGER,
  IN REPEAT_VALUE INTEGER,
  IN REPEAT_COUNT INTEGER,
  IN DAY_FREQUENCY INTEGER,
  IN WEEK_FREQUENCY INTEGER,
  IN MONDAY INTEGER,
  IN TUESDAY INTEGER,
  IN WEDNESDAY INTEGER,
  IN THURSDAY INTEGER,
  IN FRIDAY INTEGER,
  IN SATURDAY INTEGER,
  IN SUNDAY INTEGER,
  IN MONTH_DAY INTEGER,
  IN JANUARY INTEGER,
  IN FEBRUARY INTEGER,
  IN MARCH INTEGER,
  IN APRIL INTEGER,
  IN MAY INTEGER,
  IN JUNE INTEGER,
  IN JULY INTEGER,
  IN AUGUST INTEGER,
  IN SEPTEMBER INTEGER,
  IN OCTOBER INTEGER,
  IN NOVEMBER INTEGER,
  IN DECEMBER INTEGER,
  IN DATE_EXECUTE DATETIME,
  IN RESULT_STRING VARCHAR(250)
)
BEGIN
  INSERT INTO /*PREFIX*/TASKS (TASK_ID,APPLICATION_ID,ACCOUNT_ID,INTERFACE_ID,NAME,DESCRIPTION,DATE_BEGIN,
                               DATE_END,SCHEDULE,PRIORITY,ENABLED,PROC_NAME,COMMAND_STRING,REPEAT_ENABLED,
                               REPEAT_TYPE,REPEAT_VALUE,REPEAT_COUNT,DAY_FREQUENCY,WEEK_FREQUENCY,
                               MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY,SUNDAY,MONTH_DAY,
                               JANUARY,FEBRUARY,MARCH,APRIL,MAY,JUNE,JULY,AUGUST,SEPTEMBER,OCTOBER,NOVEMBER,DECEMBER,
                               DATE_EXECUTE,RESULT_STRING)
       VALUES (TASK_ID,APPLICATION_ID,ACCOUNT_ID,INTERFACE_ID,NAME,DESCRIPTION,DATE_BEGIN,
               DATE_END,SCHEDULE,PRIORITY,ENABLED,PROC_NAME,COMMAND_STRING,REPEAT_ENABLED,
               REPEAT_TYPE,REPEAT_VALUE,REPEAT_COUNT,DAY_FREQUENCY,WEEK_FREQUENCY,
               MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY,SUNDAY,MONTH_DAY,
               JANUARY,FEBRUARY,MARCH,APRIL,MAY,JUNE,JULY,AUGUST,SEPTEMBER,OCTOBER,NOVEMBER,DECEMBER,
               DATE_EXECUTE,RESULT_STRING);
END;

--

/* Создание процедуры изменения задания */

CREATE PROCEDURE /*PREFIX*/U_TASK
(
  IN TASK_ID VARCHAR(32),
  IN APPLICATION_ID VARCHAR(32),
  IN ACCOUNT_ID VARCHAR(32),
  IN INTERFACE_ID VARCHAR(32),
  IN NAME VARCHAR(100),
  IN DESCRIPTION VARCHAR(250),
  IN DATE_BEGIN DATETIME,
  IN DATE_END DATETIME,
  IN SCHEDULE INTEGER,
  IN PRIORITY INTEGER,
  IN ENABLED INTEGER,
  IN PROC_NAME VARCHAR(100),
  IN COMMAND_STRING VARCHAR(250),
  IN REPEAT_ENABLED INTEGER,
  IN REPEAT_TYPE INTEGER,
  IN REPEAT_VALUE INTEGER,
  IN REPEAT_COUNT INTEGER,
  IN DAY_FREQUENCY INTEGER,
  IN WEEK_FREQUENCY INTEGER,
  IN MONDAY INTEGER,
  IN TUESDAY INTEGER,
  IN WEDNESDAY INTEGER,
  IN THURSDAY INTEGER,
  IN FRIDAY INTEGER,
  IN SATURDAY INTEGER,
  IN SUNDAY INTEGER,
  IN MONTH_DAY INTEGER,
  IN JANUARY INTEGER,
  IN FEBRUARY INTEGER,
  IN MARCH INTEGER,
  IN APRIL INTEGER,
  IN MAY INTEGER,
  IN JUNE INTEGER,
  IN JULY INTEGER,
  IN AUGUST INTEGER,
  IN SEPTEMBER INTEGER,
  IN OCTOBER INTEGER,
  IN NOVEMBER INTEGER,
  IN DECEMBER INTEGER,
  IN DATE_EXECUTE DATETIME,
  IN RESULT_STRING VARCHAR(250),
  IN OLD_TASK_ID VARCHAR(32)
)
BEGIN
  UPDATE /*PREFIX*/TASKS T
     SET T.TASK_ID=TASK_ID,
         T.APPLICATION_ID=APPLICATION_ID,
         T.ACCOUNT_ID=ACCOUNT_ID,
         T.INTERFACE_ID=INTERFACE_ID,
         T.NAME=NAME,
         T.DESCRIPTION=DESCRIPTION,
         T.DATE_BEGIN=DATE_BEGIN,
         T.DATE_END=DATE_END,
         T.SCHEDULE=SCHEDULE,
         T.PRIORITY=PRIORITY,
         T.ENABLED=ENABLED,
         T.PROC_NAME=PROC_NAME,
         T.COMMAND_STRING=COMMAND_STRING,
         T.REPEAT_ENABLED=REPEAT_ENABLED,
         T.REPEAT_TYPE=REPEAT_TYPE,
         T.REPEAT_VALUE=REPEAT_VALUE,
         T.REPEAT_COUNT=REPEAT_COUNT,
         T.DAY_FREQUENCY=DAY_FREQUENCY,
         T.WEEK_FREQUENCY=WEEK_FREQUENCY,
         T.MONDAY=MONDAY,
         T.TUESDAY=TUESDAY,
         T.WEDNESDAY=WEDNESDAY,
         T.THURSDAY=THURSDAY,
         T.FRIDAY=FRIDAY,
         T.SATURDAY=SATURDAY,
         T.SUNDAY=SUNDAY,
         T.MONTH_DAY=MONTH_DAY,
         T.JANUARY=JANUARY,
         T.FEBRUARY=FEBRUARY,
         T.MARCH=MARCH,
         T.APRIL=APRIL,
         T.MAY=MAY,
         T.JUNE=JUNE,
         T.JULY=JULY,
         T.AUGUST=AUGUST,
         T.SEPTEMBER=SEPTEMBER,
         T.OCTOBER=OCTOBER,
         T.NOVEMBER=NOVEMBER,
         T.DECEMBER=DECEMBER,
         T.DATE_EXECUTE=DATE_EXECUTE,
         T.RESULT_STRING=RESULT_STRING
   WHERE T.TASK_ID=OLD_TASK_ID;
END;

--

/* Создание процедуры удаления задания */

CREATE PROCEDURE /*PREFIX*/D_TASK
(
  IN OLD_TASK_ID VARCHAR(32)
)
BEGIN
  DELETE FROM /*PREFIX*/TASKS
        WHERE TASK_ID=OLD_TASK_ID;
END;

--
