/* Создание таблицы обмена */

CREATE TABLE /*PREFIX*/EXCHANGES
(
  EXCHANGE_ID VARCHAR(32) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(250),
  SCRIPT LONGBLOB,
  SOURCE VARCHAR(100) NOT NULL,
  SOURCE_BEFORE LONGBLOB,
  SOURCE_AFTER LONGBLOB,
  DESTINATION VARCHAR(100) NOT NULL,
  DESTINATION_BEFORE LONGBLOB,
  DESTINATION_AFTER LONGBLOB,
  PRIORITY INTEGER,
  ENABLED INTEGER NOT NULL,
  PRIMARY KEY (EXCHANGE_ID)
)

--

/* Создание просмотра таблицы обмена */

CREATE VIEW /*PREFIX*/S_EXCHANGES
AS
  SELECT *
    FROM /*PREFIX*/EXCHANGES

--

/* Создание процедуры добавления обмена */

CREATE PROCEDURE /*PREFIX*/I_EXCHANGE
(
  IN EXCHANGE_ID VARCHAR(32),
  IN NAME VARCHAR(100),
  IN DESCRIPTION VARCHAR(250),
  IN SCRIPT LONGBLOB,
  IN SOURCE VARCHAR(100),
  IN SOURCE_BEFORE LONGBLOB,
  IN SOURCE_AFTER LONGBLOB,
  IN DESTINATION VARCHAR(100),
  IN DESTINATION_BEFORE LONGBLOB,
  IN DESTINATION_AFTER LONGBLOB,
  IN PRIORITY INTEGER,
  IN ENABLED INTEGER
)
BEGIN
  INSERT INTO /*PREFIX*/EXCHANGES (EXCHANGE_ID,NAME,DESCRIPTION,SCRIPT,
                                   SOURCE,SOURCE_BEFORE,SOURCE_AFTER,
                                   DESTINATION,DESTINATION_BEFORE,DESTINATION_AFTER,
                                   PRIORITY,ENABLED)
       VALUES (EXCHANGE_ID,NAME,DESCRIPTION,SCRIPT,
               SOURCE,SOURCE_BEFORE,SOURCE_AFTER,
               DESTINATION,DESTINATION_BEFORE,DESTINATION_AFTER,
               PRIORITY,ENABLED);
END;

--

/* Создание процедуры изменения обмена */

CREATE PROCEDURE /*PREFIX*/U_EXCHANGE
(
  IN EXCHANGE_ID VARCHAR(32),
  IN NAME VARCHAR(100),
  IN DESCRIPTION VARCHAR(250),
  IN SCRIPT LONGBLOB,
  IN SOURCE VARCHAR(100),
  IN SOURCE_BEFORE LONGBLOB,
  IN SOURCE_AFTER LONGBLOB,
  IN DESTINATION VARCHAR(100),
  IN DESTINATION_BEFORE LONGBLOB,
  IN DESTINATION_AFTER LONGBLOB,
  IN PRIORITY INTEGER,
  IN ENABLED INTEGER,
  IN OLD_EXCHANGE_ID VARCHAR(32)
)
BEGIN
  UPDATE /*PREFIX*/EXCHANGES E
     SET E.EXCHANGE_ID=EXCHANGE_ID,
         E.NAME=NAME,
         E.DESCRIPTION=DESCRIPTION,
         E.SCRIPT=SCRIPT,
         E.SOURCE=SOURCE,
         E.SOURCE_BEFORE=SOURCE_BEFORE,
         E.SOURCE_AFTER=SOURCE_AFTER,
         E.DESTINATION=DESTINATION,
         E.DESTINATION_BEFORE=DESTINATION_BEFORE,
         E.DESTINATION_AFTER=DESTINATION_AFTER,
         E.PRIORITY=PRIORITY,
         E.ENABLED=ENABLED
   WHERE E.EXCHANGE_ID=OLD_EXCHANGE_ID;
END;

--

/* Создание процедуры удаления обмена */

CREATE PROCEDURE /*PREFIX*/D_EXCHANGE
(
  IN OLD_EXCHANGE_ID VARCHAR(32)
)
BEGIN
  DELETE FROM /*PREFIX*/EXCHANGES
        WHERE EXCHANGE_ID=OLD_EXCHANGE_ID;
END;

--
