/* Создание таблицы оповещений */

CREATE TABLE /*PREFIX*/ALARMS
(
  ALARM_ID VARCHAR(32) NOT NULL,
  RECIPIENT_ID VARCHAR(32),
  TYPE_ALARM INTEGER NOT NULL,
  DATE_BEGIN DATETIME NOT NULL,
  DATE_END DATETIME,
  CAPTION VARCHAR(100) NOT NULL,
  TEXT_ALARM VARCHAR(4000) NOT NULL,
  SENDER_ID VARCHAR(32) NOT NULL,
  PRIMARY KEY (ALARM_ID),
  FOREIGN KEY (RECIPIENT_ID) REFERENCES /*PREFIX*/ACCOUNTS (ACCOUNT_ID),
  FOREIGN KEY (SENDER_ID) REFERENCES /*PREFIX*/ACCOUNTS (ACCOUNT_ID)
)

--

/* Создание просмотра оповещений */

CREATE VIEW /*PREFIX*/S_ALARMS
AS
SELECT A.*,
       A1.USER_NAME AS SENDER_NAME,
       A2.USER_NAME AS RECIPIENT_NAME
  FROM /*PREFIX*/ALARMS A
  JOIN /*PREFIX*/ACCOUNTS A1 ON A1.ACCOUNT_ID=A.SENDER_ID
  LEFT JOIN /*PREFIX*/ACCOUNTS A2 ON A2.ACCOUNT_ID=A.RECIPIENT_ID 

--

/* Создание процедуры добавления оповещения */

CREATE PROCEDURE I_ALARM 
(
  IN ALARM_ID VARCHAR(32),
  IN SENDER_ID VARCHAR(32),
  IN RECIPIENT_ID VARCHAR(32),
  IN TYPE_ALARM INTEGER,
  IN DATE_BEGIN DATETIME,
  IN DATE_END DATETIME,
  IN CAPTION VARCHAR(100),
  IN TEXT_ALARM VARCHAR(4000)
)
BEGIN
  INSERT INTO /*PREFIX*/ALARMS (ALARM_ID,SENDER_ID,RECIPIENT_ID,TYPE_ALARM,
                                DATE_BEGIN,DATE_END,CAPTION,TEXT_ALARM)
       VALUES (ALARM_ID,SENDER_ID,RECIPIENT_ID,TYPE_ALARM,
               DATE_BEGIN,DATE_END,CAPTION,TEXT_ALARM);
END;

--

/* Создание процедуры изменения оповещения */

CREATE PROCEDURE /*PREFIX*/U_ALARM 
(
  IN ALARM_ID VARCHAR(32),
  IN SENDER_ID VARCHAR(32),
  IN RECIPIENT_ID VARCHAR(32),
  IN TYPE_ALARM INTEGER,
  IN DATE_BEGIN DATETIME,
  IN DATE_END DATETIME,
  IN CAPTION VARCHAR(100),
  IN TEXT_ALARM VARCHAR(4000),
  IN OLD_ALARM_ID VARCHAR(32)
)
BEGIN
  UPDATE /*PREFIX*/ALARMS A
     SET A.ALARM_ID=ALARM_ID,
         A.SENDER_ID=SENDER_ID,
         A.RECIPIENT_ID=RECIPIENT_ID,
         A.TYPE_ALARM=TYPE_ALARM,
         A.DATE_BEGIN=DATE_BEGIN,
         A.DATE_END=DATE_END,
         A.CAPTION=CAPTION,
         A.TEXT_ALARM=TEXT_ALARM
   WHERE A.ALARM_ID=OLD_ALARM_ID;
END;

--

/* Создание процедуры удаления оповещения */

CREATE PROCEDURE /*PREFIX*/D_ALARM
(
  IN OLD_ALARM_ID VARCHAR(32)
)
BEGIN
  DELETE FROM /*PREFIX*/ALARMS 
        WHERE ALARM_ID=OLD_ALARM_ID;
END;

--
