DROP PROCEDURE DEL_FROM_TO

CREATE PROCEDURE DEL_FROM_TO
(
  IN FROM_ID VARCHAR(32),
  IN TO_ID VARCHAR(32)
)
BEGIN
  DECLARE AHEAD_RTF LONGBLOB;
  DECLARE ABODY_RTF LONGBLOB;
  
  SELECT HEAD_RTF, BODY_RTF
    INTO AHEAD_RTF, ABODY_RTF
    FROM EXPORTS
   WHERE EXPORT_ID=FROM_ID;

  UPDATE EXPORTS
     SET HEAD_RTF=AHEAD_RTF,
         BODY_RTF=ABODY_RTF
   WHERE EXPORT_ID=TO_ID;
   
  DELETE FROM PATTERNS
   WHERE EXPORT_ID=TO_ID;
   
  INSERT INTO PATTERNS (EXPORT_ID,DESIGN_ID,RTF) 
  SELECT TO_ID, DESIGN_ID, RTF 
    FROM PATTERNS
   WHERE EXPORT_ID=FROM_ID; 
   
END;