/* Создание таблицы реестра */

CREATE TABLE /*PREFIX*/ROLLS
(
  ROLL_ID VARCHAR(32) NOT NULL,
	OBJECT_ID VARCHAR(32) NOT NULL,
  ACCOUNT_ID VARCHAR(32) NOT NULL,
  OPERATION_ID VARCHAR(32) NOT NULL,
	DATE_BEGIN DATE NOT NULL,
	DATE_END DATE,
  PRIMARY KEY (ROLL_ID),
  FOREIGN KEY (OBJECT_ID) REFERENCES OBJECTS (OBJECT_ID),
  FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS (ACCOUNT_ID),
  FOREIGN KEY (OPERATION_ID) REFERENCES OPERATIONS (OPERATION_ID)
)

--

/* Создание просмотра таблицы реестра */

CREATE VIEW /*PREFIX*/S_ROLLS
AS
   SELECT R.*, 
          A.NAME AS ACCOUNT_NAME,
          O.NAME AS OPERATION_NAME
     FROM /*PREFIX*/ROLLS R
     JOIN /*PREFIX*/ACCOUNTS A ON A.ACCOUNT_ID=R.ACCOUNT_ID
     JOIN /*PREFIX*/OPERATIONS O ON O.OPERATION_ID=R.OPERATION_ID
		 
--

/* Создание процедуры добавления реестра */

CREATE PROCEDURE /*PREFIX*/I_ROLL
(
  IN ROLL_ID VARCHAR(32),
  IN OBJECT_ID VARCHAR(32),
  IN ACCOUNT_ID VARCHAR(32),
  IN OPERATION_ID VARCHAR(32),
  IN DATE_BEGIN DATE,
  IN DATE_END DATE
)
BEGIN
  INSERT INTO /*PREFIX*/ROLLS (ROLL_ID,OBJECT_ID,ACCOUNT_ID,OPERATION_ID,DATE_BEGIN,DATE_END)
       VALUES (ROLL_ID,OBJECT_ID,ACCOUNT_ID,OPERATION_ID,DATE_BEGIN,DATE_END);
END;

--

/* Создание процедуры изменения реестра */

CREATE PROCEDURE /*PREFIX*/U_ROLL
(
  IN ROLL_ID VARCHAR(32),
  IN OBJECT_ID VARCHAR(32),
  IN ACCOUNT_ID VARCHAR(32),
  IN OPERATION_ID VARCHAR(32),
  IN DATE_BEGIN DATE,
	IN DATE_END DATE,
	IN OLD_ROLL_ID VARCHAR(32)
)
BEGIN
  UPDATE /*PREFIX*/ROLLS R
     SET R.ROLL_ID=ROLL_ID,
         R.OBJECT_ID=OBJECT_ID,
         R.ACCOUNT_ID=ACCOUNT_ID,
         R.OPERATION_ID=OPERATION_ID,
				 R.DATE_BEGIN=DATE_BEGIN,
				 R.DATE_END=DATE_END
   WHERE R.ROLL_ID=OLD_ROLL_ID;
END;

--

/* Создание процедуры удаления реестра */

CREATE PROCEDURE /*PREFIX*/D_ROLL
(
  IN OLD_ROLL_ID VARCHAR(32)
)
BEGIN
  DELETE FROM /*PREFIX*/ROLLS
        WHERE ROLL_ID=OLD_ROLL_ID;
END;

--