CREATE VIEW S_WA_SELL_APARTMENT_ROLLS
AS
SELECT R.ROLL_ID, 
			 R.DATE_BEGIN,
			 R.DATE_END,
			 OP.NAME AS OPERATION_NAME,
			 V.NAME AS VIEW_NAME,
			 T.NAME AS TYPE_NAME,
			 AOP.*
  FROM ROLLS R
	JOIN OBJECTS O ON O.OBJECT_ID=R.OBJECT_ID
	JOIN OPERATIONS OP ON OP.OPERATION_ID=R.OPERATION_ID
	JOIN VIEWS V ON V.VIEW_ID=O.VIEW_ID
	JOIN TYPES T ON T.TYPE_ID=O.TYPE_ID
	JOIN S_WA_SELL_APARTMENT_PARAMS AOP ON AOP.OBJECT_ID=O.OBJECT_ID
 WHERE R.OPERATION_ID='9BB38FBAEE8B88A54FD02C983AE5C607' /* Продам */	