DROP PROCEDURE /*PREFIX*/GET_OBJECT_PARAM_VALUE;

CREATE PROCEDURE /*PREFIX*/GET_OBJECT_PARAM_VALUE
(
  IN OBJECT_ID VARCHAR(32),
	IN PARAM_ID VARCHAR(32),
	OUT VALUE BLOB
)
BEGIN
  SELECT OP.VALUE
	  INTO VALUE
		FROM /*PREFIX*/OBJECT_PARAMS OP 
	 WHERE OP.OBJECT_ID=OBJECT_ID
	   AND OP.PARAM_ID=PARAM_ID
		 AND OP.DATE_CREATE=(SELECT MAX(OP2.DATE_CREATE) 
		                       FROM /*PREFIX*/OBJECT_PARAMS OP2
											    WHERE OP2.OBJECT_ID=OBJECT_ID
		                        AND OP2.PARAM_ID=PARAM_ID);
END;