SELECT PO.PUBLISHING_ID,
       O.VIEW_ID, O.TYPE_ID, O.OPERATION_ID
  FROM PUBLISHING_OBJECTS PO 
	JOIN OBJECTS O ON O.OBJECT_ID=PO.OBJECT_ID
 WHERE PO.OBJECT_ID='170E7DCF38CD89D04304CF01CEBD9E3B'
   AND PO.DATE_BEGIN>=DATE_ADD(CURRENT_TIMESTAMP,INTERVAL -1 MONTH) 
	 AND (PO.DATE_END IS NULL OR PO.DATE_END>=CURRENT_TIMESTAMP)
	 AND O.STATUS IN (0,1)
