DROP PROCEDURE R_PRESENTATION

CREATE PROCEDURE R_PRESENTATION
(
  IN PRESENTATION_ID VARCHAR(32)
)
BEGIN
  DECLARE ATABLE VARCHAR(100);
	DECLARE COLUMN_ID VARCHAR(32);
	DECLARE VIEW_ID VARCHAR(32);
	DECLARE TYPE_ID VARCHAR(32);
	DECLARE OPERATION_ID VARCHAR(32);
	DECLARE PARAM_IDS VARCHAR(1000);
	DECLARE COLUMN_NAME VARCHAR(100);
	DECLARE OLD_COLUMN_ID VARCHAR(32);
	DECLARE PARAM_ID VARCHAR(32);
	DECLARE PARAM_TYPE INTEGER;
	DECLARE PARAM_COUNT INTEGER;
	DECLARE REAL_COUNT INTEGER;
	DECLARE STRING_BEFORE VARCHAR(100);
	DECLARE STRING_AFTER VARCHAR(100);
	DECLARE FIELD_NAME VARCHAR(1000);
	DECLARE NEW_QUERY VARCHAR(2000);
	DECLARE DONE INTEGER DEFAULT 0;
	DECLARE C1 CURSOR FOR SELECT PC.COLUMN_ID, C.NAME, CP.PARAM_ID, P.PARAM_TYPE,
	                             CP.STRING_BEFORE, CP.STRING_AFTER,
															 (SELECT COUNT(*) FROM COLUMN_PARAMS CP1 WHERE CP1.COLUMN_ID=CP.COLUMN_ID) AS PARAM_COUNT
  												FROM PRESENTATION_COLUMNS PC
  												JOIN COLUMNS C ON C.COLUMN_ID=PC.COLUMN_ID
  												JOIN COLUMN_PARAMS CP ON CP.COLUMN_ID=C.COLUMN_ID
  												JOIN PARAMS P ON P.PARAM_ID=CP.PARAM_ID
 												 WHERE PC.PRESENTATION_ID=PRESENTATION_ID
                         ORDER BY PC.PRIORITY, CP.PRIORITY;
  DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE=1;												
	
  SELECT P.TABLE_NAME INTO ATABLE
    FROM PRESENTATIONS P
   WHERE P.PRESENTATION_ID=PRESENTATION_ID;
	
	SET @QUERY=CONCAT('DROP TABLE IF EXISTS ',ATABLE);
  PREPARE STMT FROM @QUERY;
  EXECUTE STMT;
  DEALLOCATE PREPARE STMT;

	SET @QUERY=CONCAT('CREATE TABLE ',ATABLE,' AS SELECT OP.OBJECT_ID,O.VIEW_ID,O.TYPE_ID,O.OPERATION_ID,');
	SET @QUERY=CONCAT(@QUERY,'O.DATE_BEGIN,O.ACCOUNT_ID,A.USER_NAME,A.PHONE');
	SET PARAM_IDS='';
	SET OLD_COLUMN_ID='';
	SET FIELD_NAME='';
	SET REAL_COUNT=0;
		
	OPEN C1;
  FETCH C1 INTO COLUMN_ID,COLUMN_NAME,PARAM_ID,PARAM_TYPE,STRING_BEFORE,STRING_AFTER,PARAM_COUNT;
  WHILE NOT DONE DO
	
		IF (OLD_COLUMN_ID<>COLUMN_ID) THEN
		  SET REAL_COUNT=0;
		END IF;
		
		SET REAL_COUNT=REAL_COUNT+1;
		
	  /*CASE 
 	    WHEN PARAM_TYPE=0 THEN SET FIELD_NAME=CONCAT('MIN(IF(OP.PARAM_ID=''',PARAM_ID,''',CONVERT(OP.VALUE USING cp1251),NULL))');
      WHEN PARAM_TYPE=2 THEN SET FIELD_NAME=CONCAT('MIN(IF(OP.PARAM_ID=''',PARAM_ID,''',CONVERT(OP.VALUE,SIGNED),NULL))');
      WHEN PARAM_TYPE=3 THEN SET FIELD_NAME=CONCAT('MIN(IF(OP.PARAM_ID=''',PARAM_ID,''',CONVERT(OP.VALUE,DECIMAL(15,2)),NULL))');
	    ELSE SET NEW_QUERY='';
    END CASE;*/
		
		SET FIELD_NAME=CONCAT('MIN(IF(OP.PARAM_ID=''',
		                      PARAM_ID,
													''',CONCAT(''',
													IFNULL(STRING_BEFORE,''),
													''',CONVERT(OP.VALUE USING cp1251),''',
													IFNULL(STRING_AFTER,''),
													'''),NULL))');
		
		IF (REAL_COUNT=PARAM_COUNT) THEN
  		IF (PARAM_COUNT=1) THEN
	  	  SET NEW_QUERY=FIELD_NAME;
			ELSE	
		    SET NEW_QUERY=CONCAT(NEW_QUERY,',',FIELD_NAME,')');
		  END IF;
		  SET @QUERY=CONCAT(@QUERY,',',NEW_QUERY,' AS ''',COLUMN_NAME,'''');
			SET NEW_QUERY='';
		ELSE
		  IF (REAL_COUNT=1) THEN
			  SET NEW_QUERY=CONCAT('CONCAT(',FIELD_NAME);
			ELSE	
			  SET NEW_QUERY=CONCAT(NEW_QUERY,',',FIELD_NAME);
			END IF;
		END IF;
				
		IF TRIM(PARAM_IDS)='' THEN
		  SET PARAM_IDS=CONCAT('''',PARAM_ID,''''); 
		ELSE
		  SET PARAM_IDS=CONCAT(PARAM_IDS,',',CONCAT('''',PARAM_ID,'''')); 
		END IF;
		
		SET OLD_COLUMN_ID=COLUMN_ID;
		
    FETCH C1 INTO COLUMN_ID,COLUMN_NAME,PARAM_ID,PARAM_TYPE,STRING_BEFORE,STRING_AFTER,PARAM_COUNT;
  END WHILE;
  CLOSE C1;		 

	SET @QUERY=CONCAT(@QUERY,' FROM OBJECT_PARAMS OP ');
	SET @QUERY=CONCAT(@QUERY,'JOIN OBJECTS O ON O.OBJECT_ID=OP.OBJECT_ID ');
	SET @QUERY=CONCAT(@QUERY,'JOIN ACCOUNTS A ON A.ACCOUNT_ID=O.ACCOUNT_ID ');
	IF TRIM(PARAM_IDS)<>'' THEN
	  SET @QUERY=CONCAT(@QUERY,'WHERE OP.PARAM_ID IN (',PARAM_IDS,') ');
		SET @QUERY=CONCAT(@QUERY,'AND OP.DATE_CREATE=(SELECT MAX(DATE_CREATE) FROM OBJECT_PARAMS WHERE PARAM_ID=OP.PARAM_ID AND OBJECT_ID=O.OBJECT_ID) ');
  	SET @QUERY=CONCAT(@QUERY,'AND O.VIEW_ID IN (SELECT VIEW_ID FROM ACCOUNT_PRESENTATIONS WHERE PRESENTATION_ID=''',PRESENTATION_ID,''') ');
  	SET @QUERY=CONCAT(@QUERY,'AND O.TYPE_ID IN (SELECT TYPE_ID FROM ACCOUNT_PRESENTATIONS WHERE PRESENTATION_ID=''',PRESENTATION_ID,''') ');
  	SET @QUERY=CONCAT(@QUERY,'AND O.OPERATION_ID IN (SELECT OPERATION_ID FROM ACCOUNT_PRESENTATIONS WHERE PRESENTATION_ID=''',PRESENTATION_ID,''') ');
  	SET @QUERY=CONCAT(@QUERY,'AND O.DATE_END IS NULL ');
  	SET @QUERY=CONCAT(@QUERY,'AND O.STATUS=1 ');
		
		SET @QUERY=CONCAT(@QUERY,'GROUP BY OP.OBJECT_ID');

		PREPARE STMT FROM @QUERY;
    EXECUTE STMT;
    DEALLOCATE PREPARE STMT; 
		
	END IF;	
END;


call r_presentation('DDDCB1FBC05FA143495A3E7385B1392B')
