CREATE VIEW S_APARTMENT_ROLLS
AS
SELECT R.ROLL_ID, 
       R.OBJECT_ID, 
			 R.DATE_BEGIN,
			 R.DATE_END,
			 OP.NAME AS OPERATION_NAME,
			 V.NAME AS VIEW_NAME,
			 T.NAME AS TYPE_NAME,
			 AOP.TOWN_NAME,
			 AOP.REGION_NAME,
			 AOP.STREET_NAME,
			 AOP.LANDMARK_NAME,
			 AOP.DIRECTION_NAME,
			 AOP.COUNTROOM_NAME
  FROM ROLLS R
	JOIN OPERATIONS OP ON OP.OPERATION_ID=R.OPERATION_ID
	JOIN OBJECTS O ON O.OBJECT_ID=R.OBJECT_ID
	JOIN VIEWS V ON V.VIEW_ID=O.VIEW_ID
	JOIN TYPES T ON T.TYPE_ID=O.TYPE_ID
	JOIN S_APARTMENT_OBJECT_PARAMS AOP ON AOP.OBJECT_ID=O.OBJECT_ID
	