SELECT T.* FROM (
SELECT A2.USER_NAME AS WHO_NAME,
       F.SMALL_NAME AS FIRM_SMALL_NAME,
       A1.USER_NAME,
			 COUNT(*) AS AMOUNT
FROM
(
SELECT PO.PUBLISHING_ID,
       O.ACCOUNT_ID,
      (SELECT ACCOUNT_ID FROM OBJECT_PARAMS OP 
			  WHERE OP.OBJECT_ID=O.OBJECT_ID LIMIT 0,1) AS WHO_ID
FROM PUBLISHING_OBJECTS PO 
JOIN OBJECTS O ON O.OBJECT_ID=PO.OBJECT_ID
WHERE PO.
) T
JOIN ACCOUNTS A1 ON A1.ACCOUNT_ID=T.ACCOUNT_ID
JOIN ACCOUNTS A2 ON A2.ACCOUNT_ID=T.WHO_ID
LEFT JOIN FIRMS F ON F.FIRM_ID=A1.FIRM_ID
GROUP BY T.PUBLISHING_ID,T.ACCOUNT_ID
) T
ORDER BY T.WHO_NAME