DELETE FROM OBJECT_PARAMS
WHERE OBJECT_ID IN (SELECT O.OBJECT_ID FROM OBJECTS O
                     WHERE O.DATE_BEGIN<DATE_ADD(CURRENT_TIMESTAMP,INTERVAL -1 MONTH)
	                      OR O.DATE_END<=CURRENT_TIMESTAMP
                        OR O.STATUS	IN (2,3))

DELETE FROM OBJECTS
 WHERE DATE_BEGIN<DATE_ADD(CURRENT_TIMESTAMP,INTERVAL -1 MONTH)
	  OR DATE_END<=CURRENT_TIMESTAMP OR STATUS	IN (2,3)