 SET @ATABLE='';
 SET @PRESENTATION_ID='DDDCB1FBC05FA143495A3E7385B1392B';

 SELECT P.TABLE_NAME INTO @ATABLE
   FROM PRESENTATIONS P
  WHERE P.PRESENTATION_ID=@PRESENTATION_ID;
		
 SET @SQLS=CONCAT('DROP TABLE IF EXISTS ',@ATABLE);
 PREPARE stmt FROM @SQLS; 
 EXECUTE stmt;
 DEALLOCATE PREPARE stmt;
  
 SELECT PC.COLUMN_ID, C.NAME
   FROM PRESENTATION_COLUMNS PC
	 JOIN COLUMNS C ON C.COLUMN_ID=PC.COLUMN_ID
  WHERE PC.PRESENTATION_ID=@PRESENTATION_ID
	ORDER BY PC.PRIORITY;



