DROP PROCEDURE R_PRESENTATIONS

CREATE PROCEDURE /*PREFIX*/R_PRESENTATIONS
(
)
BEGIN
  DECLARE PRESENTATION_ID VARCHAR(32);
	DECLARE DONE INTEGER DEFAULT 0;
	DECLARE C1 CURSOR FOR SELECT P.PRESENTATION_ID
  												FROM /*PREFIX*/PRESENTATIONS P;
  DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE=1;	
	
	OPEN C1;
  FETCH C1 INTO PRESENTATION_ID;
  WHILE NOT DONE DO
		CALL /*PREFIX*/R_PRESENTATION (PRESENTATION_ID);
    FETCH C1 INTO PRESENTATION_ID;
  END WHILE;
  CLOSE C1;		 
END;

call r_presentations
