select t.DATE_WORK,
       t.DATE_BEGIN,
       t.DATE_END,
       DATEADD(SS,T.TIME_WORK,0) AS TIME_WORK,
       DATEADD(SS,DATEDIFF(SS,T.DATE_BEGIN,T.DATE_END)-T.TIME_WORK,0) AS TIME_INTERVAL
   from (
    SELECT 
           CONVERT(VARCHAR(10),T.DATE_BEGIN,104) AS DATE_WORK,
           MIN(T.DATE_BEGIN) AS DATE_BEGIN, 
           MAX(T.DATE_END) AS DATE_END, 
           SUM(DATEDIFF(SS,T.DATE_BEGIN,T.DATE_END)) AS TIME_WORK,
           COUNT(*) AS TASK_COUNT
            FROM TASKS T
           WHERE T.PERFORMER_ID='53C3425112CB9AD447A49FA6991DA03F'
             AND T.RESULT_ID IS NOT NULL
      GROUP BY CONVERT(VARCHAR(10),T.DATE_BEGIN,104)
) t