CREATE OR ALTER PROCEDURE GET_DISPATCHERS_REPORT 
returns (DRIVER_ID   Varchar(32),
         DRIVER_NAME Varchar(100))
AS 

begin
FOR SELECT D.DISPATCHER_ID,
           A.USER_NAME AS DRIVER_NAME       
        FROM DISPATCHERS  D
        INNER JOIN ACCOUNTS A ON A.ACCOUNT_ID = D.DISPATCHER_ID 
            INTO :DRIVER_ID,
             :DRIVER_NAME DO BEGIN       
    SUSPEND;
    END
end