/* Удаление процедуры добавления отчета */

DROP PROCEDURE /*PREFIX*/I_REPORT

--

/* Создание процедуры добавления отчета */

CREATE PROCEDURE /*PREFIX*/I_REPORT
(
  IN REPORT_ID VARCHAR(32),
  IN NAME VARCHAR(100),
  IN DESCRIPTION VARCHAR(250),
  IN INTERFACE_TYPE INTEGER,
  IN ENGINE VARCHAR(100),
  IN REPORT LONGBLOB,
  IN PLACE INTEGER
)
BEGIN
  INSERT INTO /*PREFIX*/INTERFACES (INTERFACE_ID,NAME,DESCRIPTION,INTERFACE_TYPE,MODULE_NAME,MODULE_INTERFACE)
       VALUES (REPORT_ID,NAME,DESCRIPTION,INTERFACE_TYPE,NULL,NULL);
  
	INSERT INTO /*PREFIX*/REPORTS (REPORT_ID,ENGINE,REPORT,PLACE)
       VALUES (REPORT_ID,ENGINE,REPORT,PLACE);
				 
END;

--

/* Удаление процедуры изменения отчета */

DROP PROCEDURE /*PREFIX*/U_REPORT

--

/* Создание процедуры изменения отчета */

CREATE PROCEDURE /*PREFIX*/U_REPORT
(
  IN REPORT_ID VARCHAR(32),
  IN NAME VARCHAR(100),
  IN DESCRIPTION VARCHAR(250),
  IN INTERFACE_TYPE INTEGER,
  IN ENGINE VARCHAR(100),
  IN REPORT LONGBLOB,
  IN PLACE INTEGER,
  IN OLD_REPORT_ID VARCHAR(32)
)
BEGIN
  UPDATE /*PREFIX*/INTERFACES I
	   SET I.INTERFACE_ID=REPORT_ID,
				 I.NAME=NAME,
				 I.DESCRIPTION=DESCRIPTION
	 WHERE I.INTERFACE_ID=OLD_REPORT_ID; 
  
  UPDATE /*PREFIX*/REPORTS R
     SET R.REPORT_ID=REPORT_ID,
         R.ENGINE=ENGINE,
         R.REPORT=REPORT,
         R.PLACE=PLACE
   WHERE R.REPORT_ID=OLD_REPORT_ID;
	 
END;

--

/* Удаление процедуры удаления отчета */

DROP PROCEDURE /*PREFIX*/D_REPORT

--

/* Создание процедуры удаления отчета */

CREATE PROCEDURE /*PREFIX*/D_REPORT
(
  IN OLD_REPORT_ID VARCHAR(32)
)
BEGIN
  DELETE FROM /*PREFIX*/REPORTS
        WHERE REPORT_ID=OLD_REPORT_ID;
  
	DELETE FROM /*PREFIX*/INTERFACES
	      WHERE INTERFACE_ID=OLD_REPORT_ID;
END;

--

/* Удаление процедуры добавления интерфейсного скриптов */

DROP PROCEDURE /*PREFIX*/I_SCRIPT

--

/* Создание процедуры добавления интерфейсного скриптов */

CREATE PROCEDURE /*PREFIX*/I_SCRIPT
(
  IN SCRIPT_ID VARCHAR(32),
  IN NAME VARCHAR(100),
  IN DESCRIPTION VARCHAR(250),
  IN INTERFACE_TYPE INTEGER,
  IN ENGINE VARCHAR(100),
  IN SCRIPT LONGBLOB,
  IN PLACE INTEGER
)
BEGIN
  INSERT INTO /*PREFIX*/INTERFACES (INTERFACE_ID,NAME,DESCRIPTION,INTERFACE_TYPE,MODULE_NAME,MODULE_INTERFACE)
       VALUES (SCRIPT_ID,NAME,DESCRIPTION,INTERFACE_TYPE,NULL,NULL);
			 
  INSERT INTO /*PREFIX*/SCRIPTS (SCRIPT_ID,ENGINE,SCRIPT,PLACE)
       VALUES (SCRIPT_ID,ENGINE,SCRIPT,PLACE);
END;

--

/* Удаление процедуры изменения интерфейсного скрипта */

DROP PROCEDURE /*PREFIX*/U_SCRIPT

--

/* Создание процедуры изменения интерфейсного скрипта */

CREATE PROCEDURE /*PREFIX*/U_SCRIPT
(
  IN SCRIPT_ID VARCHAR(32),
  IN NAME VARCHAR(100),
  IN DESCRIPTION VARCHAR(250),
  IN INTERFACE_TYPE INTEGER,
  IN ENGINE VARCHAR(100),
  IN SCRIPT LONGBLOB,
  IN PLACE INTEGER,
  IN OLD_SCRIPT_ID VARCHAR(32)
)
BEGIN
  UPDATE /*PREFIX*/INTERFACES I
	   SET I.INTERFACE_ID=SCRIPT_ID,
				 I.NAME=NAME,
				 I.DESCRIPTION=DESCRIPTION
	 WHERE I.INTERFACE_ID=OLD_SCRIPT_ID; 

	UPDATE /*PREFIX*/SCRIPTS S
     SET S.SCRIPT_ID=SCRIPT_ID,
         S.ENGINE=ENGINE,
         S.SCRIPT=SCRIPT,
         S.PLACE=PLACE
   WHERE S.SCRIPT_ID=OLD_SCRIPT_ID;
END;

--

/* Удаление процедуры удаления интерфейсного скрипта */

DROP PROCEDURE /*PREFIX*/D_SCRIPT

--

/* Создание процедуры удаления интерфейсного скрипта */

CREATE PROCEDURE /*PREFIX*/D_SCRIPT
(
  IN OLD_SCRIPT_ID VARCHAR(32)
)
BEGIN
  DELETE FROM /*PREFIX*/SCRIPTS
        WHERE SCRIPT_ID=OLD_SCRIPT_ID;
				
  DELETE FROM /*PREFIX*/INTERFACES
	      WHERE INTERFACE_ID=OLD_SCRIPT_ID;				
END;

--

/* Удаление процедуры добавления документа */

DROP PROCEDURE /*PREFIX*/I_DOCUMENT

--

/* Создание процедуры добавления документа */

CREATE PROCEDURE /*PREFIX*/I_DOCUMENT
(
  IN DOCUMENT_ID VARCHAR(32),
  IN NAME VARCHAR(100),
  IN DESCRIPTION VARCHAR(250),
  IN INTERFACE_TYPE INTEGER,
	IN OLE_CLASS VARCHAR(100),
  IN DOCUMENT LONGBLOB,
  IN PLACE INTEGER
)
BEGIN
  INSERT INTO /*PREFIX*/INTERFACES (INTERFACE_ID,NAME,DESCRIPTION,INTERFACE_TYPE,MODULE_NAME,MODULE_INTERFACE)
       VALUES (DOCUMENT_ID,NAME,DESCRIPTION,INTERFACE_TYPE,NULL,NULL);

	INSERT INTO /*PREFIX*/DOCUMENTS (DOCUMENT_ID,OLE_CLASS,DOCUMENT,PLACE)
       VALUES (DOCUMENT_ID,OLE_CLASS,DOCUMENT,PLACE);
END;

--

/* Создание процедуры изменения документа */

DROP PROCEDURE /*PREFIX*/U_DOCUMENT

--

/* Создание процедуры изменения документа */

CREATE PROCEDURE /*PREFIX*/U_DOCUMENT
(
  IN DOCUMENT_ID VARCHAR(32),
  IN NAME VARCHAR(100),
  IN DESCRIPTION VARCHAR(250),
  IN INTERFACE_TYPE INTEGER,
  IN OLE_CLASS VARCHAR(100),
  IN DOCUMENT LONGBLOB,
  IN PLACE INTEGER,
  IN OLD_DOCUMENT_ID VARCHAR(32)
)
BEGIN
  UPDATE /*PREFIX*/INTERFACES I
	   SET I.INTERFACE_ID=DOCUMENT_ID,
				 I.NAME=NAME,
				 I.DESCRIPTION=DESCRIPTION
	 WHERE I.INTERFACE_ID=OLD_DOCUMENT_ID; 

  UPDATE /*PREFIX*/DOCUMENTS D
     SET D.DOCUMENT_ID=DOCUMENT_ID,
         D.OLE_CLASS=OLE_CLASS,
         D.DOCUMENT=DOCUMENT,
         D.PLACE=PLACE
   WHERE D.DOCUMENT_ID=OLD_DOCUMENT_ID;
END;

--

/* Создание процедуры удаления документа */

DROP PROCEDURE /*PREFIX*/D_DOCUMENT

--

/* Создание процедуры удаления документа */

CREATE PROCEDURE /*PREFIX*/D_DOCUMENT
(
  IN OLD_DOCUMENT_ID VARCHAR(32)
)
BEGIN
  DELETE FROM /*PREFIX*/DOCUMENTS
        WHERE DOCUMENT_ID=OLD_DOCUMENT_ID;
				
  DELETE FROM /*PREFIX*/INTERFACES
	      WHERE INTERFACE_ID=OLD_DOCUMENT_ID;						
END;

--