/* Добавление нового поля */

ALTER TABLE REPORTS
ADD ENGINE VARCHAR(100)

--


/* Обновление отчетов */

UPDATE REPORTS
SET ENGINE='FastReportModule'

--


/* Модифицирование нового поля*/

ALTER TABLE REPORTS
MODIFY ENGINE  VARCHAR(100) NOT NULL 

--

/* Удаление старого поля */

ALTER TABLE REPORTS
DROP REPORT_TYPE

--

/* Удаление просмотра отчетов */

DROP VIEW /*PREFIX*/S_REPORTS

--

/* Создание просмотра отчетов */

CREATE VIEW /*PREFIX*/S_REPORTS
AS
  SELECT R.*, 
         I.NAME AS INTERFACE_NAME
    FROM /*PREFIX*/REPORTS R
    JOIN /*PREFIX*/INTERFACES I ON I.INTERFACE_ID=R.REPORT_ID

--

/* Удаление процедуры создания отчета */

DROP PROCEDURE /*PREFIX*/I_REPORT

--

/* Создание процедуры создания отчета */

CREATE PROCEDURE /*PREFIX*/I_REPORT
(
  IN REPORT_ID VARCHAR(32),
  IN ENGINE VARCHAR(100),
  IN REPORT LONGBLOB,
  IN PLACE INTEGER
)
BEGIN
  INSERT INTO /*PREFIX*/REPORTS (REPORT_ID,ENGINE,REPORT,PLACE)
       VALUES (REPORT_ID,ENGINE,REPORT,PLACE);
END;

--

/* Удаление процедуры изменения отчета */

DROP PROCEDURE /*PREFIX*/U_REPORT

--

/* Создание процедуры изменения отчета */

CREATE PROCEDURE /*PREFIX*/U_REPORT
(
  IN REPORT_ID VARCHAR(32),
  IN ENGINE VARCHAR(100),
  IN REPORT LONGBLOB,
  IN PLACE INTEGER,
  IN OLD_REPORT_ID VARCHAR(32)
)
BEGIN
  UPDATE /*PREFIX*/REPORTS R
     SET R.REPORT_ID=REPORT_ID,
         R.ENGINE=ENGINE,
         R.REPORT=REPORT,
         R.PLACE=PLACE
   WHERE R.REPORT_ID=OLD_REPORT_ID;
END;

--

/* Добавление нового поля в размещение рекламы */

ALTER TABLE ADVERTISMENT_PAGES
ADD PLACE2 VARCHAR(10) NOT NULL

--

/* Удаление просмотра размещения рекламы */

DROP VIEW /*PREFIX*/S_ADVERTISMENT_PAGES

--

/* Создание просмотра размещения рекламы */

CREATE VIEW /*PREFIX*/S_ADVERTISMENT_PAGES
AS
SELECT AP.*,
			 A.NAME AS ADVERTISMENT_NAME,
			 P.NAME AS PAGE_NAME,
			 AC1.USER_NAME, 
			 AC2.USER_NAME AS WHO_PLACED_NAME 
  FROM /*PREFIX*/ADVERTISMENT_PAGES AP
	JOIN /*PREFIX*/ADVERTISMENTS A ON  A.ADVERTISMENT_ID=AP.ADVERTISMENT_ID
  JOIN /*PREFIX*/PAGES P ON P.PAGE_ID=AP.PAGE_ID
  JOIN /*PREFIX*/ACCOUNTS AC1 ON AC1.ACCOUNT_ID=AP.ACCOUNT_ID
  JOIN /*PREFIX*/ACCOUNTS AC2 ON AC2.ACCOUNT_ID=AP.WHO_PLACED
	
--

/* Удаление процедуры создания размещения */
	
DROP PROCEDURE /*PREFIX*/I_ADVERTISMENT_PAGE

--

/* Создание процедуры создания размещения */

CREATE PROCEDURE /*PREFIX*/I_ADVERTISMENT_PAGE
(
  IN ADVERTISMENT_ID VARCHAR(32),
  IN PAGE_ID VARCHAR(32),
	IN ACCOUNT_ID VARCHAR(32),
	IN PLACE INTEGER,
	IN PLACE2 VARCHAR(10),
	IN DATE_BEGIN DATE,
	IN DATE_END DATE,
  IN PRIORITY INTEGER,
	IN COUNTER INTEGER,
	IN WHO_PLACED VARCHAR(32),
	IN DATE_PLACED DATETIME
)
BEGIN
  INSERT INTO /*PREFIX*/ADVERTISMENT_PAGES (ADVERTISMENT_ID,PAGE_ID,ACCOUNT_ID,PLACE,PLACE2,DATE_BEGIN,
	                                          DATE_END,PRIORITY,COUNTER,WHO_PLACED,DATE_PLACED)
       VALUES (ADVERTISMENT_ID,PAGE_ID,ACCOUNT_ID,PLACE,PLACE2,DATE_BEGIN,
	             DATE_END,PRIORITY,COUNTER,WHO_PLACED,DATE_PLACED);
END;

--

/* Удаление процедуры изменения размещения */

DROP PROCEDURE /*PREFIX*/U_ADVERTISMENT_PAGE

--

/* Создание процедуры изменения размещения */

CREATE PROCEDURE /*PREFIX*/U_ADVERTISMENT_PAGE
(
  IN ADVERTISMENT_ID VARCHAR(32),
  IN PAGE_ID VARCHAR(32),
	IN ACCOUNT_ID VARCHAR(32),
	IN PLACE INTEGER,
	IN PLACE2 VARCHAR(10),
	IN DATE_BEGIN DATE,
	IN DATE_END DATE,
  IN PRIORITY INTEGER,
	IN COUNTER INTEGER,
	IN WHO_PLACED VARCHAR(32),
	IN DATE_PLACED DATETIME,
  IN OLD_ADVERTISMENT_ID VARCHAR(32),
  IN OLD_PAGE_ID VARCHAR(32),
  IN OLD_ACCOUNT_ID VARCHAR(32)
)
BEGIN
  UPDATE /*PREFIX*/ADVERTISMENT_PAGES AP
     SET AP.ADVERTISMENT_ID=ADVERTISMENT_ID,
		     AP.PAGE_ID=PAGE_ID,
         AP.ACCOUNT_ID=ACCOUNT_ID,
         AP.PLACE=PLACE,
				 AP.PLACE2=PLACE2,
         AP.DATE_BEGIN=DATE_BEGIN,
         AP.DATE_END=DATE_END,
         AP.PRIORITY=PRIORITY,
         AP.COUNTER=COUNTER,
         AP.WHO_PLACED=WHO_PLACED,
         AP.DATE_PLACED=DATE_PLACED
   WHERE AP.ADVERTISMENT_ID=OLD_ADVERTISMENT_ID
	   AND AP.PAGE_ID=OLD_PAGE_ID
		 AND AP.ACCOUNT_ID=OLD_ACCOUNT_ID;
END;

--