ALTER TABLE ARTICLES
ADD VIEWS_COUNTER INTEGER

--

ALTER TABLE ARTICLES 
ADD TAGS LONGBLOB

--

DROP VIEW S_ARTICLES

--

CREATE VIEW S_ARTICLES
AS
   SELECT A.ARTICLE_ID,
          A.ACCOUNT_ID,
          A.SUBJECT_ID,
          A.DATE_CREATE,
          A.SECTION,
          A.DATE_ARTICLE,
          A.TITLE,
          A.EXCERPT,
          CONVERT(A.ARTICLE_TEXT USING cp1251) ARTICLE_TEXT,
          A.PICTURE,
          A.LINK,
          A.VIEWS_COUNTER,
          CONVERT(A.TAGS USING cp1251) TAGS,
          A1.USER_NAME,
          A1.SURNAME AS ACCOUNT_SURNAME,
          A1.NAME AS ACCOUNT_NAME,
          A1.PATRONYMIC AS ACCOUNT_PATRONYMIC,
          S.NAME AS SUBJECT_NAME
     FROM ARTICLES A
     JOIN ACCOUNTS A1 ON A1.ACCOUNT_ID=A.ACCOUNT_ID
     LEFT JOIN SUBJECTS S ON S.SUBJECT_ID=A.SUBJECT_ID

--

DROP PROCEDURE I_ARTICLE

--

CREATE PROCEDURE I_ARTICLE
(
  IN ARTICLE_ID VARCHAR(32),
  IN ACCOUNT_ID VARCHAR(32),
  IN SUBJECT_ID VARCHAR(32),
  IN DATE_CREATE DATETIME,
  IN SECTION INTEGER,
  IN DATE_ARTICLE DATETIME,
  IN TITLE VARCHAR(250),
  IN EXCERPT VARCHAR(1000),
  IN ARTICLE_TEXT LONGBLOB,
  IN PICTURE LONGBLOB,
  IN LINK VARCHAR(250),
  IN VIEWS_COUNTER INTEGER,
  IN TAGS LONGBLOB
)
BEGIN
  INSERT INTO ARTICLES (ARTICLE_ID,ACCOUNT_ID,SUBJECT_ID,DATE_CREATE,SECTION,
                        DATE_ARTICLE,TITLE,EXCERPT,ARTICLE_TEXT,PICTURE,LINK,VIEWS_COUNTER,TAGS)
       VALUES (ARTICLE_ID,ACCOUNT_ID,SUBJECT_ID,DATE_CREATE,SECTION,
               DATE_ARTICLE,TITLE,EXCERPT,ARTICLE_TEXT,PICTURE,LINK,VIEWS_COUNTER,TAGS);
END;

--

DROP PROCEDURE U_ARTICLE

--

CREATE PROCEDURE U_ARTICLE
(
  IN ARTICLE_ID VARCHAR(32),
  IN ACCOUNT_ID VARCHAR(32),
  IN SUBJECT_ID VARCHAR(32),
  IN DATE_CREATE DATETIME,
  IN SECTION INTEGER,
  IN DATE_ARTICLE DATETIME,
  IN TITLE VARCHAR(250),
  IN EXCERPT VARCHAR(1000),
  IN ARTICLE_TEXT LONGBLOB,
  IN PICTURE LONGBLOB,
  IN LINK VARCHAR(250),
  IN VIEWS_COUNTER INTEGER,
  IN TAGS LONGBLOB,
  IN OLD_ARTICLE_ID VARCHAR(32)
)
BEGIN
 UPDATE ARTICLES A
    SET A.ARTICLE_ID=ARTICLE_ID,
        A.ACCOUNT_ID=ACCOUNT_ID,
        A.SUBJECT_ID=SUBJECT_ID,
        A.DATE_CREATE=DATE_CREATE,
        A.SECTION=SECTION,
        A.DATE_ARTICLE=DATE_ARTICLE,
        A.TITLE=TITLE,
        A.EXCERPT=EXCERPT,
        A.ARTICLE_TEXT=ARTICLE_TEXT,
        A.PICTURE=PICTURE,
        A.LINK=LINK,
        A.VIEWS_COUNTER=VIEWS_COUNTER,
        A.TAGS=TAGS
  WHERE A.ARTICLE_ID=OLD_ARTICLE_ID;
END;

--

ALTER TABLE PLACEMENTS 
ADD RESTRICTED INTEGER

--

DROP VIEW `s_placements`

--

CREATE VIEW `s_placements`
AS
                  SELECT `p`.`PLACEMENT_ID` AS `PLACEMENT_ID`,
                         `p`.`BANNER_ID` AS `BANNER_ID`,
                         `p`.`PAGE_ID` AS `PAGE_ID`,
                         `p`.`ACCOUNT_ID` AS `ACCOUNT_ID`,
                         `p`.`WHO_PLACED` AS `WHO_PLACED`,
                         `p`.`DATE_PLACED` AS `DATE_PLACED`,
                         `p`.`PLACE` AS `PLACE`,
                         `p`.`DATE_BEGIN` AS `DATE_BEGIN`,
                         `p`.`DATE_END` AS `DATE_END`,
                         `p`.`PRIORITY` AS `PRIORITY`,
                         `p`.`COUNTER` AS `COUNTER`,
                         `p`.`RESTRICTED` AS `RESTRICTED`,
                         `b`.`NAME` AS `BANNER_NAME`,
                         
                         `pg`.`NAME` AS `PAGE_NAME`,
                         `ac1`.`USER_NAME` AS `USER_NAME`,
                         `ac2`.`USER_NAME` AS `WHO_PLACED_NAME`
                    FROM ((((`placements` `p`
                             JOIN`banners` `b`
                             ON ((`b`.`BANNER_ID` = `p`.`BANNER_ID`)))
                            JOIN`accounts` `ac2`
                            ON ((`ac2`.`ACCOUNT_ID` = `p`.`WHO_PLACED`)))
                           LEFT JOIN`pages` `pg`
                           ON ((`pg`.`PAGE_ID` = `p`.`PAGE_ID`)))
                          LEFT JOIN`accounts` `ac1`
                          ON ((`ac1`.`ACCOUNT_ID` = `p`.`ACCOUNT_ID`)));

--

DROP PROCEDURE I_PLACEMENT

--

CREATE PROCEDURE I_PLACEMENT
(
  IN PLACEMENT_ID VARCHAR(32),
  IN BANNER_ID VARCHAR(32),
  IN PAGE_ID VARCHAR(32),
	IN ACCOUNT_ID VARCHAR(32),
	IN WHO_PLACED VARCHAR(32),
	IN DATE_PLACED DATETIME,
	IN PLACE VARCHAR(10),
	IN DATE_BEGIN DATE,
	IN DATE_END DATE,
  IN PRIORITY INTEGER,
	IN COUNTER INTEGER,
  IN RESTRICTED INTEGER
)
BEGIN
  INSERT INTO PLACEMENTS (PLACEMENT_ID,BANNER_ID,PAGE_ID,ACCOUNT_ID,WHO_PLACED,
	                        DATE_PLACED,PLACE,DATE_BEGIN,DATE_END,PRIORITY,COUNTER,RESTRICTED)
       VALUES (PLACEMENT_ID,BANNER_ID,PAGE_ID,ACCOUNT_ID,WHO_PLACED,
	             DATE_PLACED,PLACE,DATE_BEGIN,DATE_END,PRIORITY,COUNTER,RESTRICTED);
END;

--

DROP PROCEDURE U_PLACEMENT

--

CREATE PROCEDURE U_PLACEMENT
(
  IN PLACEMENT_ID VARCHAR(32),
  IN BANNER_ID VARCHAR(32),
  IN PAGE_ID VARCHAR(32),
  IN ACCOUNT_ID VARCHAR(32),
  IN WHO_PLACED VARCHAR(32),
  IN DATE_PLACED DATETIME,
  IN PLACE VARCHAR(10),
  IN DATE_BEGIN DATE,
  IN DATE_END DATE,
  IN PRIORITY INTEGER,
  IN COUNTER INTEGER,
  IN RESTRICTED INTEGER,
  IN OLD_PLACEMENT_ID VARCHAR(32)
)
BEGIN
  UPDATE PLACEMENTS P
     SET P.PLACEMENT_ID=PLACEMENT_ID,
         P.BANNER_ID=BANNER_ID,
		     P.PAGE_ID=PAGE_ID,
         P.ACCOUNT_ID=ACCOUNT_ID,
         P.WHO_PLACED=WHO_PLACED,
         P.DATE_PLACED=DATE_PLACED,
         P.PLACE=PLACE,
         P.DATE_BEGIN=DATE_BEGIN,
         P.DATE_END=DATE_END,
         P.PRIORITY=PRIORITY,
         P.COUNTER=COUNTER,
         P.RESTRICTED=RESTRICTED
   WHERE P.PLACEMENT_ID=OLD_PLACEMENT_ID;
END;

--

