CREATE PROCEDURE DELETE_OBJECTS
(
  IN PID VARCHAR(32),
  IN AID VARCHAR(32),
  IN DBEGIN DATETIME,
  IN DEND DATETIME
)
BEGIN
  IF (DBEGIN IS NULL) THEN 
    SELECT MIN(PO.DATE_BEGIN)
      INTO DBEGIN
      FROM PUBLISHING_OBJECTS PO
     WHERE PO.PUBLISHING_ID=PID;
  END IF;
  
  IF (DBEGIN IS NULL) THEN
    SET DBEGIN=CAST('1990-01-01 00:00:00' AS DATETIME);
  END IF;

  IF (DEND IS NULL) THEN
    SET DEND=CAST('2050-01-01 00:00:00' AS DATETIME);
  END IF;

  IF (DEND IS NULL) THEN 
    SELECT MAX(PO.DATE_BEGIN)
      INTO DEND
      FROM PUBLISHING_OBJECTS PO
     WHERE PO.PUBLISHING_ID=PID;
  END IF;
  
  IF (AID IS NULL) THEN
    DELETE FROM PUBLISHING_OBJECTS
          WHERE PUBLISHING_ID=PID
            AND DATE_BEGIN>=DBEGIN
            AND DATE_BEGIN<DEND;
  ELSE
    DELETE FROM PUBLISHING_OBJECTS
          WHERE PUBLISHING_ID=PID
            AND DATE_BEGIN>=DBEGIN
            AND DATE_BEGIN<DEND
            AND OBJECT_ID IN (SELECT OBJECT_ID 
                                FROM OBJECTS
                               WHERE ACCOUNT_ID=AID);
  END IF;

  DELETE FROM OBJECT_PARAMS 
        WHERE OBJECT_ID NOT IN (SELECT OBJECT_ID FROM PUBLISHING_OBJECTS);
        
  DELETE FROM OBJECTS 
        WHERE OBJECT_ID NOT IN (SELECT OBJECT_ID FROM PUBLISHING_OBJECTS);
      
END;

--