CREATE TABLE /*PREFIX*/SUBSCRIPTIONS
(
  SUBSCRIPTION_ID VARCHAR(32) NOT NULL,
  SERVICE_ID VARCHAR(32) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(250),
  PRIMARY KEY (SUBSCRIPTION_ID),
  FOREIGN KEY (SERVICE_ID) REFERENCES /*PREFIX*/SERVICES (SERVICE_ID)
)

--

CREATE VIEW /*PREFIX*/S_SUBSCRIPTIONS
AS
   SELECT S.*, 
          S1.NAME AS SERVICE_NAME
     FROM /*PREFIX*/SUBSCRIPTIONS S
     JOIN /*PREFIX*/SERVICES S1 ON S1.SERVICE_ID=S.SERVICE_ID

--

CREATE PROCEDURE /*PREFIX*/I_SUBSCRIPTION
(
  IN SUBSCRIPTION_ID VARCHAR(32),
  IN SERVICE_ID VARCHAR(32),
	IN NAME VARCHAR(100),
	IN DESCRIPTION VARCHAR(250)
)
BEGIN
  INSERT INTO /*PREFIX*/SUBSCRIPTIONS (SUBSCRIPTION_ID,SERVICE_ID,NAME,DESCRIPTION)
       VALUES (SUBSCRIPTION_ID,SERVICE_ID,NAME,DESCRIPTION);
END;

--

CREATE PROCEDURE /*PREFIX*/U_SUBSCRIPTION
(
  IN SUBSCRIPTION_ID VARCHAR(32),
  IN SERVICE_ID VARCHAR(32),
	IN NAME VARCHAR(100),
	IN DESCRIPTION VARCHAR(250),
  IN OLD_SUBSCRIPTION_ID VARCHAR(32)
)
BEGIN
  UPDATE /*PREFIX*/SUBSCRIPTIONS S
     SET S.SUBSCRIPTION_ID=SUBSCRIPTION_ID,
         S.SERVICE_ID=SERVICE_ID,
         S.NAME=NAME,
         S.DESCRIPTION=DESCRIPTION
   WHERE S.SUBSCRIPTION_ID=OLD_SUBSCRIPTION_ID;
END;

--

CREATE PROCEDURE /*PREFIX*/D_SUBSCRIPTION
(
  IN OLD_SUBSCRIPTION_ID VARCHAR(32)
)
BEGIN
  DELETE FROM /*PREFIX*/SUBSCRIPTIONS
        WHERE SUBSCRIPTION_ID=OLD_SUBSCRIPTION_ID;
END;

--

CREATE TABLE /*PREFIX*/ACCOUNT_SUBSCRIPTIONS
(
  ACCOUNT_ID VARCHAR(32) NOT NULL,
  SUBSCRIPTION_ID VARCHAR(32) NOT NULL,
  DATE_BEGIN DATETIME NOT NULL,
  DATE_END DATETIME,
	ACCESS_TYPE INTEGER NOT NULL,
  PRIMARY KEY (ACCOUNT_ID,SUBSCRIPTION_ID),
  FOREIGN KEY (ACCOUNT_ID) REFERENCES /*PREFIX*/ACCOUNTS (ACCOUNT_ID),
  FOREIGN KEY (SUBSCRIPTION_ID) REFERENCES /*PREFIX*/SUBSCRIPTIONS (SUBSCRIPTION_ID)
)

--

CREATE VIEW /*PREFIX*/S_ACCOUNT_SUBSCRIPTIONS
AS
SELECT ACS.*,
       A.USER_NAME,
       S.NAME AS SUBSCRIPTION_NAME
  FROM /*PREFIX*/ACCOUNT_SUBSCRIPTIONS ACS
  JOIN /*PREFIX*/ACCOUNTS A ON A.ACCOUNT_ID=ACS.ACCOUNT_ID
  JOIN /*PREFIX*/SUBSCRIPTIONS S ON S.SUBSCRIPTION_ID=ACS.SUBSCRIPTION_ID

--

CREATE PROCEDURE /*PREFIX*/I_ACCOUNT_SUBSCRIPTION
(
  IN ACCOUNT_ID VARCHAR(32),
  IN SUBSCRIPTION_ID VARCHAR(32),
	IN DATE_BEGIN DATETIME,
	IN DATE_END DATETIME,
	IN ACCESS_TYPE INTEGER
)
BEGIN
  INSERT INTO /*PREFIX*/ACCOUNT_SUBSCRIPTIONS (ACCOUNT_ID,SUBSCRIPTION_ID,DATE_BEGIN,DATE_END,ACCESS_TYPE)
       VALUES (ACCOUNT_ID,SUBSCRIPTION_ID,DATE_BEGIN,DATE_END,ACCESS_TYPE);
END;

--

CREATE PROCEDURE /*PREFIX*/U_ACCOUNT_SUBSCRIPTION
(
  IN ACCOUNT_ID VARCHAR(32),
  IN SUBSCRIPTION_ID VARCHAR(32),
	IN DATE_BEGIN DATETIME,
	IN DATE_END DATETIME,
	IN ACCESS_TYPE INTEGER,
  IN OLD_ACCOUNT_ID VARCHAR(32),
  IN OLD_SUBSCRIPTION_ID VARCHAR(32)
)
BEGIN
  UPDATE /*PREFIX*/ACCOUNT_SUBSCRIPTIONS ACS
     SET ACS.ACCOUNT_ID=ACCOUNT_ID,
		     ACS.SUBSCRIPTION_ID=SUBSCRIPTION_ID,
				 ACS.DATE_BEGIN=DATE_BEGIN,
				 ACS.DATE_END=DATE_END,
				 ACS.ACCESS_TYPE=ACCESS_TYPE
   WHERE ACS.ACCOUNT_ID=OLD_ACCOUNT_ID
	   AND ACS.SUBSCRIPTION_ID=OLD_SUBSCRIPTION_ID;
END;

--

CREATE PROCEDURE /*PREFIX*/D_ACCOUNT_SUBSCRIPTION
(
  IN OLD_ACCOUNT_ID VARCHAR(32),
	IN OLD_SUBSCRIPTION_ID VARCHAR(32)
)
BEGIN
  DELETE FROM /*PREFIX*/ACCOUNT_SUBSCRIPTIONS 
        WHERE ACCOUNT_ID=OLD_ACCOUNT_ID
          AND SUBSCRIPTION_ID=OLD_SUBSCRIPTION_ID;
END;

--

CREATE TABLE /*PREFIX*/SUBSCRIPTION_CONTENTS
(
  SUBSCRIPTION_ID VARCHAR(32) NOT NULL,
  VIEW_ID VARCHAR(32) NOT NULL,
  TYPE_ID VARCHAR(32) NOT NULL,
  OPERATION_ID VARCHAR(32) NOT NULL,
  PUBLISHING_ID VARCHAR(32) NOT NULL,
  PRIMARY KEY (SUBSCRIPTION_ID,VIEW_ID,TYPE_ID,OPERATION_ID,PUBLISHING_ID),
  FOREIGN KEY (SUBSCRIPTION_ID) REFERENCES /*PREFIX*/SUBSCRIPTIONS (SUBSCRIPTION_ID),
  FOREIGN KEY (VIEW_ID) REFERENCES /*PREFIX*/VIEWS (VIEW_ID),
  FOREIGN KEY (TYPE_ID) REFERENCES /*PREFIX*/TYPES (TYPE_ID),
  FOREIGN KEY (OPERATION_ID) REFERENCES /*PREFIX*/OPERATIONS (OPERATION_ID),
  FOREIGN KEY (PUBLISHING_ID) REFERENCES /*PREFIX*/PUBLISHING (PUBLISHING_ID)
)

--

CREATE VIEW /*PREFIX*/S_SUBSCRIPTION_CONTENTS
AS
SELECT SC.*,
			 S.NAME AS SUBSCRIPTION_NAME,
			 V.NAME AS VIEW_NAME,
			 T.NAME AS TYPE_NAME,
			 O.NAME AS OPERATION_NAME,
			 PB.NAME AS PUBLISHING_NAME
  FROM /*PREFIX*/SUBSCRIPTION_CONTENTS SC
	JOIN /*PREFIX*/SUBSCRIPTIONS S ON S.SUBSCRIPTION_ID=SC.SUBSCRIPTION_ID
	JOIN /*PREFIX*/VIEWS V ON V.VIEW_ID=SC.VIEW_ID
	JOIN /*PREFIX*/TYPES T ON T.TYPE_ID=SC.TYPE_ID
	JOIN /*PREFIX*/OPERATIONS O ON O.OPERATION_ID=SC.OPERATION_ID
  JOIN /*PREFIX*/PUBLISHING PB ON PB.PUBLISHING_ID=SC.PUBLISHING_ID	

--

CREATE PROCEDURE /*PREFIX*/I_SUBSCRIPTION_CONTENT
(
  IN SUBSCRIPTION_ID VARCHAR(32),
  IN VIEW_ID VARCHAR(32),
  IN TYPE_ID VARCHAR(32),
  IN OPERATION_ID VARCHAR(32),
  IN PUBLISHING_ID VARCHAR(32)
)
BEGIN
  INSERT INTO /*PREFIX*/SUBSCRIPTION_CONTENTS (SUBSCRIPTION_ID,VIEW_ID,TYPE_ID,OPERATION_ID,PUBLISHING_ID)
       VALUES (SUBSCRIPTION_ID,VIEW_ID,TYPE_ID,OPERATION_ID,PUBLISHING_ID);
END;	

--

CREATE PROCEDURE /*PREFIX*/U_SUBSCRIPTION_CONTENT
(
  IN SUBSCRIPTION_ID VARCHAR(32),
  IN VIEW_ID VARCHAR(32),
  IN TYPE_ID VARCHAR(32),
  IN OPERATION_ID VARCHAR(32),
  IN PUBLISHING_ID VARCHAR(32),
  IN OLD_SUBSCRIPTION_ID VARCHAR(32),
  IN OLD_VIEW_ID VARCHAR(32),
  IN OLD_TYPE_ID VARCHAR(32),
  IN OLD_OPERATION_ID VARCHAR(32),
  IN OLD_PUBLISHING_ID VARCHAR(32)	
)
BEGIN
  UPDATE /*PREFIX*/SUBSCRIPTION_CONTENTS SC
     SET SC.SUBSCRIPTION_ID=SUBSCRIPTION_ID,
		     SC.VIEW_ID=VIEW_ID,
		     SC.TYPE_ID=TYPE_ID,
		     SC.OPERATION_ID=OPERATION_ID,
		     SC.PUBLISHING_ID=PUBLISHING_ID
   WHERE SC.SUBSCRIPTION_ID=OLD_SUBSCRIPTION_ID
	   AND SC.VIEW_ID=OLD_VIEW_ID
	   AND SC.TYPE_ID=OLD_TYPE_ID
	   AND SC.OPERATION_ID=OLD_OPERATION_ID
		 AND SC.PUBLISHING_ID=OLD_PUBLISHING_ID;
END;

--

CREATE PROCEDURE /*PREFIX*/D_SUBSCRIPTION_CONTENT
(
  IN OLD_SUBSCRIPTION_ID VARCHAR(32),
	IN OLD_VIEW_ID VARCHAR(32),
	IN OLD_TYPE_ID VARCHAR(32),
	IN OLD_OPERATION_ID VARCHAR(32),
	IN OLD_PUBLISHING_ID VARCHAR(32)
)
BEGIN
  DELETE FROM /*PREFIX*/SUBSCRIPTION_CONTENTS
        WHERE SUBSCRIPTION_ID=OLD_SUBSCRIPTION_ID
				  AND VIEW_ID=OLD_VIEW_ID
				  AND TYPE_ID=OLD_TYPE_ID
				  AND OPERATION_ID=OLD_OPERATION_ID
					AND PUBLISHING_ID=OLD_PUBLISHING_ID;
END;

--

ALTER TABLE ACCOUNT_PRESENTATIONS
ADD WEEKDAY INTEGER NOT NULL

--

DROP VIEW /*PREFIX*/S_ACCOUNT_PRESENTATIONS

--

CREATE VIEW /*PREFIX*/S_ACCOUNT_PRESENTATIONS
AS
SELECT AP.*,
			 A.USER_NAME,
			 V.NAME AS VIEW_NAME,
			 T.NAME AS TYPE_NAME,
			 O.NAME AS OPERATION_NAME,
			 P.NAME AS PRESENTATION_NAME,
			 PB.NAME AS PUBLISHING_NAME
  FROM /*PREFIX*/ACCOUNT_PRESENTATIONS AP
	JOIN /*PREFIX*/ACCOUNTS A ON A.ACCOUNT_ID=AP.ACCOUNT_ID
	JOIN /*PREFIX*/VIEWS V ON V.VIEW_ID=AP.VIEW_ID
	JOIN /*PREFIX*/TYPES T ON T.TYPE_ID=AP.TYPE_ID
	JOIN /*PREFIX*/OPERATIONS O ON O.OPERATION_ID=AP.OPERATION_ID
  JOIN /*PREFIX*/PRESENTATIONS P ON P.PRESENTATION_ID=AP.PRESENTATION_ID
  JOIN /*PREFIX*/PUBLISHING PB ON PB.PUBLISHING_ID=AP.PUBLISHING_ID	

--

DROP PROCEDURE /*PREFIX*/I_ACCOUNT_PRESENTATION

--

CREATE PROCEDURE /*PREFIX*/I_ACCOUNT_PRESENTATION
(
  IN ACCOUNT_ID VARCHAR(32),
  IN VIEW_ID VARCHAR(32),
  IN TYPE_ID VARCHAR(32),
  IN OPERATION_ID VARCHAR(32),
  IN PRESENTATION_ID VARCHAR(32),
  IN PUBLISHING_ID VARCHAR(32),
	IN WEEKDAY INTEGER
)
BEGIN
  INSERT INTO /*PREFIX*/ACCOUNT_PRESENTATIONS (ACCOUNT_ID,VIEW_ID,TYPE_ID,OPERATION_ID,
	                                             PRESENTATION_ID,PUBLISHING_ID,WEEKDAY)
       VALUES (ACCOUNT_ID,VIEW_ID,TYPE_ID,OPERATION_ID,
			         PRESENTATION_ID,PUBLISHING_ID,WEEKDAY);
END;	

--

DROP PROCEDURE /*PREFIX*/U_ACCOUNT_PRESENTATION

--

CREATE PROCEDURE /*PREFIX*/U_ACCOUNT_PRESENTATION
(
  IN ACCOUNT_ID VARCHAR(32),
  IN VIEW_ID VARCHAR(32),
  IN TYPE_ID VARCHAR(32),
  IN OPERATION_ID VARCHAR(32),
  IN PRESENTATION_ID VARCHAR(32),
  IN PUBLISHING_ID VARCHAR(32),
	IN WEEKDAY INTEGER,
  IN OLD_ACCOUNT_ID VARCHAR(32),
  IN OLD_VIEW_ID VARCHAR(32),
  IN OLD_TYPE_ID VARCHAR(32),
  IN OLD_OPERATION_ID VARCHAR(32),
  IN OLD_PUBLISHING_ID VARCHAR(32)	
)
BEGIN
  UPDATE /*PREFIX*/ACCOUNT_PRESENTATIONS AP
     SET AP.ACCOUNT_ID=ACCOUNT_ID,
		     AP.VIEW_ID=VIEW_ID,
		     AP.TYPE_ID=TYPE_ID,
		     AP.OPERATION_ID=OPERATION_ID,
		     AP.PRESENTATION_ID=PRESENTATION_ID,
		     AP.PUBLISHING_ID=PUBLISHING_ID,
				 AP.WEEKDAY=WEEKDAY
   WHERE AP.ACCOUNT_ID=OLD_ACCOUNT_ID
	   AND AP.VIEW_ID=OLD_VIEW_ID
	   AND AP.TYPE_ID=OLD_TYPE_ID
	   AND AP.OPERATION_ID=OLD_OPERATION_ID
		 AND AP.PUBLISHING_ID=OLD_PUBLISHING_ID;
END;

--

UPDATE ACCOUNT_PRESENTATIONS
SET WEEKDAY=5

--