ALTER TABLE /*PREFIX*/ACCOUNTS
ADD DATE_CREATE DATETIME 

--

UPDATE /*PREFIX*/ACCOUNTS
SET DATE_CREATE='2008-05-01'

--

ALTER TABLE /*PREFIX*/ACCOUNTS
MODIFY DATE_CREATE DATETIME NOT NULL

--

ALTER TABLE ACCOUNTS
ADD PHOTO LONGBLOB

--

DROP VIEW /*PREFIX*/S_ACCOUNTS

--

CREATE VIEW /*PREFIX*/S_ACCOUNTS
AS
   SELECT A.*, 
          F.SMALL_NAME AS FIRM_SMALL_NAME
     FROM /*PREFIX*/ACCOUNTS A
     LEFT JOIN /*PREFIX*/FIRMS F ON F.FIRM_ID=A.FIRM_ID

--

DROP PROCEDURE /*PREFIX*/I_ACCOUNT

--

CREATE PROCEDURE /*PREFIX*/I_ACCOUNT
(
  IN ACCOUNT_ID VARCHAR(32),
  IN FIRM_ID VARCHAR(32),
	IN DATE_CREATE DATETIME,
  IN USER_NAME VARCHAR(100),
  IN PASSWORD VARCHAR(100),
  IN DESCRIPTION VARCHAR(250),
  IN DB_USER_NAME VARCHAR(100),
  IN DB_PASSWORD VARCHAR(100),
  IN IS_ROLE INTEGER,
  IN LOCKED INTEGER,  
  IN AUTO_CREATED INTEGER,
  IN SURNAME VARCHAR(100),
  IN NAME VARCHAR(100),
  IN PATRONYMIC VARCHAR(100),
  IN PHONE VARCHAR(100),
  IN EMAIL VARCHAR(100),
	IN PHOTO LONGBLOB
)
BEGIN
  INSERT INTO /*PREFIX*/ACCOUNTS (ACCOUNT_ID,FIRM_ID,DATE_CREATE,USER_NAME,PASSWORD,DESCRIPTION,DB_USER_NAME,DB_PASSWORD,
	                                IS_ROLE,LOCKED,AUTO_CREATED,SURNAME,NAME,PATRONYMIC,PHONE,EMAIL,PHOTO)
       VALUES (ACCOUNT_ID,FIRM_ID,DATE_CREATE,USER_NAME,PASSWORD,DESCRIPTION,DB_USER_NAME,DB_PASSWORD,
	             IS_ROLE,LOCKED,AUTO_CREATED,SURNAME,NAME,PATRONYMIC,PHONE,EMAIL,PHOTO);
END;

--

DROP PROCEDURE /*PREFIX*/U_ACCOUNT

-

CREATE PROCEDURE /*PREFIX*/U_ACCOUNT
(
  IN ACCOUNT_ID VARCHAR(32),
  IN FIRM_ID VARCHAR(32),
	IN DATE_CREATE DATETIME,
  IN USER_NAME VARCHAR(100),
  IN PASSWORD VARCHAR(100),
  IN DESCRIPTION VARCHAR(250),
  IN DB_USER_NAME VARCHAR(100),
  IN DB_PASSWORD VARCHAR(100),
  IN IS_ROLE INTEGER,
  IN LOCKED INTEGER,  
  IN AUTO_CREATED INTEGER,
  IN SURNAME VARCHAR(100),
  IN NAME VARCHAR(100),
  IN PATRONYMIC VARCHAR(100),
  IN PHONE VARCHAR(100),
  IN EMAIL VARCHAR(100),
	IN PHOTO LONGBLOB,
  IN OLD_ACCOUNT_ID VARCHAR(32)
)
BEGIN
  UPDATE /*PREFIX*/ACCOUNTS A
     SET A.ACCOUNT_ID=ACCOUNT_ID,
         A.FIRM_ID=FIRM_ID,
				 A.DATE_CREATE=DATE_CREATE,
         A.USER_NAME=USER_NAME,
         A.PASSWORD=PASSWORD,
         A.DESCRIPTION=DESCRIPTION,
         A.DB_USER_NAME=DB_USER_NAME,
         A.DB_PASSWORD=DB_PASSWORD,
         A.IS_ROLE=IS_ROLE,
				 A.LOCKED=LOCKED,
				 A.AUTO_CREATED=AUTO_CREATED,
				 A.SURNAME=SURNAME,
				 A.NAME=NAME,
				 A.PATRONYMIC=PATRONYMIC,
				 A.PHONE=PHONE,
				 A.EMAIL=EMAIL,
				 A.PHOTO=PHOTO 
   WHERE A.ACCOUNT_ID=OLD_ACCOUNT_ID;
END;

--

ALTER TABLE /*PREFIX*/PARAMS
ADD MAX_LENGTH INTEGER

--

ALTER TABLE /*PREFIX*/PARAMS
ADD HINT VARCHAR(250)

--

DROP VIEW /*PREFIX*/S_PARAMS

--

CREATE VIEW /*PREFIX*/S_PARAMS
AS
SELECT * FROM /*PREFIX*/PARAMS

--

DROP PROCEDURE /*PREFIX*/I_PARAM

--

CREATE PROCEDURE /*PREFIX*/I_PARAM
(
  IN PARAM_ID VARCHAR(32),
  IN NAME VARCHAR(100),
  IN DESCRIPTION VARCHAR(250),
  IN PARAM_TYPE INTEGER,
  IN IS_NULL INTEGER,
  IN FORMAT VARCHAR(100),
	IN ELEMENT_TYPE INTEGER,
	IN MAX_LENGTH INTEGER,
	IN HINT VARCHAR(250)
)
BEGIN
  INSERT INTO /*PREFIX*/PARAMS (PARAM_ID,NAME,DESCRIPTION,PARAM_TYPE,IS_NULL,FORMAT,
	                              ELEMENT_TYPE,MAX_LENGTH,HINT)
       VALUES (PARAM_ID,NAME,DESCRIPTION,PARAM_TYPE,IS_NULL,FORMAT,
			         ELEMENT_TYPE,MAX_LENGTH,HINT);
END;

--

DROP PROCEDURE /*PREFIX*/U_PARAM

--

CREATE PROCEDURE /*PREFIX*/U_PARAM
(
  IN PARAM_ID VARCHAR(32),
  IN NAME VARCHAR(100),
  IN DESCRIPTION VARCHAR(250),
  IN PARAM_TYPE INTEGER,
  IN IS_NULL INTEGER,
  IN FORMAT VARCHAR(100),
	IN ELEMENT_TYPE INTEGER,
	IN MAX_LENGTH INTEGER,
	IN HINT VARCHAR(250),
  IN OLD_PARAM_ID VARCHAR(32)
)
BEGIN
  UPDATE /*PREFIX*/PARAMS P
     SET P.PARAM_ID=PARAM_ID,
         P.NAME=NAME,
	       P.DESCRIPTION=DESCRIPTION,
				 P.PARAM_TYPE=PARAM_TYPE,
				 P.IS_NULL=IS_NULL,
				 P.FORMAT=FORMAT,
				 P.ELEMENT_TYPE=ELEMENT_TYPE,
				 P.MAX_LENGTH=MAX_LENGTH,
				 P.HINT=HINT
   WHERE P.PARAM_ID=OLD_PARAM_ID;
END;

--

CREATE PROCEDURE /*PREFIX*/I_PUBLISHING_OBJECT2
(
  IN PUBLISHING_ID VARCHAR(32),
  IN OBJECT_ID VARCHAR(32),
	IN DATE_BEGIN DATETIME,
	IN DATE_END DATETIME
)
BEGIN
  INSERT INTO /*PREFIX*/PUBLISHING_OBJECTS (PUBLISHING_ID,OBJECT_ID,DATE_BEGIN,DATE_END)
       VALUES (PUBLISHING_ID,OBJECT_ID,DATE_BEGIN,DATE_END);
END;

--

