ALTER TABLE ACCOUNTS
ADD JOB_TITLE VARCHAR(250)

--

DROP VIEW S_ACCOUNTS

--

CREATE VIEW /*PREFIX*/S_ACCOUNTS
AS
   SELECT A.*, 
          F.SMALL_NAME AS FIRM_SMALL_NAME
     FROM /*PREFIX*/ACCOUNTS A
     LEFT JOIN /*PREFIX*/FIRMS F ON F.FIRM_ID=A.FIRM_ID

--

DROP PROCEDURE /*PREFIX*/I_ACCOUNT

--

CREATE PROCEDURE /*PREFIX*/I_ACCOUNT
(
  IN ACCOUNT_ID VARCHAR(32),
  IN FIRM_ID VARCHAR(32),
  IN DATE_CREATE DATETIME,
  IN USER_NAME VARCHAR(100),
  IN PASSWORD VARCHAR(100),
  IN DESCRIPTION VARCHAR(250),
  IN DB_USER_NAME VARCHAR(100),
  IN DB_PASSWORD VARCHAR(100),
  IN IS_ROLE INTEGER,
  IN LOCKED INTEGER,  
  IN AUTO_CREATED INTEGER,
  IN SURNAME VARCHAR(100),
  IN NAME VARCHAR(100),
  IN PATRONYMIC VARCHAR(100),
  IN PHONE VARCHAR(100),
  IN EMAIL VARCHAR(100),
  IN PHOTO LONGBLOB,
  IN JOB_TITLE VARCHAR(250)
)
BEGIN
  INSERT INTO /*PREFIX*/ACCOUNTS (ACCOUNT_ID,FIRM_ID,DATE_CREATE,USER_NAME,PASSWORD,DESCRIPTION,DB_USER_NAME,DB_PASSWORD,
	                                IS_ROLE,LOCKED,AUTO_CREATED,SURNAME,NAME,PATRONYMIC,PHONE,EMAIL,PHOTO,JOB_TITLE)
       VALUES (ACCOUNT_ID,FIRM_ID,DATE_CREATE,USER_NAME,PASSWORD,DESCRIPTION,DB_USER_NAME,DB_PASSWORD,
	             IS_ROLE,LOCKED,AUTO_CREATED,SURNAME,NAME,PATRONYMIC,PHONE,EMAIL,PHOTO,JOB_TITLE);
END;

--

DROP PROCEDURE /*PREFIX*/U_ACCOUNT

--

CREATE PROCEDURE /*PREFIX*/U_ACCOUNT
(
  IN ACCOUNT_ID VARCHAR(32),
  IN FIRM_ID VARCHAR(32),
	IN DATE_CREATE DATETIME,
  IN USER_NAME VARCHAR(100),
  IN PASSWORD VARCHAR(100),
  IN DESCRIPTION VARCHAR(250),
  IN DB_USER_NAME VARCHAR(100),
  IN DB_PASSWORD VARCHAR(100),
  IN IS_ROLE INTEGER,
  IN LOCKED INTEGER,  
  IN AUTO_CREATED INTEGER,
  IN SURNAME VARCHAR(100),
  IN NAME VARCHAR(100),
  IN PATRONYMIC VARCHAR(100),
  IN PHONE VARCHAR(100),
  IN EMAIL VARCHAR(100),
	IN PHOTO LONGBLOB,
  IN JOB_TITLE VARCHAR(250),
  IN OLD_ACCOUNT_ID VARCHAR(32)
)
BEGIN
  UPDATE /*PREFIX*/ACCOUNTS A
     SET A.ACCOUNT_ID=ACCOUNT_ID,
         A.FIRM_ID=FIRM_ID,
				 A.DATE_CREATE=DATE_CREATE,
         A.USER_NAME=USER_NAME,
         A.PASSWORD=PASSWORD,
         A.DESCRIPTION=DESCRIPTION,
         A.DB_USER_NAME=DB_USER_NAME,
         A.DB_PASSWORD=DB_PASSWORD,
         A.IS_ROLE=IS_ROLE,
				 A.LOCKED=LOCKED,
				 A.AUTO_CREATED=AUTO_CREATED,
				 A.SURNAME=SURNAME,
				 A.NAME=NAME,
				 A.PATRONYMIC=PATRONYMIC,
				 A.PHONE=PHONE,
				 A.EMAIL=EMAIL,
				 A.PHOTO=PHOTO,
         A.JOB_TITLE=JOB_TITLE
   WHERE A.ACCOUNT_ID=OLD_ACCOUNT_ID;
END;

--

/* Создание просмотра таблицы экспорта */

CREATE VIEW /*PREFIX*/S_EXPORTS
AS
  SELECT E.*,
         V.NAME AS VIEW_NAME,
         V.NUM AS VIEW_NUM,
         T.NAME AS TYPE_NAME,
         T.NUM AS TYPE_NUM,
         O.NAME AS OPERATION_NAME,
         O.NUM AS OPERATION_NUM,
         P.NAME AS PARAM_NAME,
         P.PARAM_TYPE,
         P.SORTING AS PARAM_SORTING,
         E1.NAME AS PARENT_NAME
    FROM /*PREFIX*/EXPORTS E
    LEFT JOIN /*PREFIX*/VIEWS V ON V.VIEW_ID=E.VIEW_ID
    LEFT JOIN /*PREFIX*/TYPES T ON T.TYPE_ID=E.TYPE_ID
    LEFT JOIN /*PREFIX*/OPERATIONS O ON O.OPERATION_ID=E.OPERATION_ID
    LEFT JOIN /*PREFIX*/PARAMS P ON P.PARAM_ID=E.PARAM_ID
    LEFT JOIN /*PREFIX*/EXPORTS E1 ON E1.EXPORT_ID=E.PARENT_ID


--

--

CREATE TABLE /*PREFIX*/DESIGNS
(
  DESIGN_ID VARCHAR(32) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(250),
  NUM VARCHAR(10) NOT NULL,
  PRIMARY KEY (DESIGN_ID)
)

--

CREATE VIEW /*PREFIX*/S_DESIGNS
AS
SELECT * FROM /*PREFIX*/DESIGNS

--

CREATE PROCEDURE /*PREFIX*/I_DESIGN
(
  IN DESIGN_ID VARCHAR(32),
  IN NAME VARCHAR(100),
  IN DESCRIPTION VARCHAR(250),
  IN NUM VARCHAR(10)
)
BEGIN
  INSERT INTO /*PREFIX*/DESIGNS (DESIGN_ID,NAME,DESCRIPTION,NUM)
       VALUES (DESIGN_ID,NAME,DESCRIPTION,NUM);
END;

--

CREATE PROCEDURE /*PREFIX*/U_DESIGN
(
  IN DESIGN_ID VARCHAR(32),
  IN NAME VARCHAR(100),
  IN DESCRIPTION VARCHAR(250),
  IN NUM VARCHAR(10),
  IN OLD_DESIGN_ID VARCHAR(32)
)
BEGIN
  UPDATE /*PREFIX*/DESIGNS V
     SET V.DESIGN_ID=DESIGN_ID,
         V.NAME=NAME,
	       V.DESCRIPTION=DESCRIPTION,
				 V.NUM=NUM
   WHERE V.DESIGN_ID=OLD_DESIGN_ID;
END;

--

CREATE PROCEDURE /*PREFIX*/D_DESIGN
(
  IN OLD_DESIGN_ID VARCHAR(32)
)
BEGIN
  DELETE FROM /*PREFIX*/DESIGNS 
        WHERE DESIGN_ID=OLD_DESIGN_ID;
END;

--

ALTER TABLE OBJECTS
ADD DESIGN_ID VARCHAR(32)

--

ALTER TABLE OBJECTS
ADD PRIORITY INTEGER

--

ALTER TABLE OBJECTS
ADD FOREIGN KEY (DESIGN_ID) REFERENCES DESIGNS (DESIGN_ID)

--

DROP VIEW S_OBJECTS

--

CREATE VIEW /*PREFIX*/S_OBJECTS
AS
   SELECT O.*, 
          A.USER_NAME,
          V.NAME AS VIEW_NAME,
          V.NUM AS VIEW_NUM,
	        T.NAME AS TYPE_NAME,
          T.NUM AS TYPE_NUM,
	        OP.NAME AS OPERATION_NAME,
          OP.NUM AS OPERATION_NUM,
          D.NAME AS DESIGN_NAME,
          D.NUM AS DESIGN_NUM
     FROM /*PREFIX*/OBJECTS O
     JOIN /*PREFIX*/ACCOUNTS A ON A.ACCOUNT_ID=O.ACCOUNT_ID
     JOIN /*PREFIX*/VIEWS V ON V.VIEW_ID=O.VIEW_ID
     JOIN /*PREFIX*/TYPES T ON T.TYPE_ID=O.TYPE_ID
     JOIN /*PREFIX*/OPERATIONS OP ON OP.OPERATION_ID=O.OPERATION_ID
     LEFT JOIN /*PREFIX*/DESIGNS D ON D.DESIGN_ID=O.DESIGN_ID

--

DROP PROCEDURE /*PREFIX*/I_OBJECT

--

CREATE PROCEDURE /*PREFIX*/I_OBJECT
(
  IN OBJECT_ID VARCHAR(32),
  IN ACCOUNT_ID VARCHAR(32),
  IN VIEW_ID VARCHAR(32),
  IN TYPE_ID VARCHAR(32),
  IN OPERATION_ID VARCHAR(32),
  IN STATUS INTEGER,
  IN DESIGN_ID VARCHAR(32),
  IN PRIORITY INTEGER
)
BEGIN
  INSERT INTO /*PREFIX*/OBJECTS (OBJECT_ID,ACCOUNT_ID,VIEW_ID,TYPE_ID,
                                 OPERATION_ID,STATUS,DESIGN_ID,PRIORITY)
       VALUES (OBJECT_ID,ACCOUNT_ID,VIEW_ID,TYPE_ID,
               OPERATION_ID,STATUS,DESIGN_ID,PRIORITY);
END;

--

DROP PROCEDURE /*PREFIX*/U_OBJECT

--

CREATE PROCEDURE /*PREFIX*/U_OBJECT
(
  IN OBJECT_ID VARCHAR(32),
  IN ACCOUNT_ID VARCHAR(32),
  IN VIEW_ID VARCHAR(32),
  IN TYPE_ID VARCHAR(32),
  IN OPERATION_ID VARCHAR(32),
  IN STATUS INTEGER,
  IN DESIGN_ID VARCHAR(32),
  IN PRIORITY INTEGER,
  IN OLD_OBJECT_ID VARCHAR(32)
)
BEGIN
  UPDATE /*PREFIX*/OBJECTS O
     SET O.OBJECT_ID=OBJECT_ID,
         O.ACCOUNT_ID=ACCOUNT_ID,
         O.VIEW_ID=VIEW_ID,
      	 O.TYPE_ID=TYPE_ID,
	       O.OPERATION_ID=OPERATION_ID,
	       O.STATUS=STATUS,
         O.DESIGN_ID=DESIGN_ID,
         O.PRIORITY=PRIORITY
   WHERE O.OBJECT_ID=OLD_OBJECT_ID;
END;

--

DROP PROCEDURE /*PREFIX*/D_OBJECT

--

CREATE PROCEDURE /*PREFIX*/D_OBJECT
(
  IN OLD_OBJECT_ID VARCHAR(32)
)
BEGIN
  DELETE FROM /*PREFIX*/OBJECTS
        WHERE OBJECT_ID=OLD_OBJECT_ID;
END;

--

DROP VIEW /*PREFIX*/S_PUBLISHING_OBJECTS

--

CREATE VIEW /*PREFIX*/S_PUBLISHING_OBJECTS
AS
SELECT PO.*,
       P.NAME AS PUBLISHING_NAME,
       O.ACCOUNT_ID,
       O.OPERATION_ID,
       O.TYPE_ID,
       O.VIEW_ID,
       O.DESIGN_ID, 
       O.STATUS,
       O.PRIORITY,
       A.USER_NAME,
       V.NAME AS VIEW_NAME,
       V.NUM AS VIEW_NUM,
       T.NAME AS TYPE_NAME,
       T.NUM AS TYPE_NUM,
       OP.NAME AS OPERATION_NAME,
       OP.NUM AS OPERATION_NUM,
       D.NAME AS DESIGN_NAME,
       D.NUM AS DESIGN_NUM       
  FROM /*PREFIX*/PUBLISHING_OBJECTS PO
  JOIN /*PREFIX*/PUBLISHING P ON P.PUBLISHING_ID=PO.PUBLISHING_ID
  JOIN /*PREFIX*/OBJECTS O ON O.OBJECT_ID=PO.OBJECT_ID
  JOIN /*PREFIX*/ACCOUNTS A ON A.ACCOUNT_ID=O.ACCOUNT_ID
  JOIN /*PREFIX*/VIEWS V ON V.VIEW_ID=O.VIEW_ID
  JOIN /*PREFIX*/TYPES T ON T.TYPE_ID=O.TYPE_ID
  JOIN /*PREFIX*/OPERATIONS OP ON OP.OPERATION_ID=O.OPERATION_ID
  LEFT JOIN /*PREFIX*/DESIGNS D ON D.DESIGN_ID=O.DESIGN_ID

--

DROP PROCEDURE /*PREFIX*/I_PUBLISHING_OBJECT

--

CREATE PROCEDURE /*PREFIX*/I_PUBLISHING_OBJECT
(
  IN PUBLISHING_ID VARCHAR(32),
  IN OBJECT_ID VARCHAR(32),
	IN DATE_BEGIN DATETIME,
	IN DATE_END DATETIME,
  IN ACCOUNT_ID VARCHAR(32),
  IN VIEW_ID VARCHAR(32),
  IN TYPE_ID VARCHAR(32),
  IN OPERATION_ID VARCHAR(32),
  IN STATUS INTEGER,
  IN DESIGN_ID VARCHAR(32),
  IN PRIORITY INTEGER
)
BEGIN
  INSERT INTO /*PREFIX*/OBJECTS (OBJECT_ID,ACCOUNT_ID,VIEW_ID,TYPE_ID,
                                 OPERATION_ID,STATUS,DESIGN_ID,PRIORITY)
       VALUES (OBJECT_ID,ACCOUNT_ID,VIEW_ID,TYPE_ID,
               OPERATION_ID,STATUS,DESIGN_ID,PRIORITY);

  INSERT INTO /*PREFIX*/PUBLISHING_OBJECTS (PUBLISHING_ID,OBJECT_ID,DATE_BEGIN,DATE_END)
       VALUES (PUBLISHING_ID,OBJECT_ID,DATE_BEGIN,DATE_END);
END;

--

DROP PROCEDURE /*PREFIX*/U_PUBLISHING_OBJECT

--

CREATE PROCEDURE /*PREFIX*/U_PUBLISHING_OBJECT
(
  IN PUBLISHING_ID VARCHAR(32),
  IN OBJECT_ID VARCHAR(32),
	IN DATE_BEGIN DATETIME,
	IN DATE_END DATETIME,
  IN ACCOUNT_ID VARCHAR(32),
  IN VIEW_ID VARCHAR(32),
  IN TYPE_ID VARCHAR(32),
  IN OPERATION_ID VARCHAR(32),
  IN STATUS INTEGER,
  IN DESIGN_ID VARCHAR(32),
  IN PRIORITY INTEGER,
  IN OLD_PUBLISHING_ID VARCHAR(32),
  IN OLD_OBJECT_ID VARCHAR(32)
)
BEGIN

 UPDATE /*PREFIX*/OBJECTS O
     SET O.OBJECT_ID=OBJECT_ID,
         O.ACCOUNT_ID=ACCOUNT_ID,
         O.VIEW_ID=VIEW_ID,
      	 O.TYPE_ID=TYPE_ID,
	       O.OPERATION_ID=OPERATION_ID,
	       O.STATUS=STATUS,
         O.DESIGN_ID=DESIGN_ID,
         O.PRIORITY=PRIORITY
   WHERE O.OBJECT_ID=OLD_OBJECT_ID;

  UPDATE /*PREFIX*/PUBLISHING_OBJECTS PO
     SET PO.PUBLISHING_ID=PUBLISHING_ID,
		     PO.OBJECT_ID=OBJECT_ID,
				 PO.DATE_BEGIN=DATE_BEGIN,
				 PO.DATE_END=DATE_END
   WHERE PO.PUBLISHING_ID=OLD_PUBLISHING_ID
	   AND PO.OBJECT_ID=OLD_OBJECT_ID;
END;

--

DROP PROCEDURE /*PREFIX*/D_PUBLISHING_OBJECT

--

CREATE PROCEDURE /*PREFIX*/D_PUBLISHING_OBJECT
(
  IN OLD_PUBLISHING_ID VARCHAR(32),
	IN OLD_OBJECT_ID VARCHAR(32)
)
BEGIN

  DELETE FROM /*PREFIX*/OBJECT_PARAMS
        WHERE OBJECT_ID=OLD_OBJECT_ID;

  DELETE FROM /*PREFIX*/PUBLISHING_OBJECTS 
        WHERE PUBLISHING_ID=OLD_PUBLISHING_ID
          AND OBJECT_ID=OLD_OBJECT_ID;

	DELETE FROM /*PREFIX*/OBJECTS
        WHERE OBJECT_ID=OLD_OBJECT_ID;
				
END;

--

ALTER TABLE OBJECT_PARAMS
ADD EXPORT VARCHAR(100)

--

DROP VIEW /*PREFIX*/S_OBJECT_PARAMS

--

CREATE VIEW /*PREFIX*/S_OBJECT_PARAMS
AS
SELECT OP.*,
       A.USER_NAME,
       P.NAME AS PARAM_NAME,
       P.DESCRIPTION AS PARAM_DESCRIPTION,
       P.PARAM_TYPE,
       P.MAX_LENGTH AS PARAM_MAX_LENGTH,
       P.SORTING AS PARAM_SORTING
  FROM /*PREFIX*/OBJECT_PARAMS OP
  JOIN /*PREFIX*/ACCOUNTS A ON A.ACCOUNT_ID=OP.ACCOUNT_ID
  JOIN /*PREFIX*/PARAMS P ON P.PARAM_ID=OP.PARAM_ID
  JOIN /*PREFIX*/OBJECTS O ON O.OBJECT_ID=OP.OBJECT_ID


--

CREATE TABLE /*PREFIX*/PATTERNS
(
  EXPORT_ID VARCHAR(32) NOT NULL,
  DESIGN_ID VARCHAR(32) NOT NULL,
  RTF LONGBLOB,
  PRIMARY KEY (EXPORT_ID,DESIGN_ID),
  FOREIGN KEY (EXPORT_ID) REFERENCES /*PREFIX*/EXPORTS (EXPORT_ID),
  FOREIGN KEY (DESIGN_ID) REFERENCES /*PREFIX*/DESIGNS (DESIGN_ID)
)

--

CREATE VIEW /*PREFIX*/S_PATTERNS
AS
SELECT P.*,
       E.NAME AS EXPORT_NAME,
       D.NAME AS DESIGN_NAME,
       D.NUM AS DESIGN_NUM
  FROM /*PREFIX*/PATTERNS P
  JOIN /*PREFIX*/EXPORTS E ON E.EXPORT_ID=P.EXPORT_ID
  JOIN /*PREFIX*/DESIGNS D ON D.DESIGN_ID=P.DESIGN_ID

--

CREATE PROCEDURE /*PREFIX*/I_PATTERN
(
  IN EXPORT_ID VARCHAR(32),
  IN DESIGN_ID VARCHAR(32),
  IN RTF LONGBLOB
)
BEGIN
  INSERT INTO /*PREFIX*/PATTERNS (EXPORT_ID,DESIGN_ID,RTF)
       VALUES (EXPORT_ID,DESIGN_ID,RTF);
END;

--

CREATE PROCEDURE /*PREFIX*/U_PATTERN
(
  IN EXPORT_ID VARCHAR(32),
  IN DESIGN_ID VARCHAR(32),
  IN RTF LONGBLOB,
  IN OLD_EXPORT_ID VARCHAR(32),
  IN OLD_DESIGN_ID VARCHAR(32)
)
BEGIN
  UPDATE /*PREFIX*/PATTERNS P
     SET P.EXPORT_ID=EXPORT_ID,
         P.DESIGN_ID=DESIGN_ID,
         P.RTF=RTF
   WHERE P.EXPORT_ID=OLD_EXPORT_ID
	   AND P.DESIGN_ID=OLD_DESIGN_ID;
END;

--

CREATE PROCEDURE /*PREFIX*/D_PATTERN
(
  IN OLD_EXPORT_ID VARCHAR(32),
	IN OLD_DESIGN_ID VARCHAR(32)
)
BEGIN
  DELETE FROM /*PREFIX*/PATTERNS 
        WHERE EXPORT_ID=OLD_EXPORT_ID
				  AND DESIGN_ID=OLD_DESIGN_ID;
END;

--

DROP VIEW S_OBJECT_PARAMS_EX

--

CREATE VIEW S_OBJECT_PARAMS_EX
AS
SELECT OP.*,
       P.NAME AS PARAM_NAME,
       P.PARAM_TYPE,
       P.MAX_LENGTH,
       O.ACCOUNT_ID AS OBJECT_ACCOUNT_ID,
       O.DESIGN_ID,
       O.VIEW_ID,
       O.TYPE_ID,
       O.OPERATION_ID,
       O.STATUS,
       O.PRIORITY,
       PO.PUBLISHING_ID,
       PO.DATE_BEGIN,
       PO.DATE_END
  FROM OBJECT_PARAMS OP
  JOIN PARAMS P ON P.PARAM_ID=OP.PARAM_ID
  JOIN OBJECTS O ON O.OBJECT_ID=OP.OBJECT_ID
  JOIN PUBLISHING_OBJECTS PO ON PO.OBJECT_ID=O.OBJECT_ID

--

