DROP VIEW /*PREFIX*/S_PARAM_VALUE_DEPENDS

--

CREATE VIEW /*PREFIX*/S_PARAM_VALUE_DEPENDS
AS
SELECT PVD.*,
       PV1.NAME AS WHAT_PARAM_VALUE_NAME,
       PV2.NAME AS FROM_PARAM_VALUE_NAME,
       PV1.EXPORT AS WHAT_PARAM_VALUE_EXPORT,
       PV2.EXPORT AS FROM_PARAM_VALUE_EXPORT,
			 PV1.PARAM_ID AS WHAT_PARAM_ID,
			 PV1.PRIORITY AS WHAT_PRIORITY,
			 PV2.PARAM_ID AS FROM_PARAM_ID,
			 PV2.PRIORITY AS FROM_PRIORITY,
			 P1.NAME AS WHAT_PARAM_NAME,
			 P2.NAME AS FROM_PARAM_NAME
  FROM /*PREFIX*/PARAM_VALUE_DEPENDS PVD
  JOIN /*PREFIX*/PARAM_VALUES PV1 ON PV1.PARAM_VALUE_ID=PVD.WHAT_PARAM_VALUE_ID
  JOIN /*PREFIX*/PARAM_VALUES PV2 ON PV2.PARAM_VALUE_ID=PVD.FROM_PARAM_VALUE_ID
	JOIN /*PREFIX*/PARAMS P1 ON P1.PARAM_ID=PV1.PARAM_ID
	JOIN /*PREFIX*/PARAMS P2 ON P2.PARAM_ID=PV2.PARAM_ID	

--
