ALTER TABLE ADVERTISMENTS
DROP PATH

--

ALTER TABLE ADVERTISMENTS
ADD LOCATION INTEGER NOT NULL

--

ALTER TABLE ADVERTISMENTS
ADD VALUE LONGBLOB NOT NULL

--

DROP VIEW /*PREFIX*/S_ADVERTISMENTS

--

CREATE VIEW /*PREFIX*/S_ADVERTISMENTS
AS
   SELECT A.*, 
          S.NAME AS SERVICE_NAME
     FROM /*PREFIX*/ADVERTISMENTS A
     JOIN /*PREFIX*/SERVICES S ON S.SERVICE_ID=A.SERVICE_ID

--

DROP PROCEDURE /*PREFIX*/I_ADVERTISMENT

--

CREATE PROCEDURE /*PREFIX*/I_ADVERTISMENT
(
  IN ADVERTISMENT_ID VARCHAR(32),
  IN SERVICE_ID VARCHAR(32),
	IN NAME VARCHAR(100),
	IN DESCRIPTION VARCHAR(250),
	IN ADVERTISMENT_TYPE INTEGER,
	IN LOCATION INTEGER,
	IN VALUE LONGBLOB,
	IN LINK VARCHAR(250)
)
BEGIN
  INSERT INTO /*PREFIX*/ADVERTISMENTS (ADVERTISMENT_ID,SERVICE_ID,NAME,DESCRIPTION,ADVERTISMENT_TYPE,
	                                     LOCATION,VALUE,LINK)
       VALUES (ADVERTISMENT_ID,SERVICE_ID,NAME,DESCRIPTION,ADVERTISMENT_TYPE,
			         LOCATION,VALUE,LINK);
END;

--

DROP PROCEDURE /*PREFIX*/U_ADVERTISMENT

--

CREATE PROCEDURE /*PREFIX*/U_ADVERTISMENT
(
  IN ADVERTISMENT_ID VARCHAR(32),
  IN SERVICE_ID VARCHAR(32),
	IN NAME VARCHAR(100),
	IN DESCRIPTION VARCHAR(250),
	IN ADVERTISMENT_TYPE INTEGER,
  IN LOCATION INTEGER,
	IN VALUE LONGBLOB,
	IN LINK VARCHAR(250),
  IN OLD_ADVERTISMENT_ID VARCHAR(32)
)
BEGIN
  UPDATE /*PREFIX*/ADVERTISMENTS A
     SET A.ADVERTISMENT_ID=ADVERTISMENT_ID,
         A.SERVICE_ID=SERVICE_ID,
         A.NAME=NAME,
         A.DESCRIPTION=DESCRIPTION,
				 A.ADVERTISMENT_TYPE=ADVERTISMENT_TYPE,
				 A.LOCATION=LOCATION,
				 A.VALUE=VALUE,
				 A.LINK=LINK
   WHERE A.ADVERTISMENT_ID=OLD_ADVERTISMENT_ID;
END;

--
