/* Создание таблицы приложений */

CREATE TABLE /*PREFIX*/APPLICATIONS
(
  APPLICATION_ID VARCHAR(32) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(250),
  LOCKED INTEGER DEFAULT 0 NOT NULL,
  PRIMARY KEY (APPLICATION_ID)
)

--

/* Создание просмотра таблицы приложений */

CREATE VIEW /*PREFIX*/S_APPLICATIONS
AS
SELECT * FROM /*PREFIX*/APPLICATIONS

--

/* Создание процедуры добавления приложения */

CREATE PROCEDURE /*PREFIX*/I_APPLICATION
(
  APPLICATION_ID VARCHAR(32),
  NAME VARCHAR(100),
  DESCRIPTION VARCHAR(250),
  LOCKED INTEGER
)
AS
BEGIN
  INSERT INTO /*PREFIX*/APPLICATIONS (APPLICATION_ID,NAME,DESCRIPTION,LOCKED)
       VALUES (:APPLICATION_ID,:NAME,:DESCRIPTION,:LOCKED);
END;

--

/* Создание процедуры изменения приложения */

CREATE PROCEDURE /*PREFIX*/U_APPLICATION
(
  APPLICATION_ID VARCHAR(32),
  NAME VARCHAR(100),
  DESCRIPTION VARCHAR(250),
  LOCKED INTEGER,
  OLD_APPLICATION_ID VARCHAR(32)
)
AS
BEGIN
  UPDATE /*PREFIX*/APPLICATIONS
     SET APPLICATION_ID=:APPLICATION_ID,
         NAME=:NAME,
         DESCRIPTION=:DESCRIPTION,
         LOCKED=:LOCKED
   WHERE APPLICATION_ID=:OLD_APPLICATION_ID;
END;

--

/* Создание процедуры удаления приложения */

CREATE PROCEDURE /*PREFIX*/D_APPLICATION
(
  OLD_APPLICATION_ID VARCHAR(32)
)
AS
BEGIN
  DELETE FROM /*PREFIX*/APPLICATIONS 
        WHERE APPLICATION_ID=:OLD_APPLICATION_ID;
END;

--

/* Фиксация изменений */

COMMIT