/* Создание таблицы предприятий */

CREATE TABLE /*PREFIX*/FIRMS
(
  FIRM_ID VARCHAR(32) NOT NULL,
  FIRM_TYPE_ID VARCHAR(32) NOT NULL,
  PARENT_ID VARCHAR(32),
  SMALL_NAME VARCHAR(250) NOT NULL,
  FULL_NAME VARCHAR(250) NOT NULL,
  INN VARCHAR(12),
  PAYMENT_ACCOUNT VARCHAR(20),
  BANK VARCHAR(250),
  BIK VARCHAR(20),
  CORR_ACCOUNT VARCHAR(20),
  PHONE VARCHAR(250),
  FAX VARCHAR(250),
  EMAIL VARCHAR(100),
  SITE VARCHAR(100),
  OKONH VARCHAR(20),
  OKPO VARCHAR(20),
  KPP VARCHAR(20),
  DIRECTOR VARCHAR(250),
  ACCOUNTANT VARCHAR(250),
  CONTACT_FACE VARCHAR(250),
  INDEX_LEGAL VARCHAR(10),
  STREET_LEGAL_ID VARCHAR(32),
  HOUSE_LEGAL VARCHAR(10),
  FLAT_LEGAL VARCHAR(10),
  INDEX_POST VARCHAR(10),
  STREET_POST_ID VARCHAR(32),
  HOUSE_POST VARCHAR(10),
  FLAT_POST VARCHAR(10),
  PRIMARY KEY (FIRM_ID),
  FOREIGN KEY (FIRM_TYPE_ID) REFERENCES /*PREFIX*/FIRM_TYPES (FIRM_TYPE_ID),
  FOREIGN KEY (STREET_LEGAL_ID) REFERENCES /*PREFIX*/STREETS (STREET_ID),
  FOREIGN KEY (STREET_POST_ID) REFERENCES /*PREFIX*/STREETS (STREET_ID),
  FOREIGN KEY (PARENT_ID) REFERENCES FIRMS/*PREFIX*/ (FIRM_ID)  
)

--

/* Создание просмотра таблицы предприятий */

CREATE VIEW /*PREFIX*/S_FIRMS
(
  FIRM_ID,
  FIRM_TYPE_ID,
  PARENT_ID,
  SMALL_NAME,
  FULL_NAME,
  INN,
  PAYMENT_ACCOUNT,
  BANK,
  BIK,
  CORR_ACCOUNT,
  PHONE,
  FAX,
  EMAIL,
  SITE,
  OKONH,
  OKPO,
  KPP,
  DIRECTOR,
  ACCOUNTANT,
  CONTACT_FACE,
  INDEX_LEGAL,
  STREET_LEGAL_ID,
  HOUSE_LEGAL,
  FLAT_LEGAL,
  INDEX_POST,
  STREET_POST_ID,
  HOUSE_POST,
  FLAT_POST,
  FIRM_TYPE_NAME,
  PARENT_SMALL_NAME,
  STREET_LEGAL_NAME,
  STREET_LEGAL_PREFIX,
  LOCALITY_LEGAL_ID,
  LOCALITY_LEGAL_NAME,
  LOCALITY_LEGAL_PREFIX,
  STREET_POST_NAME,
  STREET_POST_PREFIX,
  LOCALITY_POST_ID,
  LOCALITY_POST_NAME,
  LOCALITY_POST_PREFIX
)
AS
  SELECT F.*,
         FT.NAME AS FIRM_TYPE_NAME,
         F1.SMALL_NAME AS PARENT_SMALL_NAME,
         S1.NAME AS STREET_LEGAL_NAME,
         S1.PREFIX AS STREET_LEGAL_PREFIX,
         L1.LOCALITY_ID AS LOCALITY_LEGAL_ID,
         L1.NAME AS LOCALITY_LEGAL_NAME,
         L1.PREFIX AS LOCALITY_LEGAL_PREFIX,
         S2.NAME AS STREET_POST_NAME,
         S2.PREFIX AS STREET_POST_PREFIX,
         L2.LOCALITY_ID AS LOCALITY_POST_ID,
         L2.NAME AS LOCALITY_POST_NAME,
         L2.PREFIX AS LOCALITY_POST_PREFIX
    FROM /*PREFIX*/FIRMS F
    JOIN /*PREFIX*/FIRM_TYPES FT ON FT.FIRM_TYPE_ID=F.FIRM_TYPE_ID
    LEFT JOIN /*PREFIX*/STREETS S1 ON S1.STREET_ID=F.STREET_LEGAL_ID
    LEFT JOIN /*PREFIX*/LOCALITIES L1 ON L1.LOCALITY_ID=S1.LOCALITY_ID
    LEFT JOIN /*PREFIX*/STREETS S2 ON S2.STREET_ID=F.STREET_POST_ID
    LEFT JOIN /*PREFIX*/LOCALITIES L2 ON L2.LOCALITY_ID=S2.LOCALITY_ID
    LEFT JOIN /*PREFIX*/FIRMS F1 ON F1.FIRM_ID=F.PARENT_ID

--

/* Создание процедуры добавления предприятия */

CREATE PROCEDURE /*PREFIX*/I_FIRM
(
  FIRM_ID VARCHAR(32),
  FIRM_TYPE_ID VARCHAR(32),
  PARENT_ID VARCHAR(32),
  SMALL_NAME VARCHAR(250),
  FULL_NAME VARCHAR(250),
  INN VARCHAR(12),
  PAYMENT_ACCOUNT VARCHAR(20),
  BANK VARCHAR(250),
  BIK VARCHAR(20),
  CORR_ACCOUNT VARCHAR(20),
  PHONE VARCHAR(250),
  FAX VARCHAR(250),
  EMAIL VARCHAR(100),
  SITE VARCHAR(100),
  OKONH VARCHAR(20),
  OKPO VARCHAR(20),
  KPP VARCHAR(20),
  DIRECTOR VARCHAR(250),
  ACCOUNTANT VARCHAR(250),
  CONTACT_FACE VARCHAR(250),
  INDEX_LEGAL VARCHAR(10),
  STREET_LEGAL_ID VARCHAR(32),
  HOUSE_LEGAL VARCHAR(10),
  FLAT_LEGAL VARCHAR(10),
  INDEX_POST VARCHAR(10),
  STREET_POST_ID VARCHAR(32),
  HOUSE_POST VARCHAR(10),
  FLAT_POST VARCHAR(10)
)
AS
BEGIN
  INSERT INTO /*PREFIX*/FIRMS (FIRM_ID,FIRM_TYPE_ID,PARENT_ID,SMALL_NAME,FULL_NAME,INN,PAYMENT_ACCOUNT,
                               BANK,BIK,CORR_ACCOUNT,PHONE,FAX,EMAIL,SITE,OKONH,OKPO,KPP,DIRECTOR,ACCOUNTANT,
                               CONTACT_FACE,INDEX_LEGAL,STREET_LEGAL_ID,HOUSE_LEGAL,FLAT_LEGAL,
                               INDEX_POST,STREET_POST_ID,HOUSE_POST,FLAT_POST)
       VALUES (:FIRM_ID,:FIRM_TYPE_ID,:PARENT_ID,:SMALL_NAME,:FULL_NAME,:INN,:PAYMENT_ACCOUNT,
               :BANK,:BIK,:CORR_ACCOUNT,:PHONE,:FAX,:EMAIL,:SITE,:OKONH,:OKPO,:KPP,:DIRECTOR,:ACCOUNTANT,
               :CONTACT_FACE,:INDEX_LEGAL,:STREET_LEGAL_ID,:HOUSE_LEGAL,:FLAT_LEGAL,
               :INDEX_POST,:STREET_POST_ID,:HOUSE_POST,:FLAT_POST);
END;

--

/* Создание процедуры изменения предприятия */

CREATE PROCEDURE /*PREFIX*/U_FIRM
(
  FIRM_ID VARCHAR(32),
  FIRM_TYPE_ID VARCHAR(32),
  PARENT_ID VARCHAR(32),
  SMALL_NAME VARCHAR(250),
  FULL_NAME VARCHAR(250),
  INN VARCHAR(12),
  PAYMENT_ACCOUNT VARCHAR(20),
  BANK VARCHAR(250),
  BIK VARCHAR(20),
  CORR_ACCOUNT VARCHAR(20),
  PHONE VARCHAR(250),
  FAX VARCHAR(250),
  EMAIL VARCHAR(100),
  SITE VARCHAR(100),
  OKONH VARCHAR(20),
  OKPO VARCHAR(20),
  KPP VARCHAR(20),
  DIRECTOR VARCHAR(250),
  ACCOUNTANT VARCHAR(250),
  CONTACT_FACE VARCHAR(250),
  INDEX_LEGAL VARCHAR(10),
  STREET_LEGAL_ID VARCHAR(32),
  HOUSE_LEGAL VARCHAR(10),
  FLAT_LEGAL VARCHAR(10),
  INDEX_POST VARCHAR(10),
  STREET_POST_ID VARCHAR(32),
  HOUSE_POST VARCHAR(10),
  FLAT_POST VARCHAR(10),
  OLD_FIRM_ID VARCHAR(32)
)
AS
BEGIN
  UPDATE /*PREFIX*/FIRMS
     SET FIRM_ID=:FIRM_ID,
         FIRM_TYPE_ID=:FIRM_TYPE_ID,
         PARENT_ID=:PARENT_ID,
         SMALL_NAME=:SMALL_NAME,
         FULL_NAME=:FULL_NAME,
         INN=:INN,
         PAYMENT_ACCOUNT=:PAYMENT_ACCOUNT,
         BANK=:BANK,
         BIK=:BIK,
         CORR_ACCOUNT=:CORR_ACCOUNT,
         PHONE=:PHONE,
         FAX=:FAX,
         EMAIL=:EMAIL,
         SITE=:SITE,
         OKONH=:OKONH,
         OKPO=:OKPO,
         KPP=:KPP,
         DIRECTOR=:DIRECTOR,
         ACCOUNTANT=:ACCOUNTANT,
         CONTACT_FACE=:CONTACT_FACE,
         INDEX_LEGAL=:INDEX_LEGAL,
         STREET_LEGAL_ID=:STREET_LEGAL_ID,
         HOUSE_LEGAL=:HOUSE_LEGAL,
         FLAT_LEGAL=:FLAT_LEGAL,
         INDEX_POST=:INDEX_POST,
         STREET_POST_ID=:STREET_POST_ID,
         HOUSE_POST=:HOUSE_POST,
         FLAT_POST=:FLAT_POST
   WHERE FIRM_ID=:OLD_FIRM_ID;
END;

--

/* Создание процедуры удаления предприятия */

CREATE PROCEDURE /*PREFIX*/D_FIRM
(
  OLD_FIRM_ID VARCHAR(32)
)
AS
BEGIN
  DELETE FROM /*PREFIX*/FIRMS
        WHERE FIRM_ID=:OLD_FIRM_ID;
END;

--

/* Фиксация изменений */

COMMIT