/* Создание таблицы сессий */

CREATE TABLE /*PREFIX*/SESSIONS
(
  SESSION_ID VARCHAR(32) NOT NULL,
  ACCOUNT_ID VARCHAR(32) NOT NULL,
  APPLICATION_ID VARCHAR(32) NOT NULL,
  DATE_CREATE TIMESTAMP NOT NULL,
  DATE_CHANGE TIMESTAMP NOT NULL,
  PARAMS BLOB,
  PRIMARY KEY (SESSION_ID),
  FOREIGN KEY (ACCOUNT_ID) REFERENCES /*PREFIX*/ACCOUNTS (ACCOUNT_ID),
  FOREIGN KEY (APPLICATION_ID) REFERENCES /*PREFIX*/APPLICATIONS (APPLICATION_ID)
)

--

/* Создание просмотра таблицы сессий */

CREATE VIEW /*PREFIX*/S_SESSIONS
(
  SESSION_ID,
  ACCOUNT_ID,
  APPLICATION_ID,
  DATE_CREATE,
  DATE_CHANGE,
  PARAMS,
  USER_NAME,
  APPLICATION_NAME
)
AS
   SELECT S.*, 
          AC.USER_NAME AS USER_NAME,
          AP.NAME AS APPLICATION_NAME
     FROM /*PREFIX*/SESSIONS S
     JOIN /*PREFIX*/ACCOUNTS AC ON AC.ACCOUNT_ID=S.ACCOUNT_ID
     JOIN /*PREFIX*/APPLICATIONS AP ON AP.APPLICATION_ID=S.APPLICATION_ID

--

/* Создание процедуры добавления сессии */

CREATE PROCEDURE /*PREFIX*/I_SESSION
(
  SESSION_ID VARCHAR(32),
  ACCOUNT_ID VARCHAR(32),
  APPLICATION_ID VARCHAR(32),
  DATE_CREATE TIMESTAMP,
  DATE_CHANGE TIMESTAMP,
  PARAMS BLOB
)
AS
BEGIN
  INSERT INTO /*PREFIX*/SESSIONS (SESSION_ID,ACCOUNT_ID,APPLICATION_ID,DATE_CREATE,DATE_CHANGE,PARAMS)
       VALUES (:SESSION_ID,:ACCOUNT_ID,:APPLICATION_ID,:DATE_CREATE,:DATE_CHANGE,:PARAMS);
END;

--

/* Создание процедуры изменения сессии */

CREATE PROCEDURE /*PREFIX*/U_SESSION
(
  SESSION_ID VARCHAR(32),
  ACCOUNT_ID VARCHAR(32),
  APPLICATION_ID VARCHAR(32),
  DATE_CREATE TIMESTAMP,
  DATE_CHANGE TIMESTAMP,
  PARAMS BLOB,
  OLD_SESSION_ID VARCHAR(32)
)
AS
BEGIN
  UPDATE /*PREFIX*/SESSIONS
     SET SESSION_ID=:SESSION_ID,
         ACCOUNT_ID=:ACCOUNT_ID,
         APPLICATION_ID=:APPLICATION_ID,
         DATE_CREATE=:DATE_CREATE,
         DATE_CHANGE=:DATE_CHANGE,
         PARAMS=:PARAMS
   WHERE SESSION_ID=:OLD_SESSION_ID;
END;

--

/* Создание процедуры удаления сессии */

CREATE PROCEDURE /*PREFIX*/D_SESSION
(
  OLD_SESSION_ID VARCHAR(32)
)
AS
BEGIN
  DELETE FROM /*PREFIX*/SESSIONS
        WHERE SESSION_ID=:OLD_SESSION_ID;
END;

--

/* Фиксация изменений */

COMMIT