/* Создание таблицы интерфейсов */

CREATE TABLE /*PREFIX*/INTERFACES
(
  INTERFACE_ID VARCHAR(32) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(250),
  INTERFACE_TYPE INTEGER NOT NULL, 
  "MODULE_NAME" VARCHAR(100),
  MODULE_INTERFACE VARCHAR(250),
  PRIMARY KEY (INTERFACE_ID)
)

--

/* Создание просмотра таблицы интерфейсов */

CREATE VIEW /*PREFIX*/S_INTERFACES
AS
SELECT * FROM /*PREFIX*/INTERFACES

--

/* Создание процедуры добавления интерфейса */

CREATE PROCEDURE /*PREFIX*/I_INTERFACE
(
  INTERFACE_ID VARCHAR(32),
  NAME VARCHAR(100),
  DESCRIPTION VARCHAR(250),
  INTERFACE_TYPE INTEGER,
  "MODULE_NAME" VARCHAR(100),
  MODULE_INTERFACE VARCHAR(250)
)
AS
BEGIN
  INSERT INTO /*PREFIX*/INTERFACES (INTERFACE_ID,NAME,DESCRIPTION,INTERFACE_TYPE,
                                    "MODULE_NAME",MODULE_INTERFACE)
       VALUES (:INTERFACE_ID,:NAME,:DESCRIPTION,:INTERFACE_TYPE,
               :"MODULE_NAME",:MODULE_INTERFACE);
END;

--

/* Создание процедуры изменения интерфейса */

CREATE PROCEDURE /*PREFIX*/U_INTERFACE
(
  INTERFACE_ID VARCHAR(32),
  NAME VARCHAR(100),
  DESCRIPTION VARCHAR(250),
  INTERFACE_TYPE INTEGER,
  "MODULE_NAME" VARCHAR(100),
  MODULE_INTERFACE VARCHAR(250),
  OLD_INTERFACE_ID VARCHAR(32)
)
AS
BEGIN
  UPDATE /*PREFIX*/INTERFACES
     SET INTERFACE_ID=:INTERFACE_ID,
         NAME=:NAME,
         DESCRIPTION=:DESCRIPTION,
         INTERFACE_TYPE=:INTERFACE_TYPE,
         "MODULE_NAME"=:"MODULE_NAME",
         MODULE_INTERFACE=:MODULE_INTERFACE
   WHERE INTERFACE_ID=:OLD_INTERFACE_ID;
END;

--

/* Создание процедуры удаления интерфейса */

CREATE PROCEDURE /*PREFIX*/D_INTERFACE
(
  OLD_INTERFACE_ID VARCHAR(32)
)
AS
BEGIN
  DELETE FROM /*PREFIX*/INTERFACES 
        WHERE INTERFACE_ID=:OLD_INTERFACE_ID;
END;

--

/* Фиксация изменений */

COMMIT