/* Создание таблицы обмена */

CREATE TABLE /*PREFIX*/EXCHANGES
(
  EXCHANGE_ID VARCHAR(32) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(250),
  SCRIPT BLOB,
  SOURCE VARCHAR(100) NOT NULL,
  SOURCE_BEFORE BLOB,
  SOURCE_AFTER BLOB,
  DESTINATION VARCHAR(100) NOT NULL,
  DESTINATION_BEFORE BLOB,
  DESTINATION_AFTER BLOB,
  PRIORITY INTEGER,
  ENABLED INTEGER NOT NULL,
  PRIMARY KEY (EXCHANGE_ID)
)

--

/* Создание просмотра таблицы обмена */

CREATE VIEW /*PREFIX*/S_EXCHANGES
AS
  SELECT *
    FROM /*PREFIX*/EXCHANGES

--

/* Создание процедуры добавления обмена */

CREATE PROCEDURE /*PREFIX*/I_EXCHANGE
(
  EXCHANGE_ID VARCHAR(32),
  NAME VARCHAR(100),
  DESCRIPTION VARCHAR(250),
  SCRIPT BLOB,
  SOURCE VARCHAR(100),
  SOURCE_BEFORE BLOB,
  SOURCE_AFTER BLOB,
  DESTINATION VARCHAR(100),
  DESTINATION_BEFORE BLOB,
  DESTINATION_AFTER BLOB,
  PRIORITY INTEGER,
  ENABLED INTEGER
)
AS
BEGIN
  INSERT INTO /*PREFIX*/EXCHANGES (EXCHANGE_ID,NAME,DESCRIPTION,SCRIPT,
                                   SOURCE,SOURCE_BEFORE,SOURCE_AFTER,
                                   DESTINATION,DESTINATION_BEFORE,DESTINATION_AFTER,
                                   PRIORITY,ENABLED)
       VALUES (:EXCHANGE_ID,:NAME,:DESCRIPTION,:SCRIPT,
               :SOURCE,:SOURCE_BEFORE,:SOURCE_AFTER,
               :DESTINATION,:DESTINATION_BEFORE,:DESTINATION_AFTER,
               :PRIORITY,:ENABLED);
END;

--

/* Создание процедуры изменения обмена */

CREATE PROCEDURE /*PREFIX*/U_EXCHANGE
(
  EXCHANGE_ID VARCHAR(32),
  NAME VARCHAR(100),
  DESCRIPTION VARCHAR(250),
  SCRIPT BLOB,
  SOURCE VARCHAR(100),
  SOURCE_BEFORE BLOB,
  SOURCE_AFTER BLOB,
  DESTINATION VARCHAR(100),
  DESTINATION_BEFORE BLOB,
  DESTINATION_AFTER BLOB,
  PRIORITY INTEGER,
  ENABLED INTEGER,
  OLD_EXCHANGE_ID VARCHAR(32)
)
AS
BEGIN
  UPDATE /*PREFIX*/EXCHANGES
     SET EXCHANGE_ID=:EXCHANGE_ID,
         NAME=:NAME,
         DESCRIPTION=:DESCRIPTION,
         SCRIPT=:SCRIPT,
         SOURCE=:SOURCE,
         SOURCE_BEFORE=:SOURCE_BEFORE,
         SOURCE_AFTER=:SOURCE_AFTER,
         DESTINATION=:DESTINATION,
         DESTINATION_BEFORE=:DESTINATION_BEFORE,
         DESTINATION_AFTER=:DESTINATION_AFTER,
         PRIORITY=:PRIORITY,
         ENABLED=:ENABLED
   WHERE EXCHANGE_ID=:OLD_EXCHANGE_ID;
END;

--

/* Создание процедуры удаления обмена */

CREATE PROCEDURE /*PREFIX*/D_EXCHANGE
(
  OLD_EXCHANGE_ID VARCHAR(32)
)
AS
BEGIN
  DELETE FROM /*PREFIX*/EXCHANGES
        WHERE EXCHANGE_ID=:OLD_EXCHANGE_ID;
END;

--

/* Фиксация изменений */

COMMIT