/* Создание таблицы типов автомобилей */

CREATE TABLE /*PREFIX*/CAR_TYPES
(
  CAR_TYPE_ID VARCHAR(32) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(250),
  FONT_COLOR INTEGER,
  BRUSH_COLOR INTEGER,
  RATIO NUMERIC(4,2) NOT NULL,
  COST_IDLE NUMERIC(15,2) NOT NULL,
  PRIORITY INTEGER,
  PRIMARY KEY (CAR_TYPE_ID)
)

--

/* Создание просмотра типов автомобилей */

CREATE VIEW /*PREFIX*/S_CAR_TYPES
AS
SELECT * FROM /*PREFIX*/CAR_TYPES

--

/* Создание процедуры добавления типа автомобиля */

CREATE PROCEDURE /*PREFIX*/I_CAR_TYPE
(
  CAR_TYPE_ID VARCHAR(32),
  NAME VARCHAR(100),
  DESCRIPTION VARCHAR(250),
  FONT_COLOR INTEGER,
  BRUSH_COLOR INTEGER,
  RATIO NUMERIC(4,2),
  COST_IDLE NUMERIC(15,2),
  PRIORITY INTEGER
)
AS
BEGIN
  INSERT INTO /*PREFIX*/CAR_TYPES (CAR_TYPE_ID,NAME,DESCRIPTION,FONT_COLOR,BRUSH_COLOR,
                                   RATIO,COST_IDLE,PRIORITY)
       VALUES (:CAR_TYPE_ID,:NAME,:DESCRIPTION,:FONT_COLOR,:BRUSH_COLOR,
               :RATIO,:PRIORITY,:COST_IDLE);
END;

--

/* Создание процедуры изменения типа автомобиля */

CREATE PROCEDURE /*PREFIX*/U_CAR_TYPE
(
  CAR_TYPE_ID VARCHAR(32),
  NAME VARCHAR(100),
  DESCRIPTION VARCHAR(250),
  FONT_COLOR INTEGER,
  BRUSH_COLOR INTEGER,
  RATIO NUMERIC(4,2),
  COST_IDLE NUMERIC(15,2),
  PRIORITY INTEGER,
  OLD_CAR_TYPE_ID VARCHAR(32)
)
AS
BEGIN
  UPDATE /*PREFIX*/CAR_TYPES
     SET CAR_TYPE_ID=:CAR_TYPE_ID,
         NAME=:NAME,
         DESCRIPTION=:DESCRIPTION,
         FONT_COLOR=:FONT_COLOR,
         BRUSH_COLOR=:BRUSH_COLOR,
         RATIO=:RATIO,
         COST_IDLE=:COST_IDLE,
         PRIORITY=:PRIORITY
   WHERE CAR_TYPE_ID=:OLD_CAR_TYPE_ID;
END;

--

/* Создание процедуры удаления типа автомобиля */

CREATE PROCEDURE /*PREFIX*/D_CAR_TYPE
(
  OLD_CAR_TYPE_ID VARCHAR(32)
)
AS
BEGIN
  DELETE FROM /*PREFIX*/CAR_TYPES 
        WHERE CAR_TYPE_ID=:OLD_CAR_TYPE_ID;
END;

--

/* Фиксация изменений */

COMMIT