/* Создание таблицы автомобилей */

CREATE TABLE /*PREFIX*/CARS
(
  CAR_ID VARCHAR(32) NOT NULL,
  CAR_TYPE_ID VARCHAR(32) NOT NULL,
  STATE_NUM VARCHAR(50) NOT NULL,
  CALLSIGN VARCHAR(10),
  DESCRIPTION VARCHAR(250),
  BRAND VARCHAR(100) NOT NULL,
  COLOR VARCHAR(100) NOT NULL,
  YEAR_CREATED INTEGER,
  PTS VARCHAR(250),
  PAYLOAD INTEGER,
  AMOUNT INTEGER,
  PRIMARY KEY (CAR_ID),
  FOREIGN KEY (CAR_TYPE_ID) REFERENCES CAR_TYPES (CAR_TYPE_ID)
)

--

/* Создание просмотра автомобилей */

CREATE VIEW /*PREFIX*/S_CARS
(
  CAR_ID,
  CAR_TYPE_ID,
  STATE_NUM,
  CALLSIGN,
  DESCRIPTION,
  BRAND,
  COLOR,
  YEAR_CREATED,
  PTS,
  PAYLOAD,
  AMOUNT,
  CAR_TYPE_NAME,
  CAR_TYPE_FONT_COLOR,
  CAR_TYPE_BRUSH_COLOR
)
AS
  SELECT C.*,
         CT.NAME AS CAR_TYPE_NAME,
         CT.FONT_COLOR AS CAR_TYPE_FONT_COLOR,
         CT.BRUSH_COLOR AS CAR_TYPE_BRUSH_COLOR
    FROM /*PREFIX*/CARS C
    JOIN /*PREFIX*/CAR_TYPES CT ON CT.CAR_TYPE_ID=C.CAR_TYPE_ID

--

/* Создание процедуры добавления автомобиля */

CREATE PROCEDURE /*PREFIX*/I_CAR
(
  CAR_ID VARCHAR(32),
  CAR_TYPE_ID VARCHAR(32),
  STATE_NUM VARCHAR(50),
  CALLSIGN VARCHAR(10),
  DESCRIPTION VARCHAR(250),
  BRAND VARCHAR(100),
  COLOR VARCHAR(100),
  YEAR_CREATED INTEGER,
  PTS VARCHAR(250),
  PAYLOAD INTEGER,
  AMOUNT INTEGER
)
AS
BEGIN
  INSERT INTO /*PREFIX*/CARS (CAR_ID,CAR_TYPE_ID,STATE_NUM,CALLSIGN,DESCRIPTION,
                              BRAND,COLOR,YEAR_CREATED,PTS,PAYLOAD,AMOUNT)
       VALUES (:CAR_ID,:CAR_TYPE_ID,:STATE_NUM,:CALLSIGN,:DESCRIPTION,
               :BRAND,:COLOR,:YEAR_CREATED,:PTS,:PAYLOAD,:AMOUNT);
END;

--

/* Создание процедуры изменения автомобиля */

CREATE PROCEDURE /*PREFIX*/U_CAR
(
  CAR_ID VARCHAR(32),
  CAR_TYPE_ID VARCHAR(32),
  STATE_NUM VARCHAR(50),
  CALLSIGN VARCHAR(10),
  DESCRIPTION VARCHAR(250),
  BRAND VARCHAR(100),
  COLOR VARCHAR(100),
  YEAR_CREATED INTEGER,
  PTS VARCHAR(250),
  PAYLOAD INTEGER,
  AMOUNT INTEGER,
  OLD_CAR_ID VARCHAR(32)
)
AS
BEGIN
  UPDATE /*PREFIX*/CARS
     SET CAR_ID=:CAR_ID,
         CAR_TYPE_ID=:CAR_TYPE_ID,
         STATE_NUM=:STATE_NUM,
         CALLSIGN=:CALLSIGN,
         DESCRIPTION=:DESCRIPTION,
         BRAND=:BRAND,
         COLOR=:COLOR,
         YEAR_CREATED=:YEAR_CREATED,
         PTS=:PTS,
         PAYLOAD=:PAYLOAD,
         AMOUNT=:AMOUNT
   WHERE CAR_ID=:OLD_CAR_ID;
END;

--

/* Создание процедуры удаления автомобиля */

CREATE PROCEDURE /*PREFIX*/D_CAR
(
  OLD_CAR_ID VARCHAR(32)
)
AS
BEGIN
  DELETE FROM /*PREFIX*/CARS 
        WHERE CAR_ID=:OLD_CAR_ID;
END;

--

/* Фиксация изменений */

COMMIT