/* Создание таблицы доступа к типам автомобилей */

CREATE TABLE /*PREFIX*/CAR_IN_TYPES
(
  CAR_ID VARCHAR(32) NOT NULL,
  CAR_TYPE_ID VARCHAR(32) NOT NULL,
  PRIMARY KEY (CAR_ID,CAR_TYPE_ID),
  FOREIGN KEY (CAR_ID) REFERENCES CARS (CAR_ID),
  FOREIGN KEY (CAR_TYPE_ID) REFERENCES CAR_TYPES (CAR_TYPE_ID)
)

--

/* Создание просмотра доступа к типам автомобилей */

CREATE VIEW /*PREFIX*/S_CAR_IN_TYPES
(
  CAR_ID,
  CAR_TYPE_ID,
  CAR_STATE_NUM,
  CAR_BRAND,
  CAR_COLOR,
  CAR_TYPE_NAME,
  CAR_TYPE_FONT_COLOR,
  CAR_TYPE_BRUSH_COLOR
)
AS
  SELECT CIT.*,
         C.STATE_NUM AS CAR_STATE_NUM,
         C.BRAND AS CAR_BRAND,
         C.COLOR AS CAR_COLOR,
         CT.NAME AS CAR_TYPE_NAME,
         CT.FONT_COLOR AS CAR_TYPE_FONT_COLOR,
         CT.BRUSH_COLOR AS CAR_TYPE_BRUSH_COLOR
    FROM /*PREFIX*/CAR_IN_TYPES CIT
    JOIN /*PREFIX*/CARS C ON C.CAR_ID=CIT.CAR_ID
    JOIN /*PREFIX*/CAR_TYPES CT ON CT.CAR_TYPE_ID=CIT.CAR_TYPE_ID

--

/* Создание процедуры добавления доступа к типу автомобилей */

CREATE PROCEDURE /*PREFIX*/I_CAR_IN_TYPE
(
  CAR_ID VARCHAR(32),
  CAR_TYPE_ID VARCHAR(32)
)
AS
BEGIN
  INSERT INTO /*PREFIX*/CAR_IN_TYPES (CAR_ID,CAR_TYPE_ID)
       VALUES (:CAR_ID,:CAR_TYPE_ID);
END;

--

/* Создание процедуры изменения доступа к типу автомобилей */

CREATE PROCEDURE /*PREFIX*/U_CAR_IN_TYPE
(
  CAR_ID VARCHAR(32),
  CAR_TYPE_ID VARCHAR(32),
  OLD_CAR_ID VARCHAR(32),
  OLD_CAR_TYPE_ID VARCHAR(32)
)
AS
BEGIN
  UPDATE /*PREFIX*/CARS
     SET CAR_ID=:CAR_ID,
         CAR_TYPE_ID=:CAR_TYPE_ID
   WHERE CAR_ID=:OLD_CAR_ID
     AND CAR_TYPE_ID=:OLD_CAR_TYPE_ID;
END;

--

/* Создание процедуры удаления доступа к типу автомобилей */

CREATE PROCEDURE /*PREFIX*/D_CAR_IN_TYPE
(
  OLD_CAR_ID VARCHAR(32),
  OLD_CAR_TYPE_ID VARCHAR(32)
)
AS
BEGIN
  DELETE FROM /*PREFIX*/CARS 
        WHERE CAR_ID=:OLD_CAR_ID
          AND CAR_TYPE_ID=:OLD_CAR_TYPE_ID;
END;

--

/* Фиксация изменений */

COMMIT