/* Создание таблицы услуг */

CREATE TABLE /*PREFIX*/SERVICES
(
  SERVICE_ID VARCHAR(32) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(250),
  COST NUMERIC(15,2) NOT NULL,
  PRIORITY INTEGER,
  PRIMARY KEY (SERVICE_ID)
)

--

/* Создание просмотра услуг */

CREATE VIEW /*PREFIX*/S_SERVICES
AS
SELECT * FROM /*PREFIX*/SERVICES

--

/* Создание процедуры добавления услуги */

CREATE PROCEDURE /*PREFIX*/I_SERVICE
(
  SERVICE_ID VARCHAR(32),
  NAME VARCHAR(100),
  DESCRIPTION VARCHAR(250),
  COST NUMERIC(15,2),
  PRIORITY INTEGER
)
AS
BEGIN
  INSERT INTO /*PREFIX*/SERVICES (SERVICE_ID,NAME,DESCRIPTION,COST,PRIORITY)
       VALUES (:SERVICE_ID,:NAME,:DESCRIPTION,:COST,:PRIORITY);
END;

--

/* Создание процедуры изменения услуги */

CREATE PROCEDURE /*PREFIX*/U_SERVICE
(
  SERVICE_ID VARCHAR(32),
  NAME VARCHAR(100),
  DESCRIPTION VARCHAR(250),
  COST NUMERIC(15,2),
  PRIORITY INTEGER,
  OLD_SERVICE_ID VARCHAR(32)
)
AS
BEGIN
  UPDATE /*PREFIX*/SERVICES
     SET SERVICE_ID=:SERVICE_ID,
         NAME=:NAME,
         DESCRIPTION=:DESCRIPTION,
         COST=:COST,
         PRIORITY=:PRIORITY
   WHERE SERVICE_ID=:OLD_SERVICE_ID;
END;

--

/* Создание процедуры удаления услуги */

CREATE PROCEDURE /*PREFIX*/D_SERVICE
(
  OLD_SERVICE_ID VARCHAR(32)
)
AS
BEGIN
  DELETE FROM /*PREFIX*/SERVICES 
        WHERE SERVICE_ID=:OLD_SERVICE_ID;
END;

--

/* Фиксация изменений */

COMMIT