/* Создание таблицы зон */

CREATE TABLE /*PREFIX*/ZONES
(
  ZONE_ID VARCHAR(32) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(250),
  PRIORITY INTEGER,
  COST_IN NUMERIC(15,2),
  COST_OUT NUMERIC(15,2),
  PRIMARY KEY (ZONE_ID)
)

--

/* Создание просмотра зон */

CREATE VIEW /*PREFIX*/S_ZONES
AS
SELECT * FROM /*PREFIX*/ZONES

--

/* Создание процедуры добавления зоны */

CREATE OR ALTER PROCEDURE I_ZONE
(
  ZONE_ID VARCHAR(32),
  NAME VARCHAR(100),
  DESCRIPTION VARCHAR(250),
  PRIORITY INTEGER,
  COST_IN NUMERIC(15,2),
  COST_OUT NUMERIC(15,2)
)
AS
BEGIN
  INSERT INTO ZONES (ZONE_ID,NAME,DESCRIPTION,PRIORITY,COST_IN,COST_OUT)
       VALUES (:ZONE_ID,:NAME,:DESCRIPTION,:PRIORITY,:COST_IN,:COST_OUT);
END

--

/* Создание процедуры изменения зоны */

CREATE OR ALTER PROCEDURE U_ZONE
(
  ZONE_ID VARCHAR(32),
  NAME VARCHAR(100),
  DESCRIPTION VARCHAR(250),
  PRIORITY INTEGER,
  COST_IN NUMERIC(15,2),
  COST_OUT NUMERIC(15,2),
  OLD_ZONE_ID VARCHAR(32)
)
AS
BEGIN
  UPDATE ZONES
     SET ZONE_ID=:ZONE_ID,
         NAME=:NAME,
         DESCRIPTION=:DESCRIPTION,
         PRIORITY=:PRIORITY,
         COST_IN=:COST_IN,
         COST_OUT=:COST_OUT
   WHERE ZONE_ID=:OLD_ZONE_ID;
END;

--

/* Создание процедуры удаления зоны */

CREATE PROCEDURE /*PREFIX*/D_ZONE
(
  OLD_ZONE_ID VARCHAR(32)
)
AS
BEGIN
  DELETE FROM /*PREFIX*/ZONES 
        WHERE ZONE_ID=:OLD_ZONE_ID;
END;

--

/* Фиксация изменений */

COMMIT