/* Создание таблицы типов дисконтов */

CREATE TABLE /*PREFIX*/DISCOUNT_TYPES
(
  DISCOUNT_TYPE_ID VARCHAR(32) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(250),
  TYPE_CALC INTEGER NOT NULL,
  PERCENT NUMERIC(4,2),
  DISCOUNT_SUM NUMERIC(15,2),
  PROC_NAME VARCHAR(100),
  PRIORITY INTEGER,
  PRIMARY KEY (DISCOUNT_TYPE_ID)
)

--

/* Создание просмотра типов дисконтов */

CREATE VIEW /*PREFIX*/S_DISCOUNT_TYPES
AS
SELECT * FROM /*PREFIX*/DISCOUNT_TYPES

--

/* Создание процедуры добавления типа дисконта */

CREATE PROCEDURE /*PREFIX*/I_DISCOUNT_TYPE
(
  DISCOUNT_TYPE_ID VARCHAR(32),
  NAME VARCHAR(100),
  DESCRIPTION VARCHAR(250),
  TYPE_CALC INTEGER,
  PERCENT NUMERIC(4,2),
  DISCOUNT_SUM NUMERIC(15,2),
  PROC_NAME VARCHAR(100),
  PRIORITY INTEGER
)
AS
BEGIN
  INSERT INTO /*PREFIX*/DISCOUNT_TYPES (DISCOUNT_TYPE_ID,NAME,DESCRIPTION,TYPE_CALC,
                                        PERCENT,DISCOUNT_SUM,PROC_NAME,PRIORITY)
       VALUES (:DISCOUNT_TYPE_ID,:NAME,:DESCRIPTION,:TYPE_CALC,
               :PERCENT,:DISCOUNT_SUM,:PROC_NAME,:PRIORITY);
END;

--

/* Создание процедуры изменения типа дисконта */

CREATE PROCEDURE /*PREFIX*/U_DISCOUNT_TYPE
(
  DISCOUNT_TYPE_ID VARCHAR(32),
  NAME VARCHAR(100),
  DESCRIPTION VARCHAR(250),
  TYPE_CALC INTEGER,
  PERCENT NUMERIC(4,2),
  DISCOUNT_SUM NUMERIC(15,2),
  PROC_NAME VARCHAR(100),
  PRIORITY INTEGER,
  OLD_DISCOUNT_TYPE_ID VARCHAR(32)
)
AS
BEGIN
  UPDATE /*PREFIX*/DISCOUNT_TYPES
     SET DISCOUNT_TYPE_ID=:DISCOUNT_TYPE_ID,
         NAME=:NAME,
         DESCRIPTION=:DESCRIPTION,
         TYPE_CALC=:TYPE_CALC,
         PERCENT=:PERCENT,
         DISCOUNT_SUM=:DISCOUNT_SUM,
         PROC_NAME=:PROC_NAME,
         PRIORITY=:PRIORITY
   WHERE DISCOUNT_TYPE_ID=:OLD_DISCOUNT_TYPE_ID;
END;

--

/* Создание процедуры удаления типа дисконта */

CREATE PROCEDURE /*PREFIX*/D_DISCOUNT_TYPE
(
  OLD_DISCOUNT_TYPE_ID VARCHAR(32)
)
AS
BEGIN
  DELETE FROM /*PREFIX*/DISCOUNT_TYPES
        WHERE DISCOUNT_TYPE_ID=:OLD_DISCOUNT_TYPE_ID;
END;

--

/* Фиксация изменений */

COMMIT