/* Создание таблицы расчетов */

CREATE TABLE /*PREFIX*/CALCS
(
  CALC_ID VARCHAR(32) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(250),
  TYPE_CALC INTEGER NOT NULL,
  PERCENT NUMERIC(4,2),
  CALC_SUM NUMERIC(15,2),
  PROC_NAME VARCHAR(100),
  PRIORITY INTEGER,
  PRIMARY KEY (CALC_ID)
)

--

/* Создание просмотра расчетов */

CREATE VIEW /*PREFIX*/S_CALCS
AS
SELECT * FROM /*PREFIX*/CALCS

--

/* Создание процедуры добавления расчета */

CREATE PROCEDURE /*PREFIX*/I_CALC
(
  CALC_ID VARCHAR(32),
  NAME VARCHAR(100),
  DESCRIPTION VARCHAR(250),
  TYPE_CALC INTEGER,
  PERCENT NUMERIC(4,2),
  CALC_SUM NUMERIC(15,2),
  PROC_NAME VARCHAR(100),
  PRIORITY INTEGER
)
AS
BEGIN
  INSERT INTO /*PREFIX*/CALCS (CALC_ID,NAME,DESCRIPTION,TYPE_CALC,
                                   PERCENT,CALC_SUM,PROC_NAME,PRIORITY)
       VALUES (:CALC_ID,:NAME,:DESCRIPTION,:TYPE_CALC,
               :PERCENT,:CALC_SUM,:PROC_NAME,:PRIORITY);
END;

--

/* Создание процедуры изменения расчета */

CREATE PROCEDURE /*PREFIX*/U_CALC
(
  CALC_ID VARCHAR(32),
  NAME VARCHAR(100),
  DESCRIPTION VARCHAR(250),
  TYPE_CALC INTEGER,
  PERCENT NUMERIC(4,2),
  CALC_SUM NUMERIC(15,2),
  PROC_NAME VARCHAR(100),
  PRIORITY INTEGER,
  OLD_CALC_ID VARCHAR(32)
)
AS
BEGIN
  UPDATE /*PREFIX*/CALCS
     SET CALC_ID=:CALC_ID,
         NAME=:NAME,
         DESCRIPTION=:DESCRIPTION,
         TYPE_CALC=:TYPE_CALC,
         PERCENT=:PERCENT,
         CALC_SUM=:CALC_SUM,
         PROC_NAME=:PROC_NAME,
         PRIORITY=:PRIORITY
   WHERE CALC_ID=:OLD_CALC_ID;
END;

--

/* Создание процедуры удаления расчета */

CREATE PROCEDURE /*PREFIX*/D_CALC
(
  OLD_CALC_ID VARCHAR(32)
)
AS
BEGIN
  DELETE FROM /*PREFIX*/CALCS 
        WHERE CALC_ID=:OLD_CALC_ID;
END;

--

/* Фиксация изменений */

COMMIT