/* Создание таблицы способов связи */

CREATE TABLE /*PREFIX*/METHODS
(
  METHOD_ID VARCHAR(32) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(250),
  OUTGOING INTEGER NOT NULL,
  INCOMING INTEGER NOT NULL,
  PRIORITY INTEGER,
  PRIMARY KEY (METHOD_ID)
)

--

/* Создание просмотра способов связи */

CREATE VIEW /*PREFIX*/S_METHODS
AS
SELECT * FROM /*PREFIX*/METHODS

--

/* Создание процедуры добавления способа связи */

CREATE PROCEDURE /*PREFIX*/I_METHOD
(
  METHOD_ID VARCHAR(32),
  NAME VARCHAR(100),
  DESCRIPTION VARCHAR(250),
  OUTGOING INTEGER,
  INCOMING INTEGER,
  PRIORITY INTEGER
)
AS
BEGIN
  INSERT INTO /*PREFIX*/METHODS (METHOD_ID,NAME,DESCRIPTION,OUTGOING,INCOMING,PRIORITY)
       VALUES (:METHOD_ID,:NAME,:DESCRIPTION,:OUTGOING,:INCOMING,:PRIORITY);
END;

--

/* Создание процедуры изменения способа связи */

CREATE PROCEDURE /*PREFIX*/U_METHOD
(
  METHOD_ID VARCHAR(32),
  NAME VARCHAR(100),
  DESCRIPTION VARCHAR(250),
  OUTGOING INTEGER,
  INCOMING INTEGER,
  PRIORITY INTEGER,
  OLD_METHOD_ID VARCHAR(32)
)
AS
BEGIN
  UPDATE /*PREFIX*/METHODS
     SET METHOD_ID=:METHOD_ID,
         NAME=:NAME,
         DESCRIPTION=:DESCRIPTION,
         OUTGOING=:OUTGOING,
         INCOMING=:INCOMING,
         PRIORITY=:PRIORITY
   WHERE METHOD_ID=:OLD_METHOD_ID;
END;

--

/* Создание процедуры удаления способа связи */

CREATE PROCEDURE /*PREFIX*/D_METHOD
(
  OLD_METHOD_ID VARCHAR(32)
)
AS
BEGIN
  DELETE FROM /*PREFIX*/METHODS 
        WHERE METHOD_ID=:OLD_METHOD_ID;
END;

--

/* Фиксация изменений */

COMMIT