/* Создание таблицы стоянок */

CREATE TABLE /*PREFIX*/PARKS
(
  PARK_ID VARCHAR(32) NOT NULL,
  STREET_ID VARCHAR(32) NOT NULL,
  HOUSE VARCHAR(10),
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(250) NOT NULL,
  MAX_COUNT INTEGER,
  PRIORITY INTEGER,
  PRIMARY KEY (PARK_ID),
  FOREIGN KEY (STREET_ID) REFERENCES STREETS (STREET_ID)
)

--

/* Создание просмотра стоянок */

CREATE VIEW /*PREFIX*/S_PARKS
(
  PARK_ID,
  STREET_ID,
  HOUSE,
  NAME,
  DESCRIPTION,
  MAX_COUNT,
  PRIORITY,
  STREET_NAME,
  STREET_PREFIX,
  LOCALITY_NAME,
  LOCALITY_PREFIX
)
AS
SELECT P.*,
       S.NAME AS STREET_NAME,
       S.PREFIX AS STREET_PREFIX,
       L.NAME AS LOCALITY_NAME,
       L.PREFIX AS LOCALITY_PREFIX
  FROM /*PREFIX*/PARKS P
  JOIN /*PREFIX*/STREETS S ON S.STREET_ID=P.STREET_ID
  JOIN /*PREFIX*/LOCALITIES L ON L.LOCALITY_ID=S.LOCALITY_ID

--

/* Создание процедуры добавления стоянки */

CREATE PROCEDURE /*PREFIX*/I_PARK
(
  PARK_ID VARCHAR(32),
  STREET_ID VARCHAR(32),
  HOUSE VARCHAR(10),
  NAME VARCHAR(100),
  DESCRIPTION VARCHAR(250),
  MAX_COUNT INTEGER,
  PRIORITY INTEGER
)
AS
BEGIN
  INSERT INTO /*PREFIX*/PARKS (PARK_ID,STREET_ID,HOUSE,NAME,
                               DESCRIPTION,MAX_COUNT,PRIORITY)
       VALUES (:PARK_ID,:STREET_ID,:HOUSE,:NAME,
               :DESCRIPTION,:MAX_COUNT,:PRIORITY);
END;

--

/* Создание процедуры изменения стоянки */

CREATE PROCEDURE /*PREFIX*/U_PARK
(
  PARK_ID VARCHAR(32),
  STREET_ID VARCHAR(32),
  HOUSE VARCHAR(10),
  NAME VARCHAR(100),
  DESCRIPTION VARCHAR(250),
  MAX_COUNT INTEGER,
  PRIORITY INTEGER,
  OLD_PARK_ID VARCHAR(32)
)
AS
BEGIN
  UPDATE /*PREFIX*/PARKS
     SET PARK_ID=:PARK_ID,
         STREET_ID=:STREET_ID,
         HOUSE=:HOUSE,
         NAME=:NAME,
         DESCRIPTION=:DESCRIPTION,
         MAX_COUNT=:MAX_COUNT,
         PRIORITY=:PRIORITY
   WHERE PARK_ID=:OLD_PARK_ID;
END;

--

/* Создание процедуры удаления стоянки */

CREATE PROCEDURE /*PREFIX*/D_PARK
(
  OLD_PARK_ID VARCHAR(32)
)
AS
BEGIN
  DELETE FROM /*PREFIX*/PARKS 
        WHERE PARK_ID=:OLD_PARK_ID;
END;

--

/* Фиксация изменений */

COMMIT