/* Создание таблицы видов поступлений */

CREATE TABLE /*PREFIX*/RECEIPT_TYPES
(
  RECEIPT_TYPE_ID VARCHAR(32) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(250),
  SUM_RECEIPT NUMERIC(15,2),
  PRIMARY KEY (RECEIPT_TYPE_ID)
)

--

/* Создание просмотра видов поступлений */

CREATE VIEW /*PREFIX*/S_RECEIPT_TYPES
AS
SELECT * FROM /*PREFIX*/RECEIPT_TYPES

--

/* Создание процедуры добавления вида поступления */

CREATE PROCEDURE /*PREFIX*/I_RECEIPT_TYPE
(
  RECEIPT_TYPE_ID VARCHAR(32),
  NAME VARCHAR(100),
  DESCRIPTION VARCHAR(250),
  SUM_RECEIPT NUMERIC(15,2)
)
AS
BEGIN
  INSERT INTO /*PREFIX*/RECEIPT_TYPES (RECEIPT_TYPE_ID,NAME,DESCRIPTION,SUM_RECEIPT)
       VALUES (:RECEIPT_TYPE_ID,:NAME,:DESCRIPTION,:SUM_RECEIPT);
END;

--

/* Создание процедуры изменения вида поступления */

CREATE PROCEDURE /*PREFIX*/U_RECEIPT_TYPE
(
  RECEIPT_TYPE_ID VARCHAR(32),
  NAME VARCHAR(100),
  DESCRIPTION VARCHAR(250),
  SUM_RECEIPT NUMERIC(15,2),
  OLD_RECEIPT_TYPE_ID VARCHAR(32)
)
AS
BEGIN
  UPDATE /*PREFIX*/RECEIPT_TYPES
     SET RECEIPT_TYPE_ID=:RECEIPT_TYPE_ID,
         NAME=:NAME,
         DESCRIPTION=:DESCRIPTION,
         SUM_RECEIPT=:SUM_RECEIPT
   WHERE RECEIPT_TYPE_ID=:OLD_RECEIPT_TYPE_ID;
END;

--

/* Создание процедуры удаления вида поступления */

CREATE PROCEDURE /*PREFIX*/D_RECEIPT_TYPE
(
  OLD_RECEIPT_TYPE_ID VARCHAR(32)
)
AS
BEGIN
  DELETE FROM /*PREFIX*/RECEIPT_TYPES 
        WHERE RECEIPT_TYPE_ID=:OLD_RECEIPT_TYPE_ID;
END;

--

/* Фиксация изменений */

COMMIT