/* Создание таблицы черного списка */

CREATE TABLE /*PREFIX*/BLACKS
(
  BLACK_ID VARCHAR(32) NOT NULL,
  ACCOUNT_ID VARCHAR(32) NOT NULL,
  STREET_ID VARCHAR(32),
  HOUSE VARCHAR(10),
  FLAT VARCHAR(10),
  DATE_CREATE TIMESTAMP,
  PHONE VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(250),
  PRIMARY KEY (BLACK_ID),
  FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS (ACCOUNT_ID),
  FOREIGN KEY (STREET_ID) REFERENCES STREETS (STREET_ID)
)

--

/* Создание просмотра черного списка */

CREATE VIEW /*PREFIX*/S_BLACKS
(
  BLACK_ID,
  ACCOUNT_ID,
  STREET_ID,
  HOUSE,
  FLAT,
  DATE_CREATE,
  PHONE,
  DESCRIPTION,
  USER_NAME,
  STREET_NAME,
  STREET_PREFIX,
  LOCALITY_ID,
  LOCALITY_NAME,
  LOCALITY_PREFIX
)
AS
SELECT B.*,
       A.USER_NAME,
       S.NAME AS STREET_NAME,
       S.PREFIX AS STREET_PREFIX,
       L.LOCALITY_ID,
       L.NAME AS LOCALITY_NAME,
       L.PREFIX AS LOCALITY_PREFIX
  FROM /*PREFIX*/BLACKS B
  JOIN /*PREFIX*/ACCOUNTS A ON A.ACCOUNT_ID=B.ACCOUNT_ID
  LEFT JOIN /*PREFIX*/STREETS S ON S.STREET_ID=B.STREET_ID
  LEFT JOIN /*PREFIX*/LOCALITIES L ON L.LOCALITY_ID=S.LOCALITY_ID

--

/* Создание процедуры добавления записи в черный список */

CREATE PROCEDURE /*PREFIX*/I_BLACK
(
  BLACK_ID VARCHAR(32),
  ACCOUNT_ID VARCHAR(32),
  STREET_ID VARCHAR(32),
  HOUSE VARCHAR(10),
  FLAT VARCHAR(10),
  DATE_CREATE TIMESTAMP,
  PHONE VARCHAR(100),
  DESCRIPTION VARCHAR(250)
)
AS
BEGIN
  INSERT INTO /*PREFIX*/BLACKS (BLACK_ID,ACCOUNT_ID,STREET_ID,HOUSE,FLAT,
                                DATE_CREATE,PHONE,DESCRIPTION)
       VALUES (:BLACK_ID,:ACCOUNT_ID,:STREET_ID,:HOUSE,:FLAT,
               :DATE_CREATE,:PHONE,:DESCRIPTION);
END;

--

/* Создание процедуры изменения записи в черном списке */

CREATE PROCEDURE /*PREFIX*/U_BLACK
(
  BLACK_ID VARCHAR(32),
  ACCOUNT_ID VARCHAR(32),
  STREET_ID VARCHAR(32),
  HOUSE VARCHAR(10),
  FLAT VARCHAR(10),
  DATE_CREATE TIMESTAMP,
  PHONE VARCHAR(100),
  DESCRIPTION VARCHAR(250),
  OLD_BLACK_ID VARCHAR(32)
)
AS
BEGIN
  UPDATE /*PREFIX*/BLACKS
     SET BLACK_ID=:BLACK_ID,
         ACCOUNT_ID=:ACCOUNT_ID,
         STREET_ID=:STREET_ID,
         HOUSE=:HOUSE,
         FLAT=:FLAT,
         DATE_CREATE=:DATE_CREATE,
         PHONE=:PHONE,
         DESCRIPTION=:DESCRIPTION
   WHERE BLACK_ID=:OLD_BLACK_ID;
END;

--

/* Создание процедуры удаления записи в черном списке */

CREATE PROCEDURE /*PREFIX*/D_BLACK
(
  OLD_BLACK_ID VARCHAR(32)
)
AS
BEGIN
  DELETE FROM /*PREFIX*/BLACKS 
        WHERE BLACK_ID=:OLD_BLACK_ID;
END;

--

/* Фиксация изменений */

COMMIT