/* Создание таблицы списаний */

CREATE TABLE /*PREFIX*/CHARGES
(
  CHARGE_ID VARCHAR(32) NOT NULL,
  CHARGE_TYPE_ID VARCHAR(32) NOT NULL,
  ACCOUNT_ID VARCHAR(32) NOT NULL,
  WHO_CREATE_ID VARCHAR(32) NOT NULL,
  SUM_CHARGE NUMERIC(15,2) NOT NULL,
  DATE_CHARGE TIMESTAMP NOT NULL,
  DATE_CREATE TIMESTAMP NOT NULL,
  DESCRIPTION VARCHAR(250),
  PRIMARY KEY (CHARGE_ID),
  FOREIGN KEY (CHARGE_TYPE_ID) REFERENCES CHARGE_TYPES (CHARGE_TYPE_ID),
  FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS (ACCOUNT_ID),
  FOREIGN KEY (WHO_CREATE_ID) REFERENCES ACCOUNTS (ACCOUNT_ID)
)

--

/* Создание просмотра списаний */

CREATE VIEW /*PREFIX*/S_CHARGES
(
  CHARGE_ID,
  CHARGE_TYPE_ID,
  ACCOUNT_ID,
  WHO_CREATE_ID,
  SUM_CHARGE,
  DATE_CHARGE,
  DATE_CREATE,
  DESCRIPTION,
  CHARGE_TYPE_NAME,
  USER_NAME,
  WHO_USER_NAME
)
AS
SELECT C.*,
       CT.NAME AS CHARGE_TYPE_NAME,
       A1.USER_NAME,
       A2.USER_NAME AS WHO_USER_NAME
  FROM /*PREFIX*/CHARGES C
  JOIN /*PREFIX*/CHARGE_TYPES CT ON CT.CHARGE_TYPE_ID=C.CHARGE_TYPE_ID
  JOIN /*PREFIX*/ACCOUNTS A1 ON A1.ACCOUNT_ID=C.ACCOUNT_ID
  JOIN /*PREFIX*/ACCOUNTS A2 ON A2.ACCOUNT_ID=C.WHO_CREATE_ID

--

/* Создание процедуры добавления списания */

CREATE PROCEDURE /*PREFIX*/I_CHARGE
(
  CHARGE_ID VARCHAR(32),
  CHARGE_TYPE_ID VARCHAR(32),
  ACCOUNT_ID VARCHAR(32),
  WHO_CREATE_ID VARCHAR(32),
  SUM_CHARGE NUMERIC(15,2),
  DATE_CHARGE TIMESTAMP,
  DATE_CREATE TIMESTAMP,
  DESCRIPTION VARCHAR(250)
)
AS
BEGIN
  INSERT INTO /*PREFIX*/CHARGES (CHARGE_ID,CHARGE_TYPE_ID,ACCOUNT_ID,WHO_CREATE_ID,
                                  SUM_CHARGE,DATE_CHARGE,DATE_CREATE,DESCRIPTION)
       VALUES (:CHARGE_ID,:CHARGE_TYPE_ID,:ACCOUNT_ID,:WHO_CREATE_ID,
               :SUM_CHARGE,:DATE_CHARGE,:DATE_CREATE,:DESCRIPTION);
END;

--

/* Создание процедуры изменения списания */

CREATE PROCEDURE /*PREFIX*/U_CHARGE
(
  CHARGE_ID VARCHAR(32),
  CHARGE_TYPE_ID VARCHAR(32),
  ACCOUNT_ID VARCHAR(32),
  WHO_CREATE_ID VARCHAR(32),
  SUM_CHARGE NUMERIC(15,2),
  DATE_CHARGE TIMESTAMP,
  DATE_CREATE TIMESTAMP,
  DESCRIPTION VARCHAR(250),
  OLD_CHARGE_ID VARCHAR(32)
)
AS
BEGIN
  UPDATE /*PREFIX*/CHARGES
     SET CHARGE_ID=:CHARGE_ID,
         CHARGE_TYPE_ID=:CHARGE_TYPE_ID,
         ACCOUNT_ID=:ACCOUNT_ID,
         WHO_CREATE_ID=:WHO_CREATE_ID,
         SUM_CHARGE=:SUM_CHARGE,
         DATE_CHARGE=:DATE_CHARGE,
         DATE_CREATE=:DATE_CREATE,
         DESCRIPTION=:DESCRIPTION
   WHERE CHARGE_ID=:OLD_CHARGE_ID;
END;

--

/* Создание процедуры удаления списания */

CREATE PROCEDURE /*PREFIX*/D_CHARGE
(
  OLD_CHARGE_ID VARCHAR(32)
)
AS
BEGIN
  DELETE FROM /*PREFIX*/CHARGES 
        WHERE CHARGE_ID=:OLD_CHARGE_ID;
END;

--

/* Фиксация изменений */

COMMIT