/* Создание таблицы поступлений */

CREATE TABLE /*PREFIX*/RECEIPTS
(
  RECEIPT_ID VARCHAR(32) NOT NULL,
  RECEIPT_TYPE_ID VARCHAR(32) NOT NULL,
  ACCOUNT_ID VARCHAR(32) NOT NULL,
  WHO_CREATE_ID VARCHAR(32) NOT NULL,
  SUM_RECEIPT NUMERIC(15,2) NOT NULL,
  DATE_RECEIPT TIMESTAMP NOT NULL,
  DATE_CREATE TIMESTAMP NOT NULL,
  DESCRIPTION VARCHAR(250),
  PRIMARY KEY (RECEIPT_ID),
  FOREIGN KEY (RECEIPT_TYPE_ID) REFERENCES RECEIPT_TYPES (RECEIPT_TYPE_ID),
  FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS (ACCOUNT_ID),
  FOREIGN KEY (WHO_CREATE_ID) REFERENCES ACCOUNTS (ACCOUNT_ID)
)

--

/* Создание просмотра поступлений */

CREATE VIEW /*PREFIX*/S_RECEIPTS
(
  RECEIPT_ID,
  RECEIPT_TYPE_ID,
  ACCOUNT_ID,
  WHO_CREATE_ID,
  SUM_RECEIPT,
  DATE_RECEIPT,
  DATE_CREATE,
  DESCRIPTION,
  RECEIPT_TYPE_NAME,
  USER_NAME,
  WHO_USER_NAME
)
AS
SELECT R.*,
       RT.NAME AS RECEIPT_TYPE_NAME,
       A1.USER_NAME,
       A2.USER_NAME AS WHO_USER_NAME
  FROM /*PREFIX*/RECEIPTS R
  JOIN /*PREFIX*/RECEIPT_TYPES RT ON RT.RECEIPT_TYPE_ID=R.RECEIPT_TYPE_ID
  JOIN /*PREFIX*/ACCOUNTS A1 ON A1.ACCOUNT_ID=R.ACCOUNT_ID
  JOIN /*PREFIX*/ACCOUNTS A2 ON A2.ACCOUNT_ID=R.WHO_CREATE_ID

--

/* Создание процедуры добавления поступления */

CREATE PROCEDURE /*PREFIX*/I_RECEIPT
(
  RECEIPT_ID VARCHAR(32),
  RECEIPT_TYPE_ID VARCHAR(32),
  ACCOUNT_ID VARCHAR(32),
  WHO_CREATE_ID VARCHAR(32),
  SUM_RECEIPT NUMERIC(15,2),
  DATE_RECEIPT TIMESTAMP,
  DATE_CREATE TIMESTAMP,
  DESCRIPTION VARCHAR(250)
)
AS
BEGIN
  INSERT INTO /*PREFIX*/RECEIPTS (RECEIPT_ID,RECEIPT_TYPE_ID,ACCOUNT_ID,WHO_CREATE_ID,
                                  SUM_RECEIPT,DATE_RECEIPT,DATE_CREATE,DESCRIPTION)
       VALUES (:RECEIPT_ID,:RECEIPT_TYPE_ID,:ACCOUNT_ID,:WHO_CREATE_ID,
               :SUM_RECEIPT,:DATE_RECEIPT,:DATE_CREATE,:DESCRIPTION);
END;

--

/* Создание процедуры изменения поступления */

CREATE PROCEDURE /*PREFIX*/U_RECEIPT
(
  RECEIPT_ID VARCHAR(32),
  RECEIPT_TYPE_ID VARCHAR(32),
  ACCOUNT_ID VARCHAR(32),
  WHO_CREATE_ID VARCHAR(32),
  SUM_RECEIPT NUMERIC(15,2),
  DATE_RECEIPT TIMESTAMP,
  DATE_CREATE TIMESTAMP,
  DESCRIPTION VARCHAR(250),
  OLD_RECEIPT_ID VARCHAR(32)
)
AS
BEGIN
  UPDATE /*PREFIX*/RECEIPTS
     SET RECEIPT_ID=:RECEIPT_ID,
         RECEIPT_TYPE_ID=:RECEIPT_TYPE_ID,
         ACCOUNT_ID=:ACCOUNT_ID,
         WHO_CREATE_ID=:WHO_CREATE_ID,
         SUM_RECEIPT=:SUM_RECEIPT,
         DATE_RECEIPT=:DATE_RECEIPT,
         DATE_CREATE=:DATE_CREATE,
         DESCRIPTION=:DESCRIPTION
   WHERE RECEIPT_ID=:OLD_RECEIPT_ID;
END;

--

/* Создание процедуры удаления поступления */

CREATE PROCEDURE /*PREFIX*/D_RECEIPT
(
  OLD_RECEIPT_ID VARCHAR(32)
)
AS
BEGIN
  DELETE FROM /*PREFIX*/RECEIPTS 
        WHERE RECEIPT_ID=:OLD_RECEIPT_ID;
END;

--

/* Фиксация изменений */

COMMIT