/* Создание таблицы групп клиентов */

CREATE TABLE /*PREFIX*/CLIENT_GROUPS
(
  CLIENT_GROUP_ID VARCHAR(32) NOT NULL,
  PARENT_ID VARCHAR(32),
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(250),
  PRIORITY INTEGER NOT NULL,
  "LEVEL" INTEGER NOT NULL,
  PRIMARY KEY (CLIENT_GROUP_ID),
  FOREIGN KEY (PARENT_ID) REFERENCES /*PREFIX*/CLIENT_GROUPS (CLIENT_GROUP_ID)
)

--

/* Создание просмотра таблицы групп клиентов */

CREATE VIEW /*PREFIX*/S_CLIENT_GROUPS
(
  CLIENT_GROUP_ID,
  PARENT_ID,
  NAME,
  DESCRIPTION,
  PRIORITY,
  "LEVEL",
  PARENT_NAME
)
AS
   SELECT CG.*,
          CG1.NAME AS PARENT_NAME
     FROM /*PREFIX*/CLIENT_GROUPS CG
     LEFT JOIN /*PREFIX*/CLIENT_GROUPS CG1 ON CG1.CLIENT_GROUP_ID=CG.PARENT_ID

--

/* Создание процедуры добавления группы клиента */

CREATE PROCEDURE /*PREFIX*/I_CLIENT_GROUP
(
  CLIENT_GROUP_ID VARCHAR(32),
  PARENT_ID VARCHAR(32),
  NAME VARCHAR(100),
  DESCRIPTION VARCHAR(250),
  PRIORITY INTEGER
)
AS
  DECLARE VARIABLE LV INTEGER;
BEGIN
  IF (:PARENT_ID IS NULL) THEN BEGIN
    LV=1;
  END ELSE BEGIN
    SELECT CG."LEVEL"+1
      FROM /*PREFIX*/CLIENT_GROUPS CG
     WHERE CG.CLIENT_GROUP_ID=:PARENT_ID
      INTO :LV;
  END
  INSERT INTO /*PREFIX*/CLIENT_GROUPS (CLIENT_GROUP_ID,PARENT_ID,NAME,DESCRIPTION,PRIORITY,"LEVEL")
       VALUES (:CLIENT_GROUP_ID,:PARENT_ID,:NAME,:DESCRIPTION,:PRIORITY,:LV);
END;

--

/* Создание процедуры обновления уровней групп клиентов */

CREATE PROCEDURE /*PREFIX*/R_CLIENT_GROUP_LEVELS
(
  PARENT_ID VARCHAR(32),
  "LEVEL" INTEGER
)
AS
  DECLARE VARIABLE CLIENT_GROUP_ID VARCHAR(32);
  DECLARE VARIABLE L INTEGER;
BEGIN
  FOR SELECT CG.CLIENT_GROUP_ID
        FROM /*PREFIX*/CLIENT_GROUPS CG
       WHERE CG.PARENT_ID=:PARENT_ID
        INTO :CLIENT_GROUP_ID DO BEGIN

    L=:"LEVEL"+1;

    UPDATE /*PREFIX*/CLIENT_GROUPS
       SET "LEVEL"=:L
     WHERE CLIENT_GROUP_ID=:CLIENT_GROUP_ID;

    EXECUTE PROCEDURE R_CLIENT_GROUP_LEVELS(:CLIENT_GROUP_ID,:L);

  END
END;

--

/* Создание процедуры изменения группы клиента */

CREATE PROCEDURE /*PREFIX*/U_CLIENT_GROUP
(
  CLIENT_GROUP_ID VARCHAR(32),
  PARENT_ID VARCHAR(32),
  NAME VARCHAR(100),
  DESCRIPTION VARCHAR(250),
  PRIORITY INTEGER,
  OLD_CLIENT_GROUP_ID VARCHAR(32)
)
AS
  DECLARE VARIABLE LV INTEGER;
BEGIN
  IF (:PARENT_ID IS NULL) THEN BEGIN
    LV=1;
  END ELSE BEGIN
    SELECT CG."LEVEL"+1
      FROM /*PREFIX*/CLIENT_GROUPS CG
     WHERE CG.CLIENT_GROUP_ID=:PARENT_ID
      INTO :LV;
  END

  UPDATE /*PREFIX*/CLIENT_GROUPS
     SET CLIENT_GROUP_ID=:CLIENT_GROUP_ID,
         PARENT_ID=:PARENT_ID,
         NAME=:NAME,
         DESCRIPTION=:DESCRIPTION,
         PRIORITY=:PRIORITY,
         "LEVEL"=:LV
   WHERE CLIENT_GROUP_ID=:OLD_CLIENT_GROUP_ID;
    
  EXECUTE PROCEDURE /*PREFIX*/R_CLIENT_GROUP_LEVELS(:CLIENT_GROUP_ID,:LV);
END;

--

/* Создание процедуры удаления группы клиента */

CREATE PROCEDURE /*PREFIX*/D_CLIENT_GROUP
(
  OLD_CLIENT_GROUP_ID VARCHAR(32)
)
AS
BEGIN
  DELETE FROM /*PREFIX*/CLIENT_GROUPS
        WHERE CLIENT_GROUP_ID=:OLD_CLIENT_GROUP_ID;
END;

--

/* Фиксация изменений */

COMMIT
