/* Создание таблицы смен */

CREATE TABLE /*PREFIX*/SHIFTS
(
  SHIFT_ID VARCHAR(32) NOT NULL,
  ACCOUNT_ID VARCHAR(32) NOT NULL,
  DATE_BEGIN TIMESTAMP NOT NULL,
  DATE_END TIMESTAMP,
  PRIMARY KEY (SHIFT_ID),
  FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS (ACCOUNT_ID)
)

--

/* Создание просмотра смен */

CREATE VIEW /*PREFIX*/S_SHIFTS
(
  SHIFT_ID,
  ACCOUNT_ID,
  DATE_BEGIN,
  DATE_END,
  USER_NAME
)
AS
SELECT S.*,
       A.USER_NAME
  FROM /*PREFIX*/SHIFTS S
  JOIN /*PREFIX*/ACCOUNTS A ON A.ACCOUNT_ID=S.ACCOUNT_ID

--

/* Создание процедуры добавления смены */

CREATE PROCEDURE /*PREFIX*/I_SHIFT
(
  SHIFT_ID VARCHAR(32),
  ACCOUNT_ID VARCHAR(32),
  DATE_BEGIN TIMESTAMP,
  DATE_END TIMESTAMP
)
AS
BEGIN
  INSERT INTO /*PREFIX*/SHIFTS (SHIFT_ID,ACCOUNT_ID,DATE_BEGIN,DATE_END)
       VALUES (:SHIFT_ID,:ACCOUNT_ID,:DATE_BEGIN,:DATE_END);
END;

--

/* Создание процедуры изменения смены */

CREATE PROCEDURE /*PREFIX*/U_SHIFT
(
  SHIFT_ID VARCHAR(32),
  ACCOUNT_ID VARCHAR(32),
  DATE_BEGIN TIMESTAMP,
  DATE_END TIMESTAMP,
  OLD_SHIFT_ID VARCHAR(32)
)
AS
BEGIN
  UPDATE /*PREFIX*/SHIFTS
     SET SHIFT_ID=:SHIFT_ID,
         ACCOUNT_ID=:ACCOUNT_ID,
         DATE_BEGIN=:DATE_BEGIN,
         DATE_END=:DATE_END
   WHERE SHIFT_ID=:OLD_SHIFT_ID;
END;

--

/* Создание процедуры удаления смены */

CREATE PROCEDURE /*PREFIX*/D_SHIFT
(
  OLD_SHIFT_ID VARCHAR(32)
)
AS
BEGIN
  DELETE FROM /*PREFIX*/SHIFTS 
        WHERE SHIFT_ID=:OLD_SHIFT_ID;
END;

--

/* Фиксация изменений */

COMMIT