/* Создание таблицы клиентов */

CREATE TABLE /*PREFIX*/CLIENTS
(
  CLIENT_ID VARCHAR(32) NOT NULL,
  CLIENT_GROUP_ID VARCHAR(32) NOT NULL,
  CALC_ID VARCHAR(32) NOT NULL,
  SOURCE_ID VARCHAR(32),
  STREET_ACTUAL_ID VARCHAR(32),
  INDEX_ACTUAL VARCHAR(10),
  HOUSE_ACTUAL VARCHAR(10),
  FLAT_ACTUAL VARCHAR(10),
  PHONE_MOBILE VARCHAR(100) NOT NULL,
  PHONE_HOME VARCHAR(100),
  PHONE_WORK VARCHAR(100),
  SEX INTEGER,
  PASSPORT VARCHAR(250),
  DATE_BIRTH DATE,
  PLACE_BIRTH VARCHAR(250),
  MIN_BALANCE NUMERIC(15,2),
  PRIMARY KEY (CLIENT_ID),
  FOREIGN KEY (CLIENT_ID) REFERENCES /*PREFIX*/ACCOUNTS (ACCOUNT_ID),
  FOREIGN KEY (CALC_ID) REFERENCES /*PREFIX*/CALCS (CALC_ID),
  FOREIGN KEY (SOURCE_ID) REFERENCES /*PREFIX*/SOURCES (SOURCE_ID),
  FOREIGN KEY (STREET_ACTUAL_ID) REFERENCES /*PREFIX*/STREETS (STREET_ID)
)

--

/* Создание просмотра клиентов */

CREATE VIEW /*PREFIX*/S_CLIENTS
(
  CLIENT_ID,
  CLIENT_GROUP_ID,
  CALC_ID,
  SOURCE_ID,
  STREET_ACTUAL_ID,
  INDEX_ACTUAL,
  HOUSE_ACTUAL,
  FLAT_ACTUAL,
  PHONE_MOBILE,
  PHONE_HOME,
  PHONE_WORK,
  SEX,
  PASSPORT,
  DATE_BIRTH,
  PLACE_BIRTH,
  MIN_BALANCE,

)
AS
SELECT C.*,
       A.USER_NAME,
       A.PASSWORD,
       A.LOCKED,
       A.SURNAME,
       A.NAME,
       A.PATRONYMIC,
       A.DATE_CREATE,


  FROM /*PREFIX*/CLIENTS C
  JOIN /*PREFIX*/ACCOUNTS A ON A.ACCOUNT_ID=C.CLIENT_ID
  LEFT JOIN /*PREFIX*/FIRMS F ON F.FIRM_ID=A.FIRM_ID
  JOIN /*PREFIX*/CALCS CL ON CL.CALC_ID=C.CALC_ID


--

/* Создание процедуры добавления клиента */

CREATE OR ALTER PROCEDURE /*PREFIX*/I_CLIENT (
  CLIENT_ID VARCHAR(32),
  CALC_ID VARCHAR(32),
  PHONE_MOBILE VARCHAR(100),
  PHONE_HOME VARCHAR(100),
  DESCRIPTION VARCHAR(250),
  MIN_BALANCE NUMERIC(15,2),
  USER_NAME VARCHAR(100),
  LOCKED INTEGER,
  SURNAME VARCHAR(100),
  NAME VARCHAR(100),
  PATRONYMIC VARCHAR(100))
AS
  DECLARE ROLE_ID VARCHAR(32);
BEGIN

  INSERT INTO /*PREFIX*/ACCOUNTS (ACCOUNT_ID,DATE_CREATE,USER_NAME,LOCKED,SURNAME,NAME,PATRONYMIC,IS_ROLE,PHONE)
       VALUES (:CLIENT_ID,CURRENT_TIMESTAMP,:USER_NAME,:LOCKED,:SURNAME,:NAME,:PATRONYMIC,0,:PHONE_MOBILE);

  INSERT INTO /*PREFIX*/CLIENTS (CLIENT_ID,CALC_ID,PHONE_MOBILE,PHONE_HOME,DESCRIPTION,MIN_BALANCE)
       VALUES (:CLIENT_ID,:CALC_ID,:PHONE_MOBILE,:PHONE_HOME,:DESCRIPTION,:MIN_BALANCE);

  ROLE_ID='1D3BDEDD9A0B9EE84AEDC1FDED4F5A93'; /* Клиенты */
  INSERT INTO /*PREFIX*/ACCOUNT_ROLES (ROLE_ID,ACCOUNT_ID)
       VALUES (:ROLE_ID,:CLIENT_ID);
END;

--

/* Создание процедуры изменения клиента */

CREATE OR ALTER PROCEDURE /*PREFIX*/U_CLIENT
(
  CLIENT_ID VARCHAR(32),
  CALC_ID VARCHAR(32),
  PHONE_MOBILE VARCHAR(100),
  PHONE_HOME VARCHAR(100),
  DESCRIPTION VARCHAR(250),
  MIN_BALANCE NUMERIC(15,2),
  USER_NAME VARCHAR(100),
  LOCKED INTEGER,
  SURNAME VARCHAR(100),
  NAME VARCHAR(100),
  PATRONYMIC VARCHAR(100),
  OLD_CLIENT_ID VARCHAR(32)
)
AS
BEGIN

  UPDATE /*PREFIX*/ACCOUNTS
     SET ACCOUNT_ID=:CLIENT_ID,
         USER_NAME=:USER_NAME,
         LOCKED=:LOCKED,
         SURNAME=:SURNAME,
         NAME=:NAME,
         PATRONYMIC=:PATRONYMIC,
         IS_ROLE=0,
         PHONE=:PHONE_MOBILE
   WHERE ACCOUNT_ID=:OLD_CLIENT_ID;

  UPDATE /*PREFIX*/CLIENTS
     SET CLIENT_ID=:CLIENT_ID,
         CALC_ID=:CALC_ID,
         PHONE_MOBILE=:PHONE_MOBILE,
         PHONE_HOME=:PHONE_HOME,
         DESCRIPTION=:DESCRIPTION,
         MIN_BALANCE=:MIN_BALANCE
   WHERE CLIENT_ID=:OLD_CLIENT_ID;

END;

--

/* Создание процедуры удаления клиента */

CREATE OR ALTER PROCEDURE /*PREFIX*/D_CLIENT (
  OLD_CLIENT_ID VARCHAR(32))
AS
BEGIN
  DELETE FROM /*PREFIX*/CLIENTS
        WHERE CLIENT_ID=:OLD_CLIENT_ID;

  DELETE FROM /*PREFIX*/ACCOUNT_ROLES
        WHERE ACCOUNT_ID=:OLD_CLIENT_ID;

  DELETE FROM /*PRFEIX*/ACCOUNTS
        WHERE ACCOUNT_ID=:OLD_CLIENT_ID;
END;

--

/* Фиксация изменений */

COMMIT
