/* Создание таблицы еженедельных графиков водителя */

CREATE TABLE /*PREFIX*/DRIVER_WEEK_SCHEDULES
(
  DRIVER_ID VARCHAR(32) NOT NULL,
  WEEK_DAY INTEGER NOT NULL,
  DAY_HOUR INTEGER NOT NULL,
  PRIMARY KEY (DRIVER_ID,WEEK_DAY,DAY_HOUR),
  FOREIGN KEY (DRIVER_ID) REFERENCES /*PREFIX*/DRIVERS (DRIVER_ID)
)

--

/* Создание просмотра еженедельных графиков водителя */

CREATE VIEW /*PREFIX*/S_DRIVER_WEEK_SCHEDULES
(
  DRIVER_ID,
  WEEK_DAY,
  DAY_HOUR,
  DRIVER_NAME,
  DRIVER_PHONE
)
AS
SELECT DS.*,
       A.USER_NAME AS DRIVER_NAME,
       A.PHONE AS DRIVER_PHONE
  FROM /*PREFIX*/DRIVER_WEEK_SCHEDULES DS
  JOIN /*PREFIX*/DRIVERS D ON D.DRIVER_ID=DS.DRIVER_ID
  JOIN /*PREFIX*/ACCOUNTS A ON A.ACCOUNT_ID=D.DRIVER_ID

--

/* Создание процедуры добавления еженедельного графика водителю */

CREATE OR ALTER PROCEDURE /*PREFIX*/I_DRIVER_WEEK_SCHEDULE
(
  DRIVER_ID VARCHAR(32),
  WEEK_DAY INTEGER,
  DAY_HOUR INTEGER
)
AS
BEGIN
  INSERT INTO /*PREFIX*/DRIVER_WEEK_SCHEDULES (DRIVER_ID,WEEK_DAY,DAY_HOUR)
                                  VALUES (:DRIVER_ID,:WEEK_DAY,:DAY_HOUR);
END;

--

/* Создание процедуры изменения еженедельного графика водителя */

CREATE OR ALTER PROCEDURE /*PREFIX*/U_DRIVER_WEEK_SCHEDULE
(
  DRIVER_ID VARCHAR(32),
  WEEK_DAY INTEGER,
  DAY_HOUR INTEGER,
  OLD_DRIVER_ID VARCHAR(32),
  OLD_WEEK_DAY INTEGER,
  OLD_DAY_HOUR INTEGER
)
AS
BEGIN
  UPDATE /*PREFIX*/DRIVER_WEEK_SCHEDULES
     SET DRIVER_ID=:DRIVER_ID,
         WEEK_DAY=:WEEK_DAY,
         DAY_HOUR=:DAY_HOUR
   WHERE DRIVER_ID=:OLD_DRIVER_ID
     AND WEEK_DAY=:OLD_WEEK_DAY
     AND DAY_HOUR=:OLD_DAY_HOUR;
END;

--

/* Создание процедуры удаления еженедельного графика водителя */

CREATE OR ALTER PROCEDURE /*PREFIX*/D_DRIVER_WEEK_SCHEDULE
(
  OLD_DRIVER_ID VARCHAR(32),
  OLD_WEEK_DAY INTEGER,
  OLD_DAY_HOUR INTEGER
)
AS
BEGIN
  DELETE FROM /*PREFIX*/DRIVER_WEEK_SCHEDULES 
        WHERE DRIVER_ID=:OLD_DRIVER_ID
          AND WEEK_DAY=:OLD_WEEK_DAY
          AND DAY_HOUR=:OLD_DAY_HOUR;
END;

--

/* Фиксация изменений */

COMMIT