/* Создание таблицы дисконтов */

CREATE TABLE /*PREFIX*/DISCOUNTS
(
  DISCOUNT_ID VARCHAR(32) NOT NULL,
  DISCOUNT_TYPE_ID VARCHAR(32) NOT NULL,
  CLIENT_ID VARCHAR(32) NOT NULL,
  NUM VARCHAR(100) NOT NULL,
  DATE_BEGIN DATE NOT NULL,
  DATE_END DATE,
  PRIORITY INTEGER,
  PRIMARY KEY (DISCOUNT_ID),
  FOREIGN KEY (DISCOUNT_TYPE_ID) REFERENCES /*PREFIX*/DISCOUNT_TYPES (DISCOUNT_TYPE_ID),
  FOREIGN KEY (CLIENT_ID) REFERENCES /*PREFIX*/CLIENTS (CLIENT_ID)
)

--

/* Создание просмотра дисконтов */

CREATE VIEW /*PREFIX*/S_DISCOUNTS
(
  DISCOUNT_ID,
  DISCOUNT_TYPE_ID,
  CLIENT_ID,
  NUM,
  DATE_BEGIN,
  DATE_END,
  PRIORITY,
  DISCOUNT_TYPE_NAME,
  USER_NAME
)
AS
SELECT D.*,
       DT.NAME AS DISCOUNT_TYPE_NAME,
       A.USER_NAME
  FROM /*PREFIX*/DISCOUNTS D
  JOIN /*PREFIX*/DISCOUNT_TYPES DT ON DT.DISCOUNT_TYPE_ID=D.DISCOUNT_TYPE_ID
  JOIN /*PREFIX*/CLIENTS C ON C.CLIENT_ID=D.CLIENT_ID
  JOIN /*PREFIX*/ACCOUNTS A ON A.ACCOUNT_ID=C.CLIENT_ID

--

/* Создание процедуры добавления дисконта */

CREATE PROCEDURE /*PREFIX*/I_DISCOUNT
(
  DISCOUNT_ID VARCHAR(32),
  DISCOUNT_TYPE_ID VARCHAR(32),
  CLIENT_ID VARCHAR(32),
  NUM VARCHAR(100),
  DATE_BEGIN DATE,
  DATE_END DATE,
  PRIORITY INTEGER
)
AS
BEGIN
  INSERT INTO /*PREFIX*/DISCOUNTS (DISCOUNT_ID,DISCOUNT_TYPE_ID,CLIENT_ID,NUM,
                                   DATE_BEGIN,DATE_END,PRIORITY)
       VALUES (:DISCOUNT_ID,:DISCOUNT_TYPE_ID,:CLIENT_ID,:NUM,
               :DATE_BEGIN,:DATE_END,:PRIORITY);
END;

--

/* Создание процедуры изменения дисконта */

CREATE PROCEDURE /*PREFIX*/U_DISCOUNT
(
  DISCOUNT_ID VARCHAR(32),
  DISCOUNT_TYPE_ID VARCHAR(32),
  CLIENT_ID VARCHAR(32),
  NUM VARCHAR(100),
  DATE_BEGIN DATE,
  DATE_END DATE,
  PRIORITY INTEGER,
  OLD_DISCOUNT_ID VARCHAR(32)
)
AS
BEGIN
  UPDATE /*PREFIX*/DISCOUNTS
     SET DISCOUNT_ID=:DISCOUNT_ID,
         DISCOUNT_TYPE_ID=:DISCOUNT_TYPE_ID,
         CLIENT_ID=:CLIENT_ID,
         NUM=:NUM,
         DATE_BEGIN=:DATE_BEGIN,
         DATE_END=:DATE_END,
         PRIORITY=:PRIORITY
   WHERE DISCOUNT_ID=:OLD_DISCOUNT_ID;
END;

--

/* Создание процедуры удаления дисконта */

CREATE PROCEDURE /*PREFIX*/D_DISCOUNT
(
  OLD_DISCOUNT_ID VARCHAR(32)
)
AS
BEGIN
  DELETE FROM /*PREFIX*/DISCOUNTS 
        WHERE DISCOUNT_ID=:OLD_DISCOUNT_ID;
END;

--

/* Фиксация изменений */

COMMIT