/* Создание таблицы телефонов клиентов */

CREATE TABLE /*PREFIX*/CLIENT_PHONES
(
  CLIENT_ID VARCHAR(32) NOT NULL,
  PHONE VARCHAR(100) NOT NULL,
  METHOD_ID VARCHAR(32),
  DESCRIPTION VARCHAR(250),
  PRIMARY KEY (CLIENT_ID,PHONE),
  FOREIGN KEY (CLIENT_ID) REFERENCES /*PREFIX*/CLIENTS (CLIENT_ID),
  FOREIGN KEY (METHOD_ID) REFERENCES /*PREFIX*/METHODS (METHOD_ID)
)

--

/* Создание просмотра телефонов клиентов */

CREATE VIEW /*PREFIX*/S_CLIENT_PHONES
(
  CLIENT_ID,
  PHONE,
  METHOD_ID,
  DESCRIPTION,
  USER_NAME,
  METHOD_NAME
)
AS
SELECT CP.*,
       A.USER_NAME,
       M.NAME AS METHOD_NAME
  FROM /*PREFIX*/CLIENT_PHONES CP
  JOIN /*PREFIX*/CLIENTS C ON C.CLIENT_ID=CP.CLIENT_ID
  JOIN /*PREFIX*/ACCOUNTS A ON A.ACCOUNT_ID=C.CLIENT_ID
  LEFT JOIN /*PREFIX*/METHODS M ON M.METHOD_ID=CP.METHOD_ID

--

/* Создание процедуры добавления телефона клиенту */

CREATE PROCEDURE /*PREFIX*/I_CLIENT_PHONE
(
  CLIENT_ID VARCHAR(32),
  PHONE VARCHAR(100),
  METHOD_ID VARCHAR(32),
  DESCRIPTION VARCHAR(250)
)
AS
BEGIN
  INSERT INTO /*PREFIX*/CLIENT_PHONES (CLIENT_ID,PHONE,METHOD_ID,DESCRIPTION)
       VALUES (:CLIENT_ID,:PHONE,:METHOD_ID,:DESCRIPTION);
END;

--

/* Создание процедуры изменения телефона у клиента */

CREATE PROCEDURE /*PREFIX*/U_CLIENT_PHONE
(
  CLIENT_ID VARCHAR(32),
  PHONE VARCHAR(100),
  METHOD_ID VARCHAR(32),
  DESCRIPTION VARCHAR(250),
  OLD_CLIENT_ID VARCHAR(32),
  OLD_PHONE VARCHAR(100)
)
AS
BEGIN
  UPDATE /*PREFIX*/CLIENT_PHONES
     SET CLIENT_ID=:CLIENT_ID,
         PHONE=:PHONE,
         METHOD_ID=:METHOD_ID,
         DESCRIPTION=:DESCRIPTION
   WHERE CLIENT_ID=:OLD_CLIENT_ID
     AND PHONE=:OLD_PHONE;
END;

--

/* Создание процедуры удаления телефона у клиента */

CREATE PROCEDURE /*PREFIX*/D_CLIENT_PHONE
(
  OLD_CLIENT_ID VARCHAR(32),
  OLD_PHONE VARCHAR(100)
)
AS
BEGIN
  DELETE FROM /*PREFIX*/CLIENT_PHONES 
        WHERE CLIENT_ID=:OLD_CLIENT_ID
          AND PHONE=:OLD_PHONE;
END;

--

/* Фиксация изменений */

COMMIT