/* Создание таблицы дочерних клиентов */

CREATE TABLE /*PREFIX*/CLIENT_CHILDS
(
  CLIENT_ID VARCHAR(32) NOT NULL,
  CHILD_ID VARCHAR(32) NOT NULL,
  PRIMARY KEY (CLIENT_ID,CHILD_ID),
  FOREIGN KEY (CLIENT_ID) REFERENCES /*PREFIX*/CLIENTS (CLIENT_ID),
  FOREIGN KEY (CHILD_ID) REFERENCES /*PREFIX*/CLIENTS (CLIENT_ID)
)

--

/* Создание просмотра дочерних клиентов */

CREATE VIEW /*PREFIX*/S_CLIENT_CHILDS
(
  CLIENT_ID,
  CHILD_ID,
  CLIENT_USER_NAME,
  CHILD_USER_NAME,
  CHILD_SURNAME,
  CHILD_NAME,
  CHILD_PATRONYMIC
)
AS
SELECT CC.*,
       A1.USER_NAME AS CLIENT_USER_NAME,
       A2.USER_NAME AS CHILD_USER_NAME,
       A2.SURNAME AS CHILD_SURNAME,
       A2.NAME AS CHILD_USER_NAME,
       A2.PATRONYMIC AS CHILD_PATRONYMIC
  FROM /*PREFIX*/CLIENT_CHILDS CC
  JOIN /*PREFIX*/CLIENTS C1 ON C1.CLIENT_ID=CC.CLIENT_ID
  JOIN /*PREFIX*/ACCOUNTS A1 ON A1.ACCOUNT_ID=CC.CLIENT_ID
  JOIN /*PREFIX*/CLIENTS C2 ON C2.CLIENT_ID=CC.CHILD_ID
  JOIN /*PREFIX*/ACCOUNTS A2 ON A2.ACCOUNT_ID=CC.CHILD_ID

--

/* Создание процедуры добавления дочернего клиента */

CREATE PROCEDURE /*PREFIX*/I_CLIENT_CHILD
(
  CLIENT_ID VARCHAR(32),
  CHILD_ID VARCHAR(32)
)
AS
BEGIN
  INSERT INTO /*PREFIX*/CLIENT_CHILDS (CLIENT_ID,CHILD_ID)
       VALUES (:CLIENT_ID,:CHILD_ID);
END;

--

/* Создание процедуры изменения дочернего у клиента */

CREATE PROCEDURE /*PREFIX*/U_CLIENT_CHILD
(
  CLIENT_ID VARCHAR(32),
  CHILD_ID VARCHAR(32),
  OLD_CLIENT_ID VARCHAR(32),
  OLD_CHILD_ID VARCHAR(32)
)
AS
BEGIN
  UPDATE /*PREFIX*/CLIENT_CHILDS
     SET CLIENT_ID=:CLIENT_ID,
         CHILD_ID=:CHILD_ID
   WHERE CLIENT_ID=:OLD_CLIENT_ID
     AND CHILD_ID=:OLD_CHILD_ID;
END;

--

/* Создание процедуры удаления дочернего у клиента */

CREATE PROCEDURE /*PREFIX*/D_CLIENT_CHILD
(
  OLD_CLIENT_ID VARCHAR(32),
  OLD_CHILD_ID VARCHAR(32)
)
AS
BEGIN
  DELETE FROM /*PREFIX*/CLIENT_CHILDS 
        WHERE CLIENT_ID=:OLD_CLIENT_ID
          AND CHILD_ID=:OLD_CHILD_ID;
END;

--

/* Фиксация изменений */

COMMIT