/* Создание таблицы состава зон */

CREATE TABLE /*PREFIX*/COMPOSITIONS
(
  COMPOSITION_ID VARCHAR(32) NOT NULL,
  ZONE_ID VARCHAR(32) NOT NULL,
  STREET_ID VARCHAR(32) NOT NULL,
  TYPE_COMPOSITION INTEGER NOT NULL,
  HOUSES VARCHAR(250),
  EXCEPTIONS VARCHAR(250),
  PRIMARY KEY (COMPOSITION_ID),
  FOREIGN KEY (ZONE_ID) REFERENCES ZONES (ZONE_ID),
  FOREIGN KEY (STREET_ID) REFERENCES STREETS (STREET_ID)
)

--

/* Создание просмотра состава зон */

CREATE VIEW /*PREFIX*/S_COMPOSITIONS
(
  COMPOSITION_ID,
  ZONE_ID,
  STREET_ID,
  TYPE_COMPOSITION,
  HOUSES,
  EXCEPTIONS,
  ZONE_NAME,
  STREET_NAME,
  STREET_PREFIX,
  LOCALITY_NAME,
  LOCALITY_PREFIX
)
AS
SELECT C.*,
       Z.NAME AS ZONE_NAME,
       S.NAME AS STREET_NAME,
       S.PREFIX AS STREET_PREFIX,
       L.NAME AS LOCALITY_NAME,
       L.PREFIX AS LOCALITY_PREFIX
  FROM /*PREFIX*/COMPOSITIONS C
  JOIN /*PREFIX*/ZONES Z ON Z.ZONE_ID=C.ZONE_ID
  JOIN /*PREFIX*/STREETS S ON S.STREET_ID=C.STREET_ID
  JOIN /*PREFIX*/LOCALITIES L ON L.LOCALITY_ID=S.LOCALITY_ID

--

/* Создание процедуры добавления состава зоны */

CREATE PROCEDURE /*PREFIX*/I_COMPOSITION
(
  COMPOSITION_ID VARCHAR(32),
  ZONE_ID VARCHAR(32),
  STREET_ID VARCHAR(32),
  TYPE_COMPOSITION INTEGER,
  HOUSES VARCHAR(250),
  EXCEPTIONS VARCHAR(250)
)
AS
BEGIN
  INSERT INTO /*PREFIX*/COMPOSITIONS (COMPOSITION_ID,ZONE_ID,STREET_ID,
                                      TYPE_COMPOSITION,HOUSES,EXCEPTIONS)
       VALUES (:COMPOSITION_ID,:ZONE_ID,:STREET_ID,
               :TYPE_COMPOSITION,:HOUSES,:EXCEPTIONS);
END;

--

/* Создание процедуры изменения состава зоны */

CREATE PROCEDURE /*PREFIX*/U_COMPOSITION
(
  COMPOSITION_ID VARCHAR(32),
  ZONE_ID VARCHAR(32),
  STREET_ID VARCHAR(32),
  TYPE_COMPOSITION INTEGER,
  HOUSES VARCHAR(250),
  EXCEPTIONS VARCHAR(250),
  OLD_COMPOSITION_ID VARCHAR(32)
)
AS
BEGIN
  UPDATE /*PREFIX*/COMPOSITIONS
     SET COMPOSITION_ID=:COMPOSITION_ID,
         ZONE_ID=:ZONE_ID,
         STREET_ID=:STREET_ID,
         TYPE_COMPOSITION=:TYPE_COMPOSITION,
         HOUSES=:HOUSES,
         EXCEPTIONS=:EXCEPTIONS
   WHERE COMPOSITION_ID=:OLD_COMPOSITION_ID;
END;

--

/* Создание процедуры удаления состава зоны */

CREATE PROCEDURE /*PREFIX*/D_COMPOSITION
(
  OLD_COMPOSITION_ID VARCHAR(32)
)
AS
BEGIN
  DELETE FROM /*PREFIX*/COMPOSITIONS 
        WHERE COMPOSITION_ID=:OLD_COMPOSITION_ID;
END;

--

/* Фиксация изменений */

COMMIT