/* Создание таблицы действий */

CREATE TABLE /*PREFIX*/ACTIONS
(
  ACTION_ID VARCHAR(32) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(250),
  PROC_DETECT VARCHAR(100),
  FONT_COLOR INTEGER,
  BRUSH_COLOR INTEGER,
  PERIOD INTEGER,
  PRIORITY INTEGER,
  PRIMARY KEY (ACTION_ID)
)

--

/* Создание просмотра действий */

CREATE VIEW /*PREFIX*/S_ACTIONS
AS
SELECT * FROM /*PREFIX*/ACTIONS

--

/* Создание процедуры добавления действия */

CREATE PROCEDURE /*PREFIX*/I_ACTION
(
  ACTION_ID VARCHAR(32),
  NAME VARCHAR(100),
  DESCRIPTION VARCHAR(250),
  PROC_DETECT VARCHAR(100),
  FONT_COLOR INTEGER,
  BRUSH_COLOR INTEGER,
  PERIOD INTEGER,
  PRIORITY INTEGER
)
AS
BEGIN
  INSERT INTO /*PREFIX*/ACTIONS (ACTION_ID,NAME,DESCRIPTION,PROC_DETECT,
                                 FONT_COLOR,BRUSH_COLOR,PERIOD,PRIORITY)
       VALUES (:ACTION_ID,:NAME,:DESCRIPTION,:PROC_DETECT,
               :FONT_COLOR,:BRUSH_COLOR,:PERIOD,:PRIORITY);
END;

--

/* Создание процедуры изменения действия */

CREATE PROCEDURE /*PREFIX*/U_ACTION
(
  ACTION_ID VARCHAR(32),
  NAME VARCHAR(100),
  DESCRIPTION VARCHAR(250),
  PROC_DETECT VARCHAR(100),
  FONT_COLOR INTEGER,
  BRUSH_COLOR INTEGER,
  PERIOD INTEGER,
  PRIORITY INTEGER,
  OLD_ACTION_ID VARCHAR(32)
)
AS
BEGIN
  UPDATE /*PREFIX*/ACTIONS
     SET ACTION_ID=:ACTION_ID,
         NAME=:NAME,
         DESCRIPTION=:DESCRIPTION,
         PROC_DETECT=:PROC_DETECT,
         FONT_COLOR=:FONT_COLOR,
         BRUSH_COLOR=:BRUSH_COLOR,
         PERIOD=:PERIOD,
         PRIORITY=:PRIORITY
   WHERE ACTION_ID=:OLD_ACTION_ID;
END;

--

/* Создание процедуры удаления действия */

CREATE PROCEDURE /*PREFIX*/D_ACTION
(
  OLD_ACTION_ID VARCHAR(32)
)
AS
BEGIN
  DELETE FROM /*PREFIX*/ACTIONS 
        WHERE ACTION_ID=:OLD_ACTION_ID;
END;

--

/* Фиксация изменений */

COMMIT