/* Создание таблицы расчетов */

CREATE TABLE /*PREFIX*/RATES
(
  RATE_ID VARCHAR(32) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(250),
  TYPE_RATE INTEGER NOT NULL,
  PROC_NAME VARCHAR(100),
  RATE_SUM NUMERIC(15,2),
  PERIOD INTEGER,
  PRIORITY INTEGER,
  PRIMARY KEY (RATE_ID)
)

--

/* Создание просмотра расчетов */

CREATE VIEW /*PREFIX*/S_RATES
AS
SELECT * FROM /*PREFIX*/RATES

--

/* Создание процедуры добавления расчета */

CREATE PROCEDURE /*PREFIX*/I_RATE
(
  RATE_ID VARCHAR(32),
  NAME VARCHAR(100),
  DESCRIPTION VARCHAR(250),
  TYPE_RATE INTEGER,
  PROC_NAME VARCHAR(100),
  RATE_SUM NUMERIC(15,2),
  PERIOD INTEGER,
  PRIORITY INTEGER
)
AS
BEGIN
  INSERT INTO /*PREFIX*/RATES (RATE_ID,NAME,DESCRIPTION,TYPE_RATE,
                               PROC_NAME,RATE_SUM,PERIOD,PRIORITY)
       VALUES (:RATE_ID,:NAME,:DESCRIPTION,:TYPE_RATE,
               :PROC_NAME,:RATE_SUM,:PERIOD,:PRIORITY);
END;

--

/* Создание процедуры изменения расчета */

CREATE PROCEDURE /*PREFIX*/U_RATE
(
  RATE_ID VARCHAR(32),
  NAME VARCHAR(100),
  DESCRIPTION VARCHAR(250),
  TYPE_RATE INTEGER,
  PROC_NAME VARCHAR(100),
  RATE_SUM NUMERIC(15,2),
  PERIOD INTEGER,
  PRIORITY INTEGER,
  OLD_RATE_ID VARCHAR(32)
)
AS
BEGIN
  UPDATE /*PREFIX*/RATES
     SET RATE_ID=:RATE_ID,
         NAME=:NAME,
         DESCRIPTION=:DESCRIPTION,
         TYPE_RATE=:TYPE_RATE,
         PROC_NAME=:PROC_NAME,
         RATE_SUM=:RATE_SUM,
         PERIOD=:PERIOD,
         PRIORITY=:PRIORITY
   WHERE RATE_ID=:OLD_RATE_ID;
END;

--

/* Создание процедуры удаления расчета */

CREATE PROCEDURE /*PREFIX*/D_RATE
(
  OLD_RATE_ID VARCHAR(32)
)
AS
BEGIN
  DELETE FROM /*PREFIX*/RATES 
        WHERE RATE_ID=:OLD_RATE_ID;
END;

--

/* Фиксация изменений */

COMMIT