/* Создание таблицы заказов */

CREATE TABLE /*PREFIX*/ORDERS
(
  ORDER_ID VARCHAR(32) NOT NULL,
  ACTION_ID VARCHAR(32) NOT NULL,
  RATE_ID VARCHAR(32) NOT NULL,
  CAR_TYPE_ID VARCHAR(32) NOT NULL,
  WHO_ACCEPT_ID VARCHAR(32) NOT NULL,
  STREET_ID VARCHAR(32) NOT NULL,
  ZONE_ID VARCHAR(32),
  PARENT_ID VARCHAR(32),
  FIRM_ID VARCHAR(32),
  CAR_ID VARCHAR(32),
  WHO_PROCESS_ID VARCHAR(32),
  WHO_HISTORY_ID VARCHAR(32),
  RESULT_ID VARCHAR(32),
  PARK_ID VARCHAR(32),
  SOURCE_ID VARCHAR(32),
  DISCOUNT_ID VARCHAR(32),
  DRIVER_ID VARCHAR(32),
  ORDER_NUM VARCHAR(10) NOT NULL,
  PHONE VARCHAR(100) NOT NULL,
  HOUSE VARCHAR(10) NOT NULL,
  FLAT VARCHAR(10),
  PORCH VARCHAR(10),
  DATE_ACCEPT TIMESTAMP NOT NULL,
  DATE_ARRIVAL TIMESTAMP NOT NULL,
  DATE_BEGIN TIMESTAMP,
  DATE_END TIMESTAMP,
  CUSTOMER VARCHAR(250),
  DESCRIPTION VARCHAR(250),
  COST_RATE NUMERIC(15,2),
  COST_FACT NUMERIC(15,2),
  TYPE_ACCEPT INTEGER NOT NULL,
  TYPE_PROCESS INTEGER,
  DATE_HISTORY TIMESTAMP,
  BEFORE_PERIOD INTEGER NOT NULL,
  FINISHED INTEGER NOT NULL,
  PRIMARY KEY (ORDER_ID),
  FOREIGN KEY (ACTION_ID) REFERENCES /*PREFIX*/ACTIONS (ACTION_ID),
  FOREIGN KEY (RATE_ID) REFERENCES /*PREFIX*/RATES (RATE_ID),
  FOREIGN KEY (CAR_TYPE_ID) REFERENCES /*PREFIX*/CAR_TYPES (CAR_TYPE_ID),
  FOREIGN KEY (WHO_ACCEPT_ID) REFERENCES /*PREFIX*/ACCOUNTS (ACCOUNT_ID),
  FOREIGN KEY (STREET_ID) REFERENCES /*PREFIX*/STREETS (STREET_ID),
  FOREIGN KEY (ZONE_ID) REFERENCES /*PREFIX*/ZONES (ZONE_ID),
  FOREIGN KEY (PARENT_ID) REFERENCES /*PREFIX*/ORDERS (ORDER_ID),
  FOREIGN KEY (FIRM_ID) REFERENCES /*PREFIX*/FIRMS (FIRM_ID),
  FOREIGN KEY (CAR_ID) REFERENCES /*PREFIX*/CARS (CAR_ID),
  FOREIGN KEY (WHO_PROCESS_ID) REFERENCES /*PREFIX*/ACCOUNTS (ACCOUNT_ID),
  FOREIGN KEY (WHO_HISTORY_ID) REFERENCES /*PERFIX*/ACCOUNTS (ACCOUNT_ID),
  FOREIGN KEY (RESULT_ID) REFERENCES /*PREFIX*/RESULTS (RESULT_ID),
  FOREIGN KEY (PARK_ID) REFERENCES /*PREFIX*/PARKS (PARK_ID),
  FOREIGN KEY (SOURCE_ID) REFERENCES /*PREFIX*/SOURCES (SOURCE_ID),
  FOREIGN KEY (DISCOUNT_ID) REFERENCES /*PREFIX*/DISCOUNTS (DISCOUNT_ID),
  FOREIGN KEY (DRIVER_ID) REFERENCES /*PREFIX*/DRIVERS (DRIVER_ID)
)

--

/* Создание просмотра заказов */

CREATE VIEW /*PREFIX*/S_ORDERS
(
  ORDER_ID,
  ACTION_ID,
  RATE_ID,
  CAR_TYPE_ID,
  WHO_ACCEPT_ID,
  STREET_ID,
  ZONE_ID,
  PARENT_ID,
  FIRM_ID,
  CAR_ID,
  WHO_PROCESS_ID,
  WHO_HISTORY_ID,
  RESULT_ID,
  PARK_ID,
  SOURCE_ID,
  DISCOUNT_ID,
  DRIVER_ID,
  ORDER_NUM,
  PHONE,
  HOUSE,
  FLAT,
  PORCH,
  DATE_ACCEPT,
  DATE_ARRIVAL,
  DATE_BEGIN,
  DATE_END,
  CUSTOMER,
  DESCRIPTION,
  COST_RATE,
  COST_FACT,
  TYPE_ACCEPT,
  TYPE_PROCESS,
  DATE_HISTORY,
  BEFORE_PERIOD,
  FINISHED,
  ACTION_NAME,
  ACTION_BRUSH_COLOR,
  ACTION_FONT_COLOR,
  ACTION_PERIOD,
  RATE_NAME,
  CAR_TYPE_NAME,
  WHO_ACCEPT,
  STREET_NAME,
  STREET_PREFIX,
  LOCALITY_ID,
  LOCALITY_NAME,
  LOCALITY_PREFIX,
  ZONE_NAME,
  PARENT_ORDER_NUM,
  FIRM_SMALL_NAME,
  CAR_BRAND,
  CAR_STATE_NUM,
  CAR_COLOR,
  CAR_CALLSIGN,
  WHO_PROCESS,
  WHO_HISTORY,
  RESULT_NAME,
  RESULT_BRUSH_COLOR,
  RESULT_FONT_COLOR,
  PARK_NAME,
  PARK_DESCRIPTION,
  SOURCE_NAME,
  DISCOUNT_NAME,
  DRIVER_NAME,
  STATUS
)
AS
SELECT O.*,
       A.NAME AS ACTION_NAME,
       A.BRUSH_COLOR AS ACTION_BRUSH_COLOR,
       A.FONT_COLOR AS ACTION_FONT_COLOR,
       A.PERIOD AS ACTION_PERIOD,
       R.NAME AS RATE_NAME,
       CT.NAME AS CAR_TYPE_NAME,
       A1.USER_NAME AS WHO_ACCEPT,
       S1.NAME AS STREET_NAME,
       S1.PREFIX AS STREET_PREFIX,
       L1.LOCALITY_ID,
       L1.NAME AS LOCALITY_NAME,
       L1.PREFIX AS LOCALITY_PREFIX,
       Z.NAME AS ZONE_NAME,
       OP.ORDER_NUM AS PARENT_ORDER_NUM,
       F.SMALL_NAME AS FIRM_SMALL_NAME,
       C.BRAND AS CAR_BRAND,
       C.STATE_NUM AS CAR_STATE_NUM,
       C.COLOR AS CAR_COLOR,
       C.CALLSIGN AS CAR_CALLSIGN,
       A2.USER_NAME AS WHO_PROCESS,
       A4.USER_NAME AS WHO_HISTORY,
       RT.NAME AS RESULT_NAME,
       RT.BRUSH_COLOR AS RESULT_BRUSH_COLOR,
       RT.FONT_COLOR AS RESULT_FONT_COLOR,
       P.NAME AS PARK_NAME,
       P.DESCRIPTION AS PARK_DESCRIPTION,
       S.NAME AS SOURCE_NAME,
       D.NAME AS DISCOUNT_NAME,
       A3.USER_NAME AS DRIVER_NAME,
       (CASE WHEN (O.FINISHED=0) AND ((O.DATE_ACCEPT+(O.BEFORE_PERIOD*(1e0/24/60)))>=O.DATE_ARRIVAL) THEN 0
             WHEN (O.FINISHED=0) AND ((O.DATE_ACCEPT+(O.BEFORE_PERIOD*(1e0/24/60)))<O.DATE_ARRIVAL) THEN 1
             WHEN O.FINISHED=1 THEN 2
        ELSE 0 END) AS STATUS

  FROM /*PREFIX*/ORDERS O
  JOIN /*PREFIX*/ACTIONS A ON A.ACTION_ID=O.ACTION_ID
  JOIN /*PREFIX*/RATES R ON R.RATE_ID=O.RATE_ID
  JOIN /*PREFIX*/CAR_TYPES CT ON CT.CAR_TYPE_ID=O.CAR_TYPE_ID
  JOIN /*PERFIX*/ACCOUNTS A1 ON A1.ACCOUNT_ID=O.WHO_ACCEPT_ID
  JOIN /*PREFIX*/STREETS S1 ON S1.STREET_ID=O.STREET_ID
  JOIN /*PREFIX*/LOCALITIES L1 ON L1.LOCALITY_ID=S1.LOCALITY_ID
  LEFT JOIN /*PREFIX*/ZONES Z ON Z.ZONE_ID=O.ZONE_ID
  LEFT JOIN /*PERFIX*/ORDERS OP ON OP.ORDER_ID=O.PARENT_ID
  LEFT JOIN /*PERFIX*/FIRMS F ON F.FIRM_ID=O.FIRM_ID
  LEFT JOIN /*PERFIX*/CARS C ON C.CAR_ID=O.CAR_ID
  LEFT JOIN /*PERFIX*/ACCOUNTS A2 ON A2.ACCOUNT_ID=O.WHO_PROCESS_ID
  LEFT JOIN /*PERFIX*/ACCOUNTS A4 ON A4.ACCOUNT_ID=O.WHO_HISTORY_ID
  LEFT JOIN /*PERFIX*/RESULTS RT ON RT.RESULT_ID=O.RESULT_ID
  LEFT JOIN /*PERFIX*/PARKS P ON P.PARK_ID=O.PARK_ID
  LEFT JOIN /*PERFIX*/SOURCES S ON S.SOURCE_ID=O.SOURCE_ID
  LEFT JOIN /*PERFIX*/DISCOUNTS D ON D.DISCOUNT_ID=O.DISCOUNT_ID
  LEFT JOIN /*PERFIX*/DRIVERS DR ON DR.DRIVER_ID=O.DRIVER_ID
  LEFT JOIN /*PERFIX*/ACCOUNTS A3 ON A3.ACCOUNT_ID=DR.DRIVER_ID

--

/* Создание процедуры добавления заказа */

CREATE PROCEDURE /*PREFIX*/I_ORDER
(
  ORDER_ID VARCHAR(32),
  ACTION_ID VARCHAR(32),
  RATE_ID VARCHAR(32),
  CAR_TYPE_ID VARCHAR(32),
  WHO_ACCEPT_ID VARCHAR(32),
  STREET_ID VARCHAR(32),
  ZONE_ID VARCHAR(32),
  PARENT_ID VARCHAR(32),
  FIRM_ID VARCHAR(32),
  CAR_ID VARCHAR(32),
  WHO_PROCESS_ID VARCHAR(32),
  RESULT_ID VARCHAR(32),
  PARK_ID VARCHAR(32),
  SOURCE_ID VARCHAR(32),
  DISCOUNT_ID VARCHAR(32),
  DRIVER_ID VARCHAR(32),
  ORDER_NUM VARCHAR(10),
  PHONE VARCHAR(100),
  HOUSE VARCHAR(10),
  FLAT VARCHAR(10),
  PORCH VARCHAR(10),
  DATE_ACCEPT TIMESTAMP,
  DATE_ARRIVAL TIMESTAMP,
  DATE_BEGIN TIMESTAMP,
  DATE_END TIMESTAMP,
  CUSTOMER VARCHAR(250),
  DESCRIPTION VARCHAR(250),
  COST_RATE NUMERIC(15,2),
  COST_FACT NUMERIC(15,2),
  TYPE_ACCEPT INTEGER,
  TYPE_PROCESS INTEGER,
  DATE_HISTORY TIMESTAMP,
  WHO_HISTORY_ID VARCHAR(32),
  BEFORE_PERIOD INTEGER,
  FINISHED INTEGER
)
AS
BEGIN
  INSERT INTO /*PREFIX*/ORDERS (ORDER_ID,ACTION_ID,RATE_ID,CAR_TYPE_ID,WHO_ACCEPT_ID,
                                STREET_ID,ZONE_ID,PARENT_ID,
                                FIRM_ID,CAR_ID,WHO_PROCESS_ID,RESULT_ID,PARK_ID,
                                SOURCE_ID,DISCOUNT_ID,DRIVER_ID,ORDER_NUM,PHONE,
                                HOUSE,FLAT,PORCH,
                                DATE_ACCEPT,DATE_ARRIVAL,DATE_BEGIN,DATE_END,CUSTOMER,
                                DESCRIPTION,COST_RATE,COST_FACT,TYPE_ACCEPT,
                                TYPE_PROCESS,DATE_HISTORY,WHO_HISTORY_ID,BEFORE_PERIOD,
                                FINISHED)
       VALUES (:ORDER_ID,:ACTION_ID,:RATE_ID,:CAR_TYPE_ID,:WHO_ACCEPT_ID,
               :STREET_ID,:ZONE_ID,:PARENT_ID,
               :FIRM_ID,:CAR_ID,:WHO_PROCESS_ID,:RESULT_ID,:PARK_ID,
               :SOURCE_ID,:DISCOUNT_ID,:DRIVER_ID,:ORDER_NUM,:PHONE,
               :HOUSE,:FLAT,:PORCH,
               :DATE_ACCEPT,:DATE_ARRIVAL,:DATE_BEGIN,:DATE_END,:CUSTOMER,
               :DESCRIPTION,:COST_RATE,:COST_FACT,:TYPE_ACCEPT,
               :TYPE_PROCESS,:DATE_HISTORY,:WHO_HISTORY_ID,:BEFORE_PERIOD,
               :FINISHED);
END;

--

/* Создание процедуры изменения заказа */

CREATE PROCEDURE /*PREFIX*/U_ORDER
(
  ORDER_ID VARCHAR(32),
  ACTION_ID VARCHAR(32),
  RATE_ID VARCHAR(32),
  CAR_TYPE_ID VARCHAR(32),
  WHO_ACCEPT_ID VARCHAR(32),
  STREET_ID VARCHAR(32),
  ZONE_ID VARCHAR(32),
  PARENT_ID VARCHAR(32),
  FIRM_ID VARCHAR(32),
  CAR_ID VARCHAR(32),
  WHO_PROCESS_ID VARCHAR(32),
  RESULT_ID VARCHAR(32),
  PARK_ID VARCHAR(32),
  SOURCE_ID VARCHAR(32),
  DISCOUNT_ID VARCHAR(32),
  DRIVER_ID VARCHAR(32),
  ORDER_NUM VARCHAR(10),
  PHONE VARCHAR(100),
  HOUSE VARCHAR(10),
  FLAT VARCHAR(10),
  PORCH VARCHAR(10),
  DATE_ACCEPT TIMESTAMP,
  DATE_ARRIVAL TIMESTAMP,
  DATE_BEGIN TIMESTAMP,
  DATE_END TIMESTAMP,
  CUSTOMER VARCHAR(250),
  DESCRIPTION VARCHAR(250),
  COST_RATE NUMERIC(15,2),
  COST_FACT NUMERIC(15,2),
  TYPE_ACCEPT INTEGER,
  TYPE_PROCESS INTEGER,
  DATE_HISTORY TIMESTAMP,
  WHO_HISTORY_ID VARCHAR(32),
  BEFORE_PERIOD INTEGER,
  FINISHED INTEGER,
  OLD_ORDER_ID VARCHAR(32)
)
AS
BEGIN
  UPDATE /*PREFIX*/ORDERS
     SET ORDER_ID=:ORDER_ID,
         ACTION_ID=:ACTION_ID,
         RATE_ID=:RATE_ID,
         CAR_TYPE_ID=:CAR_TYPE_ID,
         WHO_ACCEPT_ID=:WHO_ACCEPT_ID,
         STREET_ID=:STREET_ID,
         ZONE_ID=:ZONE_ID,
         PARENT_ID=:PARENT_ID,
         FIRM_ID=:FIRM_ID,
         CAR_ID=:CAR_ID,
         WHO_PROCESS_ID=:WHO_PROCESS_ID,
         RESULT_ID=:RESULT_ID,
         PARK_ID=:PARK_ID,
         SOURCE_ID=:SOURCE_ID,
         DISCOUNT_ID=:DISCOUNT_ID,
         DRIVER_ID=:DRIVER_ID,
         ORDER_NUM=:ORDER_NUM,
         PHONE=:PHONE,
         HOUSE=:HOUSE,
         FLAT=:FLAT,
         PORCH=:PORCH,
         DATE_ACCEPT=:DATE_ACCEPT,
         DATE_ARRIVAL=:DATE_ARRIVAL,
         DATE_BEGIN=:DATE_BEGIN,
         DATE_END=:DATE_END,
         CUSTOMER=:CUSTOMER,
         DESCRIPTION=:DESCRIPTION,
         COST_RATE=:COST_RATE,
         COST_FACT=:COST_FACT,
         TYPE_ACCEPT=:TYPE_ACCEPT,
         TYPE_PROCESS=:TYPE_PROCESS,
         DATE_HISTORY=:DATE_HISTORY,
         WHO_HISTORY_ID=:WHO_HISTORY_ID,
         BEFORE_PERIOD=:BEFORE_PERIOD,
         FINISHED=:FINISHED
   WHERE ORDER_ID=:OLD_ORDER_ID;
END;

--

/* Создание процедуры удаления заказа */

CREATE PROCEDURE /*PREFIX*/D_ORDER
(
  OLD_ORDER_ID VARCHAR(32)
)
AS
BEGIN
  DELETE FROM /*PREFIX*/ORDERS 
        WHERE ORDER_ID=:OLD_ORDER_ID;
END;

--

/* Фиксация изменений */

COMMIT