/* Создание таблицы услуг заказов */

CREATE TABLE /*PREFIX*/ORDER_SERVICES
(
  ORDER_ID VARCHAR(32) NOT NULL,
  SERVICE_ID VARCHAR(32) NOT NULL,
  COST NUMERIC(15,2) NOT NULL,
  DESCRIPTION VARCHAR(250),
  AMOUNT INTEGER NOT NULL,
  PRIORITY INTEGER,
  PRIMARY KEY (ORDER_ID,SERVICE_ID),
  FOREIGN KEY (ORDER_ID) REFERENCES /*PREFIX*/ORDERS (ORDER_ID),
  FOREIGN KEY (SERVICE_ID) REFERENCES /*PREFIX*/SERVICES (SERVICE_ID)
)

--

/* Создание просмотра услуг заказов */

CREATE VIEW /*PREFIX*/S_ORDER_SERVICES
(
  ORDER_ID,
  SERVICE_ID,
  COST,
  DESCRIPTION,
  AMOUNT,
  PRIORITY,
  ORDER_NUM,
  DATE_ACCEPT,
  SERVICE_NAME
)
AS
SELECT OS.*,
       O.ORDER_NUM,
       O.DATE_ACCEPT,
       S.NAME AS SERVICE_NAME
  FROM /*PREFIX*/ORDER_SERVICES OS
  JOIN /*PREFIX*/ORDERS O ON O.ORDER_ID=OS.ORDER_ID
  JOIN /*PREFIX*/SERVICES S ON S.SERVICE_ID=OS.SERVICE_ID

--

/* Создание процедуры добавления услуги заказу */

CREATE PROCEDURE /*PREFIX*/I_ORDER_SERVICE
(
  ORDER_ID VARCHAR(32),
  SERVICE_ID VARCHAR(32),
  COST NUMERIC(15,2),
  DESCRIPTION VARCHAR(250),
  AMOUNT INTEGER,
  PRIORITY INTEGER
)
AS
BEGIN
  INSERT INTO /*PREFIX*/ORDER_SERVICES (ORDER_ID,SERVICE_ID,COST,
                                        DESCRIPTION,AMOUNT,PRIORITY)
       VALUES (:ORDER_ID,:SERVICE_ID,:COST,
               :DESCRIPTION,:AMOUNT,:PRIORITY);
END;

--

/* Создание процедуры изменения услуги у заказа */

CREATE PROCEDURE /*PREFIX*/U_ORDER_SERVICE
(
  ORDER_ID VARCHAR(32),
  SERVICE_ID VARCHAR(32),
  COST NUMERIC(15,2),
  DESCRIPTION VARCHAR(250),
  AMOUNT INTEGER,
  PRIORITY INTEGER,
  OLD_ORDER_ID VARCHAR(32),
  OLD_SERVICE_ID VARCHAR(32)
)
AS
BEGIN
  UPDATE /*PREFIX*/ORDER_SERVICES
     SET ORDER_ID=:ORDER_ID,
         SERVICE_ID=:SERVICE_ID,
         COST=:COST,
         DESCRIPTION=:DESCRIPTION,
         AMOUNT=:AMOUNT,
         PRIORITY=:PRIORITY
   WHERE ORDER_ID=:OLD_ORDER_ID
     AND SERVICE_ID=:OLD_SERVICE_ID;
END;

--

/* Создание процедуры удаления услуги у заказа */

CREATE PROCEDURE /*PREFIX*/D_ORDER_SERVICE
(
  OLD_ORDER_ID VARCHAR(32),
  OLD_SERVICE_ID VARCHAR(32)
)
AS
BEGIN
  DELETE FROM /*PREFIX*/ORDER_SERVICES 
        WHERE ORDER_ID=:OLD_ORDER_ID
          AND SERVICE_ID=:OLD_SERVICE_ID;
END;

--

/* Фиксация изменений */

COMMIT