/* Создание таблицы истории маршрутов */

CREATE TABLE /*PREFIX*/ROUTE_HISTORY
(
  PHONE VARCHAR(100) NOT NULL,
  STREET_ID VARCHAR(32) NOT NULL,
  HOUSE VARCHAR(10) NOT NULL,
  FLAT VARCHAR(10),
  PORCH VARCHAR(10),
  DESCRIPTION VARCHAR(250),
  CLIENT_ID VARCHAR(32),
  AMOUNT INTEGER NOT NULL,
  DATE_FIRST TIMESTAMP NOT NULL,
  DATE_LAST TIMESTAMP NOT NULL,
  PRIMARY KEY (PHONE,STREET_ID,HOUSE,FLAT),
  FOREIGN KEY (STREET_ID) REFERENCES /*PREFIX*/STREETS (STREET_ID),
  FOREIGN KEY (CLIENT_ID) REFERENCES /*PREFIX*/CLIENTS (CLIENT_ID)
)

--

/* Создание просмотра истории маршрутов */

CREATE VIEW /*PREFIX*/S_ROUTE_HISTORY
(
  PHONE,
  STREET_ID,
  HOUSE,
  FLAT,
  PORCH,
  DESCRIPTION,
  CLIENT_ID,
  AMOUNT,
  DATE_FIRST,
  DATE_LAST,
  STREET_NAME,
  STREET_PREFIX,
  LOCALITY_ID,
  LOCALITY_NAME,
  LOCALITY_PREFIX,
  CLIENT_USER_NAME,
  CLIENT_SURNAME,
  CLIENT_NAME,
  CLIENT_PATRONYMIC
)
AS
SELECT RS.*,
       S.NAME AS STREET_NAME,
       S.PREFIX AS STREET_PREFIX,
       L.LOCALITY_ID,
       L.NAME AS LOCALITY_NAME,
       L.PREFIX AS LOCALITY_PREFIX,
       A.USER_NAME AS CLIENT_USER_NAME,
       A.SURNAME AS CLIENT_SURNAME,
       A.NAME AS CLIENT_NAME,
       A.PATRONYMIC AS CLIENT_PATRONYMIC
  FROM /*PREFIX*/ROUTE_HISTORY RS
  JOIN /*PREFIX*/STREETS S ON S.STREET_ID=RS.STREET_ID
  JOIN /*PREFIX*/LOCALITIES L ON L.LOCALITY_ID=S.LOCALITY_ID
  LEFT JOIN /*PREFIX*/CLIENTS C ON C.CLIENT_ID=RS.CLIENT_ID
  LEFT JOIN /*PREFIX*/ACCOUNTS A ON A.ACCOUNT_ID=C.CLIENT_ID

--

/* Создание процедуры добавления истории маршрутов */

CREATE OR ALTER PROCEDURE /*PREFIX*/I_ROUTE_HISTORY
(
  PHONE VARCHAR(100),
  STREET_ID VARCHAR(32),
  HOUSE VARCHAR(10),
  FLAT VARCHAR(10),
  PORCH VARCHAR(10),
  DESCRIPTION VARCHAR(250),
  CLIENT_ID VARCHAR(32),
  AMOUNT INTEGER,
  DATE_FIRST TIMESTAMP,
  DATE_LAST TIMESTAMP
)
AS
BEGIN
  INSERT INTO /*PREFIX*/ROUTE_HISTORY (PHONE,STREET_ID,HOUSE,FLAT,PORCH,DESCRIPTION,CLIENT_ID,AMOUNT,DATE_FIRST,DATE_LAST)
                               VALUES (:PHONE,:STREET_ID,:HOUSE,:FLAT,:PORCH,:DESCRIPTION,:CLIENT_ID,:AMOUNT,:DATE_FIRST,:DATE_LAST);
END;

--

/* Создание процедуры изменения истории маршрутов */

CREATE OR ALTER PROCEDURE /*PREFIX*/U_ROUTE_HISTORY
(
  PHONE VARCHAR(100),
  STREET_ID VARCHAR(32),
  HOUSE VARCHAR(10),
  FLAT VARCHAR(10),
  PORCH VARCHAR(10),
  DESCRIPTION VARCHAR(250),
  CLIENT_ID VARCHAR(32),
  AMOUNT INTEGER,
  DATE_FIRST TIMESTAMP,
  DATE_LAST TIMESTAMP,
  OLD_PHONE VARCHAR(100),
  OLD_STREET_ID VARCHAR(32),
  OLD_HOUSE VARCHAR(10),
  OLD_FLAT VARCHAR(10)
)
AS
BEGIN
  UPDATE /*PREFIX*/ROUTE_HISTORY
     SET PHONE=:PHONE,
         STREET_ID=:STREET_ID,
         HOUSE=:HOUSE,
         FLAT=:FLAT,
         PORCH=:PORCH,
         DESCRIPTION=:DESCRIPTION,
         CLIENT_ID=:CLIENT_ID,
         AMOUNT=:AMOUNT,
         DATE_FIRST=:DATE_FIRST,
         DATE_LAST=:DATE_LAST
   WHERE PHONE=:OLD_PHONE
     AND STREET_ID=:OLD_STREET_ID
     AND HOUSE=:OLD_HOUSE
     AND FLAT=:OLD_FLAT;
END;

--

/* Создание процедуры удаления истории маршрутов */

CREATE OR ALTER PROCEDURE /*PREFIX*/D_ROUTE_HISTORY
(
  OLD_PHONE VARCHAR(100),
  OLD_STREET_ID VARCHAR(32),
  OLD_HOUSE VARCHAR(10),
  OLD_FLAT VARCHAR(10)
)
AS
BEGIN
  DELETE FROM /*PREFIX*/ROUTE_HISTORY 
        WHERE PHONE=:OLD_PHONE
          AND STREET_ID=:OLD_STREET_ID
          AND HOUSE=:OLD_HOUSE
          AND FLAT=:OLD_FLAT;
END;

--

/* Фиксация изменений */

COMMIT