/* Создание таблицы маршрутов */

CREATE TABLE /*PREFIX*/ROUTES
(
  ROUTE_ID VARCHAR(32) NOT NULL,
  ORDER_ID VARCHAR(32) NOT NULL,
  ZONE_ID VARCHAR(32),
  STREET_ID VARCHAR(32),
  HOUSE VARCHAR(10),
  FLAT VARCHAR(10),
  PORCH VARCHAR(10),
  DISTANCE NUMERIC(15,2),
  COST NUMERIC(15,2),
  PERIOD INTEGER,
  AMOUNT INTEGER,
  PRIORITY INTEGER,
  PRIMARY KEY (ROUTE_ID),
  FOREIGN KEY (ORDER_ID) REFERENCES /*PREFIX*/ORDERS (ORDER_ID),
  FOREIGN KEY (ZONE_ID) REFERENCES /*PREFIX*/ZONES (ZONE_ID),
  FOREIGN KEY (STREET_ID) REFERENCES /*PREFIX*/STREETS (STREET_ID)
)

--

/* Создание просмотра маршрутов */

CREATE VIEW /*PREFIX*/S_ROUTES
(
  ROUTE_ID,
  ORDER_ID,
  ZONE_ID,
  STREET_ID,
  HOUSE,
  FLAT,
  PORCH,
  DISTANCE,
  COST,
  PERIOD,
  AMOUNT,
  PRIORITY,
  ORDER_NUM,
  DATE_ACCEPT,
  ZONE_NAME,
  STREET_NAME,
  STREET_PREFIX,
  LOCALITY_ID,
  LOCALITY_NAME,
  LOCALITY_PREFIX
)
AS
SELECT R.*,
       O.ORDER_NUM,
       O.DATE_ACCEPT,
       Z.NAME AS ZONE_NAME,
       S1.NAME AS STREET_NAME,
       S1.PREFIX AS STREET_PREFIX,
       L1.LOCALITY_ID,
       L1.NAME AS LOCALITY_NAME,
       L1.PREFIX AS LOCALITY_PREFIX
  FROM /*PREFIX*/ROUTES R
  JOIN /*PREFIX*/ORDERS O ON O.ORDER_ID=R.ORDER_ID
  LEFT JOIN /*PREFIX*/ZONES Z ON Z.ZONE_ID=R.ZONE_ID
  LEFT JOIN /*PREFIX*/STREETS S1 ON S1.STREET_ID=R.STREET_ID
  LEFT JOIN /*PREFIX*/LOCALITIES L1 ON L1.LOCALITY_ID=S1.LOCALITY_ID

--

/* Создание процедуры добавления маршрута */

CREATE PROCEDURE /*PREFIX*/I_ROUTE
(
  ROUTE_ID VARCHAR(32),
  ORDER_ID VARCHAR(32),
  ZONE_ID VARCHAR(32),
  STREET_ID VARCHAR(32),
  HOUSE VARCHAR(10),
  FLAT VARCHAR(10),
  PORCH VARCHAR(10),
  DISTANCE NUMERIC(15,2),
  COST NUMERIC(15,2),
  PERIOD INTEGER,
  AMOUNT INTEGER,
  PRIORITY INTEGER
)
AS
BEGIN
  INSERT INTO /*PREFIX*/ROUTES (ROUTE_ID,ORDER_ID,ZONE_ID,STREET_ID,HOUSE,
                                FLAT,PORCH,DISTANCE,COST,PERIOD,AMOUNT,PRIORITY)
       VALUES (:ROUTE_ID,:ORDER_ID,:ZONE_ID,:STREET_ID,:HOUSE,
               :FLAT,:PORCH,:DISTANCE,:COST,:PERIOD,:AMOUNT,:PRIORITY);
END;

--

/* Создание процедуры изменения маршрута */

CREATE PROCEDURE /*PREFIX*/U_ROUTE
(
  ROUTE_ID VARCHAR(32),
  ORDER_ID VARCHAR(32),
  ZONE_ID VARCHAR(32),
  STREET_ID VARCHAR(32),
  HOUSE VARCHAR(10),
  FLAT VARCHAR(10),
  PORCH VARCHAR(10),
  DISTANCE NUMERIC(15,2),
  COST NUMERIC(15,2),
  PERIOD INTEGER,
  AMOUNT INTEGER,
  PRIORITY INTEGER,
  OLD_ROUTE_ID VARCHAR(32)
)
AS
BEGIN
  UPDATE /*PREFIX*/ROUTES
     SET ROUTE_ID=:ROUTE_ID,
         ORDER_ID=:ORDER_ID,
         ZONE_ID=:ZONE_ID,
         STREET_ID=:STREET_ID,
         HOUSE=:HOUSE,
         FLAT=:FLAT,
         PORCH=:PORCH,
         DISTANCE=:DISTANCE,
         COST=:COST,
         PERIOD=:PERIOD,
         AMOUNT=:AMOUNT,
         PRIORITY=:PRIORITY
   WHERE ROUTE_ID=:OLD_ROUTE_ID;
END;

--

/* Создание процедуры удаления маршрута */

CREATE PROCEDURE /*PREFIX*/D_ROUTE
(
  OLD_ROUTE_ID VARCHAR(32)
)
AS
BEGIN
  DELETE FROM /*PREFIX*/ROUTES 
        WHERE ROUTE_ID=:OLD_ROUTE_ID;
END;

--

/* Фиксация изменений */

COMMIT