/* Создание таблицы объектов карты */

CREATE TABLE /*PREFIX*/MAP_OBJECTS
(
  STREET_ID VARCHAR(32) NOT NULL,
  HOUSE VARCHAR(10) NOT NULL,
  LAT DOUBLE PRECISION NOT NULL,
  LON DOUBLE PRECISION NOT NULL,
  PRIMARY KEY (STREET_ID,HOUSE),
  FOREIGN KEY (STREET_ID) REFERENCES /*PREFIX*/STREETS (STREET_ID)
)

--

/* Создание просмотра объектов карты */

CREATE VIEW /*PREFIX*/S_MAP_OBJECTS
(
  STREET_ID,
  HOUSE,
  LAT,
  LON,
  STREET_NAME,
  STREET_PREFIX,
  LOCALITY_ID,
  LOCALITY_NAME,
  LOCALITY_PREFIX
)
AS
SELECT MO.*,
       S.NAME AS STREET_NAME,
       S.PREFIX AS STREET_PREFIX,
       L.LOCALITY_ID,
       L.NAME AS LOCALITY_NAME,
       L.PREFIX AS LOCALITY_PREFIX
  FROM /*PREFIX*/MAP_OBJECTS MO
  JOIN /*PREFIX*/STREETS S ON S.STREET_ID=MO.STREET_ID
  JOIN /*PREFIX*/LOCALITIES L ON L.LOCALITY_ID=S.LOCALITY_ID

--

/* Создание процедуры добавления объекта карты */

CREATE PROCEDURE /*PREFIX*/I_MAP_OBJECT
(
  STREET_ID VARCHAR(32),
  HOUSE VARCHAR(10),
  LAT DOUBLE PRECISION,
  LON DOUBLE PRECISION
)
AS
BEGIN
  INSERT INTO /*PREFIX*/MAP_OBJECTS (STREET_ID,HOUSE,LAT,LON)
       VALUES (:STREET_ID,:HOUSE,:LAT,:LON);
END;

--

/* Создание процедуры изменения объекта карты */

CREATE PROCEDURE /*PREFIX*/U_MAP_OBJECT
(
  STREET_ID VARCHAR(32),
  HOUSE VARCHAR(10),
  LAT DOUBLE PRECISION,
  LON DOUBLE PRECISION,
  OLD_STREET_ID VARCHAR(32),
  OLD_HOUSE VARCHAR(10)
)
AS
BEGIN
  UPDATE /*PREFIX*/MAP_OBJECTS
     SET STREET_ID=:STREET_ID,
         HOUSE=:HOUSE,
         LAT=:LAT,
         LON=:LON
   WHERE STREET_ID=:OLD_STREET_ID
     AND HOUSE=:OLD_HOUSE;
END;

--

/* Создание процедуры удаления объекта карты */

CREATE PROCEDURE /*PREFIX*/D_MAP_OBJECT
(
  OLD_STREET_ID VARCHAR(32),
  OLD_HOUSE VARCHAR(10)
)
AS
BEGIN
  DELETE FROM /*PREFIX*/MAP_OBJECTS 
        WHERE STREET_ID=:OLD_STREET_ID
          AND HOUSE=:OLD_HOUSE;
END;

--

/* Фиксация изменений */

COMMIT