/* Создание таблицы вызовов */

CREATE TABLE /*PREFIX*/CALLS
(
  CALL_ID VARCHAR(32) NOT NULL,
  LINE_ID VARCHAR(32) NOT NULL,
  TYPE_CALL INTEGER NOT NULL,
  CREATOR_ID VARCHAR(32) NOT NULL,
  DATE_CREATE TIMESTAMP NOT NULL,
  CALLER_ID VARCHAR(32),
  CALLER_CONTACT VARCHAR(100),
  ACCEPTOR_ID VARCHAR(32),
  ACCEPTOR_CONTACT VARCHAR(100),
  DATE_BEGIN TIMESTAMP,
  DATE_END TIMESTAMP,
  TYPE_END INTEGER,
  DATA BLOB,
  TYPE_DATA INTEGER,
  PLACE INTEGER,
  PRIMARY KEY (CALL_ID,LINE_ID),
  FOREIGN KEY (CREATOR_ID) REFERENCES /*PREFIX*/ACCOUNTS (ACCOUNT_ID),
  FOREIGN KEY (CALLER_ID) REFERENCES /*PREFIX*/ACCOUNTS (ACCOUNT_ID),
  FOREIGN KEY (ACCEPTOR_ID) REFERENCES /*PREFIX*/ACCOUNTS (ACCOUNT_ID)
)

--

/* Создание просмотра вызовов */

CREATE VIEW /*PREFIX*/S_CALLS
(
  CALL_ID,
  LINE_ID,
  TYPE_CALL,
  CREATOR_ID,
  DATE_CREATE,
  CALLER_ID,
  CALLER_CONTACT,
  ACCEPTOR_ID,
  ACCEPTOR_CONTACT,
  DATE_BEGIN,
  DATE_END,
  TYPE_END,
  DATA,
  TYPE_DATA,
  PLACE,
  CREATOR_NAME,
  CALLER_NAME,
  ACCEPTOR_NAME
)
AS
SELECT C.*,
       A1.USER_NAME AS CREATOR_NAME,
       A2.USER_NAME AS CALLER_NAME,
       A3.USER_NAME AS ACCEPTOR_NAME
  FROM /*PREFIX*/CALLS C
  JOIN /*PREFIX*/ACCOUNTS A1 ON A1.ACCOUNT_ID=C.CREATOR_ID
  LEFT JOIN /*PREFIX*/ACCOUNTS A2 ON A2.ACCOUNT_ID=C.CALLER_ID
  LEFT JOIN /*PREFIX*/ACCOUNTS A3 ON A3.ACCOUNT_ID=C.ACCEPTOR_ID

--

/* Создание процедуры добавления вызова */

CREATE OR ALTER PROCEDURE /*PREFIX*/I_CALL
(
  CALL_ID VARCHAR(32),
  LINE_ID VARCHAR(32),
  TYPE_CALL INTEGER,
  CREATOR_ID VARCHAR(32),
  DATE_CREATE TIMESTAMP,
  CALLER_ID VARCHAR(32),
  CALLER_CONTACT VARCHAR(100),
  ACCEPTOR_ID VARCHAR(32),
  ACCEPTOR_CONTACT VARCHAR(100),
  DATE_BEGIN TIMESTAMP,
  DATE_END TIMESTAMP,
  TYPE_END INTEGER,
  DATA BLOB,
  TYPE_DATA INTEGER,
  PLACE INTEGER
)
AS
BEGIN
  INSERT INTO /*PREFIX*/CALLS (CALL_ID,LINE_ID,TYPE_CALL,CREATOR_ID,DATE_CREATE,
                     CALLER_ID,CALLER_CONTACT,ACCEPTOR_ID,ACCEPTOR_CONTACT,
                     DATE_BEGIN,DATE_END,TYPE_END,DATA,TYPE_DATA,PLACE)
       VALUES (:CALL_ID,:LINE_ID,:TYPE_CALL,:CREATOR_ID,:DATE_CREATE,
               :CALLER_ID,:CALLER_CONTACT,:ACCEPTOR_ID,:ACCEPTOR_CONTACT,
               :DATE_BEGIN,:DATE_END,:TYPE_END,:DATA,:TYPE_DATA,:PLACE);
END

--

/* Создание процедуры изменения вызова */

CREATE OR ALTER PROCEDURE /*PREFIX*/U_CALL
(
  CALL_ID VARCHAR(32),
  LINE_ID VARCHAR(32),
  TYPE_CALL INTEGER,
  CREATOR_ID VARCHAR(32),
  DATE_CREATE TIMESTAMP,
  CALLER_ID VARCHAR(32),
  CALLER_CONTACT VARCHAR(100),
  ACCEPTOR_ID VARCHAR(32),
  ACCEPTOR_CONTACT VARCHAR(100),
  DATE_BEGIN TIMESTAMP,
  DATE_END TIMESTAMP,
  TYPE_END INTEGER,
  DATA BLOB,
  TYPE_DATA INTEGER,
  PLACE INTEGER,
  OLD_CALL_ID VARCHAR(32),
  OLD_LINE_ID VARCHAR(32)
)
AS
BEGIN
  UPDATE /*PREFIX*/CALLS
     SET CALL_ID=:CALL_ID,
         LINE_ID=:LINE_ID,
         TYPE_CALL=:TYPE_CALL,
         CREATOR_ID=:CREATOR_ID,
         DATE_CREATE=:DATE_CREATE,
         CALLER_ID=:CALLER_ID,
         CALLER_CONTACT=:CALLER_CONTACT,
         ACCEPTOR_ID=:ACCEPTOR_ID,
         ACCEPTOR_CONTACT=:ACCEPTOR_CONTACT,
         DATE_BEGIN=:DATE_BEGIN,
         DATE_END=:DATE_END,
         TYPE_END=:TYPE_END,
         DATA=:DATA,
         TYPE_DATA=:TYPE_DATA,
         PLACE=:PLACE
   WHERE CALL_ID=:OLD_CALL_ID
     AND LINE_ID=:OLD_LINE_ID;
END

--

/* Создание процедуры удаления вызова */

CREATE OR ALTER PROCEDURE /*PREFIX*/D_CALL
(
  OLD_CALL_ID VARCHAR(32),
  OLD_LINE_ID VARCHAR(32)
)
AS
BEGIN
  DELETE FROM /*PREFIX*/CALLS
        WHERE CALL_ID=:OLD_CALL_ID
          AND LINE_ID=:OLD_LINE_ID;
END;

--

/* Фиксация изменений */

COMMIT