/* Изменение процедуры удаления заказа */

CREATE OR ALTER PROCEDURE /*PREFIX*/D_ORDER
(
  OLD_ORDER_ID VARCHAR(32)
)
AS
BEGIN
  DELETE FROM /*PREFIX*/IN_MESSAGES
        WHERE ORDER_ID IN (SELECT ORDER_ID FROM /*PREFIX*/ORDERS
                            WHERE PARENT_ID=:OLD_ORDER_ID);

  DELETE FROM /*PREFIX*/OUT_MESSAGES
        WHERE ORDER_ID IN (SELECT ORDER_ID FROM /*PREFIX*/ORDERS
                            WHERE PARENT_ID=:OLD_ORDER_ID);

  DELETE FROM /*PREFIX*/ROUTES
        WHERE ORDER_ID IN (SELECT ORDER_ID FROM /*PREFIX*/ORDERS
                            WHERE PARENT_ID=:OLD_ORDER_ID);

  DELETE FROM /*PREFIX*/ORDER_SERVICES
        WHERE ORDER_ID IN (SELECT ORDER_ID FROM /*PREFIX*/ORDERS
                            WHERE PARENT_ID=:OLD_ORDER_ID);

  DELETE FROM /*PREFIX*/ORDERS 
        WHERE PARENT_ID=:OLD_ORDER_ID;

  DELETE FROM /*PREFIX*/IN_MESSAGES
        WHERE ORDER_ID=:OLD_ORDER_ID;

  DELETE FROM /*PREFIX*/OUT_MESSAGES
        WHERE ORDER_ID=:OLD_ORDER_ID;

  DELETE FROM /*PREFIX*/ROUTES
        WHERE ORDER_ID=:OLD_ORDER_ID;

  DELETE FROM /*PREFIX*/ORDER_SERVICES
        WHERE ORDER_ID=:OLD_ORDER_ID;

  DELETE FROM /*PREFIX*/ORDERS 
        WHERE ORDER_ID=:OLD_ORDER_ID;
END;

--

/* Фиксация изменений */

COMMIT