/* Создание просмотра водителей на сменах */

CREATE VIEW /*PREFIX*/S_DRIVER_SHIFTS
(
  SHIFT_ID,
  DRIVER_ID,
  DATE_BEGIN,
  DATE_END,
  DRIVER_NAME,
  CAR_ID,
  MIN_BALANCE,
  CAR_COLOR,
  CAR_BRAND,
  CAR_STATE_NUM,
  CAR_CALLSIGN,
  CAR_TYPE_ID,
  CAR_TYPE_NAME,
  CAR_TYPE_FONT_COLOR,
  CAR_TYPE_BRUSH_COLOR,
  PARK_ID,
  PARK_NAME,
  PARK_DESCRIPTION,
  SUM_CHARGE,
  SUM_RECEIPT,
  ACTUAL_BALANCE
)
AS
SELECT S.*,
       A.USER_NAME AS DRIVER_NAME,
       D.CAR_ID,
       D.MIN_BALANCE,
       C.COLOR AS CAR_COLOR,
       C.BRAND AS CAR_BRAND,
       C.STATE_NUM AS CAR_STATE_NUM,
       C.CALLSIGN AS CAR_CALLSIGN,
       C.CAR_TYPE_ID,
       CT.NAME AS CAR_TYPE_NAME,
       CT.FONT_COLOR AS CAR_TYPE_FONT_COLOR,
       CT.BRUSH_COLOR AS CAR_TYPE_BRUSH_COLOR,
       P.PARK_ID,
       P.NAME AS PARK_NAME,
       P.DESCRIPTION AS PARK_DESCRIPTION,
       (CASE WHEN SAC.SUM_CHARGE IS NULL THEN 0.0 ELSE SAC.SUM_CHARGE END) SUM_CHARGE,
       (CASE WHEN SAR.SUM_RECEIPT IS NULL THEN 0.0 ELSE SAR.SUM_RECEIPT END) SUM_RECEIPT,
       ((CASE WHEN SAR.SUM_RECEIPT IS NULL THEN 0.0 ELSE SAR.SUM_RECEIPT END)-
        (CASE WHEN SAC.SUM_CHARGE IS NULL THEN 0.0 ELSE SAC.SUM_CHARGE END)) AS BALANCE
  FROM /*PREFIX*/SHIFTS S
  JOIN /*PREFIX*/ACCOUNTS A ON A.ACCOUNT_ID=S.ACCOUNT_ID
  JOIN /*PREFIX*/DRIVERS D ON D.DRIVER_ID=S.ACCOUNT_ID
  JOIN /*PREFIX*/CARS C ON C.CAR_ID=D.CAR_ID
  JOIN /*PREFIX*/CAR_TYPES CT ON CT.CAR_TYPE_ID=C.CAR_TYPE_ID
  LEFT JOIN /*PREFIX*/PARK_STATES PS ON PS.DRIVER_ID=D.DRIVER_ID AND PS.DATE_OUT IS NULL
  LEFT JOIN /*PREFIX*/PARKS P ON P.PARK_ID=PS.PARK_ID
  LEFT JOIN /*PREFIX*/S_ACCOUNT_CHARGES SAC ON SAC.ACCOUNT_ID=S.ACCOUNT_ID
  LEFT JOIN /*PREFIX*/S_ACCOUNT_RECEIPTS SAR ON SAR.ACCOUNT_ID=S.ACCOUNT_ID

--

/* Фиксация изменений */

COMMIT