/* Создание процедуры открытия смены водителя */

CREATE PROCEDURE /*PREFIX*/I_DRIVER_SHIFT
(
  SHIFT_ID VARCHAR(32),
  DRIVER_ID VARCHAR(32),
  PARK_ID VARCHAR(32),
  DATE_BEGIN TIMESTAMP
)
AS
BEGIN
  INSERT INTO /*PREFIX*/SHIFTS (SHIFT_ID,ACCOUNT_ID,DATE_BEGIN)
       VALUES (:SHIFT_ID,:DRIVER_ID,:DATE_BEGIN);

  IF (PARK_ID IS NOT NULL) THEN BEGIN

    UPDATE /*PREFIX*/PARK_STATES
       SET DATE_OUT=CURRENT_TIMESTAMP
     WHERE DRIVER_ID=:DRIVER_ID;

    INSERT INTO /*PREFIX*/PARK_STATES(PARK_STATE_ID,DRIVER_ID,PARK_ID,DATE_IN)
           VALUES (/*PREFIX*/GET_UNIQUE_ID(),:DRIVER_ID,:PARK_ID,CURRENT_TIMESTAMP);

  END

END;

--

/* Фиксация изменений */

COMMIT