/* Создание процедуры постановки водителя на стоянку */

CREATE PROCEDURE /*PREFIX*/I_DRIVER_PARK
(
  DRIVER_ID VARCHAR(32),
  PARK_ID VARCHAR(32),
  DATE_IN TIMESTAMP
)
AS
BEGIN
  INSERT INTO /*PREFIX*/PARK_STATES(PARK_STATE_ID,DRIVER_ID,PARK_ID,DATE_IN)
        VALUES (/*PREFIX*/GET_UNIQUE_ID(),:DRIVER_ID,:PARK_ID,CURRENT_TIMESTAMP);
END;

--

/* Фиксация изменений */

COMMIT