/* Создание просмотра водителей на стоянках */

CREATE VIEW /*PREFIX*/S_DRIVER_PARKS
(
    PARK_STATE_ID,
    DRIVER_ID,
    PARK_ID,
    DATE_IN,
    DATE_OUT,
    DRIVER_NAME,
    CAR_ID,
    MIN_BALANCE,
    CAR_COLOR,
    CAR_BRAND,
    CAR_STATE_NUM,
    CAR_CALLSIGN,
    CAR_TYPE_ID,
    CAR_TYPE_NAME,
    CAR_TYPE_FONT_COLOR,
    CAR_TYPE_BRUSH_COLOR,
    PARK_NAME,
    SUM_CHARGE,
    SUM_RECEIPT,
    ACTUAL_BALANCE
)
AS
SELECT PS.*,
       A.USER_NAME AS DRIVER_NAME,
       D.CAR_ID,
       D.MIN_BALANCE,
       C.COLOR AS CAR_COLOR,
       C.BRAND AS CAR_BRAND,
       C.STATE_NUM AS CAR_STATE_NUM,
       C.CALLSIGN AS CAR_CALLSIGN,
       C.CAR_TYPE_ID,
       CT.NAME AS CAR_TYPE_NAME,
       CT.FONT_COLOR AS CAR_TYPE_FONT_COLOR,
       CT.BRUSH_COLOR AS CAR_TYPE_BRUSH_COLOR,
       P.NAME AS PARK_NAME,
       (CASE WHEN SAC.SUM_CHARGE IS NULL THEN 0.0 ELSE SAC.SUM_CHARGE END) SUM_CHARGE,
       (CASE WHEN SAR.SUM_RECEIPT IS NULL THEN 0.0 ELSE SAR.SUM_RECEIPT END) SUM_RECEIPT,
       ((CASE WHEN SAR.SUM_RECEIPT IS NULL THEN 0.0 ELSE SAR.SUM_RECEIPT END)-
        (CASE WHEN SAC.SUM_CHARGE IS NULL THEN 0.0 ELSE SAC.SUM_CHARGE END)) AS ACTUAL_BALANCE
  FROM /*PREFIX*/PARK_STATES PS
  JOIN /*PREFIX*/PARKS P ON P.PARK_ID=PS.PARK_ID
  JOIN /*PREFIX*/ACCOUNTS A ON A.ACCOUNT_ID=PS.DRIVER_ID
  JOIN /*PREFIX*/DRIVERS D ON D.DRIVER_ID=PS.DRIVER_ID
  JOIN /*PREFIX*/CARS C ON C.CAR_ID=D.CAR_ID
  JOIN /*PREFIX*/CAR_TYPES CT ON CT.CAR_TYPE_ID=C.CAR_TYPE_ID
  LEFT JOIN /*PREFIX*/S_ACCOUNT_CHARGES SAC ON SAC.ACCOUNT_ID=PS.DRIVER_ID
  LEFT JOIN /*PREFIX*/S_ACCOUNT_RECEIPTS SAR ON SAR.ACCOUNT_ID=PS.DRIVER_ID

--

/* Фиксация изменений */

COMMIT