/* Создание процедуры расчета стоимости по карте */

CREATE PROCEDURE /*PREFIX*/GET_COST_MAP
(
  ORDER_ID VARCHAR(32),
  STREET_ID VARCHAR(32),
  ZONE_ID VARCHAR(32),
  CAR_ID VARCHAR(32),
  RATE_ID VARCHAR(32),
  CAR_TYPE_ID VARCHAR(32),
  FIRM_ID VARCHAR(32),
  PARK_ID VARCHAR(32),
  DRIVER_ID VARCHAR(32),
  SOURCE_ID VARCHAR(32),
  DISCOUNT_ID VARCHAR(32),
  HOUSE VARCHAR(10),
  FLAT VARCHAR(10),
  PORCH VARCHAR(10),
  PHONE VARCHAR(100),
  CUSTOMER VARCHAR(250),
  ORDER_NUM VARCHAR(10),
  BASE_COST NUMERIC(15,2),
  BASE_DISTANCE NUMERIC(15,2),
  BASE_PERIOD INTEGER
)
RETURNS
(
  COST NUMERIC(15,2)
)
AS
BEGIN
  COST=BASE_COST*BASE_DISTANCE;

  IF (COST IS NOT NULL) THEN BEGIN

    IF (COST<100.0) THEN BEGIN

      COST=100.0;

    END ELSE BEGIN

      IF (BASE_DISTANCE>10.0) THEN BEGIN

        COST=COST*0.9;

      END

    END

  END

  IF (COST IS NOT NULL) THEN BEGIN

    COST=CAST(CAST((COST/10) AS NUMERIC(15,1)) AS NUMERIC(15,0))*10;

  END

END


--

/* Фиксация изменений */

COMMIT