/* Создание процедуры определения действия по умолчанию */

CREATE PROCEDURE /*PREFIX*/GET_DEFAULT_ACTION_ID
(
  ORDER_ID VARCHAR(32)
)
RETURNS
(
  ACTION_ID VARCHAR(32)
)
AS
  DECLARE PROC_DETECT VARCHAR(100);
  DECLARE SQL VARCHAR(1000);
  DECLARE DETECTED INTEGER;
  DECLARE AACTION_ID VARCHAR(32);
BEGIN
  ACTION_ID=NULL;

  FOR SELECT ACTION_ID, PROC_DETECT
        FROM /*PREFIX*/ACTIONS
       WHERE PROC_DETECT IS NOT NULL
       ORDER BY PRIORITY
        INTO :AACTION_ID,:PROC_DETECT DO BEGIN

    IF (TRIM(PROC_DETECT)<>'') THEN BEGIN
      DETECTED=0;
      SQL='SELECT DETECTED FROM '||PROC_DETECT||'('''||ORDER_ID||''');';
      EXECUTE STATEMENT SQL INTO :DETECTED;

      IF (DETECTED=1) THEN BEGIN
        ACTION_ID=AACTION_ID;
        BREAK;
      END
    END

  END
END

--

/* Фиксация изменений */

COMMIT