/* Создание процедуры блокировки заказов */

CREATE PROCEDURE /*PREFIX*/LOCK_ORDERS
(
  ACCOUNT_ID VARCHAR(32)
)
RETURNS
(
 LOCK_COUNT INTEGER
)
AS
  DECLARE FLAG INTEGER;
  DECLARE ORDER_ID VARCHAR(32);
BEGIN
  LOCK_COUNT=0;

  FOR SELECT ORDER_ID
        FROM /*PREFIX*/ORDERS
       WHERE PARENT_ID IS NULL
         AND DATE_HISTORY IS NULL
         AND WHO_HISTORY_ID IS NULL
--         AND RESULT_ID IS NULL
--         AND WHO_PROCESS_ID IS NULL
--         AND DATE_BEGIN IS NULL
         AND TYPE_PROCESS=0
         AND FINISHED<>1
         AND DATE_ARRIVAL+(BEFORE_PERIOD*(1e0/24/60))>=CURRENT_TIMESTAMP
       ORDER BY DATE_ARRIVAL
        INTO :ORDER_ID DO BEGIN

    UPDATE /*PREFIX*/ORDERS
       SET /*DATE_BEGIN=CURRENT_TIMESTAMP,*/
           WHO_PROCESS_ID=:ACCOUNT_ID
     WHERE ORDER_ID=:ORDER_ID;

    LOCK_COUNT=LOCK_COUNT+1;
  END

END

--

/* Фиксация изменений */

COMMIT