/* Создание процедуры определения результата нет водителя */

CREATE PROCEDURE /*PREFIX*/DR_NO_DRIVER
(
  ORDER_ID VARCHAR(32),
  ACTION_ID VARCHAR(32),
  RESULT_ID VARCHAR(32)
)
RETURNS
(
  DETECTED INTEGER
)
AS
  DECLARE CNT INTEGER;
  DECLARE DRIVER_ID VARCHAR(32);
BEGIN
  DETECTED=0;

   SELECT DRIVER_ID
     FROM /*PREFIX*/ORDERS
    WHERE ORDER_ID=:ORDER_ID
     INTO :DRIVER_ID;

  IF (DRIVER_ID IS NULL) THEN
    DETECTED=1;

  SUSPEND;
END

--

/* Фиксация изменений */

COMMIT