/* Создание процедуры определения результата нет доступных стоянок */

CREATE PROCEDURE /*PREFIX*/DR_NO_PARK
(
  ORDER_ID VARCHAR(32),
  ACTION_ID VARCHAR(32),
  RESULT_ID VARCHAR(32)
)
RETURNS
(
  DETECTED INTEGER
)
AS
  DECLARE CNT INTEGER;
  DECLARE PARK_ID VARCHAR(32);
  DECLARE DRIVER_ID VARCHAR(32);
BEGIN
  DETECTED=0;

   SELECT PARK_ID, DRIVER_ID
     FROM /*PREFIX*/ORDERS
    WHERE ORDER_ID=:ORDER_ID
     INTO :PARK_ID, :DRIVER_ID;

  IF ((PARK_ID IS NULL) AND (DRIVER_ID IS NULL)) THEN
    DETECTED=1;

  SUSPEND;
END

--

/* Фиксация изменений */

COMMIT