/* Создание процедуры определения результата заказ отправлен */

CREATE PROCEDURE /*PREFIX*/DR_SEND_ORDER
(
  ORDER_ID VARCHAR(32),
  ACTION_ID VARCHAR(32),
  RESULT_ID VARCHAR(32)
)
RETURNS
(
  DETECTED INTEGER
)
AS
  DECLARE CNT INTEGER;
  DECLARE DRIVER_ID VARCHAR(32);
  DECLARE DATE_BEGIN TIMESTAMP;
BEGIN
  DETECTED=0;

  SELECT DRIVER_ID, DATE_BEGIN
    FROM /*PREFIX*/ORDERS
   WHERE ORDER_ID=:ORDER_ID
    INTO :DRIVER_ID, :DATE_BEGIN;

  IF (DRIVER_ID IS NOT NULL) THEN BEGIN

    SELECT COUNT(*)
      FROM /*PREFIX*/OUT_MESSAGES
     WHERE RECIPIENT_ID=:DRIVER_ID
       AND DESCRIPTION=:ORDER_ID||:ACTION_ID
       AND TYPE_MESSAGE=0
       AND DATE_OUT IS NOT NULL
       AND DATE_CREATE>=:DATE_BEGIN
      INTO CNT;

    IF (CNT>0) THEN
      DETECTED=1;

  END

  SUSPEND;
END

--

/* Фиксация изменений */

COMMIT