/* Создание процедуры определения результата время истекло */

CREATE PROCEDURE /*PREFIX*/DR_TIME_OUT
(
  ORDER_ID VARCHAR(32),
  ACTION_ID VARCHAR(32),
  RESULT_ID VARCHAR(32)
)
RETURNS
(
  DETECTED INTEGER
)
AS
  DECLARE CNT INTEGER;
  DECLARE PERIOD INTEGER;
  DECLARE DATE_BEGIN TIMESTAMP;
BEGIN
  DETECTED=0;

   SELECT PERIOD
     FROM /*PREFIX*/ACTIONS
    WHERE ACTION_ID=:ACTION_ID
     INTO :PERIOD;

  IF (PERIOD IS NOT NULL) THEN BEGIN

    SELECT DATE_BEGIN
      FROM /*PREFIX*/ORDERS
     WHERE ORDER_ID=:ORDER_ID
      INTO :DATE_BEGIN;

    IF (DATE_BEGIN IS NOT NULL) THEN BEGIN

      IF ((DATE_BEGIN+(PERIOD*(1e0/24/60/60)))<=CURRENT_TIMESTAMP) THEN
        DETECTED=1;

    END

  END

  SUSPEND;
END


--

/* Фиксация изменений */

COMMIT