/* Создание процедуры определения результата водитель выбран */

CREATE PROCEDURE /*PREFIX*/DR_SELECT_DRIVER
(
  ORDER_ID VARCHAR(32),
  ACTION_ID VARCHAR(32),
  RESULT_ID VARCHAR(32)
)
RETURNS
(
  DETECTED INTEGER
)
AS
  DECLARE DRIVER_ID VARCHAR(32);
BEGIN
  DETECTED=0;

  SELECT DRIVER_ID
    FROM /*PREFIX*/ORDERS
   WHERE ORDER_ID=:ORDER_ID
    INTO :DRIVER_ID;

  IF (DRIVER_ID IS NOT NULL) THEN
    DETECTED=1;

  SUSPEND;
END

--

/* Фиксация изменений */

COMMIT