/* Создание процедуры определения результата частичный расчет */

CREATE PROCEDURE /*PREFIX*/DR_PARTLY_CALC
(
  ORDER_ID VARCHAR(32),
  ACTION_ID VARCHAR(32),
  RESULT_ID VARCHAR(32)
)
RETURNS
(
  DETECTED INTEGER
)
AS
  DECLARE CNT INTEGER;
  DECLARE DRIVER_ID VARCHAR(32);
  DECLARE DATE_BEGIN TIMESTAMP;
BEGIN
  DETECTED=0;

  SELECT DRIVER_ID, DATE_BEGIN
    FROM /*PREFIX*/ORDERS
   WHERE ORDER_ID=:ORDER_ID
    INTO :DRIVER_ID, :DATE_BEGIN;

  IF (DRIVER_ID IS NOT NULL) THEN BEGIN

    SELECT COUNT(*)
      FROM /*PREFIX*/IN_MESSAGES
     WHERE SENDER_ID=:DRIVER_ID
       AND CODE_MESSAGE_ID='E0D06394F6BC81BA481D1F94D12B3FB4' /* Клиент отказался платить */
       AND TYPE_MESSAGE=0
       AND DATE_IN>:DATE_BEGIN
      INTO CNT;

    IF (CNT>0) THEN
      DETECTED=1;

  END

  SUSPEND;
END

--

/* Фиксация изменений */

COMMIT