/* Создание процедуры обработки результата нет водителя */

CREATE PROCEDURE /*PREFIX*/PR_NO_DRIVER
(
  ORDER_ID VARCHAR(32),
  ACCOUNT_ID VARCHAR(32)
)
AS
  DECLARE PARK_ID VARCHAR(32);
  DECLARE DRIVER_ID VARCHAR(32);
BEGIN

  SELECT PARK_ID, DRIVER_ID
    FROM /*PREFIX*/ORDERS
   WHERE ORDER_ID=:ORDER_ID
     INTO :PARK_ID, :DRIVER_ID;

  IF (DRIVER_ID IS NULL) THEN BEGIN

    IF (PARK_ID IS NOT NULL) THEN BEGIN

      FOR SELECT DRIVER_ID
            FROM /*PREFIX*/PARK_STATES
           WHERE PARK_ID=:PARK_ID
             AND DATE_OUT IS NULL
           ORDER BY DATE_IN
            INTO :DRIVER_ID DO BEGIN
        BREAK;
      END

      IF (DRIVER_ID IS NOT NULL) THEN BEGIN

        UPDATE /*PREFIX*/ORDERS
           SET DRIVER_ID=:DRIVER_ID,
               DATE_END=CURRENT_TIMESTAMP,
               WHO_PROCESS_ID=:ACCOUNT_ID
         WHERE ORDER_ID=:ORDER_ID;

      END ELSE BEGIN

        EXECUTE PROCEDURE PR_MANUAL(ORDER_ID,ACCOUNT_ID);

      END

    END ELSE BEGIN

      EXECUTE PROCEDURE PR_MANUAL(ORDER_ID,ACCOUNT_ID);

    END

  END

END

--

/* Фиксация изменений */

COMMIT