/* Создание процедуры обработки результата водитель отказался */

CREATE PROCEDURE /*PREFIX*/PR_REFUSE_DRIVER
(
  ORDER_ID VARCHAR(32),
  ACCOUNT_ID VARCHAR(32)
)
AS
  DECLARE DRIVER_ID VARCHAR(32);
  DECLARE PHONE VARCHAR(100);
  DECLARE S VARCHAR(1000);
BEGIN

  SELECT DRIVER_ID
    FROM /*PREFIX*/ORDERS
   WHERE ORDER_ID=:ORDER_ID
    INTO :DRIVER_ID;

  UPDATE /*PREFIX*/ORDERS
     SET DATE_BEGIN=CURRENT_TIMESTAMP,
         DRIVER_ID=NULL
   WHERE ORDER_ID=:ORDER_ID;

  IF (DRIVER_ID IS NOT NULL) THEN BEGIN

    UPDATE /*PREFIX*/PARK_STATES
       SET DATE_OUT=CURRENT_TIMESTAMP
     WHERE DATE_OUT IS NULL
       AND DRIVER_ID=:DRIVER_ID;

    SELECT PHONE
      FROM /*PREFIX*/ACCOUNTS
     WHERE ACCOUNT_ID=:DRIVER_ID
      INTO :PHONE;

    S='Отказ от заказа. Вы сняты со стоянки';

    INSERT INTO /*PREFIX*/OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                        TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,PRIORITY,LOCKED)
                                VALUES (/*PREFIX*/GET_UNIQUE_ID(),:ACCOUNT_ID,:DRIVER_ID,CURRENT_TIMESTAMP,
                                        :S,NULL,0,:PHONE,NULL,2,NULL);

  END

END

--

/* Фиксация изменений */

COMMIT