/* Создание процедуры обработки результата подтверждение заказа */

CREATE PROCEDURE /*PREFIX*/PR_CONFIRM_ORDER
(
  ORDER_ID VARCHAR(32),
  ACCOUNT_ID VARCHAR(32)
)
AS
  DECLARE PHONE VARCHAR(100);
  DECLARE DRIVER_ID VARCHAR(32);
  DECLARE PARK_ID VARCHAR(32);
  DECLARE RECIPIENT_ID VARCHAR(32);
  DECLARE S VARCHAR(1000);
BEGIN

  SELECT PHONE, DRIVER_ID, PARK_ID
    FROM /*PREFIX*/ORDERS
   WHERE ORDER_ID=:ORDER_ID
    INTO :PHONE, :DRIVER_ID, :PARK_ID;

  UPDATE /*PREFIX*/ORDERS
     SET DATE_BEGIN=CURRENT_TIMESTAMP
   WHERE ORDER_ID=:ORDER_ID;

  IF ((PHONE IS NOT NULL) AND (DRIVER_ID IS NOT NULL)) THEN BEGIN

    UPDATE /*PREFIX*/PARK_STATES
       SET DATE_OUT=CURRENT_TIMESTAMP
     WHERE DRIVER_ID=:DRIVER_ID
       AND PARK_ID=:PARK_ID
       AND DATE_OUT IS NULL;

    IF (SUBSTR(PHONE,1,3)='+79')  THEN BEGIN

      RECIPIENT_ID=NULL;

      FOR SELECT ACCOUNT_ID
            FROM /*PREFIX*/ACCOUNTS
           WHERE PHONE=:PHONE
            INTO :RECIPIENT_ID DO BEGIN

        IF (RECIPIENT_ID IS NOT NULL) THEN
          BREAK;
      END

      S='Такси выехало';

      INSERT INTO /*PREFIX*/OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                          TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,PRIORITY,LOCKED)
                                  VALUES (/*PREFIX*/GET_UNIQUE_ID(),:ACCOUNT_ID,:RECIPIENT_ID,CURRENT_TIMESTAMP,
                                          :S,NULL,0,:PHONE,NULL,2,NULL);
    END

  END

END

--

/* Фиксация изменений */

COMMIT