/* Создание процедуры обработки результата клиент отказался */

CREATE PROCEDURE /*PREFIX*/PR_REFUSE_CLIENT
(
  ORDER_ID VARCHAR(32),
  ACCOUNT_ID VARCHAR(32)
)
AS
  DECLARE DRIVER_ID VARCHAR(32);
  DECLARE PARK_ID VARCHAR(32);
  DECLARE PARK_NAME VARCHAR(100);
  DECLARE PHONE VARCHAR(100);
  DECLARE PARK_STATE_ID VARCHAR(32);
  DECLARE DATE_IN TIMESTAMP;
  DECLARE S VARCHAR(1000);
BEGIN

  SELECT DRIVER_ID, PARK_ID
    FROM /*PREFIX*/ORDERS
   WHERE ORDER_ID=:ORDER_ID
    INTO :DRIVER_ID, :PARK_ID;

  UPDATE /*PREFIX*/ORDERS
     SET DATE_BEGIN=CURRENT_TIMESTAMP,
         TYPE_PROCESS=0
   WHERE ORDER_ID=:ORDER_ID;

  IF ((DRIVER_ID IS NOT NULL) AND (PARK_ID IS NOT NULL)) THEN BEGIN

    SELECT PHONE
      FROM /*PREFIX*/ACCOUNTS
     WHERE ACCOUNT_ID=:DRIVER_ID
      INTO :PHONE; 

    FOR SELECT PS.PARK_STATE_ID, P.NAME, PS.DATE_IN
          FROM /*PREFIX*/PARK_STATES PS
          JOIN /*PREFIX*/PARKS P ON P.PARK_ID=PS.PARK_ID
         WHERE PS.PARK_ID=:PARK_ID
           AND PS.DATE_OUT IS NULL
         ORDER BY PS.DATE_IN
          INTO :PARK_STATE_ID, :PARK_NAME, :DATE_IN DO BEGIN

      DATE_IN=DATE_IN-2*(1e0/24/60/60);

      INSERT INTO /*PREFIX*/PARK_STATES (PARK_STATE_ID,DRIVER_ID,PARK_ID,DATE_IN,DATE_OUT)
                                 VALUES (GET_UNIQUE_ID(),:DRIVER_ID,:PARK_ID,:DATE_IN,NULL);

      BREAK;
    END

    S='Отказ по заказу. Вы поставлены 1 на стоянку '||PARK_NAME;

    INSERT INTO /*PREFIX*/OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                        TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,PRIORITY,LOCKED)
                                VALUES (/*PREFIX*/GET_UNIQUE_ID(),:ACCOUNT_ID,:DRIVER_ID,CURRENT_TIMESTAMP,
                                        :S,NULL,0,:PHONE,NULL,0,NULL);

  END

END

--

/* Фиксация изменений */

COMMIT