/* Создание процедуры выполнения тестового кода */

CREATE PROCEDURE /*PREFIX*/CODE_TEST
(
  ACCOUNT_ID VARCHAR(32),
  IN_MESSAGE_ID VARCHAR(32)
)
AS
  DECLARE CONTACT VARCHAR(100);
  DECLARE CODE VARCHAR(100);
BEGIN
  SELECT IM.CONTACT, CM.CODE
    FROM /*PREFIX*/IN_MESSAGES IM
    LEFT JOIN /*PREFIX*/CODE_MESSAGES CM ON CM.CODE_MESSAGE_ID=IM.CODE_MESSAGE_ID
   WHERE IN_MESSAGE_ID=:IN_MESSAGE_ID
    INTO :CONTACT, :CODE;

  IF ((CONTACT IS NOT NULL) AND (CODE IS NOT NULL)) THEN BEGIN

    INSERT INTO /*PREFIX*/OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                        TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,
                                        PRIORITY,LOCKED)
                                VALUES (/*PREFIX*/GET_UNIQUE_ID(),:ACCOUNT_ID,NULL,CURRENT_TIMESTAMP,
                                        'Это ответ через очередь на запрос: '||:CODE,NULL,0,:CONTACT,NULL,0,NULL);
  END
END


--

/* Фиксация изменений */

COMMIT