/* Создание таблицы валют */

CREATE TABLE /*PREFIX*/CURRENCY
(
  CURRENCY_ID VARCHAR(32) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(250),
  PRIORITY INTEGER NOT NULL,
  PRIMARY KEY (CURRENCY_ID)
)

--

/* Создание просмотра таблицы валют */

CREATE VIEW /*PREFIX*/S_CURRENCY
AS
SELECT * FROM /*PREFIX*/CURRENCY

--

/* Создание процедуры добавления валюты */

CREATE PROCEDURE /*PREFIX*/I_CURRENCY
  @CURRENCY_ID VARCHAR(32),
  @NAME VARCHAR(100),
  @DESCRIPTION VARCHAR(250),
  @PRIORITY INTEGER
AS
BEGIN
  INSERT INTO /*PREFIX*/CURRENCY (CURRENCY_ID,NAME,DESCRIPTION,PRIORITY)
       VALUES (@CURRENCY_ID,@NAME,@DESCRIPTION,@PRIORITY);
END;

--

/* Создание процедуры изменения валюты */

CREATE PROCEDURE /*PREFIX*/U_CURRENCY
  @CURRENCY_ID VARCHAR(32),
  @NAME VARCHAR(100),
  @DESCRIPTION VARCHAR(250),
  @PRIORITY INTEGER,
  @OLD_CURRENCY_ID VARCHAR(32)
AS
BEGIN
  UPDATE /*PREFIX*/CURRENCY
     SET CURRENCY_ID=@CURRENCY_ID,
         NAME=@NAME,
	 DESCRIPTION=@DESCRIPTION,
	 PRIORITY=@PRIORITY
   WHERE CURRENCY_ID=@OLD_CURRENCY_ID;
END;

--

/* Создание процедуры удаления валюты */

CREATE PROCEDURE /*PREFIX*/D_CURRENCY
  @OLD_CURRENCY_ID VARCHAR(32)
AS
BEGIN
  DELETE FROM /*PREFIX*/CURRENCY
        WHERE CURRENCY_ID=@OLD_CURRENCY_ID;
END;

--