/* Создание таблицы шаблонов */

CREATE TABLE /*PREFIX*/PATTERNS
(
  PATTERN_ID VARCHAR(32) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(250),
  PATTERN IMAGE NOT NULL,
  PRIMARY KEY (PATTERN_ID)
)

--

/* Создание просмотра таблицы шаблонов */

CREATE VIEW /*PREFIX*/S_PATTERNS
AS
SELECT * FROM /*PREFIX*/PATTERNS

--

/* Создание процедуры добавления шаблона */

CREATE PROCEDURE /*PREFIX*/I_PATTERN
  @PATTERN_ID VARCHAR(32),
  @NAME VARCHAR(100),
  @DESCRIPTION VARCHAR(250),
  @PATTERN IMAGE
AS
BEGIN
  INSERT INTO /*PREFIX*/PATTERNS (PATTERN_ID,NAME,DESCRIPTION,PATTERN)
       VALUES (@PATTERN_ID,@NAME,@DESCRIPTION,@PATTERN);
END;

--

/* Создание процедуры изменения шаблона */

CREATE PROCEDURE /*PREFIX*/U_PATTERN
  @PATTERN_ID VARCHAR(32),
  @NAME VARCHAR(100),
  @DESCRIPTION VARCHAR(250),
  @PATTERN IMAGE,
  @OLD_PATTERN_ID VARCHAR(32)
AS
BEGIN
  UPDATE /*PREFIX*/PATTERNS
     SET PATTERN_ID=@PATTERN_ID,
         NAME=@NAME,
	 DESCRIPTION=@DESCRIPTION,
	 PATTERN=@PATTERN
   WHERE PATTERN_ID=@OLD_PATTERN_ID;
END;

--

/* Создание процедуры удаления шаблона */

CREATE PROCEDURE /*PREFIX*/D_PATTERN
  @OLD_PATTERN_ID VARCHAR(32)
AS
BEGIN
  DELETE FROM /*PREFIX*/PATTERNS 
        WHERE PATTERN_ID=@OLD_PATTERN_ID;
END;

--