/* Создание таблицы клиентов доступных учетным записям */

CREATE TABLE /*PREFIX*/ACCOUNT_FIRMS
(
  ACCOUNT_ID VARCHAR(32) NOT NULL,
  FIRM_ID VARCHAR(32) NOT NULL,
  PRIMARY KEY (ACCOUNT_ID,FIRM_ID),
  FOREIGN KEY (ACCOUNT_ID) REFERENCES /*PREFIX*/ACCOUNTS (ACCOUNT_ID),
  FOREIGN KEY (FIRM_ID) REFERENCES /*PREFIX*/FIRMS (FIRM_ID)
)

--

/* Создание просмотра таблицы клиентов доступных учетным записям */

CREATE VIEW /*PREFIX*/S_ACCOUNT_FIRMS
AS
SELECT AF.*,
       A.USER_NAME AS USER_NAME,
       F.SMALL_NAME AS FIRM_SMALL_NAME
  FROM /*PREFIX*/ACCOUNT_FIRMS AF
  JOIN /*PREFIX*/ACCOUNTS A ON A.ACCOUNT_ID=AF.ACCOUNT_ID
  JOIN /*PREFIX*/FIRMS F ON F.FIRM_ID=AF.FIRM_ID
			
--

/* Создание процедуры добавления учетной записи клиента */

CREATE PROCEDURE /*PREFIX*/I_ACCOUNT_FIRM
  @ACCOUNT_ID VARCHAR(32),
  @FIRM_ID VARCHAR(32)
AS
BEGIN
  INSERT INTO /*PREFIX*/ACCOUNT_FIRMS (ACCOUNT_ID,FIRM_ID)
       VALUES (@ACCOUNT_ID,@FIRM_ID);
END;

--

/* Создание процедуры изменения клиента у учетной записи */

CREATE PROCEDURE /*PREFIX*/U_ACCOUNT_FIRM
  @ACCOUNT_ID VARCHAR(32),
  @FIRM_ID VARCHAR(32),
  @OLD_ACCOUNT_ID VARCHAR(32),
  @OLD_FIRM_ID VARCHAR(32)
AS
BEGIN
  UPDATE /*PREFIX*/ACCOUNT_FIRMS
     SET ACCOUNT_ID=@ACCOUNT_ID,
         FIRM_ID=@FIRM_ID
   WHERE ACCOUNT_ID=@OLD_ACCOUNT_ID
     AND FIRM_ID=@OLD_FIRM_ID;
END;

--

/* Создание процедуры удаления клиента у учетной записи */

CREATE PROCEDURE /*PREFIX*/D_ACCOUNT_FIRM
  @OLD_ACCOUNT_ID VARCHAR(32),
  @OLD_FIRM_ID VARCHAR(32)
AS
BEGIN
  DELETE FROM /*PREFIX*/ACCOUNT_FIRMS 
        WHERE ACCOUNT_ID=@OLD_ACCOUNT_ID
          AND FIRM_ID=@OLD_FIRM_ID;
END;

--