/* Создание таблицы групп */

CREATE TABLE /*PREFIX*/GROUPS
(
  GROUP_ID VARCHAR(32) NOT NULL,
  PARENT_ID VARCHAR(32),
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(250),
  PATTERN_ID VARCHAR(32),
  PRIMARY KEY (GROUP_ID),
  FOREIGN KEY (PARENT_ID) REFERENCES /*PREFIX*/GROUPS (GROUP_ID),
  FOREIGN KEY (PATTERN_ID) REFERENCES /*PREFIX*/PATTERNS (PATTERN_ID)
)

--

/* Создание просмотра таблицы групп */

CREATE VIEW /*PREFIX*/S_GROUPS
AS
  SELECT G.*, 
         G1.NAME AS PARENT_NAME,
         P.NAME AS PATTERN_NAME
    FROM /*PREFIX*/GROUPS G
    LEFT JOIN /*PREFIX*/GROUPS G1 ON G1.GROUP_ID=G.PARENT_ID
    LEFT JOIN /*PREFIX*/PATTERNS P ON P.PATTERN_ID=G.PATTERN_ID

--

/* Создание процедуры добавления группы */

CREATE PROCEDURE /*PREFIX*/I_GROUP
  @GROUP_ID VARCHAR(32),
  @PATTERN_ID VARCHAR(32),
  @PARENT_ID VARCHAR(32),
  @NAME VARCHAR(100),
  @DESCRIPTION VARCHAR(250)
AS
BEGIN
  INSERT INTO /*PREFIX*/GROUPS (GROUP_ID,PATTERN_ID,PARENT_ID,NAME,DESCRIPTION)
       VALUES (@GROUP_ID,@PATTERN_ID,@PARENT_ID,@NAME,@DESCRIPTION);
END;

--

/* Создание процедуры изменения группы */

CREATE PROCEDURE /*PREFIX*/U_GROUP
  @GROUP_ID VARCHAR(32),
  @PATTERN_ID VARCHAR(32),
  @PARENT_ID VARCHAR(32),
  @NAME VARCHAR(100),
  @DESCRIPTION VARCHAR(250),
  @OLD_GROUP_ID VARCHAR(32)
AS
BEGIN
  UPDATE /*PREFIX*/GROUPS
     SET GROUP_ID=@GROUP_ID,
         PATTERN_ID=@PATTERN_ID,
	 PARENT_ID=@PARENT_ID,
	 NAME=@NAME,
         DESCRIPTION=@DESCRIPTION
   WHERE GROUP_ID=@OLD_GROUP_ID;
END;

--

/* Создание процедуры удаления группы */

CREATE PROCEDURE /*PREFIX*/D_GROUP
  @OLD_GROUP_ID VARCHAR(32)
AS
BEGIN
  DELETE FROM /*PREFIX*/GROUPS
        WHERE GROUP_ID=@OLD_GROUP_ID;
END;

--