/* Создание таблицы групп доступных учетным записям */

CREATE TABLE /*PREFIX*/ACCOUNT_GROUPS
(
  ACCOUNT_ID VARCHAR(32) NOT NULL,
  GROUP_ID VARCHAR(32) NOT NULL,
  PRIORITY INTEGER NOT NULL,
  PRIMARY KEY (ACCOUNT_ID,GROUP_ID),
  FOREIGN KEY (ACCOUNT_ID) REFERENCES /*PREFIX*/ACCOUNTS (ACCOUNT_ID),
  FOREIGN KEY (GROUP_ID) REFERENCES /*PREFIX*/GROUPS (GROUP_ID)
)

--

/* Создание просмотра таблицы групп доступных учетным записям */

CREATE VIEW /*PREFIX*/S_ACCOUNT_GROUPS
AS
SELECT AG.*,
       A.USER_NAME AS USER_NAME,
       G.NAME AS GROUP_NAME
  FROM /*PREFIX*/ACCOUNT_GROUPS AG
  JOIN /*PREFIX*/ACCOUNTS A ON A.ACCOUNT_ID=AG.ACCOUNT_ID
  JOIN /*PREFIX*/GROUPS G ON G.GROUP_ID=AG.GROUP_ID
			
--

/* Создание процедуры добавления группы учетной записи */

CREATE PROCEDURE /*PREFIX*/I_ACCOUNT_GROUP
  @ACCOUNT_ID VARCHAR(32),
  @GROUP_ID VARCHAR(32),
  @PRIORITY INTEGER
AS
BEGIN
  INSERT INTO /*PREFIX*/ACCOUNT_GROUPS (ACCOUNT_ID,GROUP_ID,PRIORITY)
       VALUES (@ACCOUNT_ID,@GROUP_ID,@PRIORITY);
END;

--

/* Создание процедуры изменения группы у учетной записи */

CREATE PROCEDURE /*PREFIX*/U_ACCOUNT_GROUP
  @ACCOUNT_ID VARCHAR(32),
  @GROUP_ID VARCHAR(32),
  @PRIORITY INTEGER,
  @OLD_ACCOUNT_ID VARCHAR(32),
  @OLD_GROUP_ID VARCHAR(32)
AS
BEGIN
  UPDATE /*PREFIX*/ACCOUNT_GROUPS
     SET ACCOUNT_ID=@ACCOUNT_ID,
         GROUP_ID=@GROUP_ID,
         PRIORITY=@PRIORITY
   WHERE ACCOUNT_ID=@OLD_ACCOUNT_ID
     AND GROUP_ID=@OLD_GROUP_ID;
END;

--

/* Создание процедуры удаления группы у учетной записи */

CREATE PROCEDURE /*PREFIX*/D_ACCOUNT_GROUP
  @OLD_ACCOUNT_ID VARCHAR(32),
  @OLD_GROUP_ID VARCHAR(32)
AS
BEGIN
  DELETE FROM /*PREFIX*/ACCOUNT_GROUPS 
        WHERE ACCOUNT_ID=@OLD_ACCOUNT_ID
          AND GROUP_ID=@OLD_GROUP_ID;
END;

--