/* Создание таблицы планов */

CREATE TABLE /*PREFIX*/PLANS
(
  PLAN_ID VARCHAR(32) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(250),
  PRIMARY KEY (PLAN_ID)
)

--

/* Создание просмотра таблицы планов */

CREATE VIEW /*PREFIX*/S_PLANS
AS
SELECT * FROM /*PREFIX*/PLANS

--

/* Создание процедуры добавления плана */

CREATE PROCEDURE /*PREFIX*/I_PLAN
  @PLAN_ID VARCHAR(32),
  @NAME VARCHAR(100),
  @DESCRIPTION VARCHAR(250)
AS
BEGIN
  INSERT INTO /*PREFIX*/PLANS (PLAN_ID,NAME,DESCRIPTION)
       VALUES (@PLAN_ID,@NAME,@DESCRIPTION);
END;

--

/* Создание процедуры изменения плана */

CREATE PROCEDURE /*PREFIX*/U_PLAN
  @PLAN_ID VARCHAR(32),
  @NAME VARCHAR(100),
  @DESCRIPTION VARCHAR(250),
  @OLD_PLAN_ID VARCHAR(32)
AS
BEGIN
  UPDATE /*PREFIX*/PLANS
     SET PLAN_ID=@PLAN_ID,
         NAME=@NAME,
	 DESCRIPTION=@DESCRIPTION
   WHERE PLAN_ID=@OLD_PLAN_ID;
END;

--

/* Создание процедуры удаления плана */

CREATE PROCEDURE /*PREFIX*/D_PLAN
  @OLD_PLAN_ID VARCHAR(32)
AS
BEGIN
  DELETE FROM /*PREFIX*/PLANS 
        WHERE PLAN_ID=@OLD_PLAN_ID;
END;

--