/* Создание таблицы действий доступных учетным записям */

CREATE TABLE /*PREFIX*/ACCOUNT_ACTIONS
(
  ACCOUNT_ID VARCHAR(32) NOT NULL,
  ACTION_ID VARCHAR(32) NOT NULL,
  PRIORITY INTEGER NOT NULL,
  PRIMARY KEY (ACCOUNT_ID,ACTION_ID),
  FOREIGN KEY (ACCOUNT_ID) REFERENCES /*PREFIX*/ACCOUNTS (ACCOUNT_ID),
  FOREIGN KEY (ACTION_ID) REFERENCES /*PREFIX*/ACTIONS (ACTION_ID)
)

--

/* Создание просмотра таблицы действий доступных учетным записям */

CREATE VIEW /*PREFIX*/S_ACCOUNT_ACTIONS
AS
SELECT AA.*,
       A.USER_NAME AS USER_NAME,
       AN.NAME AS ACTION_NAME
  FROM /*PREFIX*/ACCOUNT_ACTIONS AA
  JOIN /*PREFIX*/ACCOUNTS A ON A.ACCOUNT_ID=AA.ACCOUNT_ID
  JOIN /*PREFIX*/ACTIONS AN ON AN.ACTION_ID=AA.ACTION_ID
			
--

/* Создание процедуры добавления действия учетной записи */

CREATE PROCEDURE /*PREFIX*/I_ACCOUNT_ACTION
  @ACCOUNT_ID VARCHAR(32),
  @ACTION_ID VARCHAR(32),
  @PRIORITY INTEGER
AS
BEGIN
  INSERT INTO /*PREFIX*/ACCOUNT_ACTIONS (ACCOUNT_ID,ACTION_ID,PRIORITY)
       VALUES (@ACCOUNT_ID,@ACTION_ID,@PRIORITY);
END;

--

/* Создание процедуры изменения действия у учетной записи */

CREATE PROCEDURE /*PREFIX*/U_ACCOUNT_ACTION
  @ACCOUNT_ID VARCHAR(32),
  @ACTION_ID VARCHAR(32),
  @PRIORITY INTEGER,
  @OLD_ACCOUNT_ID VARCHAR(32),
  @OLD_ACTION_ID VARCHAR(32)
AS
BEGIN
  UPDATE /*PREFIX*/ACCOUNT_ACTIONS
     SET ACCOUNT_ID=@ACCOUNT_ID,
         ACTION_ID=@ACTION_ID,
         PRIORITY=@PRIORITY
   WHERE ACCOUNT_ID=@OLD_ACCOUNT_ID
     AND ACTION_ID=@OLD_ACTION_ID;
END;

--

/* Создание процедуры удаления действия у учетной записи */

CREATE PROCEDURE /*PREFIX*/D_ACCOUNT_ACTION
  @OLD_ACCOUNT_ID VARCHAR(32),
  @OLD_ACTION_ID VARCHAR(32)
AS
BEGIN
  DELETE FROM /*PREFIX*/ACCOUNT_ACTIONS 
        WHERE ACCOUNT_ID=@OLD_ACCOUNT_ID
          AND ACTION_ID=@OLD_ACTION_ID;
END;

--