/* Создание таблицы состава планов */

CREATE TABLE /*PREFIX*/PLAN_ACTIONS
(
  PLAN_ID VARCHAR(32) NOT NULL,
  ACTION_ID VARCHAR(32) NOT NULL,
  PRIORITY INTEGER NOT NULL,
  PERIOD INTEGER NOT NULL,
  PRIMARY KEY (PLAN_ID,ACTION_ID),
  FOREIGN KEY (PLAN_ID) REFERENCES /*PREFIX*/PLANS (PLAN_ID),
  FOREIGN KEY (ACTION_ID) REFERENCES /*PREFIX*/ACTIONS (ACTION_ID)
)

--

/* Создание просмотра таблицы состава планов */

CREATE VIEW /*PREFIX*/S_PLAN_ACTIONS
AS
SELECT PA.*,
       P.NAME AS PLAN_NAME,
       A.NAME AS ACTION_NAME
  FROM /*PREFIX*/PLAN_ACTIONS PA
  JOIN /*PREFIX*/PLANS P ON P.PLAN_ID=PA.PLAN_ID
  JOIN /*PREFIX*/ACTIONS A ON A.ACTION_ID=PA.ACTION_ID
			
--

/* Создание процедуры добавления состава плана */

CREATE PROCEDURE /*PREFIX*/I_PLAN_ACTION
  @PLAN_ID VARCHAR(32),
  @ACTION_ID VARCHAR(32),
  @PRIORITY INTEGER,
  @PERIOD INTEGER
AS
BEGIN
  INSERT INTO /*PREFIX*/PLAN_ACTIONS (PLAN_ID,ACTION_ID,PRIORITY,PERIOD)
       VALUES (@PLAN_ID,@ACTION_ID,@PRIORITY,@PERIOD);
END;

--

/* Создание процедуры изменения состава плана */

CREATE PROCEDURE /*PREFIX*/U_PLAN_ACTION
  @PLAN_ID VARCHAR(32),
  @ACTION_ID VARCHAR(32),
  @PRIORITY INTEGER,
  @PERIOD INTEGER,
  @OLD_PLAN_ID VARCHAR(32),
  @OLD_ACTION_ID VARCHAR(32)
AS
BEGIN
  UPDATE /*PREFIX*/PLAN_ACTIONS
     SET PLAN_ID=@PLAN_ID,
         ACTION_ID=@ACTION_ID,
         PRIORITY=@PRIORITY,
         PERIOD=@PERIOD
   WHERE PLAN_ID=@OLD_PLAN_ID
     AND ACTION_ID=@OLD_ACTION_ID;
END;

--

/* Создание процедуры удаления состава плана */

CREATE PROCEDURE /*PREFIX*/D_PLAN_ACTION
  @OLD_PLAN_ID VARCHAR(32),
  @OLD_ACTION_ID VARCHAR(32)
AS
BEGIN
  DELETE FROM /*PREFIX*/PLAN_ACTIONS 
        WHERE PLAN_ID=@OLD_PLAN_ID
          AND ACTION_ID=@OLD_ACTION_ID;
END;

--