/* Создание таблицы статусов */

CREATE TABLE /*PREFIX*/STATUSES
(
  STATUS_ID VARCHAR(32) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(250),
  TABLE_NAME VARCHAR(100) NOT NULL,
  CONDITION VARCHAR(250),
  PRIORITY INTEGER NOT NULL,
  PRIMARY KEY (STATUS_ID)
)

--

/* Создание просмотра таблицы статусов */

CREATE VIEW /*PREFIX*/S_STATUSES
AS
SELECT * FROM /*PREFIX*/STATUSES

--

/* Создание процедуры добавления статуса */

CREATE PROCEDURE /*PREFIX*/I_STATUS
  @STATUS_ID VARCHAR(32),
  @NAME VARCHAR(100),
  @DESCRIPTION VARCHAR(250),
  @TABLE_NAME VARCHAR(100),
  @CONDITION VARCHAR(250),
  @PRIORITY INTEGER
AS
BEGIN
  INSERT INTO /*PREFIX*/STATUSES (STATUS_ID,NAME,DESCRIPTION,TABLE_NAME,CONDITION,PRIORITY)
       VALUES (@STATUS_ID,@NAME,@DESCRIPTION,@TABLE_NAME,@CONDITION,@PRIORITY);
END;

--

/* Создание процедуры изменения статуса */

CREATE PROCEDURE /*PREFIX*/U_STATUS
  @STATUS_ID VARCHAR(32),
  @NAME VARCHAR(100),
  @DESCRIPTION VARCHAR(250),
  @TABLE_NAME VARCHAR(100),
  @CONDITION VARCHAR(250),
  @PRIORITY INTEGER,
  @OLD_STATUS_ID VARCHAR(32)
AS
BEGIN
  UPDATE /*PREFIX*/STATUSES
     SET STATUS_ID=@STATUS_ID,
         NAME=@NAME,
	 DESCRIPTION=@DESCRIPTION,
         TABLE_NAME=@TABLE_NAME,
         CONDITION=@CONDITION,
	 PRIORITY=@PRIORITY
   WHERE STATUS_ID=@OLD_STATUS_ID;
END;

--

/* Создание процедуры удаления статуса */

CREATE PROCEDURE /*PREFIX*/D_STATUS
  @OLD_STATUS_ID VARCHAR(32)
AS
BEGIN
  DELETE FROM /*PREFIX*/STATUSES 
        WHERE STATUS_ID=@OLD_STATUS_ID;
END;

--