/* Создание таблицы падежей */

CREATE TABLE /*PREFIX*/CASES
(
  SURNAME_IP VARCHAR(100) NOT NULL,
  NAME_IP VARCHAR(100) NOT NULL,
  PATRONYMIC_IP VARCHAR(100) NOT NULL,

  SURNAME_RP VARCHAR(100),
  NAME_RP VARCHAR(100),
  PATRONYMIC_RP VARCHAR(100),

  SURNAME_DP VARCHAR(100),
  NAME_DP VARCHAR(100),
  PATRONYMIC_DP VARCHAR(100),

  SURNAME_VP VARCHAR(100),
  NAME_VP VARCHAR(100),
  PATRONYMIC_VP VARCHAR(100),

  SURNAME_TP VARCHAR(100),
  NAME_TP VARCHAR(100),
  PATRONYMIC_TP VARCHAR(100),

  SURNAME_PP VARCHAR(100),
  NAME_PP VARCHAR(100),
  PATRONYMIC_PP VARCHAR(100),

  PRIMARY KEY (SURNAME_IP,NAME_IP,PATRONYMIC_IP)
)

--

/* Создание просмотра таблицы падежей */

CREATE VIEW /*PREFIX*/S_CASES
AS
SELECT * FROM /*PREFIX*/CASES

--

/* Создание процедуры добавления падежа */

CREATE PROCEDURE /*PREFIX*/I_CASE
  @SURNAME_IP VARCHAR(100),
  @NAME_IP VARCHAR(100),
  @PATRONYMIC_IP VARCHAR(100),

  @SURNAME_RP VARCHAR(100),
  @NAME_RP VARCHAR(100),
  @PATRONYMIC_RP VARCHAR(100),

  @SURNAME_DP VARCHAR(100),
  @NAME_DP VARCHAR(100),
  @PATRONYMIC_DP VARCHAR(100),

  @SURNAME_VP VARCHAR(100),
  @NAME_VP VARCHAR(100),
  @PATRONYMIC_VP VARCHAR(100),

  @SURNAME_TP VARCHAR(100),
  @NAME_TP VARCHAR(100),
  @PATRONYMIC_TP VARCHAR(100),

  @SURNAME_PP VARCHAR(100),
  @NAME_PP VARCHAR(100),
  @PATRONYMIC_PP VARCHAR(100)
AS
BEGIN
  INSERT INTO /*PREFIX*/CASES (SURNAME_IP,NAME_IP,PATRONYMIC_IP,
                               SURNAME_RP,NAME_RP,PATRONYMIC_RP,
                               SURNAME_DP,NAME_DP,PATRONYMIC_DP,
                               SURNAME_VP,NAME_VP,PATRONYMIC_VP,
                               SURNAME_TP,NAME_TP,PATRONYMIC_TP,
                               SURNAME_PP,NAME_PP,PATRONYMIC_PP)
       VALUES (@SURNAME_IP,@NAME_IP,@PATRONYMIC_IP,
               @SURNAME_RP,@NAME_RP,@PATRONYMIC_RP,
               @SURNAME_DP,@NAME_DP,@PATRONYMIC_DP,
               @SURNAME_VP,@NAME_VP,@PATRONYMIC_VP,
               @SURNAME_TP,@NAME_TP,@PATRONYMIC_TP,
               @SURNAME_PP,@NAME_PP,@PATRONYMIC_PP);
END;

--

/* Создание процедуры изменения падежа */

CREATE PROCEDURE /*PREFIX*/U_CASE
  @SURNAME_IP VARCHAR(100),
  @NAME_IP VARCHAR(100),
  @PATRONYMIC_IP VARCHAR(100),

  @SURNAME_RP VARCHAR(100),
  @NAME_RP VARCHAR(100),
  @PATRONYMIC_RP VARCHAR(100),

  @SURNAME_DP VARCHAR(100),
  @NAME_DP VARCHAR(100),
  @PATRONYMIC_DP VARCHAR(100),

  @SURNAME_VP VARCHAR(100),
  @NAME_VP VARCHAR(100),
  @PATRONYMIC_VP VARCHAR(100),

  @SURNAME_TP VARCHAR(100),
  @NAME_TP VARCHAR(100),
  @PATRONYMIC_TP VARCHAR(100),

  @SURNAME_PP VARCHAR(100),
  @NAME_PP VARCHAR(100),
  @PATRONYMIC_PP VARCHAR(100),

  @OLD_SURNAME_IP VARCHAR(100),
  @OLD_NAME_IP VARCHAR(100),
  @OLD_PATRONYMIC_IP VARCHAR(100)
AS
BEGIN
  UPDATE /*PREFIX*/CASES
     SET SURNAME_IP=@SURNAME_IP,
         NAME_IP=@NAME_IP,
         PATRONYMIC_IP=@PATRONYMIC_IP,

         SURNAME_RP=@SURNAME_RP,
         NAME_RP=@NAME_RP,
         PATRONYMIC_RP=@PATRONYMIC_RP,

         SURNAME_DP=@SURNAME_DP,
         NAME_DP=@NAME_DP,
         PATRONYMIC_DP=@PATRONYMIC_DP,

         SURNAME_VP=@SURNAME_VP,
         NAME_VP=@NAME_VP,
         PATRONYMIC_VP=@PATRONYMIC_VP,

         SURNAME_TP=@SURNAME_TP,
         NAME_TP=@NAME_TP,
         PATRONYMIC_TP=@PATRONYMIC_TP,

         SURNAME_PP=@SURNAME_PP,
         NAME_PP=@NAME_PP,
         PATRONYMIC_PP=@PATRONYMIC_PP

   WHERE SURNAME_IP=@OLD_SURNAME_IP 
     AND NAME_IP=@OLD_NAME_IP
     AND PATRONYMIC_IP=@OLD_PATRONYMIC_IP;
END;

--

/* Создание процедуры удаления падежа */

CREATE PROCEDURE /*PREFIX*/D_CASE
  @OLD_SURNAME_IP VARCHAR(100),
  @OLD_NAME_IP VARCHAR(100),
  @OLD_PATRONYMIC_IP VARCHAR(100)
AS
BEGIN
  DELETE FROM /*PREFIX*/CASES 
        WHERE SURNAME_IP=@OLD_SURNAME_IP 
          AND NAME_IP=@OLD_NAME_IP
          AND PATRONYMIC_IP=@OLD_PATRONYMIC_IP;
END;

--