/* Создание таблицы кредитных дел */

CREATE TABLE /*PREFIX*/DEALS
(
  DEAL_ID VARCHAR(32) NOT NULL,
  PLAN_ID VARCHAR(32),
  GROUP_ID VARCHAR(32) NOT NULL,
  AGREEMENT_ID VARCHAR(32) NOT NULL,
  DEBTOR_ID VARCHAR(32) NOT NULL,
  DEAL_NUM VARCHAR(100) NOT NULL,
  DATE_ISSUE DATETIME NOT NULL,
  DATE_CLOSE DATETIME,
  ACCOUNT_NUM VARCHAR(100) NOT NULL,
  ARREAR_PERIOD INTEGER NOT NULL,
  INITIAL_DEBT FLOAT NOT NULL,
  DEBT_INFORMATION IMAGE NOT NULL,
  GUARANTORS IMAGE,
  DEBTOR_NUM VARCHAR(100) NOT NULL,
  DEBTOR_DATE DATETIME NOT NULL,
  PRIMARY KEY (DEAL_ID),
  FOREIGN KEY (ACTION_ID) REFERENCES /*PREFIX*/ACTIONS (ACTION_ID),
  FOREIGN KEY (GROUP_ID) REFERENCES /*PREFIX*/GROUPS (GROUP_ID),
  FOREIGN KEY (AGREEMENT_ID) REFERENCES /*PREFIX*/AGREEMENTS (AGREEMENT_ID),
  FOREIGN KEY (DEBTOR_ID) REFERENCES /*PREFIX*/DEBTORS (DEBTOR_ID)
)

--

/* Создание просмотра таблицы кредитных дел */

CREATE VIEW /*PREFIX*/S_DEALS
AS
   SELECT D.*, 
          G.NAME AS GROUP_NAME,
          AG.NUM AS AGREEMENT_NUM,
          DB.SURNAME+' '+DB.NAME+' '+DB.PATRONYMIC+' '+CONVERT(VARCHAR(10),DB.DATE_BIRTH,104) AS DEBTOR_NAME,
          P.NAME AS PLAN_NAME,
          DB.DEBTOR_TYPE,
          DB.SURNAME,
          DB.NAME,
          DB.PATRONYMIC,
          DB.PASSPORT,
          DB.SEX,
          DB.DATE_BIRTH,
          DB.PLACE_BIRTH,
          DB.ADDRESS_RESIDENCE,
          DB.INDEX_RESIDENCE,
          DB.ADDRESS_ACTUAL,
          DB.INDEX_ACTUAL,
          DB.ADDRESS_ADDITIONAL,
          DB.INDEX_ADDITIONAL,
          DB.PLACE_WORK,
          DB.JOB_TITLE,
          DB.ADDRESS_WORK,
          DB.INDEX_WORK,
          DB.PHONE_HOME,
          DB.PHONE_WORK,
          DB.PHONE_MOBILE,
          DB.PHONE_OTHER1,
          DB.PHONE_OTHER2,
          DB.FOUNDERS
     FROM /*PREFIX*/DEALS D
     JOIN /*PREFIX*/GROUPS G ON G.GROUP_ID=D.GROUP_ID
     JOIN /*PREFIX*/AGREEMENTS AG ON AG.AGREEMENT_ID=D.AGREEMENT_ID
     JOIN /*PREFIX*/DEBTORS DB ON DB.DEBTOR_ID=D.DEBTOR_ID
     LEFT JOIN /*PREFIX*/PLANS P ON P.PLAN_ID=D.PLAN_ID

--

/* Создание процедуры добавления кредитного дела */

CREATE PROCEDURE /*PREFIX*/I_DEAL
  @DEAL_ID VARCHAR(32),
  @PLAN_ID VARCHAR(32),
  @GROUP_ID VARCHAR(32),
  @AGREEMENT_ID VARCHAR(32),
  @DEBTOR_ID VARCHAR(32),
  @DEAL_NUM VARCHAR(100),
  @DATE_ISSUE DATETIME,
  @DATE_CLOSE DATETIME,
  @ACCOUNT_NUM VARCHAR(100),
  @ARREAR_PERIOD INTEGER,
  @INITIAL_DEBT FLOAT,
  @DEBT_INFORMATION IMAGE,
  @GUARANTORS IMAGE,
  @DEBTOR_NUM VARCHAR(100),
  @DEBTOR_DATE DATETIME
AS
BEGIN
  INSERT INTO /*PREFIX*/DEALS (DEAL_ID,PLAN_ID,GROUP_ID,AGREEMENT_ID,DEBTOR_ID,
                               DEAL_NUM,DATE_ISSUE,DATE_CLOSE,ACCOUNT_NUM,ARREAR_PERIOD,
                               INITIAL_DEBT,DEBT_INFORMATION,GUARANTORS,DEBTOR_NUM,DEBTOR_DATE)
       VALUES (@DEAL_ID,@PLAN_ID,@GROUP_ID,@AGREEMENT_ID,@DEBTOR_ID,
               @DEAL_NUM,@DATE_ISSUE,@DATE_CLOSE,@ACCOUNT_NUM,@ARREAR_PERIOD,
               @INITIAL_DEBT,@DEBT_INFORMATION,@GUARANTORS,@DEBTOR_NUM,@DEBTOR_DATE);
END;

--

/* Создание процедуры изменения кредитного дела */

CREATE PROCEDURE /*PREFIX*/U_DEAL
  @DEAL_ID VARCHAR(32),
  @PLAN_ID VARCHAR(32),
  @GROUP_ID VARCHAR(32),
  @AGREEMENT_ID VARCHAR(32),
  @DEBTOR_ID VARCHAR(32),
  @DEAL_NUM VARCHAR(100),
  @DATE_ISSUE DATETIME,
  @DATE_CLOSE DATETIME,
  @ACCOUNT_NUM VARCHAR(100),
  @ARREAR_PERIOD INTEGER,
  @INITIAL_DEBT FLOAT,
  @DEBT_INFORMATION IMAGE,
  @GUARANTORS IMAGE,
  @DEBTOR_NUM VARCHAR(100),
  @DEBTOR_DATE DATETIME,
  @OLD_DEAL_ID VARCHAR(32)
AS
BEGIN
  UPDATE /*PREFIX*/DEALS
     SET DEAL_ID=@DEAL_ID,
         PLAN_ID=@PLAN_ID,
         GROUP_ID=@GROUP_ID,
         AGREEMENT_ID=@AGREEMENT_ID,
         DEBTOR_ID=@DEBTOR_ID,
         DEAL_NUM=@DEAL_NUM,
         DATE_ISSUE=@DATE_ISSUE,
         DATE_CLOSE=@DATE_CLOSE,
         ACCOUNT_NUM=@ACCOUNT_NUM,
         ARREAR_PERIOD=@ARREAR_PERIOD,
         INITIAL_DEBT=@INITIAL_DEBT,
         DEBT_INFORMATION=@DEBT_INFORMATION,
         GUARANTORS=@GUARANTORS,
         DEBTOR_NUM=@DEBTOR_NUM,
         DEBTOR_DATE=@DEBTOR_DATE
   WHERE DEAL_ID=@OLD_DEAL_ID;
END;

--

/* Создание процедуры удаления кредитного дела */

CREATE PROCEDURE /*PREFIX*/D_DEAL
  @OLD_DEAL_ID VARCHAR(32)
AS
BEGIN
  DELETE FROM /*PREFIX*/DEALS
        WHERE DEAL_ID=@OLD_DEAL_ID;
END;

--