/* Создание таблицы заданий */

CREATE TABLE /*PREFIX*/TASKS
(
  TASK_ID VARCHAR(32) NOT NULL,
  DEAL_ID VARCHAR(32) NOT NULL,
  ACTION_ID VARCHAR(32) NOT NULL,
  ACCOUNT_ID VARCHAR(32),
  PERFORMER_ID VARCHAR(32),
  RESULT_ID VARCHAR(32),
  DATE_CREATE DATETIME NOT NULL,
  DATE_BEGIN DATETIME, 
  DATE_END DATETIME, 
  DESCRIPTION VARCHAR(4000),  
  PRIMARY KEY (TASK_ID),
  FOREIGN KEY (DEAL_ID) REFERENCES /*PREFIX*/DEALS (DEAL_ID),
  FOREIGN KEY (ACTION_ID) REFERENCES /*PREFIX*/ACTIONS (ACTION_ID),
  FOREIGN KEY (ACCOUNT_ID) REFERENCES /*PREFIX*/ACCOUNTS (ACCOUNT_ID),
  FOREIGN KEY (PERFORMER_ID) REFERENCES /*PREFIX*/ACCOUNTS (ACCOUNT_ID),
  FOREIGN KEY (RESULT_ID) REFERENCES /*PREFIX*/RESULTS (RESULT_ID)
)

--

/* Создание просмотра таблицы заданий */

CREATE VIEW /*PREFIX*/S_TASKS
AS
   SELECT T.*, 
          D.DEAL_NUM,
          A.NAME AS ACTION_NAME,
          AC1.USER_NAME,
          AC2.USER_NAME AS PERFORMER_USER_NAME,
          R.NAME AS RESULT_NAME
     FROM /*PREFIX*/TASKS T
     JOIN /*PREFIX*/DEALS D ON D.DEAL_ID=T.DEAL_ID
     JOIN /*PREFIX*/ACTIONS A ON A.ACTION_ID=T.ACTION_ID
     LEFT JOIN /*PREFIX*/ACCOUNTS AC1 ON AC1.ACCOUNT_ID=T.ACCOUNT_ID
     LEFT JOIN /*PREFIX*/ACCOUNTS AC2 ON AC2.ACCOUNT_ID=T.PERFORMER_ID
     LEFT JOIN /*PREFIX*/RESULTS R ON R.RESULT_ID=T.RESULT_ID

--

/* Создание процедуры добавления задания */

CREATE PROCEDURE /*PREFIX*/I_TASK
  @TASK_ID VARCHAR(32),
  @DEAL_ID VARCHAR(32),
  @ACTION_ID VARCHAR(32),
  @ACCOUNT_ID VARCHAR(32),
  @PERFORMER_ID VARCHAR(32),
  @RESULT_ID VARCHAR(32),
  @DATE_CREATE DATETIME,
  @DATE_BEGIN DATETIME, 
  @DATE_END DATETIME, 
  @DESCRIPTION VARCHAR(4000)  
AS
BEGIN
  INSERT INTO /*PREFIX*/TASKS (TASK_ID,DEAL_ID,ACTION_ID,ACCOUNT_ID,PERFORMER_ID,RESULT_ID,
                               DATE_CREATE,DATE_BEGIN,DATE_END,DESCRIPTION)
       VALUES (@TASK_ID,@DEAL_ID,@ACTION_ID,@ACCOUNT_ID,@PERFORMER_ID,@RESULT_ID,
               @DATE_CREATE,@DATE_BEGIN,@DATE_END,@DESCRIPTION);
END;

--

/* Создание процедуры изменения задания */

CREATE PROCEDURE /*PREFIX*/U_TASK
  @TASK_ID VARCHAR(32),
  @DEAL_ID VARCHAR(32),
  @ACTION_ID VARCHAR(32),
  @ACCOUNT_ID VARCHAR(32),
  @PERFORMER_ID VARCHAR(32),
  @RESULT_ID VARCHAR(32),
  @DATE_CREATE DATETIME,
  @DATE_BEGIN DATETIME, 
  @DATE_END DATETIME, 
  @DESCRIPTION VARCHAR(4000),
  @OLD_TASK_ID VARCHAR(32)
AS
BEGIN
  UPDATE /*PREFIX*/TASKS
     SET TASK_ID=@TASK_ID,
         DEAL_ID=@DEAL_ID,
         ACTION_ID=@ACTION_ID,
         ACCOUNT_ID=@ACCOUNT_ID,
         PERFORMER_ID=@PERFORMER_ID,
         RESULT_ID=@RESULT_ID,
         DATE_CREATE=@DATE_CREATE,
         DATE_BEGIN=@DATE_BEGIN,
         DATE_END=@DATE_END,
         DESCRIPTION=@DESCRIPTION
   WHERE TASK_ID=@OLD_TASK_ID;
END;

--

/* Создание процедуры удаления задания */

CREATE PROCEDURE /*PREFIX*/D_TASK
  @OLD_TASK_ID VARCHAR(32)
AS
BEGIN
  DELETE FROM /*PREFIX*/TASKS
        WHERE TASK_ID=@OLD_TASK_ID;
END;

--