/* Создание просмотра таблицы кредитных дел и организаций */

CREATE VIEW /*PREFIX*/S_DEAL_FIRMS
AS
   SELECT D.DEAL_ID,
          D.PLAN_ID,  
          D.GROUP_ID,
          D.AGREEMENT_ID,
          D.DEAL_NUM,
          D.DATE_ISSUE,
          D.DATE_CLOSE,
          D.ACCOUNT_NUM,
          D.ARREAR_PERIOD,
          D.INITIAL_DEBT,
          D.DEBT_INFORMATION,
          D.GUARANTORS, 
          D.DEBTOR_NUM,
          D.DEBTOR_DATE,
          DB.*,
          A.NUM AS AGREEMENT_NUM,
          F.FIRM_ID, 
          F.SMALL_NAME AS FIRM_SMALL_NAME,
          C.NAME AS CURRENCY_NAME,
          G.NAME AS GROUP_NAME,
          PL.NAME AS PLAN_NAME,
          P1.AMOUNT AS AMOUNT_PAYMENT,
          P.PATTERN,
          (CASE  
             WHEN P1.AMOUNT IS NULL THEN D.INITIAL_DEBT
             ELSE D.INITIAL_DEBT-P1.AMOUNT
           END) AS CURRENT_DEBT
     FROM /*PREFIX*/DEALS D
     JOIN /*PREFIX*/DEBTORS DB ON DB.DEBTOR_ID=D.DEBTOR_ID
     JOIN /*PREFIX*/GROUPS G ON G.GROUP_ID=D.GROUP_ID
     JOIN /*PREFIX*/AGREEMENTS A ON A.AGREEMENT_ID=D.AGREEMENT_ID
     JOIN /*PREFIX*/FIRMS F ON F.FIRM_ID=A.FIRM_ID
     JOIN /*PREFIX*/VARIANTS V ON V.VARIANT_ID=A.VARIANT_ID
     JOIN /*PREFIX*/CURRENCY C ON C.CURRENCY_ID=V.CURRENCY_ID
     LEFT JOIN /*PREFIX*/PLANS PL ON PL.PLAN_ID=D.PLAN_ID
     LEFT JOIN /*PREFIX*/PATTERNS P ON P.PATTERN_ID=G.PATTERN_ID
     LEFT JOIN (SELECT DEAL_ID, SUM(AMOUNT) AS AMOUNT 
                  FROM /*PREFIX*/PAYMENTS WHERE STATE=1
                 GROUP BY DEAL_ID)AS P1 ON P1.DEAL_ID=D.DEAL_ID   

--

