/* Создание таблицы отчетов доступных действиям */

CREATE TABLE /*PREFIX*/ACTION_REPORTS
(
  ACTION_ID VARCHAR(32) NOT NULL,
  REPORT_ID VARCHAR(32) NOT NULL,
  PRIORITY INTEGER NOT NULL,
  PRIMARY KEY (ACTION_ID,REPORT_ID),
  FOREIGN KEY (ACTION_ID) REFERENCES /*PREFIX*/ACTIONS (ACTION_ID),
  FOREIGN KEY (REPORT_ID) REFERENCES /*PREFIX*/REPORTS (REPORT_ID)
)

--

/* Создание просмотра таблицы отчетов доступных действиям */

CREATE VIEW /*PREFIX*/S_ACTION_REPORTS
AS
SELECT AR.*,
       A.NAME AS ACTION_NAME,
       I.NAME AS REPORT_NAME,
       R.REPORT_TYPE
  FROM /*PREFIX*/ACTION_REPORTS AR
  JOIN /*PREFIX*/ACTIONS A ON A.ACTION_ID=AR.ACTION_ID
  JOIN /*PREFIX*/REPORTS R ON R.REPORT_ID=AR.REPORT_ID			
  JOIN /*PREFIX*/INTERFACES I ON I.INTERFACE_ID=R.REPORT_ID

--

/* Создание процедуры добавления отчета действию */

CREATE PROCEDURE /*PREFIX*/I_ACTION_REPORT
  @ACTION_ID VARCHAR(32),
  @REPORT_ID VARCHAR(32),
  @PRIORITY INTEGER
AS
BEGIN
  INSERT INTO /*PREFIX*/ACTION_REPORTS (ACTION_ID,REPORT_ID,PRIORITY)
       VALUES (@ACTION_ID,@REPORT_ID,@PRIORITY);
END;

--

/* Создание процедуры изменения отчета у действия */

CREATE PROCEDURE /*PREFIX*/U_ACTION_REPORT
  @ACTION_ID VARCHAR(32),
  @REPORT_ID VARCHAR(32),
  @PRIORITY INTEGER,
  @OLD_ACTION_ID VARCHAR(32),
  @OLD_REPORT_ID VARCHAR(32)
AS
BEGIN
  UPDATE /*PREFIX*/ACTION_REPORTS
     SET ACTION_ID=@ACTION_ID,
         REPORT_ID=@REPORT_ID,
         PRIORITY=@PRIORITY
   WHERE ACTION_ID=@OLD_ACTION_ID
     AND REPORT_ID=@OLD_REPORT_ID;
END;

--

/* Создание процедуры удаления отчета у действия */

CREATE PROCEDURE /*PREFIX*/D_ACTION_REPORT
  @OLD_ACTION_ID VARCHAR(32),
  @OLD_REPORT_ID VARCHAR(32)
AS
BEGIN
  DELETE FROM /*PREFIX*/ACTION_REPORTS 
        WHERE ACTION_ID=@OLD_ACTION_ID
          AND REPORT_ID=@OLD_REPORT_ID;
END;

--