/* Создание просмотра таблицы новых дел, имеющих задание */

CREATE VIEW /*PREFIX*/S_NEW_DEALS
AS
   SELECT T.TASK_ID,
          T.DATE_CREATE,
          T.DATE_BEGIN,
          T.ACCOUNT_ID,
          T.RESULT_ID,
          D.DEAL_ID,
          D.DEAL_NUM,
          D.ACCOUNT_NUM,
          D.ARREAR_PERIOD,
          D.INITIAL_DEBT,
          D.DEBTOR_NUM,
          D.DEBTOR_DATE,
          D.GROUP_ID,
          A.ACTION_ID,
          A.NAME AS ACTION_NAME,
          A.PURPOSE,
          AR.AGREEMENT_ID,
          F.FIRM_ID,
          F.SMALL_NAME AS FIRM_SMALL_NAME,
          DB.DEBTOR_ID,
          DB.SURNAME,
          DB.NAME,
          DB.PATRONYMIC,
          DB.ADDRESS_RESIDENCE,
          DB.ADDRESS_ACTUAL,
          DB.ADDRESS_ADDITIONAL,
          DB.ADDRESS_WORK,
          V.VARIANT_ID,
          C.CURRENCY_ID, 
          C.NAME AS CURRENCY_NAME,
          (CASE  
             WHEN P1.AMOUNT IS NULL THEN D.INITIAL_DEBT
             ELSE D.INITIAL_DEBT-P1.AMOUNT
           END) AS CURRENT_DEBT
     FROM /*PREFIX*/TASKS T
     JOIN /*PREFIX*/DEALS D ON D.DEAL_ID=T.DEAL_ID
     JOIN /*PREFIX*/ACTIONS A ON A.ACTION_ID=T.ACTION_ID
     JOIN /*PREFIX*/DEBTORS DB ON DB.DEBTOR_ID=D.DEBTOR_ID
     JOIN /*PREFIX*/AGREEMENTS AR ON AR.AGREEMENT_ID=D.AGREEMENT_ID
     JOIN /*PREFIX*/FIRMS F ON F.FIRM_ID=AR.FIRM_ID
     JOIN /*PREFIX*/VARIANTS V ON V.VARIANT_ID=AR.VARIANT_ID
     JOIN /*PREFIX*/CURRENCY C ON C.CURRENCY_ID=V.CURRENCY_ID
     LEFT JOIN (SELECT DEAL_ID, SUM(AMOUNT) AS AMOUNT 
                  FROM /*PREFIX*/PAYMENTS WHERE STATE=1
                 GROUP BY DEAL_ID)AS P1 ON P1.DEAL_ID=D.DEAL_ID    
    WHERE T.RESULT_ID IS NULL
      AND D.DATE_CLOSE IS NULL
      AND T.DATE_CREATE<=CURRENT_TIMESTAMP     
      AND (SELECT COUNT(*) FROM /*PREFIX*/TASKS T2 WHERE T2.DEAL_ID=T.DEAL_ID)=1 


--

