/* Создание просмотра таблицы ???? */

CREATE VIEW S_DEBTOR_STATIONS
 AS SELECT 
  DB.SURNAME AS SURNAME,
  DB.NAME AS NAME,
  DB.PATRONYMIC AS PATRONYMIC, 
  DB.DATE_BIRTH AS DATE_BIRTH,
  DB.PASSPORT AS PASSPORT,
  DB.INDEX_RESIDENCE AS INDEX_RESIDENCE,
  DB.ADDRESS_RESIDENCE AS ADDRESS_RESIDENCE,
  DB.INDEX_ACTUAL AS INDEX_ACTUAL,
  DB.ADDRESS_ACTUAL AS ADDRESS_ACTUAL,
  DB.PLACE_WORK AS PLACE_WORK,
  DB.INDEX_WORK AS INDEX_WORK,  
  DB.ADDRESS_WORK AS ADDRESS_WORK,
  DB.PHONE_HOME AS PHONE_HOME,
  DB.PHONE_WORK AS PHONE_WORK,
  DB.PHONE_MOBILE AS PHONE_MOBILE,
          (CASE 
             WHEN P1.AMOUNT IS NULL THEN D.INITIAL_DEBT
             ELSE D.INITIAL_DEBT-P1.AMOUNT
           END) AS DEBT,
  DATEDIFF(DAY, D.DATE_ISSUE, CURRENT_TIMESTAMP) AS DAYS_DEBT, 
  D.DATE_ISSUE AS DATE_ISSUE
     FROM /*PREFIX*/DEALS D
     JOIN  DEBTORS DB ON DB.DEBTOR_ID=D.DEBTOR_ID
     LEFT JOIN (SELECT DEAL_ID, SUM(AMOUNT) AS AMOUNT 
                  FROM /*PREFIX*/PAYMENTS WHERE STATE=1
                 GROUP BY DEAL_ID)AS P1 ON P1.DEAL_ID=D.DEAL_ID


--

