/* Создание просмотра реестра писем */

CREATE VIEW /*PREFIX*/S_ROLL_LETTERS
AS
 SELECT D.DEAL_ID,
        D.ACCOUNT_NUM,
        DB.SURNAME, 
        DB.NAME,
        DB.PATRONYMIC,
        DB.DATE_BIRTH,
        DATEADD(DAY,-D1.DEBT_PERIOD,CURRENT_TIMESTAMP) AS DATE_DEBT,
        DB.ADDRESS_RESIDENCE,
        (CASE  
          WHEN P1.AMOUNT IS NULL THEN D.INITIAL_DEBT
          ELSE D.INITIAL_DEBT-P1.AMOUNT
         END) AS CURRENT_DEBT, 
        C.NAME AS CURRENCY_NAME
     FROM /*PREFIX*/DEALS D
     JOIN /*PREFIX*/DEBTORS DB ON DB.DEBTOR_ID=D.DEBTOR_ID
     JOIN /*PREFIX*/AGREEMENTS A ON A.AGREEMENT_ID=D.AGREEMENT_ID
     JOIN /*PREFIX*/VARIANTS V ON V.VARIANT_ID=A.VARIANT_ID
     JOIN /*PREFIX*/CURRENCY C ON C.CURRENCY_ID=V.CURRENCY_ID
     JOIN (SELECT DEAL_ID, 
                  ARREAR_PERIOD+DATEDIFF(DAY,DATE_ISSUE,CURRENT_TIMESTAMP) AS DEBT_PERIOD 
            FROM /*PREFIX*/DEALS) AS D1 ON D1.DEAL_ID=D.DEAL_ID
     LEFT JOIN (SELECT DEAL_ID, 
                       SUM(AMOUNT) AS AMOUNT 
                  FROM /*PREFIX*/PAYMENTS 
                 WHERE STATE=1
                 GROUP BY DEAL_ID) AS P1 ON P1.DEAL_ID=D.DEAL_ID    

--

