/* Создание просмотра конвретов */

CREATE VIEW /*PREFIX*/S_ENVELOPES
AS
 SELECT D.DEAL_ID,
        DB.SURNAME, 
        DB.NAME,
        DB.PATRONYMIC,
        DB.ADDRESS_RESIDENCE,
        DB.INDEX_RESIDENCE,
        DB.ADDRESS_ACTUAL,
        DB.INDEX_ACTUAL,
        DB.ADDRESS_ADDITIONAL,
        DB.INDEX_ADDITIONAL, 
        DB.ADDRESS_WORK,
        DB.INDEX_WORK,
        C.SURNAME_DP,
        C.NAME_DP,
        C.PATRONYMIC_DP
     FROM /*PREFIX*/DEALS D
     JOIN /*PREFIX*/DEBTORS DB ON DB.DEBTOR_ID=D.DEBTOR_ID
     LEFT JOIN /*PREFIX*/CASES C ON C.SURNAME_IP=DB.SURNAME AND C.NAME_IP=DB.NAME AND C.PATRONYMIC_IP=DB.PATRONYMIC

--

