/* Создание просмотра требований */

CREATE VIEW /*PREFIX*/S_REQUIREMENTS
AS
 SELECT D.DEAL_ID,
        D.DEBTOR_NUM,
        D.DEBTOR_DATE, 
        D.ACCOUNT_NUM,
        DB.SURNAME, 
        DB.NAME,
        DB.SEX,
        DB.PATRONYMIC,
        DB.ADDRESS_RESIDENCE,
        DB.INDEX_RESIDENCE,
        DB.ADDRESS_ACTUAL,
        DB.INDEX_ACTUAL,
        DB.ADDRESS_ADDITIONAL,
        DB.INDEX_ADDITIONAL, 
        DB.ADDRESS_WORK,
        DB.INDEX_WORK,
        F.SMALL_NAME AS FIRM_SMALL_NAME,
        F.FULL_NAME AS FIRM_FULL_NAME,
        F.BANK AS FIRM_BANK,
        F.INN AS FIRM_INN,
        F.CORR_ACCOUNT  AS FIRM_CORR_ACCOUNT,
        F.BIK AS FIRM_BIK,
        F.LEGAL_ADDRESS AS FIRM_LEGAL_ADDRESS,
        F.LEGAL_INDEX AS FIRM_LEGAL_INDEX,
        F.PHONE AS FIRM_PHONE,
        F.FIRM_TYPE_ID,
        FT.NAME AS FIRM_TYPE_NAME,
        C.NAME AS CURRENCY_NAME,
        (CASE 
           WHEN P1.AMOUNT IS NULL THEN D.INITIAL_DEBT
           ELSE D.INITIAL_DEBT-P1.AMOUNT
         END) AS DEBT,
        (CASE 
           WHEN P1.DATE_PAYMENT IS NULL THEN D.DATE_ISSUE
           ELSE P1.DATE_PAYMENT
         END) AS DATE_DEBT   

     FROM /*PREFIX*/DEALS D
     JOIN /*PREFIX*/DEBTORS DB ON DB.DEBTOR_ID=D.DEBTOR_ID
     JOIN /*PREFIX*/AGREEMENTS A ON A.AGREEMENT_ID=D.AGREEMENT_ID
     JOIN /*PREFIX*/FIRMS F ON F.FIRM_ID=A.FIRM_ID
     JOIN /*PREFIX*/FIRM_TYPES FT ON FT.FIRM_TYPE_ID=F.FIRM_TYPE_ID
     JOIN /*PREFIX*/VARIANTS V ON V.VARIANT_ID=A.VARIANT_ID
     JOIN /*PREFIX*/CURRENCY C ON C.CURRENCY_ID=V.CURRENCY_ID
     LEFT JOIN (SELECT DEAL_ID, 
                       SUM(AMOUNT) AS AMOUNT,
                       MAX(DATE_PAYMENT) AS DATE_PAYMENT
                  FROM /*PREFIX*/PAYMENTS 
                 WHERE STATE=1
                 GROUP BY DEAL_ID) AS P1 ON P1.DEAL_ID=D.DEAL_ID

--

