/* Создание процедуры установки блокировки задания 2 */

CREATE PROCEDURE /*PREFIX*/LOCK_TASK2
  @ACCOUNT_ID VARCHAR(32),
  @TASK_ID VARCHAR(32),
  @LOCKED INTEGER OUT
AS
BEGIN
  DECLARE @AACCOUNT_ID VARCHAR(32);
  BEGIN TRANSACTION;
  SET @LOCKED=0;
  SET @AACCOUNT_ID=(SELECT ACCOUNT_ID FROM /*PREFIX*/TASKS T
                     WHERE T.TASK_ID=@TASK_ID);
  IF (@AACCOUNT_ID IS NULL) BEGIN
    UPDATE /*PREFIX*/TASKS
       SET ACCOUNT_ID=@ACCOUNT_ID,
           DATE_BEGIN=GETDATE()
     WHERE TASK_ID=@TASK_ID; 
    SET @LOCKED=1;
  END;
  COMMIT TRANSACTION;
END;


--
