/* Создание процедуры установки блокировки задания */

CREATE PROCEDURE /*PREFIX*/LOCK_TASK
  @ACCOUNT_ID VARCHAR(32),
  @PURPOSE INTEGER,
  @DATE_CREATE DATETIME,
  @TASK_ID VARCHAR(32) OUTPUT
AS
BEGIN
  IF (@ACCOUNT_ID IS NOT NULL) BEGIN
    BEGIN TRANSACTION;
    IF (@DATE_CREATE IS NULL) BEGIN
      SET @DATE_CREATE=CURRENT_TIMESTAMP;
    END;
    SET @TASK_ID=(SELECT TOP 1 T.TASK_ID
                    FROM /*PREFIX*/TASKS T
                    JOIN /*PREFIX*/ACCOUNT_ACTIONS AA ON AA.ACTION_ID=T.ACTION_ID
                    JOIN /*PREFIX*/ACCOUNT_GROUPS AG ON AG.ACCOUNT_ID=AA.ACCOUNT_ID 
                    JOIN /*PREFIX*/DEALS D ON D.DEAL_ID=T.DEAL_ID AND D.GROUP_ID=AG.GROUP_ID
                    JOIN /*PREFIX*/ACTIONS A ON A.ACTION_ID=AA.ACTION_ID
                   WHERE AA.ACCOUNT_ID=@ACCOUNT_ID
                     AND (T.ACCOUNT_ID IS NULL OR T.ACCOUNT_ID=@ACCOUNT_ID)
                     AND T.RESULT_ID IS NULL
                     AND D.DATE_CLOSE IS NULL
                     AND T.DATE_CREATE<=@DATE_CREATE
                     AND A.PURPOSE=@PURPOSE
                   ORDER BY AG.PRIORITY, AA.PRIORITY, T.DATE_CREATE);
    IF (@TASK_ID IS NOT NULL) BEGIN
      UPDATE /*PREFIX*/TASKS
         SET ACCOUNT_ID=@ACCOUNT_ID,
             DATE_BEGIN=GETDATE()
       WHERE TASK_ID=@TASK_ID; 
    END;
    COMMIT TRANSACTION;
  END;
END

--
