/* Создание процедуры снятия блокировки задания 2 */

CREATE PROCEDURE /*PREFIX*/UNLOCK_TASK2
  @TASK_ID VARCHAR(32),
  @UNLOCKED INTEGER OUT
AS
BEGIN
  DECLARE @AACCOUNT_ID VARCHAR(32);
  BEGIN TRANSACTION;
  SET @UNLOCKED=0;
  SET @AACCOUNT_ID=(SELECT ACCOUNT_ID FROM /*PREFIX*/TASKS T
                     WHERE T.TASK_ID=@TASK_ID);
  IF (@AACCOUNT_ID IS NOT NULL) BEGIN
    UPDATE /*PREFIX*/TASKS
       SET ACCOUNT_ID=NULL,
           RESULT_ID=NULL,
           DATE_BEGIN=NULL,
           PERFORMER_ID=NULL
     WHERE TASK_ID=@TASK_ID; 
    SET @UNLOCKED=1;
  END;
  COMMIT TRANSACTION;
END;

--
