/* Изменение процедуры добавления кредитного дела */

ALTER PROCEDURE /*PREFIX*/I_DEAL
  @DEAL_ID VARCHAR(32),
  @PLAN_ID VARCHAR(32),
  @GROUP_ID VARCHAR(32),
  @AGREEMENT_ID VARCHAR(32),
  @DEBTOR_ID VARCHAR(32),
  @DEAL_NUM VARCHAR(100),
  @DATE_ISSUE DATETIME,
  @DATE_CLOSE DATETIME,
  @ACCOUNT_NUM VARCHAR(100),
  @ARREAR_PERIOD INTEGER,
  @INITIAL_DEBT FLOAT,
  @DEBT_INFORMATION IMAGE,
  @GUARANTORS IMAGE,
  @DEBTOR_NUM VARCHAR(100),
  @DEBTOR_DATE DATETIME
AS
BEGIN
  DECLARE @ACTION_ID VARCHAR(32);

  INSERT INTO /*PREFIX*/DEALS (DEAL_ID,PLAN_ID,GROUP_ID,AGREEMENT_ID,DEBTOR_ID,
                               DEAL_NUM,DATE_ISSUE,DATE_CLOSE,ACCOUNT_NUM,ARREAR_PERIOD,
                               INITIAL_DEBT,DEBT_INFORMATION,GUARANTORS,DEBTOR_NUM,DEBTOR_DATE)
       VALUES (@DEAL_ID,@PLAN_ID,@GROUP_ID,@AGREEMENT_ID,@DEBTOR_ID,
               @DEAL_NUM,@DATE_ISSUE,@DATE_CLOSE,@ACCOUNT_NUM,@ARREAR_PERIOD,
               @INITIAL_DEBT,@DEBT_INFORMATION,@GUARANTORS,@DEBTOR_NUM,@DEBTOR_DATE);

  IF NOT EXISTS(SELECT DEAL_ID FROM /*PREFIX*/TASKS WHERE DEAL_ID=@DEAL_ID) AND (@PLAN_ID IS NOT NULL) BEGIN
    IF EXISTS (SELECT ACTION_ID FROM /*PREFIX*/PLAN_ACTIONS WHERE PLAN_ID=@PLAN_ID) BEGIN
      SET @ACTION_ID=(SELECT TOP 1 ACTION_ID FROM /*PREFIX*/PLAN_ACTIONS 
                       WHERE PLAN_ID=@PLAN_ID ORDER BY PRIORITY);
      IF (@ACTION_ID IS NOT NULL) BEGIN
        INSERT INTO /*PREFIX*/TASKS (TASK_ID,DEAL_ID,ACTION_ID,DATE_CREATE)
             VALUES (DBO.GET_UNIQUE_ID(),@DEAL_ID,@ACTION_ID,GETDATE());
      END;
    END;
  END;
END;

--
