/* Изменение процедуры изменения кредитного дела */

ALTER PROCEDURE /*PREFIX*/U_DEAL
  @DEAL_ID VARCHAR(32),
  @PLAN_ID VARCHAR(32),
  @GROUP_ID VARCHAR(32),
  @AGREEMENT_ID VARCHAR(32),
  @DEBTOR_ID VARCHAR(32),
  @DEAL_NUM VARCHAR(100),
  @DATE_ISSUE DATETIME,
  @DATE_CLOSE DATETIME,
  @ACCOUNT_NUM VARCHAR(100),
  @ARREAR_PERIOD INTEGER,
  @INITIAL_DEBT FLOAT,
  @DEBT_INFORMATION IMAGE,
  @GUARANTORS IMAGE,
  @DEBTOR_NUM VARCHAR(100),
  @DEBTOR_DATE DATETIME,
  @OLD_DEAL_ID VARCHAR(32)
AS
BEGIN
  DECLARE @ACTION_ID VARCHAR(32);

  UPDATE /*PREFIX*/DEALS
     SET DEAL_ID=@DEAL_ID,
         PLAN_ID=@PLAN_ID,
         GROUP_ID=@GROUP_ID,
         AGREEMENT_ID=@AGREEMENT_ID,
         DEBTOR_ID=@DEBTOR_ID,
         DEAL_NUM=@DEAL_NUM,
         DATE_ISSUE=@DATE_ISSUE,
         DATE_CLOSE=@DATE_CLOSE,
         ACCOUNT_NUM=@ACCOUNT_NUM,
         ARREAR_PERIOD=@ARREAR_PERIOD,
         INITIAL_DEBT=@INITIAL_DEBT,
         DEBT_INFORMATION=@DEBT_INFORMATION,
         GUARANTORS=@GUARANTORS,
         DEBTOR_NUM=@DEBTOR_NUM,
         DEBTOR_DATE=@DEBTOR_DATE
   WHERE DEAL_ID=@OLD_DEAL_ID;


  IF NOT EXISTS(SELECT DEAL_ID FROM /*PREFIX*/TASKS WHERE DEAL_ID=@DEAL_ID) AND (@PLAN_ID IS NOT NULL) BEGIN
    IF EXISTS (SELECT ACTION_ID FROM /*PREFIX*/PLAN_ACTIONS WHERE PLAN_ID=@PLAN_ID) BEGIN
      SET @ACTION_ID=(SELECT TOP 1 ACTION_ID FROM /*PREFIX*/PLAN_ACTIONS 
                       WHERE PLAN_ID=@PLAN_ID ORDER BY PRIORITY);
      IF (@ACTION_ID IS NOT NULL) BEGIN
        INSERT INTO /*PREFIX*/TASKS (TASK_ID,DEAL_ID,ACTION_ID,DATE_CREATE)
             VALUES (DBO.GET_UNIQUE_ID(),@DEAL_ID,@ACTION_ID,GETDATE());
      END;
    END;
  END;
END;

--
