/* Изменение процедуры изменения должника */

ALTER PROCEDURE /*PREFIX*/U_DEBTOR
  @DEBTOR_ID VARCHAR(32),
  @DEBTOR_TYPE INTEGER,
  @SURNAME VARCHAR(100),
  @NAME VARCHAR(100),
  @PATRONYMIC VARCHAR(100),
  @PASSPORT VARCHAR(250),
  @SEX INTEGER,
  @DATE_BIRTH DATETIME,
  @PLACE_BIRTH VARCHAR(250), 
  @ADDRESS_RESIDENCE VARCHAR(250),
  @INDEX_RESIDENCE VARCHAR(10),
  @ADDRESS_ACTUAL VARCHAR(250),
  @INDEX_ACTUAL VARCHAR(10),
  @ADDRESS_ADDITIONAL VARCHAR(250),
  @INDEX_ADDITIONAL VARCHAR(10),
  @JOB_TITLE VARCHAR(250),
  @PLACE_WORK VARCHAR(250),
  @ADDRESS_WORK VARCHAR(250),
  @INDEX_WORK VARCHAR(10),
  @PHONE_HOME VARCHAR(20),
  @PHONE_WORK VARCHAR(20),
  @PHONE_MOBILE VARCHAR(20),
  @PHONE_OTHER1 VARCHAR(20),
  @PHONE_OTHER2 VARCHAR(20),
  @FOUNDERS IMAGE,
  @OLD_DEBTOR_ID VARCHAR(32)
AS
BEGIN
  INSERT INTO /*PREFIX*/HISTORIES (HISTORY_ID,DEBTOR_ID,DATE_HISTORY,DEBTOR_TYPE,SURNAME,
                                   NAME,PATRONYMIC,PASSPORT,SEX,DATE_BIRTH,
                                   PLACE_BIRTH,ADDRESS_RESIDENCE,INDEX_RESIDENCE,ADDRESS_ACTUAL,INDEX_ACTUAL,
                                   ADDRESS_ADDITIONAL,INDEX_ADDITIONAL,JOB_TITLE,PLACE_WORK,ADDRESS_WORK,
                                   INDEX_WORK,PHONE_HOME,PHONE_WORK,PHONE_MOBILE,PHONE_OTHER1,PHONE_OTHER2,
                                   FOUNDERS)
  SELECT DBO.GET_UNIQUE_ID(),DEBTOR_ID,CURRENT_TIMESTAMP,DEBTOR_TYPE,SURNAME,
         NAME,PATRONYMIC,PASSPORT,SEX,DATE_BIRTH,
         PLACE_BIRTH,ADDRESS_RESIDENCE,INDEX_RESIDENCE,ADDRESS_ACTUAL,INDEX_ACTUAL,
         ADDRESS_ADDITIONAL,INDEX_ADDITIONAL,JOB_TITLE,PLACE_WORK,ADDRESS_WORK,
         INDEX_WORK,PHONE_HOME,PHONE_WORK,PHONE_MOBILE,PHONE_OTHER1,PHONE_OTHER2,
         FOUNDERS 
    FROM /*PREFIX*/DEBTORS
   WHERE DEBTOR_ID=@OLD_DEBTOR_ID;

  UPDATE /*PREFIX*/DEBTORS
     SET DEBTOR_ID=@DEBTOR_ID,
         DEBTOR_TYPE=@DEBTOR_TYPE,
         SURNAME=@SURNAME,
         NAME=@NAME,
         PATRONYMIC=@PATRONYMIC,
         PASSPORT=@PASSPORT,
         SEX=@SEX,
         DATE_BIRTH=@DATE_BIRTH,
         PLACE_BIRTH=@PLACE_BIRTH,
         ADDRESS_RESIDENCE=@ADDRESS_RESIDENCE,
         INDEX_RESIDENCE=@INDEX_RESIDENCE,
         ADDRESS_ACTUAL=@ADDRESS_ACTUAL,
         INDEX_ACTUAL=@INDEX_ACTUAL,
         ADDRESS_ADDITIONAL=@ADDRESS_ADDITIONAL,
         INDEX_ADDITIONAL=@INDEX_ADDITIONAL,
         JOB_TITLE=@JOB_TITLE,
         PLACE_WORK=@PLACE_WORK,
         ADDRESS_WORK=@ADDRESS_WORK,
         INDEX_WORK=@INDEX_WORK,
         PHONE_HOME=@PHONE_HOME,
         PHONE_WORK=@PHONE_WORK,
         PHONE_MOBILE=@PHONE_MOBILE,
         PHONE_OTHER1=@PHONE_OTHER1,
         PHONE_OTHER2=@PHONE_OTHER2,
         FOUNDERS=@FOUNDERS
   WHERE DEBTOR_ID=@OLD_DEBTOR_ID;
END;

--
