/* Изменение процедуры удаления должника */

ALTER PROCEDURE /*PREFIX*/D_DEBTOR
  @OLD_DEBTOR_ID VARCHAR(32)
AS
BEGIN
  DELETE FROM /*PREFIX*/HISTORIES
        WHERE DEBTOR_ID=@OLD_DEBTOR_ID;

  DELETE FROM /*PREFIX*/DEBTORS
        WHERE DEBTOR_ID=@OLD_DEBTOR_ID;
END;

--
