/* Создание процедуры импорта должника */

CREATE PROCEDURE /*PREFIX*/IMPORT_DEBTOR
  @AGREEMENT_ID VARCHAR(32),
  @GROUP_ID VARCHAR(32),
  @PLAN_ID VARCHAR(32),
  @DATE_ISSUE DATETIME,
  @DEAL_NUM VARCHAR(100),
  @ACCOUNT_NUM VARCHAR(100),
  @ARREAR_PERIOD INTEGER,
  @INITIAL_DEBT FLOAT,
  @DEBT_INFORMATION IMAGE,
  @GUARANTORS IMAGE,
  @DEBTOR_NUM VARCHAR(100),
  @DEBTOR_DATE DATETIME,
  @DEBTOR_TYPE INTEGER,
  @SURNAME VARCHAR(100),
  @NAME VARCHAR(100),
  @PATRONYMIC VARCHAR(100),
  @PASSPORT VARCHAR(250),
  @SEX INTEGER, 
  @DATE_BIRTH DATETIME,
  @PLACE_BIRTH VARCHAR(250),
  @ADDRESS_RESIDENCE VARCHAR(250),
  @INDEX_RESIDENCE VARCHAR(10),
  @ADDRESS_ACTUAL VARCHAR(250),
  @INDEX_ACTUAL VARCHAR(10),
  @ADDRESS_ADDITIONAL VARCHAR(250),
  @INDEX_ADDITIONAL VARCHAR(10),
  @PLACE_WORK VARCHAR(250),
  @JOB_TITLE VARCHAR(250),
  @ADDRESS_WORK VARCHAR(250),
  @INDEX_WORK VARCHAR(10),
  @PHONE_HOME VARCHAR(20),
  @PHONE_WORK VARCHAR(20),
  @PHONE_MOBILE VARCHAR(20),
  @PHONE_OTHER1 VARCHAR(20),
  @PHONE_OTHER2 VARCHAR(20),
  @FOUNDERS IMAGE,
  @DEAL_ID VARCHAR(32) OUT
AS
BEGIN
  DECLARE @DEBTOR_ID VARCHAR(32);

  SET @DEBTOR_ID=(SELECT TOP 1 DEBTOR_ID FROM /*PREFIX*/DEBTORS 
                   WHERE DEBTOR_TYPE=@DEBTOR_TYPE
                     AND SURNAME=@SURNAME
                     AND NAME=@NAME
                     AND PATRONYMIC=@PATRONYMIC
                     AND SEX=@SEX
                     AND DATE_BIRTH=@DATE_BIRTH
                     AND PLACE_BIRTH=@PLACE_BIRTH);

  IF (@DEBTOR_ID IS NULL) BEGIN

    SET @DEBTOR_ID=DBO.GET_UNIQUE_ID();

    EXEC /*PREFIX*/I_DEBTOR @DEBTOR_ID,@DEBTOR_TYPE,@SURNAME,@NAME,@PATRONYMIC,@PASSPORT,@SEX,@DATE_BIRTH,
                            @PLACE_BIRTH,@ADDRESS_RESIDENCE,@INDEX_RESIDENCE,@ADDRESS_ACTUAL,@INDEX_ACTUAL,
                            @ADDRESS_ADDITIONAL,@INDEX_ADDITIONAL,@JOB_TITLE,@PLACE_WORK,@ADDRESS_WORK,
                            @INDEX_WORK,@PHONE_HOME,@PHONE_WORK,@PHONE_MOBILE,@PHONE_OTHER1,@PHONE_OTHER2,
                            @FOUNDERS;
  END ELSE BEGIN
    EXEC /*PREFIX*/U_DEBTOR @DEBTOR_ID,@DEBTOR_TYPE,@SURNAME,@NAME,@PATRONYMIC,@PASSPORT,@SEX,@DATE_BIRTH,
                            @PLACE_BIRTH,@ADDRESS_RESIDENCE,@INDEX_RESIDENCE,@ADDRESS_ACTUAL,@INDEX_ACTUAL,
                            @ADDRESS_ADDITIONAL,@INDEX_ADDITIONAL,@JOB_TITLE,@PLACE_WORK,@ADDRESS_WORK,
                            @INDEX_WORK,@PHONE_HOME,@PHONE_WORK,@PHONE_MOBILE,@PHONE_OTHER1,@PHONE_OTHER2,
                            @FOUNDERS,@DEBTOR_ID;
  END;

  
  SET @DEAL_ID=(SELECT TOP 1 DEAL_ID FROM /*PREFIX*/DEALS
                 WHERE DEBTOR_ID=@DEBTOR_ID
                   AND AGREEMENT_ID=@AGREEMENT_ID
                   AND ACCOUNT_NUM=@ACCOUNT_NUM);

  IF (@DEAL_ID IS NULL) BEGIN
  
    SET @DEAL_ID=DBO.GET_UNIQUE_ID();

    EXEC /*PREFIX*/I_DEAL @DEAL_ID,@PLAN_ID,@GROUP_ID,@AGREEMENT_ID,@DEBTOR_ID,
                          @DEAL_NUM,@DATE_ISSUE,NULL,@ACCOUNT_NUM,@ARREAR_PERIOD,
                          @INITIAL_DEBT,@DEBT_INFORMATION,@GUARANTORS,@DEBTOR_NUM,@DEBTOR_DATE;
  END ELSE BEGIN
    RAISERROR('Найдено кредитное дело по счету: %s, но что дальше с ним делать???',16,1,@ACCOUNT_NUM); 
    RETURN;
  END;
END;

--
