/* Создание процедуры импорта падежей */

CREATE PROCEDURE /*PREFIX*/IMPORT_CASE
  @SURNAME_IP VARCHAR(100),
  @NAME_IP VARCHAR(100),
  @PATRONYMIC_IP VARCHAR(100),

  @SURNAME_RP VARCHAR(100),
  @NAME_RP VARCHAR(100),
  @PATRONYMIC_RP VARCHAR(100),

  @SURNAME_DP VARCHAR(100),
  @NAME_DP VARCHAR(100),
  @PATRONYMIC_DP VARCHAR(100),

  @SURNAME_VP VARCHAR(100),
  @NAME_VP VARCHAR(100),
  @PATRONYMIC_VP VARCHAR(100),

  @SURNAME_TP VARCHAR(100),
  @NAME_TP VARCHAR(100),
  @PATRONYMIC_TP VARCHAR(100),

  @SURNAME_PP VARCHAR(100),
  @NAME_PP VARCHAR(100),
  @PATRONYMIC_PP VARCHAR(100)
AS
BEGIN
  IF NOT EXISTS(SELECT * FROM CASES 
                 WHERE SURNAME_IP=@SURNAME_IP
                   AND NAME_IP=@NAME_IP
                   AND PATRONYMIC_IP=@PATRONYMIC_IP) BEGIN

    EXEC I_CASE @SURNAME_IP,@NAME_IP,@PATRONYMIC_IP,
                @SURNAME_RP,@NAME_RP,@PATRONYMIC_RP,
                @SURNAME_DP,@NAME_DP,@PATRONYMIC_DP,
                @SURNAME_VP,@NAME_VP,@PATRONYMIC_VP,
                @SURNAME_TP,@NAME_TP,@PATRONYMIC_TP,
                @SURNAME_PP,@NAME_PP,@PATRONYMIC_PP;
  END;
END;


--
