/* Создание процедуры применения плана */

CREATE PROCEDURE /*PREFIX*/APPLY_PLAN
  @TASK_ID VARCHAR(32),
  @PLAN_ID VARCHAR(32)
AS
BEGIN
  DECLARE @ACTION_ID VARCHAR(32);
  DECLARE @ACCOUNT_ID VARCHAR(32);

  IF (@TASK_ID IS NOT NULL) AND (@PLAN_ID IS NOT NULL) BEGIN

    IF EXISTS (SELECT ACTION_ID FROM /*PREFIX*/PLAN_ACTIONS WHERE PLAN_ID=@PLAN_ID) BEGIN

      SET @ACTION_ID=(SELECT TOP 1 ACTION_ID FROM /*PREFIX*/PLAN_ACTIONS 
                       WHERE PLAN_ID=@PLAN_ID ORDER BY PRIORITY);

      SET @ACCOUNT_ID=(SELECT ACCOUNT_ID FROM /*PREFIX*/TASKS WHERE TASK_ID=@TASK_ID);

      IF (@ACTION_ID IS NOT NULL) AND (@ACCOUNT_ID IS NULL) BEGIN
        
        UPDATE /*PREFIX*/TASKS 
           SET ACTION_ID=@ACTION_ID,
               DATE_CREATE=GETDATE(),
               ACCOUNT_ID=NULL,
               RESULT_ID=NULL,
               DATE_BEGIN=NULL,
               PERFORMER_ID=NULL
         WHERE TASK_ID=@TASK_ID

      END;
    END;
  END;

END;



--
