/* Создание процедуры применения группы */

CREATE PROCEDURE /*PREFIX*/APPLY_GROUP
  @TASK_ID VARCHAR(32),
  @GROUP_ID VARCHAR(32)
AS
BEGIN
  DECLARE @DEAL_ID VARCHAR(32);

  IF (@TASK_ID IS NOT NULL) AND (@GROUP_ID IS NOT NULL) BEGIN

    SET @DEAL_ID=(SELECT DEAL_ID FROM /*PREFIX*/TASKS WHERE TASK_ID=@TASK_ID);

    IF (@DEAL_ID IS NOT NULL) BEGIN
        
      UPDATE /*PREFIX*/DEALS
         SET GROUP_ID=@GROUP_ID
       WHERE DEAL_ID=@DEAL_ID

    END;
  END;

END;


--
