/* Создание процедуры расчета вознаграждения с фиксированной частью */

CREATE PROCEDURE /*PREFIX*/CALC_FIXED_ROUBLE
  @AGREEMENT_ID VARCHAR(32),
  @DATE_BEGIN DATETIME,
  @DATE_END DATETIME
AS
BEGIN
  SET NOCOUNT ON;
  
  DECLARE @DEBTOR_NUM VARCHAR(100),
          @DATE_DEBT DATETIME,
          @DEBTOR_NAME VARCHAR(300),
          @DEBT_PERIOD INTEGER,
          @AMOUNT_ARRIVAL FLOAT,
          @COST_SERVICE FLOAT,
          @FIXED_PART FLOAT,
          @VARIABLE_PART FLOAT,
          @AMOUNT_REMUNERATION FLOAT,
          @MAX_DATE DATETIME,
          @MIN_DATE DATETIME,
          @AMOUNT_BEFORE FLOAT;

  CREATE TABLE #CALC_FIXED_ROUBLE
  (
    DEBTOR_NUM VARCHAR(100),
    DATE_DEBT DATETIME,
    DEBTOR_NAME VARCHAR(300),
    DEBT_PERIOD INTEGER,
    AMOUNT_ARRIVAL FLOAT,
    COST_SERVICE FLOAT,
    FIXED_PART FLOAT,
    VARIABLE_PART FLOAT,
    AMOUNT_REMUNERATION FLOAT
  );
  
  SELECT @MIN_DATE=MIN(DATE_PAYMENT), @MAX_DATE=MAX(DATE_PAYMENT) 
    FROM /*PREFIX*/PAYMENTS
   WHERE STATE=1
     AND DEAL_ID IN (SELECT DEAL_ID FROM /*PREFIX*/DEALS 
                      WHERE AGREEMENT_ID=@AGREEMENT_ID
                        AND DATE_CLOSE IS NULL);

  IF (@DATE_BEGIN IS NOT NULL) SET @MIN_DATE=@DATE_BEGIN;

  IF (@DATE_END IS NOT NULL) SET @MAX_DATE=@DATE_END;

  DECLARE CUR CURSOR  
      FOR SELECT D.DEBTOR_NUM,
                 DATEADD(DAY,-D1.DEBT_PERIOD,CURRENT_TIMESTAMP) AS DATE_DEBT, 
                 DB.SURNAME+' '+DB.NAME+' '+DB.PATRONYMIC AS DEBTOR_NAME,
                 D1.DEBT_PERIOD AS DEBT_PERIOD,
                 (CASE 
                    WHEN P1.AMOUNT IS NULL THEN 0
                    ELSE P1.AMOUNT
                  END) AS AMOUNT_ARRIVAL,
                 (CASE 
                   WHEN D1.DEBT_PERIOD<=60 THEN 9
                   WHEN (D1.DEBT_PERIOD>60) AND (D1.DEBT_PERIOD<=90) THEN 12
                   WHEN (D1.DEBT_PERIOD>90) AND (D1.DEBT_PERIOD<=120) THEN 16
                   WHEN (D1.DEBT_PERIOD>120) AND (D1.DEBT_PERIOD<=180) THEN 20
                   ELSE 25
                  END) AS COST_SERVICE,
                 (CASE 
                    WHEN P2.AMOUNT IS NULL THEN 0
                    ELSE P2.AMOUNT
                  END) AS AMOUNT_BEFORE
  
            FROM /*PREFIX*/DEALS D
            JOIN /*PREFIX*/DEBTORS DB ON DB.DEBTOR_ID=D.DEBTOR_ID
            JOIN (SELECT DEAL_ID, ARREAR_PERIOD+DATEDIFF(DAY,DATE_ISSUE,CURRENT_TIMESTAMP) AS DEBT_PERIOD 
                    FROM /*PREFIX*/DEALS) AS D1 ON D1.DEAL_ID=D.DEAL_ID
            LEFT JOIN (SELECT DEAL_ID, SUM(AMOUNT) AS AMOUNT 
                         FROM /*PREFIX*/PAYMENTS 
                        WHERE STATE=1
                          AND DATE_PAYMENT>=@MIN_DATE 
                          AND DATE_PAYMENT<=@MAX_DATE 
                        GROUP BY DEAL_ID)AS P1 ON P1.DEAL_ID=D.DEAL_ID
            LEFT JOIN (SELECT DEAL_ID, SUM(AMOUNT) AS AMOUNT 
                         FROM /*PREFIX*/PAYMENTS 
                        WHERE STATE=1
                          AND DATE_PAYMENT<@MIN_DATE 
                        GROUP BY DEAL_ID)AS P2 ON P2.DEAL_ID=D.DEAL_ID
           WHERE D.AGREEMENT_ID=@AGREEMENT_ID
             AND D.DATE_CLOSE IS NULL 
      FOR READ ONLY;

  OPEN CUR;

  FETCH NEXT FROM CUR
  INTO @DEBTOR_NUM,@DATE_DEBT,@DEBTOR_NAME,@DEBT_PERIOD,@AMOUNT_ARRIVAL,
       @COST_SERVICE,@AMOUNT_BEFORE;

  WHILE @@FETCH_STATUS=0 BEGIN
    
    IF (@AMOUNT_ARRIVAL>0.0) BEGIN

      SET @FIXED_PART=0.0; 
     
      IF (@AMOUNT_ARRIVAL>=1000.0) AND (@AMOUNT_BEFORE<1000.0) BEGIN
        SET @FIXED_PART=300.0;   
      END;

      SET @VARIABLE_PART=@AMOUNT_ARRIVAL*@COST_SERVICE/100;

      SET @AMOUNT_REMUNERATION=@FIXED_PART+@VARIABLE_PART;

      INSERT INTO #CALC_FIXED_ROUBLE (DEBTOR_NUM,DATE_DEBT,DEBTOR_NAME,DEBT_PERIOD,AMOUNT_ARRIVAL,
                                      COST_SERVICE,FIXED_PART,VARIABLE_PART,AMOUNT_REMUNERATION)
           VALUES (@DEBTOR_NUM,@DATE_DEBT,@DEBTOR_NAME,@DEBT_PERIOD,@AMOUNT_ARRIVAL,
                   @COST_SERVICE,@FIXED_PART,@VARIABLE_PART,@AMOUNT_REMUNERATION);
    END;

    FETCH NEXT FROM CUR 
    INTO @DEBTOR_NUM,@DATE_DEBT,@DEBTOR_NAME,@DEBT_PERIOD,@AMOUNT_ARRIVAL,
         @COST_SERVICE,@AMOUNT_BEFORE;
  END;

  CLOSE CUR;
  DEALLOCATE CUR;

  SET NOCOUNT OFF;

  SELECT * FROM #CALC_FIXED_ROUBLE
   ORDER BY DEBTOR_NAME;

  DROP TABLE #CALC_FIXED_ROUBLE; 
END;

--
