/* Создание процедуры подсчета затрат рабочего времени */

CREATE PROCEDURE /*PREFIX*/EXPENSESES_UPTIME
  @ACCOUNT_ID VARCHAR(32),
  @DATE_BEGIN DATETIME,
  @DATE_END DATETIME
AS
BEGIN
  DECLARE @MIN_DATE DATETIME,
          @MAX_DATE DATETIME;
 
  SELECT @MIN_DATE=MIN(CONVERT(DATETIME,CONVERT(VARCHAR(10),DATE_BEGIN,104),104)), 
         @MAX_DATE=MAX(CONVERT(DATETIME,CONVERT(VARCHAR(10),DATE_BEGIN,104),104)) 
    FROM /*PREFIX*/TASKS
   WHERE PERFORMER_ID=@ACCOUNT_ID
     AND RESULT_ID IS NOT NULL;

  IF (@DATE_BEGIN IS NOT NULL) SET @MIN_DATE=@DATE_BEGIN;

  IF (@DATE_END IS NOT NULL) SET @MAX_DATE=@DATE_END;

  SELECT T.DATE_WORK,
         T.DATE_BEGIN,
         T.DATE_END,
         DATEADD(SS,T.TIME_WORK,0) AS TIME_WORK,
         DATEADD(SS,DATEDIFF(SS,T.DATE_BEGIN,T.DATE_END)-T.TIME_WORK,0) AS TIME_INTERVAL,
         T.TASK_COUNT            
    FROM (SELECT CONVERT(DATETIME,CONVERT(VARCHAR(10),DATE_BEGIN,104),104) AS DATE_WORK,
                 MIN(T.DATE_BEGIN) AS DATE_BEGIN, 
                 MAX(T.DATE_END) AS DATE_END, 
                 SUM(DATEDIFF(SS,T.DATE_BEGIN,T.DATE_END)) AS TIME_WORK,
                 COUNT(*) AS TASK_COUNT
            FROM /*PREFIX*/TASKS T
           WHERE T.PERFORMER_ID=@ACCOUNT_ID
             AND T.RESULT_ID IS NOT NULL
             AND CONVERT(DATETIME,CONVERT(VARCHAR(10),DATE_BEGIN,104),104)>=@MIN_DATE
             AND CONVERT(DATETIME,CONVERT(VARCHAR(10),DATE_BEGIN,104),104)<=@MAX_DATE 
      GROUP BY CONVERT(DATETIME,CONVERT(VARCHAR(10),DATE_BEGIN,104),104)) T
   ORDER BY T.DATE_WORK;
END;

--
