/* Создание процедуры анализа деятельности */

CREATE PROCEDURE /*PREFIX*/ANALYSIS_ACTIVITY
  @AGREEMENT_ID VARCHAR(32),
  @DATE_BEGIN DATETIME,
  @DATE_END DATETIME
AS
BEGIN
  DECLARE @MIN_DATE DATETIME,
          @MAX_DATE DATETIME;
 
  IF (@AGREEMENT_ID IS NOT NULL) BEGIN  
    SELECT @MIN_DATE=MIN(CONVERT(DATETIME,CONVERT(VARCHAR(10),T.DATE_BEGIN,104),104)), 
           @MAX_DATE=MAX(CONVERT(DATETIME,CONVERT(VARCHAR(10),T.DATE_BEGIN,104),104)) 
      FROM /*PREFIX*/TASKS T
      JOIN /*PREFIX*/DEALS D ON D.DEAL_ID=T.DEAL_ID
     WHERE T.RESULT_ID IS NOT NULL
       AND D.AGREEMENT_ID=@AGREEMENT_ID;
  END ELSE BEGIN
    SELECT @MIN_DATE=MIN(CONVERT(DATETIME,CONVERT(VARCHAR(10),T.DATE_BEGIN,104),104)), 
           @MAX_DATE=MAX(CONVERT(DATETIME,CONVERT(VARCHAR(10),T.DATE_BEGIN,104),104)) 
      FROM /*PREFIX*/TASKS T
     WHERE T.RESULT_ID IS NOT NULL;
  END;

  IF (@DATE_BEGIN IS NOT NULL) SET @MIN_DATE=@DATE_BEGIN;

  IF (@DATE_END IS NOT NULL) SET @MAX_DATE=@DATE_END;

  IF (@AGREEMENT_ID IS NOT NULL) BEGIN
    SELECT T.ACTION_ID,
           T.DATE_WORK,
           A.NAME AS ACTION_NAME,
           T.ACTION_COUNT
     FROM (SELECT T.ACTION_ID,  
                  CONVERT(DATETIME,CONVERT(VARCHAR(10),T.DATE_BEGIN,104),104) AS DATE_WORK,
                  COUNT(*) AS ACTION_COUNT
             FROM /*PREFIX*/TASKS T
             JOIN /*PREFIX*/DEALS D ON D.DEAL_ID=T.DEAL_ID
            WHERE T.RESULT_ID IS NOT NULL 
              AND CONVERT(DATETIME,CONVERT(VARCHAR(10),T.DATE_BEGIN,104),104)>=@MIN_DATE
              AND CONVERT(DATETIME,CONVERT(VARCHAR(10),T.DATE_BEGIN,104),104)<=@MAX_DATE          
              AND D.AGREEMENT_ID=@AGREEMENT_ID
            GROUP BY T.ACTION_ID, CONVERT(DATETIME,CONVERT(VARCHAR(10),T.DATE_BEGIN,104),104)) T
     JOIN ACTIONS A ON A.ACTION_ID=T.ACTION_ID
    ORDER BY T.DATE_WORK;
  END ELSE BEGIN
    SELECT T.ACTION_ID,
           T.DATE_WORK,
           A.NAME AS ACTION_NAME,
           T.ACTION_COUNT
     FROM (SELECT T.ACTION_ID,  
                  CONVERT(DATETIME,CONVERT(VARCHAR(10),T.DATE_BEGIN,104),104) AS DATE_WORK,
                  COUNT(*) AS ACTION_COUNT
             FROM /*PREFIX*/TASKS T
            WHERE T.RESULT_ID IS NOT NULL 
              AND CONVERT(DATETIME,CONVERT(VARCHAR(10),T.DATE_BEGIN,104),104)>=@MIN_DATE
              AND CONVERT(DATETIME,CONVERT(VARCHAR(10),T.DATE_BEGIN,104),104)<=@MAX_DATE          
            GROUP BY T.ACTION_ID, CONVERT(DATETIME,CONVERT(VARCHAR(10),T.DATE_BEGIN,104),104)) T
     JOIN ACTIONS A ON A.ACTION_ID=T.ACTION_ID
    ORDER BY T.DATE_WORK;
  END;
END;

--
