/* Создание процедуры подсчета характеристики заемщиков */

CREATE PROCEDURE /*PREFIX*/FEATURE_DEBTOR
  @AGREEMENT_ID VARCHAR(32),
  @DATE_BEGIN DATETIME,
  @DATE_END DATETIME
AS
BEGIN
  DECLARE @MIN_DATE DATETIME,
          @MAX_DATE DATETIME;

  IF (@AGREEMENT_ID IS NOT NULL) BEGIN 
    SELECT @MIN_DATE=MIN(DATE_ISSUE), @MAX_DATE=MAX(DATE_ISSUE) 
      FROM /*PREFIX*/DEALS
     WHERE DATE_CLOSE IS NULL
       AND AGREEMENT_ID=@AGREEMENT_ID;
  END ELSE BEGIN
    SELECT @MIN_DATE=MIN(DATE_ISSUE), @MAX_DATE=MAX(DATE_ISSUE) 
      FROM /*PREFIX*/DEALS
     WHERE DATE_CLOSE IS NULL;
  END;

  IF (@DATE_BEGIN IS NOT NULL) SET @MIN_DATE=@DATE_BEGIN;

  IF (@DATE_END IS NOT NULL) SET @MAX_DATE=@DATE_END;

  IF (@AGREEMENT_ID IS NOT NULL) BEGIN
    SELECT DB.SEX,
           D1.DEAL_COUNT AS AGE_30,
           D2.DEAL_COUNT AS AGE_31_45,
           D3.DEAL_COUNT AS AGE_46_60,
           D4.DEAL_COUNT AS AGE_61, 
           COUNT(*) AS DEAL_COUNT
      FROM /*PREFIX*/DEALS D
      JOIN /*PREFIX*/DEBTORS DB ON DB.DEBTOR_ID=D.DEBTOR_ID
      LEFT JOIN (SELECT DB.SEX, COUNT(*) AS DEAL_COUNT
                   FROM /*PREFIX*/ DEALS D
                   JOIN /*PREFIX*/DEBTORS DB ON DB.DEBTOR_ID=D.DEBTOR_ID
                  WHERE DATEDIFF(YY,DB.DATE_BIRTH,CURRENT_TIMESTAMP)<30
                    AND D.AGREEMENT_ID=@AGREEMENT_ID
                    AND D.DATE_ISSUE>=@MIN_DATE 
                    AND D.DATE_ISSUE<=@MAX_DATE 
                  GROUP BY DB.SEX) D1 ON D1.SEX=DB.SEX
      LEFT JOIN (SELECT DB.SEX, COUNT(*) AS DEAL_COUNT
                   FROM /*PREFIX*/ DEALS D
                   JOIN /*PREFIX*/DEBTORS DB ON DB.DEBTOR_ID=D.DEBTOR_ID
                  WHERE DATEDIFF(YY,DB.DATE_BIRTH,CURRENT_TIMESTAMP)>=31
                    AND DATEDIFF(YY,DB.DATE_BIRTH,CURRENT_TIMESTAMP)<=45
                    AND D.AGREEMENT_ID=@AGREEMENT_ID
                    AND D.DATE_ISSUE>=@MIN_DATE 
                    AND D.DATE_ISSUE<=@MAX_DATE 
                  GROUP BY DB.SEX) D2 ON D2.SEX=DB.SEX
      LEFT JOIN (SELECT DB.SEX, COUNT(*) AS DEAL_COUNT
                   FROM /*PREFIX*/ DEALS D
                   JOIN /*PREFIX*/DEBTORS DB ON DB.DEBTOR_ID=D.DEBTOR_ID
                  WHERE DATEDIFF(YY,DB.DATE_BIRTH,CURRENT_TIMESTAMP)>=46
                    AND DATEDIFF(YY,DB.DATE_BIRTH,CURRENT_TIMESTAMP)<=60
                    AND D.AGREEMENT_ID=@AGREEMENT_ID
                    AND D.DATE_ISSUE>=@MIN_DATE 
                    AND D.DATE_ISSUE<=@MAX_DATE 
                  GROUP BY DB.SEX) D3 ON D3.SEX=DB.SEX
      LEFT JOIN (SELECT DB.SEX, COUNT(*) AS DEAL_COUNT
                   FROM /*PREFIX*/ DEALS D
                   JOIN /*PREFIX*/DEBTORS DB ON DB.DEBTOR_ID=D.DEBTOR_ID
                  WHERE DATEDIFF(YY,DB.DATE_BIRTH,CURRENT_TIMESTAMP)>=61
                    AND D.AGREEMENT_ID=@AGREEMENT_ID
                    AND D.DATE_ISSUE>=@MIN_DATE 
                    AND D.DATE_ISSUE<=@MAX_DATE 
                  GROUP BY DB.SEX) D4 ON D4.SEX=DB.SEX
     WHERE D.AGREEMENT_ID=@AGREEMENT_ID
       AND D.DATE_ISSUE>=@MIN_DATE 
       AND D.DATE_ISSUE<=@MAX_DATE  
     GROUP BY DB.SEX, D1.DEAL_COUNT, D2.DEAL_COUNT, D3.DEAL_COUNT, D4.DEAL_COUNT
     ORDER BY DB.SEX;
  END ELSE BEGIN
    SELECT DB.SEX,
           D1.DEAL_COUNT AS AGE_30,
           D2.DEAL_COUNT AS AGE_31_45,
           D3.DEAL_COUNT AS AGE_46_60,
           D4.DEAL_COUNT AS AGE_61, 
           COUNT(*) AS DEAL_COUNT
      FROM /*PREFIX*/DEALS D
      JOIN /*PREFIX*/DEBTORS DB ON DB.DEBTOR_ID=D.DEBTOR_ID
      LEFT JOIN (SELECT DB.SEX, COUNT(*) AS DEAL_COUNT
                   FROM /*PREFIX*/ DEALS D
                   JOIN /*PREFIX*/DEBTORS DB ON DB.DEBTOR_ID=D.DEBTOR_ID
                  WHERE DATEDIFF(YY,DB.DATE_BIRTH,CURRENT_TIMESTAMP)<30
                    AND D.DATE_ISSUE>=@MIN_DATE 
                    AND D.DATE_ISSUE<=@MAX_DATE 
                  GROUP BY DB.SEX) D1 ON D1.SEX=DB.SEX
      LEFT JOIN (SELECT DB.SEX, COUNT(*) AS DEAL_COUNT
                   FROM /*PREFIX*/ DEALS D
                   JOIN /*PREFIX*/DEBTORS DB ON DB.DEBTOR_ID=D.DEBTOR_ID
                  WHERE DATEDIFF(YY,DB.DATE_BIRTH,CURRENT_TIMESTAMP)>=31
                    AND DATEDIFF(YY,DB.DATE_BIRTH,CURRENT_TIMESTAMP)<=45
                    AND D.DATE_ISSUE>=@MIN_DATE 
                    AND D.DATE_ISSUE<=@MAX_DATE 
                  GROUP BY DB.SEX) D2 ON D2.SEX=DB.SEX
      LEFT JOIN (SELECT DB.SEX, COUNT(*) AS DEAL_COUNT
                   FROM /*PREFIX*/ DEALS D
                   JOIN /*PREFIX*/DEBTORS DB ON DB.DEBTOR_ID=D.DEBTOR_ID
                  WHERE DATEDIFF(YY,DB.DATE_BIRTH,CURRENT_TIMESTAMP)>=46
                    AND DATEDIFF(YY,DB.DATE_BIRTH,CURRENT_TIMESTAMP)<=60
                    AND D.DATE_ISSUE>=@MIN_DATE 
                    AND D.DATE_ISSUE<=@MAX_DATE 
                  GROUP BY DB.SEX) D3 ON D3.SEX=DB.SEX
      LEFT JOIN (SELECT DB.SEX, COUNT(*) AS DEAL_COUNT
                   FROM /*PREFIX*/ DEALS D
                   JOIN /*PREFIX*/DEBTORS DB ON DB.DEBTOR_ID=D.DEBTOR_ID
                  WHERE DATEDIFF(YY,DB.DATE_BIRTH,CURRENT_TIMESTAMP)>=61
                    AND D.DATE_ISSUE>=@MIN_DATE 
                    AND D.DATE_ISSUE<=@MAX_DATE 
                  GROUP BY DB.SEX) D4 ON D4.SEX=DB.SEX
     WHERE D.DATE_ISSUE>=@MIN_DATE 
       AND D.DATE_ISSUE<=@MAX_DATE  
     GROUP BY DB.SEX, D1.DEAL_COUNT, D2.DEAL_COUNT, D3.DEAL_COUNT, D4.DEAL_COUNT
     ORDER BY DB.SEX;
  END;  
END;

--
