/* Создание процедуры выборки акта сверки */

CREATE PROCEDURE /*PREFIX*/ACT_OF_REVISE
  @AGREEMENT_ID VARCHAR(32),
  @DATE DATETIME
AS
BEGIN
  DECLARE @MAX_DATE DATETIME;

  SELECT @MAX_DATE=MAX(DATE_PAYMENT)  
    FROM /*PREFIX*/PAYMENTS
   WHERE STATE=1
     AND DEAL_ID IN (SELECT DEAL_ID FROM /*PREFIX*/DEALS 
                      WHERE AGREEMENT_ID=@AGREEMENT_ID
                        AND DATE_CLOSE IS NULL);

  IF (@DATE IS NOT NULL) SET @MAX_DATE=@DATE;

  SELECT D.DEBTOR_NUM,
         DB.SURNAME,
         DB.NAME,
         DB.PATRONYMIC,
         P.DATE_PAYMENT,
         P.AMOUNT
    FROM /*PREFIX*/PAYMENTS P
    JOIN /*PERFIX*/DEALS D ON D.DEAL_ID=P.DEAL_ID
    JOIN DEBTORS DB ON DB.DEBTOR_ID=D.DEBTOR_ID
  WHERE P.STATE=1
    AND D.AGREEMENT_ID=@AGREEMENT_ID
  ORDER BY D.DEBTOR_NUM;
END;

--
