/* Создание процедуры выборки платежей должников */

CREATE PROCEDURE /*PREFIX*/DEBTOR_PAYMENTS
  @AGREEMENT_ID VARCHAR(32),
  @DATE_BEGIN DATETIME,
  @DATE_END DATETIME
AS
BEGIN
  DECLARE @MIN_DATE DATETIME,
          @MAX_DATE DATETIME;

  SELECT @MIN_DATE=MIN(DATE_PAYMENT), 
         @MAX_DATE=MAX(DATE_PAYMENT) 
    FROM /*PREFIX*/PAYMENTS
   WHERE STATE=1
     AND DEAL_ID IN (SELECT DEAL_ID FROM /*PREFIX*/DEALS 
                      WHERE AGREEMENT_ID=@AGREEMENT_ID
                        AND DATE_CLOSE IS NULL);

  IF (@DATE_BEGIN IS NOT NULL) SET @MIN_DATE=@DATE_BEGIN;

  IF (@DATE_END IS NOT NULL) SET @MAX_DATE=@DATE_END;

  SELECT D.DEBTOR_NUM,
         DB.SURNAME,
         DB.NAME,
         DB.PATRONYMIC, 
         DB.ADDRESS_RESIDENCE,
         D.INITIAL_DEBT,
         P1.AMOUNT,
         (CASE 
            WHEN P1.AMOUNT IS NULL THEN D.INITIAL_DEBT
            ELSE D.INITIAL_DEBT-P1.AMOUNT
          END) AS DEBT         
    FROM /*PREFIX*/DEALS D
    JOIN /*PREFIX*/DEBTORS DB ON DB.DEBTOR_ID=D.DEBTOR_ID
    LEFT JOIN (SELECT DEAL_ID, SUM(AMOUNT) AS AMOUNT 
                 FROM /*PREFIX*/PAYMENTS 
                WHERE STATE=1
                  AND DATE_PAYMENT>=@MIN_DATE 
                  AND DATE_PAYMENT<=@MAX_DATE 
                GROUP BY DEAL_ID) AS P1 ON P1.DEAL_ID=D.DEAL_ID
   WHERE D.AGREEMENT_ID=@AGREEMENT_ID
   ORDER BY DB.SURNAME, DB.NAME, DB.PATRONYMIC;

END;

--
