/* Создание процедуры получения информации по кредитному делу */

CREATE PROCEDURE /*PREFIX*/GET_DEAL_INFO
  @DEAL_ID VARCHAR(32),
  @INITIAL_DEBT FLOAT OUT,
  @AMOUNT_PAYMENT FLOAT OUT,
  @CURRENT_DEBT FLOAT OUT
AS
BEGIN
  
  SELECT @INITIAL_DEBT=D.INITIAL_DEBT,
         @AMOUNT_PAYMENT=P1.AMOUNT,
         @CURRENT_DEBT= 
          (CASE  
             WHEN P1.AMOUNT IS NULL THEN D.INITIAL_DEBT
             ELSE D.INITIAL_DEBT-P1.AMOUNT
           END)
     FROM /*PREFIX*/DEALS D
     LEFT JOIN (SELECT DEAL_ID, SUM(AMOUNT) AS AMOUNT 
                  FROM /*PREFIX*/PAYMENTS WHERE STATE=1
                 GROUP BY DEAL_ID)AS P1 ON P1.DEAL_ID=D.DEAL_ID
    WHERE D.DEAL_ID=@DEAL_ID;
END;

--
