/* Создание процедуры получения количества заданий */

CREATE PROCEDURE /*PREFIX*/GET_TASK_COUNT
  @ACCOUNT_ID VARCHAR(32),
  @TASK_ID VARCHAR(32),
  @ACTION_ID VARCHAR(32),
  @PURPOSE INTEGER,
  @DATE_CREATE DATETIME,
  @COUNT INTEGER OUT
AS
BEGIN
  IF (@ACCOUNT_ID IS NOT NULL) BEGIN
 
    SELECT @COUNT=COUNT(*)
      FROM /*PREFIX*/TASKS T
      JOIN /*PREFIX*/ACCOUNT_ACTIONS AA ON AA.ACTION_ID=T.ACTION_ID
      JOIN /*PREFIX*/ACCOUNT_GROUPS AG ON AG.ACCOUNT_ID=AA.ACCOUNT_ID 
      JOIN /*PREFIX*/DEALS D ON D.DEAL_ID=T.DEAL_ID AND D.GROUP_ID=AG.GROUP_ID
      JOIN /*PREFIX*/ACTIONS A ON A.ACTION_ID=AA.ACTION_ID
     WHERE AA.ACCOUNT_ID=@ACCOUNT_ID
       AND (T.ACCOUNT_ID IS NULL OR T.ACCOUNT_ID=@ACCOUNT_ID)
       AND T.ACTION_ID=@ACTION_ID 
       AND T.RESULT_ID IS NULL
       AND D.DATE_CLOSE IS NULL
       AND CONVERT(DATETIME,CONVERT(VARCHAR(10),T.DATE_CREATE,104),104)=@DATE_CREATE
       AND A.PURPOSE=@PURPOSE
       AND T.TASK_ID<>@TASK_ID;

  END;
END;

--








