/* Создание таблицы улиц */

CREATE TABLE /*PREFIX*/STREETS
(
  STREET_ID VARCHAR(32) NOT NULL,
  LOCALITY_ID VARCHAR(32) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  PREFIX VARCHAR(10),
  PRIMARY KEY (STREET_ID),
  FOREIGN KEY (LOCALITY_ID) REFERENCES LOCALITIES (LOCALITY_ID)
)

--

/* Создание просмотра улиц */

CREATE VIEW /*PREFIX*/S_STREETS
(
  STREET_ID,
  LOCALITY_ID,
  NAME,
  PREFIX,
  LOCALITY_NAME,
  LOCALITY_PREFIX
)
AS
SELECT S.*,
       L.NAME AS LOCALITY_NAME,
       L.PREFIX AS LOCALITY_PREFIX
  FROM /*PREFIX*/STREETS S
  JOIN /*PREFIX*/LOCALITIES L ON L.LOCALITY_ID=S.LOCALITY_ID


--

/* Создание процедуры добавления улицы */

CREATE PROCEDURE /*PREFIX*/I_STREET
(
  STREET_ID VARCHAR(32),
  LOCALITY_ID VARCHAR(32),
  NAME VARCHAR(100),
  PREFIX VARCHAR(10)
)
AS
BEGIN
  INSERT INTO /*PREFIX*/STREETS (STREET_ID,LOCALITY_ID,NAME,PREFIX)
       VALUES (:STREET_ID,:LOCALITY_ID,:NAME,:PREFIX);
END;

--

/* Создание процедуры изменения улицы */

CREATE PROCEDURE /*PREFIX*/U_STREET
(
  STREET_ID VARCHAR(32),
  LOCALITY_ID VARCHAR(32),
  NAME VARCHAR(100),
  PREFIX VARCHAR(10),
  OLD_STREET_ID VARCHAR(32)
)
AS
BEGIN
  UPDATE /*PREFIX*/STREETS
     SET STREET_ID=:STREET_ID,
         LOCALITY_ID=:LOCALITY_ID,
         NAME=:NAME,
         PREFIX=:PREFIX
   WHERE STREET_ID=:OLD_STREET_ID;
END;

--

/* Создание процедуры удаления улицы */

CREATE PROCEDURE /*PREFIX*/D_STREET
(
  OLD_STREET_ID VARCHAR(32)
)
AS
BEGIN
  DELETE FROM /*PREFIX*/STREETS 
        WHERE STREET_ID=:OLD_STREET_ID;
END;

--

/* Фиксация изменений */

COMMIT