/* Создание таблицы дилеров */

CREATE TABLE /*PREFIX*/DEALERS
(
  DEALER_ID VARCHAR(32) NOT NULL,
  PAYMENT_TYPE INTEGER NOT NULL,
  PAYMENT_PERCENT NUMERIC(15,2),
  PRIMARY KEY (DEALER_ID),
  FOREIGN KEY (DEALER_ID) REFERENCES /*PREFIX*/FIRMS (FIRM_ID)
)

--

/* Создание просмотра таблицы дилеров */

CREATE VIEW /*PREFIX*/S_DEALERS
AS
  SELECT D.*,
         F.SMALL_NAME,
         F.FULL_NAME,
         F.PHONE,
         F.FAX,
         F.EMAIL,
         F.SITE,
         F.DIRECTOR,
         F.CONTACT_FACE,
         F.INDEX_POST,
         F.STREET_POST_ID,
         F.HOUSE_POST,
         F.FLAT_POST,
         S2.NAME AS STREET_POST_NAME,
         S2.PREFIX AS STREET_POST_PREFIX,
         L2.LOCALITY_ID AS LOCALITY_POST_ID,
         L2.NAME AS LOCALITY_POST_NAME,
         L2.PREFIX AS LOCALITY_POST_PREFIX
    FROM /*PREFIX*/DEALERS D
    JOIN /*PREFIX*/FIRMS F ON F.FIRM_ID=D.DEALER_ID
    LEFT JOIN /*PREFIX*/STREETS S2 ON S2.STREET_ID=F.STREET_POST_ID
    LEFT JOIN /*PREFIX*/LOCALITIES L2 ON L2.LOCALITY_ID=S2.LOCALITY_ID


--

/* Создание процедуры добавления дилера */

CREATE OR ALTER PROCEDURE /*PREFIX*/I_DEALER
(
  DEALER_ID VARCHAR(32),
  PAYMENT_TYPE INTEGER,
  PAYMENT_PERCENT NUMERIC(15,2),
  SMALL_NAME VARCHAR(250),
  FULL_NAME VARCHAR(250),
  PHONE VARCHAR(250),
  FAX VARCHAR(250),
  EMAIL VARCHAR(100),
  SITE VARCHAR(100),
  DIRECTOR VARCHAR(250),
  CONTACT_FACE VARCHAR(250),
  INDEX_POST VARCHAR(10),
  STREET_POST_ID VARCHAR(32),
  HOUSE_POST VARCHAR(10),
  FLAT_POST VARCHAR(10)
)
AS
BEGIN
  INSERT INTO /*PREFIX*/FIRMS (FIRM_ID,SMALL_NAME,FULL_NAME,PHONE,FAX,EMAIL,SITE,DIRECTOR,
                               CONTACT_FACE,INDEX_POST,STREET_POST_ID,HOUSE_POST,FLAT_POST)
       VALUES (:DEALER_ID,:SMALL_NAME,:FULL_NAME,:PHONE,:FAX,:EMAIL,:SITE,:DIRECTOR,
               :CONTACT_FACE,:INDEX_POST,:STREET_POST_ID,:HOUSE_POST,:FLAT_POST);

  INSERT INTO /*PREFIX*/DEALERS (DEALER_ID,PAYMENT_TYPE,PAYMENT_PERCENT)
       VALUES (:DEALER_ID,:PAYMENT_TYPE,:PAYMENT_PERCENT);
END;

--

/* Создание процедуры изменения дилера */

CREATE PROCEDURE /*PREFIX*/U_DEALER
(
  DEALER_ID VARCHAR(32),
  PAYMENT_TYPE INTEGER,
  PAYMENT_PERCENT NUMERIC(15,2),
  SMALL_NAME VARCHAR(250),
  FULL_NAME VARCHAR(250),
  PHONE VARCHAR(250),
  FAX VARCHAR(250),
  EMAIL VARCHAR(100),
  SITE VARCHAR(100),
  DIRECTOR VARCHAR(250),
  CONTACT_FACE VARCHAR(250),
  INDEX_POST VARCHAR(10),
  STREET_POST_ID VARCHAR(32),
  HOUSE_POST VARCHAR(10),
  FLAT_POST VARCHAR(10),
  OLD_DEALER_ID VARCHAR(32)
)
AS
BEGIN
  UPDATE /*PREFIX*/FIRMS
     SET FIRM_ID=:DEALER_ID,
         SMALL_NAME=:SMALL_NAME,
         FULL_NAME=:FULL_NAME,
         PHONE=:PHONE,
         FAX=:FAX,
         EMAIL=:EMAIL,
         SITE=:SITE,
         DIRECTOR=:DIRECTOR,
         CONTACT_FACE=:CONTACT_FACE,
         INDEX_POST=:INDEX_POST,
         STREET_POST_ID=:STREET_POST_ID,
         HOUSE_POST=:HOUSE_POST,
         FLAT_POST=:FLAT_POST
   WHERE FIRM_ID=:OLD_DEALER_ID;


  UPDATE /*PREFIX*/DEALERS
     SET DEALER_ID=:DEALER_ID,
         PAYMENT_TYPE=:PAYMENT_TYPE,
         PAYMENT_PERCENT=:PAYMENT_PERCENT
   WHERE DEALER_ID=:OLD_DEALER_ID;
END;

--

/* Создание процедуры удаления дилера */

CREATE PROCEDURE /*PREFIX*/D_DEALER
(
  OLD_DEALER_ID VARCHAR(32)
)
AS
BEGIN
  DELETE FROM /*PREFIX*/DEALERS
        WHERE DEALER_ID=:OLD_DEALER_ID;

  DELETE FROM /*PREFIX*/FIRMS
        WHERE FIRM_ID=:OLD_DEALER_ID;
END;

--

/* Фиксация изменений */

COMMIT