/* Создание таблицы подтуров */

CREATE TABLE /*PREFIX*/SUBROUNDS
(
  SUBROUND_ID VARCHAR(32) NOT NULL,
  TIRAGE_ID VARCHAR(32) NOT NULL,
  ROUND_NUM INTEGER NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  PERCENT NUMERIC(4,2) NOT NULL,
  PRIORITY INTEGER NOT NULL,
  PRIMARY KEY (SUBROUND_ID),
  FOREIGN KEY (TIRAGE_ID) REFERENCES /*PREFIX*/TIRAGES (TIRAGE_ID)
)

--

/* Создание просмотра таблицы подтуров */

CREATE VIEW /*PREFIX*/S_SUBROUNDS
(
  SUBROUND_ID,
  TIRAGE_ID,
  ROUND_NUM,
  NAME,
  PERCENT,
  PRIORITY,
  TIRAGE_NUM
)
AS
  SELECT P.*,
         T.NUM AS TIRAGE_NUM
    FROM /*PREFIX*/SUBROUNDS P
    JOIN /*PREFIX*/TIRAGES T ON T.TIRAGE_ID=P.TIRAGE_ID

--

/* Создание процедуры добавления подтура */

CREATE PROCEDURE /*PREFIX*/I_SUBROUND
(
  SUBROUND_ID VARCHAR(32),
  TIRAGE_ID VARCHAR(32),
  ROUND_NUM INTEGER,
  NAME VARCHAR(100),
  PERCENT NUMERIC(4,2),
  PRIORITY INTEGER
)
AS
BEGIN
  INSERT INTO /*PREFIX*/SUBROUNDS (SUBROUND_ID,TIRAGE_ID,ROUND_NUM,NAME,PERCENT,PRIORITY)
       VALUES (:SUBROUND_ID,:TIRAGE_ID,:ROUND_NUM,:NAME,:PERCENT,:PRIORITY);
END;

--

/* Создание процедуры изменения подтура */

CREATE PROCEDURE /*PREFIX*/U_SUBROUND
(
  SUBROUND_ID VARCHAR(32),
  TIRAGE_ID VARCHAR(32),
  ROUND_NUM INTEGER,
  NAME VARCHAR(100),
  PERCENT NUMERIC(4,2),
  PRIORITY INTEGER,
  OLD_SUBROUND_ID VARCHAR(32)
)
AS
BEGIN
  UPDATE /*PREFIX*/SUBROUNDS
     SET SUBROUND_ID=:SUBROUND_ID,
         TIRAGE_ID=:TIRAGE_ID,
         ROUND_NUM=:ROUND_NUM,
         NAME=:NAME,
         PERCENT=:PERCENT,
         PRIORITY=:PRIORITY
   WHERE SUBROUND_ID=:OLD_SUBROUND_ID;
END;

--

/* Создание процедуры удаления подтура */

CREATE PROCEDURE /*PREFIX*/D_SUBROUND
(
  OLD_SUBROUND_ID VARCHAR(32)
)
AS
BEGIN
  DELETE FROM /*PREFIX*/SUBROUNDS
        WHERE SUBROUND_ID=:OLD_SUBROUND_ID;
END;

--

/* Фиксация изменений */

COMMIT