/* Создание таблицы розыгрышей */

CREATE TABLE /*PREFIX*/LOTTERY
(
  LOTTERY_ID VARCHAR(32) NOT NULL,
  TIRAGE_ID VARCHAR(32) NOT NULL,
  SUBROUND_ID VARCHAR(32),
  PRIORITY INTEGER NOT NULL,
  ROUND_NUM INTEGER NOT NULL,
  BARREL_NUM VARCHAR(2) NOT NULL,
  PRIMARY KEY (LOTTERY_ID),
  FOREIGN KEY (TIRAGE_ID) REFERENCES /*PREFIX*/TIRAGES (TIRAGE_ID),
  FOREIGN KEY (SUBROUND_ID) REFERENCES /*PREFIX*/SUBROUNDS (SUBROUND_ID)
)

--

CREATE INDEX IDX_LOTTERY_ROUND_NUM
ON LOTTERY (ROUND_NUM)

--

/* Создание просмотра таблицы розыгрышей */

CREATE OR ALTER VIEW S_LOTTERY
(
    LOTTERY_ID,
    TIRAGE_ID,
    SUBROUND_ID,
    PRIORITY,
    ROUND_NUM,
    BARREL_NUM,
    TIRAGE_NUM,
    SUBROUND_PRIORITY,
    SUBROUND_NAME
)
AS
SELECT L.*,
       T.NUM AS TIRAGE_NUM,
       S.PRIORITY AS SUBROUND_PRIORITY,
       S.NAME AS SUBROUND_NAME
    FROM /*PREFIX*/LOTTERY L
    JOIN /*PREFIX*/TIRAGES T ON T.TIRAGE_ID=L.TIRAGE_ID
    LEFT JOIN /*PREFIX*/SUBROUNDS S ON S.SUBROUND_ID=L.SUBROUND_ID

--

/* Создание процедуры добавления розыгрыша */

CREATE OR ALTER PROCEDURE /*PREFIX*/I_LOTTERY
(
  LOTTERY_ID VARCHAR(32),
  TIRAGE_ID VARCHAR(32),
  SUBROUND_ID VARCHAR(32),
  PRIORITY INTEGER,
  ROUND_NUM INTEGER,
  BARREL_NUM VARCHAR(2)
)
AS
BEGIN
  INSERT INTO /*PREFIX*/LOTTERY (LOTTERY_ID,TIRAGE_ID,SUBROUND_ID,PRIORITY,ROUND_NUM,BARREL_NUM)
       VALUES (:LOTTERY_ID,:TIRAGE_ID,:SUBROUND_ID,:PRIORITY,:ROUND_NUM,:BARREL_NUM);
END;

--

/* Создание процедуры изменения розыгрыша */

CREATE OR ALTER PROCEDURE /*PREFIX*/U_LOTTERY
(
  LOTTERY_ID VARCHAR(32),
  TIRAGE_ID VARCHAR(32),
  SUBROUND_ID VARCHAR(32),
  PRIORITY INTEGER,
  ROUND_NUM INTEGER,
  BARREL_NUM VARCHAR(2),
  OLD_LOTTERY_ID VARCHAR(32)
)
AS
BEGIN
  UPDATE /*PREFIX*/LOTTERY
     SET LOTTERY_ID=:LOTTERY_ID,
         TIRAGE_ID=:TIRAGE_ID,
         SUBROUND_ID=:SUBROUND_ID,
         PRIORITY=:PRIORITY,
         ROUND_NUM=:ROUND_NUM,
         BARREL_NUM=:BARREL_NUM
   WHERE LOTTERY_ID=:OLD_LOTTERY_ID;
END;

--

/* Создание процедуры удаления розыгрыша */

CREATE PROCEDURE /*PREFIX*/D_LOTTERY
(
  OLD_LOTTERY_ID VARCHAR(32)
)
AS
BEGIN
  DELETE FROM /*PREFIX*/LOTTERY
        WHERE LOTTERY_ID=:OLD_LOTTERY_ID;
END;

--

/* Фиксация изменений */

COMMIT