/* Создание таблицы выигрышей */

CREATE TABLE /*PREFIX*/WINNINGS
(
  LOTTERY_ID VARCHAR(32) NOT NULL,
  TICKET_ID VARCHAR(32) NOT NULL,
  PRIMARY KEY (LOTTERY_ID,TICKET_ID),
  FOREIGN KEY (LOTTERY_ID) REFERENCES /*PREFIX*/LOTTERY (LOTTERY_ID),
  FOREIGN KEY (TICKET_ID) REFERENCES /*PREFIX*/TICKETS (TICKET_ID)
)

--

CREATE OR ALTER VIEW S_WINNINGS
(
  LOTTERY_ID,
  TICKET_ID,
  TIRAGE_ID,
  ROUND_NUM,
  SUBROUND_ID,
  BARREL_NUM,
  LOTTERY_PRIORITY,
  TIRAGE_NUM,
  TICKET_SERIES,
  TICKET_NUM,
  DEALER_ID,
  SURNAME,
  NAME,
  PATRONYMIC,
  ADDRESS,
  PHONE,
  DEALER_SMALL_NAME,
  SUBROUND_NAME,
  SUBROUND_PRIORITY
)
AS
SELECT W.*,
       L.TIRAGE_ID,
       L.ROUND_NUM,
       L.SUBROUND_ID,
       L.BARREL_NUM,
       L.PRIORITY,
       TR.NUM,
       T.SERIES,
       T.NUM,
       T.DEALER_ID,
       T.SURNAME,
       T.NAME,
       T.PATRONYMIC,
       T.ADDRESS,
       T.PHONE,
       F.SMALL_NAME,
       S.NAME,
       S.PRIORITY
  FROM WINNINGS W
  JOIN LOTTERY L ON L.LOTTERY_ID=W.LOTTERY_ID
  JOIN TIRAGES TR ON TR.TIRAGE_ID=L.TIRAGE_ID
  JOIN TICKETS T ON T.TICKET_ID=W.TICKET_ID
  LEFT JOIN DEALERS D ON D.DEALER_ID=T.DEALER_ID
  LEFT JOIN FIRMS F ON F.FIRM_ID=D.DEALER_ID
  LEFT JOIN SUBROUNDS S ON S.SUBROUND_ID=L.SUBROUND_ID

--