/* Создание процедуры получения статистики по тиражу */

CREATE OR ALTER PROCEDURE GET_TIRAGE_STATISTICS
(
  TIRAGE_ID VARCHAR(32),
  TICKET_COST NUMERIC(15,2),
  PRIZE_PERCENT NUMERIC(4,2),
  JACKPOT_PERCENT NUMERIC(4,2),
  FIRST_PERCENT NUMERIC(4,2),
  SECOND_1_ROUND_PERCENT NUMERIC(4,2),
  SECOND_2_ROUND_PERCENT NUMERIC(4,2),
  SECOND_3_ROUND_PERCENT NUMERIC(4,2),
  SECOND_4_ROUND_PERCENT NUMERIC(4,2)
)
RETURNS (
  ALL_COUNT INTEGER,
  USED_COUNT INTEGER,
  NOT_USED_COUNT INTEGER,
  PRIZE_SUM NUMERIC(15,2),
  JACKPOT_SUM NUMERIC(15,2),
  FIRST_SUM NUMERIC(15,2),
  SECOND_1_ROUND_SUM NUMERIC(15,2),
  SECOND_2_ROUND_SUM NUMERIC(15,2),
  SECOND_3_ROUND_SUM NUMERIC(15,2),
  SECOND_4_ROUND_SUM NUMERIC(15,2))
AS
DECLARE VARIABLE TEMP_SUM NUMERIC(15,2);
BEGIN

  SELECT COUNT(*)
    FROM /*PREFIX*/TICKETS
   WHERE TIRAGE_ID=:TIRAGE_ID
    INTO :ALL_COUNT;

  SELECT COUNT(*)
    FROM /*PREFIX*/TICKETS
   WHERE TIRAGE_ID=:TIRAGE_ID
     AND USED=0
    INTO :NOT_USED_COUNT;

  USED_COUNT=ALL_COUNT-NOT_USED_COUNT;

  PRIZE_SUM=(TICKET_COST*USED_COUNT)*PRIZE_PERCENT/100;

  JACKPOT_SUM=PRIZE_SUM*JACKPOT_PERCENT/100;

  FIRST_SUM=PRIZE_SUM*FIRST_PERCENT/100;

  SECOND_1_ROUND_SUM=PRIZE_SUM*SECOND_1_ROUND_PERCENT/100;

  SECOND_2_ROUND_SUM=PRIZE_SUM*SECOND_2_ROUND_PERCENT/100;

  SECOND_3_ROUND_SUM=PRIZE_SUM*SECOND_3_ROUND_PERCENT/100;

  SECOND_4_ROUND_SUM=PRIZE_SUM*SECOND_4_ROUND_PERCENT/100;
END;

--

/* Фиксация изменений */

COMMIT