/* Создание процедуры получения статистики по дилеру */

CREATE OR ALTER PROCEDURE GET_DEALER_STATISTICS
(
  TIRAGE_ID VARCHAR(32),
  DEALER_ID VARCHAR(32)
)
RETURNS
(
  ALL_COUNT INTEGER,
  USED_COUNT INTEGER,
  NOT_USED_COUNT INTEGER
)
AS
DECLARE VARIABLE TEMP_SUM NUMERIC(15,2);
BEGIN

  SELECT COUNT(*)
    FROM /*PREFIX*/TICKETS
   WHERE TIRAGE_ID=:TIRAGE_ID
     AND DEALER_ID=:DEALER_ID
    INTO :ALL_COUNT;

  SELECT COUNT(*)
    FROM /*PREFIX*/TICKETS
   WHERE TIRAGE_ID=:TIRAGE_ID
     AND DEALER_ID=:DEALER_ID
     AND USED=0
    INTO :NOT_USED_COUNT;

  USED_COUNT=ALL_COUNT-NOT_USED_COUNT;

END;

--

/* Фиксация изменений */

COMMIT