/* Создание процедуры получения статистики по розыгрышу */

CREATE OR ALTER PROCEDURE GET_LOTTERY_STATISTICS
(
  TIRAGE_ID VARCHAR(32)
)
RETURNS (
  TICKET_COST NUMERIC(15,2),
  PRIZE_PERCENT NUMERIC(4,2),
  JACKPOT_PERCENT NUMERIC(4,2),
  FIRST_PERCENT NUMERIC(4,2),
  SECOND_1_ROUND_PERCENT NUMERIC(4,2),
  SECOND_2_ROUND_PERCENT NUMERIC(4,2),
  SECOND_3_ROUND_PERCENT NUMERIC(4,2),
  SECOND_4_ROUND_PERCENT NUMERIC(4,2),
  ALL_COUNT INTEGER,
  USED_COUNT INTEGER,
  NOT_USED_COUNT INTEGER,
  PRIZE_SUM NUMERIC(15,2),
  JACKPOT_SUM NUMERIC(15,2),
  FIRST_SUM NUMERIC(15,2),
  SECOND_1_ROUND_SUM NUMERIC(15,2),
  SECOND_2_ROUND_SUM NUMERIC(15,2),
  SECOND_3_ROUND_SUM NUMERIC(15,2),
  SECOND_4_ROUND_SUM NUMERIC(15,2))
AS
DECLARE VARIABLE TEMP_SUM NUMERIC(15,2);
BEGIN

  SELECT TICKET_COST, PRIZE_PERCENT, JACKPOT_PERCENT, FIRST_PERCENT,
         SECOND_1_ROUND_PERCENT, SECOND_2_ROUND_PERCENT,
         SECOND_3_ROUND_PERCENT, SECOND_4_ROUND_PERCENT
    FROM /*PREFIX*/TIRAGES
   WHERE TIRAGE_ID=:TIRAGE_ID
    INTO :TICKET_COST, :PRIZE_PERCENT, :JACKPOT_PERCENT, :FIRST_PERCENT,
         :SECOND_1_ROUND_PERCENT, :SECOND_2_ROUND_PERCENT,
         :SECOND_3_ROUND_PERCENT, :SECOND_4_ROUND_PERCENT;

  EXECUTE PROCEDURE GET_TIRAGE_STATISTICS(TIRAGE_ID,TICKET_COST,PRIZE_PERCENT,JACKPOT_PERCENT,FIRST_PERCENT,
                                          SECOND_1_ROUND_PERCENT,SECOND_2_ROUND_PERCENT,
                                          SECOND_3_ROUND_PERCENT,SECOND_4_ROUND_PERCENT)
   RETURNING_VALUES (ALL_COUNT,USED_COUNT,NOT_USED_COUNT,PRIZE_SUM,JACKPOT_SUM,FIRST_SUM,
                     SECOND_1_ROUND_SUM,SECOND_2_ROUND_SUM,SECOND_3_ROUND_SUM,SECOND_4_ROUND_SUM);

END;

--

/* Фиксация изменений */

COMMIT