CREATE OR ALTER PROCEDURE GET_SUBROUNDS
(
  LAST_SUBROUND_ID VARCHAR(32)
)
RETURNS
(
  SUBROUND_ID VARCHAR(32)
)
AS
DECLARE TIRAGE_ID VARCHAR(32);
DECLARE ROUND_NUM INTEGER;
BEGIN

  SELECT TIRAGE_ID, ROUND_NUM
    FROM SUBROUNDS
   WHERE SUBROUND_ID=:LAST_SUBROUND_ID
    INTO :TIRAGE_ID, :ROUND_NUM;

  FOR SELECT SUBROUND_ID
        FROM SUBROUNDS
       WHERE TIRAGE_ID=:TIRAGE_ID
         AND ROUND_NUM=:ROUND_NUM
       ORDER BY PRIORITY
        INTO :SUBROUND_ID DO BEGIN

    IF (SUBROUND_ID=LAST_SUBROUND_ID) THEN
      BREAK;

    SUSPEND;
  END

END