/* Создание процедуры получения билетов вместе с линиями */

CREATE OR ALTER PROCEDURE GET_TICKET_LINES
(
  TIRAGE_ID VARCHAR(32),
  ROUND_NUM INTEGER,
  SUBROUND_ID VARCHAR(32)
)
RETURNS
(
  TICKET_ID VARCHAR(32),
  LOTTERY_ID VARCHAR(32),
  LINE_NUM INTEGER,
  LINE_COLOR INTEGER
)
AS
BEGIN

  FOR SELECT TICKET_ID, LOTTERY_ID, 1, 0
        FROM /*PREFIX*/GET_TICKET_LINE(:TIRAGE_ID,:ROUND_NUM,1,:SUBROUND_ID)
       UNION
      SELECT TICKET_ID, LOTTERY_ID, 2, 1
        FROM /*PREFIX*/GET_TICKET_LINE(:TIRAGE_ID,:ROUND_NUM,2,:SUBROUND_ID)
       UNION
      SELECT TICKET_ID, LOTTERY_ID, 3, 0
        FROM /*PREFIX*/GET_TICKET_LINE(:TIRAGE_ID,:ROUND_NUM,3,:SUBROUND_ID)
       UNION
      SELECT TICKET_ID, LOTTERY_ID, 4, 1
        FROM /*PREFIX*/GET_TICKET_LINE(:TIRAGE_ID,:ROUND_NUM,4,:SUBROUND_ID)
       UNION
      SELECT TICKET_ID, LOTTERY_ID, 5, 0
        FROM /*PREFIX*/GET_TICKET_LINE(:TIRAGE_ID,:ROUND_NUM,5,:SUBROUND_ID)
       UNION
      SELECT TICKET_ID, LOTTERY_ID, 6, 1
        FROM /*PREFIX*/GET_TICKET_LINE(:TIRAGE_ID,:ROUND_NUM,6,:SUBROUND_ID)
        INTO :TICKET_ID, :LOTTERY_ID, :LINE_NUM, :LINE_COLOR DO BEGIN

    SUSPEND;

  END

END

--

/* Фиксация изменений */

COMMIT