/* Создание процедуры расчета всех раундов */

CREATE OR ALTER PROCEDURE CALCULATE
(
  TIRAGE_ID VARCHAR(32)
)
AS
DECLARE SUBROUND_ID VARCHAR(32);
BEGIN
  EXECUTE PROCEDURE CALCULATE_FIRST_ROUND(:TIRAGE_ID);

  EXECUTE PROCEDURE CALCULATE_SECOND_ROUND(:TIRAGE_ID);

  EXECUTE PROCEDURE CALCULATE_THIRD_ROUND(:TIRAGE_ID);

  FOR SELECT DISTINCT(L.SUBROUND_ID)
        FROM LOTTERY L
        JOIN SUBROUNDS S ON S.SUBROUND_ID=L.SUBROUND_ID
       WHERE L.TIRAGE_ID=:TIRAGE_ID
         AND L.ROUND_NUM=4
       ORDER BY S.PRIORITY, L.PRIORITY
        INTO :SUBROUND_ID DO BEGIN

      EXECUTE PROCEDURE CALCULATE_FOURTH_ROUND(:TIRAGE_ID,:SUBROUND_ID);

  END
END

--

/* Фиксация изменений */

COMMIT