/* Создание процедуры получения четвертого раунда */

CREATE OR ALTER PROCEDURE GET_FOURTH_ROUND
(
  TIRAGE_ID VARCHAR(32),
  SUBROUND_ID VARCHAR(32)
)
RETURNS
(
  TICKET_COUNT INTEGER
)
AS
BEGIN
  TICKET_COUNT=0;

  EXECUTE PROCEDURE CALCULATE_FOURTH_ROUND(:TIRAGE_ID,:SUBROUND_ID);

  SELECT COUNT(*)
    FROM WINNINGS
   WHERE LOTTERY_ID IN (SELECT LOTTERY_ID
                          FROM LOTTERY
                         WHERE TIRAGE_ID=:TIRAGE_ID
                           AND ROUND_NUM=4
                           AND SUBROUND_ID=:SUBROUND_ID)
    INTO :TICKET_COUNT;

END

--

/* Фиксация изменений */

COMMIT