CREATE OR ALTER PROCEDURE GET_PROTOCOL
(
  TIRAGE_ID VARCHAR(32)
)
RETURNS (
  TICKET_ID VARCHAR(32),
  ROUND_NUM INTEGER,
  SUBROUND_NAME VARCHAR(100),
  NUM VARCHAR(8),
  SERIES VARCHAR(5),
  DEALER_ID VARCHAR(32),
  DEALER_SMALL_NAME VARCHAR(250),
  PRIZE_NAME VARCHAR(40),
  PRIZE_COST NUMERIC(15,4),
  SURNAME VARCHAR(100),
  NAME VARCHAR(100),
  PATRONYMIC VARCHAR(100),
  ADDRESS VARCHAR(250),
  PHONE VARCHAR(100))
AS
  DECLARE TICKET_COST NUMERIC(15,2);
  DECLARE PRIZE_PERCENT NUMERIC(4,2);
  DECLARE JACKPOT_PERCENT NUMERIC(4,2);
  DECLARE FIRST_PERCENT NUMERIC(4,2);
  DECLARE SECOND_1_ROUND_PERCENT NUMERIC(4,2);
  DECLARE SECOND_2_ROUND_PERCENT NUMERIC(4,2);
  DECLARE SECOND_3_ROUND_PERCENT NUMERIC(4,2);
  DECLARE SECOND_4_ROUND_PERCENT NUMERIC(4,2);
  DECLARE ALL_COUNT INTEGER;
  DECLARE USED_COUNT INTEGER;
  DECLARE NOT_USED_COUNT INTEGER;
  DECLARE PRIZE_SUM NUMERIC(15,2);
  DECLARE JACKPOT_SUM NUMERIC(15,2);
  DECLARE FIRST_SUM NUMERIC(15,2);
  DECLARE SECOND_1_ROUND_SUM NUMERIC(15,2);
  DECLARE SECOND_2_ROUND_SUM NUMERIC(15,2);
  DECLARE SECOND_3_ROUND_SUM NUMERIC(15,2);
  DECLARE SECOND_4_ROUND_SUM NUMERIC(15,2);
  DECLARE TICKET_COUNT INTEGER;
  DECLARE SUBROUND_ID VARCHAR(32);
  DECLARE SUBROUND_PERCENT NUMERIC(4,2);
BEGIN

  EXECUTE PROCEDURE GET_LOTTERY_STATISTICS(:TIRAGE_ID)
   RETURNING_VALUES :TICKET_COST, PRIZE_PERCENT, JACKPOT_PERCENT, FIRST_PERCENT,
                    :SECOND_1_ROUND_PERCENT, :SECOND_2_ROUND_PERCENT, SECOND_3_ROUND_PERCENT, :SECOND_4_ROUND_PERCENT,
                    :ALL_COUNT, :USED_COUNT, :NOT_USED_COUNT, :PRIZE_SUM, :JACKPOT_SUM, :FIRST_SUM,
                    :SECOND_1_ROUND_SUM, :SECOND_2_ROUND_SUM, :SECOND_3_ROUND_SUM, :SECOND_4_ROUND_SUM;

  SELECT COUNT(*)
    FROM WINNINGS
   WHERE LOTTERY_ID IN (SELECT LOTTERY_ID
                          FROM LOTTERY
                         WHERE TIRAGE_ID=:TIRAGE_ID
                           AND ROUND_NUM=1
                           AND SUBROUND_ID IS NULL) 
    INTO :TICKET_COUNT;

  IF (TICKET_COUNT=0) THEN TICKET_COUNT=1;

  PRIZE_NAME='Денежный приз';
  PRIZE_COST=SECOND_1_ROUND_SUM/TICKET_COUNT;

  FOR SELECT W.TICKET_ID,1,NULL,T.NUM,T.SERIES,
             T.DEALER_ID,F.SMALL_NAME,:PRIZE_NAME,:PRIZE_COST,
             T.SURNAME,T.NAME,T.PATRONYMIC,T.ADDRESS,T.PHONE
        FROM WINNINGS W
        JOIN LOTTERY L ON L.LOTTERY_ID=W.LOTTERY_ID
        JOIN TICKETS T ON T.TICKET_ID=W.TICKET_ID
        LEFT JOIN DEALERS D ON D.DEALER_ID=T.DEALER_ID
        LEFT JOIN FIRMS F ON F.FIRM_ID=D.DEALER_ID
       WHERE W.LOTTERY_ID IN (SELECT LOTTERY_ID
                                FROM LOTTERY
                               WHERE TIRAGE_ID=:TIRAGE_ID
                                 AND ROUND_NUM=1
                                 AND SUBROUND_ID IS NULL)
         AND L.TIRAGE_ID=:TIRAGE_ID
       ORDER BY L.PRIORITY
        INTO :TICKET_ID,:ROUND_NUM,:SUBROUND_NAME,:NUM,:SERIES,
             :DEALER_ID,:DEALER_SMALL_NAME,:PRIZE_NAME,:PRIZE_COST,
             :SURNAME,:NAME,:PATRONYMIC,:ADDRESS,:PHONE DO BEGIN
    SUSPEND;
  END

  SELECT COUNT(*)
    FROM WINNINGS
   WHERE LOTTERY_ID IN (SELECT LOTTERY_ID
                          FROM LOTTERY
                         WHERE TIRAGE_ID=:TIRAGE_ID
                           AND ROUND_NUM=2
                           AND SUBROUND_ID IS NULL)
    INTO :TICKET_COUNT;

  IF (TICKET_COUNT=0) THEN TICKET_COUNT=1;

  PRIZE_NAME='Денежный приз';
  PRIZE_COST=SECOND_2_ROUND_SUM/TICKET_COUNT;

  FOR SELECT W.TICKET_ID,2,NULL,T.NUM,T.SERIES,
             T.DEALER_ID,F.SMALL_NAME,:PRIZE_NAME,:PRIZE_COST,
             T.SURNAME,T.NAME,T.PATRONYMIC,T.ADDRESS,T.PHONE
        FROM WINNINGS W
        JOIN LOTTERY L ON L.LOTTERY_ID=W.LOTTERY_ID
        JOIN TICKETS T ON T.TICKET_ID=W.TICKET_ID
        LEFT JOIN DEALERS D ON D.DEALER_ID=T.DEALER_ID
        LEFT JOIN FIRMS F ON F.FIRM_ID=D.DEALER_ID
       WHERE W.LOTTERY_ID IN (SELECT LOTTERY_ID
                                FROM LOTTERY
                               WHERE TIRAGE_ID=:TIRAGE_ID
                                 AND ROUND_NUM=2
                                 AND SUBROUND_ID IS NULL)
         AND L.TIRAGE_ID=:TIRAGE_ID
       ORDER BY L.PRIORITY
        INTO :TICKET_ID,:ROUND_NUM,:SUBROUND_NAME,:NUM,:SERIES,
             :DEALER_ID,:DEALER_SMALL_NAME,:PRIZE_NAME,:PRIZE_COST,
             :SURNAME,:NAME,:PATRONYMIC,:ADDRESS,:PHONE DO BEGIN
    SUSPEND;
  END

  SELECT COUNT(*)
    FROM WINNINGS
   WHERE LOTTERY_ID IN (SELECT LOTTERY_ID
                          FROM LOTTERY
                         WHERE TIRAGE_ID=:TIRAGE_ID
                           AND ROUND_NUM=3
                           AND SUBROUND_ID IS NULL)
    INTO :TICKET_COUNT;
    
  IF (TICKET_COUNT=0) THEN TICKET_COUNT=1;

  PRIZE_NAME='Денежный приз';
  PRIZE_COST=SECOND_3_ROUND_SUM/TICKET_COUNT;

  FOR SELECT W.TICKET_ID,3,NULL,T.NUM,T.SERIES,
             T.DEALER_ID,F.SMALL_NAME,:PRIZE_NAME,:PRIZE_COST,
             T.SURNAME,T.NAME,T.PATRONYMIC,T.ADDRESS,T.PHONE
        FROM WINNINGS W
        JOIN LOTTERY L ON L.LOTTERY_ID=W.LOTTERY_ID
        JOIN TICKETS T ON T.TICKET_ID=W.TICKET_ID
        LEFT JOIN DEALERS D ON D.DEALER_ID=T.DEALER_ID
        LEFT JOIN FIRMS F ON F.FIRM_ID=D.DEALER_ID
       WHERE W.LOTTERY_ID IN (SELECT LOTTERY_ID
                                FROM LOTTERY
                               WHERE TIRAGE_ID=:TIRAGE_ID
                                 AND ROUND_NUM=3
                                 AND SUBROUND_ID IS NULL)
         AND L.TIRAGE_ID=:TIRAGE_ID
       ORDER BY L.PRIORITY
        INTO :TICKET_ID,:ROUND_NUM,:SUBROUND_NAME,:NUM,:SERIES,
             :DEALER_ID,:DEALER_SMALL_NAME,:PRIZE_NAME,:PRIZE_COST,
             :SURNAME,:NAME,:PATRONYMIC,:ADDRESS,:PHONE DO BEGIN
    SUSPEND;
  END

  FOR SELECT SUBROUND_ID, NAME, PERCENT
        FROM SUBROUNDS
       WHERE TIRAGE_ID=:TIRAGE_ID
       ORDER BY PRIORITY
        INTO :SUBROUND_ID, :SUBROUND_NAME, :SUBROUND_PERCENT DO BEGIN

    SELECT COUNT(*)
      FROM WINNINGS
      WHERE LOTTERY_ID IN (SELECT LOTTERY_ID
                             FROM LOTTERY
                            WHERE TIRAGE_ID=:TIRAGE_ID
                              AND ROUND_NUM=4
                              AND SUBROUND_ID=:SUBROUND_ID)
       INTO :TICKET_COUNT;

    IF (TICKET_COUNT=0) THEN TICKET_COUNT=1;

    PRIZE_NAME='Денежный приз';
    PRIZE_COST=SECOND_4_ROUND_SUM*(SUBROUND_PERCENT/100)/TICKET_COUNT;

    FOR SELECT W.TICKET_ID,4,:SUBROUND_NAME,T.NUM,T.SERIES,
               T.DEALER_ID,F.SMALL_NAME,:PRIZE_NAME,:PRIZE_COST,
               T.SURNAME,T.NAME,T.PATRONYMIC,T.ADDRESS,T.PHONE
          FROM WINNINGS W
          JOIN LOTTERY L ON L.LOTTERY_ID=W.LOTTERY_ID
          JOIN TICKETS T ON T.TICKET_ID=W.TICKET_ID
          LEFT JOIN DEALERS D ON D.DEALER_ID=T.DEALER_ID
          LEFT JOIN FIRMS F ON F.FIRM_ID=D.DEALER_ID
         WHERE W.LOTTERY_ID IN (SELECT LOTTERY_ID
                                  FROM LOTTERY
                                 WHERE TIRAGE_ID=:TIRAGE_ID
                                   AND ROUND_NUM=4
                                   AND SUBROUND_ID=:SUBROUND_ID)
           AND L.TIRAGE_ID=:TIRAGE_ID
         ORDER BY L.PRIORITY
          INTO :TICKET_ID,:ROUND_NUM,:SUBROUND_NAME,:NUM,:SERIES,
               :DEALER_ID,:DEALER_SMALL_NAME,:PRIZE_NAME,:PRIZE_COST,
               :SURNAME,:NAME,:PATRONYMIC,:ADDRESS,:PHONE DO BEGIN
      SUSPEND;
    END
  END

END