/* Создание таблицы предприятий */

CREATE TABLE /*PREFIX*/FIRMS
(
  FIRM_ID VARCHAR(32) NOT NULL,
  FIRM_TYPE_ID VARCHAR(32) NOT NULL,
  PARENT_ID VARCHAR(32),
  SMALL_NAME VARCHAR(250) NOT NULL,
  FULL_NAME VARCHAR(250) NOT NULL,
  INN VARCHAR(12),
  PAYMENT_ACCOUNT VARCHAR(20),
  BANK VARCHAR(250),
  BIK VARCHAR(20),
  CORR_ACCOUNT VARCHAR(20),
  LEGAL_ADDRESS VARCHAR(250),
  LEGAL_INDEX VARCHAR(10),
  POST_ADDRESS VARCHAR(250),
  POST_INDEX VARCHAR(10),
  PHONE VARCHAR(250),
  FAX VARCHAR(250),
  EMAIL VARCHAR(100),
  SITE VARCHAR(100),
  OKONH VARCHAR(20),
  OKPO VARCHAR(20),
  KPP VARCHAR(20),
  DIRECTOR VARCHAR(250),
  ACCOUNTANT VARCHAR(250),
  CONTACT_FACE VARCHAR(250),
  PRIMARY KEY (FIRM_ID),
  FOREIGN KEY (FIRM_TYPE_ID) REFERENCES /*PREFIX*/FIRM_TYPES (FIRM_TYPE_ID),
  FOREIGN KEY (PARENT_ID) REFERENCES FIRMS/*PREFIX*/ (FIRM_ID)
)

--

/* Создание просмотра таблицы предприятий */

CREATE VIEW /*PREFIX*/S_FIRMS
AS
  SELECT F.*, 
         FT.NAME AS FIRM_TYPE_NAME,
         F1.SMALL_NAME AS PARENT_SMALL_NAME
    FROM /*PREFIX*/FIRMS F
    JOIN /*PREFIX*/FIRM_TYPES FT ON FT.FIRM_TYPE_ID=F.FIRM_TYPE_ID
    LEFT JOIN /*PREFIX*/FIRMS F1 ON F1.FIRM_ID=F.PARENT_ID

--

/* Создание процедуры добавления предприятия */

CREATE PROCEDURE /*PREFIX*/I_FIRM
  @FIRM_ID VARCHAR(32),
  @FIRM_TYPE_ID VARCHAR(32),
  @PARENT_ID VARCHAR(32),
  @SMALL_NAME VARCHAR(250),
  @FULL_NAME VARCHAR(250),
  @INN VARCHAR(12),
  @PAYMENT_ACCOUNT VARCHAR(20),
  @BANK VARCHAR(250),
  @BIK VARCHAR(20),
  @CORR_ACCOUNT VARCHAR(20),
  @LEGAL_ADDRESS VARCHAR(250),
  @LEGAL_INDEX VARCHAR(10),
  @POST_ADDRESS VARCHAR(250),
  @POST_INDEX VARCHAR(10),
  @PHONE VARCHAR(250),
  @FAX VARCHAR(250),
  @EMAIL VARCHAR(100),
  @SITE VARCHAR(100),
  @OKONH VARCHAR(20),
  @OKPO VARCHAR(20),
  @KPP VARCHAR(20),
  @DIRECTOR VARCHAR(250),
  @ACCOUNTANT VARCHAR(250),
  @CONTACT_FACE VARCHAR(250)
AS
BEGIN
  INSERT INTO /*PREFIX*/FIRMS (FIRM_ID,FIRM_TYPE_ID,PARENT_ID,SMALL_NAME,FULL_NAME,INN,PAYMENT_ACCOUNT,
	                       BANK,BIK,CORR_ACCOUNT,LEGAL_ADDRESS,LEGAL_INDEX,POST_ADDRESS,POST_INDEX,
                               PHONE,FAX,EMAIL,SITE,OKONH,OKPO,KPP,DIRECTOR,ACCOUNTANT,CONTACT_FACE)
       VALUES (@FIRM_ID,@FIRM_TYPE_ID,@PARENT_ID,@SMALL_NAME,@FULL_NAME,@INN,@PAYMENT_ACCOUNT,
               @BANK,@BIK,@CORR_ACCOUNT,@LEGAL_ADDRESS,@LEGAL_INDEX,@POST_ADDRESS,@POST_INDEX,
               @PHONE,@FAX,@EMAIL,@SITE,@OKONH,@OKPO,@KPP,@DIRECTOR,@ACCOUNTANT,@CONTACT_FACE);
END;


--

/* Создание процедуры изменения предприятия */

CREATE PROCEDURE /*PREFIX*/U_FIRM
  @FIRM_ID VARCHAR(32),
  @FIRM_TYPE_ID VARCHAR(32),
  @PARENT_ID VARCHAR(32),
  @SMALL_NAME VARCHAR(250),
  @FULL_NAME VARCHAR(250),
  @INN VARCHAR(12),
  @PAYMENT_ACCOUNT VARCHAR(20),
  @BANK VARCHAR(250),
  @BIK VARCHAR(20),
  @CORR_ACCOUNT VARCHAR(20),
  @LEGAL_ADDRESS VARCHAR(250),
  @LEGAL_INDEX VARCHAR(10),
  @POST_ADDRESS VARCHAR(250),
  @POST_INDEX VARCHAR(10),
  @PHONE VARCHAR(250),
  @FAX VARCHAR(250),
  @EMAIL VARCHAR(100),
  @SITE VARCHAR(100),
  @OKONH VARCHAR(20),
  @OKPO VARCHAR(20),
  @KPP VARCHAR(20),
  @DIRECTOR VARCHAR(250),
  @ACCOUNTANT VARCHAR(250),
  @CONTACT_FACE VARCHAR(250),
  @OLD_FIRM_ID VARCHAR(32)
AS
BEGIN
  UPDATE /*PREFIX*/FIRMS
     SET FIRM_ID=@FIRM_ID,
         FIRM_TYPE_ID=@FIRM_TYPE_ID,
	 PARENT_ID=@PARENT_ID,
	 SMALL_NAME=@SMALL_NAME,
	 FULL_NAME=@FULL_NAME,
	 INN=@INN,
	 PAYMENT_ACCOUNT=@PAYMENT_ACCOUNT,
         BANK=@BANK,
	 BIK=@BIK,
         CORR_ACCOUNT=@CORR_ACCOUNT,
	 LEGAL_ADDRESS=@LEGAL_ADDRESS,
	 LEGAL_INDEX=@LEGAL_INDEX,
	 POST_ADDRESS=@POST_ADDRESS,
	 POST_INDEX=@POST_INDEX,
	 PHONE=@PHONE,
	 FAX=@FAX,
	 EMAIL=@EMAIL,
	 SITE=@SITE,
 	 OKONH=@OKONH,
	 OKPO=@OKPO,
	 KPP=@KPP,
	 DIRECTOR=@DIRECTOR,
	 ACCOUNTANT=@ACCOUNTANT,
         CONTACT_FACE=@CONTACT_FACE
   WHERE FIRM_ID=@OLD_FIRM_ID;
END;

--

/* Создание процедуры удаления предприятия */

CREATE PROCEDURE /*PREFIX*/D_FIRM
  @OLD_FIRM_ID VARCHAR(32)
AS
BEGIN
  DELETE FROM /*PREFIX*/FIRMS
        WHERE FIRM_ID=@OLD_FIRM_ID;
END;

--