/* Создание таблицы интерфейсных документов */

CREATE TABLE /*PREFIX*/DOCUMENTS
(
  DOCUMENT_ID VARCHAR(32) NOT NULL,
  OLE_CLASS VARCHAR(100) NOT NULL,
  DOCUMENT IMAGE NOT NULL,
  PLACE INTEGER NOT NULL,
  PRIMARY KEY (DOCUMENT_ID),
  FOREIGN KEY (DOCUMENT_ID) REFERENCES /*PREFIX*/INTERFACES (INTERFACE_ID)
)

--

/* Создание просмотра таблицы интерфейсных документов */

CREATE VIEW /*PREFIX*/S_DOCUMENTS
AS
  SELECT D.*, 
         I.NAME AS INTERFACE_NAME
    FROM /*PREFIX*/DOCUMENTS D
    JOIN /*PREFIX*/INTERFACES I ON I.INTERFACE_ID=D.DOCUMENT_ID

--

/* Создание процедуры добавления интерфейсного документа */

CREATE PROCEDURE /*PREFIX*/I_DOCUMENT
  @DOCUMENT_ID VARCHAR(32),
  @OLE_CLASS VARCHAR(100),
  @DOCUMENT IMAGE,
  @PLACE INTEGER
AS
BEGIN
  INSERT INTO /*PREFIX*/DOCUMENTS (DOCUMENT_ID,OLE_CLASS,DOCUMENT,PLACE)
       VALUES (@DOCUMENT_ID,@OLE_CLASS,@DOCUMENT,@PLACE);
END;

--

/* Создание процедуры изменения интерфейсного документа */

CREATE PROCEDURE /*PREFIX*/U_DOCUMENT
  @DOCUMENT_ID VARCHAR(32),
  @OLE_CLASS VARCHAR(100),
  @DOCUMENT IMAGE,
  @PLACE INTEGER,
  @OLD_DOCUMENT_ID VARCHAR(32)
AS
BEGIN
  UPDATE /*PREFIX*/DOCUMENTS
     SET DOCUMENT_ID=@DOCUMENT_ID,
         OLE_CLASS=@OLE_CLASS,
         DOCUMENT=@DOCUMENT,
         PLACE=@PLACE
   WHERE DOCUMENT_ID=@OLD_DOCUMENT_ID;
END;

--

/* Создание процедуры удаления интерфейсного документа */

CREATE PROCEDURE /*PREFIX*/D_DOCUMENT
  @OLD_DOCUMENT_ID VARCHAR(32)
AS
BEGIN
  DELETE FROM /*PREFIX*/DOCUMENTS
        WHERE DOCUMENT_ID=@OLD_DOCUMENT_ID;
END;

--