/* Создание таблицы документов */

CREATE TABLE /*PREFIX*/DOCS
(
  DOC_ID VARCHAR(32) NOT NULL,
  VIEW_ID VARCHAR(32) NOT NULL,
  NUM VARCHAR(50) NOT NULL,
  DATE_DOC DATETIME NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(250),
  PRIMARY KEY (DOC_ID),
  FOREIGN KEY (VIEW_ID) REFERENCES /*PREFIX*/VIEWS (VIEW_ID)
)

--

/* Создание просмотра таблицы документов */

CREATE VIEW /*PREFIX*/S_DOCS
AS
   SELECT D.*, 
          V.NAME AS VIEW_NAME
     FROM /*PREFIX*/DOCS D
     JOIN /*PREFIX*/VIEWS V ON V.VIEW_ID=D.VIEW_ID

--

/* Создание процедуры добавления документа */

CREATE PROCEDURE /*PREFIX*/I_DOC
  @DOC_ID VARCHAR(32),
  @VIEW_ID VARCHAR(32),
  @NUM VARCHAR(50),
  @DATE_DOC DATETIME,
  @NAME VARCHAR(100),
  @DESCRIPTION VARCHAR(250)
AS
BEGIN
  INSERT INTO /*PREFIX*/DOCS (DOC_ID,VIEW_ID,NUM,DATE_DOC,NAME,DESCRIPTION)
       VALUES (@DOC_ID,@VIEW_ID,@NUM,@DATE_DOC,@NAME,@DESCRIPTION);
END;

--

/* Создание процедуры изменения документа */

CREATE PROCEDURE /*PREFIX*/U_DOC
  @DOC_ID VARCHAR(32),
  @VIEW_ID VARCHAR(32),
  @NUM VARCHAR(50),
  @DATE_DOC DATETIME,
  @NAME VARCHAR(100),
  @DESCRIPTION VARCHAR(250),
  @OLD_DOC_ID VARCHAR(32)
AS
BEGIN
  UPDATE /*PREFIX*/DOCS
     SET DOC_ID=@DOC_ID,
         VIEW_ID=@VIEW_ID,
         NUM=@NUM,
         DATE_DOC=@DATE_DOC,
         NAME=@NAME,
         DESCRIPTION=@DESCRIPTION
   WHERE DOC_ID=@OLD_DOC_ID;
END;

--

/* Создание процедуры удаления документа */

CREATE PROCEDURE /*PREFIX*/D_DOC
  @OLD_DOC_ID VARCHAR(32)
AS
BEGIN
  DELETE FROM /*PREFIX*/DOCS
        WHERE DOC_ID=@OLD_DOC_ID;
END;

--