/* Создание таблицы позиций планов */

CREATE TABLE /*PREFIX*/POSITIONS
(
  POSITION_ID VARCHAR(32) NOT NULL,
  PLAN_ID VARCHAR(32) NOT NULL,
  VIEW_ID VARCHAR(32) NOT NULL,
  FIRM_ID VARCHAR(32) NOT NULL,
  PRIORITY INTEGER NOT NULL
  PRIMARY KEY (POSITION_ID),
  FOREIGN KEY (PLAN_ID) REFERENCES /*PREFIX*/PLANS (PLAN_ID),
  FOREIGN KEY (VIEW_ID) REFERENCES /*PREFIX*/VIEWS (VIEW_ID),
  FOREIGN KEY (FIRM_ID) REFERENCES /*PREFIX*/FIRMS (FIRM_ID)
)

--

/* Создание просмотра таблицы позиций планов */

CREATE VIEW /*PREFIX*/S_POSITIONS
AS
   SELECT P.*, 
          PL.NAME AS PLAN_NAME,
          V.NAME AS VIEW_NAME,
          F.SMALL_NAME AS FIRM_SMALL_NAME
     FROM /*PREFIX*/POSITIONS P
     JOIN /*PREFIX*/PLANS PL ON PL.PLAN_ID=P.PLAN_ID
     JOIN /*PREFIX*/VIEWS V ON V.VIEW_ID=P.VIEW_ID
     JOIN /*PREFIX*/FIRMS F ON F.FIRM_ID=P.FIRM_ID

--

/* Создание процедуры добавления позиции плану */

CREATE PROCEDURE /*PREFIX*/I_POSITION
  @POSITION_ID VARCHAR(32),
  @PLAN_ID VARCHAR(32),
  @VIEW_ID VARCHAR(32),
  @FIRM_ID VARCHAR(32),
  @PRIORITY INTEGER
AS
BEGIN
  INSERT INTO /*PREFIX*/POSITIONS (POSITION_ID,PLAN_ID,VIEW_ID,FIRM_ID,PRIORITY)
       VALUES (@POSITION_ID,@PLAN_ID,@VIEW_ID,@FIRM_ID,@PRIORITY);
END;

--

/* Создание процедуры изменения позиции плана */

CREATE PROCEDURE /*PREFIX*/U_POSITION
  @POSITION_ID VARCHAR(32),
  @PLAN_ID VARCHAR(32),
  @VIEW_ID VARCHAR(32),
  @FIRM_ID VARCHAR(32),
  @PRIORITY INTEGER,
  @OLD_POSITION_ID VARCHAR(32)
AS
BEGIN
  UPDATE /*PREFIX*/POSITIONS
     SET POSITION_ID=@POSITION_ID,
         PLAN_ID=@PLAN_ID,
         VIEW_ID=@VIEW_ID,
         FIRM_ID=@FIRM_ID,
         PRIORITY=@PRIORITY
   WHERE POSITION_ID=@OLD_POSITION_ID;
END;

--

/* Создание процедуры удаления позиции плана */

CREATE PROCEDURE /*PREFIX*/D_POSITION
  @OLD_POSITION_ID VARCHAR(32)
AS
BEGIN
  DELETE FROM /*PREFIX*/POSITIONS
        WHERE POSITION_ID=@OLD_POSITION_ID;
END;

--