/* Создание таблицы движения документов */

CREATE TABLE /*PREFIX*/MOTIONS
(
  MOTION_ID VARCHAR(32) NOT NULL,
  POSITION_ID VARCHAR(32) NOT NULL,
  DOC_ID VARCHAR(32) NOT NULL,
  DATE_ISSUE DATETIME NOT NULL,
  ACCOUNT_ID VARCHAR(32),
  DATE_PROCESS DATETIME,
  DESCRIPTION VARCHAR(1000),
  PRIMARY KEY (MOTION_ID),
  FOREIGN KEY (POSITION_ID) REFERENCES /*PREFIX*/POSITIONS (POSITION_ID),
  FOREIGN KEY (DOC_ID) REFERENCES /*PREFIX*/DOCS (DOC_ID),
  FOREIGN KEY (ACCOUNT_ID) REFERENCES /*PREFIX*/ACCOUNTS (ACCOUNT_ID)
)

--

/* Создание просмотра таблицы движения документов */

CREATE VIEW /*PREFIX*/S_MOTIONS
AS
   SELECT M.*, 
          P.PRIORITY AS POSITION_PRIORITY,
          PL.NAME AS PLAN_NAME,
          D.NUM+' '+CONVERT(VARCHAR(10),D.DATE_DOC,104)+' '+D.NAME AS DOC_FULL_NAME,
          A.USER_NAME,
          F.SMALL_NAME AS FIRM_SMALL_NAME
     FROM /*PREFIX*/MOTIONS M
     JOIN /*PREFIX*/POSITIONS P ON P.POSITION_ID=M.POSITION_ID
     JOIN /*PREFIX*/PLANS PL ON PL.PLAN_ID=P.PLAN_ID
     JOIN /*PREFIX*/DOCS D ON D.DOC_ID=M.DOC_ID
     LEFT JOIN /*PREFIX*/ACCOUNTS A ON A.ACCOUNT_ID=M.ACCOUNT_ID
     LEFT JOIN /*PREFIX*/FIRMS F ON F.FIRM_ID=A.FIRM_ID

--

/* Создание процедуры добавления движения документу */

CREATE PROCEDURE /*PREFIX*/I_MOTION
  @MOTION_ID VARCHAR(32),
  @POSITION_ID VARCHAR(32),
  @DOC_ID VARCHAR(32),
  @DATE_ISSUE DATETIME,
  @ACCOUNT_ID VARCHAR(32),
  @DATE_PROCESS DATETIME,
  @DESCRIPTION VARCHAR(1000)
AS
BEGIN
  INSERT INTO /*PREFIX*/MOTIONS (MOTION_ID,POSITION_ID,DOC_ID,DATE_ISSUE,
                                 ACCOUNT_ID,DATE_PROCESS,DESCRIPTION)
       VALUES (@MOTION_ID,@POSITION_ID,@DOC_ID,@DATE_ISSUE,
               @ACCOUNT_ID,@DATE_PROCESS,@DESCRIPTION);
END;

--

/* Создание процедуры изменения движения документа */

CREATE PROCEDURE /*PREFIX*/U_MOTION
  @MOTION_ID VARCHAR(32),
  @POSITION_ID VARCHAR(32),
  @DOC_ID VARCHAR(32),
  @DATE_ISSUE DATETIME,
  @ACCOUNT_ID VARCHAR(32),
  @DATE_PROCESS DATETIME,
  @DESCRIPTION VARCHAR(1000),
  @OLD_MOTION_ID VARCHAR(32)
AS
BEGIN
  UPDATE /*PREFIX*/MOTIONS
     SET MOTION_ID=@MOTION_ID,
         POSITION_ID=@POSITION_ID,
         DOC_ID=@DOC_ID,
         DATE_ISSUE=@DATE_ISSUE,
         ACCOUNT_ID=@ACCOUNT_ID,
         DATE_PROCESS=@DATE_PROCESS,
         DESCRIPTION=@DESCRIPTION
   WHERE MOTION_ID=@OLD_MOTION_ID;
END;

--

/* Создание процедуры удаления движения документа */

CREATE PROCEDURE /*PREFIX*/D_MOTION
  @OLD_MOTION_ID VARCHAR(32)
AS
BEGIN
  DELETE FROM /*PREFIX*/MOTIONS
        WHERE MOTION_ID=@OLD_MOTION_ID;
END;

--