/* Создание процедуры изменения движения документа */

CREATE PROCEDURE /*PREFIX*/U_MANAGEMENT
  @MOTION_ID VARCHAR(32),
  @ACCOUNT_ID VARCHAR(32),
  @DESCRIPTION VARCHAR(1000),
  @STATUS INTEGER,
  @OLD_MOTION_ID VARCHAR(32)
AS
BEGIN
  DECLARE
     @POSITION_ID VARCHAR(32),
     @DOC_ID VARCHAR(32),
     @VIEW_ID VARCHAR(32),
     @PLAN_ID VARCHAR(32),
     @PRIORITY INTEGER,
     @DATE_ISSUE DATETIME,
     @NEW_MOTION_ID VARCHAR(32);

  IF (@STATUS=0) BEGIN

    UPDATE /*PREFIX*/MOTIONS
       SET MOTION_ID=@MOTION_ID,
           ACCOUNT_ID=NULL,
           DATE_PROCESS=NULL,
           DESCRIPTION=@DESCRIPTION
     WHERE MOTION_ID=@OLD_MOTION_ID;

  END ELSE BEGIN

    SET @DATE_ISSUE=CURRENT_TIMESTAMP;

    UPDATE /*PREFIX*/MOTIONS
       SET MOTION_ID=@MOTION_ID,
           ACCOUNT_ID=@ACCOUNT_ID,
           DATE_PROCESS=@DATE_ISSUE,
           DESCRIPTION=@DESCRIPTION
     WHERE MOTION_ID=@OLD_MOTION_ID;
    
    SELECT @DOC_ID=M.DOC_ID,
           @VIEW_ID=D.VIEW_ID,
           @PLAN_ID=P.PLAN_ID,
           @PRIORITY=P.PRIORITY
      FROM /*PREFIX*/MOTIONS M 
      JOIN /*PREFIX*/DOCS D ON D.DOC_ID=M.DOC_ID
      JOIN /*PREFIX*/POSITIONS P ON P.POSITION_ID=M.POSITION_ID
     WHERE M.MOTION_ID=@OLD_MOTION_ID
 
      
    IF (@DOC_ID IS NOT NULL) BEGIN
      
      SELECT TOP 1 @POSITION_ID=P.POSITION_ID
        FROM /*PREFIX*/POSITIONS P
       WHERE P.PLAN_ID=@PLAN_ID
         AND P.VIEW_ID=@VIEW_ID
         AND P.PRIORITY>@PRIORITY
       ORDER BY P.PRIORITY;
  
      IF (@POSITION_ID IS NOT NULL) BEGIN
        
        DELETE FROM /*PREFIX*/MOTIONS 
              WHERE POSITION_ID=@POSITION_ID
                AND DOC_ID=@DOC_ID;

        SET @NEW_MOTION_ID=(SELECT ID FROM S_GET_UNIQUE_ID);

        INSERT INTO /*PREFIX*/MOTIONS (MOTION_ID,POSITION_ID,DOC_ID,DATE_ISSUE) 
             VALUES (@NEW_MOTION_ID,@POSITION_ID,@DOC_ID,@DATE_ISSUE);
      END;
    END;
  END;
END;

--
