/* Создание просмотра планов по видам */

CREATE VIEW /*PREFIX*/S_PLAN_VIEWS
AS
SELECT P.PLAN_ID,
       PL.NAME AS PLAN_NAME,
       PL.DESCRIPTION AS PLAN_DESCRIPTION,
       V.VIEW_ID
  FROM /*PREFIX*/POSITIONS P
  JOIN /*PREFIX*/PLANS PL ON PL.PLAN_ID=P.PLAN_ID
  JOIN /*PREFIX*/VIEWS V ON V.VIEW_ID=P.VIEW_ID

--
