/* Создание процедуры получения первого раунда */

CREATE PROCEDURE /*PREFIX*/GET_FIRST_ROUND
(
  TIRAGE_ID VARCHAR(32)
)
RETURNS
(
  TICKET_COUNT INTEGER
)
AS
  DECLARE L1 INTEGER;
  DECLARE L2 INTEGER;
  DECLARE L3 INTEGER;
  DECLARE L4 INTEGER;
BEGIN
  TICKET_COUNT=0;

  SELECT COUNT(*)
    FROM /*PREFIX*/GET_TICKET_LINE(:TIRAGE_ID,1,1)
    INTO :L1;

  SELECT COUNT(*)
    FROM /*PREFIX*/GET_TICKET_LINE(:TIRAGE_ID,1,2)
    INTO :L2;

  SELECT COUNT(*)
    FROM /*PREFIX*/GET_TICKET_LINE(:TIRAGE_ID,1,3)
    INTO :L3;

  SELECT COUNT(*)
    FROM /*PREFIX*/GET_TICKET_LINE(:TIRAGE_ID,1,4)
    INTO :L4;

  TICKET_COUNT=L1+L2+L3+L4;
 -- SUSPEND;
END;

--

/* Фиксация изменений */

COMMIT