/* Создание таблицы типов фирм */

CREATE TABLE /*PREFIX*/FIRM_TYPES
(
  FIRM_TYPE_ID VARCHAR2(32) NOT NULL,
  NAME VARCHAR2(100) NOT NULL,
  DESCRIPTION VARCHAR2(250),
  PRIORITY INTEGER NOT NULL,
  PRIMARY KEY (FIRM_TYPE_ID)
)

--

/* Создание просмотра таблицы типов фирм */

CREATE OR REPLACE VIEW /*PREFIX*/S_FIRM_TYPES
AS
SELECT * FROM /*PREFIX*/FIRM_TYPES

--

/* Создание процедуры добавления типа фирмы */

CREATE OR REPLACE PROCEDURE /*PREFIX*/I_FIRM_TYPE
(
  FIRM_TYPE_ID IN VARCHAR2,
  NAME IN VARCHAR2,
  DESCRIPTION IN VARCHAR2,
  PRIORITY IN INTEGER
)
AS
BEGIN
  INSERT INTO /*PREFIX*/FIRM_TYPES (FIRM_TYPE_ID,NAME,DESCRIPTION,PRIORITY)
       VALUES (FIRM_TYPE_ID,NAME,DESCRIPTION,PRIORITY);
END;

--

/* Создание процедуры изменения типа фирмы */

CREATE OR REPLACE PROCEDURE /*PREFIX*/U_FIRM_TYPE
(
  FIRM_TYPE_ID IN VARCHAR2,
  NAME IN VARCHAR2,
  DESCRIPTION IN VARCHAR2,
  PRIORITY IN INTEGER,
  OLD_FIRM_TYPE_ID IN VARCHAR2
)
AS
BEGIN
  UPDATE /*PREFIX*/FIRM_TYPES
     SET FIRM_TYPE_ID=U_FIRM_TYPE.FIRM_TYPE_ID,
         NAME=U_FIRM_TYPE.NAME,
	     DESCRIPTION=U_FIRM_TYPE.DESCRIPTION,
		 PRIORITY=U_FIRM_TYPE.PRIORITY
   WHERE FIRM_TYPE_ID=OLD_FIRM_TYPE_ID;
END;

--

/* Создание процедуры удаления типа фирмы */

CREATE OR REPLACE PROCEDURE /*PREFIX*/D_FIRM_TYPE
(
  OLD_FIRM_TYPE_ID IN VARCHAR2
)
AS
BEGIN
  DELETE FROM /*PREFIX*/FIRM_TYPES 
        WHERE FIRM_TYPE_ID=OLD_FIRM_TYPE_ID;
END;

--

/* Фиксация изменений */

COMMIT