/* Создание таблицы приложений */

CREATE TABLE /*PREFIX*/APPLICATIONS
(
  APPLICATION_ID VARCHAR2(32) NOT NULL,
  NAME VARCHAR2(100) NOT NULL,
  DESCRIPTION VARCHAR2(250),
  LOCKED INTEGER DEFAULT 0 NOT NULL,
  PRIMARY KEY (APPLICATION_ID)
)

--

/* Создание просмотра таблицы приложений */

CREATE VIEW /*PREFIX*/S_APPLICATIONS
AS
SELECT * FROM /*PREFIX*/APPLICATIONS

--

/* Создание процедуры добавления приложения */

CREATE OR REPLACE PROCEDURE /*PREFIX*/I_APPLICATION
(
  APPLICATION_ID IN VARCHAR2,
  NAME IN VARCHAR2,
  DESCRIPTION IN VARCHAR2,
  LOCKED IN INTEGER
)
AS
BEGIN
  INSERT INTO /*PREFIX*/APPLICATIONS (APPLICATION_ID,NAME,DESCRIPTION,LOCKED)
       VALUES (APPLICATION_ID,NAME,DESCRIPTION,LOCKED);
END;

--

/* Создание процедуры изменения приложения */

CREATE OR REPLACE PROCEDURE /*PREFIX*/U_APPLICATION
(
  APPLICATION_ID IN VARCHAR2,
  NAME IN VARCHAR2,
  DESCRIPTION IN VARCHAR2,
  LOCKED IN INTEGER,
  OLD_APPLICATION_ID IN VARCHAR2
)
AS
BEGIN
  UPDATE /*PREFIX*/APPLICATIONS
     SET APPLICATION_ID=U_APPLICATION.APPLICATION_ID,
         NAME=U_APPLICATION.NAME,
	     DESCRIPTION=U_APPLICATION.DESCRIPTION,
		 LOCKED=U_APPLICATION.LOCKED
   WHERE APPLICATION_ID=OLD_APPLICATION_ID;
END;

--

/* Создание процедуры удаления приложения */

CREATE OR REPLACE PROCEDURE /*PREFIX*/D_APPLICATION
(
  OLD_APPLICATION_ID IN VARCHAR2
)
AS
BEGIN
  DELETE FROM /*PREFIX*/APPLICATIONS 
        WHERE APPLICATION_ID=OLD_APPLICATION_ID;
END;

--

/* Фиксация изменений */

COMMIT