/* Создание таблицы профилей */

CREATE TABLE /*PREFIX*/PROFILES
(
  ACCOUNT_ID VARCHAR2(32) NOT NULL,
  APPLICATION_ID VARCHAR2(32) NOT NULL,
  PROFILE BLOB,
  PRIMARY KEY (ACCOUNT_ID,APPLICATION_ID),
  FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS (ACCOUNT_ID),
  FOREIGN KEY (APPLICATION_ID) REFERENCES APPLICATIONS (APPLICATION_ID)
)

--

/* Создание просмотра таблицы профилей */

CREATE VIEW /*PREFIX*/S_PROFILES
AS
SELECT P.*,
       AC.USER_NAME AS USER_NAME,
       AP.NAME AS APPLICATION_NAME
  FROM /*PREFIX*/PROFILES P
  JOIN /*PREFIX*/ACCOUNTS AC ON AC.ACCOUNT_ID=P.ACCOUNT_ID
  JOIN /*PREFIX*/APPLICATIONS AP ON AP.APPLICATION_ID=P.APPLICATION_ID
			
--

/* Создание процедуры добавления профиля */

CREATE OR REPLACE PROCEDURE /*PREFIX*/I_PROFILE
(
  ACCOUNT_ID IN VARCHAR2,
  APPLICATION_ID IN VARCHAR2,
  PROFILE IN BLOB
)
AS
BEGIN
  INSERT INTO /*PREFIX*/PROFILES (ACCOUNT_ID,APPLICATION_ID,PROFILE)
       VALUES (ACCOUNT_ID,APPLICATION_ID,PROFILE);
END;

--

/* Создание процедуры изменения профиля */

CREATE OR REPLACE PROCEDURE /*PREFIX*/U_PROFILE
(
  ACCOUNT_ID IN VARCHAR2,
  APPLICATION_ID IN VARCHAR2,
  PROFILE IN BLOB,
  OLD_ACCOUNT_ID IN VARCHAR2,
  OLD_APPLICATION_ID IN VARCHAR2
)
AS
BEGIN
  UPDATE /*PREFIX*/PROFILES
     SET ACCOUNT_ID=U_PROFILE.ACCOUNT_ID,
         APPLICATION_ID=U_PROFILE.APPLICATION_ID,
         PROFILE=U_PROFILE.PROFILE
   WHERE ACCOUNT_ID=OLD_ACCOUNT_ID
     AND APPLICATION_ID=OLD_APPLICATION_ID;
END;

--

/* Создание процедуры удаления профиля */

CREATE OR REPLACE PROCEDURE /*PREFIX*/D_PROFILE
(
  OLD_ACCOUNT_ID IN VARCHAR2,
  OLD_APPLICATION_ID IN VARCHAR2
)
AS
BEGIN
  DELETE FROM /*PREFIX*/PROFILES 
        WHERE ACCOUNT_ID=OLD_ACCOUNT_ID
		  AND APPLICATION_ID=OLD_APPLICATION_ID;
END;

--

/* Фиксация изменений */

COMMIT