/* Создание таблицы сессий */

CREATE TABLE /*PREFIX*/SESSIONS
(
  SESSION_ID VARCHAR2(32) NOT NULL,
  ACCOUNT_ID VARCHAR2(32) NOT NULL,
  APPLICATION_ID VARCHAR2(32) NOT NULL,
  DATE_CREATE DATE NOT NULL,
  DATE_CHANGE DATE NOT NULL,
  PARAMS BLOB,
  PRIMARY KEY (SESSION_ID),
  FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS (ACCOUNT_ID),
  FOREIGN KEY (APPLICATION_ID) REFERENCES APPLICATIONS (APPLICATION_ID)
)

--

/* Создание просмотра таблицы сессий */

CREATE VIEW /*PREFIX*/S_SESSIONS
AS
   SELECT S.*, 
          AC.USER_NAME AS USER_NAME,
          AP.NAME AS APPLICATION_NAME
     FROM /*PREFIX*/SESSIONS S
     JOIN /*PREFIX*/ACCOUNTS AC ON AC.ACCOUNT_ID=S.ACCOUNT_ID
	 JOIN /*PREFIX*/APPLICATIONS AP ON AP.APPLICATION_ID=S.APPLICATION_ID

--

/* Создание процедуры добавления сессии */

CREATE OR REPLACE PROCEDURE /*PREFIX*/I_SESSION
(
  SESSION_ID IN VARCHAR2,
  ACCOUNT_ID IN VARCHAR2,
  APPLICATION_ID IN VARCHAR2,
  DATE_CREATE IN DATE,
  DATE_CHANGE IN DATE,
  PARAMS IN BLOB
)
AS
BEGIN
  INSERT INTO /*PREFIX*/SESSIONS (SESSION_ID,ACCOUNT_ID,APPLICATION_ID,DATE_CREATE,DATE_CHANGE,PARAMS)
       VALUES (SESSION_ID,ACCOUNT_ID,APPLICATION_ID,DATE_CREATE,DATE_CHANGE,PARAMS);
END;

--

/* Создание процедуры изменения сессии */

CREATE OR REPLACE PROCEDURE /*PREFIX*/U_SESSION
(
  SESSION_ID IN VARCHAR2,
  ACCOUNT_ID IN VARCHAR2,
  APPLICATION_ID IN VARCHAR2,
  DATE_CREATE IN DATE,
  DATE_CHANGE IN DATE,
  PARAMS IN BLOB,
  OLD_SESSION_ID IN VARCHAR2
)
AS
BEGIN
  UPDATE /*PREFIX*/SESSIONS
     SET SESSION_ID=U_SESSION.SESSION_ID,
         ACCOUNT_ID=U_SESSION.ACCOUNT_ID,
         APPLICATION_ID=U_SESSION.APPLICATION_ID,
         DATE_CREATE=U_SESSION.DATE_CREATE,
		 DATE_CHANGE=U_SESSION.DATE_CHANGE,
		 PARAMS=U_SESSION.PARAMS
   WHERE SESSION_ID=OLD_SESSION_ID;
END;

--

/* Создание процедуры удаления сессии */

CREATE OR REPLACE PROCEDURE /*PREFIX*/D_SESSION
(
  OLD_SESSION_ID IN VARCHAR2
)
AS
BEGIN
  DELETE FROM /*PREFIX*/SESSIONS
        WHERE SESSION_ID=OLD_SESSION_ID;
END;

--

/* Фиксация изменений */

COMMIT