/* Создание таблицы документов */

CREATE TABLE /*PREFIX*/DOCUMENTS
(
  DOCUMENT_ID VARCHAR2(32) NOT NULL,
  OLE_CLASS VARCHAR2(100) NOT NULL,
  DOCUMENT BLOB NOT NULL,
  PLACE INTEGER NOT NULL,
  PRIMARY KEY (DOCUMENT_ID),
  FOREIGN KEY (DOCUMENT_ID) REFERENCES /*PREFIX*/INTERFACES (INTERFACE_ID)
)

--

/* Создание просмотра таблицы документов */

CREATE VIEW /*PREFIX*/S_DOCUMENTS
AS
  SELECT D.*, 
         I.NAME AS INTERFACE_NAME
    FROM /*PREFIX*/DOCUMENTS D
    JOIN /*PREFIX*/INTERFACES I ON I.INTERFACE_ID=D.DOCUMENT_ID

--

/* Создание процедуры добавления документа */

CREATE OR REPLACE PROCEDURE /*PREFIX*/I_DOCUMENT
(
  DOCUMENT_ID IN VARCHAR2,
  OLE_CLASS IN VARCHAR2,
  DOCUMENT IN BLOB,
  PLACE IN INTEGER
)
AS
BEGIN
  INSERT INTO /*PREFIX*/DOCUMENTS (DOCUMENT_ID,OLE_CLASS,DOCUMENT,PLACE)
       VALUES (DOCUMENT_ID,OLE_CLASS,DOCUMENT,PLACE);
END;

--

/* Создание процедуры изменения документа */

CREATE OR REPLACE PROCEDURE /*PREFIX*/U_DOCUMENT
(
  DOCUMENT_ID IN VARCHAR2,
  OLE_CLASS IN VARCHAR2,
  DOCUMENT IN BLOB,
  PLACE IN INTEGER,
  OLD_DOCUMENT_ID IN VARCHAR2
)
AS
BEGIN
  UPDATE /*PREFIX*/DOCUMENTS
     SET DOCUMENT_ID=U_DOCUMENT.DOCUMENT_ID,
         OLE_CLASS=U_DOCUMENT.OLE_CLASS,
         DOCUMENT=U_DOCUMENT.DOCUMENT,
         PLACE=U_DOCUMENT.PLACE
   WHERE DOCUMENT_ID=OLD_DOCUMENT_ID;
END;

--

/* Создание процедуры удаления документа */

CREATE OR REPLACE PROCEDURE /*PREFIX*/D_DOCUMENT
(
  OLD_DOCUMENT_ID IN VARCHAR2
)
AS
BEGIN
  DELETE FROM /*PREFIX*/DOCUMENTS
        WHERE DOCUMENT_ID=OLD_DOCUMENT_ID;
END;

--

/* Фиксация изменений */

COMMIT