/* Создание таблицы прав интерфейсов */

CREATE TABLE /*PREFIX*/PERMISSIONS
(
  PERMISSION_ID VARCHAR2(32) NOT NULL,
  ACCOUNT_ID VARCHAR2(32) NOT NULL,
  INTERFACE_ID VARCHAR2(32) NOT NULL,
  RIGHT_ACCESS VARCHAR2(250) NOT NULL,
  VALUE VARCHAR2(250) NOT NULL,
  PRIMARY KEY (PERMISSION_ID),
  FOREIGN KEY (ACCOUNT_ID) REFERENCES /*PREFIX*/ACCOUNTS (ACCOUNT_ID),
  FOREIGN KEY (INTERFACE_ID) REFERENCES /*PREFIX*/INTERFACES (INTERFACE_ID)
)

--

/* Создание просмотра таблицы прав интерфейсов */

CREATE VIEW /*PREFIX*/S_PERMISSIONS
AS
   SELECT P.*, 
          A.USER_NAME AS USER_NAME,
          I.NAME AS INTERFACE_NAME
     FROM /*PREFIX*/PERMISSIONS P
     JOIN /*PREFIX*/ACCOUNTS A ON A.ACCOUNT_ID=P.ACCOUNT_ID
	 JOIN /*PREFIX*/INTERFACES I ON I.INTERFACE_ID=P.INTERFACE_ID

--

/* Создание процедуры добавления права */

CREATE OR REPLACE PROCEDURE /*PREFIX*/I_PERMISSION
(
  PERMISSION_ID IN VARCHAR2,
  ACCOUNT_ID IN VARCHAR2,
  INTERFACE_ID IN VARCHAR2,
  RIGHT_ACCESS IN VARCHAR2,
  VALUE IN VARCHAR2
)
AS
BEGIN
  INSERT INTO /*PREFIX*/PERMISSIONS (PERMISSION_ID,ACCOUNT_ID,INTERFACE_ID,RIGHT_ACCESS,VALUE)
       VALUES (PERMISSION_ID,ACCOUNT_ID,INTERFACE_ID,RIGHT_ACCESS,VALUE);
END;

--

/* Создание процедуры изменения права */

CREATE OR REPLACE PROCEDURE /*PREFIX*/U_PERMISSION
(
  PERMISSION_ID IN VARCHAR2,
  ACCOUNT_ID IN VARCHAR2,
  INTERFACE_ID IN VARCHAR2,
  RIGHT_ACCESS IN VARCHAR2,
  VALUE IN VARCHAR2,
  OLD_PERMISSION_ID IN VARCHAR2
)
AS
BEGIN
  UPDATE /*PREFIX*/PERMISSIONS
     SET PERMISSION_ID=U_PERMISSION.PERMISSION_ID,
         ACCOUNT_ID=U_PERMISSION.ACCOUNT_ID,
         INTERFACE_ID=U_PERMISSION.INTERFACE_ID,
         RIGHT_ACCESS=U_PERMISSION.RIGHT_ACCESS,
		 VALUE=U_PERMISSION.VALUE
   WHERE PERMISSION_ID=OLD_PERMISSION_ID;
END;

--

/* Создание процедуры удаления права */

CREATE OR REPLACE PROCEDURE /*PREFIX*/D_PERMISSION
(
  OLD_PERMISSION_ID IN VARCHAR2
)
AS
BEGIN
  DELETE FROM /*PREFIX*/PERMISSIONS
        WHERE PERMISSION_ID=OLD_PERMISSION_ID;
END;

--

/* Фиксация изменений */

COMMIT