/* Создание таблицы меню */

CREATE TABLE /*PREFIX*/MENUS
(
  MENU_ID VARCHAR2(32) NOT NULL,
  INTERFACE_ID VARCHAR2(32),
  PARENT_ID VARCHAR2(32),
  NAME VARCHAR2(100) NOT NULL,
  DESCRIPTION VARCHAR2(250),
  PRIORITY INTEGER NOT NULL,
  SHORTCUT INTEGER,
  PICTURE BLOB,
  "LEVEL" INTEGER NOT NULL,
  PRIMARY KEY (MENU_ID),
  FOREIGN KEY (INTERFACE_ID) REFERENCES INTERFACES (INTERFACE_ID),
  FOREIGN KEY (PARENT_ID) REFERENCES MENUS (MENU_ID)
)

--

/* Создание просмотра таблицы меню */

CREATE VIEW /*PREFIX*/S_MENUS
AS
   SELECT M.*, 
          I.NAME AS INTERFACE_NAME,
          M1.NAME AS PARENT_NAME					
     FROM /*PREFIX*/MENUS M
     LEFT JOIN /*PREFIX*/INTERFACES I ON I.INTERFACE_ID=M.INTERFACE_ID
     LEFT JOIN	/*PREFIX*/MENUS M1 ON M1.MENU_ID=M.PARENT_ID

--

/* Создание процедуры добавления меню */

CREATE OR REPLACE PROCEDURE /*PREFIX*/I_MENU
(
  MENU_ID IN VARCHAR2,
  INTERFACE_ID IN VARCHAR2,
  PARENT_ID IN VARCHAR2,
  NAME IN VARCHAR2,
  DESCRIPTION IN VARCHAR2,
  PRIORITY IN INTEGER,
  SHORTCUT IN INTEGER,
  PICTURE IN BLOB
)
AS
  LV INTEGER;
BEGIN
  IF (PARENT_ID IS NULL) THEN
	LV:=1;
  ELSE
	SELECT "LEVEL"+1 INTO LV 
	  FROM /*PREFIX*/MENUS
	 WHERE MENU_ID=I_MENU.PARENT_ID;
  END IF;
  
  INSERT INTO /*PREFIX*/MENUS (MENU_ID,INTERFACE_ID,PARENT_ID,NAME,DESCRIPTION,PRIORITY,SHORTCUT,PICTURE,"LEVEL")
       VALUES (MENU_ID,INTERFACE_ID,PARENT_ID,NAME,DESCRIPTION,PRIORITY,SHORTCUT,PICTURE,LV);
END;

--

/* Создание процедуры обновления уровней меню */

CREATE OR REPLACE PROCEDURE /*PREFIX*/R_MENU_LEVELS
(
  PARENT_ID IN VARCHAR2,
  LEVEL IN INTEGER
)
AS
  L INTEGER;
BEGIN
  FOR INC IN (SELECT M.MENU_ID
                FROM /*PREFIX*/MENUS M 
			   WHERE M.PARENT_ID=R_MENU_LEVELS.PARENT_ID) LOOP
    L:=LEVEL+1;
	
	UPDATE /*PREFIX*/MENUS
	   SET "LEVEL"=L
	 WHERE MENU_ID=INC.MENU_ID;
	 
    /*PREFIX*/R_MENU_LEVELS(INC.MENU_ID,L);
			   
  END LOOP;	     
END;

--

/* Создание процедуры изменения меню */

CREATE OR REPLACE PROCEDURE /*PREFIX*/U_MENU
(
  MENU_ID IN VARCHAR2,
  INTERFACE_ID IN VARCHAR2,
  PARENT_ID IN VARCHAR2,
  NAME IN VARCHAR2,
  DESCRIPTION IN VARCHAR2,
  PRIORITY IN INTEGER,
  SHORTCUT IN INTEGER,
  PICTURE IN BLOB,
  OLD_MENU_ID IN VARCHAR2
)
AS
  LV INTEGER;
BEGIN
  IF (PARENT_ID IS NULL) THEN
	LV:=1;
  ELSE
	SELECT "LEVEL"+1 INTO LV 
	  FROM /*PREFIX*/MENUS
	 WHERE MENU_ID=U_MENU.PARENT_ID;
  END IF;

  UPDATE /*PREFIX*/MENUS
     SET MENU_ID=U_MENU.MENU_ID,
         INTERFACE_ID=U_MENU.INTERFACE_ID,
		 PARENT_ID=U_MENU.PARENT_ID,
		 NAME=U_MENU.NAME,
		 DESCRIPTION=U_MENU.DESCRIPTION,
		 PRIORITY=U_MENU.PRIORITY,
		 SHORTCUT=U_MENU.SHORTCUT,
		 PICTURE=U_MENU.PICTURE,
		 "LEVEL"=LV
   WHERE MENU_ID=OLD_MENU_ID;
   
  /*PREFIX*/R_MENU_LEVELS(MENU_ID,LV);
END;

--

/* Создание процедуры удаления меню */

CREATE OR REPLACE PROCEDURE /*PREFIX*/D_MENU
(
  OLD_MENU_ID IN VARCHAR2
)
AS
BEGIN
  DELETE FROM /*PREFIX*/MENUS
        WHERE MENU_ID=OLD_MENU_ID;
END;

--

/* Фиксация изменений */

COMMIT