/* Создание таблицы журнала действий */

CREATE TABLE /*PREFIX*/JOURNAL_ACTIONS
(
  JOURNAL_ACTION_ID VARCHAR2(32) NOT NULL,
  ACCOUNT_ID VARCHAR2(32) NOT NULL,
  APPLICATION_ID VARCHAR2(32) NOT NULL,
  ACTION_TYPE INTEGER NOT NULL,
  DATE_ACTION DATE NOT NULL,
  MODULE VARCHAR2(250),
  OBJECT VARCHAR2(250),
  METHOD VARCHAR2(250),
  PARAM VARCHAR2(250),
  VALUE BLOB NOT NULL,
  PRIMARY KEY (JOURNAL_ACTION_ID),
  FOREIGN KEY (ACCOUNT_ID) REFERENCES /*PREFIX*/ACCOUNTS (ACCOUNT_ID),
  FOREIGN KEY (APPLICATION_ID) REFERENCES /*PREFIX*/APPLICATIONS (APPLICATION_ID)
)

--

/* Создание просмотра таблицы журнала действий */

CREATE VIEW /*PREFIX*/S_JOURNAL_ACTIONS
AS
   SELECT JA.*, 
          A.USER_NAME AS USER_NAME,
          AP.NAME AS APPLICATION_NAME
     FROM /*PREFIX*/JOURNAL_ACTIONS JA
     JOIN /*PREFIX*/ACCOUNTS A ON A.ACCOUNT_ID=JA.ACCOUNT_ID
     JOIN /*PREFIX*/APPLICATIONS AP ON AP.APPLICATION_ID=JA.APPLICATION_ID

--

/* Создание процедуры добавления действия в журнал */

CREATE OR REPLACE PROCEDURE /*PREFIX*/I_JOURNAL_ACTION
(
  JOURNAL_ACTION_ID IN VARCHAR2,
  ACCOUNT_ID IN VARCHAR2,
  APPLICATION_ID IN VARCHAR2,
  ACTION_TYPE IN INTEGER,
  DATE_ACTION IN DATE,
  MODULE IN VARCHAR2,
  OBJECT IN VARCHAR2,
  METHOD IN VARCHAR2,
  PARAM IN VARCHAR2,
  VALUE IN BLOB
)
AS
BEGIN
  INSERT INTO /*PREFIX*/JOURNAL_ACTIONS (JOURNAL_ACTION_ID,ACCOUNT_ID,APPLICATION_ID,ACTION_TYPE,
	                                     DATE_ACTION,MODULE,OBJECT,METHOD,PARAM,VALUE)
       VALUES (JOURNAL_ACTION_ID,ACCOUNT_ID,APPLICATION_ID,ACTION_TYPE,
	           DATE_ACTION,MODULE,OBJECT,METHOD,PARAM,VALUE);
END;

--

/* Создание процедуры изменения действия в журнале */

CREATE OR REPLACE PROCEDURE /*PREFIX*/U_JOURNAL_ACTION
(
  JOURNAL_ACTION_ID IN VARCHAR2,
  ACCOUNT_ID IN VARCHAR2,
  APPLICATION_ID IN VARCHAR2,
  ACTION_TYPE IN INTEGER,
  DATE_ACTION IN DATE,
  MODULE IN VARCHAR2,
  OBJECT IN VARCHAR2,
  METHOD IN VARCHAR2,
  PARAM IN VARCHAR2,
  VALUE IN BLOB,
  OLD_JOURNAL_ACTION_ID IN VARCHAR2
)
AS
BEGIN
  UPDATE /*PREFIX*/JOURNAL_ACTIONS
     SET JOURNAL_ACTION_ID=U_JOURNAL_ACTION.JOURNAL_ACTION_ID,
         ACCOUNT_ID=U_JOURNAL_ACTION.ACCOUNT_ID,
         APPLICATION_ID=U_JOURNAL_ACTION.APPLICATION_ID,
         ACTION_TYPE=U_JOURNAL_ACTION.ACTION_TYPE,
         DATE_ACTION=U_JOURNAL_ACTION.DATE_ACTION,
         MODULE=U_JOURNAL_ACTION.MODULE,
         OBJECT=U_JOURNAL_ACTION.OBJECT,
         METHOD=U_JOURNAL_ACTION.METHOD,
         PARAM=U_JOURNAL_ACTION.PARAM,
         VALUE=U_JOURNAL_ACTION.VALUE
   WHERE JOURNAL_ACTION_ID=OLD_JOURNAL_ACTION_ID;
END;

--

/* Создание процедуры удаления действия из журнала */

CREATE OR REPLACE PROCEDURE /*PREFIX*/D_JOURNAL_ACTION
(
  OLD_JOURNAL_ACTION_ID IN VARCHAR2
)
AS
BEGIN
  DELETE FROM /*PREFIX*/JOURNAL_ACTIONS
        WHERE JOURNAL_ACTION_ID=OLD_JOURNAL_ACTION_ID;
END;

--

/* Фиксация изменений */

COMMIT