/* Создание таблицы констант */

CREATE TABLE /*PREFIX*/CONSTS
(
  NAME VARCHAR2(100) NOT NULL,
  DESCRIPTION VARCHAR2(250),
  VALUE BLOB NOT NULL,
  PRIMARY KEY (NAME)
)

--

/* Создание просмотра таблицы констант */

CREATE VIEW /*PREFIX*/S_CONSTS
AS
SELECT * FROM /*PREFIX*/CONSTS

--

/* Создание процедуры добавления константы */

CREATE OR REPLACE PROCEDURE /*PREFIX*/I_CONST
(
  NAME IN VARCHAR2,
  DESCRIPTION IN VARCHAR2,
  VALUE IN BLOB
)
AS
BEGIN
  INSERT INTO /*PREFIX*/CONSTS (NAME,DESCRIPTION,VALUE)
       VALUES (NAME,DESCRIPTION,VALUE);
END;

--

/* Создание процедуры изменения константы */

CREATE OR REPLACE PROCEDURE /*PREFIX*/U_CONST
(
  NAME IN VARCHAR2,
  DESCRIPTION IN VARCHAR2,
  VALUE IN BLOB,
  OLD_NAME IN VARCHAR2
)
AS
BEGIN
  UPDATE /*PREFIX*/CONSTS
     SET NAME=U_CONST.NAME,
         DESCRIPTION=U_CONST.DESCRIPTION,
         VALUE=U_CONST.VALUE
   WHERE NAME=OLD_NAME;
END;

--

/* Создание процедуры удаления константы */

CREATE OR REPLACE PROCEDURE /*PREFIX*/D_CONST
(
  OLD_NAME IN VARCHAR2
)
AS
BEGIN
  DELETE FROM /*PREFIX*/CONSTS 
        WHERE NAME=OLD_NAME;
END;

--

/* Фиксация изменений */

COMMIT