CREATE GLOBAL TEMPORARY TABLE TMP_WINNINGS
(
  TICKET_ID VARCHAR(32) NOT NULL,
  ROUND_NUM INTEGER NOT NULL,
  SUBROUND_ID VARCHAR(32)
  LOTTERY_ID VARCHAR(32) NOT NULL,
) ON COMMIT PRESERVE ROWS

--

CREATE INDEX IDX_TMP_WINNINGS_ROUND_NUM
ON TMP_WINNINGS (ROUND_NUM)

--

CREATE INDEX IDX_TMP_WINNINGS_SUBROUND_ID
ON TMP_WINNINGS (SUBROUND_ID)

--

