u:
cd u:\bin
copy cmhttp.bpl u:\install\taxi\free\cmhttp.bpl /Y
copy cmuibase.bpl u:\install\taxi\free\cmuibase.bpl /Y
copy core.bpl u:\install\taxi\free\core.bpl /Y
copy imaudio.bpl u:\install\taxi\free\imaudio.bpl /Y
copy imcall.bpl u:\install\taxi\free\imcall.bpl /Y
copy imdesign.bpl u:\install\taxi\free\imdesign.bpl /Y
copy imimport.bpl u:\install\taxi\free\imimport.bpl /Y
copy immap.bpl u:\install\taxi\free\immap.bpl /Y
copy immess.bpl u:\install\taxi\free\immess.bpl /Y
copy imsecure.bpl u:\install\taxi\free\imsecure.bpl /Y
copy imsupport.bpl u:\install\taxi\free\imsupport.bpl /Y
copy imtaxi.bpl u:\install\taxi\free\imtaxi.bpl /Y
copy inet100.bpl u:\install\taxi\free\inet100.bpl /Y
copy objects.bpl u:\install\taxi\free\objects.bpl /Y
copy omaudio.bpl u:\install\taxi\free\omaudio.bpl /Y
copy omcom.bpl u:\install\taxi\free\omcom.bpl /Y
copy omnet.bpl u:\install\taxi\free\omnet.bpl /Y
copy rpmfast.bpl u:\install\taxi\free\rpmfast.bpl /Y
copy rtl100.bpl u:\install\taxi\free\rpmfast.bpl /Y
copy smcall.bpl u:\install\taxi\free\smcall.bpl /Y
copy smcallback.bpl u:\install\taxi\free\smcallback.bpl /Y
copy smcallevt.bpl u:\install\taxi\free\smcallevt.bpl /Y
copy smcallsip.bpl u:\install\taxi\free\smcallsip.bpl /Y
copy smgsm.bpl u:\install\taxi\free\smgsm.bpl /Y
copy smhttp.bpl u:\install\taxi\free\smhttp.bpl /Y
copy smhttpdef.bpl u:\install\taxi\free\smhttpdef.bpl /Y
copy smhttpfls.bpl u:\install\taxi\free\smhttpfls.bpl /Y
copy smhttping.bpl u:\install\taxi\free\smhttping.bpl /Y
copy smhttpmap.bpl u:\install\taxi\free\smhttpmap.bpl /Y
copy smhttpmob.bpl u:\install\taxi\free\smhttpmob.bpl /Y
copy smhttpplt.bpl u:\install\taxi\free\smhttpplt.bpl /Y
copy smhttpsup.bpl u:\install\taxi\free\smhttpsup.bpl /Y
copy smhttpupd.bpl u:\install\taxi\free\smhttpupd.bpl /Y
copy smsmpp.bpl u:\install\taxi\free\smsmpp.bpl /Y
copy smtaxi.bpl u:\install\taxi\free\smtaxi.bpl /Y
copy smudpevt.bpl u:\install\taxi\free\smudpevt.bpl /Y
copy tee7100.bpl u:\install\taxi\free\tee7100.bpl /Y
copy teedb7100.bpl u:\install\taxi\free\teedb7100.bpl /Y
copy teeui7100.bpl u:\install\taxi\free\teeui7100.bpl /Y
copy vcl100.bpl u:\install\taxi\free\vcl100.bpl /Y
copy vclactnband100.bpl u:\install\taxi\free\vclactnband100.bpl /Y
copy vcldb100.bpl u:\install\taxi\free\vcldb100.bpl /Y
copy vcliex100.bpl u:\install\taxi\free\vcliex100.bpl /Y
copy vclimg100.bpl u:\install\taxi\free\vclimg100.bpl /Y
copy vcljpg100.bpl u:\install\taxi\free\vcljpg100.bpl /Y
copy vclx100.bpl u:\install\taxi\free\vclx100.bpl /Y
copy udfibase.dll u:\install\taxi\free\udfibase.bpl /Y
copy taxi.exe u:\install\taxi\free\taxi.exe /Y
copy u:\java\TaxiMobileClient\dist\taxi.jar u:\install\taxi\free\taxi.jar /Y
copy cmhttp.map u:\install\taxi\free\cmhttp.map /Y
copy cmuibase.map u:\install\taxi\free\cmuibase.map /Y
copy core.map u:\install\taxi\free\core.map /Y
copy imaudio.map u:\install\taxi\free\imaudio.map /Y
copy imcall.map u:\install\taxi\free\imcall.map /Y
copy imdesign.map u:\install\taxi\free\imdesign.map /Y
copy imimport.map u:\install\taxi\free\imimport.map /Y
copy immap.map u:\install\taxi\free\immap.map /Y
copy immess.map u:\install\taxi\free\immess.map /Y
copy imsecure.map u:\install\taxi\free\imsecure.map /Y
copy imsupport.map u:\install\taxi\free\imsupport.map /Y
copy imtaxi.map u:\install\taxi\free\imtaxi.map /Y
copy objects.map u:\install\taxi\free\objects.map /Y
copy omaudio.map u:\install\taxi\free\omaudio.map /Y
copy omcom.map u:\install\taxi\free\omcom.map /Y
copy omnet.map u:\install\taxi\free\omnet.map /Y
copy rpmfast.map u:\install\taxi\free\rpmfast.map /Y
copy smcall.map u:\install\taxi\free\smcall.map /Y
copy smcallback.map u:\install\taxi\free\smcallback.map /Y
copy smcallevt.map u:\install\taxi\free\smcallevt.map /Y
copy smcallsip.map u:\install\taxi\free\smcallsip.map /Y
copy smgsm.map u:\install\taxi\free\smgsm.map /Y
copy smhttp.map u:\install\taxi\free\smhttp.map /Y
copy smhttpdef.map u:\install\taxi\free\smhttpdef.map /Y
copy smhttpfls.map u:\install\taxi\free\smhttpfls.map /Y
copy smhttping.map u:\install\taxi\free\smhttping.map /Y
copy smhttpmap.map u:\install\taxi\free\smhttpmap.map /Y
copy smhttpmob.map u:\install\taxi\free\smhttpmob.map /Y
copy smhttpplt.map u:\install\taxi\free\smhttpplt.map /Y
copy smhttpsup.map u:\install\taxi\free\smhttpsup.map /Y
copy smhttpupd.map u:\install\taxi\free\smhttpupd.map /Y
copy smsmpp.map u:\install\taxi\free\smsmpp.map /Y
copy smtaxi.map u:\install\taxi\free\smtaxi.map /Y
copy smudpevt.map u:\install\taxi\free\smudpevt.map /Y
copy taxi.map u:\install\taxi\free\taxi.map /Y
copy u:\java\config.xml u:\install\taxi\free\config.xml /Y

