CREATE OR ALTER PROCEDURE GET_ROUTE_BY_STREETS
(
  FROM_STREET_ID VARCHAR(32),
  FROM_HOUSE VARCHAR(10),
  TO_STREET_ID VARCHAR(32),
  TO_HOUSE VARCHAR(10)
)
RETURNS
(
  DISTANCE DOUBLE PRECISION,
  DURATION INTEGER
)
AS
DECLARE RET BLOB;
DECLARE DIS INTEGER;
DECLARE DUR INTEGER;
DECLARE S VARCHAR(100);
DECLARE PARAMS VARCHAR(250);
DECLARE DIST DOUBLE PRECISION;
DECLARE HOST VARCHAR(50) = '192.168.0.7';
DECLARE PORT VARCHAR(10) = '55508';
BEGIN
  DISTANCE=0.0;
  DURATION=0;

  FOR SELECT DISTANCE, DURATION
        FROM MAP_ROUTES
       WHERE FROM_STREET_ID=:FROM_STREET_ID
         AND FROM_HOUSE=:FROM_HOUSE
         AND TO_STREET_ID=:TO_STREET_ID
         AND TO_HOUSE=:TO_HOUSE
        INTO :DIS, :DUR DO BEGIN
    BREAK;
  END

/*  IF ((LAT1 IS NOT NULL) AND
      (LON1 IS NOT NULL) AND
      (LAT2 IS NOT NULL) AND
      (LON2 IS NOT NULL) AND
      (SERVER_EXISTS(HOST,PORT,500)=1)) THEN BEGIN

    PARAMS='?Lat1='||CAST(CAST(LAT1 AS NUMERIC(12,9)) AS VARCHAR(30))||
           '&Lon1='||CAST(CAST(LON1 AS NUMERIC(12,9)) AS VARCHAR(30))||
           '&Lat2='||CAST(CAST(LAT2 AS NUMERIC(12,9)) AS VARCHAR(30))||
           '&Lon2='||CAST(CAST(LON2 AS NUMERIC(12,9)) AS VARCHAR(30));

    RET=HTTP_GET(HOST,PORT,'/ingitmap','','',PARAMS,5000);

    IF (RET IS NOT NULL) THEN BEGIN

      S=SUBSTRING(RET FROM 1 FOR 100);

      DISTANCE=CAST(S AS NUMERIC(15,2));

      PARAMS='?Lat1='||CAST(CAST(LAT2 AS NUMERIC(12,9)) AS VARCHAR(30))||
             '&Lon1='||CAST(CAST(LON2 AS NUMERIC(12,9)) AS VARCHAR(30))||
             '&Lat2='||CAST(CAST(LAT1 AS NUMERIC(12,9)) AS VARCHAR(30))||
             '&Lon2='||CAST(CAST(LON1 AS NUMERIC(12,9)) AS VARCHAR(30));

      RET=HTTP_GET(HOST,PORT,'/ingitmap','','',PARAMS,5000);
      S=SUBSTRING(RET FROM 1 FOR 100);
      DIST=CAST(S AS NUMERIC(15,2));

      DISTANCE = IIF(DISTANCE < DIST, DISTANCE, DIST);

    END

  END */

END
