CREATE OR ALTER PROCEDURE GET_ROUTE_BY_COORDINATES
(
  FROM_LAT DOUBLE PRECISION,
  FROM_LON DOUBLE PRECISION,
  TO_LAT DOUBLE PRECISION,
  TO_LON DOUBLE PRECISION
)
RETURNS
(
  DISTANCE DOUBLE PRECISION,
  DURATION INTEGER
)
AS
DECLARE RET BLOB;
DECLARE S VARCHAR(100);
DECLARE PARAMS VARCHAR(250);
DECLARE DIS DOUBLE PRECISION;
DECLARE DUR INTEGER;
DECLARE LAT1 VARCHAR(10);
DECLARE LAT2 VARCHAR(10);
DECLARE LON1 VARCHAR(10);
DECLARE LON2 VARCHAR(10);

DECLARE HOST VARCHAR(50) = '192.168.0.7';
DECLARE PORT VARCHAR(10) = '55508';

BEGIN
  DISTANCE=NULL;
  DURATION=NULL;

  IF ((FROM_LAT IS NOT NULL) AND
      (FROM_LON IS NOT NULL) AND
      (TO_LAT IS NOT NULL) AND
      (TO_LON IS NOT NULL)) THEN BEGIN

    LAT1=CAST(CAST(FROM_LAT AS NUMERIC(7,4)) AS VARCHAR(10));
    LON1=CAST(CAST(FROM_LON AS NUMERIC(7,4)) AS VARCHAR(10));
    LAT2=CAST(CAST(TO_LAT AS NUMERIC(7,4)) AS VARCHAR(10));
    LON2=CAST(CAST(TO_LON AS NUMERIC(7,4)) AS VARCHAR(10));



  END

/*  IF ((LAT1 IS NOT NULL) AND
      (LON1 IS NOT NULL) AND
      (LAT2 IS NOT NULL) AND
      (LON2 IS NOT NULL) AND
      (SERVER_EXISTS(HOST,PORT,500)=1)) THEN BEGIN

    PARAMS='?Lat1='||CAST(CAST(LAT1 AS NUMERIC(12,9)) AS VARCHAR(30))||
           '&Lon1='||CAST(CAST(LON1 AS NUMERIC(12,9)) AS VARCHAR(30))||
           '&Lat2='||CAST(CAST(LAT2 AS NUMERIC(12,9)) AS VARCHAR(30))||
           '&Lon2='||CAST(CAST(LON2 AS NUMERIC(12,9)) AS VARCHAR(30));

    RET=HTTP_GET(HOST,PORT,'/ingitmap','','',PARAMS,5000);

    IF (RET IS NOT NULL) THEN BEGIN

      S=SUBSTRING(RET FROM 1 FOR 100);

      DISTANCE=CAST(S AS NUMERIC(15,2));

      PARAMS='?Lat1='||CAST(CAST(LAT2 AS NUMERIC(12,9)) AS VARCHAR(30))||
             '&Lon1='||CAST(CAST(LON2 AS NUMERIC(12,9)) AS VARCHAR(30))||
             '&Lat2='||CAST(CAST(LAT1 AS NUMERIC(12,9)) AS VARCHAR(30))||
             '&Lon2='||CAST(CAST(LON1 AS NUMERIC(12,9)) AS VARCHAR(30));

      RET=HTTP_GET(HOST,PORT,'/ingitmap','','',PARAMS,5000);
      S=SUBSTRING(RET FROM 1 FOR 100);
      DIST=CAST(S AS NUMERIC(15,2));

      DISTANCE = IIF(DISTANCE < DIST, DISTANCE, DIST);

    END

  END */

END
