CREATE OR ALTER PROCEDURE GET_CLIENT_SUM (
  CLIENT_ID VARCHAR(32),
  COST NUMERIC(15,2)) 
RETURNS (
  RET_SUM NUMERIC(15,2))
AS
declare variable TYPE_CALC integer;
declare variable PERCENT numeric(4,2);
declare variable CALC_SUM numeric(15,2);
declare variable PROC_NAME varchar(100);
BEGIN
  RET_SUM=COST;

  IF ((CLIENT_ID IS NOT NULL) AND (COST IS NOT NULL)) THEN BEGIN

    SELECT CL.TYPE_CALC, CL.PERCENT, CL.CALC_SUM, CL.PROC_NAME
      FROM /*PREFIX*/CLIENTS C
      JOIN /*PREFIX*/CALCS CL ON CL.CALC_ID=C.CALC_ID
     WHERE C.CLIENT_ID=:CLIENT_ID
      INTO :TYPE_CALC, :PERCENT, :CALC_SUM, :PROC_NAME;

    IF (TYPE_CALC=0) THEN
      RET_SUM=COST;

    IF (TYPE_CALC=1) THEN
      RET_SUM=COST;

    IF ((TYPE_CALC=2) AND (PERCENT IS NOT NULL)) THEN BEGIN

      RET_SUM=(COST*PERCENT)/100;
      if (RET_SUM>60.0) then RET_SUM=60.0;

    END

    IF ((TYPE_CALC=3) AND (CALC_SUM IS NOT NULL)) THEN BEGIN

      RET_SUM=COST-CALC_SUM;

    END

  END

  SUSPEND;

END
