/* Создание таблицы доступа к действиям */

CREATE TABLE /*PREFIX*/ACTION_ACCOUNTS
(
  ACTION_ID VARCHAR(32) NOT NULL,
  ACCOUNT_ID VARCHAR(32) NOT NULL,
  PRIORITY INTEGER,
  PRIMARY KEY (ACTION_ID,ACCOUNT_ID),
  FOREIGN KEY (ACTION_ID) REFERENCES /*PREFIX*/ACTIONS (ACTION_ID),
  FOREIGN KEY (ACCOUNT_ID) REFERENCES /*PREFIX*/ACCOUNTS (ACCOUNT_ID)
)

--

/* Создание просмотра доступа к действиям */

CREATE VIEW /*PREFIX*/S_ACTION_ACCOUNTS
(
  ACTION_ID,
  ACCOUNT_ID,
  PRIORITY,
  ACTION_NAME,
  USER_NAME
)
AS
SELECT AA.*,
       AC.NAME AS ACTION_NAME,
       AN.USER_NAME
  FROM /*PREFIX*/ACTION_ACCOUNTS AA
  JOIN /*PREFIX*/ACTIONS AC ON AC.ACTION_ID=AA.ACTION_ID
  JOIN /*PREFIX*/ACCOUNTS AN ON AN.ACCOUNT_ID=AA.ACCOUNT_ID

--

/* Создание процедуры добавления доступа к действию */

CREATE PROCEDURE /*PREFIX*/I_ACTION_ACCOUNT
(
  ACTION_ID VARCHAR(32),
  ACCOUNT_ID VARCHAR(32),
  PRIORITY INTEGER
)
AS
BEGIN
  INSERT INTO /*PREFIX*/ACTION_ACCOUNTS (ACTION_ID,ACCOUNT_ID,PRIORITY)
       VALUES (:ACTION_ID,:ACCOUNT_ID,:PRIORITY);
END;

--

/* Создание процедуры изменения доступа к действию */

CREATE PROCEDURE /*PREFIX*/U_ACTION_ACCOUNT
(
  ACTION_ID VARCHAR(32),
  ACCOUNT_ID VARCHAR(32),
  PRIORITY INTEGER,
  OLD_ACTION_ID VARCHAR(32),
  OLD_ACCOUNT_ID VARCHAR(32)
)
AS
BEGIN
  UPDATE /*PREFIX*/ACTION_ACCOUNTS
     SET ACTION_ID=:ACTION_ID,
         ACCOUNT_ID=:ACCOUNT_ID,
         PRIORITY=:PRIORITY
   WHERE ACTION_ID=:OLD_ACTION_ID
     AND ACCOUNT_ID=:OLD_ACCOUNT_ID;
END;

--

/* Создание процедуры удаления доступа к действию */

CREATE PROCEDURE /*PREFIX*/D_ACTION_ACCOUNT
(
  OLD_ACTION_ID VARCHAR(32),
  OLD_ACCOUNT_ID VARCHAR(32)
)
AS
BEGIN
  DELETE FROM /*PREFIX*/ACTION_ACCOUNTS 
        WHERE ACTION_ID=:OLD_ACTION_ID
          AND ACCOUNT_ID=:OLD_ACCOUNT_ID;
END;

--

/* Фиксация изменений */

COMMIT