/* Создание процедуры обработки результата нет водителя */

CREATE PROCEDURE /*PREFIX*/PR_NO_DRIVER
(
  ORDER_ID VARCHAR(32),
  ACCOUNT_ID VARCHAR(32)
)
AS
  DECLARE PARK_ID VARCHAR(32);
  DECLARE DRIVER_ID VARCHAR(32);
  DECLARE CNT INTEGER;
  DECLARE BALANCE NUMERIC(15,2);
  DECLARE S VARCHAR(1000);
  DECLARE PREFIX VARCHAR(10);
  DECLARE STREET VARCHAR(100);
  DECLARE HOUSE VARCHAR(10);
  DECLARE FLAT VARCHAR(10);
  DECLARE PORCH VARCHAR(10);
  DECLARE LOCALITY VARCHAR(100);
  DECLARE PHONE VARCHAR(100);
  DECLARE DATE_END TIMESTAMP;
  DECLARE DATE_ACCEPT TIMESTAMP;
  DECLARE DATE_ARRIVAL TIMESTAMP;
  DECLARE BEFORE_PERIOD INTEGER;
  DECLARE D TIMESTAMP;
BEGIN

  SELECT O.PARK_ID, O.DRIVER_ID,
         S.PREFIX, S.NAME, O.HOUSE, O.FLAT, O.PORCH, L.NAME,
         O.DATE_END, O.DATE_ACCEPT, O.DATE_ARRIVAL, O.BEFORE_PERIOD
    FROM /*PREFIX*/ORDERS O
    JOIN /*PREFIX*/STREETS S ON S.STREET_ID=O.STREET_ID
    JOIN /*PREFIX*/LOCALITIES L ON L.LOCALITY_ID=S.LOCALITY_ID
   WHERE O.ORDER_ID=:ORDER_ID
     INTO :PARK_ID, :DRIVER_ID,
          :PREFIX, :STREET, :HOUSE, :FLAT, :PORCH, :LOCALITY,
          :DATE_END, :DATE_ACCEPT, :DATE_ARRIVAL, :BEFORE_PERIOD;

  IF (DRIVER_ID IS NULL) THEN BEGIN

    IF (PARK_ID IS NOT NULL) THEN BEGIN

      FOR SELECT DRIVER_ID
            FROM /*PREFIX*/PARK_STATES
           WHERE PARK_ID=:PARK_ID
             AND DATE_OUT IS NULL
           ORDER BY DATE_IN
            INTO :DRIVER_ID DO BEGIN
        BREAK;
      END

    END ELSE BEGIN

      EXECUTE PROCEDURE PR_MANUAL(ORDER_ID,ACCOUNT_ID);

    END

  END

  IF (DRIVER_ID IS NOT NULL) THEN BEGIN

    CNT=0;

    IF (DATE_END IS NOT NULL) THEN BEGIN

      SELECT COUNT(*)
        FROM /*PREFIX*/OUT_MESSAGES
       WHERE RECIPIENT_ID=:DRIVER_ID
         AND DATE_CREATE=:DATE_END
         AND DESCRIPTION=:ORDER_ID
         AND DATE_OUT IS NULL
        INTO CNT;

    END

    IF (CNT=0) THEN BEGIN

      D=CURRENT_TIMESTAMP;

      UPDATE /*PREFIX*/ORDERS
         SET DRIVER_ID=:DRIVER_ID,
             DATE_END=:D,
             WHO_PROCESS_ID=:ACCOUNT_ID
       WHERE ORDER_ID=:ORDER_ID;

      SELECT PHONE
        FROM /*PREFIX*/ACCOUNTS
       WHERE ACCOUNT_ID=:DRIVER_ID
        INTO :PHONE;

      S='';

      IF (PREFIX IS NOT NULL) THEN
        S=PREFIX||' ';

      S=S||STREET||' '||HOUSE;

      IF (FLAT IS NOT NULL) THEN
        S=S||'-'||FLAT;

      IF (PORCH IS NOT NULL) THEN
        S=S||' п.'||PORCH;

      S=S||', '||LOCALITY;

      IF (DATE_ACCEPT<DATE_ARRIVAL) THEN BEGIN

        IF ((DATE_ACCEPT+(BEFORE_PERIOD*(1e0/24/60)))<DATE_ARRIVAL) THEN BEGIN

          S='Предв. на '||/*PERFIX*/FORMAT_DATETIME('hh:nn',DATE_ARRIVAL)||', '||S;

        END ELSE BEGIN

          S='Заказ на '||/*PERFIX*/FORMAT_DATETIME('hh:nn',DATE_ARRIVAL)||', '||S;

        END

      END

      INSERT INTO /*PREFIX*/OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                          TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,PRIORITY,LOCKED)
                                  VALUES (GET_UNIQUE_ID(),:ACCOUNT_ID,:DRIVER_ID,:D,
                                          :S,NULL,0,:PHONE,:ORDER_ID,0,NULL);
    END

  END

END

--

/* Фиксация изменений */

COMMIT