EXECUTE BLOCK
AS
DECLARE PHONE VARCHAR(100);
DECLARE DATE_BEGIN TIMESTAMP;
BEGIN
  DELETE FROM OUT_MESSAGES;

  DATE_BEGIN=CURRENT_TIMESTAMP;

  FOR SELECT FIRST 3000
             PHONE
        FROM ORIGINAL_PHONES
       WHERE SENT=0
         AND PHONE NOT IN (SELECT PHONE
                             FROM HISTORY_PHONES
                            WHERE DATE_LAST>DATEADD(MONTH,-2,CURRENT_TIMESTAMP))
        INTO :PHONE DO BEGIN


    UPDATE ORIGINAL_PHONES
       SET SENT=1
     WHERE PHONE=:PHONE;

 /* FOR SELECT '+79029232332'
        FROM RDB$DATABASE
        INTO :PHONE DO BEGIN*/


    DATE_BEGIN=DATEADD(MILLISECOND,250,DATE_BEGIN);

    INSERT INTO OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                              TEXT_OUT,
                              DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,PRIORITY,LOCKED,
                              DATE_BEGIN,DATE_END,ORDER_ID,CHANNEL,DELIVERY,DATE_DELIVERY,
                              FLASH,DEST_PORT,FIRM_ID,OPERATOR_ID,MESSAGE_ID,SOURCE)
                      VALUES (GET_UNIQUE_ID(),'EF536273DCCB8A6E42EFEF0972F87CCC',NULL,CURRENT_TIMESTAMP,
                             'Комфортное такси Красноярска. 2-7777-87, www.ataxi24.ru, Стань своим!',
                             NULL,0,:PHONE,NULL,0,NULL,
                             :DATE_BEGIN,NULL,NULL,NULL,NULL,NULL,
                             0,NULL,NULL,NULL,NULL,'2777787');

  END

END
