CREATE TABLE /*PREFIX*/LOCALITIES
(
  LOCALITY_ID VARCHAR(32) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  PREFIX VARCHAR(10),
  PRIMARY KEY (LOCALITY_ID)
)


CREATE VIEW /*PREFIX*/S_LOCALITIES
AS
SELECT * FROM /*PREFIX*/LOCALITIES


CREATE PROCEDURE /*PREFIX*/I_LOCALITY
(
  LOCALITY_ID VARCHAR(32),
  NAME VARCHAR(100),
  PREFIX VARCHAR(10)
)
AS
BEGIN
  INSERT INTO /*PREFIX*/LOCALITIES (LOCALITY_ID,NAME,PREFIX)
       VALUES (:LOCALITY_ID,:NAME,:PREFIX);
END;

CREATE PROCEDURE /*PREFIX*/U_LOCALITY
(
  LOCALITY_ID VARCHAR(32),
  NAME VARCHAR(100),
  PREFIX VARCHAR(10),
  OLD_LOCALITY_ID VARCHAR(32)
)
AS
BEGIN
  UPDATE /*PREFIX*/LOCALITIES
     SET LOCALITY_ID=:LOCALITY_ID,
         NAME=:NAME,
         PREFIX=:PREFIX
   WHERE LOCALITY_ID=:OLD_LOCALITY_ID;
END;

CREATE PROCEDURE /*PREFIX*/D_LOCALITY
(
  OLD_LOCALITY_ID VARCHAR(32)
)
AS
BEGIN
  DELETE FROM /*PREFIX*/LOCALITIES 
        WHERE LOCALITY_ID=:OLD_LOCALITY_ID;
END;


ALTER PROCEDURE /*PREFIX*/U_APPLICATION_INTERFACE
(
  APPLICATION_ID VARCHAR(32),
  ACCOUNT_ID VARCHAR(32),
  INTERFACE_ID VARCHAR(32),
  PRIORITY INTEGER,
  AUTO_RUN INTEGER,
  OLD_APPLICATION_ID VARCHAR(32),
  OLD_ACCOUNT_ID VARCHAR(32),
  OLD_INTERFACE_ID VARCHAR(32)
)
AS
BEGIN
  UPDATE /*PREFIX*/APPLICATION_INTERFACES
     SET APPLICATION_ID=:APPLICATION_ID,
         ACCOUNT_ID=:ACCOUNT_ID,
         INTERFACE_ID=:INTERFACE_ID,
         PRIORITY=:PRIORITY,
         AUTO_RUN=:AUTO_RUN
   WHERE APPLICATION_ID=:OLD_APPLICATION_ID
     AND ACCOUNT_ID=:OLD_ACCOUNT_ID
     AND INTERFACE_ID=:OLD_INTERFACE_ID;
END;


CREATE TABLE /*PREFIX*/STREETS
(
  STREET_ID VARCHAR(32) NOT NULL,
  LOCALITY_ID VARCHAR(32) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  PREFIX VARCHAR(10),
  PRIMARY KEY (STREET_ID),
  FOREIGN KEY (LOCALITY_ID) REFERENCES LOCALITIES (LOCALITY_ID)
)


CREATE VIEW /*PREFIX*/S_STREETS
(
  STREET_ID,
  LOCALITY_ID,
  NAME,
  PREFIX,
  LOCALITY_NAME,
  LOCALITY_PREFIX
)
AS
SELECT S.*,
       L.NAME AS LOCALITY_NAME,
       L.PREFIX AS LOCALITY_PREFIX
  FROM /*PREFIX*/STREETS S
  JOIN /*PREFIX*/LOCALITIES L ON L.LOCALITY_ID=S.LOCALITY_ID


CREATE PROCEDURE /*PREFIX*/I_STREET
(
  STREET_ID VARCHAR(32),
  LOCALITY_ID VARCHAR(32),
  NAME VARCHAR(100),
  PREFIX VARCHAR(10)
)
AS
BEGIN
  INSERT INTO /*PREFIX*/STREETS (STREET_ID,LOCALITY_ID,NAME,PREFIX)
       VALUES (:STREET_ID,:LOCALITY_ID,:NAME,:PREFIX);
END;

CREATE PROCEDURE /*PREFIX*/U_STREET
(
  STREET_ID VARCHAR(32),
  LOCALITY_ID VARCHAR(32),
  NAME VARCHAR(100),
  PREFIX VARCHAR(10),
  OLD_STREET_ID VARCHAR(32)
)
AS
BEGIN
  UPDATE /*PREFIX*/STREETS
     SET STREET_ID=:STREET_ID,
         LOCALITY_ID=:LOCALITY_ID,
         NAME=:NAME,
         PREFIX=:PREFIX
   WHERE STREET_ID=:OLD_STREET_ID;
END;

CREATE PROCEDURE /*PREFIX*/D_STREET
(
  OLD_STREET_ID VARCHAR(32)
)
AS
BEGIN
  DELETE FROM /*PREFIX*/STREETS 
        WHERE STREET_ID=:OLD_STREET_ID;
END;

DROP VIEW S_FIRMS

DROP PROCEDURE U_FIRM

DROP PROCEDURE I_FIRM

ALTER TABLE FIRMS
DROP LEGAL_ADDRESS

ALTER TABLE FIRMS
DROP LEGAL_INDEX

ALTER TABLE FIRMS
DROP POST_ADDRESS

ALTER TABLE FIRMS
DROP POST_INDEX

ALTER TABLE FIRMS
ADD INDEX_LEGAL VARCHAR(10)

ALTER TABLE FIRMS
ADD STREET_LEGAL_ID VARCHAR(32)

ALTER TABLE FIRMS
ADD HOUSE_LEGAL VARCHAR(10)

ALTER TABLE FIRMS
ADD FLAT_LEGAL VARCHAR(10)

ALTER TABLE FIRMS
ADD INDEX_POST VARCHAR(10)

ALTER TABLE FIRMS
ADD STREET_POST_ID VARCHAR(32)

ALTER TABLE FIRMS
ADD HOUSE_POST VARCHAR(10)

ALTER TABLE FIRMS
ADD FLAT_POST VARCHAR(10)

ALTER TABLE FIRMS
ADD FOREIGN KEY (STREET_LEGAL_ID) REFERENCES /*PREFIX*/STREETS (STREET_ID)

ALTER TABLE FIRMS
ADD FOREIGN KEY (STREET_POST_ID) REFERENCES /*PREFIX*/STREETS (STREET_ID)


CREATE VIEW /*PREFIX*/S_FIRMS
(
  FIRM_ID,
  FIRM_TYPE_ID,
  PARENT_ID,
  SMALL_NAME,
  FULL_NAME,
  INN,
  PAYMENT_ACCOUNT,
  BANK,
  BIK,
  CORR_ACCOUNT,
  PHONE,
  FAX,
  EMAIL,
  SITE,
  OKONH,
  OKPO,
  KPP,
  DIRECTOR,
  ACCOUNTANT,
  CONTACT_FACE,
  INDEX_LEGAL,
  STREET_LEGAL_ID,
  HOUSE_LEGAL,
  FLAT_LEGAL,
  INDEX_POST,
  STREET_POST_ID,
  HOUSE_POST,
  FLAT_POST,
  FIRM_TYPE_NAME,
  PARENT_SMALL_NAME,
  STREET_LEGAL_NAME,
  STREET_LEGAL_PREFIX,
  LOCALITY_LEGAL_NAME,
  LOCALITY_LEGAL_PREFIX,
  STREET_POST_NAME,
  STREET_POST_PREFIX,
  LOCALITY_POST_NAME,
  LOCALITY_POST_PREFIX
)
AS
  SELECT F.*,
         FT.NAME AS FIRM_TYPE_NAME,
         F1.SMALL_NAME AS PARENT_SMALL_NAME,
         S1.NAME AS STREET_LEGAL_NAME,
         S1.PREFIX AS STREET_LEGAL_PREFIX,
         L1.NAME AS LOCALITY_LEGAL_NAME,
         L1.PREFIX AS LOCALITY_LEGAL_PREFIX,
         S2.NAME AS STREET_POST_NAME,
         S2.PREFIX AS STREET_POST_PREFIX,
         L2.NAME AS LOCALITY_POST_NAME,
         L2.PREFIX AS LOCALITY_POST_PREFIX
    FROM /*PREFIX*/FIRMS F
    JOIN /*PREFIX*/FIRM_TYPES FT ON FT.FIRM_TYPE_ID=F.FIRM_TYPE_ID
    LEFT JOIN /*PREFIX*/STREETS S1 ON S1.STREET_ID=F.STREET_LEGAL_ID
    LEFT JOIN /*PREFIX*/LOCALITIES L1 ON L1.LOCALITY_ID=S1.LOCALITY_ID
    LEFT JOIN /*PREFIX*/STREETS S2 ON S2.STREET_ID=F.STREET_POST_ID
    LEFT JOIN /*PREFIX*/LOCALITIES L2 ON L2.LOCALITY_ID=S2.LOCALITY_ID
    LEFT JOIN /*PREFIX*/FIRMS F1 ON F1.FIRM_ID=F.PARENT_ID


CREATE PROCEDURE /*PREFIX*/I_FIRM
(
  FIRM_ID VARCHAR(32),
  FIRM_TYPE_ID VARCHAR(32),
  PARENT_ID VARCHAR(32),
  SMALL_NAME VARCHAR(250),
  FULL_NAME VARCHAR(250),
  INN VARCHAR(12),
  PAYMENT_ACCOUNT VARCHAR(20),
  BANK VARCHAR(250),
  BIK VARCHAR(20),
  CORR_ACCOUNT VARCHAR(20),
  PHONE VARCHAR(250),
  FAX VARCHAR(250),
  EMAIL VARCHAR(100),
  SITE VARCHAR(100),
  OKONH VARCHAR(20),
  OKPO VARCHAR(20),
  KPP VARCHAR(20),
  DIRECTOR VARCHAR(250),
  ACCOUNTANT VARCHAR(250),
  CONTACT_FACE VARCHAR(250),
  INDEX_LEGAL VARCHAR(10),
  STREET_LEGAL_ID VARCHAR(32),
  HOUSE_LEGAL VARCHAR(10),
  FLAT_LEGAL VARCHAR(10),
  INDEX_POST VARCHAR(10),
  STREET_POST_ID VARCHAR(32),
  HOUSE_POST VARCHAR(10),
  FLAT_POST VARCHAR(10)
)
AS
BEGIN
  INSERT INTO /*PREFIX*/FIRMS (FIRM_ID,FIRM_TYPE_ID,PARENT_ID,SMALL_NAME,FULL_NAME,INN,PAYMENT_ACCOUNT,
                               BANK,BIK,CORR_ACCOUNT,PHONE,FAX,EMAIL,SITE,OKONH,OKPO,KPP,DIRECTOR,ACCOUNTANT,
                               CONTACT_FACE,INDEX_LEGAL,STREET_LEGAL_ID,HOUSE_LEGAL,FLAT_LEGAL,
                               INDEX_POST,STREET_POST_ID,HOUSE_POST,FLAT_POST)
       VALUES (:FIRM_ID,:FIRM_TYPE_ID,:PARENT_ID,:SMALL_NAME,:FULL_NAME,:INN,:PAYMENT_ACCOUNT,
               :BANK,:BIK,:CORR_ACCOUNT,:PHONE,:FAX,:EMAIL,:SITE,:OKONH,:OKPO,:KPP,:DIRECTOR,:ACCOUNTANT,
               :CONTACT_FACE,:INDEX_LEGAL,:STREET_LEGAL_ID,:HOUSE_LEGAL,:FLAT_LEGAL,
               :INDEX_POST,:STREET_POST_ID,:HOUSE_POST,:FLAT_POST);
END;


CREATE PROCEDURE /*PREFIX*/U_FIRM
(
  FIRM_ID VARCHAR(32),
  FIRM_TYPE_ID VARCHAR(32),
  PARENT_ID VARCHAR(32),
  SMALL_NAME VARCHAR(250),
  FULL_NAME VARCHAR(250),
  INN VARCHAR(12),
  PAYMENT_ACCOUNT VARCHAR(20),
  BANK VARCHAR(250),
  BIK VARCHAR(20),
  CORR_ACCOUNT VARCHAR(20),
  PHONE VARCHAR(250),
  FAX VARCHAR(250),
  EMAIL VARCHAR(100),
  SITE VARCHAR(100),
  OKONH VARCHAR(20),
  OKPO VARCHAR(20),
  KPP VARCHAR(20),
  DIRECTOR VARCHAR(250),
  ACCOUNTANT VARCHAR(250),
  CONTACT_FACE VARCHAR(250),
  INDEX_LEGAL VARCHAR(10),
  STREET_LEGAL_ID VARCHAR(32),
  HOUSE_LEGAL VARCHAR(10),
  FLAT_LEGAL VARCHAR(10),
  INDEX_POST VARCHAR(10),
  STREET_POST_ID VARCHAR(32),
  HOUSE_POST VARCHAR(10),
  FLAT_POST VARCHAR(10),
  OLD_FIRM_ID VARCHAR(32)
)
AS
BEGIN
  UPDATE /*PREFIX*/FIRMS
     SET FIRM_ID=:FIRM_ID,
         FIRM_TYPE_ID=:FIRM_TYPE_ID,
         PARENT_ID=:PARENT_ID,
         SMALL_NAME=:SMALL_NAME,
         FULL_NAME=:FULL_NAME,
         INN=:INN,
         PAYMENT_ACCOUNT=:PAYMENT_ACCOUNT,
         BANK=:BANK,
         BIK=:BIK,
         CORR_ACCOUNT=:CORR_ACCOUNT,
         PHONE=:PHONE,
         FAX=:FAX,
         EMAIL=:EMAIL,
         SITE=:SITE,
         OKONH=:OKONH,
         OKPO=:OKPO,
         KPP=:KPP,
         DIRECTOR=:DIRECTOR,
         ACCOUNTANT=:ACCOUNTANT,
         CONTACT_FACE=:CONTACT_FACE,
         INDEX_LEGAL=:INDEX_LEGAL,
         STREET_LEGAL_ID=:STREET_LEGAL_ID,
         HOUSE_LEGAL=:HOUSE_LEGAL,
         FLAT_LEGAL=:FLAT_LEGAL,
         INDEX_POST=:INDEX_POST,
         STREET_POST_ID=:STREET_POST_ID,
         HOUSE_POST=:HOUSE_POST,
         FLAT_POST=:FLAT_POST
   WHERE FIRM_ID=:OLD_FIRM_ID;
END;

