CREATE VIEW /*PRIFIX*/S_DEBTORS_TURNOUT
AS
SELECT     DB .*, 
		CASE WHEN MONTH(CAST(ARREAR_PERIOD AS DATETIME)) >= 6 THEN '6 мес и больше.' 
		WHEN YEAR(CAST(ARREAR_PERIOD AS DATETIME)) > 1900 THEN '6 мес и больше.'
		ELSE CAST(MONTH(CAST(ARREAR_PERIOD AS DATETIME)) AS CHAR) END AS ARREAR_MONTH, 
		(CASE WHEN P.AMOUNT IS NULL 
              THEN D .INITIAL_DEBT ELSE D .INITIAL_DEBT - P.AMOUNT END) AS CURRENT_DEBT
FROM	/*PREFIX*/DEBTORS DB
		JOIN /*PRIFIX*/DEALS D ON D.DEBTOR_ID = DB.DEBTOR_ID
		LEFT JOIN	(SELECT     DEAL_ID, SUM(AMOUNT) AS AMOUNT
                     FROM          /*PRIFIX*/PAYMENTS
                     WHERE      STATE = 1
                     GROUP BY DEAL_ID) AS P ON P.DEAL_ID = D .DEAL_ID