CREATE VIEW /*PREFIX*/S_DEBTORS_REGISTRY
AS
SELECT  DB.DEBTOR_ID,
		DB.SURNAME+' '+DB.NAME+' '+DB.PATRONYMIC AS NAME, 
		DB.ADDRESS_RESIDENCE AS ADDRESS,
		DB.DATE_BIRTH,
		(CASE WHEN P.AMOUNT IS NULL 
              THEN D .INITIAL_DEBT ELSE D .INITIAL_DEBT - P.AMOUNT END) AS CURRENT_DEBT,
		D.ACCOUNT_NUM,
		D.DEBTOR_DATE
FROM	/*PREFIX*/DEBTORS DB
		JOIN dbo.DEALS D ON D.DEBTOR_ID = DB.DEBTOR_ID
		LEFT JOIN	(SELECT     DEAL_ID, SUM(AMOUNT) AS AMOUNT
                     FROM       /*PREFIX*/PAYMENTS
                     WHERE      STATE = 1
                     GROUP BY DEAL_ID) AS P ON P.DEAL_ID = D .DEAL_ID
GROUP BY DB.DEBTOR_ID, DB.SURNAME, DB.NAME, DB.PATRONYMIC, DB.ADDRESS_RESIDENCE, 
DB.DATE_BIRTH, D .INITIAL_DEBT, D.ACCOUNT_NUM, D.DEBTOR_DATE, P.AMOUNT