/* Создание таблицы приложений */

CREATE TABLE /*PREFIX*/APPLICATIONS
(
  APPLICATION_ID VARCHAR(32) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(250),
  LOCKED INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (APPLICATION_ID)
)

--

/* Создание просмотра таблицы приложений */

CREATE VIEW /*PREFIX*/S_APPLICATIONS
AS
SELECT * FROM /*PREFIX*/APPLICATIONS

--

/* Создание процедуры добавления приложения */

CREATE PROCEDURE /*PREFIX*/I_APPLICATION
(
  IN APPLICATION_ID VARCHAR(32),
  IN NAME VARCHAR(100),
  IN DESCRIPTION VARCHAR(250),
  IN LOCKED INTEGER
)
BEGIN
  INSERT INTO /*PREFIX*/APPLICATIONS (APPLICATION_ID,NAME,DESCRIPTION,LOCKED)
       VALUES (APPLICATION_ID,NAME,DESCRIPTION,LOCKED);
END;

--

/* Создание процедуры изменения приложения */

CREATE PROCEDURE /*PREFIX*/U_APPLICATION
(
  IN APPLICATION_ID VARCHAR(32),
  IN NAME VARCHAR(100),
  IN DESCRIPTION VARCHAR(250),
	IN LOCKED INTEGER,
  IN OLD_APPLICATION_ID VARCHAR(32)
)
BEGIN
  UPDATE /*PREFIX*/APPLICATIONS V
     SET V.APPLICATION_ID=APPLICATION_ID,
         V.NAME=NAME,
	       V.DESCRIPTION=DESCRIPTION,
				 V.LOCKED=LOCKED
   WHERE V.APPLICATION_ID=OLD_APPLICATION_ID;
END;

--

/* Создание процедуры удаления приложения */

CREATE PROCEDURE /*PREFIX*/D_APPLICATION
(
  IN OLD_APPLICATION_ID VARCHAR(32)
)
BEGIN
  DELETE FROM /*PREFIX*/APPLICATIONS 
        WHERE APPLICATION_ID=OLD_APPLICATION_ID;
END;

--