/* Создание таблицы пользователей */

CREATE TABLE /*PREFIX*/ACCOUNTS
(
  ACCOUNT_ID VARCHAR(32) NOT NULL,
  FIRM_ID VARCHAR(32),
  DATE_CREATE DATETIME NOT NULL,
  USER_NAME VARCHAR(100) NOT NULL,
  PASSWORD VARCHAR(100),
  DESCRIPTION VARCHAR(250),
  DB_USER_NAME VARCHAR(100),
  DB_PASSWORD VARCHAR(100),
  IS_ROLE INTEGER,
  LOCKED INTEGER,  
  AUTO_CREATED INTEGER,
  SURNAME VARCHAR(100),
  NAME VARCHAR(100),
  PATRONYMIC VARCHAR(100),
  PHONE VARCHAR(100),
  EMAIL VARCHAR(100),
  PHOTO LONGBLOB,
  PRIMARY KEY (ACCOUNT_ID)
)

--

/* Создание просмотра таблицы пользователей */

CREATE VIEW /*PREFIX*/S_ACCOUNTS
AS
   SELECT A.*, 
          F.SMALL_NAME AS FIRM_SMALL_NAME
     FROM /*PREFIX*/ACCOUNTS A
     LEFT JOIN /*PREFIX*/FIRMS F ON F.FIRM_ID=A.FIRM_ID

--

/* Создание процедуры добавления пользователя */

CREATE PROCEDURE /*PREFIX*/I_ACCOUNT
(
  IN ACCOUNT_ID VARCHAR(32),
  IN FIRM_ID VARCHAR(32),
	IN DATE_CREATE DATETIME,
  IN USER_NAME VARCHAR(100),
  IN PASSWORD VARCHAR(100),
  IN DESCRIPTION VARCHAR(250),
  IN DB_USER_NAME VARCHAR(100),
  IN DB_PASSWORD VARCHAR(100),
  IN IS_ROLE INTEGER,
  IN LOCKED INTEGER,  
  IN AUTO_CREATED INTEGER,
  IN SURNAME VARCHAR(100),
  IN NAME VARCHAR(100),
  IN PATRONYMIC VARCHAR(100),
  IN PHONE VARCHAR(100),
  IN EMAIL VARCHAR(100),
	IN PHOTO LONGBLOB
)
BEGIN
  INSERT INTO /*PREFIX*/ACCOUNTS (ACCOUNT_ID,FIRM_ID,DATE_CREATE,USER_NAME,PASSWORD,DESCRIPTION,DB_USER_NAME,DB_PASSWORD,
	                                IS_ROLE,LOCKED,AUTO_CREATED,SURNAME,NAME,PATRONYMIC,PHONE,EMAIL,PHOTO)
       VALUES (ACCOUNT_ID,FIRM_ID,DATE_CREATE,USER_NAME,PASSWORD,DESCRIPTION,DB_USER_NAME,DB_PASSWORD,
	             IS_ROLE,LOCKED,AUTO_CREATED,SURNAME,NAME,PATRONYMIC,PHONE,EMAIL,PHOTO);
END;

--

/* Создание процедуры изменения пользователя */

CREATE PROCEDURE /*PREFIX*/U_ACCOUNT
(
  IN ACCOUNT_ID VARCHAR(32),
  IN FIRM_ID VARCHAR(32),
	IN DATE_CREATE DATETIME,
  IN USER_NAME VARCHAR(100),
  IN PASSWORD VARCHAR(100),
  IN DESCRIPTION VARCHAR(250),
  IN DB_USER_NAME VARCHAR(100),
  IN DB_PASSWORD VARCHAR(100),
  IN IS_ROLE INTEGER,
  IN LOCKED INTEGER,  
  IN AUTO_CREATED INTEGER,
  IN SURNAME VARCHAR(100),
  IN NAME VARCHAR(100),
  IN PATRONYMIC VARCHAR(100),
  IN PHONE VARCHAR(100),
  IN EMAIL VARCHAR(100),
	IN PHOTO LONGBLOB,
  IN OLD_ACCOUNT_ID VARCHAR(32)
)
BEGIN
  UPDATE /*PREFIX*/ACCOUNTS A
     SET A.ACCOUNT_ID=ACCOUNT_ID,
         A.FIRM_ID=FIRM_ID,
				 A.DATE_CREATE=DATE_CREATE,
         A.USER_NAME=USER_NAME,
         A.PASSWORD=PASSWORD,
         A.DESCRIPTION=DESCRIPTION,
         A.DB_USER_NAME=DB_USER_NAME,
         A.DB_PASSWORD=DB_PASSWORD,
         A.IS_ROLE=IS_ROLE,
				 A.LOCKED=LOCKED,
				 A.AUTO_CREATED=AUTO_CREATED,
				 A.SURNAME=SURNAME,
				 A.NAME=NAME,
				 A.PATRONYMIC=PATRONYMIC,
				 A.PHONE=PHONE,
				 A.EMAIL=EMAIL,
				 A.PHOTO=PHOTO 
   WHERE A.ACCOUNT_ID=OLD_ACCOUNT_ID;
END;

--

/* Создание процедуры удаления пользователя */

CREATE PROCEDURE /*PREFIX*/D_ACCOUNT
(
  IN OLD_ACCOUNT_ID VARCHAR(32)
)
BEGIN
  DELETE FROM /*PREFIX*/ACCOUNTS
        WHERE ACCOUNT_ID=OLD_ACCOUNT_ID;
END;

--