/* Создание таблицы видов */

CREATE TABLE /*PREFIX*/VIEWS
(
  VIEW_ID VARCHAR(32) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(250),
  NUM VARCHAR(10) NOT NULL,
  PRIMARY KEY (VIEW_ID)
)

--

/* Создание просмотра таблицы видов */

CREATE VIEW /*PREFIX*/S_VIEWS
AS
SELECT * FROM /*PREFIX*/VIEWS

--

/* Создание процедуры добавления вида */

CREATE PROCEDURE /*PREFIX*/I_VIEW
(
  IN VIEW_ID VARCHAR(32),
  IN NAME VARCHAR(100),
  IN DESCRIPTION VARCHAR(250),
  IN NUM VARCHAR(10)
)
BEGIN
  INSERT INTO /*PREFIX*/VIEWS (VIEW_ID,NAME,DESCRIPTION,NUM)
       VALUES (VIEW_ID,NAME,DESCRIPTION,NUM);
END;

--

/* Создание процедуры изменения вида */

CREATE PROCEDURE /*PREFIX*/U_VIEW
(
  IN VIEW_ID VARCHAR(32),
  IN NAME VARCHAR(100),
  IN DESCRIPTION VARCHAR(250),
  IN NUM VARCHAR(10),
  IN OLD_VIEW_ID VARCHAR(32)
)
BEGIN
  UPDATE /*PREFIX*/VIEWS V
     SET V.VIEW_ID=VIEW_ID,
         V.NAME=NAME,
	       V.DESCRIPTION=DESCRIPTION,
				 V.NUM=NUM
   WHERE V.VIEW_ID=OLD_VIEW_ID;
END;

--

/* Создание процедуры удаления вида */

CREATE PROCEDURE /*PREFIX*/D_VIEW
(
  IN OLD_VIEW_ID VARCHAR(32)
)
BEGIN
  DELETE FROM /*PREFIX*/VIEWS 
        WHERE VIEW_ID=OLD_VIEW_ID;
END;

--