/* Создание таблицы типов */

CREATE TABLE /*PREFIX*/TYPES
(
  TYPE_ID VARCHAR(32) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(250),
  NUM VARCHAR(10) NOT NULL,
  PRIMARY KEY (TYPE_ID)
)

--

/* Создание просмотра таблицы типов */

CREATE VIEW /*PREFIX*/S_TYPES
AS
SELECT * FROM /*PREFIX*/TYPES

--

/* Создание процедуры добавления типа */

CREATE PROCEDURE /*PREFIX*/I_TYPE
(
  IN TYPE_ID VARCHAR(32),
  IN NAME VARCHAR(100),
  IN DESCRIPTION VARCHAR(250),
  IN NUM VARCHAR(10)
)
BEGIN
  INSERT INTO /*PREFIX*/TYPES (TYPE_ID,NAME,DESCRIPTION,NUM)
       VALUES (TYPE_ID,NAME,DESCRIPTION,NUM);
END;

--

/* Создание процедуры изменения типа */

CREATE PROCEDURE /*PREFIX*/U_TYPE
(
  IN TYPE_ID VARCHAR(32),
  IN NAME VARCHAR(100),
  IN DESCRIPTION VARCHAR(250),
	IN NUM VARCHAR(10),
	IN OLD_TYPE_ID VARCHAR(32)
)
BEGIN
  UPDATE /*PREFIX*/TYPES V
     SET V.TYPE_ID=TYPE_ID,
         V.NAME=NAME,
         V.DESCRIPTION=DESCRIPTION,
	 V.NUM=NUM
   WHERE V.TYPE_ID=OLD_TYPE_ID;
END;

--

/* Создание процедуры удаления типа */

CREATE PROCEDURE /*PREFIX*/D_TYPE
(
  IN OLD_TYPE_ID VARCHAR(32)
)
BEGIN
  DELETE FROM /*PREFIX*/TYPES 
        WHERE TYPE_ID=OLD_TYPE_ID;
END;

--