/* Создание таблицы оформлений */

CREATE TABLE /*PREFIX*/DESIGNS
(
  DESIGN_ID VARCHAR(32) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(250),
  NUM VARCHAR(10) NOT NULL,
  PRIMARY KEY (DESIGN_ID)
)

--

/* Создание просмотра таблицы оформлений */

CREATE VIEW /*PREFIX*/S_DESIGNS
AS
SELECT * FROM /*PREFIX*/DESIGNS

--

/* Создание процедуры добавления оформления */

CREATE PROCEDURE /*PREFIX*/I_DESIGN
(
  IN DESIGN_ID VARCHAR(32),
  IN NAME VARCHAR(100),
  IN DESCRIPTION VARCHAR(250),
  IN NUM VARCHAR(10)
)
BEGIN
  INSERT INTO /*PREFIX*/DESIGNS (DESIGN_ID,NAME,DESCRIPTION,NUM)
       VALUES (DESIGN_ID,NAME,DESCRIPTION,NUM);
END;

--

/* Создание процедуры изменения оформления */

CREATE PROCEDURE /*PREFIX*/U_DESIGN
(
  IN DESIGN_ID VARCHAR(32),
  IN NAME VARCHAR(100),
  IN DESCRIPTION VARCHAR(250),
  IN NUM VARCHAR(10),
  IN OLD_DESIGN_ID VARCHAR(32)
)
BEGIN
  UPDATE /*PREFIX*/DESIGNS V
     SET V.DESIGN_ID=DESIGN_ID,
         V.NAME=NAME,
	       V.DESCRIPTION=DESCRIPTION,
				 V.NUM=NUM
   WHERE V.DESIGN_ID=OLD_DESIGN_ID;
END;

--

/* Создание процедуры удаления оформления */

CREATE PROCEDURE /*PREFIX*/D_DESIGN
(
  IN OLD_DESIGN_ID VARCHAR(32)
)
BEGIN
  DELETE FROM /*PREFIX*/DESIGNS 
        WHERE DESIGN_ID=OLD_DESIGN_ID;
END;

--