/* Создание таблицы шаблонов */

CREATE TABLE /*PREFIX*/PATTERNS
(
  EXPORT_ID VARCHAR(32) NOT NULL,
  DESIGN_ID VARCHAR(32) NOT NULL,
  RTF LONGBLOB NOT NULL,
  PRIMARY KEY (EXPORT_ID,DESIGN_ID),
  FOREIGN KEY (EXPORT_ID) REFERENCES /*PREFIX*/EXPORTS (EXPORT_ID),
  FOREIGN KEY (DESIGN_ID) REFERENCES /*PREFIX*/DESIGNS (DESIGN_ID)
)

--

/* Создание просмотра таблицы состава видов */

CREATE VIEW /*PREFIX*/S_PATTERNS
AS
SELECT P.*,
       E.NAME AS EXPORT_NAME,
       D.NAME AS DESIGN_NAME,
       D.NUM AS DESIGN_NUM
  FROM /*PREFIX*/PATTERNS P
  JOIN /*PREFIX*/EXPORTS E ON E.EXPORT_ID=P.EXPORT_ID
  JOIN /*PREFIX*/DESIGNS D ON D.DESIGN_ID=P.DESIGN_ID
			
--

/* Создание процедуры добавления виду типа */

CREATE PROCEDURE /*PREFIX*/I_PATTERN
(
  IN EXPORT_ID VARCHAR(32),
  IN DESIGN_ID VARCHAR(32),
  IN RTF LONGBLOB
)
BEGIN
  INSERT INTO /*PREFIX*/PATTERNS (EXPORT_ID,DESIGN_ID,RTF)
       VALUES (EXPORT_ID,DESIGN_ID,RTF);
END;

--

/* Создание процедуры изменения типа у вида */

CREATE PROCEDURE /*PREFIX*/U_PATTERN
(
  IN EXPORT_ID VARCHAR(32),
  IN DESIGN_ID VARCHAR(32),
  IN RTF LONGBLOB,
  IN OLD_EXPORT_ID VARCHAR(32),
  IN OLD_DESIGN_ID VARCHAR(32)
)
BEGIN
  UPDATE /*PREFIX*/PATTERNS P
     SET P.EXPORT_ID=EXPORT_ID,
         P.DESIGN_ID=DESIGN_ID,
         P.RTF=RTF
   WHERE P.EXPORT_ID=OLD_EXPORT_ID
	   AND P.DESIGN_ID=OLD_DESIGN_ID;
END;

--

/* Создание процедуры удаления типа у вида */

CREATE PROCEDURE /*PREFIX*/D_PATTERN
(
  IN OLD_EXPORT_ID VARCHAR(32),
	IN OLD_DESIGN_ID VARCHAR(32)
)
BEGIN
  DELETE FROM /*PREFIX*/PATTERNS 
        WHERE EXPORT_ID=OLD_EXPORT_ID
				  AND DESIGN_ID=OLD_DESIGN_ID;
END;

--