/* Создание таблицы объектов */

CREATE TABLE /*PREFIX*/OBJECTS
(
  OBJECT_ID VARCHAR(32) NOT NULL,
  ACCOUNT_ID VARCHAR(32) NOT NULL,
  VIEW_ID VARCHAR(32) NOT NULL,
  TYPE_ID VARCHAR(32) NOT NULL,
  OPERATION_ID VARCHAR(32) NOT NULL,
  STATUS INTEGER NOT NULL DEFAULT 0,
  DESIGN_ID VARCHAR(32),
  PRIORITY INTEGER,
  PRIMARY KEY (OBJECT_ID),
  FOREIGN KEY (ACCOUNT_ID) REFERENCES /*PREFIX*/ACCOUNTS (ACCOUNT_ID),
  FOREIGN KEY (VIEW_ID) REFERENCES /*PREFIX*/VIEWS (VIEW_ID),
  FOREIGN KEY (TYPE_ID) REFERENCES /*PREFIX*/TYPES (TYPE_ID),
  FOREIGN KEY (OPERATION_ID) REFERENCES /*PREFIX*/OPERATIONS (OPERATION_ID),
  FOREIGN KEY (DESIGN_ID) REFERENCES /*PREFIX*/DESIGNS (DESIGN_ID)
)

--

/* Создание просмотра таблицы объектов */

CREATE VIEW /*PREFIX*/S_OBJECTS
AS
   SELECT O.*, 
          A.USER_NAME,
          V.NAME AS VIEW_NAME,
          V.NUM AS VIEW_NUM,
	  T.NAME AS TYPE_NAME,
          T.NUM AS TYPE_NUM,
	  OP.NAME AS OPERATION_NAME,
          OP.NUM AS OPERATION_NUM,
          D.NAME AS DESIGN_NAME,
          D.NUM AS DESIGN_NUM
     FROM /*PREFIX*/OBJECTS O
     JOIN /*PREFIX*/ACCOUNTS A ON A.ACCOUNT_ID=O.ACCOUNT_ID
     JOIN /*PREFIX*/VIEWS V ON V.VIEW_ID=O.VIEW_ID
     JOIN /*PREFIX*/TYPES T ON T.TYPE_ID=O.TYPE_ID
     JOIN /*PREFIX*/OPERATIONS OP ON OP.OPERATION_ID=O.OPERATION_ID
     LEFT JOIN /*PREFIX*/DESIGNS D ON D.DESIGN_ID=O.DESIGN_ID
--

/* Создание процедуры добавления объекта */

CREATE PROCEDURE /*PREFIX*/I_OBJECT
(
  IN OBJECT_ID VARCHAR(32),
  IN ACCOUNT_ID VARCHAR(32),
  IN VIEW_ID VARCHAR(32),
  IN TYPE_ID VARCHAR(32),
  IN OPERATION_ID VARCHAR(32),
  IN STATUS INTEGER,
  IN DESIGN_ID VARCHAR(32),
  IN PRIORITY INTEGER
)
BEGIN
  INSERT INTO /*PREFIX*/OBJECTS (OBJECT_ID,ACCOUNT_ID,VIEW_ID,TYPE_ID,
                                 OPERATION_ID,STATUS,DESIGN_ID,PRIORITY)
       VALUES (OBJECT_ID,ACCOUNT_ID,VIEW_ID,TYPE_ID,
               OPERATION_ID,STATUS,DESIGN_ID,PRIORITY);
END;

--

/* Создание процедуры изменения объекта */

CREATE PROCEDURE /*PREFIX*/U_OBJECT
(
  IN OBJECT_ID VARCHAR(32),
  IN ACCOUNT_ID VARCHAR(32),
  IN VIEW_ID VARCHAR(32),
  IN TYPE_ID VARCHAR(32),
  IN OPERATION_ID VARCHAR(32),
  IN STATUS INTEGER,
  IN DESIGN_ID VARCHAR(32),
  IN PRIORITY INTEGER,
  IN OLD_OBJECT_ID VARCHAR(32)
)
BEGIN
  UPDATE /*PREFIX*/OBJECTS O
     SET O.OBJECT_ID=OBJECT_ID,
         O.ACCOUNT_ID=ACCOUNT_ID,
         O.VIEW_ID=VIEW_ID,
      	 O.TYPE_ID=TYPE_ID,
	       O.OPERATION_ID=OPERATION_ID,
	       O.STATUS=STATUS,
         O.DESIGN_ID=DESIGN_ID,
         O.PRIORITY=PRIORITY
   WHERE O.OBJECT_ID=OLD_OBJECT_ID;
END;

--

/* Создание процедуры удаления объекта */

CREATE PROCEDURE /*PREFIX*/D_OBJECT
(
  IN OLD_OBJECT_ID VARCHAR(32)
)
BEGIN
  DELETE FROM /*PREFIX*/OBJECTS
        WHERE OBJECT_ID=OLD_OBJECT_ID;
END;

--