/* Создание таблицы операций */

CREATE TABLE /*PREFIX*/OPERATIONS
(
  OPERATION_ID VARCHAR(32) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(250),
  NUM VARCHAR(10) NOT NULL,
  PRIMARY KEY (OPERATION_ID)
)

--

/* Создание просмотра таблицы операций */

CREATE VIEW /*PREFIX*/S_OPERATIONS
AS
SELECT * FROM /*PREFIX*/OPERATIONS

--

/* Создание процедуры добавления операции */

CREATE PROCEDURE /*PREFIX*/I_OPERATION
(
  IN OPERATION_ID VARCHAR(32),
  IN NAME VARCHAR(100),
  IN DESCRIPTION VARCHAR(250),
  IN NUM VARCHAR(10)
)
BEGIN
  INSERT INTO /*PREFIX*/OPERATIONS (OPERATION_ID,NAME,DESCRIPTION,NUM)
       VALUES (OPERATION_ID,NAME,DESCRIPTION,NUM);
END;

--

/* Создание процедуры изменения операции */

CREATE PROCEDURE /*PREFIX*/U_OPERATION
(
  IN OPERATION_ID VARCHAR(32),
  IN NAME VARCHAR(100),
  IN DESCRIPTION VARCHAR(250),
  IN NUM VARCHAR(10),
  IN OLD_OPERATION_ID VARCHAR(32)
)
BEGIN
  UPDATE /*PREFIX*/OPERATIONS O
     SET O.OPERATION_ID=OPERATION_ID,
         O.NAME=NAME,
         O.DESCRIPTION=DESCRIPTION,
	 O.NUM=NUM
   WHERE O.OPERATION_ID=OLD_OPERATION_ID;
END;

--

/* Создание процедуры удаления операции */

CREATE PROCEDURE /*PREFIX*/D_OPERATION
(
  IN OLD_OPERATION_ID VARCHAR(32)
)
BEGIN
  DELETE FROM /*PREFIX*/OPERATIONS 
        WHERE OPERATION_ID=OLD_OPERATION_ID;
END;

--