/* Создание таблицы состава типов */

CREATE TABLE /*PREFIX*/TYPE_OPERATIONS
(
  TYPE_ID VARCHAR(32) NOT NULL,
  OPERATION_ID VARCHAR(32) NOT NULL,
  PRIORITY INTEGER NOT NULL,
  PRIMARY KEY (TYPE_ID,OPERATION_ID),
  FOREIGN KEY (TYPE_ID) /*PREFIX*/REFERENCES TYPES (TYPE_ID),
  FOREIGN KEY (OPERATION_ID) REFERENCES /*PREFIX*/OPERATIONS (OPERATION_ID)
)

--

/* Создание просмотра таблицы состава типов */

CREATE VIEW /*PREFIX*/S_TYPE_OPERATIONS
AS
SELECT TP.*,
       T.NAME AS TYPE_NAME,
       T.NUM AS TYPE_NUM,
       T.DESCRIPTION AS TYPE_DESCRIPTION,
       O.NAME AS OPERATION_NAME,
       O.NUM AS OPERATION_NUM
  FROM /*PREFIX*/TYPE_OPERATIONS TP
  JOIN /*PREFIX*/TYPES T ON T.TYPE_ID=TP.TYPE_ID
  JOIN /*PREFIX*/OPERATIONS O ON O.OPERATION_ID=TP.OPERATION_ID
			
--

/* Создание процедуры добавления виду типа */

CREATE PROCEDURE /*PREFIX*/I_TYPE_OPERATION
(
  IN TYPE_ID VARCHAR(32),
  IN OPERATION_ID VARCHAR(32),
  IN PRIORITY INTEGER
)
BEGIN
  INSERT INTO /*PREFIX*/TYPE_OPERATIONS (TYPE_ID,OPERATION_ID,PRIORITY)
       VALUES (TYPE_ID,OPERATION_ID,PRIORITY);
END;

--

/* Создание процедуры изменения типа у вида */

CREATE PROCEDURE /*PREFIX*/U_TYPE_OPERATION
(
  IN TYPE_ID VARCHAR(32),
  IN OPERATION_ID VARCHAR(32),
  IN PRIORITY INTEGER,
  IN OLD_TYPE_ID VARCHAR(32),
  IN OLD_OPERATION_ID VARCHAR(32)
)
BEGIN
  UPDATE /*PREFIX*/TYPE_OPERATIONS TP
     SET TP.TYPE_ID=TYPE_ID,
         TP.OPERATION_ID=OPERATION_ID,
         TP.PRIORITY=PRIORITY
   WHERE TP.TYPE_ID=OLD_TYPE_ID
	   AND TP.OPERATION_ID=OLD_OPERATION_ID;
END;

--

/* Создание процедуры удаления типа у вида */

CREATE PROCEDURE /*PREFIX*/D_TYPE_OPERATION
(
  IN OLD_TYPE_ID VARCHAR(32),
	IN OLD_OPERATION_ID VARCHAR(32)
)
BEGIN
  DELETE FROM /*PREFIX*/TYPE_OPERATIONS 
        WHERE TYPE_ID=OLD_TYPE_ID
	  AND OPERATION_ID=OLD_OPERATION_ID;
END;

--