/* Создание таблицы зависимости параметров от типа */

CREATE TABLE /*PREFIX*/TYPE_PARAMS
(
  TYPE_ID VARCHAR(32) NOT NULL,
  PARAM_ID VARCHAR(32) NOT NULL,
  OPERATION_ID VARCHAR(32) NOT NULL,
  VISIBLE INTEGER NOT NULL,
  MAIN INTEGER NOT NULL,
  PRIORITY INTEGER NOT NULL,
  PRIMARY KEY (TYPE_ID,PARAM_ID,OPERATION_ID),
  FOREIGN KEY (TYPE_ID) REFERENCES /*PREFIX*/TYPES (TYPE_ID),
  FOREIGN KEY (PARAM_ID) REFERENCES /*PREFIX*/PARAMS (PARAM_ID),
  FOREIGN KEY (OPERATION_ID) REFERENCES /*PREFIX*/OPERATIONS (OPERATION_ID)
)

--

/* Создание просмотра таблицы зависимости параметров от типа */

CREATE VIEW /*PREFIX*/S_TYPE_PARAMS
AS
SELECT TP.*,
			 T.NAME AS TYPE_NAME,
			 P.NAME AS PARAM_NAME,
			 O.NAME AS OPERATION_NAME,
			 P.PARAM_TYPE
  FROM /*PREFIX*/TYPE_PARAMS TP
	JOIN /*PREFIX*/TYPES T ON T.TYPE_ID=TP.TYPE_ID
  JOIN /*PREFIX*/PARAMS P ON P.PARAM_ID=TP.PARAM_ID
	JOIN /*PREFIX*/OPERATIONS O ON O.OPERATION_ID=TP.OPERATION_ID
	
--

/* Создание процедуры добавления типу параметра */

CREATE PROCEDURE /*PREFIX*/I_TYPE_PARAM
(
  IN TYPE_ID VARCHAR(32),
  IN PARAM_ID VARCHAR(32),
	IN OPERATION_ID VARCHAR(32),
	IN VISIBLE INTEGER,
	IN MAIN INTEGER,
  IN PRIORITY INTEGER
)
BEGIN
  INSERT INTO /*PREFIX*/TYPE_PARAMS (TYPE_ID,PARAM_ID,OPERATION_ID,VISIBLE,MAIN,PRIORITY)
       VALUES (TYPE_ID,PARAM_ID,OPERATION_ID,VISIBLE,MAIN,PRIORITY);
END;

--

/* Создание процедуры изменения параметра у типа */

CREATE PROCEDURE /*PREFIX*/U_TYPE_PARAM
(
  IN TYPE_ID VARCHAR(32),
  IN PARAM_ID VARCHAR(32),
	IN OPERATION_ID VARCHAR(32),
	IN VISIBLE INTEGER,
	IN MAIN INTEGER,
  IN PRIORITY INTEGER,
  IN OLD_TYPE_ID VARCHAR(32),
  IN OLD_PARAM_ID VARCHAR(32),
	IN OLD_OPERATION_ID VARCHAR(32)
)
BEGIN
  UPDATE /*PREFIX*/TYPE_PARAMS PT
     SET PT.TYPE_ID=TYPE_ID,
		     PT.PARAM_ID=PARAM_ID,
		     PT.OPERATION_ID=OPERATION_ID,
				 PT.VISIBLE=VISIBLE,
				 PT.MAIN=MAIN,
         PT.PRIORITY=PRIORITY
   WHERE PT.TYPE_ID=OLD_TYPE_ID
	   AND PT.PARAM_ID=OLD_PARAM_ID
		 AND PT.OPERATION_ID=OLD_OPERATION_ID;
END;

--

/* Создание процедуры удаления параметра у типа */

CREATE PROCEDURE /*PREFIX*/D_TYPE_PARAM
(
  IN OLD_TYPE_ID VARCHAR(32),
	IN OLD_PARAM_ID VARCHAR(32),
	IN OLD_OPERATION_ID VARCHAR(32)
)
BEGIN
  DELETE FROM /*PREFIX*/TYPE_PARAMS 
        WHERE TYPE_ID=OLD_TYPE_ID
				  AND PARAM_ID=OLD_PARAM_ID
					AND OPERATION_ID=OLD_OPERATION_ID;
END;

--