/* Создание таблицы параметров */

CREATE TABLE /*PREFIX*/PARAMS
(
  PARAM_ID VARCHAR(32) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(250),
  PARAM_TYPE INTEGER NOT NULL,
  MAX_LENGTH INTEGER,
  SORTING INTEGER,
  LOCKED INTEGER NOT NULL,
  PRIMARY KEY (PARAM_ID)
)

--

/* Создание просмотра таблицы параметров */

CREATE VIEW /*PREFIX*/S_PARAMS
AS
SELECT * FROM /*PREFIX*/PARAMS

--

/* Создание процедуры добавления параметра */

CREATE PROCEDURE /*PREFIX*/I_PARAM
(
  IN PARAM_ID VARCHAR(32),
  IN NAME VARCHAR(100),
  IN DESCRIPTION VARCHAR(250),
  IN PARAM_TYPE INTEGER,
  IN MAX_LENGTH INTEGER,
  IN SORTING INTEGER,
  IN LOCKED INTEGER
)
BEGIN
  INSERT INTO /*PREFIX*/PARAMS (PARAM_ID,NAME,DESCRIPTION,PARAM_TYPE,MAX_LENGTH,SORTING,LOCKED)
       VALUES (PARAM_ID,NAME,DESCRIPTION,PARAM_TYPE,MAX_LENGTH,SORTING,LOCKED);
END;

--

/* Создание процедуры изменения параметра */

CREATE PROCEDURE /*PREFIX*/U_PARAM
(
  IN PARAM_ID VARCHAR(32),
  IN NAME VARCHAR(100),
  IN DESCRIPTION VARCHAR(250),
  IN PARAM_TYPE INTEGER,
	IN MAX_LENGTH INTEGER,
  IN SORTING INTEGER,
  IN LOCKED INTEGER,
  IN OLD_PARAM_ID VARCHAR(32)
)
BEGIN
  UPDATE /*PREFIX*/PARAMS P
     SET P.PARAM_ID=PARAM_ID,
         P.NAME=NAME,
         P.DESCRIPTION=DESCRIPTION,
         P.PARAM_TYPE=PARAM_TYPE,
         P.MAX_LENGTH=MAX_LENGTH,
         P.SORTING=SORTING,
         P.LOCKED=LOCKED
   WHERE P.PARAM_ID=OLD_PARAM_ID;
END;

--

/* Создание процедуры удаления параметра */

CREATE PROCEDURE /*PREFIX*/D_PARAM
(
  IN OLD_PARAM_ID VARCHAR(32)
)
BEGIN
  DELETE FROM /*PREFIX*/PARAMS 
        WHERE PARAM_ID=OLD_PARAM_ID;
END;

--