/* Создание таблицы значений параметров */

CREATE TABLE /*PREFIX*/PARAM_VALUES
(
  PARAM_VALUE_ID VARCHAR(32) NOT NULL,
  PARAM_ID VARCHAR(32) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(250),
  PRIORITY INTEGER NOT NULL,
  EXPORT VARCHAR(100),
  PRIMARY KEY (PARAM_VALUE_ID),
  FOREIGN KEY (PARAM_ID) REFERENCES PARAMS (PARAM_ID)
)

--

/* Создание просмотра таблицы значений параметров */

CREATE VIEW /*PREFIX*/S_PARAM_VALUES
AS
SELECT PV.*,
       P.NAME AS PARAM_NAME
  FROM /*PREFIX*/PARAM_VALUES PV
  JOIN /*PREFIX*/PARAMS P ON P.PARAM_ID=PV.PARAM_ID

--

/* Создание процедуры добавления значения параметра */

CREATE PROCEDURE /*PREFIX*/I_PARAM_VALUE
(
  IN PARAM_VALUE_ID VARCHAR(32),
  IN PARAM_ID VARCHAR(32),
  IN NAME VARCHAR(100),
  IN DESCRIPTION VARCHAR(250),
	IN PRIORITY INTEGER,
	IN EXPORT VARCHAR(100)
)
BEGIN
  INSERT INTO /*PREFIX*/PARAM_VALUES (PARAM_VALUE_ID,PARAM_ID,NAME,DESCRIPTION,PRIORITY,EXPORT)
       VALUES (PARAM_VALUE_ID,PARAM_ID,NAME,DESCRIPTION,PRIORITY,EXPORT);
END;

--

/* Создание процедуры изменения значения параметра */

CREATE PROCEDURE /*PREFIX*/U_PARAM_VALUE
(
  IN PARAM_VALUE_ID VARCHAR(32),
  IN PARAM_ID VARCHAR(32),
  IN NAME VARCHAR(100),
  IN DESCRIPTION VARCHAR(250),
	IN PRIORITY INTEGER,
	IN EXPORT VARCHAR(100),
  IN OLD_PARAM_VALUE_ID VARCHAR(32)
)
BEGIN
  UPDATE /*PREFIX*/PARAM_VALUES PV
     SET PV.PARAM_VALUE_ID=PARAM_VALUE_ID,
         PV.PARAM_ID=PARAM_ID,
         PV.NAME=NAME,
	       PV.DESCRIPTION=DESCRIPTION,
				 PV.PRIORITY=PRIORITY,
				 PV.EXPORT=EXPORT
   WHERE PV.PARAM_VALUE_ID=OLD_PARAM_VALUE_ID;
END;

--

/* Создание процедуры удаления значения параметра */

CREATE PROCEDURE /*PREFIX*/D_PARAM_VALUE
(
  IN OLD_PARAM_VALUE_ID VARCHAR(32)
)
BEGIN
  DELETE FROM /*PREFIX*/PARAM_VALUES 
        WHERE PARAM_VALUE_ID=OLD_PARAM_VALUE_ID;
END;

--