/* Создание таблицы параметров объекта */

CREATE TABLE /*PREFIX*/OBJECT_PARAMS
(
  OBJECT_PARAM_ID VARCHAR(32) NOT NULL,
  ACCOUNT_ID VARCHAR(32) NOT NULL,
  PARAM_ID VARCHAR(32) NOT NULL,
  OBJECT_ID VARCHAR(32) NOT NULL,
  DATE_CREATE DATETIME NOT NULL,
  DESCRIPTION VARCHAR(250),
  VALUE_STRING VARCHAR(1000),
  VALUE_NUMBER FLOAT,
  VALUE_DATE DATETIME,
  VALUE_BLOB LONGBLOB,
  EXPORT VARCHAR(100),
  PRIMARY KEY (OBJECT_PARAM_ID),
  FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS (ACCOUNT_ID),
  FOREIGN KEY (PARAM_ID) REFERENCES PARAMS (PARAM_ID),
  FOREIGN KEY (OBJECT_ID) REFERENCES OBJECTS (OBJECT_ID)
)

--

/* Создание просмотра таблицы параметров объекта */

CREATE VIEW /*PREFIX*/S_OBJECT_PARAMS
AS
SELECT OP.*,
       A.USER_NAME,
       P.NAME AS PARAM_NAME,
       P.DESCRIPTION AS PARAM_DESCRIPTION,
       P.PARAM_TYPE,
       P.MAX_LENGTH AS PARAM_MAX_LENGTH
  FROM /*PREFIX*/OBJECT_PARAMS OP
  JOIN /*PREFIX*/ACCOUNTS A ON A.ACCOUNT_ID=OP.ACCOUNT_ID
  JOIN /*PREFIX*/PARAMS P ON P.PARAM_ID=OP.PARAM_ID
  JOIN /*PREFIX*/OBJECTS O ON O.OBJECT_ID=OP.OBJECT_ID

--

/* Создание процедуры добавления параметра объекта */

CREATE PROCEDURE /*PREFIX*/I_OBJECT_PARAM
(
  IN OBJECT_PARAM_ID VARCHAR(32),
  IN ACCOUNT_ID VARCHAR(32),
  IN PARAM_ID VARCHAR(32),
  IN OBJECT_ID VARCHAR(32),
  IN DATE_CREATE DATETIME,
  IN VALUE_STRING VARCHAR(1000),
  IN VALUE_NUMBER FLOAT,
  IN VALUE_DATE DATETIME,
  IN VALUE_BLOB LONGBLOB,
  IN DESCRIPTION VARCHAR(250),
  IN EXPORT VARCHAR(100)
)
BEGIN
  INSERT INTO /*PREFIX*/OBJECT_PARAMS (OBJECT_PARAM_ID,ACCOUNT_ID,PARAM_ID,OBJECT_ID,DATE_CREATE,
                                       VALUE_STRING,VALUE_NUMBER,VALUE_DATE,VALUE_BLOB,DESCRIPTION,EXPORT)
       VALUES (OBJECT_PARAM_ID,ACCOUNT_ID,PARAM_ID,OBJECT_ID,DATE_CREATE,
               VALUE_STRING,VALUE_NUMBER,VALUE_DATE,VALUE_BLOB,DESCRIPTION,EXPORT);
END;

--

/* Создание процедуры изменения параметра объекта */

CREATE PROCEDURE /*PREFIX*/U_OBJECT_PARAM
(
  IN OBJECT_PARAM_ID VARCHAR(32),
  IN ACCOUNT_ID VARCHAR(32),
  IN PARAM_ID VARCHAR(32),
  IN OBJECT_ID VARCHAR(32),
  IN DATE_CREATE DATETIME,
  IN VALUE_STRING VARCHAR(1000),
  IN VALUE_NUMBER FLOAT,
  IN VALUE_DATE DATETIME,
  IN VALUE_BLOB LONGBLOB,
  IN DESCRIPTION VARCHAR(250),
  IN EXPORT VARCHAR(100),
  IN OLD_OBJECT_PARAM_ID VARCHAR(32)
)
BEGIN
  UPDATE /*PREFIX*/OBJECT_PARAMS OP
     SET OP.OBJECT_PARAM_ID=OBJECT_PARAM_ID,
         OP.ACCOUNT_ID=ACCOUNT_ID,
         OP.PARAM_ID=PARAM_ID,
	       OP.OBJECT_ID=OBJECT_ID,
	       OP.DATE_CREATE=DATE_CREATE,
	       OP.VALUE_STRING=VALUE_STRING,
         OP.VALUE_NUMBER=VALUE_NUMBER,
         OP.VALUE_DATE=VALUE_DATE,
         OP.VALUE_BLOB=VALUE_BLOB,
         OP.DESCRIPTION=DESCRIPTION,
         OP.EXPORT=EXPORT
   WHERE OP.OBJECT_PARAM_ID=OLD_OBJECT_PARAM_ID;
END;

--

/* Создание процедуры удаления параметра объекта */

CREATE PROCEDURE /*PREFIX*/D_OBJECT_PARAM
(
  IN OLD_OBJECT_PARAM_ID VARCHAR(32)
)
BEGIN
  DELETE FROM /*PREFIX*/OBJECT_PARAMS 
        WHERE OBJECT_PARAM_ID=OLD_OBJECT_PARAM_ID;
END;

--