/* Создание таблицы сессий */

CREATE TABLE /*PREFIX*/SESSIONS
(
  SESSION_ID VARCHAR(32) NOT NULL,
  ACCOUNT_ID VARCHAR(32) NOT NULL,
  APPLICATION_ID VARCHAR(32) NOT NULL,
  DATE_CREATE DATETIME NOT NULL,
  DATE_CHANGE DATETIME NOT NULL,
  PARAMS LONGBLOB,
  PRIMARY KEY (SESSION_ID),
  FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS (ACCOUNT_ID),
  FOREIGN KEY (APPLICATION_ID) REFERENCES APPLICATIONS (APPLICATION_ID)
)

--

/* Создание просмотра таблицы сессий */

CREATE VIEW /*PREFIX*/S_SESSIONS
AS
   SELECT S.*, 
          AC.USER_NAME AS USER_NAME,
					AP.NAME AS APPLICATION_NAME
     FROM /*PREFIX*/SESSIONS S
     JOIN /*PREFIX*/ACCOUNTS AC ON AC.ACCOUNT_ID=S.ACCOUNT_ID
		 JOIN /*PREFIX*/APPLICATIONS AP ON AP.APPLICATION_ID=S.APPLICATION_ID

--

/* Создание процедуры добавления сессии */

CREATE PROCEDURE /*PREFIX*/I_SESSION
(
  IN SESSION_ID VARCHAR(32),
  IN ACCOUNT_ID VARCHAR(32),
	IN APPLICATION_ID VARCHAR(32),
  IN DATE_CREATE DATETIME,
	IN DATE_CHANGE DATETIME,
	IN PARAMS LONGBLOB
)
BEGIN
  INSERT INTO /*PREFIX*/SESSIONS (SESSION_ID,ACCOUNT_ID,APPLICATION_ID,DATE_CREATE,DATE_CHANGE,PARAMS)
       VALUES (SESSION_ID,ACCOUNT_ID,APPLICATION_ID,DATE_CREATE,DATE_CHANGE,PARAMS);
END;

--

/* Создание процедуры изменения сессии */

CREATE PROCEDURE /*PREFIX*/U_SESSION
(
  IN SESSION_ID VARCHAR(32),
  IN ACCOUNT_ID VARCHAR(32),
	IN APPLICATION_ID VARCHAR(32),
  IN DATE_CREATE DATETIME,
	IN DATE_CHANGE DATETIME,
	IN PARAMS LONGBLOB,
  IN OLD_SESSION_ID VARCHAR(32)
)
BEGIN
  UPDATE /*PREFIX*/SESSIONS S
     SET S.SESSION_ID=SESSION_ID,
         S.ACCOUNT_ID=ACCOUNT_ID,
         S.APPLICATION_ID=APPLICATION_ID,
         S.DATE_CREATE=DATE_CREATE,
				 S.DATE_CHANGE=DATE_CHANGE,
				 S.PARAMS=PARAMS
   WHERE S.SESSION_ID=OLD_SESSION_ID;
END;

--

/* Создание процедуры удаления сессии */

CREATE PROCEDURE /*PREFIX*/D_SESSION
(
  IN OLD_SESSION_ID VARCHAR(32)
)
BEGIN
  DELETE FROM /*PREFIX*/SESSIONS
        WHERE SESSION_ID=OLD_SESSION_ID;
END;

--