/* Создание таблицы колонок */

CREATE TABLE /*PREFIX*/COLUMNS
(
  COLUMN_ID VARCHAR(32) NOT NULL,
  PRESENTATION_ID VARCHAR(32) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(250),
  PRIORITY INTEGER NOT NULL,
  VALUE_DEFAULT VARCHAR(250),
  VISIBLE INTEGER NOT NULL,
  USE_DEPEND INTEGER NOT NULL,
  NOT_EMPTY INTEGER NOT NULL,
  WIDTH VARCHAR(10),
  ALIGN INTEGER NOT NULL,
  PRIMARY KEY (COLUMN_ID),
  FOREIGN KEY (PRESENTATION_ID) REFERENCES PRESENTATIONS (PRESENTATION_ID)
)

--

/* Создание просмотра таблицы колонок */

CREATE VIEW /*PREFIX*/S_COLUMNS
AS
SELECT C.*,
       P.NAME AS PRESENTATION_NAME
  FROM /*PREFIX*/COLUMNS C
  JOIN /*PREFIX*/PRESENTATIONS P ON  P.PRESENTATION_ID=C.PRESENTATION_ID

--

/* Создание процедуры добавления колонки */

CREATE PROCEDURE /*PREFIX*/I_COLUMN
(
  IN COLUMN_ID VARCHAR(32),
  IN NAME VARCHAR(100),
  IN DESCRIPTION VARCHAR(250),
  IN PRESENTATION_ID VARCHAR(32),
  IN PRIORITY INTEGER,
  IN VALUE_DEFAULT VARCHAR(250),
  IN VISIBLE INTEGER,
  IN USE_DEPEND INTEGER,
  IN NOT_EMPTY INTEGER,
  IN WIDTH VARCHAR(10),
  IN ALIGN INTEGER
)
BEGIN
  INSERT INTO /*PREFIX*/COLUMNS (COLUMN_ID,NAME,DESCRIPTION,PRESENTATION_ID,PRIORITY,
                                 VALUE_DEFAULT,VISIBLE,USE_DEPEND,NOT_EMPTY,WIDTH,ALIGN)
       VALUES (COLUMN_ID,NAME,DESCRIPTION,PRESENTATION_ID,PRIORITY,
               VALUE_DEFAULT,VISIBLE,USE_DEPEND,NOT_EMPTY,WIDTH,ALIGN);
END;

--

/* Создание процедуры изменения колонки */

CREATE PROCEDURE /*PREFIX*/U_COLUMN
(
  IN COLUMN_ID VARCHAR(32),
  IN NAME VARCHAR(100),
  IN DESCRIPTION VARCHAR(250),
  IN PRESENTATION_ID VARCHAR(32),
  IN PRIORITY INTEGER,
  IN VALUE_DEFAULT VARCHAR(250),
  IN VISIBLE INTEGER,
  IN USE_DEPEND INTEGER,
  IN NOT_EMPTY INTEGER,
  IN WIDTH VARCHAR(10),
  IN ALIGN INTEGER,
  IN OLD_COLUMN_ID VARCHAR(32)
)
BEGIN
  UPDATE /*PREFIX*/COLUMNS C
     SET C.COLUMN_ID=COLUMN_ID,
         C.NAME=NAME,
         C.DESCRIPTION=DESCRIPTION,
         C.PRESENTATION_ID=PRESENTATION_ID,
         C.PRIORITY=PRIORITY,
	       C.VALUE_DEFAULT=VALUE_DEFAULT,
	       C.VISIBLE=VISIBLE,
	       C.USE_DEPEND=USE_DEPEND,
	       C.NOT_EMPTY=NOT_EMPTY,
	       C.WIDTH=WIDTH,
	       C.ALIGN=ALIGN
   WHERE C.COLUMN_ID=OLD_COLUMN_ID;
END;

--

/* Создание процедуры удаления колонки */

CREATE PROCEDURE /*PREFIX*/D_COLUMN
(
	IN OLD_COLUMN_ID VARCHAR(32)
)
BEGIN
  DELETE FROM /*PREFIX*/COLUMNS 
        WHERE COLUMN_ID=OLD_COLUMN_ID;
END;

--