/* Создание таблицы параметров доступных пользователю */

CREATE TABLE /*PREFIX*/ACCOUNT_PARAMS
(
  ACCOUNT_ID VARCHAR(32) NOT NULL,
  PARAM_ID VARCHAR(32) NOT NULL,
  PRIORITY INTEGER NOT NULL,
  PRIMARY KEY (ACCOUNT_ID,PARAM_ID),
  FOREIGN KEY (ACCOUNT_ID) REFERENCES /*PREFIX*/ACCOUNTS (ACCOUNT_ID),
  FOREIGN KEY (PARAM_ID) REFERENCES /*PREFIX*/PARAMS (PARAM_ID)
)

--

/* Создание просмотра таблицы параметров доступных пользователю */

CREATE VIEW /*PREFIX*/S_ACCOUNT_PARAMS
AS
SELECT AP.*,
       A.USER_NAME,
			 P.NAME AS PARAM_NAME
  FROM /*PREFIX*/ACCOUNT_PARAMS AP
	JOIN /*PREFIX*/ACCOUNTS A ON A.ACCOUNT_ID=AP.ACCOUNT_ID
	JOIN /*PREFIX*/PARAMS P ON P.PARAM_ID=AP.PARAM_ID
			
--

/* Создание процедуры добавления пользователю параметра */

CREATE PROCEDURE /*PREFIX*/I_ACCOUNT_PARAM
(
  IN ACCOUNT_ID VARCHAR(32),
  IN PARAM_ID VARCHAR(32),
  IN PRIORITY INTEGER
)
BEGIN
  INSERT INTO /*PREFIX*/ACCOUNT_PARAMS (ACCOUNT_ID,PARAM_ID,PRIORITY)
       VALUES (ACCOUNT_ID,PARAM_ID,PRIORITY);
END;

--

/* Создание процедуры изменения параметра у пользователя */

CREATE PROCEDURE /*PREFIX*/U_ACCOUNT_PARAM
(
  IN ACCOUNT_ID VARCHAR(32),
  IN PARAM_ID VARCHAR(32),
  IN PRIORITY INTEGER,
  IN OLD_ACCOUNT_ID VARCHAR(32),
  IN OLD_PARAM_ID VARCHAR(32)
)
BEGIN
  UPDATE /*PREFIX*/ACCOUNT_PARAMS AP
     SET AP.ACCOUNT_ID=ACCOUNT_ID,
         AP.PARAM_ID=PARAM_ID,
         AP.PRIORITY=PRIORITY
   WHERE AP.ACCOUNT_ID=OLD_ACCOUNT_ID
	   AND AP.PARAM_ID=OLD_PARAM_ID;
END;

--

/* Создание процедуры удаления параметра у пользователя */

CREATE PROCEDURE /*PREFIX*/D_ACCOUNT_PARAM
(
  IN OLD_ACCOUNT_ID VARCHAR(32),
	IN OLD_PARAM_ID VARCHAR(32)
)
BEGIN
  DELETE FROM /*PREFIX*/ACCOUNT_PARAMS 
        WHERE ACCOUNT_ID=OLD_ACCOUNT_ID
				  AND PARAM_ID=OLD_PARAM_ID;
END;

--