/* Создание таблицы интерфейсов */

CREATE TABLE /*PREFIX*/INTERFACES
(
  INTERFACE_ID VARCHAR(32) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(250),
  INTERFACE_TYPE INTEGER NOT NULL,
  MODULE_NAME VARCHAR(100),
  MODULE_INTERFACE VARCHAR(250) NULL,
  PRIMARY KEY (INTERFACE_ID)
)

--

/* Создание просмотра таблицы интерфейсов */

CREATE VIEW /*PREFIX*/S_INTERFACES
AS
SELECT * FROM /*PREFIX*/INTERFACES

--

/* Создание процедуры добавления интерфейса */

CREATE PROCEDURE /*PREFIX*/I_INTERFACE
(
  IN INTERFACE_ID VARCHAR(32),
  IN NAME VARCHAR(100),
  IN DESCRIPTION VARCHAR(250),
  IN INTERFACE_TYPE INTEGER,
  IN MODULE_NAME VARCHAR(100),
	IN MODULE_INTERFACE VARCHAR(250)
)
BEGIN
  INSERT INTO /*PREFIX*/INTERFACES (INTERFACE_ID,NAME,DESCRIPTION,INTERFACE_TYPE,MODULE_NAME,MODULE_INTERFACE)
       VALUES (INTERFACE_ID,NAME,DESCRIPTION,INTERFACE_TYPE,MODULE_NAME,MODULE_INTERFACE);
END;

--

/* Создание процедуры изменения интерфейса */

CREATE PROCEDURE /*PREFIX*/U_INTERFACE
(
  IN INTERFACE_ID VARCHAR(32),
  IN NAME VARCHAR(100),
  IN DESCRIPTION VARCHAR(250),
	IN INTERFACE_TYPE INTEGER, 
	IN MODULE_NAME VARCHAR(100),
	IN MODULE_INTERFACE VARCHAR(250),
  IN OLD_INTERFACE_ID VARCHAR(32)
)
BEGIN
  UPDATE /*PREFIX*/INTERFACES I
     SET I.INTERFACE_ID=INTERFACE_ID,
         I.NAME=NAME,
         I.DESCRIPTION=DESCRIPTION,
				 I.INTERFACE_TYPE=INTERFACE_TYPE,
	       I.MODULE_NAME=MODULE_NAME,
				 I.MODULE_INTERFACE=MODULE_INTERFACE
   WHERE I.INTERFACE_ID=OLD_INTERFACE_ID;
END;

--

/* Создание процедуры удаления интерфейса */

CREATE PROCEDURE /*PREFIX*/D_INTERFACE
(
  IN OLD_INTERFACE_ID VARCHAR(32)
)
BEGIN
  DELETE FROM /*PREFIX*/INTERFACES 
        WHERE INTERFACE_ID=OLD_INTERFACE_ID;
END;

--