/* Создание таблицы услуг */

CREATE TABLE /*PREFIX*/SERVICES
(
  SERVICE_ID VARCHAR(32) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(250),
  PRIORITY INTEGER NOT NULL,
  PRIMARY KEY (SERVICE_ID)
)

--

/* Создание просмотра таблицы услуг */

CREATE VIEW /*PREFIX*/S_SERVICES
AS
SELECT * FROM /*PREFIX*/SERVICES

--

/* Создание процедуры добавления услуги */

CREATE PROCEDURE /*PREFIX*/I_SERVICE
(
  IN SERVICE_ID VARCHAR(32),
  IN NAME VARCHAR(100),
  IN DESCRIPTION VARCHAR(250),
	IN PRIORITY INTEGER
)
BEGIN
  INSERT INTO /*PREFIX*/SERVICES (SERVICE_ID,NAME,DESCRIPTION,PRIORITY)
       VALUES (SERVICE_ID,NAME,DESCRIPTION,PRIORITY);
END;

--

/* Создание процедуры изменения услуги */

CREATE PROCEDURE /*PREFIX*/U_SERVICE
(
  IN SERVICE_ID VARCHAR(32),
  IN NAME VARCHAR(100),
  IN DESCRIPTION VARCHAR(250),
	IN PRIORITY INTEGER,
  IN OLD_SERVICE_ID VARCHAR(32)
)
BEGIN
  UPDATE /*PREFIX*/SERVICES V
     SET V.SERVICE_ID=SERVICE_ID,
         V.NAME=NAME,
	       V.DESCRIPTION=DESCRIPTION,
				 V.PRIORITY=PRIORITY
   WHERE V.SERVICE_ID=OLD_SERVICE_ID;
END;

--

/* Создание процедуры удаления услуги */

CREATE PROCEDURE /*PREFIX*/D_SERVICE
(
  IN OLD_SERVICE_ID VARCHAR(32)
)
BEGIN
  DELETE FROM /*PREFIX*/SERVICES 
        WHERE SERVICE_ID=OLD_SERVICE_ID;
END;

--