/* Создание таблицы страниц */

CREATE TABLE /*PREFIX*/PAGES
(
  PAGE_ID VARCHAR(32) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(250),
  ADDRESS VARCHAR(250) NOT NULL,
  PRIMARY KEY (PAGE_ID)
)

--

/* Создание просмотра таблицы страниц */

CREATE VIEW /*PREFIX*/S_PAGES
AS
SELECT * FROM /*PREFIX*/PAGES

--

/* Создание процедуры добавления страницы */

CREATE PROCEDURE /*PREFIX*/I_PAGE
(
  IN PAGE_ID VARCHAR(32),
  IN NAME VARCHAR(100),
  IN DESCRIPTION VARCHAR(250),
	IN ADDRESS VARCHAR(250)
)
BEGIN
  INSERT INTO /*PREFIX*/PAGES (PAGE_ID,NAME,DESCRIPTION,ADDRESS)
       VALUES (PAGE_ID,NAME,DESCRIPTION,ADDRESS);
END;

--

/* Создание процедуры изменения страницы */

CREATE PROCEDURE /*PREFIX*/U_PAGE
(
  IN PAGE_ID VARCHAR(32),
  IN NAME VARCHAR(100),
  IN DESCRIPTION VARCHAR(250),
	IN ADDRESS VARCHAR(250),
  IN OLD_PAGE_ID VARCHAR(32)
)
BEGIN
  UPDATE /*PREFIX*/PAGES V
     SET V.PAGE_ID=PAGE_ID,
         V.NAME=NAME,
	       V.DESCRIPTION=DESCRIPTION,
				 V.ADDRESS=ADDRESS
   WHERE V.PAGE_ID=OLD_PAGE_ID;
END;

--

/* Создание процедуры удаления страницы */

CREATE PROCEDURE /*PREFIX*/D_PAGE
(
  IN OLD_PAGE_ID VARCHAR(32)
)
BEGIN
  DELETE FROM /*PREFIX*/PAGES 
        WHERE PAGE_ID=OLD_PAGE_ID;
END;

--

