/* Создание таблицы размещения рекламы */

CREATE TABLE /*PREFIX*/ADVERTISMENT_PAGES
(
  ADVERTISMENT_ID VARCHAR(32) NOT NULL,
  PAGE_ID VARCHAR(32) NOT NULL,
	ACCOUNT_ID VARCHAR(32) NOT NULL,
	PLACE INTEGER NOT NULL,
        PLACE2 VARCHAR(10) NOT NULL,
	DATE_BEGIN DATE NOT NULL,
	DATE_END DATE,
	PRIORITY INTEGER NOT NULL,
	COUNTER INTEGER,
	WHO_PLACED VARCHAR(32) NOT NULL,
	DATE_PLACED DATETIME NOT NULL,
  PRIMARY KEY (ADVERTISMENT_ID,PAGE_ID,ACCOUNT_ID),
  FOREIGN KEY (ADVERTISMENT_ID) REFERENCES ADVERTISMENTS (ADVERTISMENT_ID),
  FOREIGN KEY (PAGE_ID) REFERENCES PAGES (PAGE_ID),
  FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS (ACCOUNT_ID),
  FOREIGN KEY (WHO_PLACED) REFERENCES ACCOUNTS (ACCOUNT_ID)
)

--

/* Создание просмотра таблицы размещения рекламы */

CREATE VIEW /*PREFIX*/S_ADVERTISMENT_PAGES
AS
SELECT AP.*,
			 A.NAME AS ADVERTISMENT_NAME,
			 P.NAME AS PAGE_NAME,
			 AC1.USER_NAME, 
			 AC2.USER_NAME AS WHO_PLACED_NAME 
  FROM /*PREFIX*/ADVERTISMENT_PAGES AP
	JOIN /*PREFIX*/ADVERTISMENTS A ON  A.ADVERTISMENT_ID=AP.ADVERTISMENT_ID
  JOIN /*PREFIX*/PAGES P ON P.PAGE_ID=AP.PAGE_ID
  JOIN /*PREFIX*/ACCOUNTS AC1 ON AC1.ACCOUNT_ID=AP.ACCOUNT_ID
  JOIN /*PREFIX*/ACCOUNTS AC2 ON AC2.ACCOUNT_ID=AP.WHO_PLACED
	
--

/* Создание процедуры добавления размещения рекламы */

CREATE PROCEDURE /*PREFIX*/I_ADVERTISMENT_PAGE
(
  IN ADVERTISMENT_ID VARCHAR(32),
  IN PAGE_ID VARCHAR(32),
	IN ACCOUNT_ID VARCHAR(32),
	IN PLACE INTEGER,
	IN PLACE2 VARCHAR(10),
	IN DATE_BEGIN DATE,
	IN DATE_END DATE,
  IN PRIORITY INTEGER,
	IN COUNTER INTEGER,
	IN WHO_PLACED VARCHAR(32),
	IN DATE_PLACED DATETIME
)
BEGIN
  INSERT INTO /*PREFIX*/ADVERTISMENT_PAGES (ADVERTISMENT_ID,PAGE_ID,ACCOUNT_ID,PLACE,PLACE2,DATE_BEGIN,
	                                          DATE_END,PRIORITY,COUNTER,WHO_PLACED,DATE_PLACED)
       VALUES (ADVERTISMENT_ID,PAGE_ID,ACCOUNT_ID,PLACE,PLACE2,DATE_BEGIN,
	             DATE_END,PRIORITY,COUNTER,WHO_PLACED,DATE_PLACED);
END;

--

/* Создание процедуры изменения размещения рекламы */

CREATE PROCEDURE /*PREFIX*/U_ADVERTISMENT_PAGE
(
  IN ADVERTISMENT_ID VARCHAR(32),
  IN PAGE_ID VARCHAR(32),
	IN ACCOUNT_ID VARCHAR(32),
	IN PLACE INTEGER,
	IN PLACE2 VARCHAR(10),
	IN DATE_BEGIN DATE,
	IN DATE_END DATE,
  IN PRIORITY INTEGER,
	IN COUNTER INTEGER,
	IN WHO_PLACED VARCHAR(32),
	IN DATE_PLACED DATETIME,
  IN OLD_ADVERTISMENT_ID VARCHAR(32),
  IN OLD_PAGE_ID VARCHAR(32),
  IN OLD_ACCOUNT_ID VARCHAR(32)
)
BEGIN
  UPDATE /*PREFIX*/ADVERTISMENT_PAGES AP
     SET AP.ADVERTISMENT_ID=ADVERTISMENT_ID,
		     AP.PAGE_ID=PAGE_ID,
         AP.ACCOUNT_ID=ACCOUNT_ID,
         AP.PLACE=PLACE,
				 AP.PLACE2=PLACE2,
         AP.DATE_BEGIN=DATE_BEGIN,
         AP.DATE_END=DATE_END,
         AP.PRIORITY=PRIORITY,
         AP.COUNTER=COUNTER,
         AP.WHO_PLACED=WHO_PLACED,
         AP.DATE_PLACED=DATE_PLACED
   WHERE AP.ADVERTISMENT_ID=OLD_ADVERTISMENT_ID
	   AND AP.PAGE_ID=OLD_PAGE_ID
		 AND AP.ACCOUNT_ID=OLD_ACCOUNT_ID;
END;

--

/* Создание процедуры удаления размещения рекламы */

CREATE PROCEDURE /*PREFIX*/D_ADVERTISMENT_PAGE
(
  IN OLD_ADVERTISMENT_ID VARCHAR(32),
	IN OLD_PAGE_ID VARCHAR(32),
	IN OLD_ACCOUNT_ID VARCHAR(32)
)
BEGIN
  DELETE FROM /*PREFIX*/ADVERTISMENT_PAGES 
        WHERE ADVERTISMENT_ID=OLD_ADVERTISMENT_ID
				  AND PAGE_ID=OLD_PAGE_ID
					AND ACCOUNT_ID=OLD_ACCOUNT_ID;
END;

--