/* Создание таблицы выпусков */

CREATE TABLE /*PREFIX*/ISSUES
(
  ISSUE_ID VARCHAR(32) NOT NULL,
  PUBLISHING_ID VARCHAR(32) NOT NULL,
	NUM VARCHAR(100) NOT NULL,
	DESCRIPTION VARCHAR(250),
	DATE_BEGIN DATE NOT NULL,
	DATE_END DATE NOT NULL,
	PRIMARY KEY (ISSUE_ID),
  FOREIGN KEY (PUBLISHING_ID) REFERENCES /*PREFIX*/PUBLISHING (PUBLISHING_ID)
)

--

/* Создание просмотра таблицы выпусков */

CREATE VIEW /*PREFIX*/S_ISSUES
AS
   SELECT S.*, 
          P.NAME AS PUBLISHING_NAME
     FROM /*PREFIX*/ISSUES S
     JOIN /*PREFIX*/PUBLISHING P ON P.PUBLISHING_ID=S.PUBLISHING_ID

--

/* Создание процедуры добавления выпуска */

CREATE PROCEDURE /*PREFIX*/I_ISSUE
(
  IN ISSUE_ID VARCHAR(32),
  IN PUBLISHING_ID VARCHAR(32),
	IN NUM VARCHAR(100),
	IN DESCRIPTION VARCHAR(250),
	IN DATE_BEGIN DATE,
	IN DATE_END DATE
)
BEGIN
  INSERT INTO /*PREFIX*/ISSUES (ISSUE_ID,PUBLISHING_ID,NUM,DESCRIPTION,DATE_BEGIN,DATE_END)
       VALUES (ISSUE_ID,PUBLISHING_ID,NUM,DESCRIPTION,DATE_BEGIN,DATE_END);
END;

--

/* Создание процедуры изменения выпуска */

CREATE PROCEDURE /*PREFIX*/U_ISSUE
(
  IN ISSUE_ID VARCHAR(32),
  IN PUBLISHING_ID VARCHAR(32),
	IN NUM VARCHAR(100),
	IN DESCRIPTION VARCHAR(250),
	IN DATE_BEGIN DATE,
	IN DATE_END DATE,
  IN OLD_ISSUE_ID VARCHAR(32)
)
BEGIN
  UPDATE /*PREFIX*/ISSUES I
     SET I.ISSUE_ID=ISSUE_ID,
         I.PUBLISHING_ID=PUBLISHING_ID,
         I.NUM=NUM,
         I.DESCRIPTION=DESCRIPTION,
				 I.DATE_BEGIN=DATE_BEGIN,
				 I.DATE_END=DATE_END
   WHERE I.ISSUE_ID=OLD_ISSUE_ID;
END;

--

/* Создание процедуры удаления выпуска */

CREATE PROCEDURE /*PREFIX*/D_ISSUE
(
  IN OLD_ISSUE_ID VARCHAR(32)
)
BEGIN
  DELETE FROM /*PREFIX*/ISSUES
        WHERE ISSUE_ID=OLD_ISSUE_ID;
END;

--