/* Создание таблицы принадлежности изданию */

CREATE TABLE /*PREFIX*/PUBLISHING_OBJECTS
(
  PUBLISHING_ID VARCHAR(32) NOT NULL,
  OBJECT_ID VARCHAR(32) NOT NULL,
  DATE_BEGIN DATETIME NOT NULL,
  DATE_END DATETIME,
  PRIMARY KEY (PUBLISHING_ID,OBJECT_ID),
  FOREIGN KEY (PUBLISHING_ID) REFERENCES /*PREFIX*/PUBLISHING (PUBLISHING_ID),
  FOREIGN KEY (OBJECT_ID) REFERENCES /*PREFIX*/OBJECTS (OBJECT_ID)
)

--

/* Создание просмотра таблицы принадлежности изданию */

CREATE VIEW /*PREFIX*/S_PUBLISHING_OBJECTS
AS
SELECT PO.*,
       P.NAME AS PUBLISHING_NAME,
       O.ACCOUNT_ID,
       O.OPERATION_ID,
       O.TYPE_ID,
       O.VIEW_ID,
       O.DESIGN_ID, 
       O.STATUS,
       O.PRIORITY,
       A.USER_NAME,
       V.NAME AS VIEW_NAME,
       V.NUM AS VIEW_NUM,
       T.NAME AS TYPE_NAME,
       T.NUM AS TYPE_NUM,
       OP.NAME AS OPERATION_NAME,
       OP.NUM AS OPERATION_NUM,
       D.NAME AS DESIGN_NAME,
       D.NUM AS DESIGN_NUM       
  FROM /*PREFIX*/PUBLISHING_OBJECTS PO
  JOIN /*PREFIX*/PUBLISHING P ON P.PUBLISHING_ID=PO.PUBLISHING_ID
  JOIN /*PREFIX*/OBJECTS O ON O.OBJECT_ID=PO.OBJECT_ID
  JOIN /*PREFIX*/ACCOUNTS A ON A.ACCOUNT_ID=O.ACCOUNT_ID
  JOIN /*PREFIX*/VIEWS V ON V.VIEW_ID=O.VIEW_ID
  JOIN /*PREFIX*/TYPES T ON T.TYPE_ID=O.TYPE_ID
  JOIN /*PREFIX*/OPERATIONS OP ON OP.OPERATION_ID=O.OPERATION_ID
  LEFT JOIN /*PREFIX*/DESIGNS D ON D.DESIGN_ID=O.DESIGN_ID
			
--

/* Создание процедуры добавления принадлежности объекта изданию */

CREATE PROCEDURE /*PREFIX*/I_PUBLISHING_OBJECT
(
  IN PUBLISHING_ID VARCHAR(32),
  IN OBJECT_ID VARCHAR(32),
	IN DATE_BEGIN DATETIME,
	IN DATE_END DATETIME,
  IN ACCOUNT_ID VARCHAR(32),
  IN VIEW_ID VARCHAR(32),
  IN TYPE_ID VARCHAR(32),
  IN OPERATION_ID VARCHAR(32),
  IN STATUS INTEGER,
  IN DESIGN_ID VARCHAR(32),
  IN PRIORITY INTEGER
)
BEGIN
  INSERT INTO /*PREFIX*/OBJECTS (OBJECT_ID,ACCOUNT_ID,VIEW_ID,TYPE_ID,
                                 OPERATION_ID,STATUS,DESIGN_ID,PRIORITY)
       VALUES (OBJECT_ID,ACCOUNT_ID,VIEW_ID,TYPE_ID,
               OPERATION_ID,STATUS,DESIGN_ID,PRIORITY);

  INSERT INTO /*PREFIX*/PUBLISHING_OBJECTS (PUBLISHING_ID,OBJECT_ID,DATE_BEGIN,DATE_END)
       VALUES (PUBLISHING_ID,OBJECT_ID,DATE_BEGIN,DATE_END);
END;

--

/* Создание процедуры добавления принадлежности объекта изданию 2 */

CREATE PROCEDURE /*PREFIX*/I_PUBLISHING_OBJECT2
(
  IN PUBLISHING_ID VARCHAR(32),
  IN OBJECT_ID VARCHAR(32),
	IN DATE_BEGIN DATETIME,
	IN DATE_END DATETIME
)
BEGIN
  INSERT INTO /*PREFIX*/PUBLISHING_OBJECTS (PUBLISHING_ID,OBJECT_ID,DATE_BEGIN,DATE_END)
       VALUES (PUBLISHING_ID,OBJECT_ID,DATE_BEGIN,DATE_END);
END;

--

/* Создание процедуры изменения принадлежности объекта изданию */

CREATE PROCEDURE /*PREFIX*/U_PUBLISHING_OBJECT
(
  IN PUBLISHING_ID VARCHAR(32),
  IN OBJECT_ID VARCHAR(32),
	IN DATE_BEGIN DATETIME,
	IN DATE_END DATETIME,
  IN ACCOUNT_ID VARCHAR(32),
  IN VIEW_ID VARCHAR(32),
  IN TYPE_ID VARCHAR(32),
  IN OPERATION_ID VARCHAR(32),
  IN STATUS INTEGER,
  IN DESIGN_ID VARCHAR(32),
  IN PRIORITY INTEGER,
  IN OLD_PUBLISHING_ID VARCHAR(32),
  IN OLD_OBJECT_ID VARCHAR(32)
)
BEGIN

 UPDATE /*PREFIX*/OBJECTS O
     SET O.OBJECT_ID=OBJECT_ID,
         O.ACCOUNT_ID=ACCOUNT_ID,
         O.VIEW_ID=VIEW_ID,
      	 O.TYPE_ID=TYPE_ID,
	       O.OPERATION_ID=OPERATION_ID,
	       O.STATUS=STATUS,
         O.DESIGN_ID=DESIGN_ID,
         O.PRIORITY=PRIORITY
   WHERE O.OBJECT_ID=OLD_OBJECT_ID;

  UPDATE /*PREFIX*/PUBLISHING_OBJECTS PO
     SET PO.PUBLISHING_ID=PUBLISHING_ID,
		     PO.OBJECT_ID=OBJECT_ID,
				 PO.DATE_BEGIN=DATE_BEGIN,
				 PO.DATE_END=DATE_END
   WHERE PO.PUBLISHING_ID=OLD_PUBLISHING_ID
	   AND PO.OBJECT_ID=OLD_OBJECT_ID;
END;

--

/* Создание процедуры удаления объекта у издания */

CREATE PROCEDURE /*PREFIX*/D_PUBLISHING_OBJECT
(
  IN OLD_PUBLISHING_ID VARCHAR(32),
	IN OLD_OBJECT_ID VARCHAR(32)
)
BEGIN

  DELETE FROM /*PREFIX*/OBJECT_PARAMS
        WHERE OBJECT_ID=OLD_OBJECT_ID;

  DELETE FROM /*PREFIX*/PUBLISHING_OBJECTS 
        WHERE PUBLISHING_ID=OLD_PUBLISHING_ID
          AND OBJECT_ID=OLD_OBJECT_ID;

	DELETE FROM /*PREFIX*/OBJECTS
        WHERE OBJECT_ID=OLD_OBJECT_ID;
				
END;

--