/* Создание таблицы журнала действий */

CREATE TABLE /*PREFIX*/JOURNAL_ACTIONS
(
  JOURNAL_ACTION_ID VARCHAR(32) NOT NULL,
  ACCOUNT_ID VARCHAR(32) NOT NULL,
  APPLICATION_ID VARCHAR(32) NOT NULL,
  ACTION_TYPE INTEGER NOT NULL,
  DATE_ACTION DATETIME NOT NULL,
  MODULE VARCHAR(250),
  OBJECT VARCHAR(250),
  METHOD VARCHAR(250),
  PARAM VARCHAR(250),
  VALUE LONGBLOB NOT NULL,
  PRIMARY KEY (JOURNAL_ACTION_ID),
  FOREIGN KEY (ACCOUNT_ID) REFERENCES /*PREFIX*/ACCOUNTS (ACCOUNT_ID),
  FOREIGN KEY (APPLICATION_ID) REFERENCES /*PREFIX*/APPLICATIONS (APPLICATION_ID)
)

--

/* Создание просмотра таблицы журнала действий */

CREATE VIEW /*PREFIX*/S_JOURNAL_ACTIONS
AS
   SELECT JA.*, 
          A.USER_NAME AS USER_NAME,
          AP.NAME AS APPLICATION_NAME
     FROM /*PREFIX*/JOURNAL_ACTIONS JA
     JOIN /*PREFIX*/ACCOUNTS A ON A.ACCOUNT_ID=JA.ACCOUNT_ID
     JOIN /*PREFIX*/APPLICATIONS AP ON AP.APPLICATION_ID=JA.APPLICATION_ID

--

/* Создание процедуры добавления действия в журнал */

CREATE PROCEDURE /*PREFIX*/I_JOURNAL_ACTION
(
  IN JOURNAL_ACTION_ID VARCHAR(32),
  IN ACCOUNT_ID VARCHAR(32),
  IN APPLICATION_ID VARCHAR(32),
  IN ACTION_TYPE INTEGER,
  IN DATE_ACTION DATETIME,
  IN MODULE VARCHAR(250),
  IN OBJECT VARCHAR(250),
  IN METHOD VARCHAR(250),
  IN PARAM VARCHAR(250),
  IN VALUE LONGBLOB
)
BEGIN
  INSERT INTO /*PREFIX*/JOURNAL_ACTIONS (JOURNAL_ACTION_ID,ACCOUNT_ID,APPLICATION_ID,ACTION_TYPE,
	                                 DATE_ACTION,MODULE,OBJECT,METHOD,PARAM,VALUE)
       VALUES (JOURNAL_ACTION_ID,ACCOUNT_ID,APPLICATION_ID,ACTION_TYPE,
	       DATE_ACTION,MODULE,OBJECT,METHOD,PARAM,VALUE);
END;

--

/* Создание процедуры изменения действия в журнале */

CREATE PROCEDURE /*PREFIX*/U_JOURNAL_ACTION
(
  IN JOURNAL_ACTION_ID VARCHAR(32),
  IN ACCOUNT_ID VARCHAR(32),
  IN APPLICATION_ID VARCHAR(32),
  IN ACTION_TYPE INTEGER,
  IN DATE_ACTION DATETIME,
  IN MODULE VARCHAR(250),
  IN OBJECT VARCHAR(250),
  IN METHOD VARCHAR(250),
  IN PARAM VARCHAR(250),
  IN VALUE LONGBLOB,
  IN OLD_JOURNAL_ACTION_ID VARCHAR(32)
)
BEGIN
  UPDATE /*PREFIX*/JOURNAL_ACTIONS AP
     SET AP.JOURNAL_ACTION_ID=JOURNAL_ACTION_ID,
         AP.ACCOUNT_ID=ACCOUNT_ID,
         AP.APPLICATION_ID=APPLICATION_ID,
         AP.ACTION_TYPE=ACTION_TYPE,
         AP.DATE_ACTION=DATE_ACTION,
         AP.MODULE=MODULE,
         AP.OBJECT=OBJECT,
         AP.METHOD=METHOD,
         AP.PARAM=PARAM,
         AP.VALUE=VALUE
   WHERE AP.JOURNAL_ACTION_ID=OLD_JOURNAL_ACTION_ID;
END;

--

/* Создание процедуры удаления действия из журнала */

CREATE PROCEDURE /*PREFIX*/D_JOURNAL_ACTION
(
  IN OLD_JOURNAL_ACTION_ID VARCHAR(32)
)
BEGIN
  DELETE FROM /*PREFIX*/JOURNAL_ACTIONS
        WHERE JOURNAL_ACTION_ID=OLD_JOURNAL_ACTION_ID;
END;

--