/* Создание таблицы кредитных программ */

CREATE TABLE /*PREFIX*/CREDIT_PROGRAMS
(
  CREDIT_PROGRAM_ID VARCHAR(32) NOT NULL,
  FIRM_ID VARCHAR(32) NOT NULL,
  PROGRAM_TYPE INTEGER NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(250),
  PERIOD_MIN INTEGER,
  PERIOD_MAX INTEGER,
  RATE_FROM FLOAT,
  RATE_BEFORE FLOAT,
  AMOUNT_MIN FLOAT,
  AMOUNT_MAX FLOAT,
  CURRENCY INTEGER NOT NULL,
  AGE_FROM INTEGER,
  AGE_BEFORE INTEGER,
  PRIMARY KEY (CREDIT_PROGRAM_ID),
  FOREIGN KEY (FIRM_ID) REFERENCES /*PREFIX*/FIRMS (FIRM_ID)
)

--

/* Создание просмотра таблицы кредитных программ */

CREATE VIEW /*PREFIX*/S_CREDIT_PROGRAMS
AS
   SELECT CP.*, 
          F.SMALL_NAME AS FIRM_SMALL_NAME
     FROM /*PREFIX*/CREDIT_PROGRAMS CP
     JOIN /*PREFIX*/FIRMS F ON F.FIRM_ID=CP.FIRM_ID

--

/* Создание процедуры добавления кредитной программы */

CREATE PROCEDURE /*PREFIX*/I_CREDIT_PROGRAM
(
  IN CREDIT_PROGRAM_ID VARCHAR(32),
  IN FIRM_ID VARCHAR(32),
  IN PROGRAM_TYPE INTEGER,
  IN NAME VARCHAR(100),
  IN DESCRIPTION VARCHAR(250),
  IN PERIOD_MIN INTEGER,
  IN PERIOD_MAX INTEGER,
  IN RATE_FROM FLOAT,
  IN RATE_BEFORE FLOAT,
  IN AMOUNT_MIN FLOAT,
  IN AMOUNT_MAX FLOAT,
  IN CURRENCY INTEGER,
  IN AGE_FROM INTEGER,
  IN AGE_BEFORE INTEGER
)
BEGIN
  INSERT INTO /*PREFIX*/CREDIT_PROGRAMS (CREDIT_PROGRAM_ID,FIRM_ID,PROGRAM_TYPE,NAME,DESCRIPTION,PERIOD_MIN,PERIOD_MAX,
	                                 RATE_FROM,RATE_BEFORE,AMOUNT_MIN,AMOUNT_MAX,CURRENCY,AGE_FROM,AGE_BEFORE)
       VALUES (CREDIT_PROGRAM_ID,FIRM_ID,PROGRAM_TYPE,NAME,DESCRIPTION,PERIOD_MIN,PERIOD_MAX,
               RATE_FROM,RATE_BEFORE,AMOUNT_MIN,AMOUNT_MAX,CURRENCY,AGE_FROM,AGE_BEFORE);
END;

--

/* Создание процедуры изменения кредитной программы */

CREATE PROCEDURE /*PREFIX*/U_CREDIT_PROGRAM
(
  IN CREDIT_PROGRAM_ID VARCHAR(32),
  IN FIRM_ID VARCHAR(32),
  IN PROGRAM_TYPE INTEGER,
  IN NAME VARCHAR(100),
  IN DESCRIPTION VARCHAR(250),
  IN PERIOD_MIN INTEGER,
  IN PERIOD_MAX INTEGER,
  IN RATE_FROM FLOAT,
  IN RATE_BEFORE FLOAT,
  IN AMOUNT_MIN FLOAT,
  IN AMOUNT_MAX FLOAT,
  IN CURRENCY INTEGER,
  IN AGE_FROM INTEGER,
  IN AGE_BEFORE INTEGER,
  IN OLD_CREDIT_PROGRAM_ID VARCHAR(32)
)
BEGIN
  UPDATE /*PREFIX*/CREDIT_PROGRAMS CP
     SET CP.CREDIT_PROGRAM_ID=CREDIT_PROGRAM_ID,
         CP.FIRM_ID=FIRM_ID,
         CP.PROGRAM_TYPE=PROGRAM_TYPE,
         CP.NAME=NAME,
         CP.DESCRIPTION=DESCRIPTION,
         CP.PERIOD_MIN=PERIOD_MIN,
         CP.PERIOD_MAX=PERIOD_MAX,
         CP.RATE_FROM=RATE_FROM,
         CP.RATE_BEFORE=RATE_BEFORE,
         CP.AMOUNT_MIN=AMOUNT_MIN,
         CP.AMOUNT_MAX=AMOUNT_MAX,
         CP.CURRENCY=CURRENCY,
         CP.AGE_FROM=AGE_FROM,
         CP.AGE_BEFORE=AGE_BEFORE
   WHERE CP.CREDIT_PROGRAM_ID=OLD_CREDIT_PROGRAM_ID;
END;

--

/* Создание процедуры удаления кредитной программы */

CREATE PROCEDURE /*PREFIX*/D_CREDIT_PROGRAM
(
  IN OLD_CREDIT_PROGRAM_ID VARCHAR(32)
)
BEGIN
  DELETE FROM /*PREFIX*/CREDIT_PROGRAMS
        WHERE CREDIT_PROGRAM_ID=OLD_CREDIT_PROGRAM_ID;
END;

--