/* Создание процедуры подсчета детальной статистики */

CREATE PROCEDURE /*PREFIX*/P_AMOUNT_DETAIL
(
  IN ACCOUNT_ID VARCHAR(32),
  IN PUBLISHING_ID VARCHAR(32),
  IN DATE_BEGIN DATETIME,
	IN DATE_END DATETIME
)
BEGIN
  DECLARE ADATE_BEGIN DATETIME;
  DECLARE ADATE_END DATETIME;
	
	SET ADATE_BEGIN=DATE_BEGIN;
	SET ADATE_END=DATE_END;

  IF (ADATE_BEGIN IS NULL) THEN
    SELECT MIN(PO.DATE_BEGIN) INTO ADATE_BEGIN
  	  FROM /*PREFIX*/PUBLISHING_OBJECTS PO
	   WHERE PO.PUBLISHING_ID=PUBLISHING_ID;
	END IF;	 
	 
  IF (ADATE_END IS NULL) THEN
    SELECT MAX(PO.DATE_BEGIN) INTO ADATE_END
	    FROM /*PREFIX*/PUBLISHING_OBJECTS PO
	   WHERE PO.PUBLISHING_ID=PUBLISHING_ID;
	END IF;	 
	 	 
  SELECT V.NAME AS VIEW_NAME,
         T.NAME AS TYPE_NAME,

		  	 (SELECT COUNT(*) 
			      FROM PUBLISHING_OBJECTS PO 
			      JOIN OBJECTS O ON O.OBJECT_ID=PO.OBJECT_ID
				   WHERE O.VIEW_ID=VT.VIEW_ID AND O.TYPE_ID=VT.TYPE_ID 
  				   AND O.OPERATION_ID='9BB38FBAEE8B88A54FD02C983AE5C607' 
						 AND O.ACCOUNT_ID=ACCOUNT_ID
						 AND PO.PUBLISHING_ID=PUBLISHING_ID
						 AND PO.DATE_BEGIN>=ADATE_BEGIN
						 AND PO.DATE_BEGIN<=ADATE_END
						 ) AS SELL_AMOUNT,
					 
			   (SELECT COUNT(*) 
			      FROM PUBLISHING_OBJECTS PO 
			      JOIN OBJECTS O ON O.OBJECT_ID=PO.OBJECT_ID
				   WHERE O.VIEW_ID=VT.VIEW_ID AND O.TYPE_ID=VT.TYPE_ID 
   				   AND O.OPERATION_ID='A7D600213026BBCE43F7B4676A8DC7F1' 
	  				 AND O.ACCOUNT_ID=ACCOUNT_ID
						 AND PO.PUBLISHING_ID=PUBLISHING_ID
						 AND PO.DATE_BEGIN>=ADATE_BEGIN
						 AND PO.DATE_BEGIN<=ADATE_END
						 ) AS BUY_AMOUNT,

		  	 (SELECT COUNT(*) 
			      FROM PUBLISHING_OBJECTS PO 
			      JOIN OBJECTS O ON O.OBJECT_ID=PO.OBJECT_ID
				   WHERE O.VIEW_ID=VT.VIEW_ID AND O.TYPE_ID=VT.TYPE_ID 
				     AND O.OPERATION_ID='D5F0B39F9E48A9304EA0A28ABFA2132F' 
					   AND O.ACCOUNT_ID=ACCOUNT_ID
						 AND PO.PUBLISHING_ID=PUBLISHING_ID
						 AND PO.DATE_BEGIN>=ADATE_BEGIN
						 AND PO.DATE_BEGIN<=ADATE_END
						 ) AS CHANGE_AMOUNT,

			   (SELECT COUNT(*) 
			      FROM PUBLISHING_OBJECTS PO 
			      JOIN OBJECTS O ON O.OBJECT_ID=PO.OBJECT_ID
				   WHERE O.VIEW_ID=VT.VIEW_ID AND O.TYPE_ID=VT.TYPE_ID 
				     AND O.OPERATION_ID='31B977EB8E80ABEB4BB4215FD6777072' 
					   AND O.ACCOUNT_ID=ACCOUNT_ID
						 AND PO.PUBLISHING_ID=PUBLISHING_ID
						 AND PO.DATE_BEGIN>=ADATE_BEGIN
						 AND PO.DATE_BEGIN<=ADATE_END
						 ) AS DELIVER_AMOUNT,

			   (SELECT COUNT(*) 
			      FROM PUBLISHING_OBJECTS PO 
			      JOIN OBJECTS O ON O.OBJECT_ID=PO.OBJECT_ID
				   WHERE O.VIEW_ID=VT.VIEW_ID AND O.TYPE_ID=VT.TYPE_ID 
				     AND O.OPERATION_ID='8B5206B8E53DB842408847A0C46E0A1D' 
					   AND O.ACCOUNT_ID=ACCOUNT_ID
						 AND PO.PUBLISHING_ID=PUBLISHING_ID
						 AND PO.DATE_BEGIN>=ADATE_BEGIN
						 AND PO.DATE_BEGIN<=ADATE_END
						 ) AS SHOOT_AMOUNT

	  FROM VIEW_TYPES VT 
	  JOIN VIEWS V ON V.VIEW_ID=VT.VIEW_ID
	  JOIN TYPES T ON T.TYPE_ID=VT.TYPE_ID
   ORDER BY V.PRIORITY, VT.PRIORITY;
 
END;


--

