/* Создание таблицы констант */

CREATE TABLE /*PREFIX*/CONSTS
(
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(250),
  VALUE LONGBLOB NOT NULL,
  PRIMARY KEY (NAME)
)

--

/* Создание просмотра таблицы констант */

CREATE VIEW /*PREFIX*/S_CONSTS
AS
SELECT * FROM /*PREFIX*/CONSTS

--

/* Создание процедуры добавления константы */

CREATE PROCEDURE /*PREFIX*/I_CONST
(
  IN NAME VARCHAR(100),
  IN DESCRIPTION VARCHAR(250),
  IN VALUE LONGBLOB
)
BEGIN
  INSERT INTO /*PREFIX*/CONSTS (NAME,DESCRIPTION,VALUE)
       VALUES (NAME,DESCRIPTION,VALUE);
END;

--

/* Создание процедуры изменения константы */

CREATE PROCEDURE /*PREFIX*/U_CONST
(
  IN NAME VARCHAR(100),
  IN DESCRIPTION VARCHAR(250),
  IN VALUE LONGBLOB,
  IN OLD_NAME VARCHAR(100)
)
BEGIN
  UPDATE /*PREFIX*/CONSTS C
     SET C.NAME=NAME,
         C.DESCRIPTION=DESCRIPTION,
         C.VALUE=VALUE
   WHERE C.NAME=OLD_NAME;
END;

--

/* Создание процедуры удаления константы */

CREATE PROCEDURE /*PREFIX*/D_CONST
(
  IN OLD_NAME VARCHAR(100)
)
BEGIN
  DELETE FROM /*PREFIX*/CONSTS 
        WHERE NAME=OLD_NAME;
END;

--