/* Создание таблицы подписки */

CREATE TABLE /*PREFIX*/SUBSCRIPTIONS
(
  SUBSCRIPTION_ID VARCHAR(32) NOT NULL,
  SERVICE_ID VARCHAR(32) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(250),
  PRIMARY KEY (SUBSCRIPTION_ID),
  FOREIGN KEY (SERVICE_ID) REFERENCES /*PREFIX*/SERVICES (SERVICE_ID)
)

--

/* Создание просмотра таблицы подписки */

CREATE VIEW /*PREFIX*/S_SUBSCRIPTIONS
AS
   SELECT S.*, 
          S1.NAME AS SERVICE_NAME
     FROM /*PREFIX*/SUBSCRIPTIONS S
     JOIN /*PREFIX*/SERVICES S1 ON S1.SERVICE_ID=S.SERVICE_ID

--

/* Создание процедуры добавления подписки */

CREATE PROCEDURE /*PREFIX*/I_SUBSCRIPTION
(
  IN SUBSCRIPTION_ID VARCHAR(32),
  IN SERVICE_ID VARCHAR(32),
	IN NAME VARCHAR(100),
	IN DESCRIPTION VARCHAR(250)
)
BEGIN
  INSERT INTO /*PREFIX*/SUBSCRIPTIONS (SUBSCRIPTION_ID,SERVICE_ID,NAME,DESCRIPTION)
       VALUES (SUBSCRIPTION_ID,SERVICE_ID,NAME,DESCRIPTION);
END;

--

/* Создание процедуры изменения подписки */

CREATE PROCEDURE /*PREFIX*/U_SUBSCRIPTION
(
  IN SUBSCRIPTION_ID VARCHAR(32),
  IN SERVICE_ID VARCHAR(32),
	IN NAME VARCHAR(100),
	IN DESCRIPTION VARCHAR(250),
  IN OLD_SUBSCRIPTION_ID VARCHAR(32)
)
BEGIN
  UPDATE /*PREFIX*/SUBSCRIPTIONS S
     SET S.SUBSCRIPTION_ID=SUBSCRIPTION_ID,
         S.SERVICE_ID=SERVICE_ID,
         S.NAME=NAME,
         S.DESCRIPTION=DESCRIPTION
   WHERE S.SUBSCRIPTION_ID=OLD_SUBSCRIPTION_ID;
END;

--

/* Создание процедуры удаления подписки */

CREATE PROCEDURE /*PREFIX*/D_SUBSCRIPTION
(
  IN OLD_SUBSCRIPTION_ID VARCHAR(32)
)
BEGIN
  DELETE FROM /*PREFIX*/SUBSCRIPTIONS
        WHERE SUBSCRIPTION_ID=OLD_SUBSCRIPTION_ID;
END;

--