/* Создание таблицы доступа к подписке */

CREATE TABLE /*PREFIX*/ACCOUNT_SUBSCRIPTIONS
(
  ACCOUNT_ID VARCHAR(32) NOT NULL,
  SUBSCRIPTION_ID VARCHAR(32) NOT NULL,
  DATE_BEGIN DATETIME NOT NULL,
  DATE_END DATETIME,
  ACCESS_TYPE INTEGER NOT NULL,
  PRIMARY KEY (ACCOUNT_ID,SUBSCRIPTION_ID),
  FOREIGN KEY (ACCOUNT_ID) REFERENCES /*PREFIX*/ACCOUNTS (ACCOUNT_ID),
  FOREIGN KEY (SUBSCRIPTION_ID) REFERENCES /*PREFIX*/SUBSCRIPTIONS (SUBSCRIPTION_ID)
)

--

/* Создание просмотра таблицы доступа к подписке */

CREATE VIEW /*PREFIX*/S_ACCOUNT_SUBSCRIPTIONS
AS
SELECT ACS.*,
       A.USER_NAME,
       S.NAME AS SUBSCRIPTION_NAME
  FROM /*PREFIX*/ACCOUNT_SUBSCRIPTIONS ACS
  JOIN /*PREFIX*/ACCOUNTS A ON A.ACCOUNT_ID=ACS.ACCOUNT_ID
  JOIN /*PREFIX*/SUBSCRIPTIONS S ON S.SUBSCRIPTION_ID=ACS.SUBSCRIPTION_ID
			
--

/* Создание процедуры добавления доступа к подписке */

CREATE PROCEDURE /*PREFIX*/I_ACCOUNT_SUBSCRIPTION
(
  IN ACCOUNT_ID VARCHAR(32),
  IN SUBSCRIPTION_ID VARCHAR(32),
	IN DATE_BEGIN DATETIME,
	IN DATE_END DATETIME,
	IN ACCESS_TYPE INTEGER
)
BEGIN
  INSERT INTO /*PREFIX*/ACCOUNT_SUBSCRIPTIONS (ACCOUNT_ID,SUBSCRIPTION_ID,DATE_BEGIN,DATE_END,ACCESS_TYPE)
       VALUES (ACCOUNT_ID,SUBSCRIPTION_ID,DATE_BEGIN,DATE_END,ACCESS_TYPE);
END;

--

/* Создание процедуры изменения доступа к подписке */

CREATE PROCEDURE /*PREFIX*/U_ACCOUNT_SUBSCRIPTION
(
  IN ACCOUNT_ID VARCHAR(32),
  IN SUBSCRIPTION_ID VARCHAR(32),
	IN DATE_BEGIN DATETIME,
	IN DATE_END DATETIME,
	IN ACCESS_TYPE INTEGER,
  IN OLD_ACCOUNT_ID VARCHAR(32),
  IN OLD_SUBSCRIPTION_ID VARCHAR(32)
)
BEGIN
  UPDATE /*PREFIX*/ACCOUNT_SUBSCRIPTIONS ACS
     SET ACS.ACCOUNT_ID=ACCOUNT_ID,
		     ACS.SUBSCRIPTION_ID=SUBSCRIPTION_ID,
				 ACS.DATE_BEGIN=DATE_BEGIN,
				 ACS.DATE_END=DATE_END,
				 ACS.ACCESS_TYPE=ACCESS_TYPE
   WHERE ACS.ACCOUNT_ID=OLD_ACCOUNT_ID
	   AND ACS.SUBSCRIPTION_ID=OLD_SUBSCRIPTION_ID;
END;

--

/* Создание процедуры удаления доступа к подписке */

CREATE PROCEDURE /*PREFIX*/D_ACCOUNT_SUBSCRIPTION
(
  IN OLD_ACCOUNT_ID VARCHAR(32),
	IN OLD_SUBSCRIPTION_ID VARCHAR(32)
)
BEGIN
  DELETE FROM /*PREFIX*/ACCOUNT_SUBSCRIPTIONS 
        WHERE ACCOUNT_ID=OLD_ACCOUNT_ID
          AND SUBSCRIPTION_ID=OLD_SUBSCRIPTION_ID;
END;

--