/* Создание таблицы содержания подписки */

CREATE TABLE /*PREFIX*/SUBSCRIPTION_CONTENTS
(
  SUBSCRIPTION_ID VARCHAR(32) NOT NULL,
  VIEW_ID VARCHAR(32) NOT NULL,
  TYPE_ID VARCHAR(32) NOT NULL,
  OPERATION_ID VARCHAR(32) NOT NULL,
  PUBLISHING_ID VARCHAR(32) NOT NULL,
  PRIMARY KEY (SUBSCRIPTION_ID,VIEW_ID,TYPE_ID,OPERATION_ID,PUBLISHING_ID),
  FOREIGN KEY (SUBSCRIPTION_ID) REFERENCES /*PREFIX*/SUBSCRIPTIONS (SUBSCRIPTION_ID),
  FOREIGN KEY (VIEW_ID) REFERENCES /*PREFIX*/VIEWS (VIEW_ID),
  FOREIGN KEY (TYPE_ID) REFERENCES /*PREFIX*/TYPES (TYPE_ID),
  FOREIGN KEY (OPERATION_ID) REFERENCES /*PREFIX*/OPERATIONS (OPERATION_ID),
  FOREIGN KEY (PUBLISHING_ID) REFERENCES /*PREFIX*/PUBLISHING (PUBLISHING_ID)
)

--

/* Создание просмотра таблицы содержания подписки */

CREATE VIEW /*PREFIX*/S_SUBSCRIPTION_CONTENTS
AS
SELECT SC.*,
			 S.NAME AS SUBSCRIPTION_NAME,
			 V.NAME AS VIEW_NAME,
			 T.NAME AS TYPE_NAME,
			 O.NAME AS OPERATION_NAME,
			 PB.NAME AS PUBLISHING_NAME
  FROM /*PREFIX*/SUBSCRIPTION_CONTENTS SC
	JOIN /*PREFIX*/SUBSCRIPTIONS S ON S.SUBSCRIPTION_ID=SC.SUBSCRIPTION_ID
	JOIN /*PREFIX*/VIEWS V ON V.VIEW_ID=SC.VIEW_ID
	JOIN /*PREFIX*/TYPES T ON T.TYPE_ID=SC.TYPE_ID
	JOIN /*PREFIX*/OPERATIONS O ON O.OPERATION_ID=SC.OPERATION_ID
  JOIN /*PREFIX*/PUBLISHING PB ON PB.PUBLISHING_ID=SC.PUBLISHING_ID	
	
--

/* Создание процедуры добавления содержания подписки */

CREATE PROCEDURE /*PREFIX*/I_SUBSCRIPTION_CONTENT
(
  IN SUBSCRIPTION_ID VARCHAR(32),
  IN VIEW_ID VARCHAR(32),
  IN TYPE_ID VARCHAR(32),
  IN OPERATION_ID VARCHAR(32),
  IN PUBLISHING_ID VARCHAR(32)
)
BEGIN
  INSERT INTO /*PREFIX*/SUBSCRIPTION_CONTENTS (SUBSCRIPTION_ID,VIEW_ID,TYPE_ID,OPERATION_ID,PUBLISHING_ID)
       VALUES (SUBSCRIPTION_ID,VIEW_ID,TYPE_ID,OPERATION_ID,PUBLISHING_ID);
END;	

--

/* Создание процедуры изменения содержания подписки */

CREATE PROCEDURE /*PREFIX*/U_SUBSCRIPTION_CONTENT
(
  IN SUBSCRIPTION_ID VARCHAR(32),
  IN VIEW_ID VARCHAR(32),
  IN TYPE_ID VARCHAR(32),
  IN OPERATION_ID VARCHAR(32),
  IN PUBLISHING_ID VARCHAR(32),
  IN OLD_SUBSCRIPTION_ID VARCHAR(32),
  IN OLD_VIEW_ID VARCHAR(32),
  IN OLD_TYPE_ID VARCHAR(32),
  IN OLD_OPERATION_ID VARCHAR(32),
  IN OLD_PUBLISHING_ID VARCHAR(32)	
)
BEGIN
  UPDATE /*PREFIX*/SUBSCRIPTION_CONTENTS SC
     SET SC.SUBSCRIPTION_ID=SUBSCRIPTION_ID,
		     SC.VIEW_ID=VIEW_ID,
		     SC.TYPE_ID=TYPE_ID,
		     SC.OPERATION_ID=OPERATION_ID,
		     SC.PUBLISHING_ID=PUBLISHING_ID
   WHERE SC.SUBSCRIPTION_ID=OLD_SUBSCRIPTION_ID
	   AND SC.VIEW_ID=OLD_VIEW_ID
	   AND SC.TYPE_ID=OLD_TYPE_ID
	   AND SC.OPERATION_ID=OLD_OPERATION_ID
		 AND SC.PUBLISHING_ID=OLD_PUBLISHING_ID;
END;

--

/* Создание процедуры удаления содержания подписки */

CREATE PROCEDURE /*PREFIX*/D_SUBSCRIPTION_CONTENT
(
  IN OLD_SUBSCRIPTION_ID VARCHAR(32),
	IN OLD_VIEW_ID VARCHAR(32),
	IN OLD_TYPE_ID VARCHAR(32),
	IN OLD_OPERATION_ID VARCHAR(32),
	IN OLD_PUBLISHING_ID VARCHAR(32)
)
BEGIN
  DELETE FROM /*PREFIX*/SUBSCRIPTION_CONTENTS
        WHERE SUBSCRIPTION_ID=OLD_SUBSCRIPTION_ID
				  AND VIEW_ID=OLD_VIEW_ID
				  AND TYPE_ID=OLD_TYPE_ID
				  AND OPERATION_ID=OLD_OPERATION_ID
					AND PUBLISHING_ID=OLD_PUBLISHING_ID;
END;

--