/* Создание просмотра меню представлений */

CREATE VIEW S_MENU_PRESENTATIONS
AS
SELECT AP.*,
       A.USER_NAME,
       V.NAME AS VIEW_NAME,
       T.NAME AS TYPE_NAME,
       O.NAME AS OPERATION_NAME,
       P.NAME AS PRESENTATION_NAME,
       P.TABLE_NAME,
			 PB.NAME AS PUBLISHING_NAME 
  FROM ACCOUNT_PRESENTATIONS AP
	JOIN ACCOUNTS A ON A.ACCOUNT_ID=AP.ACCOUNT_ID
  JOIN VIEWS V ON V.VIEW_ID=AP.VIEW_ID
  JOIN TYPES T ON T.TYPE_ID=AP.TYPE_ID
  JOIN OPERATIONS O ON O.OPERATION_ID=AP.OPERATION_ID
  JOIN PRESENTATIONS P ON P.PRESENTATION_ID=AP.PRESENTATION_ID
  JOIN PUBLISHING PB ON PB.PUBLISHING_ID=AP.PUBLISHING_ID
  JOIN VIEW_TYPES VT ON VT.VIEW_ID=AP.VIEW_ID AND VT.TYPE_ID=AP.TYPE_ID
ORDER BY A.USER_NAME, PB.PRIORITY, V.PRIORITY, VT.PRIORITY, O.PRIORITY
	
--

