/* —оздание просмотра параметров представлений */

CREATE VIEW /*PREFIX*/S_PRESENTATION_PARAMS
AS
SELECT CP.*,
       C.NAME AS COLUMN_NAME,
       P.NAME AS PARAM_NAME,
       P.PARAM_TYPE,
       P.MAX_LENGTH,
       C.PRESENTATION_ID,
       C.NOT_EMPTY,
       C.USE_DEPEND
  FROM /*PREFIX*/COLUMN_PARAMS CP
  JOIN /*PREFIX*/COLUMNS C ON  C.COLUMN_ID=CP.COLUMN_ID
  JOIN /*PREFIX*/PARAMS P ON P.PARAM_ID=CP.PARAM_ID
 ORDER BY C.PRIORITY, CP.PRIORITY
	
--

