/* Создание таблицы интерфейсов доступных приложению */

CREATE TABLE /*PREFIX*/APPLICATION_INTERFACES
(
  APPLICATION_ID VARCHAR(32) NOT NULL,
  ACCOUNT_ID VARCHAR(32) NOT NULL,
  INTERFACE_ID VARCHAR(32) NOT NULL,
  PRIORITY INTEGER NOT NULL,
  AUTO_RUN INTEGER NOT NULL,
  PRIMARY KEY (APPLICATION_ID,ACCOUNT_ID,INTERFACE_ID),
  FOREIGN KEY (APPLICATION_ID) REFERENCES /*PREFIX*/APPLICATIONS (APPLICATION_ID),
  FOREIGN KEY (ACCOUNT_ID) REFERENCES /*PREFIX*/ACCOUNTS (ACCOUNT_ID),
  FOREIGN KEY (INTERFACE_ID) REFERENCES /*PREFIX*/INTERFACES (INTERFACE_ID)
)

--

/* Создание просмотра таблицы интерфейсов доступных приложению */

CREATE VIEW /*PREFIX*/S_APPLICATION_INTERFACES
(
  APPLICATION_ID,
  ACCOUNT_ID,
  INTERFACE_ID,
  PRIORITY,
  AUTO_RUN,
  APPLICATION_NAME,
  USER_NAME,
  INTERFACE_NAME
)
AS
SELECT AI.*,
       A.NAME AS APPLICATION_NAME,
       AC.USER_NAME,
       I.NAME AS INTERFACE_NAME
  FROM /*PREFIX*/APPLICATION_INTERFACES AI
  JOIN /*PREFIX*/APPLICATIONS A ON A.APPLICATION_ID=AI.APPLICATION_ID
  JOIN /*PREFIX*/ACCOUNTS AC ON AC.ACCOUNT_ID=AI.ACCOUNT_ID
  JOIN /*PREFIX*/INTERFACES I ON I.INTERFACE_ID=AI.INTERFACE_ID
			
--

/* Создание процедуры добавления приложению интерфейса */

CREATE PROCEDURE /*PREFIX*/I_APPLICATION_INTERFACE
(
  APPLICATION_ID VARCHAR(32),
  ACCOUNT_ID VARCHAR(32),
  INTERFACE_ID VARCHAR(32),
  PRIORITY INTEGER,
  AUTO_RUN INTEGER
)
AS
BEGIN
  INSERT INTO /*PREFIX*/APPLICATION_INTERFACES (APPLICATION_ID,ACCOUNT_ID,INTERFACE_ID,PRIORITY,AUTO_RUN)
       VALUES (:APPLICATION_ID,:ACCOUNT_ID,:INTERFACE_ID,:PRIORITY,:AUTO_RUN);
END;

--

/* Создание процедуры изменения интерфейса у приложения */

CREATE PROCEDURE /*PREFIX*/U_APPLICATION_INTERFACE
(
  APPLICATION_ID VARCHAR(32),
  ACCOUNT_ID VARCHAR(32),
  INTERFACE_ID VARCHAR(32),
  PRIORITY INTEGER,
  AUTO_RUN INTEGER,
  OLD_APPLICATION_ID VARCHAR(32),
  OLD_ACCOUNT_ID VARCHAR(32),
  OLD_INTERFACE_ID VARCHAR(32)
)
AS
BEGIN
  UPDATE /*PREFIX*/APPLICATION_INTERFACES
     SET APPLICATION_ID=:APPLICATION_ID,
         ACCOUNT_ID=:ACCOUNT_ID,
         INTERFACE_ID=:INTERFACE_ID,
         PRIORITY=:PRIORITY,
         AUTO_RUN=:AUTO_RUN
   WHERE APPLICATION_ID=:OLD_APPLICATION_ID
     AND ACCOUNT_ID=:OLD_ACCOUNT_ID
     AND INTERFACE_ID=:OLD_INTERFACE_ID;
END;

--

/* Создание процедуры удаления интерфейса у приложения */

CREATE PROCEDURE /*PREFIX*/D_APPLICATION_INTERFACE
(
  OLD_APPLICATION_ID VARCHAR(32),
  OLD_ACCOUNT_ID VARCHAR(32),
  OLD_INTERFACE_ID VARCHAR(32)
)
AS
BEGIN
  DELETE FROM /*PREFIX*/APPLICATION_INTERFACES 
        WHERE APPLICATION_ID=:OLD_APPLICATION_ID
          AND ACCOUNT_ID=:OLD_ACCOUNT_ID
          AND INTERFACE_ID=:OLD_INTERFACE_ID;
END;

--

/* Фиксация изменений */

COMMIT