/* Создание таблицы тиражей */

CREATE TABLE /*PREFIX*/TIRAGES
(
  TIRAGE_ID VARCHAR(32) NOT NULL,
  NUM VARCHAR(3) NOT NULL,
  EXECUTION_DATE TIMESTAMP NOT NULL,
  EXECUTION_PLACE VARCHAR(250) NOT NULL,
  TICKET_COST NUMERIC(15,2) NOT NULL,
  JACKPOT_PERCENT NUMERIC(4,2) NOT NULL,
  PRIZE_PERCENT NUMERIC(4,2) NOT NULL,
  PREPARATION_DATE TIMESTAMP,
  FIRST_ROUND_PERCENT NUMERIC(4,2) NOT NULL,
  THIRD_ROUND_SUM NUMERIC(15,2) NOT NULL,
  FOURTH_ROUND_SUM NUMERIC(15,2),
  PRIMARY KEY (TIRAGE_ID)
)

--

/* Создание просмотра таблицы тиражей */

CREATE VIEW /*PREFIX*/S_TIRAGES
(
  TIRAGE_ID,
  NUM,
  EXECUTION_DATE,
  EXECUTION_PLACE,
  TICKET_COST,
  JACKPOT_PERCENT,
  PRIZE_PERCENT,
  PREPARATION_DATE,
  FIRST_ROUND_PERCENT,
  THIRD_ROUND_SUM,
  FOURTH_ROUND_SUM
)
AS
  SELECT T.*
    FROM /*PREFIX*/TIRAGES T

--

/* Создание процедуры добавления тиража */

CREATE PROCEDURE /*PREFIX*/I_TIRAGE
(
  TIRAGE_ID VARCHAR(32),
  NUM VARCHAR(3),
  EXECUTION_DATE TIMESTAMP,
  EXECUTION_PLACE VARCHAR(250),
  TICKET_COST NUMERIC(15,2),
  JACKPOT_PERCENT NUMERIC(4,2),
  PRIZE_PERCENT NUMERIC(4,2),
  PREPARATION_DATE TIMESTAMP,
  FIRST_ROUND_PERCENT NUMERIC(4,2),
  THIRD_ROUND_SUM NUMERIC(15,2),
  FOURTH_ROUND_SUM NUMERIC(15,2)
)
AS
BEGIN
  INSERT INTO /*PREFIX*/TIRAGES (TIRAGE_ID,NUM,EXECUTION_DATE,EXECUTION_PLACE,TICKET_COST,JACKPOT_PERCENT,
                                 PRIZE_PERCENT,PREPARATION_DATE,FIRST_ROUND_PERCENT,THIRD_ROUND_SUM,FOURTH_ROUND_SUM)
       VALUES (:TIRAGE_ID,:NUM,:EXECUTION_DATE,:EXECUTION_PLACE,:TICKET_COST,:JACKPOT_PERCENT,
               :PRIZE_PERCENT,:PREPARATION_DATE,:FIRST_ROUND_PERCENT,:THIRD_ROUND_SUM,:FOURTH_ROUND_SUM);
END;

--

/* Создание процедуры изменения тиража */

CREATE PROCEDURE /*PREFIX*/U_TIRAGE
(
  TIRAGE_ID VARCHAR(32),
  NUM VARCHAR(3),
  EXECUTION_DATE TIMESTAMP,
  EXECUTION_PLACE VARCHAR(250),
  TICKET_COST NUMERIC(15,2),
  JACKPOT_PERCENT NUMERIC(4,2),
  PRIZE_PERCENT NUMERIC(4,2),
  PREPARATION_DATE TIMESTAMP,
  FIRST_ROUND_PERCENT NUMERIC(4,2),
  THIRD_ROUND_SUM NUMERIC(15,2),
  FOURTH_ROUND_SUM NUMERIC(15,2),
  OLD_TIRAGE_ID VARCHAR(32)
)
AS
BEGIN
  UPDATE /*PREFIX*/TIRAGES
     SET TIRAGE_ID=:TIRAGE_ID,
         NUM=:NUM,
         EXECUTION_DATE=:EXECUTION_DATE,
         EXECUTION_PLACE=:EXECUTION_PLACE,
         TICKET_COST=:TICKET_COST,
         JACKPOT_PERCENT=:JACKPOT_PERCENT,
         PRIZE_PERCENT=:PRIZE_PERCENT,
         PREPARATION_DATE=:PREPARATION_DATE,
         FIRST_ROUND_PERCENT=:FIRST_ROUND_PERCENT,
         THIRD_ROUND_SUM=:THIRD_ROUND_SUM,
         FOURTH_ROUND_SUM=:FOURTH_ROUND_SUM
   WHERE TIRAGE_ID=:OLD_TIRAGE_ID;
END;

--

/* Создание процедуры удаления тиража */

CREATE PROCEDURE /*PREFIX*/D_TIRAGE
(
  OLD_TIRAGE_ID VARCHAR(32)
)
AS
BEGIN
  DELETE FROM /*PREFIX*/TIRAGES
        WHERE TIRAGE_ID=:OLD_TIRAGE_ID;
END;

--

/* Фиксация изменений */

COMMIT