/* Создание таблицы членов тиражной комиссии */

CREATE TABLE /*PREFIX*/TIRAGE_MEMBERS
(
  TIRAGE_ID VARCHAR(32) NOT NULL,
  MEMBER_ID VARCHAR(32) NOT NULL,
  PRIORITY INTEGER,
  PRIMARY KEY (TIRAGE_ID,MEMBER_ID),
  FOREIGN KEY (TIRAGE_ID) REFERENCES /*PREFIX*/TIRAGES (TIRAGE_ID),
  FOREIGN KEY (MEMBER_ID) REFERENCES /*PREFIX*/MEMBERS (MEMBER_ID)
)

--

/* Создание просмотра таблицы членов тиражной комиссии */

CREATE VIEW /*PREFIX*/S_TIRAGE_MEMBERS
(
  TIRAGE_ID,
  MEMBER_ID,
  PRIORITY,
  TIRAGE_NUM,
  MEMBER_SURNAME,
  MEMBER_NAME,
  MEMBER_PATRONYMIC
)
AS
SELECT TM.*,
       T.NUM AS TIRAGE_NUM,
       M.SURNAME AS MEMBER_SURNAME,
       M.NAME AS MEMBER_NAME,
       M.PATRONYMIC AS MEMBER_PATRONYMIC
  FROM /*PREFIX*/TIRAGE_MEMBERS TM
  JOIN /*PREFIX*/TIRAGES T ON T.TIRAGE_ID=TM.TIRAGE_ID
  JOIN /*PREFIX*/MEMBERS M ON M.MEMBER_ID=TM.MEMBER_ID
			
--

/* Создание процедуры добавления члена тиражной комиссии */

CREATE PROCEDURE /*PREFIX*/I_TIRAGE_MEMBER
(
  TIRAGE_ID VARCHAR(32),
  MEMBER_ID VARCHAR(32),
  PRIORITY INTEGER
)
AS
BEGIN
  INSERT INTO /*PREFIX*/TIRAGE_MEMBERS (TIRAGE_ID,MEMBER_ID,PRIORITY)
       VALUES (:TIRAGE_ID,:MEMBER_ID,:PRIORITY);
END;

--

/* Создание процедуры изменения члена тиражной комиссии */

CREATE PROCEDURE /*PREFIX*/U_TIRAGE_MEMBER
(
  TIRAGE_ID VARCHAR(32),
  MEMBER_ID VARCHAR(32),
  PRIORITY INTEGER,
  OLD_TIRAGE_ID VARCHAR(32),
  OLD_MEMBER_ID VARCHAR(32)
)
AS
BEGIN
  UPDATE /*PREFIX*/TIRAGE_MEMBERS
     SET TIRAGE_ID=:TIRAGE_ID,
         MEMBER_ID=:MEMBER_ID,
         PRIORITY=:PRIORITY
   WHERE TIRAGE_ID=:OLD_TIRAGE_ID
     AND MEMBER_ID=:OLD_MEMBER_ID;
END;

--

/* Создание процедуры удаления члена тиражной комиссии */

CREATE PROCEDURE /*PREFIX*/D_TIRAGE_MEMBER
(
  OLD_TIRAGE_ID VARCHAR(32),
  OLD_MEMBER_ID VARCHAR(32)
)
AS
BEGIN
  DELETE FROM /*PREFIX*/TIRAGE_MEMBERS 
        WHERE TIRAGE_ID=:OLD_TIRAGE_ID
          AND MEMBER_ID=:OLD_MEMBER_ID;
END;

--

/* Фиксация изменений */

COMMIT