/* Изменение процедуры удаления тиража */

ALTER PROCEDURE /*PREFIX*/D_TIRAGE
(
  OLD_TIRAGE_ID VARCHAR(32)
)
AS
BEGIN
  DELETE FROM /*PREFIX*/LOTTERY
        WHERE TIRAGE_ID=:OLD_TIRAGE_ID;

  DELETE FROM /*PREFIX*/LOTTERY
        WHERE PRIZE_ID IN (SELECT PRIZE_ID
                             FROM /*PREFIX*/PRIZES
                            WHERE TIRAGE_ID=:OLD_TIRAGE_ID);

  DELETE FROM /*PREFIX*/PRIZES
        WHERE TIRAGE_ID=:OLD_TIRAGE_ID;

  DELETE FROM /*PREFIX*/TICKETS
        WHERE TIRAGE_ID=:OLD_TIRAGE_ID;

  DELETE FROM /*PREFIX*/TIRAGES
        WHERE TIRAGE_ID=:OLD_TIRAGE_ID;
END;

--

/* Фиксация изменений */

COMMIT