/* Создание процедуры изменения владельца билета */

CREATE PROCEDURE /*PREFIX*/CHANGE_TICKET_OWNER
(
  TICKET_ID VARCHAR(32),
  SURNAME VARCHAR(100),
  NAME VARCHAR(100),
  PATRONYMIC VARCHAR(100),
  ADDRESS VARCHAR(250),
  PHONE VARCHAR(100)
)
AS
BEGIN
  UPDATE /*PREFIX*/TICKETS
     SET SURNAME=:SURNAME,
         NAME=:NAME,
         PATRONYMIC=:PATRONYMIC,
         ADDRESS=:ADDRESS,
         PHONE=:PHONE
   WHERE TICKET_ID=:TICKET_ID;
END;

--

/* Фиксация изменений */

COMMIT