/* Создание процедуры получения статистики по розыгрышу */


CREATE OR ALTER PROCEDURE /*PREFIX*/GET_LOTTERY_STATISTICS
(
  TIRAGE_ID VARCHAR(32)
)
RETURNS
(
  ALL_COUNT INTEGER,
  USED_COUNT INTEGER,
  NOT_USED_COUNT INTEGER,
  PRIZE_SUM NUMERIC(15,2),
  JACKPOT_SUM NUMERIC(15,2),
  FIRST_ROUND_SUM NUMERIC(15,2),
  SECOND_ROUND_SUM NUMERIC(15,2),
  THIRD_ROUND_SUM NUMERIC(15,2),
  FOURTH_ROUND_SUM NUMERIC(15,2)
)
AS
  DECLARE TICKET_COST NUMERIC(15,2);
  DECLARE PRIZE_PERCENT NUMERIC(4,2);
  DECLARE JACKPOT_PERCENT NUMERIC(4,2);
  DECLARE FIRST_ROUND_PERCENT NUMERIC(4,2);
  DECLARE TEMP_SUM NUMERIC(15,2);
BEGIN

  SELECT TICKET_COST, PRIZE_PERCENT, JACKPOT_PERCENT,
         FIRST_ROUND_PERCENT, THIRD_ROUND_SUM, FOURTH_ROUND_SUM
    FROM /*PREFIX*/TIRAGES
   WHERE TIRAGE_ID=:TIRAGE_ID
    INTO :TICKET_COST, :PRIZE_PERCENT, :JACKPOT_PERCENT,
         :FIRST_ROUND_PERCENT, :THIRD_ROUND_SUM, :FOURTH_ROUND_SUM;

  SELECT COUNT(*)
    FROM /*PREFIX*/TICKETS
   WHERE TIRAGE_ID=:TIRAGE_ID
    INTO :ALL_COUNT;

  SELECT COUNT(*)
    FROM /*PREFIX*/TICKETS
   WHERE TIRAGE_ID=:TIRAGE_ID
     AND NOT_USED=1
    INTO :NOT_USED_COUNT;

  USED_COUNT=ALL_COUNT-NOT_USED_COUNT;

  PRIZE_SUM=(TICKET_COST*USED_COUNT)*PRIZE_PERCENT/100;
  JACKPOT_SUM=PRIZE_SUM*JACKPOT_PERCENT/100;

  IF (FOURTH_ROUND_SUM IS NULL) THEN
    FOURTH_ROUND_SUM=0.0;

  TEMP_SUM=PRIZE_SUM-FOURTH_ROUND_SUM;
  FIRST_ROUND_SUM=TEMP_SUM*FIRST_ROUND_PERCENT/100;
  SECOND_ROUND_SUM=TEMP_SUM-FIRST_ROUND_SUM-THIRD_ROUND_SUM;

END;

--

/* Фиксация изменений */

COMMIT