/* Создание процедуры получения количества линий билетов */

CREATE PROCEDURE /*PREFIX*/GET_TICKET_LINE_COUNT
(
  TIRAGE_ID VARCHAR(32),
  PRIZE_ID VARCHAR(32),
  ROUND_NUM INTEGER,
  ROUND_NUM_EX INTEGER
)
RETURNS
(
 TICKET_ID VARCHAR(32),
 LINE_COUNT INTEGER
)
AS
BEGIN

  FOR SELECT TICKET_ID, COUNT(*)
        FROM /*PREFIX*/GET_TICKET_LINES(:TIRAGE_ID,:PRIZE_ID,:ROUND_NUM,:ROUND_NUM_EX)
       GROUP BY TICKET_ID
        INTO :TICKET_ID, :LINE_COUNT DO BEGIN

    SUSPEND;

  END

END;

--

/* Фиксация изменений */

COMMIT