/* Создание процедуры получения билетов по серии */

CREATE PROCEDURE /*PREFIX*/GET_TICKET_SERIES
(
  TIRAGE_ID VARCHAR(32),
  PRIZE_ID VARCHAR(32),
  ROUND_NUM INTEGER
)
RETURNS
(
  TICKET_ID VARCHAR(32)
)
AS
  DECLARE SQL VARCHAR(2000);
  DECLARE S VARCHAR(250);
  DECLARE BARREL_NUM VARCHAR(2);
BEGIN

  SQL='SELECT TICKET_ID FROM /*PREFIX*/TICKETS '||
      ' WHERE TIRAGE_ID='''||TIRAGE_ID||''' AND NOT_USED=0 ';

  S='';

  IF (PRIZE_ID IS NOT NULL) THEN BEGIN
    FOR SELECT BARREL_NUM
          FROM /*PREFIX*/LOTTERY
         WHERE TIRAGE_ID=:TIRAGE_ID
           AND PRIZE_ID=:PRIZE_ID
           AND ROUND_NUM=:ROUND_NUM
         ORDER BY INPUT_DATE
          INTO :BARREL_NUM DO BEGIN
      IF (S='') THEN BEGIN
        S=BARREL_NUM;
      END ELSE BEGIN
        S=S||BARREL_NUM;
      END
    END
  END ELSE BEGIN
    FOR SELECT BARREL_NUM
          FROM /*PREFIX*/LOTTERY
         WHERE TIRAGE_ID=:TIRAGE_ID
           AND PRIZE_ID IS NULL
           AND ROUND_NUM=:ROUND_NUM
         ORDER BY INPUT_DATE
          INTO :BARREL_NUM DO BEGIN
      IF (S='') THEN BEGIN
        S=BARREL_NUM;
      END ELSE BEGIN
        S=S||BARREL_NUM;
      END
    END
  END

  IF (S<>'') THEN BEGIN

    SQL=SQL||'AND SERIES LIKE '''||S||'%'' ';

    FOR EXECUTE STATEMENT SQL
                     INTO :TICKET_ID DO BEGIN
      SUSPEND;

    END

  END

END;

--

/* Фиксация изменений */

COMMIT