/* Создание таблицы интерфейсных отчетов */

CREATE TABLE /*PREFIX*/REPORTS
(
  REPORT_ID VARCHAR(32) NOT NULL,
  REPORT_TYPE INTEGER NOT NULL,
  REPORT IMAGE NOT NULL,
  PLACE INTEGER NOT NULL,
  PRIMARY KEY (REPORT_ID),
  FOREIGN KEY (REPORT_ID) REFERENCES /*PREFIX*/INTERFACES (INTERFACE_ID)
)

--

/* Создание просмотра таблицы интерфейсных отчетов */

CREATE VIEW /*PREFIX*/S_REPORTS
AS
  SELECT R.*, 
         I.NAME AS INTERFACE_NAME
    FROM /*PREFIX*/REPORTS R
    JOIN /*PREFIX*/INTERFACES I ON I.INTERFACE_ID=R.REPORT_ID

--

/* Создание процедуры добавления интерфейсного отчета */

CREATE PROCEDURE /*PREFIX*/I_REPORT
  @REPORT_ID VARCHAR(32),
  @REPORT_TYPE INTEGER,
  @REPORT IMAGE,
  @PLACE INTEGER
AS
BEGIN
  INSERT INTO /*PREFIX*/REPORTS (REPORT_ID,REPORT_TYPE,REPORT,PLACE)
       VALUES (@REPORT_ID,@REPORT_TYPE,@REPORT,@PLACE);
END;

--

/* Создание процедуры изменения интерфейсного отчета */

CREATE PROCEDURE /*PREFIX*/U_REPORT
  @REPORT_ID VARCHAR(32),
  @REPORT_TYPE INTEGER,
  @REPORT IMAGE,
  @PLACE INTEGER,
  @OLD_REPORT_ID VARCHAR(32)
AS
BEGIN
  UPDATE /*PREFIX*/REPORTS
     SET REPORT_ID=@REPORT_ID,
         REPORT_TYPE=@REPORT_TYPE,
         REPORT=@REPORT,
         PLACE=@PLACE
   WHERE REPORT_ID=@OLD_REPORT_ID;
END;

--

/* Создание процедуры удаления интерфейсного отчета */

CREATE PROCEDURE /*PREFIX*/D_REPORT
  @OLD_REPORT_ID VARCHAR(32)
AS
BEGIN
  DELETE FROM /*PREFIX*/REPORTS
        WHERE REPORT_ID=@OLD_REPORT_ID;
END;

--