/* Создание таблицы журнала действий */

CREATE TABLE /*PREFIX*/JOURNAL_ACTIONS
(
  JOURNAL_ACTION_ID VARCHAR(32) NOT NULL,
  ACCOUNT_ID VARCHAR(32) NOT NULL,
  APPLICATION_ID VARCHAR(32) NOT NULL,
  ACTION_TYPE INTEGER NOT NULL,
  DATE_ACTION TIMESTAMP NOT NULL,
  MODULE VARCHAR(250),
  OBJECT VARCHAR(250),
  METHOD VARCHAR(250),
  PARAM VARCHAR(250),
  "VALUE" BLOB NOT NULL,
  PRIMARY KEY (JOURNAL_ACTION_ID),
  FOREIGN KEY (ACCOUNT_ID) REFERENCES /*PREFIX*/ACCOUNTS (ACCOUNT_ID),
  FOREIGN KEY (APPLICATION_ID) REFERENCES /*PREFIX*/APPLICATIONS (APPLICATION_ID)
)

--

/* Создание просмотра таблицы журнала действий */

CREATE VIEW /*PREFIX*/S_JOURNAL_ACTIONS
(
  JOURNAL_ACTION_ID,
  ACCOUNT_ID,
  APPLICATION_ID,
  ACTION_TYPE,
  DATE_ACTION,
  MODULE,
  OBJECT,
  METHOD,
  PARAM,
  "VALUE",
  USER_NAME,
  APPLICATION_NAME
)
AS
   SELECT JA.*, 
          A.USER_NAME AS USER_NAME,
          AP.NAME AS APPLICATION_NAME
     FROM /*PREFIX*/JOURNAL_ACTIONS JA
     JOIN /*PREFIX*/ACCOUNTS A ON A.ACCOUNT_ID=JA.ACCOUNT_ID
     JOIN /*PREFIX*/APPLICATIONS AP ON AP.APPLICATION_ID=JA.APPLICATION_ID

--

/* Создание процедуры добавления действия в журнал */

CREATE PROCEDURE /*PREFIX*/I_JOURNAL_ACTION
(
  JOURNAL_ACTION_ID VARCHAR(32),
  ACCOUNT_ID VARCHAR(32),
  APPLICATION_ID VARCHAR(32),
  ACTION_TYPE INTEGER,
  DATE_ACTION TIMESTAMP,
  MODULE VARCHAR(250),
  OBJECT VARCHAR(250),
  METHOD VARCHAR(250),
  PARAM VARCHAR(250),
  "VALUE" BLOB
)
AS
BEGIN
  INSERT INTO /*PREFIX*/JOURNAL_ACTIONS (JOURNAL_ACTION_ID,ACCOUNT_ID,APPLICATION_ID,ACTION_TYPE,
                                         DATE_ACTION,MODULE,OBJECT,METHOD,PARAM,"VALUE")
       VALUES (:JOURNAL_ACTION_ID,:ACCOUNT_ID,:APPLICATION_ID,:ACTION_TYPE,
               :DATE_ACTION,:MODULE,:OBJECT,:METHOD,:PARAM,:"VALUE");
END;

--

/* Создание процедуры изменения действия в журнале */

CREATE PROCEDURE /*PREFIX*/U_JOURNAL_ACTION
(
  JOURNAL_ACTION_ID VARCHAR(32),
  ACCOUNT_ID VARCHAR(32),
  APPLICATION_ID VARCHAR(32),
  ACTION_TYPE INTEGER,
  DATE_ACTION TIMESTAMP,
  MODULE VARCHAR(250),
  OBJECT VARCHAR(250),
  METHOD VARCHAR(250),
  PARAM VARCHAR(250),
  "VALUE" BLOB,
  OLD_JOURNAL_ACTION_ID VARCHAR(32)
)
AS
BEGIN
  UPDATE /*PREFIX*/JOURNAL_ACTIONS
     SET JOURNAL_ACTION_ID=:JOURNAL_ACTION_ID,
         ACCOUNT_ID=:ACCOUNT_ID,
         APPLICATION_ID=:APPLICATION_ID,
         ACTION_TYPE=:ACTION_TYPE,
         DATE_ACTION=:DATE_ACTION,
         MODULE=:MODULE,
         OBJECT=:OBJECT,
         METHOD=:METHOD,
         PARAM=:PARAM,
         "VALUE"=:"VALUE"
   WHERE JOURNAL_ACTION_ID=:OLD_JOURNAL_ACTION_ID;
END;

--

/* Создание процедуры удаления действия из журнала */

CREATE PROCEDURE /*PREFIX*/D_JOURNAL_ACTION
(
  OLD_JOURNAL_ACTION_ID VARCHAR(32)
)
AS
BEGIN
  DELETE FROM /*PREFIX*/JOURNAL_ACTIONS
        WHERE JOURNAL_ACTION_ID=:OLD_JOURNAL_ACTION_ID;
END;

--

/* Фиксация изменений */

COMMIT