/* Создание таблицы оповещений */

CREATE TABLE /*PREFIX*/ALARMS
(
  ALARM_ID VARCHAR(32) NOT NULL,
  RECIPIENT_ID VARCHAR(32),
  TYPE_ALARM INTEGER NOT NULL,
  DATE_BEGIN TIMESTAMP NOT NULL,
  DATE_END TIMESTAMP,
  CAPTION VARCHAR(100) NOT NULL,
  TEXT_ALARM VARCHAR(4000) NOT NULL,
  SENDER_ID VARCHAR(32) NOT NULL, 
  PRIMARY KEY (ALARM_ID),
  FOREIGN KEY (RECIPIENT_ID) REFERENCES /*PREFIX*/ACCOUNTS (ACCOUNT_ID)
)

--

/* Создание просмотра оповещений */

CREATE VIEW /*PREFIX*/S_ALARMS
(
    ALARM_ID,
    RECIPIENT_ID,
    TYPE_ALARM,
    DATE_BEGIN,
    DATE_END,
    CAPTION,
    TEXT_ALARM,
    SENDER_ID,
    SENDER_NAME,
    RECIPIENT_NAME)
AS
SELECT A.*,
       A1.USER_NAME AS SENDER_NAME,
       A2.USER_NAME AS RECIPIENT_NAME
  FROM /*PREFIX*/ALARMS A
  JOIN /*PREFIX*/ACCOUNTS A1 ON A1.ACCOUNT_ID=A.SENDER_ID
  LEFT JOIN /*PREFIX*/ACCOUNTS A2 ON A2.ACCOUNT_ID=A.RECIPIENT_ID

--

/* Создание процедуры добавления оповещения */

CREATE OR ALTER PROCEDURE /*PREFIX*/I_ALARM
(
  ALARM_ID VARCHAR(32),
  SENDER_ID VARCHAR(32),
  RECIPIENT_ID VARCHAR(32),
  TYPE_ALARM INTEGER,
  DATE_BEGIN TIMESTAMP,
  DATE_END TIMESTAMP,
  CAPTION VARCHAR(100),
  TEXT_ALARM VARCHAR(4000))
AS
BEGIN
  INSERT INTO /*PREFIX*/ALARMS (ALARM_ID,SENDER_ID,RECIPIENT_ID,TYPE_ALARM,
                                DATE_BEGIN,DATE_END,CAPTION,TEXT_ALARM)
       VALUES (:ALARM_ID,:SENDER_ID,:RECIPIENT_ID,:TYPE_ALARM,
               :DATE_BEGIN,:DATE_END,:CAPTION,:TEXT_ALARM);
END;

--

/* Создание процедуры изменения оповещения */

CREATE OR ALTER PROCEDURE /*PREFIX*/U_ALARM
(
  ALARM_ID VARCHAR(32),
  SENDER_ID VARCHAR(32),
  RECIPIENT_ID VARCHAR(32),
  TYPE_ALARM INTEGER,
  DATE_BEGIN TIMESTAMP,
  DATE_END TIMESTAMP,
  CAPTION VARCHAR(100),
  TEXT_ALARM VARCHAR(4000),
  OLD_ALARM_ID VARCHAR(32))
AS
BEGIN
  UPDATE /*PREFIX*/ALARMS
     SET ALARM_ID=:ALARM_ID,
         SENDER_ID=:SENDER_ID,
         RECIPIENT_ID=:RECIPIENT_ID,
         TYPE_ALARM=:TYPE_ALARM,
         DATE_BEGIN=:DATE_BEGIN,
         DATE_END=:DATE_END,
         CAPTION=:CAPTION,
         TEXT_ALARM=:TEXT_ALARM
   WHERE ALARM_ID=:OLD_ALARM_ID;
END;

--

/* Создание процедуры удаления оповещения */

CREATE PROCEDURE /*PREFIX*/D_ALARM
(
  OLD_ALARM_ID VARCHAR(32)
)
AS
BEGIN
  DELETE FROM /*PREFIX*/ALARMS 
        WHERE ALARM_ID=:OLD_ALARM_ID;
END;

--

/* Фиксация изменений */

COMMIT