consts

9CA9F2761D2BBE974791906824C3C31A
A468782967A1A4D347F85F33D39E348A
56140344A440BE774C9007D49CD574E9
16835607B30CA79F4CE883B53AFE972D
634880F305E9AA434245E3E596697001
16835607B30CA79F4CE883B53AFE972D

--

CREATE OR ALTER PROCEDURE GET_ORDER_DETAILS 
(
  ORDER_NUM VARCHAR(10),
  DATE_BEGIN TIMESTAMP,
  DATE_END TIMESTAMP) 
RETURNS (
  ORDER_NUM_R VARCHAR(10),
  WHO_HISTORY VARCHAR(100),
  WHO_PROCESS VARCHAR(100),
  ACTION_NAME VARCHAR(100),
  RESULT_NAME VARCHAR(100),
  DATE_BEGIN_R TIMESTAMP,
  DATE_END_R TIMESTAMP,
  DESCRIPTION VARCHAR(250),
  DATE_HISTORY TIMESTAMP,
  RAZN DOUBLE PRECISION)
AS
  declare variable D1 Date;
  declare variable D2 Date;
begin
  D1=CAST(DATE_BEGIN AS DATE);
  IF (D1 IS NULL) THEN BEGIN
    SELECT MIN((CASE
              WHEN DATE_BEGIN IS NOT NULL THEN DATE_BEGIN
              ELSE DATE_HISTORY END))
      FROM ORDERS
      INTO :D1;
  END


 D2=CAST(DATE_END AS DATE);
  IF (D2 IS NULL) THEN BEGIN
    SELECT MAX((CASE
              WHEN DATE_BEGIN IS NOT NULL THEN DATE_BEGIN
              ELSE DATE_HISTORY END))
      FROM ORDERS
      INTO :D2;
  END        
   
IF(:ORDER_NUM IS NULL) THEN BEGIN       
FOR SELECT
      O.ORDER_NUM,
      (SELECT AC.USER_NAME 
      FROM ACCOUNTS AC
      WHERE AC.ACCOUNT_ID = O.WHO_HISTORY_ID) AS WHO_HISTORY,  
       O.DATE_HISTORY,
       (SELECT AC.USER_NAME 
       FROM ACCOUNTS AC
       WHERE AC.ACCOUNT_ID = O.WHO_PROCESS_ID) AS WHO_PROCESS,
       A.NAME AS ACTION_NAME,
       R.NAME AS RESULT_NAME,
       O.DATE_BEGIN,
       O.DATE_END,
       (O.DATE_END -  O.DATE_BEGIN) AS RAZN,
       O.DESCRIPTION  
FROM ORDERS O
LEFT JOIN RESULTS R ON O.RESULT_ID = R.RESULT_ID 
LEFT JOIN ACTIONS A ON O.ACTION_ID = A.ACTION_ID
        WHERE CAST((CASE
              WHEN O.DATE_BEGIN IS NOT NULL THEN O.DATE_BEGIN
              ELSE O.DATE_HISTORY END) AS DATE) >= :D1 
              AND  
              CAST((CASE
              WHEN O.DATE_BEGIN IS NOT NULL THEN O.DATE_BEGIN
              ELSE O.DATE_HISTORY END) AS DATE) <= :D2
         
        ORDER BY O.ORDER_NUM, (CASE
        WHEN O.DATE_BEGIN IS NOT NULL THEN O.DATE_BEGIN
        ELSE O.DATE_HISTORY END)                 
            INTO 
            :ORDER_NUM_R,
            :WHO_HISTORY,
            :DATE_HISTORY,
            :WHO_PROCESS,
            :ACTION_NAME,
            :RESULT_NAME,
            :DATE_BEGIN_R,
            :DATE_END_R,
            :RAZN,
            :DESCRIPTION          
          DO BEGIN       
    SUSPEND;
    END END ELSE BEGIN
    
    FOR SELECT
      O.ORDER_NUM,
      (SELECT AC.USER_NAME 
      FROM ACCOUNTS AC
      WHERE AC.ACCOUNT_ID = O.WHO_HISTORY_ID) AS WHO_HISTORY,  
       O.DATE_HISTORY,
       (SELECT AC.USER_NAME 
       FROM ACCOUNTS AC
       WHERE AC.ACCOUNT_ID = O.WHO_PROCESS_ID) AS WHO_PROCESS,
       A.NAME AS ACTION_NAME,
       R.NAME AS RESULT_NAME,
       O.DATE_BEGIN,
       O.DATE_END,
       (O.DATE_END -  O.DATE_BEGIN) AS RAZN,
       O.DESCRIPTION  
FROM ORDERS O
LEFT JOIN RESULTS R ON O.RESULT_ID = R.RESULT_ID 
LEFT JOIN ACTIONS A ON O.ACTION_ID = A.ACTION_ID
        WHERE CAST((CASE
              WHEN O.DATE_BEGIN IS NOT NULL THEN O.DATE_BEGIN
              ELSE O.DATE_HISTORY END) AS DATE) >= :D1 
              AND  
              CAST((CASE
              WHEN O.DATE_BEGIN IS NOT NULL THEN O.DATE_BEGIN
              ELSE O.DATE_HISTORY END) AS DATE) <= :D2
              AND O.ORDER_NUM = :ORDER_NUM
        
        ORDER BY O.ORDER_NUM, (CASE
        WHEN O.DATE_BEGIN IS NOT NULL THEN O.DATE_BEGIN
        ELSE O.DATE_HISTORY END)                 
            INTO 
            :ORDER_NUM_R,
            :WHO_HISTORY,
            :DATE_HISTORY,
            :WHO_PROCESS,
            :ACTION_NAME,
            :RESULT_NAME,
            :DATE_BEGIN_R,
            :DATE_END_R,
            :RAZN,
            :DESCRIPTION          
          DO BEGIN       
    SUSPEND;  
     
    END 
    END
end

--

DROP VIEW S_CLIENT_PHONES

--

CREATE VIEW S_CLIENT_PHONES
(
    CLIENT_ID,
    PHONE,
    METHOD_ID,
    DESCRIPTION,
    LOCALITY_ID,
    STREET_ID,
    HOUSE,
    FLAT,
    PORCH,
    ADDRESS_DESC,
    CLIENT_PHONE,
    USER_NAME,
    SURNAME,
    NAME,
    PATRONYMIC,
    LOCKED,
    FIRM_SMALL_NAME,
    METHOD_NAME,
    STREET_NAME,
    STREET_PREFIX,
    LOCALITY_NAME,
    LOCALITY_PREFIX
)
AS
SELECT CP.*,
       S1.LOCALITY_ID,
       C.STREET_ID,
       C.HOUSE,
       C.FLAT,
       C.PORCH,
       C.ADDRESS_DESC,
       A.PHONE AS CLIENT_PHONE,
       A.USER_NAME,
       A.SURNAME,
       A.NAME,
       A.PATRONYMIC,
       A.LOCKED,
       F.SMALL_NAME AS FIRM_SMALL_NAME,
       M.NAME AS METHOD_NAME,
       S1.NAME AS STREET_NAME,
       S1.PREFIX AS STREET_PREFIX,
       L1.NAME AS LOCALITY_NAME,
       L1.PREFIX AS LOCALITY_PREFIX
  FROM CLIENT_PHONES CP
  JOIN CLIENTS C ON C.CLIENT_ID=CP.CLIENT_ID
  JOIN ACCOUNTS A ON A.ACCOUNT_ID=C.CLIENT_ID
  LEFT JOIN FIRMS F ON F.FIRM_ID=A.FIRM_ID
  LEFT JOIN METHODS M ON M.METHOD_ID=CP.METHOD_ID
  LEFT JOIN STREETS S1 ON S1.STREET_ID=C.STREET_ID
  LEFT JOIN LOCALITIES L1 ON L1.LOCALITY_ID=S1.LOCALITY_ID

--

CREATE OR ALTER PROCEDURE GET_CLIENT_PHONES
(
  CLIENT_ID VARCHAR(32)
)
RETURNS
(
  PHONE VARCHAR(100)
)
AS
BEGIN

  SELECT A.PHONE
    FROM CLIENTS C
    JOIN ACCOUNTS A ON A.ACCOUNT_ID=C.CLIENT_ID
   WHERE C.CLIENT_ID=:CLIENT_ID
    INTO :PHONE;

  SUSPEND;

  FOR SELECT PHONE
        FROM CLIENT_PHONES
       WHERE CLIENT_ID=:CLIENT_ID
       ORDER BY PHONE
        INTO :PHONE DO BEGIN
    SUSPEND;
  END

END

--

CREATE OR ALTER PROCEDURE PR_NO_PARK (
  ORDER_ID VARCHAR(32),
  ACCOUNT_ID VARCHAR(32))
AS
DECLARE ZONE_ID VARCHAR(32);
DECLARE PARK_ID VARCHAR(32);
DECLARE DRIVER_ID VARCHAR(32);
DECLARE CNT INTEGER;
DECLARE RESULT_PARK_ID VARCHAR(32);
BEGIN

  SELECT ZONE_ID, DRIVER_ID
    FROM /*PREFIX*/ORDERS
   WHERE ORDER_ID=:ORDER_ID
     INTO :ZONE_ID, :DRIVER_ID;

  IF (DRIVER_ID IS NULL) THEN BEGIN

    IF (ZONE_ID IS NOT NULL) THEN BEGIN

        RESULT_PARK_ID=NULL;

        FOR SELECT P.PARK_ID
              FROM /*PREFIX*/ZONE_PARKS ZP
              JOIN /*PREFIX*/PARKS P ON P.PARK_ID=ZP.PARK_ID
             WHERE ZP.ZONE_ID=:ZONE_ID
             ORDER BY ZP.DISTANCE, ZP.PERIOD
              INTO :PARK_ID DO BEGIN

          FOR SELECT DRIVER_ID
                FROM PARK_STATES
               WHERE PARK_ID=:PARK_ID
                 AND DATE_OUT IS NULL
                INTO :DRIVER_ID DO BEGIN

            SELECT COUNT(*)
              FROM ORDERS
             WHERE DRIVER_ID=:DRIVER_ID
               AND PARENT_ID IS NULL
               AND DATE_HISTORY IS NULL
               AND FINISHED<>1
              INTO :CNT;

            IF (CNT=0) THEN BEGIN
              RESULT_PARK_ID=PARK_ID;
              BREAK;
            END

          END

          IF (RESULT_PARK_ID IS NOT NULL) THEN
            BREAK;

        END

        IF (RESULT_PARK_ID IS NOT NULL) THEN BEGIN

          UPDATE /*PREFIX*/ORDERS
             SET PARK_ID=:RESULT_PARK_ID,
                 DATE_END=CURRENT_TIMESTAMP,
                 WHO_PROCESS_ID=:ACCOUNT_ID
           WHERE ORDER_ID=:ORDER_ID;

        END ELSE BEGIN

          EXECUTE PROCEDURE PR_MANUAL(ORDER_ID,ACCOUNT_ID);

        END

    END ELSE BEGIN

      EXECUTE PROCEDURE PR_MANUAL(ORDER_ID,ACCOUNT_ID);

    END

  END

END

--

CREATE OR ALTER PROCEDURE PR_NO_DRIVER (
  ORDER_ID VARCHAR(32),
  ACCOUNT_ID VARCHAR(32))
AS
DECLARE ZONE_ID VARCHAR(32);
DECLARE PARK_ID VARCHAR(32);
DECLARE DRIVER_ID VARCHAR(32);
DECLARE RESULT_DRIVER_ID VARCHAR(32);
DECLARE RESULT_PARK_ID VARCHAR(32);
DECLARE CAR_ID VARCHAR(32);
DECLARE CNT INTEGER;
BEGIN

  SELECT ZONE_ID, PARK_ID, DRIVER_ID
    FROM ORDERS
   WHERE ORDER_ID=:ORDER_ID
    INTO :ZONE_ID, :PARK_ID, :DRIVER_ID;

  IF (DRIVER_ID IS NULL) THEN BEGIN

    IF (ZONE_ID IS NOT NULL) THEN BEGIN

      RESULT_PARK_ID=NULL;
      RESULT_DRIVER_ID=NULL;

      IF (PARK_ID IS NULL) THEN BEGIN

        FOR SELECT P.PARK_ID
              FROM ZONE_PARKS ZP
              JOIN PARKS P ON P.PARK_ID=ZP.PARK_ID
             WHERE ZP.ZONE_ID=:ZONE_ID
             ORDER BY ZP.DISTANCE, ZP.PERIOD
              INTO :PARK_ID DO BEGIN

          FOR SELECT PS.DRIVER_ID
                FROM PARK_STATES PS
                JOIN DRIVERS D ON D.DRIVER_ID=PS.DRIVER_ID
               WHERE PS.PARK_ID=:PARK_ID
                 AND PS.DATE_OUT IS NULL
               ORDER BY D.PRIORITY, PS.DATE_IN
                INTO :DRIVER_ID DO BEGIN

            SELECT COUNT(*)
              FROM ORDERS
             WHERE DRIVER_ID=:DRIVER_ID
               AND PARENT_ID IS NULL
               AND DATE_HISTORY IS NULL
               AND FINISHED<>1
              INTO :CNT;

            IF (CNT=0) THEN BEGIN
              RESULT_DRIVER_ID=DRIVER_ID;
              BREAK;
            END

          END

          IF (RESULT_DRIVER_ID IS NOT NULL) THEN BEGIN
            RESULT_PARK_ID=PARK_ID;
            BREAK;
          END

        END

      END ELSE BEGIN

        FOR SELECT PS.DRIVER_ID
              FROM PARK_STATES PS
              JOIN DRIVERS D ON D.DRIVER_ID=PS.DRIVER_ID
             WHERE PS.PARK_ID=:PARK_ID
               AND PS.DATE_OUT IS NULL
             ORDER BY D.PRIORITY, PS.DATE_IN
              INTO :DRIVER_ID DO BEGIN

          SELECT COUNT(*)
            FROM ORDERS
           WHERE DRIVER_ID=:DRIVER_ID
             AND PARENT_ID IS NULL
             AND DATE_HISTORY IS NULL
             AND FINISHED<>1
            INTO :CNT;

          IF (CNT=0) THEN BEGIN
            RESULT_DRIVER_ID=DRIVER_ID;
            RESULT_PARK_ID=PARK_ID;
            BREAK;
          END

        END

      END

      IF (RESULT_DRIVER_ID IS NOT NULL) THEN BEGIN

        SELECT CAR_ID
          FROM DRIVERS
         WHERE DRIVER_ID=:RESULT_DRIVER_ID
          INTO :CAR_ID;

        UPDATE ORDERS
           SET PARK_ID=:RESULT_PARK_ID,
               DRIVER_ID=:RESULT_DRIVER_ID,
               CAR_ID=:CAR_ID,
               DATE_END=CURRENT_TIMESTAMP,
               WHO_PROCESS_ID=:ACCOUNT_ID
         WHERE ORDER_ID=:ORDER_ID;

      END ELSE BEGIN

        EXECUTE PROCEDURE PR_MANUAL(ORDER_ID,ACCOUNT_ID);

      END

    END ELSE BEGIN

      EXECUTE PROCEDURE PR_MANUAL(ORDER_ID,ACCOUNT_ID);

    END

  END

END

--

/* Создание таблицы дочерних клиентов */

CREATE TABLE /*PREFIX*/CLIENT_CHILDS
(
  CLIENT_ID VARCHAR(32) NOT NULL,
  CHILD_ID VARCHAR(32) NOT NULL,
  PRIMARY KEY (CLIENT_ID,CHILD_ID),
  FOREIGN KEY (CLIENT_ID) REFERENCES /*PREFIX*/CLIENTS (CLIENT_ID),
  FOREIGN KEY (CHILD_ID) REFERENCES /*PREFIX*/CLIENTS (CLIENT_ID)
)

--

/* Создание просмотра дочерних клиентов */

CREATE VIEW /*PREFIX*/S_CLIENT_CHILDS
(
  CLIENT_ID,
  CHILD_ID,
  CLIENT_USER_NAME,
  CHILD_USER_NAME,
  CHILD_SURNAME,
  CHILD_NAME,
  CHILD_PATRONYMIC
)
AS
SELECT CC.*,
       A1.USER_NAME AS CLIENT_USER_NAME,
       A2.USER_NAME AS CHILD_USER_NAME,
       A2.SURNAME AS CHILD_SURNAME,
       A2.NAME AS CHILD_USER_NAME,
       A2.PATRONYMIC AS CHILD_PATRONYMIC
  FROM /*PREFIX*/CLIENT_CHILDS CC
  JOIN /*PREFIX*/CLIENTS C1 ON C1.CLIENT_ID=CC.CLIENT_ID
  JOIN /*PREFIX*/ACCOUNTS A1 ON A1.ACCOUNT_ID=CC.CLIENT_ID
  JOIN /*PREFIX*/CLIENTS C2 ON C2.CLIENT_ID=CC.CHILD_ID
  JOIN /*PREFIX*/ACCOUNTS A2 ON A2.ACCOUNT_ID=CC.CHILD_ID

--

/* Создание процедуры добавления дочернего клиента */

CREATE PROCEDURE /*PREFIX*/I_CLIENT_CHILD
(
  CLIENT_ID VARCHAR(32),
  CHILD_ID VARCHAR(32)
)
AS
BEGIN
  INSERT INTO /*PREFIX*/CLIENT_CHILDS (CLIENT_ID,CHILD_ID)
       VALUES (:CLIENT_ID,:CHILD_ID);
END;

--

/* Создание процедуры изменения дочернего у клиента */

CREATE PROCEDURE /*PREFIX*/U_CLIENT_CHILD
(
  CLIENT_ID VARCHAR(32),
  CHILD_ID VARCHAR(32),
  OLD_CLIENT_ID VARCHAR(32),
  OLD_CHILD_ID VARCHAR(32)
)
AS
BEGIN
  UPDATE /*PREFIX*/CLIENT_CHILDS
     SET CLIENT_ID=:CLIENT_ID,
         CHILD_ID=:CHILD_ID
   WHERE CLIENT_ID=:OLD_CLIENT_ID
     AND CHILD_ID=:OLD_CHILD_ID;
END;

--

/* Создание процедуры удаления дочернего у клиента */

CREATE PROCEDURE /*PREFIX*/D_CLIENT_CHILD
(
  OLD_CLIENT_ID VARCHAR(32),
  OLD_CHILD_ID VARCHAR(32)
)
AS
BEGIN
  DELETE FROM /*PREFIX*/CLIENT_CHILDS 
        WHERE CLIENT_ID=:OLD_CLIENT_ID
          AND CHILD_ID=:OLD_CHILD_ID;
END;

--

CREATE OR ALTER PROCEDURE PR_ARRIVAL_DRIVER (
  ORDER_ID VARCHAR(32),
  ACCOUNT_ID VARCHAR(32))
AS
DECLARE PHONE VARCHAR(100);
DECLARE DRIVER_ID VARCHAR(32);
DECLARE COST_RATE NUMERIC(15,2);
DECLARE COLOR VARCHAR(100);
DECLARE BRAND VARCHAR(100);
DECLARE STATE_NUM VARCHAR(50);
DECLARE PREFIX VARCHAR(10);
DECLARE STREET VARCHAR(100);
DECLARE HOUSE VARCHAR(10);
DECLARE FLAT VARCHAR(10);
DECLARE PORCH VARCHAR(10);
DECLARE LOCALITY VARCHAR(100);
DECLARE RECIPIENT_ID VARCHAR(32);
DECLARE S VARCHAR(1000);
DECLARE S1 VARCHAR(1000);
DECLARE ADDRESS VARCHAR(1000);
DECLARE NUM INTEGER;
DECLARE CNT INTEGER;
DECLARE FLAG INTEGER;
DECLARE D TIMESTAMP;
BEGIN

  SELECT O.PHONE, O.DRIVER_ID, O.COST_RATE,
         C.COLOR, C.BRAND, C.STATE_NUM
    FROM ORDERS O
    LEFT JOIN DRIVERS D ON D.DRIVER_ID=O.DRIVER_ID
    LEFT JOIN CARS C ON C.CAR_ID=D.CAR_ID
   WHERE ORDER_ID=:ORDER_ID
    INTO :PHONE, :DRIVER_ID, :COST_RATE,
         :COLOR, :BRAND, :STATE_NUM;

  UPDATE ORDERS
     SET DATE_BEGIN=CURRENT_TIMESTAMP
   WHERE ORDER_ID=:ORDER_ID;

  IF (DRIVER_ID IS NOT NULL) THEN BEGIN

    IF (PHONE IS NOT NULL) THEN BEGIN

      IF (SUBSTR(PHONE,1,3)='+79')  THEN BEGIN

        RECIPIENT_ID=NULL;

        FOR SELECT ACCOUNT_ID
              FROM ACCOUNTS
             WHERE PHONE=:PHONE
              INTO :RECIPIENT_ID DO BEGIN

          IF (RECIPIENT_ID IS NOT NULL) THEN
            BREAK;
        END

        FLAG=0;

        FOR SELECT STREET_ID, HOUSE
              FROM ROUTES
             WHERE ORDER_ID=:ORDER_ID
             ORDER BY PRIORITY
              INTO :STREET, :HOUSE DO BEGIN

          IF ((STREET IS NOT NULL) AND (HOUSE IS NOT NULL)) THEN BEGIN

          END ELSE BEGIN

            FLAG=1;

          END
        END

        IF ((COST_RATE>0.0) AND (FLAG=0)) THEN BEGIN

          SELECT CONST_VALUE FROM GET_CONST_VALUE('8D9E6C9F4852AD8142205F027B2A5288') INTO :S;

        END ELSE BEGIN

          SELECT CONST_VALUE FROM GET_CONST_VALUE('93EBB0171E37A0884313759C0DA1EB3D') INTO :S;

        END

        IF (S IS NOT NULL) THEN BEGIN

          S=REPLACE_STRING(S,'%COLOR',COLOR);
          S=REPLACE_STRING(S,'%BRAND',BRAND);
          S=REPLACE_STRING(S,'%STATE_NUM',STATE_NUM);
          S=REPLACE_STRING(S,'%COST_RATE',CAST(CAST(COST_RATE AS NUMERIC(15,0)) AS VARCHAR(30)));

          INSERT INTO OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                    TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,PRIORITY,LOCKED,DATE_BEGIN)
                            VALUES (GET_UNIQUE_ID(),:ACCOUNT_ID,:RECIPIENT_ID,CURRENT_TIMESTAMP,
                                    :S,NULL,0,:PHONE,NULL,0,NULL,CURRENT_TIMESTAMP);

        END

        SELECT CONST_VALUE FROM GET_CONST_VALUE('F4384929079999BB47A895BFCA5BB382') INTO :S;

        IF (S IS NOT NULL) THEN BEGIN

          INSERT INTO OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                    TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,PRIORITY,LOCKED,DATE_BEGIN)
                            VALUES (GET_UNIQUE_ID(),:ACCOUNT_ID,:RECIPIENT_ID,CURRENT_TIMESTAMP,
                                    :S,NULL,0,:PHONE,NULL,0,NULL,CURRENT_TIMESTAMP);

        END

      END

    END

    SELECT PHONE
      FROM ACCOUNTS
     WHERE ACCOUNT_ID=:DRIVER_ID
      INTO :PHONE;

    FLAG=0;
    NUM=0;

    SELECT COUNT(*)
      FROM ROUTES
     WHERE ORDER_ID=:ORDER_ID
      INTO :CNT;

    D=CURRENT_TIMESTAMP;

    FOR SELECT S.PREFIX, S.NAME, R.HOUSE, R.FLAT, R.PORCH, L.NAME
          FROM ROUTES R
          LEFT JOIN STREETS S ON S.STREET_ID=R.STREET_ID
          LEFT JOIN LOCALITIES L ON L.LOCALITY_ID=S.LOCALITY_ID
         WHERE R.ORDER_ID=:ORDER_ID
         ORDER BY R.PRIORITY
          INTO :PREFIX, :STREET, :HOUSE, :FLAT, :PORCH, :LOCALITY DO BEGIN

      ADDRESS='';
      S=NULL;

      IF ((STREET IS NOT NULL) AND (HOUSE IS NOT NULL)) THEN BEGIN

        IF (PREFIX IS NOT NULL) THEN
          ADDRESS=PREFIX||' ';

        IF (STREET IS NOT NULL) THEN
          ADDRESS=ADDRESS||STREET;

        IF (HOUSE IS NOT NULL) THEN
          ADDRESS=ADDRESS||' '||HOUSE;

        IF (FLAT IS NOT NULL) THEN
          ADDRESS=ADDRESS||'-'||FLAT;

        IF (PORCH IS NOT NULL) THEN
          ADDRESS=ADDRESS||' п.'||PORCH;

        IF ((LOCALITY IS NOT NULL) AND (LOCALITY<>'Красноярск')) THEN
          ADDRESS=ADDRESS||', '||LOCALITY;

        SELECT CONST_VALUE FROM GET_CONST_VALUE('92009DB6C3EAA9E74B80D333538FE40D') INTO :S;

      END ELSE BEGIN

        FLAG=1;

        SELECT CONST_VALUE FROM GET_CONST_VALUE('7ED5E8A8BBD9870A411517B54D9EB973') INTO :S;

      END

      IF (S IS NOT NULL) THEN BEGIN

        NUM=NUM+1;

        S=REPLACE_STRING(S,'%NUM',NUM);
        S=REPLACE_STRING(S,'%COUNT',CNT);
        S=REPLACE_STRING(S,'%ADDRESS',ADDRESS);

        IF (NUM=CNT) THEN BEGIN

          IF ((FLAG=0) AND (COST_RATE>0.0)) THEN

            SELECT CONST_VALUE FROM GET_CONST_VALUE('9C8BC7D14DAEAE5C4DC8C1C91B20BCC2') INTO :S1;

          ELSE

            SELECT CONST_VALUE FROM GET_CONST_VALUE('D3F68032AD999D004140A480A8AAF749') INTO :S1;

        END ELSE

          S1=S;


        IF (S1 IS NOT NULL) THEN BEGIN

          S1=REPLACE_STRING(S1,'%ADDRESS',S);
          S1=REPLACE_STRING(S1,'%COST_RATE',CAST(CAST(COST_RATE AS NUMERIC(15,0)) AS VARCHAR(30)));

          RECIPIENT_ID=DRIVER_ID;

          INSERT INTO OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                    TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,PRIORITY,LOCKED,DATE_BEGIN)
                            VALUES (GET_UNIQUE_ID(),:ACCOUNT_ID,:RECIPIENT_ID,CURRENT_TIMESTAMP,
                                    :S1,NULL,0,:PHONE,NULL,2,NULL,:D);

          D=D+1*(1e0/24/60/60);

        END

      END

    END

  END

END

--

CREATE OR ALTER PROCEDURE PR_SELECT_DRIVER (
  ORDER_ID VARCHAR(32),
  ACCOUNT_ID VARCHAR(32))
AS
DECLARE DRIVER_ID VARCHAR(32);
DECLARE CAR_ID VARCHAR(32);
DECLARE CNT INTEGER;
DECLARE S VARCHAR(1000);
DECLARE ADDRESS VARCHAR(1000);
DECLARE PREFIX VARCHAR(10);
DECLARE STREET VARCHAR(100);
DECLARE HOUSE VARCHAR(10);
DECLARE FLAT VARCHAR(10);
DECLARE PORCH VARCHAR(10);
DECLARE LOCALITY VARCHAR(100);
DECLARE PHONE VARCHAR(100);
DECLARE DATE_ACCEPT TIMESTAMP;
DECLARE DATE_ARRIVAL TIMESTAMP;
DECLARE DATE_BEGIN TIMESTAMP;
DECLARE BEFORE_PERIOD INTEGER;
DECLARE ACTION_ID VARCHAR(32);
DECLARE D TIMESTAMP;
DECLARE DESCRIPTION VARCHAR(250);
BEGIN

  SELECT O.DRIVER_ID,
         S.PREFIX, S.NAME, O.HOUSE, O.FLAT, O.PORCH, L.NAME,
         O.DATE_ACCEPT, O.DATE_ARRIVAL, O.BEFORE_PERIOD,
         O.ACTION_ID, O.DATE_BEGIN, O.DESCRIPTION
    FROM ORDERS O
    JOIN STREETS S ON S.STREET_ID=O.STREET_ID
    JOIN LOCALITIES L ON L.LOCALITY_ID=S.LOCALITY_ID
   WHERE O.ORDER_ID=:ORDER_ID
    INTO :DRIVER_ID,
         :PREFIX, :STREET, :HOUSE, :FLAT, :PORCH, :LOCALITY,
         :DATE_ACCEPT, :DATE_ARRIVAL, :BEFORE_PERIOD,
         :ACTION_ID, :DATE_BEGIN, :DESCRIPTION;

  IF (DRIVER_ID IS NOT NULL) THEN BEGIN

    CNT=0;

    SELECT COUNT(*)
      FROM OUT_MESSAGES
     WHERE RECIPIENT_ID=:DRIVER_ID
       AND DESCRIPTION=:ORDER_ID||:ACTION_ID
       AND TYPE_MESSAGE=0
       AND DATE_OUT IS NULL
       AND DATE_CREATE>=:DATE_BEGIN
      INTO CNT;

    IF (CNT=0) THEN BEGIN

      SELECT D.CAR_ID, A.PHONE
        FROM DRIVERS D
        JOIN ACCOUNTS A ON A.ACCOUNT_ID=D.DRIVER_ID
       WHERE D.DRIVER_ID=:DRIVER_ID
        INTO :CAR_ID, :PHONE;

      D=CURRENT_TIMESTAMP;

      UPDATE ORDERS
         SET DRIVER_ID=:DRIVER_ID,
             CAR_ID=:CAR_ID,
             DATE_END=:D,
             WHO_PROCESS_ID=:ACCOUNT_ID
       WHERE ORDER_ID=:ORDER_ID;

      ADDRESS='';

      IF (PREFIX IS NOT NULL) THEN
        ADDRESS=PREFIX||' ';

      ADDRESS=ADDRESS||STREET||' '||HOUSE;

      IF (FLAT IS NOT NULL) THEN
        ADDRESS=ADDRESS||'-'||FLAT;

      IF (PORCH IS NOT NULL) THEN
        ADDRESS=ADDRESS||' п.'||PORCH;

      IF ((LOCALITY IS NOT NULL) AND (LOCALITY<>'Красноярск')) THEN
        ADDRESS=ADDRESS||', '||LOCALITY;

      IF (DATE_ACCEPT<DATE_ARRIVAL) THEN BEGIN

        IF ((DATE_ACCEPT+(BEFORE_PERIOD*(1e0/24/60)))<DATE_ARRIVAL) THEN BEGIN

          SELECT CONST_VALUE FROM GET_CONST_VALUE('2A773F389AD895B94010252F1DC6D3CC') INTO :S;

        END ELSE BEGIN

          SELECT CONST_VALUE FROM GET_CONST_VALUE('051BE1C8C28F9DB34EAA8DD46E0DA3B4') INTO :S;

        END

      END ELSE BEGIN

        SELECT CONST_VALUE FROM GET_CONST_VALUE('CD5055A23D04B51641F3211814253430') INTO :S;

      END

      IF (S IS NOT NULL) THEN BEGIN

        S=REPLACE_STRING(S,'%TIME',FORMAT_DATETIME('hh:nn',DATE_ARRIVAL));
        S=REPLACE_STRING(S,'%ADDRESS',ADDRESS);

        INSERT INTO OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                  TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,PRIORITY,LOCKED,DATE_BEGIN)
                          VALUES (GET_UNIQUE_ID(),:ACCOUNT_ID,:DRIVER_ID,:D,
                                  :S,NULL,0,:PHONE,:ORDER_ID||:ACTION_ID,0,NULL,:D);

        IF ((DESCRIPTION IS NOT NULL) AND (TRIM(DESCRIPTION)<>'')) THEN BEGIN

          S=DESCRIPTION;

          INSERT INTO OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                    TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,PRIORITY,LOCKED,DATE_BEGIN)
                            VALUES (GET_UNIQUE_ID(),:ACCOUNT_ID,:DRIVER_ID,:D,
                                    :S,NULL,0,:PHONE,NULL,0,NULL,:D);
        END

      END

    END

  END

END

--

CREATE EXCEPTION E '';

--

CREATE OR ALTER PROCEDURE I_CLIENT (
  CLIENT_ID VARCHAR(32),
  CLIENT_GROUP_ID VARCHAR(32),
  CALC_ID VARCHAR(32),
  SOURCE_ID VARCHAR(32),
  METHOD_ID VARCHAR(32),
  STREET_ID VARCHAR(32),
  "INDEX" VARCHAR(10),
  HOUSE VARCHAR(10),
  FLAT VARCHAR(10),
  SEX INTEGER,
  PASSPORT VARCHAR(250),
  DATE_BIRTH DATE,
  PLACE_BIRTH VARCHAR(250),
  MIN_BALANCE NUMERIC(15,2),
  PORCH VARCHAR(10),
  ADDRESS_DESC VARCHAR(250),
  PHONE VARCHAR(100),
  DESCRIPTION VARCHAR(250),
  USER_NAME VARCHAR(100),
  "PASSWORD" VARCHAR(100),
  LOCKED INTEGER,
  SURNAME VARCHAR(100),
  NAME VARCHAR(100),
  PATRONYMIC VARCHAR(100),
  FIRM_ID VARCHAR(32),
  JOB_TITLE VARCHAR(250))
AS
  DECLARE ROLE_ID VARCHAR(32);
  DECLARE CNT INTEGER;
BEGIN

  SELECT COUNT(*)
    FROM CLIENTS C
    JOIN ACCOUNTS A ON A.ACCOUNT_ID=C.CLIENT_ID
   WHERE UPPER(A.USER_NAME)=UPPER(:USER_NAME)
    INTO :CNT;

  IF (CNT>0) THEN
    EXCEPTION E 'Логин уже существует';


  INSERT INTO ACCOUNTS (ACCOUNT_ID,DATE_CREATE,USER_NAME,LOCKED,SURNAME,NAME,PATRONYMIC,
                                  IS_ROLE,PHONE,DESCRIPTION,FIRM_ID,JOB_TITLE,"PASSWORD")
                          VALUES (:CLIENT_ID,CURRENT_TIMESTAMP,:USER_NAME,:LOCKED,:SURNAME,:NAME,:PATRONYMIC,
                                  0,:PHONE,:DESCRIPTION,:FIRM_ID,:JOB_TITLE,:"PASSWORD");

  INSERT INTO CLIENTS (CLIENT_ID,CLIENT_GROUP_ID,CALC_ID,SOURCE_ID,METHOD_ID,STREET_ID,"INDEX",
                                 HOUSE,FLAT,SEX,PASSPORT,DATE_BIRTH,PLACE_BIRTH,MIN_BALANCE,
                                 PORCH,ADDRESS_DESC)
                         VALUES (:CLIENT_ID,:CLIENT_GROUP_ID,:CALC_ID,:SOURCE_ID,:METHOD_ID,:STREET_ID,:"INDEX",
                                 :HOUSE,:FLAT,:SEX,:PASSPORT,:DATE_BIRTH,:PLACE_BIRTH,:MIN_BALANCE,
                                 :PORCH,:ADDRESS_DESC);

  ROLE_ID='1D3BDEDD9A0B9EE84AEDC1FDED4F5A93'; /* Клиенты */
  INSERT INTO ACCOUNT_ROLES (ROLE_ID,ACCOUNT_ID)
       VALUES (:ROLE_ID,:CLIENT_ID);
END

--

CREATE OR ALTER PROCEDURE U_CLIENT (
  CLIENT_ID VARCHAR(32),
  CLIENT_GROUP_ID VARCHAR(32),
  CALC_ID VARCHAR(32),
  SOURCE_ID VARCHAR(32),
  METHOD_ID VARCHAR(32),
  STREET_ID VARCHAR(32),
  "INDEX" VARCHAR(10),
  HOUSE VARCHAR(10),
  FLAT VARCHAR(10),
  SEX INTEGER,
  PASSPORT VARCHAR(250),
  DATE_BIRTH DATE,
  PLACE_BIRTH VARCHAR(250),
  MIN_BALANCE NUMERIC(15,2),
  PORCH VARCHAR(10),
  ADDRESS_DESC VARCHAR(250),
  PHONE VARCHAR(100),
  DESCRIPTION VARCHAR(250),
  USER_NAME VARCHAR(100),
  "PASSWORD" VARCHAR(100),
  LOCKED INTEGER,
  SURNAME VARCHAR(100),
  NAME VARCHAR(100),
  PATRONYMIC VARCHAR(100),
  FIRM_ID VARCHAR(32),
  JOB_TITLE VARCHAR(250),
  OLD_CLIENT_ID VARCHAR(32))
AS
  DECLARE CNT INTEGER;
BEGIN

  SELECT COUNT(*)
    FROM CLIENTS C
    JOIN ACCOUNTS A ON A.ACCOUNT_ID=C.CLIENT_ID
   WHERE UPPER(A.USER_NAME)=UPPER(:USER_NAME)
     AND C.CLIENT_ID<>:CLIENT_ID
    INTO :CNT;

  IF (CNT>0) THEN
    EXCEPTION E 'Логин уже существует';


  UPDATE ACCOUNTS
     SET ACCOUNT_ID=:CLIENT_ID,
         USER_NAME=:USER_NAME,
         LOCKED=:LOCKED,
         SURNAME=:SURNAME,
         NAME=:NAME,
         PATRONYMIC=:PATRONYMIC,
         IS_ROLE=0,
         PHONE=:PHONE,
         DESCRIPTION=:DESCRIPTION,
         FIRM_ID=:FIRM_ID,
         JOB_TITLE=:JOB_TITLE,
         "PASSWORD"=:"PASSWORD"
   WHERE ACCOUNT_ID=:OLD_CLIENT_ID;

  UPDATE CLIENTS
     SET CLIENT_ID=:CLIENT_ID,
         CLIENT_GROUP_ID=:CLIENT_GROUP_ID,
         CALC_ID=:CALC_ID,
         SOURCE_ID=:SOURCE_ID,
         METHOD_ID=:METHOD_ID,
         STREET_ID=:STREET_ID,
         "INDEX"=:"INDEX",
         HOUSE=:HOUSE,
         FLAT=:FLAT,
         SEX=:SEX,
         PASSPORT=:PASSPORT,
         DATE_BIRTH=:DATE_BIRTH,
         PLACE_BIRTH=:PLACE_BIRTH,
         MIN_BALANCE=:MIN_BALANCE,
         PORCH=:PORCH,
         ADDRESS_DESC=:ADDRESS_DESC
   WHERE CLIENT_ID=:OLD_CLIENT_ID;

END

--

DROP PROCEDURE CODE_BALANCE

--

CREATE OR ALTER PROCEDURE CODE_DRIVER_BALANCE
(
  ACCOUNT_ID VARCHAR(32),
  IN_MESSAGE_ID VARCHAR(32)
)
AS
DECLARE CONTACT VARCHAR(100);
DECLARE SENDER_ID VARCHAR(32);
DECLARE S VARCHAR(70);
DECLARE SUM_CHARGE NUMERIC(15,2);
DECLARE SUM_RECEIPT NUMERIC(15,2);
DECLARE BALANCE NUMERIC(15,2);
DECLARE CNT INTEGER;
DECLARE CHARGE_TYPE_ID VARCHAR(32);
DECLARE CONST_VALUE VARCHAR(4000);
BEGIN
  SELECT CONTACT, SENDER_ID
    FROM IN_MESSAGES
   WHERE IN_MESSAGE_ID=:IN_MESSAGE_ID
    INTO :CONTACT, :SENDER_ID;

  IF ((CONTACT IS NOT NULL) AND (SENDER_ID IS NOT NULL)) THEN BEGIN

    EXECUTE PROCEDURE GET_ACCOUNT_BALANCE(:SENDER_ID)
     RETURNING_VALUES :SUM_CHARGE, :SUM_RECEIPT, :BALANCE;

    SELECT COUNT(*)
      FROM DRIVERS D
      JOIN ACCOUNTS A ON A.ACCOUNT_ID=D.DRIVER_ID
     WHERE D.DRIVER_ID=:SENDER_ID
       AND A.LOCKED<>1
      INTO :CNT;

    IF (CNT>0) THEN BEGIN

      SELECT CONST_VALUE FROM GET_CONST_VALUE('2031AA8F2E4B959248967F2838DC5F19') INTO :S;

      IF (S IS NOT NULL) THEN BEGIN

        S=REPLACE_STRING(S,'%BALANCE',CAST(BALANCE AS VARCHAR(30)));

        INSERT INTO OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                  TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,PRIORITY,LOCKED,DATE_BEGIN)
                          VALUES (GET_UNIQUE_ID(),:ACCOUNT_ID,:SENDER_ID,CURRENT_TIMESTAMP,
                                  :S,NULL,0,:CONTACT,NULL,1,NULL,CURRENT_TIMESTAMP);
      END

    END

  END
END

--

CREATE OR ALTER PROCEDURE CODE_CLIENT_BALANCE
(
  ACCOUNT_ID VARCHAR(32),
  IN_MESSAGE_ID VARCHAR(32)
)
AS
DECLARE CONTACT VARCHAR(100);
DECLARE SENDER_ID VARCHAR(32);
DECLARE S VARCHAR(70);
DECLARE SUM_CHARGE NUMERIC(15,2);
DECLARE SUM_RECEIPT NUMERIC(15,2);
DECLARE BALANCE NUMERIC(15,2);
DECLARE CNT INTEGER;
DECLARE CHARGE_TYPE_ID VARCHAR(32);
DECLARE CONST_VALUE VARCHAR(4000);
BEGIN
  SELECT CONTACT, SENDER_ID
    FROM IN_MESSAGES
   WHERE IN_MESSAGE_ID=:IN_MESSAGE_ID
    INTO :CONTACT, :SENDER_ID;

  IF ((CONTACT IS NOT NULL) AND (SENDER_ID IS NOT NULL)) THEN BEGIN

    EXECUTE PROCEDURE GET_ACCOUNT_BALANCE(:SENDER_ID)
     RETURNING_VALUES :SUM_CHARGE, :SUM_RECEIPT, :BALANCE;

    SELECT COUNT(*)
      FROM CLIENTS C
      JOIN ACCOUNTS A ON A.ACCOUNT_ID=C.CLIENT_ID
     WHERE C.CLIENT_ID=:SENDER_ID
       AND A.LOCKED<>1
      INTO :CNT;

    IF (CNT>0) THEN BEGIN

      SELECT CONST_VALUE FROM GET_CONST_VALUE('2031AA8F2E4B959248967F2838DC5F19') INTO :S;

      IF (S IS NOT NULL) THEN BEGIN

        S=REPLACE_STRING(S,'%BALANCE',CAST(BALANCE AS VARCHAR(30)));

        INSERT INTO OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                  TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,PRIORITY,LOCKED,DATE_BEGIN)
                          VALUES (GET_UNIQUE_ID(),:ACCOUNT_ID,:SENDER_ID,CURRENT_TIMESTAMP,
                                  :S,NULL,0,:CONTACT,NULL,1,NULL,CURRENT_TIMESTAMP);
      END

    END

  END
END

--

CREATE OR ALTER PROCEDURE CODE_ORDER
(
  ACCOUNT_ID VARCHAR(32),
  IN_MESSAGE_ID VARCHAR(32)
)
AS
DECLARE CONTACT VARCHAR(100);
DECLARE SENDER_ID VARCHAR(32);
DECLARE S VARCHAR(70);
DECLARE CNT INTEGER;
DECLARE CONST_VALUE VARCHAR(4000);
DECLARE ORDER_NUM VARCHAR(10);
DECLARE ACTION_ID VARCHAR(32);
DECLARE RATE_ID VARCHAR(32);
DECLARE CAR_TYPE_ID VARCHAR(32);
DECLARE CLIENT_ID VARCHAR(32);
DECLARE STREET_ID VARCHAR(32);
DECLARE HOUSE VARCHAR(10);
DECLARE FLAT VARCHAR(10);
DECLARE PORCH VARCHAR(10);
DECLARE ADDRESS_DESC VARCHAR(250);
DECLARE LOCKED INTEGER;
BEGIN
  SELECT CONTACT, SENDER_ID
    FROM IN_MESSAGES
   WHERE IN_MESSAGE_ID=:IN_MESSAGE_ID
    INTO :CONTACT, :SENDER_ID;

  SELECT COUNT(*)
    FROM BLACKS
   WHERE UPPER(PHONE)=UPPER(:CONTACT)
    INTO :CNT;

  IF ((CONTACT IS NOT NULL) AND (CNT=0)) THEN BEGIN

    SELECT LOCKED, CLIENT_ID, STREET_ID, HOUSE, FLAT, PORCH, ADDRESS_DESC
      FROM CLIENTS C
      JOIN ACCOUNTS A ON A.ACCOUNT_ID=C.CLIENT_ID
     WHERE C.CLIENT_ID=:SENDER_ID
      INTO :LOCKED, :CLIENT_ID, :STREET_ID, :HOUSE, :FLAT, :PORCH, :ADDRESS_DESC;

    IF ((CLIENT_ID IS NULL) OR ((CLIENT_ID IS NOT NULL) AND (LOCKED<>1))) THEN BEGIN

      SELECT CONST_VALUE FROM GET_CONST_VALUE('CB66FC06A78BB69D430EB7BD1AFA13FA') INTO :S;

      IF (S IS NOT NULL) THEN BEGIN

        STREET_ID='FA27330C653381FA4EDE11ECF0959DD6';  /* Красноярск - .*/
        HOUSE=NULL;
        FLAT=NULL;
        PORCH=NULL;
        ADDRESS_DESC=NULL;

        EXECUTE PROCEDURE GET_ORDER_NUM
         RETURNING_VALUES :ORDER_NUM;

        ACTION_ID='E019DBDE7D55BEC34D12A709EE3FEB0B'; /* Создание */

        RATE_ID=NULL;
        FOR SELECT RATE_ID
             FROM RATES
            ORDER BY PRIORITY
             INTO :RATE_ID DO BEGIN
          BREAK;
        END

        CAR_TYPE_ID=NULL;
        FOR SELECT CAR_TYPE_ID
              FROM CAR_TYPES
             ORDER BY PRIORITY
              INTO :CAR_TYPE_ID DO BEGIN
          BREAK;
        END

        IF ((RATE_ID IS NOT NULL) AND (CAR_TYPE_ID IS NOT NULL)) THEN BEGIN

          INSERT INTO ORDERS (ORDER_ID,ACTION_ID,RATE_ID,CAR_TYPE_ID,WHO_ACCEPT_ID,
                              CLIENT_ID,STREET_ID,HOUSE,FLAT,PORCH,DESCRIPTION,
                              ORDER_NUM,PHONE,DATE_ACCEPT,DATE_ARRIVAL,TYPE_ACCEPT,
                              TYPE_PROCESS,BEFORE_PERIOD,DATE_BEGIN,FINISHED)
                      VALUES (GET_UNIQUE_ID(),:ACTION_ID,:RATE_ID,:CAR_TYPE_ID,:ACCOUNT_ID,
                              :CLIENT_ID,:STREET_ID,:HOUSE,:FLAT,:PORCH,:ADDRESS_DESC,
                              :ORDER_NUM,:CONTACT,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,
                              1,30,CURRENT_TIMESTAMP,0);

          S=REPLACE_STRING(S,'%ORDER_NUM',ORDER_NUM);

          INSERT INTO OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                    TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,PRIORITY,LOCKED,DATE_BEGIN)
                            VALUES (GET_UNIQUE_ID(),:ACCOUNT_ID,:SENDER_ID,CURRENT_TIMESTAMP,
                                    :S,NULL,0,:CONTACT,NULL,1,NULL,CURRENT_TIMESTAMP);

        END

      END

    END

  END

END

--

CREATE OR ALTER PROCEDURE PR_ARRIVAL_DRIVER (
  ORDER_ID VARCHAR(32),
  ACCOUNT_ID VARCHAR(32))
AS
DECLARE PHONE VARCHAR(100);
DECLARE DRIVER_ID VARCHAR(32);
DECLARE COST_RATE NUMERIC(15,2);
DECLARE COST_CASH NUMERIC(15,2);
DECLARE COLOR VARCHAR(100);
DECLARE BRAND VARCHAR(100);
DECLARE STATE_NUM VARCHAR(50);
DECLARE PREFIX VARCHAR(10);
DECLARE STREET VARCHAR(100);
DECLARE HOUSE VARCHAR(10);
DECLARE FLAT VARCHAR(10);
DECLARE PORCH VARCHAR(10);
DECLARE LOCALITY VARCHAR(100);
DECLARE CLIENT_ID VARCHAR(32);
DECLARE CALC_ID VARCHAR(32);
DECLARE SUM_CHARGE NUMERIC(15,2);
DECLARE SUM_RECEIPT NUMERIC(15,2);
DECLARE BALANCE NUMERIC(15,2);
DECLARE S VARCHAR(1000);
DECLARE S1 VARCHAR(1000);
DECLARE ADDRESS VARCHAR(1000);
DECLARE NUM INTEGER;
DECLARE CNT INTEGER;
DECLARE FLAG INTEGER;
DECLARE D TIMESTAMP;
BEGIN

  SELECT O.PHONE, O.DRIVER_ID, O.COST_RATE, O.CLIENT_ID,
         C.COLOR, C.BRAND, C.STATE_NUM
    FROM ORDERS O
    LEFT JOIN DRIVERS D ON D.DRIVER_ID=O.DRIVER_ID
    LEFT JOIN CARS C ON C.CAR_ID=D.CAR_ID
   WHERE ORDER_ID=:ORDER_ID
    INTO :PHONE, :DRIVER_ID, :COST_RATE, :CLIENT_ID,
         :COLOR, :BRAND, :STATE_NUM;

  UPDATE ORDERS
     SET DATE_BEGIN=CURRENT_TIMESTAMP
   WHERE ORDER_ID=:ORDER_ID;

  CALC_ID=NULL;

  IF (CLIENT_ID IS NOT NULL) THEN BEGIN

    SELECT CALC_ID
      FROM CLIENTS
     WHERE CLIENT_ID=:CLIENT_ID
      INTO :CALC_ID;

  END

  BALANCE=NULL;

  IF (CALC_ID IS NOT NULL) THEN BEGIN

    EXECUTE PROCEDURE GET_ACCOUNT_BALANCE(:CLIENT_ID)
     RETURNING_VALUES :SUM_CHARGE, :SUM_RECEIPT, :BALANCE;

  END

  FLAG=0;

  FOR SELECT STREET_ID, HOUSE
        FROM ROUTES
       WHERE ORDER_ID=:ORDER_ID
       ORDER BY PRIORITY
        INTO :STREET, :HOUSE DO BEGIN

    IF ((STREET IS NOT NULL) AND (HOUSE IS NOT NULL)) THEN BEGIN

    END ELSE BEGIN

      FLAG=1;

    END
  END

  COST_CASH=NULL;

  IF ((COST_RATE>0.0) AND (FLAG=0)) THEN BEGIN

    IF (BALANCE IS NOT NULL) THEN BEGIN

      IF (BALANCE>=COST_RATE) THEN
        COST_CASH=0.0;
      ELSE
        COST_CASH=COST_RATE-BALANCE;

    END

  END

  IF (SUBSTR(PHONE,1,3)='+79')  THEN BEGIN

    IF ((COST_RATE>0.0) AND (FLAG=0)) THEN BEGIN

      IF (COST_CASH IS NULL) THEN

        SELECT CONST_VALUE FROM GET_CONST_VALUE('8D9E6C9F4852AD8142205F027B2A5288') INTO :S;

      ELSE

        SELECT CONST_VALUE FROM GET_CONST_VALUE('9CA9F2761D2BBE974791906824C3C31A') INTO :S;

    END ELSE BEGIN

      SELECT CONST_VALUE FROM GET_CONST_VALUE('93EBB0171E37A0884313759C0DA1EB3D') INTO :S;

    END

    IF (S IS NOT NULL) THEN BEGIN

      S=REPLACE_STRING(S,'%COLOR',COLOR);
      S=REPLACE_STRING(S,'%BRAND',BRAND);
      S=REPLACE_STRING(S,'%STATE_NUM',STATE_NUM);
      S=REPLACE_STRING(S,'%COST_RATE',CAST(CAST(COST_RATE AS NUMERIC(15,0)) AS VARCHAR(30)));
      S=REPLACE_STRING(S,'%COST_CASH',CAST(CAST(COST_CASH AS NUMERIC(15,0)) AS VARCHAR(30)));

      INSERT INTO OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,PRIORITY,LOCKED,DATE_BEGIN)
                        VALUES (GET_UNIQUE_ID(),:ACCOUNT_ID,:CLIENT_ID,CURRENT_TIMESTAMP,
                                :S,NULL,0,:PHONE,NULL,0,NULL,CURRENT_TIMESTAMP);

    END

    SELECT CONST_VALUE FROM GET_CONST_VALUE('F4384929079999BB47A895BFCA5BB382') INTO :S;

    IF (S IS NOT NULL) THEN BEGIN

      INSERT INTO OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,PRIORITY,LOCKED,DATE_BEGIN)
                        VALUES (GET_UNIQUE_ID(),:ACCOUNT_ID,:CLIENT_ID,CURRENT_TIMESTAMP,
                                :S,NULL,0,:PHONE,NULL,0,NULL,CURRENT_TIMESTAMP);

    END

  END

  IF (DRIVER_ID IS NOT NULL) THEN BEGIN

    SELECT PHONE
      FROM ACCOUNTS
     WHERE ACCOUNT_ID=:DRIVER_ID
      INTO :PHONE;

    FLAG=0;
    NUM=0;

    SELECT COUNT(*)
      FROM ROUTES
     WHERE ORDER_ID=:ORDER_ID
      INTO :CNT;

    D=CURRENT_TIMESTAMP;

    FOR SELECT S.PREFIX, S.NAME, R.HOUSE, R.FLAT, R.PORCH, L.NAME
          FROM ROUTES R
          LEFT JOIN STREETS S ON S.STREET_ID=R.STREET_ID
          LEFT JOIN LOCALITIES L ON L.LOCALITY_ID=S.LOCALITY_ID
         WHERE R.ORDER_ID=:ORDER_ID
         ORDER BY R.PRIORITY
          INTO :PREFIX, :STREET, :HOUSE, :FLAT, :PORCH, :LOCALITY DO BEGIN

      ADDRESS='';
      S=NULL;

      IF ((STREET IS NOT NULL) AND (HOUSE IS NOT NULL)) THEN BEGIN

        IF (PREFIX IS NOT NULL) THEN
          ADDRESS=PREFIX||' ';

        IF (STREET IS NOT NULL) THEN
          ADDRESS=ADDRESS||STREET;

        IF (HOUSE IS NOT NULL) THEN
          ADDRESS=ADDRESS||' '||HOUSE;

        IF (FLAT IS NOT NULL) THEN
          ADDRESS=ADDRESS||'-'||FLAT;

        IF (PORCH IS NOT NULL) THEN
          ADDRESS=ADDRESS||' п.'||PORCH;

        IF ((LOCALITY IS NOT NULL) AND (LOCALITY<>'Красноярск')) THEN
          ADDRESS=ADDRESS||', '||LOCALITY;

        SELECT CONST_VALUE FROM GET_CONST_VALUE('92009DB6C3EAA9E74B80D333538FE40D') INTO :S;

      END ELSE BEGIN

        FLAG=1;

        SELECT CONST_VALUE FROM GET_CONST_VALUE('7ED5E8A8BBD9870A411517B54D9EB973') INTO :S;

      END

      IF (S IS NOT NULL) THEN BEGIN

        NUM=NUM+1;

        S=REPLACE_STRING(S,'%NUM',NUM);
        S=REPLACE_STRING(S,'%COUNT',CNT);
        S=REPLACE_STRING(S,'%ADDRESS',ADDRESS);

        IF (NUM=CNT) THEN BEGIN

          IF ((FLAG=0) AND (COST_RATE>0.0)) THEN BEGIN

            IF (COST_CASH IS NULL) THEN

              SELECT CONST_VALUE FROM GET_CONST_VALUE('9C8BC7D14DAEAE5C4DC8C1C91B20BCC2') INTO :S1;

            ELSE

              SELECT CONST_VALUE FROM GET_CONST_VALUE('A468782967A1A4D347F85F33D39E348A') INTO :S1;

          END ELSE

            SELECT CONST_VALUE FROM GET_CONST_VALUE('D3F68032AD999D004140A480A8AAF749') INTO :S1;

        END ELSE

          S1=S;


        IF (S1 IS NOT NULL) THEN BEGIN

          S1=REPLACE_STRING(S1,'%ADDRESS',S);
          S1=REPLACE_STRING(S1,'%COST_RATE',CAST(CAST(COST_RATE AS NUMERIC(15,0)) AS VARCHAR(30)));
          S1=REPLACE_STRING(S1,'%COST_CASH',CAST(CAST(COST_CASH AS NUMERIC(15,0)) AS VARCHAR(30)));

          INSERT INTO OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                    TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,PRIORITY,LOCKED,DATE_BEGIN)
                            VALUES (GET_UNIQUE_ID(),:ACCOUNT_ID,:DRIVER_ID,CURRENT_TIMESTAMP,
                                    :S1,NULL,0,:PHONE,NULL,2,NULL,:D);

          D=D+1*(1e0/24/60/60);

        END

      END

    END

  END

END

--

charge_types

757B9CAF2D3CA5144A7E2A23472990E5

receipt_types

3F91C48D888F81974941D256C0815B03
9958D6ED64ADAAB94AEF470DA7B5F4F7

--

CREATE OR ALTER PROCEDURE PR_FULL_CALC (
  ORDER_ID VARCHAR(32),
  ACCOUNT_ID VARCHAR(32))
AS
DECLARE COST_RATE NUMERIC(15,2);
DECLARE COST_FACT NUMERIC(15,2);
DECLARE NON_CASH NUMERIC(15,2);
DECLARE PARENT_SUM NUMERIC(15,2);
DECLARE PHONE VARCHAR(100);
DECLARE DRIVER_ID VARCHAR(32);
DECLARE SUM_CHARGE NUMERIC(15,2);
DECLARE SUM_RECEIPT NUMERIC(15,2);
DECLARE BALANCE NUMERIC(15,2);
DECLARE MIN_BALANCE NUMERIC(15,2);
DECLARE CHARGE_TYPE_ID VARCHAR(32);
DECLARE RECEIPT_TYPE_ID VARCHAR(32);
DECLARE CLIENT_ID VARCHAR(32);
DECLARE PARENT_ID VARCHAR(32);
DECLARE CALC_ID VARCHAR(32);
DECLARE S VARCHAR(1000);
DECLARE CODE VARCHAR(100);
DECLARE CNT INTEGER;
DECLARE DESCRIPTION VARCHAR(250);
DECLARE USER_NAME VARCHAR(100);
BEGIN

  SELECT PHONE, DRIVER_ID, COST_RATE, COST_FACT, CLIENT_ID
    FROM ORDERS
   WHERE ORDER_ID=:ORDER_ID
    INTO :PHONE, :DRIVER_ID, :COST_RATE, :COST_FACT, :CLIENT_ID;

  IF ((COST_FACT IS NULL) OR (COST_FACT<=0.0))  THEN
    COST_FACT=:COST_RATE;

  IF (COST_FACT<=0.0) THEN BEGIN

    SELECT CONST_VALUE FROM GET_CONST_VALUE('4BB5C780923E872D436DA3DA31C9E0B0') INTO :S;

    IF (S IS NOT NULL) THEN BEGIN

      SELECT PHONE
        FROM ACCOUNTS
       WHERE ACCOUNT_ID=:DRIVER_ID
        INTO :PHONE;

      INSERT INTO OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,PRIORITY,LOCKED,DATE_BEGIN)
                        VALUES (GET_UNIQUE_ID(),:ACCOUNT_ID,:DRIVER_ID,CURRENT_TIMESTAMP,
                                :S,NULL,0,:PHONE,NULL,2,NULL,CURRENT_TIMESTAMP);
    END

    EXECUTE PROCEDURE PR_MANUAL(ORDER_ID,ACCOUNT_ID);

  END ELSE BEGIN

    UPDATE ORDERS
       SET FINISHED=1,
           DATE_END=CURRENT_TIMESTAMP,
           WHO_PROCESS_ID=:ACCOUNT_ID,
           COST_FACT=:COST_FACT
     WHERE ORDER_ID=:ORDER_ID;

    EXECUTE PROCEDURE CREATE_ROUTE_HISTORY(ORDER_ID);

    IF (DRIVER_ID IS NOT NULL) THEN BEGIN

      CALC_ID=NULL;

      IF (CLIENT_ID IS NOT NULL) THEN BEGIN

        SELECT C.CALC_ID, A.USER_NAME
          FROM CLIENTS C
          JOIN ACCOUNTS A ON A.ACCOUNT_ID=C.CLIENT_ID
         WHERE CLIENT_ID=:CLIENT_ID
          INTO :CALC_ID, :USER_NAME;

        SELECT COUNT(*)
          FROM CLIENT_CHILDS
         WHERE CHILD_ID=:CLIENT_ID
          INTO :CNT;

        IF (CNT>0) THEN BEGIN

          PARENT_SUM=2.0;

          IF ((COST_FACT>150.0) AND (COST_FACT<=250.0)) THEN
            PARENT_SUM=5.0;

          IF ((COST_FACT>250.0) AND (COST_FACT<=350.0)) THEN
            PARENT_SUM=10.0;

          IF (COST_FACT>350.0) THEN
            PARENT_SUM=20.0;

          SUM_RECEIPT=PARENT_SUM/CNT;

          FOR SELECT CLIENT_ID
                FROM CLIENT_CHILDS

               WHERE CHILD_ID=:CLIENT_ID
                INTO :PARENT_ID DO BEGIN

           RECEIPT_TYPE_ID='9958D6ED64ADAAB94AEF470DA7B5F4F7'; /* Поездка дочернего клиента */

           DESCRIPTION=USER_NAME;

           INSERT INTO RECEIPTS (RECEIPT_ID,RECEIPT_TYPE_ID,ACCOUNT_ID,WHO_CREATE_ID,
                                 SUM_RECEIPT,DATE_RECEIPT,DATE_CREATE,DESCRIPTION)
                         VALUES (GET_UNIQUE_ID(),:RECEIPT_TYPE_ID,:PARENT_ID,:ACCOUNT_ID,
                                :SUM_RECEIPT,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,:DESCRIPTION);


          END
        END

      END

      BALANCE=NULL;

      IF (CALC_ID IS NOT NULL) THEN BEGIN

        EXECUTE PROCEDURE GET_ACCOUNT_BALANCE(:CLIENT_ID)
         RETURNING_VALUES :SUM_CHARGE, :SUM_RECEIPT, :BALANCE;

      END

      NON_CASH=NULL;

      IF (BALANCE IS NOT NULL) THEN BEGIN

        IF (BALANCE>=COST_FACT) THEN BEGIN
          NON_CASH=COST_FACT;
          BALANCE=BALANCE-NON_CASH;
        END ELSE BEGIN
          NON_CASH=BALANCE;
          BALANCE=0.0;
        END

      END

      IF (NON_CASH IS NOT NULL) THEN BEGIN

        CHARGE_TYPE_ID='757B9CAF2D3CA5144A7E2A23472990E5'; /* Поездка */

        SUM_CHARGE=NON_CASH;

        INSERT INTO CHARGES (CHARGE_ID,WHO_CREATE_ID,CHARGE_TYPE_ID,ACCOUNT_ID,
                             SUM_CHARGE,DATE_CHARGE,DATE_CREATE,DESCRIPTION)
                     VALUES (GET_UNIQUE_ID(),:ACCOUNT_ID,:CHARGE_TYPE_ID,:CLIENT_ID,
                             :SUM_CHARGE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL);


      END

      IF (SUBSTR(PHONE,1,3)='+79')  THEN BEGIN

        IF (NON_CASH IS NOT NULL) THEN BEGIN

          SELECT CONST_VALUE FROM GET_CONST_VALUE('56140344A440BE774C9007D49CD574E9') INTO :S;

        END ELSE BEGIN

          SELECT CONST_VALUE FROM GET_CONST_VALUE('05B75340B170BF5141FC63F5CDF7FCD6') INTO :S;

        END

        IF (S IS NOT NULL) THEN BEGIN

          S=REPLACE_STRING(S,'%BALANCE',CAST(CAST(BALANCE AS NUMERIC(15,0)) AS VARCHAR(30)));

          INSERT INTO OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                    TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,PRIORITY,LOCKED,DATE_BEGIN)
                            VALUES (GET_UNIQUE_ID(),:ACCOUNT_ID,:CLIENT_ID,CURRENT_TIMESTAMP,
                                    :S,NULL,0,:PHONE,NULL,2,NULL,CURRENT_TIMESTAMP);
        END

        SELECT CONST_VALUE FROM GET_CONST_VALUE('E9FFA9589ABD8C174474572B72017BCC') INTO :S;

        IF (S IS NOT NULL) THEN BEGIN

          INSERT INTO OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                    TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,PRIORITY,LOCKED,DATE_BEGIN)
                            VALUES (GET_UNIQUE_ID(),:ACCOUNT_ID,:CLIENT_ID,CURRENT_TIMESTAMP,
                                    :S,NULL,0,:PHONE,NULL,2,NULL,CURRENT_TIMESTAMP);
        END

      END

      CHARGE_TYPE_ID='E1BC9789DA9DB2B041C0784EBE92BFC9'; /* Выполнение заказа */

      SELECT RET_SUM
        FROM GET_DRIVER_SUM(:DRIVER_ID,:COST_FACT)
        INTO :SUM_CHARGE;

      INSERT INTO CHARGES (CHARGE_ID,WHO_CREATE_ID,CHARGE_TYPE_ID,ACCOUNT_ID,
                           SUM_CHARGE,DATE_CHARGE,DATE_CREATE,DESCRIPTION)
                   VALUES (GET_UNIQUE_ID(),:ACCOUNT_ID,:CHARGE_TYPE_ID,:DRIVER_ID,
                           :SUM_CHARGE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL);

      IF (NON_CASH IS NOT NULL) THEN BEGIN

        RECEIPT_TYPE_ID='3F91C48D888F81974941D256C0815B03'; /* Компенсация за поездку */

        SUM_RECEIPT=NON_CASH;

        INSERT INTO RECEIPTS (RECEIPT_ID,RECEIPT_TYPE_ID,ACCOUNT_ID,WHO_CREATE_ID,
                              SUM_RECEIPT,DATE_RECEIPT,DATE_CREATE,DESCRIPTION)
                      VALUES (GET_UNIQUE_ID(),:RECEIPT_TYPE_ID,:DRIVER_ID,:ACCOUNT_ID,
                              :SUM_RECEIPT,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL);

      END

      EXECUTE PROCEDURE GET_ACCOUNT_BALANCE(:DRIVER_ID)
       RETURNING_VALUES :SUM_CHARGE, :SUM_RECEIPT, :BALANCE;

      SELECT MIN_BALANCE
        FROM DRIVERS
       WHERE DRIVER_ID=:DRIVER_ID
        INTO :MIN_BALANCE;

      IF ((MIN_BALANCE IS NULL) OR ((MIN_BALANCE IS NOT NULL) AND (BALANCE>MIN_BALANCE))) THEN BEGIN

        SELECT CONST_VALUE FROM GET_CONST_VALUE('16835607B30CA79F4CE883B53AFE972D') INTO :S;

      END ELSE BEGIN

        UPDATE SHIFTS
           SET DATE_END=CURRENT_TIMESTAMP
         WHERE ACCOUNT_ID=:DRIVER_ID
           AND DATE_END IS NULL;

        SELECT CONST_VALUE FROM GET_CONST_VALUE('634880F305E9AA434245E3E596697001') INTO :S;

      END

      SELECT PHONE
        FROM ACCOUNTS
       WHERE ACCOUNT_ID=:DRIVER_ID
        INTO :PHONE;

      IF (S IS NOT NULL) THEN BEGIN

        S=REPLACE_STRING(S,'%BALANCE',CAST(BALANCE AS VARCHAR(30)));

        IF (NON_CASH IS NULL) THEN
          NON_CASH=0.0;

        S=REPLACE_STRING(S,'%NON_CASH',CAST(CAST(NON_CASH AS NUMERIC(15,0)) AS VARCHAR(30)));

        INSERT INTO OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                  TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,PRIORITY,LOCKED,DATE_BEGIN)
                          VALUES (GET_UNIQUE_ID(),:ACCOUNT_ID,:DRIVER_ID,CURRENT_TIMESTAMP,
                                  :S,NULL,0,:PHONE,NULL,2,NULL,CURRENT_TIMESTAMP);
      END

      FOR SELECT TRIM(SUB_STRING(IM.TEXT_IN,2,100))
            FROM IN_MESSAGES IM
            JOIN CODE_MESSAGES CM ON CM.CODE_MESSAGE_ID=IM.CODE_MESSAGE_ID
           WHERE IM.SENDER_ID=:DRIVER_ID
             AND IM.CODE_MESSAGE_ID='0388BCC17DE1A1754B566F18AEEED771' /* Клиент рассчитался полностью */
             AND IM.TYPE_MESSAGE=0
             AND CM.ENABLED=1
           ORDER BY IM.DATE_IN DESC
            INTO :CODE DO BEGIN

        SELECT COUNT(*)
          FROM CODE_MESSAGES
         WHERE CODE=:CODE
          INTO :CNT;

        IF (CNT=1) THEN BEGIN

          EXECUTE PROCEDURE TRY_PARK_IN(ACCOUNT_ID,DRIVER_ID,CODE);

        END ELSE BEGIN

          EXECUTE PROCEDURE QUERY_PARK_STATES (ACCOUNT_ID,DRIVER_ID,PHONE);

        END

        BREAK;
      END

    END

  END
END

--