/* Создание представления входящий сообщений водителей */

CREATE VIEW S_DRIVER_IN_MESSAGES
(
    IN_MESSAGE_ID,
    SENDER_ID,
    CODE_MESSAGE_ID,
    DATE_SEND,
    TEXT_IN,
    DATE_IN,
    TYPE_MESSAGE,
    CONTACT,
    SENDER_NAME,
    CODE,
    CAR_STATE_NUM,
    CAR_BRAND,
    CAR_COLOR,
    CAR_CALLSIGN

    )
AS
SELECT IM.*,
       A.USER_NAME AS SENDER_NAME,
       CM.CODE,
       CR.STATE_NUM AS CAR_STATE_NUM,
       CR.BRAND AS CAR_BRAND,
       CR.COLOR AS CAR_COLOR,
       CR.CALLSIGN AS CAR_CALLSIGN

  FROM /*PREFIX*/IN_MESSAGES IM
  JOIN /*PREFIX*/DRIVERS D ON D.DRIVER_ID=IM.SENDER_ID
  JOIN /*PREFIX*/CARS CR ON CR.CAR_ID=D.CAR_ID
  LEFT JOIN /*PREFIX*/ACCOUNTS A ON A.ACCOUNT_ID=IM.SENDER_ID
  LEFT JOIN /*PREFIX*/CODE_MESSAGES CM ON CM.CODE_MESSAGE_ID=IM.CODE_MESSAGE_ID

--

/* Создание представления исходящий сообщений водителей */


CREATE VIEW S_DRIVER_OUT_MESSAGES
(
    OUT_MESSAGE_ID,
    CREATOR_ID,
    RECIPIENT_ID,
    DATE_CREATE,
    TEXT_OUT,
    DATE_OUT,
    TYPE_MESSAGE,
    CONTACT,
    DESCRIPTION,
    PRIORITY,
    LOCKED,
    PERIOD,
    CREATOR_NAME,
    RECIPIENT_NAME,
    RECIPIENT_PHONE,
    RECIPIENT_EMAIL,
    CAR_STATE_NUM,
    CAR_BRAND,
    CAR_COLOR,
    CAR_CALLSIGN
    )
AS
SELECT OM.*,
       A1.USER_NAME AS CREATOR_NAME,
       A2.USER_NAME AS RECIPIENT_NAME,
       A2.PHONE AS RECIPIENT_PHONE,
       A2.EMAIL AS RECIPIENT_EMAIL,
       CR.STATE_NUM AS CAR_STATE_NUM,
       CR.BRAND AS CAR_BRAND,
       CR.COLOR AS CAR_COLOR,
       CR.CALLSIGN AS CAR_CALLSIGN

  FROM /*PREFIX*/OUT_MESSAGES OM
  JOIN /*PREFIX*/DRIVERS D ON D.DRIVER_ID=OM.RECIPIENT_ID
  JOIN /*PREFIX*/CARS CR ON CR.CAR_ID=D.CAR_ID
  JOIN /*PREFIX*/ACCOUNTS A1 ON A1.ACCOUNT_ID=OM.CREATOR_ID
  LEFT JOIN /*PREFIX*/ACCOUNTS A2 ON A2.ACCOUNT_ID=OM.RECIPIENT_ID

--
