DROP PROCEDURE GET_ROUTE_DISTANCE

--

DROP EXTERNAL FUNCTION HTTP_GET

--

DECLARE EXTERNAL FUNCTION HTTP_GET
    CSTRING(32767),
    CSTRING(32767),
    CSTRING(32767),
    CSTRING(32767),
    BLOB
RETURNS PARAMETER 5
ENTRY_POINT 'HTTP_GET' MODULE_NAME 'udfibase.dll';

--

CREATE OR ALTER PROCEDURE GET_ROUTE_DISTANCE
(
  LAT1 DOUBLE PRECISION,
  LON1 DOUBLE PRECISION,
  LAT2 DOUBLE PRECISION,
  LON2 DOUBLE PRECISION
)
RETURNS (
  DISTANCE DOUBLE PRECISION
)
AS
DECLARE RET BLOB;
DECLARE S VARCHAR(100);
DECLARE PARAMS VARCHAR(250);
BEGIN
  DISTANCE=0.0;

  PARAMS='?Lat1='||CAST(CAST(LAT1 AS NUMERIC(12,9)) AS VARCHAR(30))||
         '&Lon1='||CAST(CAST(LON1 AS NUMERIC(12,9)) AS VARCHAR(30))||
         '&Lat2='||CAST(CAST(LAT2 AS NUMERIC(12,9)) AS VARCHAR(30))||
         '&Lon2='||CAST(CAST(LON2 AS NUMERIC(12,9)) AS VARCHAR(30));

  RET=HTTP_GET('192.168.0.2','55508','/ingitmap',PARAMS);

  IF (RET IS NOT NULL) THEN BEGIN

    S=SUBSTRING(RET FROM 1 FOR 100);

    DISTANCE=CAST(S AS NUMERIC(15,2));

  END

END

--

DECLARE EXTERNAL FUNCTION COMPRESS_BLOB
    BLOB,
    INTEGER,
    BLOB
RETURNS PARAMETER 3
ENTRY_POINT 'COMPRESS_BLOB' MODULE_NAME 'udfibase.dll';

--

DECLARE EXTERNAL FUNCTION DECOMPRESS_BLOB
    BLOB,
    BLOB
RETURNS PARAMETER 2
ENTRY_POINT 'DECOMPRESS_BLOB' MODULE_NAME 'udfibase.dll';

--

DECLARE EXTERNAL FUNCTION ENCODE_BLOB
    BLOB,
    CSTRING(32767),
    INTEGER,
    INTEGER,
    BLOB
RETURNS PARAMETER 5
ENTRY_POINT 'ENCODE_BLOB' MODULE_NAME 'udfibase.dll';

--

DECLARE EXTERNAL FUNCTION DECODE_BLOB
    BLOB,
    CSTRING(32767),
    INTEGER,
    INTEGER,
    BLOB
RETURNS PARAMETER 5
ENTRY_POINT 'DECODE_BLOB' MODULE_NAME 'udfibase.dll';

--

DECLARE EXTERNAL FUNCTION HTTP_POST
    CSTRING(32767),
    CSTRING(32767),
    CSTRING(32767),
    BLOB,
    BLOB
RETURNS PARAMETER 5
ENTRY_POINT 'HTTP_POST' MODULE_NAME 'udfibase.dll';

--

DECLARE EXTERNAL FUNCTION MD5
    CSTRING(32767)
RETURNS CSTRING(32)
ENTRY_POINT 'MD5' MODULE_NAME 'udfibase.dll';

--

DECLARE EXTERNAL FUNCTION CHR
    INTEGER
RETURNS CSTRING(1)
ENTRY_POINT 'CHR' MODULE_NAME 'udfibase.dll';

--

DECLARE EXTERNAL FUNCTION CONFIG_EXISTS
    BLOB,
    CSTRING(32767)
RETURNS INTEGER BY VALUE
ENTRY_POINT 'CONFIG_EXISTS' MODULE_NAME 'udfibase.dll';

--

DECLARE EXTERNAL FUNCTION CONFIG_READ
    BLOB,
    CSTRING(32767),
    CSTRING(32767),
    CSTRING(32767)
RETURNS CSTRING(32767)
ENTRY_POINT 'CONFIG_READ' MODULE_NAME 'udfibase.dll';

--

DECLARE EXTERNAL FUNCTION BLOB_TO_STRING
    BLOB,
    INTEGER,
    INTEGER
RETURNS CSTRING(32767)
ENTRY_POINT 'BLOB_TO_STRING' MODULE_NAME 'udfibase.dll';

--

DECLARE EXTERNAL FUNCTION STRING_TO_BLOB
    CSTRING(32767),
    BLOB
RETURNS PARAMETER 2
ENTRY_POINT 'STRING_TO_BLOB' MODULE_NAME 'udfibase.dll';

--

DECLARE EXTERNAL FUNCTION DUPE
    CSTRING(32767),
    INTEGER
RETURNS CSTRING(32767)
ENTRY_POINT 'DUPE' MODULE_NAME 'udfibase.dll';

--

DECLARE EXTERNAL FUNCTION RANDOM_STRING
    INTEGER
RETURNS CSTRING(32767)
ENTRY_POINT 'RANDOM_STRING' MODULE_NAME 'udfibase.dll';

--

DECLARE EXTERNAL FUNCTION RANDOM
    INTEGER
RETURNS INTEGER BY VALUE
ENTRY_POINT 'RANDOM' MODULE_NAME 'udfibase.dll';

--

DECLARE EXTERNAL FUNCTION JOIN_BLOB
    BLOB,
    BLOB,
    BLOB
RETURNS PARAMETER 3
ENTRY_POINT 'JOIN_BLOB' MODULE_NAME 'udfibase.dll';

--

DECLARE EXTERNAL FUNCTION UDP
    CSTRING(32767),
    CSTRING(32767),
    BLOB,
    BLOB
RETURNS PARAMETER 4
ENTRY_POINT 'UDP' MODULE_NAME 'udfibase.dll';

--

DECLARE EXTERNAL FUNCTION PING
    CSTRING(32767),
    INTEGER
RETURNS INTEGER BY VALUE
ENTRY_POINT 'PING' MODULE_NAME 'udfibase.dll';

--

DECLARE EXTERNAL FUNCTION CONFIG_WRITE
    BLOB,
    CSTRING(32767),
    CSTRING(32767),
    CSTRING(32767),
    BLOB
RETURNS PARAMETER 5
ENTRY_POINT 'CONFIG_WRITE' MODULE_NAME 'udfibase.dll';

--

CREATE OR ALTER PROCEDURE GET_CONST_VALUE
(
    CONST_NAME VARCHAR(100)
)
RETURNS (
    CONST_VALUE VARCHAR(4000)
    ) 
AS
BEGIN
  CONST_VALUE=NULL;
  FOR SELECT BLOB_TO_STRING("VALUE",1,4000)
        FROM CONSTS
       WHERE UPPER(NAME)=UPPER(:CONST_NAME)
        INTO :CONST_VALUE DO BEGIN
    BREAK;
  END
  SUSPEND;
END

--

DROP PROCEDURE RESTART_TASK_SERVER

--

DROP EXTERNAL FUNCTION EXECUTE_COMMAND

--

DECLARE EXTERNAL FUNCTION EXECUTE_COMMAND
    CSTRING(32767),
    INTEGER,
    INTEGER
RETURNS INTEGER BY VALUE
ENTRY_POINT 'EXECUTE_COMMAND' MODULE_NAME 'udfibase.dll';

