consts

A82FFC060D399C82436CB3D669239B0B
6905163E6105BE12488DAF7AAFA32810

--

ALTER TABLE IN_MESSAGES
ADD DESCRIPTION VARCHAR(250)

--

DROP VIEW S_DRIVER_IN_MESSAGES

--

CREATE VIEW S_DRIVER_IN_MESSAGES
(
    IN_MESSAGE_ID,
    SENDER_ID,
    CODE_MESSAGE_ID,
    DATE_SEND,
    TEXT_IN,
    DATE_IN,
    TYPE_MESSAGE,
    CONTACT,
    ORDER_ID,
    CHANNEL,
    DESCRIPTION,
    SENDER_NAME,
    CODE,
    CAR_STATE_NUM,
    CAR_BRAND,
    CAR_COLOR,
    CAR_CALLSIGN)
AS
SELECT IM.*,
       A.USER_NAME AS SENDER_NAME,
       CM.CODE,
       CR.STATE_NUM AS CAR_STATE_NUM,
       CR.BRAND AS CAR_BRAND,
       CR.COLOR AS CAR_COLOR,
       CR.CALLSIGN AS CAR_CALLSIGN
  FROM IN_MESSAGES IM
  JOIN DRIVERS D ON D.DRIVER_ID=IM.SENDER_ID
  JOIN CARS CR ON CR.CAR_ID=D.CAR_ID
  LEFT JOIN ACCOUNTS A ON A.ACCOUNT_ID=IM.SENDER_ID
  LEFT JOIN CODE_MESSAGES CM ON CM.CODE_MESSAGE_ID=IM.CODE_MESSAGE_ID

--

DROP VIEW S_IN_MESSAGES

--

CREATE VIEW S_IN_MESSAGES
(
    IN_MESSAGE_ID,
    SENDER_ID,
    CODE_MESSAGE_ID,
    DATE_SEND,
    TEXT_IN,
    DATE_IN,
    TYPE_MESSAGE,
    CONTACT,
    ORDER_ID,
    CHANNEL,
    DESCRIPTION,
    SENDER_NAME,
    CODE)
AS
SELECT IM.*,
       A.USER_NAME AS SENDER_NAME,
       CM.CODE
  FROM IN_MESSAGES IM
  LEFT JOIN ACCOUNTS A ON A.ACCOUNT_ID=IM.SENDER_ID
  LEFT JOIN CODE_MESSAGES CM ON CM.CODE_MESSAGE_ID=IM.CODE_MESSAGE_ID

--

CREATE OR ALTER PROCEDURE I_IN_MESSAGE 
(
  IN_MESSAGE_ID VARCHAR(32),
  SENDER_ID VARCHAR(32),
  CODE_MESSAGE_ID VARCHAR(32),
  DATE_SEND TIMESTAMP,
  TEXT_IN VARCHAR(4000),
  DATE_IN TIMESTAMP,
  TYPE_MESSAGE INTEGER,
  CONTACT VARCHAR(100),
  ORDER_ID VARCHAR(32),
  CHANNEL VARCHAR(100),
  DESCRIPTION VARCHAR(250))
AS
BEGIN
  IF (DATE_IN IS NULL) THEN BEGIN
    DATE_IN=CURRENT_TIMESTAMP;
  END

  INSERT INTO IN_MESSAGES (IN_MESSAGE_ID,SENDER_ID,CODE_MESSAGE_ID,DATE_SEND,
                           TEXT_IN,DATE_IN,TYPE_MESSAGE,CONTACT,ORDER_ID,CHANNEL,DESCRIPTION)
       VALUES (:IN_MESSAGE_ID,:SENDER_ID,:CODE_MESSAGE_ID,:DATE_SEND,
               :TEXT_IN,:DATE_IN,:TYPE_MESSAGE,:CONTACT,:ORDER_ID,:CHANNEL,:DESCRIPTION);
END

--

CREATE OR ALTER PROCEDURE U_IN_MESSAGE
(
  IN_MESSAGE_ID VARCHAR(32),
  SENDER_ID VARCHAR(32),
  CODE_MESSAGE_ID VARCHAR(32),
  DATE_SEND TIMESTAMP,
  TEXT_IN VARCHAR(4000),
  DATE_IN TIMESTAMP,
  TYPE_MESSAGE INTEGER,
  CONTACT VARCHAR(100),
  ORDER_ID VARCHAR(32),
  CHANNEL VARCHAR(100),
  DESCRIPTION VARCHAR(250),
  OLD_IN_MESSAGE_ID VARCHAR(32))
AS
BEGIN
  UPDATE IN_MESSAGES
     SET IN_MESSAGE_ID=:IN_MESSAGE_ID,
         SENDER_ID=:SENDER_ID,
         CODE_MESSAGE_ID=:CODE_MESSAGE_ID,
         DATE_SEND=:DATE_SEND,
         TEXT_IN=:TEXT_IN,
         DATE_IN=:DATE_IN,
         TYPE_MESSAGE=:TYPE_MESSAGE,
         CONTACT=:CONTACT,
         ORDER_ID=:ORDER_ID,
         CHANNEL=:CHANNEL,
         DESCRIPTION=:DESCRIPTION
   WHERE IN_MESSAGE_ID=:OLD_IN_MESSAGE_ID;
END

--

CREATE OR ALTER PROCEDURE D_IN_MESSAGE
(
  OLD_IN_MESSAGE_ID VARCHAR(32)
)
AS
BEGIN
  DELETE FROM /*PREFIX*/IN_MESSAGES 
        WHERE IN_MESSAGE_ID=:OLD_IN_MESSAGE_ID;
END

--

DROP VIEW S_MAP_OBJECTS

--

DROP PROCEDURE I_MAP_OBJECT

--

DROP PROCEDURE U_MAP_OBJECT

--

DROP PROCEDURE D_MAP_OBJECT

--


ALTER TABLE MAP_OBJECTS
ADD LAT2 DOUBLE PRECISION

--

UPDATE MAP_OBJECTS
   SET LAT2=CAST(LAT AS NUMERIC(13,9))

--

ALTER TABLE MAP_OBJECTS
DROP LAT

--

ALTER TABLE MAP_OBJECTS
ADD LON2 DOUBLE PRECISION

--

UPDATE MAP_OBJECTS
   SET LON2=CAST(LON AS NUMERIC(13,9))

--

ALTER TABLE MAP_OBJECTS
DROP LON

--

ALTER TABLE MAP_OBJECTS
ADD LAT DOUBLE PRECISION

--

UPDATE MAP_OBJECTS
   SET LAT=LAT2

--

ALTER TABLE MAP_OBJECTS
ADD LON DOUBLE PRECISION


--

UPDATE MAP_OBJECTS
   SET LON=LON2

--

ALTER TABLE MAP_OBJECTS
DROP LAT2

--

ALTER TABLE MAP_OBJECTS
DROP LON2

--

update RDB$RELATION_FIELDS set
RDB$NULL_FLAG = 1
where (RDB$FIELD_NAME = 'LAT') and
(RDB$RELATION_NAME = 'MAP_OBJECTS')

--

update RDB$RELATION_FIELDS set
RDB$NULL_FLAG = 1
where (RDB$FIELD_NAME = 'LON') and
(RDB$RELATION_NAME = 'MAP_OBJECTS')

--

CREATE VIEW /*PREFIX*/S_MAP_OBJECTS
(
  STREET_ID,
  HOUSE,
  LAT,
  LON,
  STREET_NAME,
  STREET_PREFIX,
  LOCALITY_ID,
  LOCALITY_NAME,
  LOCALITY_PREFIX
)
AS
SELECT MO.*,
       S.NAME AS STREET_NAME,
       S.PREFIX AS STREET_PREFIX,
       L.LOCALITY_ID,
       L.NAME AS LOCALITY_NAME,
       L.PREFIX AS LOCALITY_PREFIX
  FROM /*PREFIX*/MAP_OBJECTS MO
  JOIN /*PREFIX*/STREETS S ON S.STREET_ID=MO.STREET_ID
  JOIN /*PREFIX*/LOCALITIES L ON L.LOCALITY_ID=S.LOCALITY_ID

--

CREATE PROCEDURE /*PREFIX*/I_MAP_OBJECT
(
  STREET_ID VARCHAR(32),
  HOUSE VARCHAR(10),
  LAT DOUBLE PRECISION,
  LON DOUBLE PRECISION
)
AS
BEGIN
  INSERT INTO /*PREFIX*/MAP_OBJECTS (STREET_ID,HOUSE,LAT,LON)
       VALUES (:STREET_ID,:HOUSE,:LAT,:LON);
END;

--

CREATE PROCEDURE /*PREFIX*/U_MAP_OBJECT
(
  STREET_ID VARCHAR(32),
  HOUSE VARCHAR(10),
  LAT DOUBLE PRECISION,
  LON DOUBLE PRECISION,
  OLD_STREET_ID VARCHAR(32),
  OLD_HOUSE VARCHAR(10)
)
AS
BEGIN
  UPDATE /*PREFIX*/MAP_OBJECTS
     SET STREET_ID=:STREET_ID,
         HOUSE=:HOUSE,
         LAT=:LAT,
         LON=:LON
   WHERE STREET_ID=:OLD_STREET_ID
     AND HOUSE=:OLD_HOUSE;
END;

--

CREATE PROCEDURE /*PREFIX*/D_MAP_OBJECT
(
  OLD_STREET_ID VARCHAR(32),
  OLD_HOUSE VARCHAR(10)
)
AS
BEGIN
  DELETE FROM /*PREFIX*/MAP_OBJECTS 
        WHERE STREET_ID=:OLD_STREET_ID
          AND HOUSE=:OLD_HOUSE;
END;

--

DECLARE EXTERNAL FUNCTION MAP_DISTANCE
    CSTRING(32767),
    DOUBLE PRECISION,
    DOUBLE PRECISION,
    DOUBLE PRECISION,
    DOUBLE PRECISION
RETURNS DOUBLE PRECISION BY VALUE
ENTRY_POINT 'MAP_DISTANCE' MODULE_NAME 'udfibaseingit.dll';


--

DROP PROCEDURE MAP_GET_ROUTE_DISTANCE

--

CREATE OR ALTER PROCEDURE GET_ROUTE_DISTANCE
(
  LAT1 DOUBLE PRECISION,
  LON1 DOUBLE PRECISION,
  LAT2 DOUBLE PRECISION,
  LON2 DOUBLE PRECISION
)
RETURNS (
  DISTANCE DOUBLE PRECISION)
AS
BEGIN
  DISTANCE=MAP_DISTANCE('C:\GWX6_DEMO\GWX\CITY_DEM\city_dem.chart',LAT1,LON1,LAT2,LON2);
END

--

CREATE OR ALTER PROCEDURE PR_ANOTHER_DRIVER (
  ORDER_ID VARCHAR(32),
  ACCOUNT_ID VARCHAR(32))
AS
DECLARE PHONE VARCHAR(100);
DECLARE DRIVER_ID VARCHAR(32);
DECLARE S VARCHAR(1000);
BEGIN

  SELECT DRIVER_ID
    FROM ORDERS
   WHERE ORDER_ID=:ORDER_ID
    INTO :DRIVER_ID;

  UPDATE ORDERS
     SET TYPE_PROCESS=0,
         DATE_END=CURRENT_TIMESTAMP,
         WHO_PROCESS_ID=:ACCOUNT_ID,
         DRIVER_ID=NULL,
         CAR_ID=NULL
   WHERE ORDER_ID=:ORDER_ID;

  IF (DRIVER_ID IS NOT NULL) THEN BEGIN

    SELECT PHONE
      FROM ACCOUNTS
     WHERE ACCOUNT_ID=:DRIVER_ID
      INTO :PHONE;

    SELECT CONST_VALUE FROM GET_CONST_VALUE('A82FFC060D399C82436CB3D669239B0B') INTO :S;

    IF (S IS NOT NULL) THEN BEGIN

      INSERT INTO OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,PRIORITY,LOCKED,DATE_BEGIN)
                        VALUES (GET_UNIQUE_ID(),:ACCOUNT_ID,:DRIVER_ID,CURRENT_TIMESTAMP,
                                :S,NULL,0,:PHONE,NULL,0,NULL,CURRENT_TIMESTAMP);
    END

  END

END

--

update RDB$RELATION_FIELDS set
RDB$NULL_FLAG = 1
where (RDB$FIELD_NAME = 'HOUSE') and
(RDB$RELATION_NAME = 'PARKS')

--

CREATE OR ALTER PROCEDURE PR_ARRIVAL_DRIVER (
  ORDER_ID VARCHAR(32),
  ACCOUNT_ID VARCHAR(32))
AS
DECLARE PHONE VARCHAR(100);
DECLARE DRIVER_ID VARCHAR(32);
DECLARE PARK_ID VARCHAR(32);
DECLARE PARK_STREET_ID VARCHAR(32);
DECLARE PARK_HOUSE VARCHAR(10);
DECLARE FROM_STREET_ID VARCHAR(32);
DECLARE FROM_HOUSE VARCHAR(10);
DECLARE RECEIPT_TYPE_ID VARCHAR(32);
DECLARE COST_RATE NUMERIC(15,2);
DECLARE COST_CASH NUMERIC(15,2);
DECLARE COLOR VARCHAR(100);
DECLARE BRAND VARCHAR(100);
DECLARE STATE_NUM VARCHAR(50);
DECLARE PREFIX VARCHAR(10);
DECLARE STREET VARCHAR(100);
DECLARE HOUSE VARCHAR(10);
DECLARE FLAT VARCHAR(10);
DECLARE PORCH VARCHAR(10);
DECLARE LOCALITY VARCHAR(100);
DECLARE CLIENT_ID VARCHAR(32);
DECLARE CALC_ID VARCHAR(32);
DECLARE SUM_CHARGE NUMERIC(15,2);
DECLARE SUM_RECEIPT NUMERIC(15,2);
DECLARE BALANCE NUMERIC(15,2);
DECLARE S VARCHAR(1000);
DECLARE S1 VARCHAR(1000);
DECLARE ADDRESS VARCHAR(1000);
DECLARE NUM INTEGER;
DECLARE CNT INTEGER;
DECLARE FLAG INTEGER;
DECLARE D TIMESTAMP;
DECLARE LAT1 DOUBLE PRECISION;
DECLARE LON1 DOUBLE PRECISION;
DECLARE LAT2 DOUBLE PRECISION;
DECLARE LON2 DOUBLE PRECISION;
DECLARE ROUTE_DISTANCE DOUBLE PRECISION;
DECLARE DISTANCE NUMERIC(15,2);
BEGIN

  SELECT O.PHONE, O.DRIVER_ID, O.PARK_ID,
         O.STREET_ID, O.HOUSE,
         O.COST_RATE, O.CLIENT_ID,
         C.COLOR, C.BRAND, C.STATE_NUM
    FROM ORDERS O
    LEFT JOIN DRIVERS D ON D.DRIVER_ID=O.DRIVER_ID
    LEFT JOIN CARS C ON C.CAR_ID=D.CAR_ID
   WHERE ORDER_ID=:ORDER_ID
    INTO :PHONE, :DRIVER_ID, :PARK_ID,
         :FROM_STREET_ID, :FROM_HOUSE,
         :COST_RATE, :CLIENT_ID,
         :COLOR, :BRAND, :STATE_NUM;

  UPDATE ORDERS
     SET DATE_BEGIN=CURRENT_TIMESTAMP
   WHERE ORDER_ID=:ORDER_ID;

  CALC_ID=NULL;

  IF (CLIENT_ID IS NOT NULL) THEN BEGIN

    SELECT CALC_ID
      FROM CLIENTS
     WHERE CLIENT_ID=:CLIENT_ID
      INTO :CALC_ID;

  END

  BALANCE=NULL;

  IF (CALC_ID IS NOT NULL) THEN BEGIN

    EXECUTE PROCEDURE GET_ACCOUNT_BALANCE(:CLIENT_ID)
     RETURNING_VALUES :SUM_CHARGE, :SUM_RECEIPT, :BALANCE;

  END

  FLAG=0;

  FOR SELECT STREET_ID, HOUSE
        FROM ROUTES
       WHERE ORDER_ID=:ORDER_ID
       ORDER BY PRIORITY
        INTO :STREET, :HOUSE DO BEGIN

    IF ((STREET IS NOT NULL) AND (HOUSE IS NOT NULL)) THEN BEGIN

    END ELSE BEGIN

      FLAG=1;

    END
  END

  COST_CASH=NULL;

  IF ((COST_RATE>0.0) AND (FLAG=0)) THEN BEGIN

    IF (BALANCE IS NOT NULL) THEN BEGIN

      IF (BALANCE>=COST_RATE) THEN
        COST_CASH=0.0;
      ELSE
        COST_CASH=COST_RATE-BALANCE;

    END

  END

  IF (SUBSTR(PHONE,1,3)='+79')  THEN BEGIN

    IF ((COST_RATE>0.0) AND (FLAG=0)) THEN BEGIN

      IF (COST_CASH IS NULL) THEN

        SELECT CONST_VALUE FROM GET_CONST_VALUE('8D9E6C9F4852AD8142205F027B2A5288') INTO :S;

      ELSE

        SELECT CONST_VALUE FROM GET_CONST_VALUE('9CA9F2761D2BBE974791906824C3C31A') INTO :S;

    END ELSE BEGIN

      SELECT CONST_VALUE FROM GET_CONST_VALUE('93EBB0171E37A0884313759C0DA1EB3D') INTO :S;

    END

    IF (S IS NOT NULL) THEN BEGIN

      S=REPLACE_STRING(S,'%COLOR',COLOR);
      S=REPLACE_STRING(S,'%BRAND',BRAND);
      S=REPLACE_STRING(S,'%STATE_NUM',STATE_NUM);
      S=REPLACE_STRING(S,'%COST_RATE',CAST(CAST(COST_RATE AS NUMERIC(15,0)) AS VARCHAR(30)));
      S=REPLACE_STRING(S,'%COST_CASH',CAST(CAST(COST_CASH AS NUMERIC(15,0)) AS VARCHAR(30)));

      INSERT INTO OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,PRIORITY,LOCKED,DATE_BEGIN)
                        VALUES (GET_UNIQUE_ID(),:ACCOUNT_ID,:CLIENT_ID,CURRENT_TIMESTAMP,
                                :S,NULL,0,:PHONE,NULL,0,NULL,CURRENT_TIMESTAMP);

    END

    SELECT CONST_VALUE FROM GET_CONST_VALUE('F4384929079999BB47A895BFCA5BB382') INTO :S;

    IF (S IS NOT NULL) THEN BEGIN

      INSERT INTO OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,PRIORITY,LOCKED,DATE_BEGIN)
                        VALUES (GET_UNIQUE_ID(),:ACCOUNT_ID,:CLIENT_ID,CURRENT_TIMESTAMP,
                                :S,NULL,0,:PHONE,NULL,0,NULL,CURRENT_TIMESTAMP);

    END

  END

  IF (DRIVER_ID IS NOT NULL) THEN BEGIN

    SELECT PHONE
      FROM ACCOUNTS
     WHERE ACCOUNT_ID=:DRIVER_ID
      INTO :PHONE;

    FLAG=0;
    NUM=0;

    SELECT COUNT(*)
      FROM ROUTES
     WHERE ORDER_ID=:ORDER_ID
      INTO :CNT;

    D=CURRENT_TIMESTAMP;

    FOR SELECT S.PREFIX, S.NAME, R.HOUSE, R.FLAT, R.PORCH, L.NAME
          FROM ROUTES R
          LEFT JOIN STREETS S ON S.STREET_ID=R.STREET_ID
          LEFT JOIN LOCALITIES L ON L.LOCALITY_ID=S.LOCALITY_ID
         WHERE R.ORDER_ID=:ORDER_ID
         ORDER BY R.PRIORITY
          INTO :PREFIX, :STREET, :HOUSE, :FLAT, :PORCH, :LOCALITY DO BEGIN

      ADDRESS='';
      S=NULL;

      IF ((STREET IS NOT NULL) AND (HOUSE IS NOT NULL)) THEN BEGIN

        IF (PREFIX IS NOT NULL) THEN
          ADDRESS=PREFIX||' ';

        IF (STREET IS NOT NULL) THEN
          ADDRESS=ADDRESS||STREET;

        IF (HOUSE IS NOT NULL) THEN
          ADDRESS=ADDRESS||' '||HOUSE;

        IF (FLAT IS NOT NULL) THEN
          ADDRESS=ADDRESS||'-'||FLAT;

        IF (PORCH IS NOT NULL) THEN
          ADDRESS=ADDRESS||' п.'||PORCH;

        IF ((LOCALITY IS NOT NULL) AND (LOCALITY<>'Красноярск')) THEN
          ADDRESS=ADDRESS||', '||LOCALITY;

        SELECT CONST_VALUE FROM GET_CONST_VALUE('92009DB6C3EAA9E74B80D333538FE40D') INTO :S;

      END ELSE BEGIN

        FLAG=1;

        SELECT CONST_VALUE FROM GET_CONST_VALUE('7ED5E8A8BBD9870A411517B54D9EB973') INTO :S;

      END

      IF (S IS NOT NULL) THEN BEGIN

        NUM=NUM+1;

        S=REPLACE_STRING(S,'%NUM',NUM);
        S=REPLACE_STRING(S,'%COUNT',CNT);
        S=REPLACE_STRING(S,'%ADDRESS',ADDRESS);

        IF (NUM=CNT) THEN BEGIN

          IF ((FLAG=0) AND (COST_RATE>0.0)) THEN BEGIN

            IF (COST_CASH IS NULL) THEN

              SELECT CONST_VALUE FROM GET_CONST_VALUE('9C8BC7D14DAEAE5C4DC8C1C91B20BCC2') INTO :S1;

            ELSE

              SELECT CONST_VALUE FROM GET_CONST_VALUE('A468782967A1A4D347F85F33D39E348A') INTO :S1;

          END ELSE

            SELECT CONST_VALUE FROM GET_CONST_VALUE('D3F68032AD999D004140A480A8AAF749') INTO :S1;

        END ELSE

          S1=S;


        IF (S1 IS NOT NULL) THEN BEGIN

          S1=REPLACE_STRING(S1,'%ADDRESS',S);
          S1=REPLACE_STRING(S1,'%COST_RATE',CAST(CAST(COST_RATE AS NUMERIC(15,0)) AS VARCHAR(30)));
          S1=REPLACE_STRING(S1,'%COST_CASH',CAST(CAST(COST_CASH AS NUMERIC(15,0)) AS VARCHAR(30)));

          INSERT INTO OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                    TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,PRIORITY,LOCKED,DATE_BEGIN)
                            VALUES (GET_UNIQUE_ID(),:ACCOUNT_ID,:DRIVER_ID,CURRENT_TIMESTAMP,
                                    :S1,NULL,0,:PHONE,NULL,2,NULL,:D);

          D=D+1*(1e0/24/60/60);

        END

      END

    END

    IF (PARK_ID IS NOT NULL) THEN BEGIN

      SELECT STREET_ID, HOUSE
        FROM PARKS
       WHERE PARK_ID=:PARK_ID
        INTO :PARK_STREET_ID, :PARK_HOUSE;

      IF ((PARK_STREET_ID IS NOT NULL) AND (PARK_HOUSE IS NOT NULL)) THEN BEGIN

        SELECT LAT, LON
          FROM MAP_OBJECTS
         WHERE STREET_ID=:PARK_STREET_ID
           AND HOUSE=:PARK_HOUSE
          INTO :LAT1, :LON1;

        IF ((LAT1 IS NOT NULL) AND (LON1 IS NOT NULL) AND
            (FROM_STREET_ID IS NOT NULL) AND (FROM_HOUSE IS NOT NULL)) THEN BEGIN

          SELECT LAT, LON
            FROM MAP_OBJECTS
           WHERE STREET_ID=:FROM_STREET_ID
             AND HOUSE=:FROM_HOUSE
            INTO :LAT2, :LON2;

          IF ((LAT2 IS NOT NULL) AND (LON2 IS NOT NULL)) THEN BEGIN

            EXECUTE PROCEDURE GET_ROUTE_DISTANCE(:LAT1,:LON1,:LAT2,:LON2)
             RETURNING_VALUES :ROUTE_DISTANCE;

            IF ((ROUTE_DISTANCE IS NOT NULL) AND (ROUTE_DISTANCE>0.0)) THEN BEGIN

              DISTANCE=CAST((ROUTE_DISTANCE/1000) AS NUMERIC(15,2));

              IF (DISTANCE>5.0) THEN BEGIN

                DISTANCE=DISTANCE-5.0;

                RECEIPT_TYPE_ID='2448E302595392064D9DF67BDD05C7DB'; /* Компенсация за прогон */

                SUM_RECEIPT=DISTANCE*2.5;

                INSERT INTO RECEIPTS (RECEIPT_ID,RECEIPT_TYPE_ID,ACCOUNT_ID,WHO_CREATE_ID,
                                      SUM_RECEIPT,DATE_RECEIPT,DATE_CREATE,DESCRIPTION)
                              VALUES (GET_UNIQUE_ID(),:RECEIPT_TYPE_ID,:DRIVER_ID,:ACCOUNT_ID,
                                      :SUM_RECEIPT,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL);

                SELECT CONST_VALUE FROM GET_CONST_VALUE('6905163E6105BE12488DAF7AAFA32810') INTO :S;

                IF (S IS NOT NULL) THEN BEGIN

                  S=REPLACE_STRING(S,'%DISTANCE',CAST(DISTANCE AS VARCHAR(30)));
                  S=REPLACE_STRING(S,'%SUM_RECEIPT',CAST(SUM_RECEIPT AS VARCHAR(30)));

                  INSERT INTO OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                            TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,PRIORITY,LOCKED,DATE_BEGIN)
                                    VALUES (GET_UNIQUE_ID(),:ACCOUNT_ID,:DRIVER_ID,CURRENT_TIMESTAMP,
                                            :S,NULL,0,:PHONE,NULL,2,NULL,:D);


                END

              END

            END

          END

        END

      END

    END

  END

END

--

CREATE OR ALTER PROCEDURE CREATE_ORDER_HISTORY (
  OLD_ORDER_ID VARCHAR(32),
  NEW_ORDER_ID VARCHAR(32),
  ACCOUNT_ID VARCHAR(32),
  ACTION_ID VARCHAR(32),
  RESULT_ID VARCHAR(32),
  TYPE_PROCESS INTEGER,
  DATE_BEGIN TIMESTAMP,
  WITH_DEPENDS INTEGER)
AS
BEGIN

  INSERT INTO ORDERS (ORDER_ID,PARENT_ID,ACTION_ID,RATE_ID,CAR_TYPE_ID,
                                WHO_ACCEPT_ID,STREET_ID,ZONE_ID,CAR_ID,
                                WHO_PROCESS_ID,RESULT_ID,PARK_ID,SOURCE_ID,DISCOUNT_ID,
                                DRIVER_ID,ORDER_NUM,PHONE,HOUSE,FLAT,PORCH,
                                DATE_ACCEPT,DATE_ARRIVAL,DATE_BEGIN,DATE_END,CUSTOMER,
                                DESCRIPTION,COST_RATE,COST_FACT,TYPE_ACCEPT,
                                TYPE_PROCESS,DATE_HISTORY,WHO_HISTORY_ID,BEFORE_PERIOD,
                                FINISHED,LOCKED,CLIENT_ID,COST_GROSS)
  SELECT :NEW_ORDER_ID,NULL,:ACTION_ID,RATE_ID,CAR_TYPE_ID,
         WHO_ACCEPT_ID,STREET_ID,ZONE_ID,CAR_ID,
         NULL,:RESULT_ID,PARK_ID,SOURCE_ID,DISCOUNT_ID,
         DRIVER_ID,ORDER_NUM,PHONE,HOUSE,FLAT,PORCH,
         DATE_ACCEPT,DATE_ARRIVAL,:DATE_BEGIN,NULL,CUSTOMER,
         DESCRIPTION,COST_RATE,COST_FACT,TYPE_ACCEPT,
         :TYPE_PROCESS,NULL,NULL,BEFORE_PERIOD,FINISHED,LOCKED,CLIENT_ID,COST_GROSS
    FROM ORDERS
   WHERE ORDER_ID=:OLD_ORDER_ID;

  IF (WITH_DEPENDS IS NOT NULL) THEN BEGIN

    INSERT INTO ROUTES (ROUTE_ID,ORDER_ID,ZONE_ID,STREET_ID,HOUSE,
                                  FLAT,PORCH,DISTANCE,COST,PERIOD,AMOUNT,PRIORITY)
    SELECT GET_UNIQUE_ID(),:NEW_ORDER_ID,ZONE_ID,STREET_ID,HOUSE,
           FLAT,PORCH,DISTANCE,COST,PERIOD,AMOUNT,PRIORITY
      FROM ROUTES
     WHERE ORDER_ID=:OLD_ORDER_ID;


    INSERT INTO ORDER_SERVICES (ORDER_ID,SERVICE_ID,COST,
                                DESCRIPTION,AMOUNT,PRIORITY)
    SELECT :NEW_ORDER_ID,SERVICE_ID,COST,
           DESCRIPTION,AMOUNT,PRIORITY
      FROM ORDER_SERVICES
     WHERE ORDER_ID=:OLD_ORDER_ID;

  END

  UPDATE ORDERS
     SET PARENT_ID=:NEW_ORDER_ID,
         DATE_HISTORY=CURRENT_TIMESTAMP,
         WHO_HISTORY_ID=:ACCOUNT_ID
   WHERE ORDER_ID=:OLD_ORDER_ID;

  UPDATE ORDERS
     SET PARENT_ID=:NEW_ORDER_ID
   WHERE PARENT_ID=:OLD_ORDER_ID;

  UPDATE IN_MESSAGES
     SET ORDER_ID=:NEW_ORDER_ID
   WHERE ORDER_ID=:OLD_ORDER_ID;

  UPDATE OUT_MESSAGES
     SET ORDER_ID=:NEW_ORDER_ID
   WHERE ORDER_ID=:OLD_ORDER_ID;

END

--

DROP PROCEDURE CODE_ORDER

--

CREATE OR ALTER PROCEDURE CODE_MAKE_ORDER
(
  ACCOUNT_ID VARCHAR(32),
  IN_MESSAGE_ID VARCHAR(32)
)
AS
DECLARE CONTACT VARCHAR(100);
DECLARE SENDER_ID VARCHAR(32);
DECLARE S VARCHAR(70);
DECLARE CNT INTEGER;
DECLARE CONST_VALUE VARCHAR(4000);
DECLARE ORDER_NUM VARCHAR(10);
DECLARE ACTION_ID VARCHAR(32);
DECLARE RATE_ID VARCHAR(32);
DECLARE CAR_TYPE_ID VARCHAR(32);
DECLARE CLIENT_ID VARCHAR(32);
DECLARE STREET_ID VARCHAR(32);
DECLARE HOUSE VARCHAR(10);
DECLARE FLAT VARCHAR(10);
DECLARE PORCH VARCHAR(10);
DECLARE ADDRESS_DESC VARCHAR(250);
DECLARE LOCKED INTEGER;
DECLARE ORDER_ID VARCHAR(32);
BEGIN
  SELECT CONTACT, SENDER_ID
    FROM IN_MESSAGES
   WHERE IN_MESSAGE_ID=:IN_MESSAGE_ID
    INTO :CONTACT, :SENDER_ID;

  SELECT COUNT(*)
    FROM BLACKS
   WHERE UPPER(PHONE)=UPPER(:CONTACT)
    INTO :CNT;

  IF ((CONTACT IS NOT NULL) AND (CNT=0)) THEN BEGIN

    SELECT LOCKED, CLIENT_ID, STREET_ID, HOUSE, FLAT, PORCH, ADDRESS_DESC
      FROM CLIENTS C
      JOIN ACCOUNTS A ON A.ACCOUNT_ID=C.CLIENT_ID
     WHERE C.CLIENT_ID=:SENDER_ID
      INTO :LOCKED, :CLIENT_ID, :STREET_ID, :HOUSE, :FLAT, :PORCH, :ADDRESS_DESC;

    IF ((CLIENT_ID IS NULL) OR ((CLIENT_ID IS NOT NULL) AND (LOCKED<>1))) THEN BEGIN

      SELECT CONST_VALUE FROM GET_CONST_VALUE('CB66FC06A78BB69D430EB7BD1AFA13FA') INTO :S;

      IF (S IS NOT NULL) THEN BEGIN

        STREET_ID='FA27330C653381FA4EDE11ECF0959DD6';  /* Красноярск - .*/
        HOUSE=NULL;
        FLAT=NULL;
        PORCH=NULL;
        ADDRESS_DESC=NULL;

        EXECUTE PROCEDURE GET_ORDER_NUM
         RETURNING_VALUES :ORDER_NUM;

        ACTION_ID='E019DBDE7D55BEC34D12A709EE3FEB0B'; /* Создание */

        RATE_ID=NULL;
        FOR SELECT RATE_ID
             FROM RATES
            ORDER BY PRIORITY
             INTO :RATE_ID DO BEGIN
          BREAK;
        END

        CAR_TYPE_ID=NULL;
        FOR SELECT CAR_TYPE_ID
              FROM CAR_TYPES
             ORDER BY PRIORITY
              INTO :CAR_TYPE_ID DO BEGIN
          BREAK;
        END

        IF ((RATE_ID IS NOT NULL) AND (CAR_TYPE_ID IS NOT NULL)) THEN BEGIN

          ORDER_ID=GET_UNIQUE_ID();

          INSERT INTO ORDERS (ORDER_ID,ACTION_ID,RATE_ID,CAR_TYPE_ID,WHO_ACCEPT_ID,
                              CLIENT_ID,STREET_ID,HOUSE,FLAT,PORCH,DESCRIPTION,
                              ORDER_NUM,PHONE,DATE_ACCEPT,DATE_ARRIVAL,TYPE_ACCEPT,
                              TYPE_PROCESS,BEFORE_PERIOD,DATE_BEGIN,FINISHED)
                      VALUES (:ORDER_ID,:ACTION_ID,:RATE_ID,:CAR_TYPE_ID,:ACCOUNT_ID,
                              :CLIENT_ID,:STREET_ID,:HOUSE,:FLAT,:PORCH,:ADDRESS_DESC,
                              :ORDER_NUM,:CONTACT,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,
                              1,30,CURRENT_TIMESTAMP,0);

          S=REPLACE_STRING(S,'%ORDER_NUM',ORDER_NUM);

          INSERT INTO OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                    TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,
                                    PRIORITY,LOCKED,DATE_BEGIN,ORDER_ID)
                            VALUES (GET_UNIQUE_ID(),:ACCOUNT_ID,:SENDER_ID,CURRENT_TIMESTAMP,
                                    :S,NULL,0,:CONTACT,NULL,
                                    1,NULL,CURRENT_TIMESTAMP,:ORDER_ID);

        END

      END

    END

  END

END

--

CREATE OR ALTER PROCEDURE CODE_PROCESS_ORDER
(
  ACCOUNT_ID VARCHAR(32),
  IN_MESSAGE_ID VARCHAR(32)
)
AS
DECLARE SENDER_ID VARCHAR(32);
DECLARE CODE VARCHAR(100);
DECLARE CNT INTEGER;
DECLARE SUM_CHARGE NUMERIC(15,2);
DECLARE SUM_RECEIPT NUMERIC(15,2);
DECLARE BALANCE NUMERIC(15,2);
DECLARE MIN_BALANCE NUMERIC(15,2);
DECLARE ORDER_ID VARCHAR(32);
BEGIN
  SELECT IM.SENDER_ID, CM.CODE
    FROM IN_MESSAGES IM
    LEFT JOIN CODE_MESSAGES CM ON CM.CODE_MESSAGE_ID=IM.CODE_MESSAGE_ID
   WHERE IN_MESSAGE_ID=:IN_MESSAGE_ID
    INTO :SENDER_ID, :CODE;

  IF ((SENDER_ID IS NOT NULL) AND (CODE IS NOT NULL)) THEN BEGIN

    SELECT COUNT(*)
      FROM DRIVERS D
      JOIN ACCOUNTS A ON A.ACCOUNT_ID=D.DRIVER_ID
     WHERE D.DRIVER_ID=:SENDER_ID
       AND A.LOCKED<>1
      INTO :CNT;

    IF (CNT>0) THEN BEGIN

      EXECUTE PROCEDURE GET_ACCOUNT_BALANCE(:SENDER_ID)
       RETURNING_VALUES :SUM_CHARGE, :SUM_RECEIPT, :BALANCE;

      SELECT MIN_BALANCE
        FROM DRIVERS
       WHERE DRIVER_ID=:SENDER_ID
        INTO :MIN_BALANCE;

      IF ((MIN_BALANCE IS NULL) OR ((MIN_BALANCE IS NOT NULL) AND (BALANCE>MIN_BALANCE))) THEN BEGIN

        ORDER_ID=NULL;

        FOR SELECT ORDER_ID
              FROM ORDERS
             WHERE DRIVER_ID=:SENDER_ID
               AND PARENT_ID IS NULL
               AND DATE_HISTORY IS NULL
               AND FINISHED<>1
             ORDER BY DATE_ACCEPT DESC
              INTO :ORDER_ID DO BEGIN
          BREAK;
        END

        IF (ORDER_ID IS NOT NULL) THEN BEGIN

          UPDATE IN_MESSAGES
             SET ORDER_ID=:ORDER_ID
           WHERE IN_MESSAGE_ID=:IN_MESSAGE_ID;

        END

      END

    END

  END
END

--

CREATE OR ALTER PROCEDURE DR_SEND_ORDER (
  ORDER_ID VARCHAR(32),
  ACTION_ID VARCHAR(32),
  RESULT_ID VARCHAR(32)) 
RETURNS (
  DETECTED INTEGER)
AS
  DECLARE CNT INTEGER;
  DECLARE DRIVER_ID VARCHAR(32);
  DECLARE DATE_BEGIN TIMESTAMP;
  DECLARE DATE_ACCEPT TIMESTAMP;
BEGIN
  DETECTED=0;

  SELECT DRIVER_ID, DATE_BEGIN, DATE_ACCEPT
    FROM ORDERS
   WHERE ORDER_ID=:ORDER_ID
    INTO :DRIVER_ID, :DATE_BEGIN, :DATE_ACCEPT;

  IF (DRIVER_ID IS NOT NULL) THEN BEGIN

    SELECT COUNT(*)
      FROM OUT_MESSAGES
     WHERE RECIPIENT_ID=:DRIVER_ID
       AND ORDER_ID=:ORDER_ID
       AND DESCRIPTION=:ACTION_ID
       AND TYPE_MESSAGE=0
       AND DATE_OUT IS NOT NULL
       AND DATE_CREATE>=:DATE_BEGIN
/*       AND DATE_CREATE>=:DATE_ACCEPT */
      INTO CNT;

    IF (CNT>0) THEN
      DETECTED=1;

  END

  SUSPEND;
END

--

CREATE OR ALTER PROCEDURE PR_SELECT_DRIVER (
  ORDER_ID VARCHAR(32),
  ACCOUNT_ID VARCHAR(32))
AS
DECLARE DRIVER_ID VARCHAR(32);
DECLARE CAR_ID VARCHAR(32);
DECLARE CNT INTEGER;
DECLARE S VARCHAR(1000);
DECLARE ADDRESS VARCHAR(1000);
DECLARE PREFIX VARCHAR(10);
DECLARE STREET VARCHAR(100);
DECLARE HOUSE VARCHAR(10);
DECLARE FLAT VARCHAR(10);
DECLARE PORCH VARCHAR(10);
DECLARE LOCALITY VARCHAR(100);
DECLARE PHONE VARCHAR(100);
DECLARE DATE_ACCEPT TIMESTAMP;
DECLARE DATE_ARRIVAL TIMESTAMP;
DECLARE DATE_BEGIN TIMESTAMP;
DECLARE BEFORE_PERIOD INTEGER;
DECLARE ACTION_ID VARCHAR(32);
DECLARE D TIMESTAMP;
DECLARE DESCRIPTION VARCHAR(250);
BEGIN

  SELECT O.DRIVER_ID,
         S.PREFIX, S.NAME, O.HOUSE, O.FLAT, O.PORCH, L.NAME,
         O.DATE_ACCEPT, O.DATE_ARRIVAL, O.BEFORE_PERIOD,
         O.ACTION_ID, O.DATE_BEGIN, O.DESCRIPTION
    FROM ORDERS O
    JOIN STREETS S ON S.STREET_ID=O.STREET_ID
    JOIN LOCALITIES L ON L.LOCALITY_ID=S.LOCALITY_ID
   WHERE O.ORDER_ID=:ORDER_ID
    INTO :DRIVER_ID,
         :PREFIX, :STREET, :HOUSE, :FLAT, :PORCH, :LOCALITY,
         :DATE_ACCEPT, :DATE_ARRIVAL, :BEFORE_PERIOD,
         :ACTION_ID, :DATE_BEGIN, :DESCRIPTION;

  IF (DRIVER_ID IS NOT NULL) THEN BEGIN

    CNT=0;

    SELECT COUNT(*)
      FROM OUT_MESSAGES
     WHERE RECIPIENT_ID=:DRIVER_ID
       AND ORDER_ID=:ORDER_ID
       AND DESCRIPTION=:ACTION_ID
       AND TYPE_MESSAGE=0
       AND DATE_OUT IS NULL
       AND DATE_CREATE>=:DATE_BEGIN
/*       AND DATE_CREATE>=:DATE_ACCEPT */
      INTO CNT;

    IF (CNT=0) THEN BEGIN

      SELECT D.CAR_ID, A.PHONE
        FROM DRIVERS D
        JOIN ACCOUNTS A ON A.ACCOUNT_ID=D.DRIVER_ID
       WHERE D.DRIVER_ID=:DRIVER_ID
        INTO :CAR_ID, :PHONE;

      D=CURRENT_TIMESTAMP;

      UPDATE ORDERS
         SET DRIVER_ID=:DRIVER_ID,
             CAR_ID=:CAR_ID,
             DATE_END=:D,
             WHO_PROCESS_ID=:ACCOUNT_ID
       WHERE ORDER_ID=:ORDER_ID;

      ADDRESS='';

      IF (PREFIX IS NOT NULL) THEN
        ADDRESS=PREFIX||' ';

      ADDRESS=ADDRESS||STREET||' '||HOUSE;

      IF (FLAT IS NOT NULL) THEN
        ADDRESS=ADDRESS||'-'||FLAT;

      IF (PORCH IS NOT NULL) THEN
        ADDRESS=ADDRESS||' п.'||PORCH;

      IF ((LOCALITY IS NOT NULL) AND (LOCALITY<>'Красноярск')) THEN
        ADDRESS=ADDRESS||', '||LOCALITY;

      IF (DATE_ACCEPT<DATE_ARRIVAL) THEN BEGIN

        IF ((DATE_ACCEPT+(BEFORE_PERIOD*(1e0/24/60)))<DATE_ARRIVAL) THEN BEGIN

          SELECT CONST_VALUE FROM GET_CONST_VALUE('2A773F389AD895B94010252F1DC6D3CC') INTO :S;

        END ELSE BEGIN

          SELECT CONST_VALUE FROM GET_CONST_VALUE('051BE1C8C28F9DB34EAA8DD46E0DA3B4') INTO :S;

        END

      END ELSE BEGIN

        SELECT CONST_VALUE FROM GET_CONST_VALUE('CD5055A23D04B51641F3211814253430') INTO :S;

      END

      IF (S IS NOT NULL) THEN BEGIN

        S=REPLACE_STRING(S,'%TIME',FORMAT_DATETIME('hh:nn',DATE_ARRIVAL));
        S=REPLACE_STRING(S,'%ADDRESS',ADDRESS);

        INSERT INTO OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                  TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,
                                  PRIORITY,LOCKED,DATE_BEGIN,ORDER_ID)
                          VALUES (GET_UNIQUE_ID(),:ACCOUNT_ID,:DRIVER_ID,:D,
                                  :S,NULL,0,:PHONE,:ACTION_ID,
                                  0,NULL,:D,:ORDER_ID);

        IF ((DESCRIPTION IS NOT NULL) AND (TRIM(DESCRIPTION)<>'')) THEN BEGIN

          S=DESCRIPTION;

          D=D+1*(1e0/24/60/60);

          INSERT INTO OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                    TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,
                                    PRIORITY,LOCKED,DATE_BEGIN,ORDER_ID)
                            VALUES (GET_UNIQUE_ID(),:ACCOUNT_ID,:DRIVER_ID,:D,
                                    :S,NULL,0,:PHONE,NULL,
                                    0,NULL,:D,:ORDER_ID);
        END

      END

    END

  END

END

--

CREATE OR ALTER PROCEDURE DR_CONFIRM_ORDER (
  ORDER_ID VARCHAR(32),
  ACTION_ID VARCHAR(32),
  RESULT_ID VARCHAR(32)) 
RETURNS (
  DETECTED INTEGER)
AS
DECLARE CNT INTEGER;
DECLARE DRIVER_ID VARCHAR(32);
DECLARE DATE_BEGIN TIMESTAMP;
DECLARE DATE_ACCEPT TIMESTAMP;
BEGIN
  DETECTED=0;

  SELECT DRIVER_ID, DATE_BEGIN, DATE_ACCEPT
    FROM ORDERS
   WHERE ORDER_ID=:ORDER_ID
    INTO :DRIVER_ID, :DATE_BEGIN, :DATE_ACCEPT;

  IF (DRIVER_ID IS NOT NULL) THEN BEGIN

    SELECT COUNT(*)
      FROM IN_MESSAGES IM
      JOIN CODE_MESSAGES CM ON CM.CODE_MESSAGE_ID=IM.CODE_MESSAGE_ID
     WHERE IM.SENDER_ID=:DRIVER_ID
       AND IM.ORDER_ID=:ORDER_ID
       AND IM.CODE_MESSAGE_ID='A87C64B41C87907A4B8C58C5F6A19E2F' /* Водитель принял заказ */
       AND IM.TYPE_MESSAGE=0
/*       AND IM.DATE_IN>:DATE_BEGIN */
       AND IM.DATE_IN>:DATE_ACCEPT
       AND CM.ENABLED=1
       AND IM.DESCRIPTION IS NULL
      INTO CNT;

    IF (CNT>0) THEN
      DETECTED=1;

  END

  SUSPEND;
END

--

CREATE OR ALTER PROCEDURE PR_CONFIRM_ORDER (
  ORDER_ID VARCHAR(32),
  ACCOUNT_ID VARCHAR(32))
AS
DECLARE PHONE VARCHAR(100);
DECLARE DRIVER_ID VARCHAR(32);
DECLARE PARK_ID VARCHAR(32);
DECLARE RECIPIENT_ID VARCHAR(32);
DECLARE S VARCHAR(1000);
BEGIN

  SELECT PHONE, DRIVER_ID, PARK_ID
    FROM ORDERS
   WHERE ORDER_ID=:ORDER_ID
    INTO :PHONE, :DRIVER_ID, :PARK_ID;

  UPDATE ORDERS
     SET DATE_BEGIN=CURRENT_TIMESTAMP
   WHERE ORDER_ID=:ORDER_ID;

  IF ((PHONE IS NOT NULL) AND (DRIVER_ID IS NOT NULL)) THEN BEGIN

    UPDATE IN_MESSAGES
       SET DESCRIPTION=:ORDER_ID
     WHERE ORDER_ID=:ORDER_ID
       AND CODE_MESSAGE_ID='A87C64B41C87907A4B8C58C5F6A19E2F' /* Водитель принял заказ */
       AND SENDER_ID=:DRIVER_ID
       AND DESCRIPTION IS NULL;

    UPDATE PARK_STATES
       SET DATE_OUT=CURRENT_TIMESTAMP
     WHERE DRIVER_ID=:DRIVER_ID
       AND PARK_ID=:PARK_ID
       AND DATE_OUT IS NULL;

    IF (SUBSTR(PHONE,1,3)='+79')  THEN BEGIN

      RECIPIENT_ID=NULL;

      FOR SELECT ACCOUNT_ID
            FROM ACCOUNTS
           WHERE PHONE=:PHONE
            INTO :RECIPIENT_ID DO BEGIN

        IF (RECIPIENT_ID IS NOT NULL) THEN
          BREAK;
      END

      SELECT CONST_VALUE FROM GET_CONST_VALUE('1C12AF5D5D57ACD045A724F8E3FF90ED') INTO :S;

      IF (S IS NOT NULL) THEN BEGIN

        INSERT INTO OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                  TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,
                                  PRIORITY,LOCKED,DATE_BEGIN,ORDER_ID)
                          VALUES (GET_UNIQUE_ID(),:ACCOUNT_ID,:RECIPIENT_ID,CURRENT_TIMESTAMP,
                                  :S,NULL,0,:PHONE,NULL,
                                  2,NULL,CURRENT_TIMESTAMP,:ORDER_ID);
      END
    END

    SELECT PHONE
      FROM ACCOUNTS
     WHERE ACCOUNT_ID=:DRIVER_ID
      INTO :PHONE;

    SELECT CONST_VALUE FROM GET_CONST_VALUE('723E98B898F89A8941B6CAAB092221AE') INTO :S;

    IF (S IS NOT NULL) THEN BEGIN

      RECIPIENT_ID=DRIVER_ID;

      INSERT INTO OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,
                                PRIORITY,LOCKED,DATE_BEGIN,ORDER_ID)
                        VALUES (GET_UNIQUE_ID(),:ACCOUNT_ID,:RECIPIENT_ID,CURRENT_TIMESTAMP,
                                :S,NULL,0,:PHONE,NULL,
                                2,NULL,CURRENT_TIMESTAMP,:ORDER_ID);
    END

  END

END

--

CREATE OR ALTER PROCEDURE DR_REFUSE_DRIVER (
  ORDER_ID VARCHAR(32),
  ACTION_ID VARCHAR(32),
  RESULT_ID VARCHAR(32)) 
RETURNS (
  DETECTED INTEGER)
AS
DECLARE CNT INTEGER;
DECLARE DRIVER_ID VARCHAR(32);
DECLARE DATE_BEGIN TIMESTAMP;
DECLARE DATE_ACCEPT TIMESTAMP;
BEGIN
  DETECTED=0;

  SELECT DRIVER_ID, DATE_BEGIN, DATE_ACCEPT
    FROM ORDERS
   WHERE ORDER_ID=:ORDER_ID
    INTO :DRIVER_ID, :DATE_BEGIN, :DATE_ACCEPT;

  IF (DRIVER_ID IS NOT NULL) THEN BEGIN

    SELECT COUNT(*)
      FROM IN_MESSAGES IM
      JOIN CODE_MESSAGES CM ON CM.CODE_MESSAGE_ID=IM.CODE_MESSAGE_ID
     WHERE IM.SENDER_ID=:DRIVER_ID
       AND IM.ORDER_ID=:ORDER_ID
       AND IM.CODE_MESSAGE_ID='2D41BEAE73EE84B04F4E6210C399BB63' /* Водитель отказалася от заказа */
       AND IM.TYPE_MESSAGE=0
/*       AND IM.DATE_IN>:DATE_BEGIN */
       AND IM.DATE_IN>:DATE_ACCEPT
       AND CM.ENABLED=1
       AND IM.DESCRIPTION IS NULL
      INTO CNT;

    IF (CNT>0) THEN
      DETECTED=1;

  END

  SUSPEND;
END

--

CREATE OR ALTER PROCEDURE PR_REFUSE_DRIVER_CONFIRM 
(
  ORDER_ID VARCHAR(32),
  ACCOUNT_ID VARCHAR(32))
AS
DECLARE DRIVER_ID VARCHAR(32);
DECLARE PARK_ID VARCHAR(32);
DECLARE PHONE VARCHAR(100);
DECLARE S VARCHAR(1000);
BEGIN

  SELECT DRIVER_ID
    FROM ORDERS
   WHERE ORDER_ID=:ORDER_ID
    INTO :DRIVER_ID;

  PARK_ID=NULL;

  FOR SELECT PARK_ID
        FROM ORDERS
       WHERE PARENT_ID=:ORDER_ID
       ORDER BY DATE_HISTORY
        INTO :PARK_ID DO BEGIN
    BREAK;
  END

  UPDATE ORDERS
     SET DATE_BEGIN=CURRENT_TIMESTAMP,
         PARK_ID=:PARK_ID,
         DRIVER_ID=NULL,
         CAR_ID=NULL
   WHERE ORDER_ID=:ORDER_ID;

  IF (DRIVER_ID IS NOT NULL) THEN BEGIN

    UPDATE IN_MESSAGES
       SET DESCRIPTION=:ORDER_ID
     WHERE ORDER_ID=:ORDER_ID
       AND CODE_MESSAGE_ID='2D41BEAE73EE84B04F4E6210C399BB63' /* Водитель отказалася от заказа */
       AND SENDER_ID=:DRIVER_ID
       AND DESCRIPTION IS NULL;

    UPDATE PARK_STATES
       SET DATE_OUT=CURRENT_TIMESTAMP
     WHERE DATE_OUT IS NULL
       AND DRIVER_ID=:DRIVER_ID;

    SELECT PHONE
      FROM ACCOUNTS
     WHERE ACCOUNT_ID=:DRIVER_ID
      INTO :PHONE;

    SELECT CONST_VALUE FROM GET_CONST_VALUE('14AB0F225BEFBBB14E0A5296BEB471A3') INTO :S;

    IF (S IS NOT NULL) THEN BEGIN

      INSERT INTO OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,
                                PRIORITY,LOCKED,DATE_BEGIN,ORDER_ID)
                        VALUES (GET_UNIQUE_ID(),:ACCOUNT_ID,:DRIVER_ID,CURRENT_TIMESTAMP,
                                :S,NULL,0,:PHONE,NULL,
                                2,NULL,CURRENT_TIMESTAMP,:ORDER_ID);
    END

  END

END

--

CREATE OR ALTER PROCEDURE DR_REFUSE_CLIENT
(
  ORDER_ID VARCHAR(32),
  ACTION_ID VARCHAR(32),
  RESULT_ID VARCHAR(32)) 
RETURNS (
  DETECTED INTEGER)
AS
DECLARE CNT INTEGER;
DECLARE DRIVER_ID VARCHAR(32);
DECLARE DATE_BEGIN TIMESTAMP;
DECLARE DATE_ACCEPT TIMESTAMP;
BEGIN
  DETECTED=0;

  SELECT DRIVER_ID, DATE_BEGIN, DATE_ACCEPT
    FROM ORDERS
   WHERE ORDER_ID=:ORDER_ID
    INTO :DRIVER_ID, :DATE_BEGIN, :DATE_ACCEPT;

  IF (DRIVER_ID IS NOT NULL) THEN BEGIN

    SELECT COUNT(*)
      FROM IN_MESSAGES IM
      JOIN CODE_MESSAGES CM ON CM.CODE_MESSAGE_ID=IM.CODE_MESSAGE_ID
     WHERE IM.SENDER_ID=:DRIVER_ID
       AND IM.ORDER_ID=:ORDER_ID
       AND IM.CODE_MESSAGE_ID='9273E67428E797614B153E4C799D6F48' /* Клиент отказался от заказа */
       AND IM.TYPE_MESSAGE=0
/*       AND IM.DATE_IN>:DATE_BEGIN */
       AND IM.DATE_IN>:DATE_ACCEPT
       AND CM.ENABLED=1
       AND IM.DESCRIPTION IS NULL
      INTO CNT;

    IF (CNT>0) THEN
      DETECTED=1;

  END

  SUSPEND;
END

--

CREATE OR ALTER PROCEDURE PR_REFUSE_CLIENT_CONFIRM (
  ORDER_ID VARCHAR(32),
  ACCOUNT_ID VARCHAR(32))
AS
DECLARE DRIVER_ID VARCHAR(32);
DECLARE PHONE VARCHAR(100);
DECLARE S VARCHAR(1000);
BEGIN

  SELECT DRIVER_ID
    FROM ORDERS
   WHERE ORDER_ID=:ORDER_ID
    INTO :DRIVER_ID;

  UPDATE ORDERS
     SET DATE_END=CURRENT_TIMESTAMP,
         WHO_PROCESS_ID=:ACCOUNT_ID,
         FINISHED=1
   WHERE ORDER_ID=:ORDER_ID;

  IF (DRIVER_ID IS NOT NULL) THEN BEGIN

    UPDATE IN_MESSAGES
       SET DESCRIPTION=:ORDER_ID
     WHERE ORDER_ID=:ORDER_ID
       AND CODE_MESSAGE_ID='9273E67428E797614B153E4C799D6F48' /* Клиент отказался от заказа */
       AND SENDER_ID=:DRIVER_ID
       AND DESCRIPTION IS NULL;

    SELECT PHONE
      FROM ACCOUNTS
     WHERE ACCOUNT_ID=:DRIVER_ID
      INTO :PHONE;

    SELECT CONST_VALUE FROM GET_CONST_VALUE('C40297F408B0AF3A45776489F11FC512') INTO :S;

    IF (S IS NOT NULL) THEN BEGIN

      INSERT INTO OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,
                                PRIORITY,LOCKED,DATE_BEGIN,ORDER_ID)
                        VALUES (GET_UNIQUE_ID(),:ACCOUNT_ID,:DRIVER_ID,CURRENT_TIMESTAMP,
                                :S,NULL,0,:PHONE,NULL,
                                0,NULL,CURRENT_TIMESTAMP,:ORDER_ID);
    END

  END

END

--

CREATE OR ALTER PROCEDURE PR_ANOTHER_DRIVER (
  ORDER_ID VARCHAR(32),
  ACCOUNT_ID VARCHAR(32))
AS
DECLARE PHONE VARCHAR(100);
DECLARE DRIVER_ID VARCHAR(32);
DECLARE PARK_ID VARCHAR(32);
DECLARE S VARCHAR(1000);
BEGIN

  SELECT DRIVER_ID
    FROM ORDERS
   WHERE ORDER_ID=:ORDER_ID
    INTO :DRIVER_ID;

  PARK_ID=NULL;

  FOR SELECT PARK_ID
        FROM ORDERS
       WHERE PARENT_ID=:ORDER_ID
       ORDER BY DATE_HISTORY
        INTO :PARK_ID DO BEGIN
    BREAK;
  END

  UPDATE ORDERS
     SET TYPE_PROCESS=0,
         DATE_END=CURRENT_TIMESTAMP,
         WHO_PROCESS_ID=:ACCOUNT_ID,
         PARK_ID=:PARK_ID,
         DRIVER_ID=NULL,
         CAR_ID=NULL
   WHERE ORDER_ID=:ORDER_ID;

  IF (DRIVER_ID IS NOT NULL) THEN BEGIN

    SELECT PHONE
      FROM ACCOUNTS
     WHERE ACCOUNT_ID=:DRIVER_ID
      INTO :PHONE;

    SELECT CONST_VALUE FROM GET_CONST_VALUE('A82FFC060D399C82436CB3D669239B0B') INTO :S;

    IF (S IS NOT NULL) THEN BEGIN

      INSERT INTO OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,
                                PRIORITY,LOCKED,DATE_BEGIN,ORDER_ID)
                        VALUES (GET_UNIQUE_ID(),:ACCOUNT_ID,:DRIVER_ID,CURRENT_TIMESTAMP,
                                :S,NULL,0,:PHONE,NULL,
                                0,NULL,CURRENT_TIMESTAMP,:ORDER_ID);
    END

  END

END

--

CREATE OR ALTER PROCEDURE PR_DOUBLE (
  ORDER_ID VARCHAR(32),
  ACCOUNT_ID VARCHAR(32))
AS
BEGIN

  UPDATE ORDERS
     SET DATE_END=CURRENT_TIMESTAMP,
         WHO_PROCESS_ID=:ACCOUNT_ID,
         FINISHED=1
   WHERE ORDER_ID=:ORDER_ID;

END

--

CREATE OR ALTER PROCEDURE DR_ARRIVAL_DRIVER
(
  ORDER_ID VARCHAR(32),
  ACTION_ID VARCHAR(32),
  RESULT_ID VARCHAR(32)) 
RETURNS (
  DETECTED INTEGER)
AS
DECLARE CNT INTEGER;
DECLARE DRIVER_ID VARCHAR(32);
DECLARE DATE_BEGIN TIMESTAMP;
DECLARE DATE_ACCEPT TIMESTAMP;
BEGIN
  DETECTED=0;

  SELECT DRIVER_ID, DATE_BEGIN, DATE_ACCEPT
    FROM ORDERS
   WHERE ORDER_ID=:ORDER_ID
    INTO :DRIVER_ID, :DATE_BEGIN, :DATE_ACCEPT;

  IF (DRIVER_ID IS NOT NULL) THEN BEGIN

    SELECT COUNT(*)
      FROM IN_MESSAGES IM
      JOIN CODE_MESSAGES CM ON CM.CODE_MESSAGE_ID=IM.CODE_MESSAGE_ID
     WHERE IM.SENDER_ID=:DRIVER_ID
       AND IM.ORDER_ID=:ORDER_ID
       AND IM.CODE_MESSAGE_ID='618A0B399123BEEA474944099929C541' /* Водитель прибыл */
       AND IM.TYPE_MESSAGE=0
/*       AND IM.DATE_IN>:DATE_BEGIN */
       AND IM.DATE_IN>:DATE_ACCEPT
       AND CM.ENABLED=1
       AND IM.DESCRIPTION IS NULL
      INTO CNT;

    IF (CNT>0) THEN
      DETECTED=1;

  END

  SUSPEND;
END

--

CREATE OR ALTER PROCEDURE PR_ARRIVAL_DRIVER (
  ORDER_ID VARCHAR(32),
  ACCOUNT_ID VARCHAR(32))
AS
DECLARE PHONE VARCHAR(100);
DECLARE DRIVER_ID VARCHAR(32);
DECLARE PARK_ID VARCHAR(32);
DECLARE PARK_STREET_ID VARCHAR(32);
DECLARE PARK_HOUSE VARCHAR(10);
DECLARE FROM_STREET_ID VARCHAR(32);
DECLARE FROM_HOUSE VARCHAR(10);
DECLARE RECEIPT_TYPE_ID VARCHAR(32);
DECLARE COST_RATE NUMERIC(15,2);
DECLARE COST_CASH NUMERIC(15,2);
DECLARE COLOR VARCHAR(100);
DECLARE BRAND VARCHAR(100);
DECLARE STATE_NUM VARCHAR(50);
DECLARE PREFIX VARCHAR(10);
DECLARE STREET VARCHAR(100);
DECLARE HOUSE VARCHAR(10);
DECLARE FLAT VARCHAR(10);
DECLARE PORCH VARCHAR(10);
DECLARE LOCALITY VARCHAR(100);
DECLARE CLIENT_ID VARCHAR(32);
DECLARE CALC_ID VARCHAR(32);
DECLARE SUM_CHARGE NUMERIC(15,2);
DECLARE SUM_RECEIPT NUMERIC(15,2);
DECLARE BALANCE NUMERIC(15,2);
DECLARE S VARCHAR(1000);
DECLARE S1 VARCHAR(1000);
DECLARE ADDRESS VARCHAR(1000);
DECLARE NUM INTEGER;
DECLARE CNT INTEGER;
DECLARE FLAG INTEGER;
DECLARE D TIMESTAMP;
DECLARE LAT1 DOUBLE PRECISION;
DECLARE LON1 DOUBLE PRECISION;
DECLARE LAT2 DOUBLE PRECISION;
DECLARE LON2 DOUBLE PRECISION;
DECLARE ROUTE_DISTANCE DOUBLE PRECISION;
DECLARE DISTANCE NUMERIC(15,2);
BEGIN

  SELECT O.PHONE, O.DRIVER_ID, O.PARK_ID,
         O.STREET_ID, O.HOUSE,
         O.COST_RATE, O.CLIENT_ID,
         C.COLOR, C.BRAND, C.STATE_NUM
    FROM ORDERS O
    LEFT JOIN DRIVERS D ON D.DRIVER_ID=O.DRIVER_ID
    LEFT JOIN CARS C ON C.CAR_ID=D.CAR_ID
   WHERE ORDER_ID=:ORDER_ID
    INTO :PHONE, :DRIVER_ID, :PARK_ID,
         :FROM_STREET_ID, :FROM_HOUSE,
         :COST_RATE, :CLIENT_ID,
         :COLOR, :BRAND, :STATE_NUM;

  UPDATE ORDERS
     SET DATE_BEGIN=CURRENT_TIMESTAMP
   WHERE ORDER_ID=:ORDER_ID;

  CALC_ID=NULL;

  IF (CLIENT_ID IS NOT NULL) THEN BEGIN

    SELECT CALC_ID
      FROM CLIENTS
     WHERE CLIENT_ID=:CLIENT_ID
      INTO :CALC_ID;

  END

  BALANCE=NULL;

  IF (CALC_ID IS NOT NULL) THEN BEGIN

    EXECUTE PROCEDURE GET_ACCOUNT_BALANCE(:CLIENT_ID)
     RETURNING_VALUES :SUM_CHARGE, :SUM_RECEIPT, :BALANCE;

  END

  FLAG=0;

  FOR SELECT STREET_ID, HOUSE
        FROM ROUTES
       WHERE ORDER_ID=:ORDER_ID
       ORDER BY PRIORITY
        INTO :STREET, :HOUSE DO BEGIN

    IF ((STREET IS NOT NULL) AND (HOUSE IS NOT NULL)) THEN BEGIN

    END ELSE BEGIN

      FLAG=1;

    END
  END

  COST_CASH=NULL;

  IF ((COST_RATE>0.0) AND (FLAG=0)) THEN BEGIN

    IF (BALANCE IS NOT NULL) THEN BEGIN

      IF (BALANCE>=COST_RATE) THEN
        COST_CASH=0.0;
      ELSE
        COST_CASH=COST_RATE-BALANCE;

    END

  END

  IF (SUBSTR(PHONE,1,3)='+79')  THEN BEGIN

    IF ((COST_RATE>0.0) AND (FLAG=0)) THEN BEGIN

      IF (COST_CASH IS NULL) THEN

        SELECT CONST_VALUE FROM GET_CONST_VALUE('8D9E6C9F4852AD8142205F027B2A5288') INTO :S;

      ELSE

        SELECT CONST_VALUE FROM GET_CONST_VALUE('9CA9F2761D2BBE974791906824C3C31A') INTO :S;

    END ELSE BEGIN

      SELECT CONST_VALUE FROM GET_CONST_VALUE('93EBB0171E37A0884313759C0DA1EB3D') INTO :S;

    END

    IF (S IS NOT NULL) THEN BEGIN

      S=REPLACE_STRING(S,'%COLOR',COLOR);
      S=REPLACE_STRING(S,'%BRAND',BRAND);
      S=REPLACE_STRING(S,'%STATE_NUM',STATE_NUM);
      S=REPLACE_STRING(S,'%COST_RATE',CAST(CAST(COST_RATE AS NUMERIC(15,0)) AS VARCHAR(30)));
      S=REPLACE_STRING(S,'%COST_CASH',CAST(CAST(COST_CASH AS NUMERIC(15,0)) AS VARCHAR(30)));

      INSERT INTO OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,
                                PRIORITY,LOCKED,DATE_BEGIN,ORDER_ID)
                        VALUES (GET_UNIQUE_ID(),:ACCOUNT_ID,:CLIENT_ID,CURRENT_TIMESTAMP,
                                :S,NULL,0,:PHONE,NULL,
                                0,NULL,CURRENT_TIMESTAMP,:ORDER_ID);

    END

    SELECT CONST_VALUE FROM GET_CONST_VALUE('F4384929079999BB47A895BFCA5BB382') INTO :S;

    IF (S IS NOT NULL) THEN BEGIN

      INSERT INTO OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,
                                PRIORITY,LOCKED,DATE_BEGIN,ORDER_ID)
                        VALUES (GET_UNIQUE_ID(),:ACCOUNT_ID,:CLIENT_ID,CURRENT_TIMESTAMP,
                                :S,NULL,0,:PHONE,NULL,
                                0,NULL,CURRENT_TIMESTAMP,:ORDER_ID);

    END

  END

  IF (DRIVER_ID IS NOT NULL) THEN BEGIN

    UPDATE IN_MESSAGES
       SET DESCRIPTION=:ORDER_ID
     WHERE ORDER_ID=:ORDER_ID
       AND CODE_MESSAGE_ID='618A0B399123BEEA474944099929C541' /* Водитель прибыл */
       AND SENDER_ID=:DRIVER_ID
       AND DESCRIPTION IS NULL;

    SELECT PHONE
      FROM ACCOUNTS
     WHERE ACCOUNT_ID=:DRIVER_ID
      INTO :PHONE;

    FLAG=0;
    NUM=0;

    SELECT COUNT(*)
      FROM ROUTES
     WHERE ORDER_ID=:ORDER_ID
      INTO :CNT;

    D=CURRENT_TIMESTAMP;

    FOR SELECT S.PREFIX, S.NAME, R.HOUSE, R.FLAT, R.PORCH, L.NAME
          FROM ROUTES R
          LEFT JOIN STREETS S ON S.STREET_ID=R.STREET_ID
          LEFT JOIN LOCALITIES L ON L.LOCALITY_ID=S.LOCALITY_ID
         WHERE R.ORDER_ID=:ORDER_ID
         ORDER BY R.PRIORITY
          INTO :PREFIX, :STREET, :HOUSE, :FLAT, :PORCH, :LOCALITY DO BEGIN

      ADDRESS='';
      S=NULL;

      IF ((STREET IS NOT NULL) AND (HOUSE IS NOT NULL)) THEN BEGIN

        IF (PREFIX IS NOT NULL) THEN
          ADDRESS=PREFIX||' ';

        IF (STREET IS NOT NULL) THEN
          ADDRESS=ADDRESS||STREET;

        IF (HOUSE IS NOT NULL) THEN
          ADDRESS=ADDRESS||' '||HOUSE;

        IF (FLAT IS NOT NULL) THEN
          ADDRESS=ADDRESS||'-'||FLAT;

        IF (PORCH IS NOT NULL) THEN
          ADDRESS=ADDRESS||' п.'||PORCH;

        IF ((LOCALITY IS NOT NULL) AND (LOCALITY<>'Красноярск')) THEN
          ADDRESS=ADDRESS||', '||LOCALITY;

        SELECT CONST_VALUE FROM GET_CONST_VALUE('92009DB6C3EAA9E74B80D333538FE40D') INTO :S;

      END ELSE BEGIN

        FLAG=1;

        SELECT CONST_VALUE FROM GET_CONST_VALUE('7ED5E8A8BBD9870A411517B54D9EB973') INTO :S;

      END

      IF (S IS NOT NULL) THEN BEGIN

        NUM=NUM+1;

        S=REPLACE_STRING(S,'%NUM',NUM);
        S=REPLACE_STRING(S,'%COUNT',CNT);
        S=REPLACE_STRING(S,'%ADDRESS',ADDRESS);

        IF (NUM=CNT) THEN BEGIN

          IF ((FLAG=0) AND (COST_RATE>0.0)) THEN BEGIN

            IF (COST_CASH IS NULL) THEN

              SELECT CONST_VALUE FROM GET_CONST_VALUE('9C8BC7D14DAEAE5C4DC8C1C91B20BCC2') INTO :S1;

            ELSE

              SELECT CONST_VALUE FROM GET_CONST_VALUE('A468782967A1A4D347F85F33D39E348A') INTO :S1;

          END ELSE

            SELECT CONST_VALUE FROM GET_CONST_VALUE('D3F68032AD999D004140A480A8AAF749') INTO :S1;

        END ELSE

          S1=S;


        IF (S1 IS NOT NULL) THEN BEGIN

          S1=REPLACE_STRING(S1,'%ADDRESS',S);
          S1=REPLACE_STRING(S1,'%COST_RATE',CAST(CAST(COST_RATE AS NUMERIC(15,0)) AS VARCHAR(30)));
          S1=REPLACE_STRING(S1,'%COST_CASH',CAST(CAST(COST_CASH AS NUMERIC(15,0)) AS VARCHAR(30)));

          INSERT INTO OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                    TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,
                                    PRIORITY,LOCKED,DATE_BEGIN,ORDER_ID)
                            VALUES (GET_UNIQUE_ID(),:ACCOUNT_ID,:DRIVER_ID,CURRENT_TIMESTAMP,
                                    :S1,NULL,0,:PHONE,NULL,
                                    2,NULL,:D,:ORDER_ID);

          D=D+1*(1e0/24/60/60);

        END

      END

    END

    IF (PARK_ID IS NOT NULL) THEN BEGIN

      SELECT STREET_ID, HOUSE
        FROM PARKS
       WHERE PARK_ID=:PARK_ID
        INTO :PARK_STREET_ID, :PARK_HOUSE;

      IF ((PARK_STREET_ID IS NOT NULL) AND (PARK_HOUSE IS NOT NULL)) THEN BEGIN

        SELECT LAT, LON
          FROM MAP_OBJECTS
         WHERE STREET_ID=:PARK_STREET_ID
           AND HOUSE=:PARK_HOUSE
          INTO :LAT1, :LON1;

        IF ((LAT1 IS NOT NULL) AND (LON1 IS NOT NULL) AND
            (FROM_STREET_ID IS NOT NULL) AND (FROM_HOUSE IS NOT NULL)) THEN BEGIN

          SELECT LAT, LON
            FROM MAP_OBJECTS
           WHERE STREET_ID=:FROM_STREET_ID
             AND HOUSE=:FROM_HOUSE
            INTO :LAT2, :LON2;

          IF ((LAT2 IS NOT NULL) AND (LON2 IS NOT NULL)) THEN BEGIN

            EXECUTE PROCEDURE GET_ROUTE_DISTANCE(:LAT1,:LON1,:LAT2,:LON2)
             RETURNING_VALUES :ROUTE_DISTANCE;

            IF ((ROUTE_DISTANCE IS NOT NULL) AND (ROUTE_DISTANCE>0.0)) THEN BEGIN

              DISTANCE=CAST((ROUTE_DISTANCE/1000) AS NUMERIC(15,2));

              IF (DISTANCE>5.0) THEN BEGIN

                DISTANCE=DISTANCE-5.0;

                RECEIPT_TYPE_ID='2448E302595392064D9DF67BDD05C7DB'; /* Компенсация за прогон */

                SUM_RECEIPT=DISTANCE*2.5;

                INSERT INTO RECEIPTS (RECEIPT_ID,RECEIPT_TYPE_ID,ACCOUNT_ID,WHO_CREATE_ID,
                                      SUM_RECEIPT,DATE_RECEIPT,DATE_CREATE,DESCRIPTION)
                              VALUES (GET_UNIQUE_ID(),:RECEIPT_TYPE_ID,:DRIVER_ID,:ACCOUNT_ID,
                                      :SUM_RECEIPT,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL);

                SELECT CONST_VALUE FROM GET_CONST_VALUE('6905163E6105BE12488DAF7AAFA32810') INTO :S;

                IF (S IS NOT NULL) THEN BEGIN

                  S=REPLACE_STRING(S,'%DISTANCE',CAST(DISTANCE AS VARCHAR(30)));
                  S=REPLACE_STRING(S,'%SUM_RECEIPT',CAST(SUM_RECEIPT AS VARCHAR(30)));

                  INSERT INTO OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                            TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,
                                            PRIORITY,LOCKED,DATE_BEGIN,ORDER_ID)
                                    VALUES (GET_UNIQUE_ID(),:ACCOUNT_ID,:DRIVER_ID,CURRENT_TIMESTAMP,
                                            :S,NULL,0,:PHONE,NULL,
                                            2,NULL,:D,:ORDER_ID);


                END

              END

            END

          END

        END

      END

    END

  END

END

--

CREATE OR ALTER PROCEDURE PR_REFUSE_DRIVER_DRIVE_OUT
(
  ORDER_ID VARCHAR(32),
  ACCOUNT_ID VARCHAR(32))
AS
DECLARE DRIVER_ID VARCHAR(32);
DECLARE PARK_ID VARCHAR(32);
DECLARE PHONE VARCHAR(100);
DECLARE S VARCHAR(1000);
BEGIN

  SELECT DRIVER_ID
    FROM ORDERS
   WHERE ORDER_ID=:ORDER_ID
    INTO :DRIVER_ID;

  PARK_ID=NULL;

  FOR SELECT PARK_ID
        FROM ORDERS
       WHERE PARENT_ID=:ORDER_ID
       ORDER BY DATE_HISTORY
        INTO :PARK_ID DO BEGIN
    BREAK;
  END

  UPDATE ORDERS
     SET DATE_BEGIN=CURRENT_TIMESTAMP,
         PARK_ID=:PARK_ID,
         DRIVER_ID=NULL,
         CAR_ID=NULL
   WHERE ORDER_ID=:ORDER_ID;

  IF (DRIVER_ID IS NOT NULL) THEN BEGIN

    UPDATE IN_MESSAGES
       SET DESCRIPTION=:ORDER_ID
     WHERE ORDER_ID=:ORDER_ID
       AND CODE_MESSAGE_ID='2D41BEAE73EE84B04F4E6210C399BB63' /* Водитель отказалася от заказа */
       AND SENDER_ID=:DRIVER_ID
       AND DESCRIPTION IS NULL;

    SELECT PHONE
      FROM ACCOUNTS
     WHERE ACCOUNT_ID=:DRIVER_ID
      INTO :PHONE;

    SELECT CONST_VALUE FROM GET_CONST_VALUE('7D5B6BED096187764ECE40FC7D5CB943') INTO :S;

    IF (S IS NOT NULL) THEN BEGIN

      INSERT INTO OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,
                                PRIORITY,LOCKED,DATE_BEGIN,ORDER_ID)
                        VALUES (GET_UNIQUE_ID(),:ACCOUNT_ID,:DRIVER_ID,CURRENT_TIMESTAMP,
                                :S,NULL,0,:PHONE,NULL,
                                2,NULL,CURRENT_TIMESTAMP,:ORDER_ID);
    END

  END

END

--

CREATE OR ALTER PROCEDURE PR_REFUSE_CLIENT_DRIVE_OUT 
(
  ORDER_ID VARCHAR(32),
  ACCOUNT_ID VARCHAR(32))
AS
DECLARE DRIVER_ID VARCHAR(32);
DECLARE PARK_ID VARCHAR(32);
DECLARE PARK_NAME VARCHAR(100);
DECLARE PHONE VARCHAR(100);
DECLARE PARK_STATE_ID VARCHAR(32);
DECLARE DATE_IN TIMESTAMP;
DECLARE S VARCHAR(1000);
BEGIN

  SELECT DRIVER_ID, PARK_ID
    FROM ORDERS
   WHERE ORDER_ID=:ORDER_ID
    INTO :DRIVER_ID, :PARK_ID;

  UPDATE ORDERS
     SET DATE_END=CURRENT_TIMESTAMP,
         WHO_PROCESS_ID=:ACCOUNT_ID,
         FINISHED=1
   WHERE ORDER_ID=:ORDER_ID;


  IF (DRIVER_ID IS NOT NULL) THEN BEGIN

    UPDATE IN_MESSAGES
       SET DESCRIPTION=:ORDER_ID
     WHERE ORDER_ID=:ORDER_ID
       AND CODE_MESSAGE_ID='9273E67428E797614B153E4C799D6F48' /* Клиент отказался от заказа */
       AND SENDER_ID=:DRIVER_ID
       AND DESCRIPTION IS NULL;

    IF (PARK_ID IS NOT NULL) THEN BEGIN

      FOR SELECT PS.PARK_STATE_ID, P.NAME, PS.DATE_IN
            FROM PARK_STATES PS
            JOIN PARKS P ON P.PARK_ID=PS.PARK_ID
           WHERE PS.PARK_ID=:PARK_ID
             AND PS.DATE_OUT IS NULL
           ORDER BY PS.DATE_IN
            INTO :PARK_STATE_ID, :PARK_NAME, :DATE_IN DO BEGIN

        DATE_IN=DATE_IN-1*(1e0/24/60/60);

        INSERT INTO PARK_STATES (PARK_STATE_ID,DRIVER_ID,PARK_ID,DATE_IN,DATE_OUT)
                         VALUES (GET_UNIQUE_ID(),:DRIVER_ID,:PARK_ID,:DATE_IN,NULL);

        BREAK;
      END

      IF (PARK_NAME IS NULL) THEN BEGIN

        INSERT INTO PARK_STATES (PARK_STATE_ID,DRIVER_ID,PARK_ID,DATE_IN,DATE_OUT)
                         VALUES (GET_UNIQUE_ID(),:DRIVER_ID,:PARK_ID,CURRENT_TIMESTAMP,NULL);

        SELECT NAME
          FROM PARKS
         WHERE PARK_ID=:PARK_ID
          INTO :PARK_NAME;

      END

      SELECT PHONE
        FROM ACCOUNTS
       WHERE ACCOUNT_ID=:DRIVER_ID
        INTO :PHONE;

      SELECT CONST_VALUE FROM GET_CONST_VALUE('7604B1762FDB97EC406174FB54FA13EA') INTO :S;

      IF (S IS NOT NULL) THEN BEGIN

        S=REPLACE_STRING(S,'%PARK_NAME',PARK_NAME);

        INSERT INTO OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                  TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,
                                  PRIORITY,LOCKED,DATE_BEGIN,ORDER_ID)
                          VALUES (GET_UNIQUE_ID(),:ACCOUNT_ID,:DRIVER_ID,CURRENT_TIMESTAMP,
                                  :S,NULL,0,:PHONE,NULL,
                                  0,NULL,CURRENT_TIMESTAMP,:ORDER_ID);
      END

    END

  END

END

--

CREATE OR ALTER PROCEDURE PR_REFUSE_CLIENT_COME_OUT
(
  ORDER_ID VARCHAR(32),
  ACCOUNT_ID VARCHAR(32))
AS
DECLARE DRIVER_ID VARCHAR(32);
DECLARE PARK_ID VARCHAR(32);
DECLARE PARK_NAME VARCHAR(100);
DECLARE PHONE VARCHAR(100);
DECLARE PARK_STATE_ID VARCHAR(32);
DECLARE DATE_IN TIMESTAMP;
DECLARE S VARCHAR(1000);
BEGIN

  SELECT DRIVER_ID, PARK_ID
    FROM ORDERS
   WHERE ORDER_ID=:ORDER_ID
    INTO :DRIVER_ID, :PARK_ID;

  UPDATE ORDERS
     SET DATE_END=CURRENT_TIMESTAMP,
         WHO_PROCESS_ID=:ACCOUNT_ID,
         FINISHED=1
   WHERE ORDER_ID=:ORDER_ID;

  IF (DRIVER_ID IS NOT NULL) THEN BEGIN

    UPDATE IN_MESSAGES
       SET DESCRIPTION=:ORDER_ID
     WHERE ORDER_ID=:ORDER_ID
       AND CODE_MESSAGE_ID='9273E67428E797614B153E4C799D6F48' /* Клиент отказался от заказа */
       AND SENDER_ID=:DRIVER_ID
       AND DESCRIPTION IS NULL;

    IF (PARK_ID IS NOT NULL) THEN BEGIN

      FOR SELECT PS.PARK_STATE_ID, P.NAME, PS.DATE_IN
            FROM PARK_STATES PS
            JOIN PARKS P ON P.PARK_ID=PS.PARK_ID
           WHERE PS.PARK_ID=:PARK_ID
             AND PS.DATE_OUT IS NULL
           ORDER BY PS.DATE_IN
            INTO :PARK_STATE_ID, :PARK_NAME, :DATE_IN DO BEGIN

        DATE_IN=DATE_IN-1*(1e0/24/60/60);

        INSERT INTO PARK_STATES (PARK_STATE_ID,DRIVER_ID,PARK_ID,DATE_IN,DATE_OUT)
                         VALUES (GET_UNIQUE_ID(),:DRIVER_ID,:PARK_ID,:DATE_IN,NULL);

        BREAK;
      END

      IF (PARK_NAME IS NULL) THEN BEGIN

        INSERT INTO PARK_STATES (PARK_STATE_ID,DRIVER_ID,PARK_ID,DATE_IN,DATE_OUT)
                         VALUES (GET_UNIQUE_ID(),:DRIVER_ID,:PARK_ID,CURRENT_TIMESTAMP,NULL);

        SELECT NAME
          FROM PARKS
         WHERE PARK_ID=:PARK_ID
          INTO :PARK_NAME;

      END

      SELECT PHONE
        FROM ACCOUNTS
       WHERE ACCOUNT_ID=:DRIVER_ID
        INTO :PHONE;

      SELECT CONST_VALUE FROM GET_CONST_VALUE('13D70B96F52BBE8D4E115CCC194F3B10') INTO :S;

      IF (S IS NOT NULL) THEN BEGIN

        S=REPLACE_STRING(S,'%PARK_NAME',PARK_NAME);

        INSERT INTO OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                  TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,
                                  PRIORITY,LOCKED,DATE_BEGIN,ORDER_ID)
                          VALUES (GET_UNIQUE_ID(),:ACCOUNT_ID,:DRIVER_ID,CURRENT_TIMESTAMP,
                                  :S,NULL,0,:PHONE,NULL,
                                  2,NULL,CURRENT_TIMESTAMP,:ORDER_ID);
      END

    END

  END

END

--

CREATE OR ALTER PROCEDURE PR_REFUSE_DRIVER_COME_OUT (
  ORDER_ID VARCHAR(32),
  ACCOUNT_ID VARCHAR(32))
AS
DECLARE DRIVER_ID VARCHAR(32);
DECLARE PHONE VARCHAR(100);
DECLARE S VARCHAR(1000);
BEGIN

  SELECT DRIVER_ID
    FROM ORDERS
   WHERE ORDER_ID=:ORDER_ID
    INTO :DRIVER_ID;

  UPDATE ORDERS
     SET TYPE_PROCESS=1,
         DATE_END=CURRENT_TIMESTAMP,
         WHO_PROCESS_ID=:ACCOUNT_ID
   WHERE ORDER_ID=:ORDER_ID;

  IF (DRIVER_ID IS NOT NULL) THEN BEGIN

    UPDATE IN_MESSAGES
       SET DESCRIPTION=:ORDER_ID
     WHERE ORDER_ID=:ORDER_ID
       AND CODE_MESSAGE_ID='2D41BEAE73EE84B04F4E6210C399BB63' /* Водитель отказалася от заказа */
       AND SENDER_ID=:DRIVER_ID
       AND DESCRIPTION IS NULL;

    SELECT PHONE
      FROM ACCOUNTS
     WHERE ACCOUNT_ID=:DRIVER_ID
      INTO :PHONE;

    SELECT CONST_VALUE FROM GET_CONST_VALUE('2C0BBC7EF7418D934C32D8969D7F2D8C') INTO :S;

    IF (S IS NOT NULL) THEN BEGIN

      INSERT INTO OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,
                                PRIORITY,LOCKED,DATE_BEGIN,ORDER_ID)
                        VALUES (GET_UNIQUE_ID(),:ACCOUNT_ID,:DRIVER_ID,CURRENT_TIMESTAMP,
                                :S,NULL,0,:PHONE,NULL,
                                2,NULL,CURRENT_TIMESTAMP,:ORDER_ID);
    END

  END

END

--

CREATE OR ALTER PROCEDURE DR_CLIENT_IN_CAR (
  ORDER_ID VARCHAR(32),
  ACTION_ID VARCHAR(32),
  RESULT_ID VARCHAR(32)) 
RETURNS (
  DETECTED INTEGER)
AS
DECLARE CNT INTEGER;
DECLARE DRIVER_ID VARCHAR(32);
DECLARE DATE_BEGIN TIMESTAMP;
DECLARE DATE_ACCEPT TIMESTAMP;
BEGIN
  DETECTED=0;

  SELECT DRIVER_ID, DATE_BEGIN, DATE_ACCEPT
    FROM ORDERS
   WHERE ORDER_ID=:ORDER_ID
    INTO :DRIVER_ID, :DATE_BEGIN, :DATE_ACCEPT;

  IF (DRIVER_ID IS NOT NULL) THEN BEGIN

    SELECT COUNT(*)
      FROM IN_MESSAGES IM
      JOIN CODE_MESSAGES CM ON CM.CODE_MESSAGE_ID=IM.CODE_MESSAGE_ID
     WHERE IM.SENDER_ID=:DRIVER_ID
       AND IM.ORDER_ID=:ORDER_ID
       AND IM.CODE_MESSAGE_ID='3FD0D3ABD5E0B697483FF8520EDDBD6D' /* Клиент сел в машину */
       AND IM.TYPE_MESSAGE=0
/*       AND IM.DATE_IN>:DATE_BEGIN */
       AND IM.DATE_IN>:DATE_ACCEPT
       AND CM.ENABLED=1
       AND IM.DESCRIPTION IS NULL
      INTO CNT;

    IF (CNT>0) THEN
      DETECTED=1;

  END

  SUSPEND;
END

--

CREATE OR ALTER PROCEDURE PR_CLIENT_IN_CAR (
  ORDER_ID VARCHAR(32),
  ACCOUNT_ID VARCHAR(32))
AS
DECLARE PHONE VARCHAR(100);
DECLARE DRIVER_ID VARCHAR(32);
DECLARE S VARCHAR(1000);
BEGIN

  SELECT DRIVER_ID
    FROM ORDERS
   WHERE ORDER_ID=:ORDER_ID
    INTO :DRIVER_ID;

  UPDATE ORDERS
     SET DATE_BEGIN=CURRENT_TIMESTAMP
   WHERE ORDER_ID=:ORDER_ID;

  IF (DRIVER_ID IS NOT NULL) THEN BEGIN

    UPDATE IN_MESSAGES
       SET DESCRIPTION=:ORDER_ID
     WHERE ORDER_ID=:ORDER_ID
       AND CODE_MESSAGE_ID='3FD0D3ABD5E0B697483FF8520EDDBD6D' /* Клиент сел в машину */
       AND SENDER_ID=:DRIVER_ID
       AND DESCRIPTION IS NULL;

    SELECT PHONE
      FROM ACCOUNTS
     WHERE ACCOUNT_ID=:DRIVER_ID
      INTO :PHONE;

    SELECT CONST_VALUE FROM GET_CONST_VALUE('620D357394B89B18454EB58DD5CE9F19') INTO :S;

    IF (S IS NOT NULL) THEN BEGIN

      INSERT INTO OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,
                                PRIORITY,LOCKED,DATE_BEGIN,ORDER_ID)
                        VALUES (GET_UNIQUE_ID(),:ACCOUNT_ID,:DRIVER_ID,CURRENT_TIMESTAMP,
                                :S,NULL,0,:PHONE,NULL,
                                2,NULL,CURRENT_TIMESTAMP,:ORDER_ID);
    END

  END

END

--

CREATE OR ALTER PROCEDURE DR_PARTLY_CALC
(
  ORDER_ID VARCHAR(32),
  ACTION_ID VARCHAR(32),
  RESULT_ID VARCHAR(32)) 
RETURNS (
  DETECTED INTEGER)
AS
DECLARE CNT INTEGER;
DECLARE DRIVER_ID VARCHAR(32);
DECLARE DATE_BEGIN TIMESTAMP;
DECLARE DATE_ACCEPT TIMESTAMP;
BEGIN
  DETECTED=0;

  SELECT DRIVER_ID, DATE_BEGIN, DATE_ACCEPT
    FROM ORDERS
   WHERE ORDER_ID=:ORDER_ID
    INTO :DRIVER_ID, :DATE_BEGIN, :DATE_ACCEPT;

  IF (DRIVER_ID IS NOT NULL) THEN BEGIN

    SELECT COUNT(*)
      FROM IN_MESSAGES IM
      JOIN CODE_MESSAGES CM ON CM.CODE_MESSAGE_ID=IM.CODE_MESSAGE_ID
     WHERE IM.SENDER_ID=:DRIVER_ID
       AND IM.ORDER_ID=:ORDER_ID
       AND IM.CODE_MESSAGE_ID='E0D06394F6BC81BA481D1F94D12B3FB4' /* Клиент отказался платить */
       AND IM.TYPE_MESSAGE=0
/*       AND IM.DATE_IN>:DATE_BEGIN */
       AND IM.DATE_IN>:DATE_ACCEPT
       AND CM.ENABLED=1
       AND IM.DESCRIPTION IS NULL
      INTO CNT;

    IF (CNT>0) THEN
      DETECTED=1;

  END

  SUSPEND;
END

--

CREATE OR ALTER PROCEDURE PR_PARTY_CALC
(
  ORDER_ID VARCHAR(32),
  ACCOUNT_ID VARCHAR(32))
AS
DECLARE PHONE VARCHAR(100);
DECLARE DRIVER_ID VARCHAR(32);
DECLARE S VARCHAR(1000);
BEGIN

  SELECT DRIVER_ID
    FROM ORDERS
   WHERE ORDER_ID=:ORDER_ID
    INTO :DRIVER_ID;

  UPDATE ORDERS
     SET TYPE_PROCESS=1,
         DATE_END=CURRENT_TIMESTAMP,
         WHO_PROCESS_ID=:ACCOUNT_ID
   WHERE ORDER_ID=:ORDER_ID;

  IF (DRIVER_ID IS NOT NULL) THEN BEGIN

    UPDATE IN_MESSAGES
       SET DESCRIPTION=:ORDER_ID
     WHERE ORDER_ID=:ORDER_ID
       AND CODE_MESSAGE_ID='E0D06394F6BC81BA481D1F94D12B3FB4' /* Клиент отказался платить */
       AND SENDER_ID=:DRIVER_ID
       AND DESCRIPTION IS NULL;

    SELECT PHONE
      FROM ACCOUNTS
     WHERE ACCOUNT_ID=:DRIVER_ID
      INTO :PHONE;

    SELECT CONST_VALUE FROM GET_CONST_VALUE('8B477D56F777966345EBC1130AF01C55') INTO :S;

    IF (S IS NOT NULL) THEN BEGIN

      INSERT INTO OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,
                                PRIORITY,LOCKED,DATE_BEGIN,ORDER_ID)
                        VALUES (GET_UNIQUE_ID(),:ACCOUNT_ID,:DRIVER_ID,CURRENT_TIMESTAMP,
                                :S,NULL,0,:PHONE,NULL,
                                2,NULL,CURRENT_TIMESTAMP,:ORDER_ID);
    END

  END

END

--

CREATE OR ALTER PROCEDURE DR_CHANGE_ROUTE (
  ORDER_ID VARCHAR(32),
  ACTION_ID VARCHAR(32),
  RESULT_ID VARCHAR(32)) 
RETURNS (
  DETECTED INTEGER)
AS
DECLARE CNT INTEGER;
DECLARE DRIVER_ID VARCHAR(32);
DECLARE DATE_BEGIN TIMESTAMP;
DECLARE DATE_ACCEPT TIMESTAMP;
BEGIN
  DETECTED=0;

  SELECT DRIVER_ID, DATE_BEGIN, DATE_ACCEPT
    FROM ORDERS
   WHERE ORDER_ID=:ORDER_ID
    INTO :DRIVER_ID, :DATE_BEGIN, :DATE_ACCEPT;

  IF (DRIVER_ID IS NOT NULL) THEN BEGIN

    SELECT COUNT(*)
      FROM IN_MESSAGES IM
      JOIN CODE_MESSAGES CM ON CM.CODE_MESSAGE_ID=IM.CODE_MESSAGE_ID
     WHERE IM.SENDER_ID=:DRIVER_ID
       AND IM.ORDER_ID=:ORDER_ID
       AND IM.CODE_MESSAGE_ID='F42D57842950B923481A9B2D02B925CB' /* Клиент хочет сменить маршрут */
       AND IM.TYPE_MESSAGE=0
/*       AND IM.DATE_IN>:DATE_BEGIN */
       AND IM.DATE_IN>:DATE_ACCEPT
       AND CM.ENABLED=1
       AND IM.DESCRIPTION IS NULL
      INTO CNT;

    IF (CNT>0) THEN
      DETECTED=1;

  END

  SUSPEND;
END

--

CREATE OR ALTER PROCEDURE PR_CHANGE_ROUTE (
  ORDER_ID VARCHAR(32),
  ACCOUNT_ID VARCHAR(32))
AS
DECLARE PHONE VARCHAR(100);
DECLARE DRIVER_ID VARCHAR(32);
DECLARE S VARCHAR(1000);
BEGIN

  SELECT DRIVER_ID
    FROM ORDERS
   WHERE ORDER_ID=:ORDER_ID
    INTO :DRIVER_ID;

  UPDATE ORDERS
     SET TYPE_PROCESS=1,
         DATE_END=CURRENT_TIMESTAMP,
         WHO_PROCESS_ID=:ACCOUNT_ID
   WHERE ORDER_ID=:ORDER_ID;

  IF (DRIVER_ID IS NOT NULL) THEN BEGIN

    UPDATE IN_MESSAGES
       SET DESCRIPTION=:ORDER_ID
     WHERE ORDER_ID=:ORDER_ID
       AND CODE_MESSAGE_ID='F42D57842950B923481A9B2D02B925CB' /* Клиент хочет сменить маршрут */
       AND SENDER_ID=:DRIVER_ID
       AND DESCRIPTION IS NULL;

    SELECT PHONE
      FROM ACCOUNTS
     WHERE ACCOUNT_ID=:DRIVER_ID
      INTO :PHONE;

    SELECT CONST_VALUE FROM GET_CONST_VALUE('2A7354AFB1FDB1D041F8FB2D06FFBC70') INTO :S;

    IF (S IS NOT NULL) THEN BEGIN

      INSERT INTO OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,
                                PRIORITY,LOCKED,DATE_BEGIN,ORDER_ID)
                        VALUES (GET_UNIQUE_ID(),:ACCOUNT_ID,:DRIVER_ID,CURRENT_TIMESTAMP,
                                :S,NULL,0,:PHONE,NULL,
                                2,NULL,CURRENT_TIMESTAMP,:ORDER_ID);
    END

  END

END

--

CREATE OR ALTER PROCEDURE TRY_PARK_IN (
  ORDER_ID VARCHAR(32),
  ACCOUNT_ID VARCHAR(32),
  DRIVER_ID VARCHAR(32),
  CODE VARCHAR(100))
AS
DECLARE S VARCHAR(1000);
DECLARE PHONE VARCHAR(100);
DECLARE CNT INTEGER;
DECLARE SUM_CHARGE NUMERIC(15,2);
DECLARE SUM_RECEIPT NUMERIC(15,2);
DECLARE BALANCE NUMERIC(15,2);
DECLARE MIN_BALANCE NUMERIC(15,2);
DECLARE D TIMESTAMP;
DECLARE PARK_ID VARCHAR(32);
DECLARE PARK_NAME VARCHAR(100);
DECLARE PARK_DESCRIPTION VARCHAR(250);
DECLARE PRIORITY INTEGER;
BEGIN

  IF ((DRIVER_ID IS NOT NULL) AND (CODE IS NOT NULL)) THEN BEGIN

    SELECT A.PHONE
      FROM DRIVERS D
      JOIN ACCOUNTS A ON A.ACCOUNT_ID=D.DRIVER_ID
     WHERE D.DRIVER_ID=:DRIVER_ID
       AND A.LOCKED<>1
      INTO :PHONE;

    IF (PHONE IS NOT NULL) THEN BEGIN

      EXECUTE PROCEDURE GET_ACCOUNT_BALANCE(:DRIVER_ID)
       RETURNING_VALUES :SUM_CHARGE, :SUM_RECEIPT, :BALANCE;

      SELECT MIN_BALANCE
        FROM DRIVERS
       WHERE DRIVER_ID=:DRIVER_ID
        INTO :MIN_BALANCE;

      IF ((MIN_BALANCE IS NULL) OR ((MIN_BALANCE IS NOT NULL) AND (BALANCE>MIN_BALANCE))) THEN BEGIN

        SELECT COUNT(*)
          FROM ORDERS
         WHERE DRIVER_ID=:DRIVER_ID
           AND PARENT_ID IS NULL
           AND DATE_HISTORY IS NULL
           AND FINISHED<>1
          INTO :CNT;

        IF (CNT>0) THEN BEGIN

          SELECT CONST_VALUE FROM GET_CONST_VALUE('764B2BA8498AB18345852AA2FE39F4D9') INTO :S;

          IF (S IS NOT NULL) THEN BEGIN

            INSERT INTO OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                      TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,
                                      PRIORITY,LOCKED,DATE_BEGIN,ORDER_ID)
                              VALUES (GET_UNIQUE_ID(),:ACCOUNT_ID,:DRIVER_ID,CURRENT_TIMESTAMP,
                                      :S,NULL,0,:PHONE,NULL,
                                      2,NULL,CURRENT_TIMESTAMP,:ORDER_ID);
          END

        END ELSE BEGIN

          UPDATE PARK_STATES
             SET DATE_OUT=CURRENT_TIMESTAMP
           WHERE DRIVER_ID=:DRIVER_ID
             AND DATE_OUT IS NULL;

          SELECT COUNT(*)
            FROM SHIFTS
           WHERE ACCOUNT_ID=:DRIVER_ID
             AND DATE_END IS NULL
            INTO :CNT;

          D=CURRENT_TIMESTAMP;

          IF (CNT=0) THEN BEGIN

            INSERT INTO SHIFTS (SHIFT_ID,ACCOUNT_ID,DATE_BEGIN,DATE_END)
                        VALUES (GET_UNIQUE_ID(),:DRIVER_ID,:D,NULL);

          END

          PARK_ID=NULL;
          PARK_NAME=NULL;

          FOR SELECT P.PARK_ID, P.NAME, P.DESCRIPTION
                FROM PARKS P
               WHERE (((P.MAX_COUNT IS NOT NULL) AND
                       (P.MAX_COUNT> (SELECT COUNT(*)
                                        FROM PARK_STATES
                                       WHERE DATE_OUT IS NULL
                                         AND PARK_ID=P.PARK_ID)))
                      OR (P.MAX_COUNT IS NULL))
                 AND P.NAME=:CODE
                INTO :PARK_ID, :PARK_NAME, :PARK_DESCRIPTION  DO BEGIN
            BREAK;
          END

          IF (PARK_ID IS NOT NULL) THEN BEGIN

            INSERT INTO PARK_STATES (PARK_STATE_ID,PARK_ID,DRIVER_ID,DATE_IN,DATE_OUT)
                             VALUES (GET_UNIQUE_ID(),:PARK_ID,:DRIVER_ID,:D,NULL);

            SELECT COUNT(*)
              FROM PARK_STATES
             WHERE PARK_ID=:PARK_ID
               AND DATE_OUT IS NULL
              INTO PRIORITY;

            SELECT CONST_VALUE FROM GET_CONST_VALUE('80627FCA459EA3574F6BA8730F32946F') INTO :S;

            IF (S IS NOT NULL) THEN BEGIN

              S=REPLACE_STRING(S,'%PRIORITY',CAST(PRIORITY AS VARCHAR(10)));
              S=REPLACE_STRING(S,'%PARK_NAME',PARK_NAME);
              S=REPLACE_STRING(S,'%PARK_DESCRIPTION',PARK_DESCRIPTION);
              S=REPLACE_STRING(S,'%BALANCE',CAST(BALANCE AS VARCHAR(30)));

              INSERT INTO OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                        TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,
                                        PRIORITY,LOCKED,DATE_BEGIN,ORDER_ID)
                                VALUES (GET_UNIQUE_ID(),:ACCOUNT_ID,:DRIVER_ID,CURRENT_TIMESTAMP,
                                        :S,NULL,0,:PHONE,NULL,
                                        1,NULL,CURRENT_TIMESTAMP,:ORDER_ID);
            END

          END ELSE BEGIN

            SELECT CONST_VALUE FROM GET_CONST_VALUE('18B1E217D3789DDF4BCE1EEE9C7AB7A5') INTO :S;

            IF (S IS NOT NULL) THEN BEGIN

              INSERT INTO OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                        TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,
                                        PRIORITY,LOCKED,DATE_BEGIN,ORDER_ID)
                                VALUES (GET_UNIQUE_ID(),:ACCOUNT_ID,:DRIVER_ID,CURRENT_TIMESTAMP,
                                        :S,NULL,0,:PHONE,NULL,
                                        1,NULL,CURRENT_TIMESTAMP,:ORDER_ID);
            END

          END

        END

      END ELSE BEGIN

        SELECT CONST_VALUE FROM GET_CONST_VALUE('0690BD9649C89DD8472558C3270F35D6') INTO :S;

        IF (S IS NOT NULL) THEN BEGIN

          INSERT INTO OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                    TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,
                                    PRIORITY,LOCKED,DATE_BEGIN,ORDER_ID)
                            VALUES (GET_UNIQUE_ID(),:ACCOUNT_ID,:DRIVER_ID,CURRENT_TIMESTAMP,
                                    :S,NULL,0,:PHONE,NULL,
                                    1,NULL,CURRENT_TIMESTAMP,:ORDER_ID);
        END

      END

    END

  END
END

--

CREATE OR ALTER PROCEDURE QUERY_PARK_STATES (
  ORDER_ID VARCHAR(32),
  CREATOR_ID VARCHAR(32),
  RECIPIENT_ID VARCHAR(32),
  CONTACT VARCHAR(100))
AS
  DECLARE S VARCHAR(1000);
  DECLARE F VARCHAR(1000);
  DECLARE S1 VARCHAR(1000);
  DECLARE PARK_NAME VARCHAR(100);
  DECLARE CNT INTEGER;
BEGIN
  IF ((CREATOR_ID IS NOT NULL) AND (CONTACT IS NOT NULL)) THEN BEGIN

    S='';

    SELECT CONST_VALUE FROM GET_CONST_VALUE('A3D890F68FF0BDCC4B42C3135174ABEF') INTO :F;

    IF (F IS NOT NULL) THEN BEGIN

       FOR SELECT P.NAME,
                  (SELECT COUNT(*)
                     FROM PARK_STATES PS
                    WHERE PS.DATE_OUT IS NULL
                      AND PS.PARK_ID=P.PARK_ID)
             FROM PARKS P
            ORDER BY P.PRIORITY
             INTO :PARK_NAME, :CNT DO BEGIN

         S1=F;
         S1=REPLACE_STRING(S1,'%PARK_NAME',PARK_NAME);
         S1=REPLACE_STRING(S1,'%COUNT',CAST(CNT AS VARCHAR(10)));

         S=S||S1;

       END

       INSERT INTO OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                 TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,
                                 PRIORITY,LOCKED,DATE_BEGIN,ORDER_ID)
                         VALUES (GET_UNIQUE_ID(),:CREATOR_ID,:RECIPIENT_ID,CURRENT_TIMESTAMP,
                                :S,NULL,0,:CONTACT,NULL,
                                1,NULL,CURRENT_TIMESTAMP,:ORDER_ID);
     END

  END

END

--

CREATE OR ALTER PROCEDURE DR_FULL_CALC
(
  ORDER_ID VARCHAR(32),
  ACTION_ID VARCHAR(32),
  RESULT_ID VARCHAR(32)) 
RETURNS (
  DETECTED INTEGER)
AS
DECLARE CNT INTEGER;
DECLARE DRIVER_ID VARCHAR(32);
DECLARE DATE_BEGIN TIMESTAMP;
DECLARE DATE_ACCEPT TIMESTAMP;
BEGIN
  DETECTED=0;

  SELECT DRIVER_ID, DATE_BEGIN, DATE_ACCEPT
    FROM ORDERS
   WHERE ORDER_ID=:ORDER_ID
    INTO :DRIVER_ID, :DATE_BEGIN, :DATE_ACCEPT;

  IF (DRIVER_ID IS NOT NULL) THEN BEGIN

    SELECT COUNT(*)
      FROM IN_MESSAGES IM
      JOIN CODE_MESSAGES CM ON CM.CODE_MESSAGE_ID=IM.CODE_MESSAGE_ID
     WHERE IM.SENDER_ID=:DRIVER_ID
       AND IM.ORDER_ID=:ORDER_ID
       AND IM.CODE_MESSAGE_ID='0388BCC17DE1A1754B566F18AEEED771' /* Клиент рассчитался полностью */
       AND IM.TYPE_MESSAGE=0
/*       AND IM.DATE_IN>:DATE_BEGIN */
       AND IM.DATE_IN>:DATE_ACCEPT
       AND CM.ENABLED=1
       AND IM.DESCRIPTION IS NULL
      INTO CNT;

    IF (CNT>0) THEN
      DETECTED=1;

  END

  SUSPEND;
END

--

CREATE OR ALTER PROCEDURE PR_FULL_CALC 
(
  ORDER_ID VARCHAR(32),
  ACCOUNT_ID VARCHAR(32))
AS
DECLARE COST_RATE NUMERIC(15,2);
DECLARE COST_FACT NUMERIC(15,2);
DECLARE NON_CASH NUMERIC(15,2);
DECLARE PARENT_SUM NUMERIC(15,2);
DECLARE PHONE VARCHAR(100);
DECLARE DRIVER_ID VARCHAR(32);
DECLARE SUM_CHARGE NUMERIC(15,2);
DECLARE SUM_RECEIPT NUMERIC(15,2);
DECLARE BALANCE NUMERIC(15,2);
DECLARE MIN_BALANCE NUMERIC(15,2);
DECLARE CHARGE_TYPE_ID VARCHAR(32);
DECLARE RECEIPT_TYPE_ID VARCHAR(32);
DECLARE CLIENT_ID VARCHAR(32);
DECLARE PARENT_ID VARCHAR(32);
DECLARE CALC_ID VARCHAR(32);
DECLARE S VARCHAR(1000);
DECLARE CODE VARCHAR(100);
DECLARE CNT INTEGER;
DECLARE DESCRIPTION VARCHAR(250);
DECLARE USER_NAME VARCHAR(100);
BEGIN

  SELECT PHONE, DRIVER_ID, COST_RATE, COST_FACT, CLIENT_ID
    FROM ORDERS
   WHERE ORDER_ID=:ORDER_ID
    INTO :PHONE, :DRIVER_ID, :COST_RATE, :COST_FACT, :CLIENT_ID;

  IF (DRIVER_ID IS NOT NULL) THEN BEGIN

    UPDATE IN_MESSAGES
       SET DESCRIPTION=:ORDER_ID
     WHERE ORDER_ID=:ORDER_ID
       AND CODE_MESSAGE_ID='0388BCC17DE1A1754B566F18AEEED771' /* Клиент рассчитался полностью */
       AND SENDER_ID=:DRIVER_ID
       AND DESCRIPTION IS NULL;

  END

  IF ((COST_FACT IS NULL) OR (COST_FACT<=0.0))  THEN
    COST_FACT=:COST_RATE;

  IF (COST_FACT<=0.0) THEN BEGIN

    SELECT CONST_VALUE FROM GET_CONST_VALUE('4BB5C780923E872D436DA3DA31C9E0B0') INTO :S;

    IF (S IS NOT NULL) THEN BEGIN

      SELECT PHONE
        FROM ACCOUNTS
       WHERE ACCOUNT_ID=:DRIVER_ID
        INTO :PHONE;

      INSERT INTO OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,
                                PRIORITY,LOCKED,DATE_BEGIN,ORDER_ID)
                        VALUES (GET_UNIQUE_ID(),:ACCOUNT_ID,:DRIVER_ID,CURRENT_TIMESTAMP,
                                :S,NULL,0,:PHONE,NULL,
                                2,NULL,CURRENT_TIMESTAMP,:ORDER_ID);
    END

    EXECUTE PROCEDURE PR_MANUAL(ORDER_ID,ACCOUNT_ID);

  END ELSE BEGIN

    UPDATE ORDERS
       SET FINISHED=1,
           DATE_END=CURRENT_TIMESTAMP,
           WHO_PROCESS_ID=:ACCOUNT_ID,
           COST_FACT=:COST_FACT
     WHERE ORDER_ID=:ORDER_ID;

    EXECUTE PROCEDURE CREATE_ROUTE_HISTORY(ORDER_ID);

    IF (DRIVER_ID IS NOT NULL) THEN BEGIN

      CALC_ID=NULL;

      IF (CLIENT_ID IS NOT NULL) THEN BEGIN

        SELECT C.CALC_ID, A.USER_NAME
          FROM CLIENTS C
          JOIN ACCOUNTS A ON A.ACCOUNT_ID=C.CLIENT_ID
         WHERE CLIENT_ID=:CLIENT_ID
          INTO :CALC_ID, :USER_NAME;

        SELECT COUNT(*)
          FROM CLIENT_CHILDS
         WHERE CHILD_ID=:CLIENT_ID
          INTO :CNT;

        IF (CNT>0) THEN BEGIN

          PARENT_SUM=2.0;

          IF ((COST_FACT>150.0) AND (COST_FACT<=250.0)) THEN
            PARENT_SUM=5.0;

          IF ((COST_FACT>250.0) AND (COST_FACT<=350.0)) THEN
            PARENT_SUM=10.0;

          IF (COST_FACT>350.0) THEN
            PARENT_SUM=20.0;

          SUM_RECEIPT=PARENT_SUM/CNT;

          FOR SELECT CLIENT_ID
                FROM CLIENT_CHILDS

               WHERE CHILD_ID=:CLIENT_ID
                INTO :PARENT_ID DO BEGIN

           RECEIPT_TYPE_ID='9958D6ED64ADAAB94AEF470DA7B5F4F7'; /* Поездка дочернего клиента */

           DESCRIPTION=USER_NAME;

           INSERT INTO RECEIPTS (RECEIPT_ID,RECEIPT_TYPE_ID,ACCOUNT_ID,WHO_CREATE_ID,
                                 SUM_RECEIPT,DATE_RECEIPT,DATE_CREATE,DESCRIPTION)
                         VALUES (GET_UNIQUE_ID(),:RECEIPT_TYPE_ID,:PARENT_ID,:ACCOUNT_ID,
                                :SUM_RECEIPT,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,:DESCRIPTION);

          END
        END

      END

      BALANCE=NULL;

      IF (CALC_ID IS NOT NULL) THEN BEGIN

        EXECUTE PROCEDURE GET_ACCOUNT_BALANCE(:CLIENT_ID)
         RETURNING_VALUES :SUM_CHARGE, :SUM_RECEIPT, :BALANCE;

      END

      NON_CASH=NULL;

      IF (BALANCE IS NOT NULL) THEN BEGIN

        IF (BALANCE>=COST_FACT) THEN BEGIN
          NON_CASH=COST_FACT;
          BALANCE=BALANCE-NON_CASH;
        END ELSE BEGIN
          NON_CASH=BALANCE;
          BALANCE=0.0;
        END

      END

      IF (NON_CASH IS NOT NULL) THEN BEGIN

        CHARGE_TYPE_ID='757B9CAF2D3CA5144A7E2A23472990E5'; /* Поездка */

        SUM_CHARGE=NON_CASH;

        INSERT INTO CHARGES (CHARGE_ID,WHO_CREATE_ID,CHARGE_TYPE_ID,ACCOUNT_ID,
                             SUM_CHARGE,DATE_CHARGE,DATE_CREATE,DESCRIPTION)
                     VALUES (GET_UNIQUE_ID(),:ACCOUNT_ID,:CHARGE_TYPE_ID,:CLIENT_ID,
                             :SUM_CHARGE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL);


      END

      IF (SUBSTR(PHONE,1,3)='+79')  THEN BEGIN

        IF (NON_CASH IS NOT NULL) THEN BEGIN

          SELECT CONST_VALUE FROM GET_CONST_VALUE('56140344A440BE774C9007D49CD574E9') INTO :S;

        END ELSE BEGIN

          SELECT CONST_VALUE FROM GET_CONST_VALUE('05B75340B170BF5141FC63F5CDF7FCD6') INTO :S;

        END

        IF (S IS NOT NULL) THEN BEGIN

          S=REPLACE_STRING(S,'%BALANCE',CAST(CAST(BALANCE AS NUMERIC(15,0)) AS VARCHAR(30)));

          INSERT INTO OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                    TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,
                                    PRIORITY,LOCKED,DATE_BEGIN,ORDER_ID)
                            VALUES (GET_UNIQUE_ID(),:ACCOUNT_ID,:CLIENT_ID,CURRENT_TIMESTAMP,
                                    :S,NULL,0,:PHONE,NULL,
                                    2,NULL,CURRENT_TIMESTAMP,:ORDER_ID);
        END

        SELECT CONST_VALUE FROM GET_CONST_VALUE('E9FFA9589ABD8C174474572B72017BCC') INTO :S;

        IF (S IS NOT NULL) THEN BEGIN

          INSERT INTO OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                    TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,
                                    PRIORITY,LOCKED,DATE_BEGIN,ORDER_ID)
                            VALUES (GET_UNIQUE_ID(),:ACCOUNT_ID,:CLIENT_ID,CURRENT_TIMESTAMP,
                                    :S,NULL,0,:PHONE,NULL,
                                    2,NULL,CURRENT_TIMESTAMP,:ORDER_ID);
        END

      END

      CHARGE_TYPE_ID='E1BC9789DA9DB2B041C0784EBE92BFC9'; /* Выполнение заказа */

      SELECT RET_SUM
        FROM GET_DRIVER_SUM(:DRIVER_ID,:COST_FACT)
        INTO :SUM_CHARGE;

      INSERT INTO CHARGES (CHARGE_ID,WHO_CREATE_ID,CHARGE_TYPE_ID,ACCOUNT_ID,
                           SUM_CHARGE,DATE_CHARGE,DATE_CREATE,DESCRIPTION)
                   VALUES (GET_UNIQUE_ID(),:ACCOUNT_ID,:CHARGE_TYPE_ID,:DRIVER_ID,
                           :SUM_CHARGE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL);

      IF (NON_CASH IS NOT NULL) THEN BEGIN

        RECEIPT_TYPE_ID='3F91C48D888F81974941D256C0815B03'; /* Компенсация за поездку */

        SUM_RECEIPT=NON_CASH;

        INSERT INTO RECEIPTS (RECEIPT_ID,RECEIPT_TYPE_ID,ACCOUNT_ID,WHO_CREATE_ID,
                              SUM_RECEIPT,DATE_RECEIPT,DATE_CREATE,DESCRIPTION)
                      VALUES (GET_UNIQUE_ID(),:RECEIPT_TYPE_ID,:DRIVER_ID,:ACCOUNT_ID,
                              :SUM_RECEIPT,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL);

      END

      EXECUTE PROCEDURE GET_ACCOUNT_BALANCE(:DRIVER_ID)
       RETURNING_VALUES :SUM_CHARGE, :SUM_RECEIPT, :BALANCE;

      SELECT MIN_BALANCE
        FROM DRIVERS
       WHERE DRIVER_ID=:DRIVER_ID
        INTO :MIN_BALANCE;

      IF ((MIN_BALANCE IS NULL) OR ((MIN_BALANCE IS NOT NULL) AND (BALANCE>MIN_BALANCE))) THEN BEGIN

        SELECT CONST_VALUE FROM GET_CONST_VALUE('16835607B30CA79F4CE883B53AFE972D') INTO :S;

      END ELSE BEGIN

        UPDATE SHIFTS
           SET DATE_END=CURRENT_TIMESTAMP
         WHERE ACCOUNT_ID=:DRIVER_ID
           AND DATE_END IS NULL;

        SELECT CONST_VALUE FROM GET_CONST_VALUE('634880F305E9AA434245E3E596697001') INTO :S;

      END

      SELECT PHONE
        FROM ACCOUNTS
       WHERE ACCOUNT_ID=:DRIVER_ID
        INTO :PHONE;

      IF (S IS NOT NULL) THEN BEGIN

        S=REPLACE_STRING(S,'%BALANCE',CAST(BALANCE AS VARCHAR(30)));

        IF (NON_CASH IS NULL) THEN
          NON_CASH=0.0;

        S=REPLACE_STRING(S,'%NON_CASH',CAST(CAST(NON_CASH AS NUMERIC(15,0)) AS VARCHAR(30)));

        INSERT INTO OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                  TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,
                                  PRIORITY,LOCKED,DATE_BEGIN,ORDER_ID)
                          VALUES (GET_UNIQUE_ID(),:ACCOUNT_ID,:DRIVER_ID,CURRENT_TIMESTAMP,
                                  :S,NULL,0,:PHONE,NULL,
                                  2,NULL,CURRENT_TIMESTAMP,:ORDER_ID);
      END

      FOR SELECT TRIM(SUB_STRING(IM.TEXT_IN,2,100))
            FROM IN_MESSAGES IM
            JOIN CODE_MESSAGES CM ON CM.CODE_MESSAGE_ID=IM.CODE_MESSAGE_ID
           WHERE IM.SENDER_ID=:DRIVER_ID
             AND IM.ORDER_ID=:ORDER_ID
             AND IM.CODE_MESSAGE_ID='0388BCC17DE1A1754B566F18AEEED771' /* Клиент рассчитался полностью */
             AND IM.TYPE_MESSAGE=0
             AND CM.ENABLED=1
           ORDER BY IM.DATE_IN DESC
            INTO :CODE DO BEGIN

        SELECT COUNT(*)
          FROM CODE_MESSAGES
         WHERE CODE=:CODE
          INTO :CNT;

        IF (CNT=1) THEN BEGIN

          EXECUTE PROCEDURE TRY_PARK_IN(ORDER_ID,ACCOUNT_ID,DRIVER_ID,CODE);

        END ELSE BEGIN

          EXECUTE PROCEDURE QUERY_PARK_STATES (ORDER_ID,ACCOUNT_ID,DRIVER_ID,PHONE);

        END

        BREAK;
      END

    END

  END
END

--

CREATE OR ALTER PROCEDURE CODE_PARK_IN (
  ACCOUNT_ID VARCHAR(32),
  IN_MESSAGE_ID VARCHAR(32))
AS
DECLARE SENDER_ID VARCHAR(32);
DECLARE CODE VARCHAR(100);
BEGIN
  SELECT IM.SENDER_ID, CM.CODE
    FROM IN_MESSAGES IM
    LEFT JOIN CODE_MESSAGES CM ON CM.CODE_MESSAGE_ID=IM.CODE_MESSAGE_ID
   WHERE IN_MESSAGE_ID=:IN_MESSAGE_ID
    INTO :SENDER_ID, :CODE;

  IF ((SENDER_ID IS NOT NULL) AND (CODE IS NOT NULL)) THEN BEGIN

    EXECUTE PROCEDURE TRY_PARK_IN (NULL,ACCOUNT_ID,SENDER_ID,CODE);

  END
END

--

CREATE OR ALTER PROCEDURE CODE_PARK_STATES (
  ACCOUNT_ID VARCHAR(32),
  IN_MESSAGE_ID VARCHAR(32))
AS
DECLARE CONTACT VARCHAR(100);
DECLARE SENDER_ID VARCHAR(32);
DECLARE S VARCHAR(1000);
DECLARE S1 VARCHAR(1000);
DECLARE F VARCHAR(1000);
DECLARE PARK_NAME VARCHAR(100);
DECLARE SUM_CHARGE NUMERIC(15,2);
DECLARE SUM_RECEIPT NUMERIC(15,2);
DECLARE BALANCE NUMERIC(15,2);
DECLARE MIN_BALANCE NUMERIC(15,2);
DECLARE CNT INTEGER;
BEGIN
  SELECT CONTACT, SENDER_ID
    FROM IN_MESSAGES
   WHERE IN_MESSAGE_ID=:IN_MESSAGE_ID
    INTO :CONTACT, :SENDER_ID;

  IF ((CONTACT IS NOT NULL) AND (SENDER_ID IS NOT NULL)) THEN BEGIN

    SELECT COUNT(*)
      FROM DRIVERS D
      JOIN  ACCOUNTS A ON A.ACCOUNT_ID=D.DRIVER_ID
     WHERE D.DRIVER_ID=:SENDER_ID
       AND A.LOCKED<>1
      INTO :CNT;

    IF (CNT>0) THEN BEGIN

      EXECUTE PROCEDURE GET_ACCOUNT_BALANCE(:SENDER_ID)
       RETURNING_VALUES :SUM_CHARGE, :SUM_RECEIPT, :BALANCE;

      SELECT MIN_BALANCE
        FROM DRIVERS
       WHERE DRIVER_ID=:SENDER_ID
        INTO :MIN_BALANCE;

      IF ((MIN_BALANCE IS NULL) OR ((MIN_BALANCE IS NOT NULL) AND (BALANCE>MIN_BALANCE))) THEN BEGIN
 
        EXECUTE PROCEDURE QUERY_PARK_STATES (NULL,ACCOUNT_ID,SENDER_ID,CONTACT);

      END

    END

  END
END

--

CREATE OR ALTER PROCEDURE U_ORDER
(
  ORDER_ID VARCHAR(32),
  ACTION_ID VARCHAR(32),
  RATE_ID VARCHAR(32),
  CAR_TYPE_ID VARCHAR(32),
  WHO_ACCEPT_ID VARCHAR(32),
  STREET_ID VARCHAR(32),
  ZONE_ID VARCHAR(32),
  PARENT_ID VARCHAR(32),
  CAR_ID VARCHAR(32),
  WHO_PROCESS_ID VARCHAR(32),
  RESULT_ID VARCHAR(32),
  PARK_ID VARCHAR(32),
  SOURCE_ID VARCHAR(32),
  DISCOUNT_ID VARCHAR(32),
  DRIVER_ID VARCHAR(32),
  ORDER_NUM VARCHAR(10),
  PHONE VARCHAR(100),
  HOUSE VARCHAR(10),
  FLAT VARCHAR(10),
  PORCH VARCHAR(10),
  DATE_ACCEPT TIMESTAMP,
  DATE_ARRIVAL TIMESTAMP,
  DATE_BEGIN TIMESTAMP,
  DATE_END TIMESTAMP,
  CUSTOMER VARCHAR(250),
  DESCRIPTION VARCHAR(250),
  COST_RATE NUMERIC(18,2),
  COST_FACT NUMERIC(18,2),
  TYPE_ACCEPT INTEGER,
  TYPE_PROCESS INTEGER,
  DATE_HISTORY TIMESTAMP,
  WHO_HISTORY_ID VARCHAR(32),
  BEFORE_PERIOD INTEGER,
  FINISHED INTEGER,
  LOCKED VARCHAR(32),
  CLIENT_ID VARCHAR(32),
  COST_GROSS NUMERIC(18,2),
  OLD_ORDER_ID VARCHAR(32))
AS
  DECLARE RECIPIENT_ID VARCHAR(32);
  DECLARE OLD_COST_RATE NUMERIC(15,2);
  DECLARE S VARCHAR(70);
BEGIN
  UPDATE ORDERS
     SET ORDER_ID=:ORDER_ID,
         ACTION_ID=:ACTION_ID,
         RATE_ID=:RATE_ID,
         CAR_TYPE_ID=:CAR_TYPE_ID,
         WHO_ACCEPT_ID=:WHO_ACCEPT_ID,
         STREET_ID=:STREET_ID,
         ZONE_ID=:ZONE_ID,
         PARENT_ID=:PARENT_ID,
         CAR_ID=:CAR_ID,
         WHO_PROCESS_ID=:WHO_PROCESS_ID,
         RESULT_ID=:RESULT_ID,
         PARK_ID=:PARK_ID,
         SOURCE_ID=:SOURCE_ID,
         DISCOUNT_ID=:DISCOUNT_ID,
         DRIVER_ID=:DRIVER_ID,
         ORDER_NUM=:ORDER_NUM,
         PHONE=:PHONE,
         HOUSE=:HOUSE,
         FLAT=:FLAT,
         PORCH=:PORCH,
         DATE_ACCEPT=:DATE_ACCEPT,
         DATE_ARRIVAL=:DATE_ARRIVAL,
         DATE_BEGIN=:DATE_BEGIN,
         DATE_END=:DATE_END,
         CUSTOMER=:CUSTOMER,
         DESCRIPTION=:DESCRIPTION,
         COST_RATE=:COST_RATE,
         COST_FACT=:COST_FACT,
         TYPE_ACCEPT=:TYPE_ACCEPT,
         TYPE_PROCESS=:TYPE_PROCESS,
         DATE_HISTORY=:DATE_HISTORY,
         WHO_HISTORY_ID=:WHO_HISTORY_ID,
         BEFORE_PERIOD=:BEFORE_PERIOD,
         FINISHED=:FINISHED,
         LOCKED=:LOCKED,
         CLIENT_ID=:CLIENT_ID,
         COST_GROSS=:COST_GROSS
   WHERE ORDER_ID=:OLD_ORDER_ID;

  OLD_COST_RATE=NULL;

  FOR SELECT COST_RATE
        FROM ORDERS
       WHERE PARENT_ID=:OLD_ORDER_ID
         AND DATE_HISTORY IS NOT NULL
       ORDER BY DATE_HISTORY DESC
        INTO :OLD_COST_RATE DO BEGIN

    IF (OLD_COST_RATE IS NOT NULL) THEN
      BREAK;

  END

  IF ((COST_RATE IS NOT NULL) AND (OLD_COST_RATE<>COST_RATE) AND (WHO_PROCESS_ID IS NOT NULL)) THEN BEGIN

    IF (SUBSTR(PHONE,1,3)='+79')  THEN BEGIN

      RECIPIENT_ID=NULL;

      FOR SELECT ACCOUNT_ID
            FROM ACCOUNTS
           WHERE PHONE=:PHONE
            INTO :RECIPIENT_ID DO BEGIN

        IF (RECIPIENT_ID IS NOT NULL) THEN
          BREAK;
      END

      SELECT CONST_VALUE FROM GET_CONST_VALUE('6F6E5F38806C896B43AC16E69914EFFA') INTO :S;

      IF (S IS NOT NULL) THEN BEGIN

        S=REPLACE_STRING(S,'%COST_RATE',CAST(COST_RATE AS VARCHAR(30)));

        INSERT INTO OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                  TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,
                                  PRIORITY,LOCKED,DATE_BEGIN,ORDER_ID)
                          VALUES (GET_UNIQUE_ID(),:WHO_PROCESS_ID,:RECIPIENT_ID,CURRENT_TIMESTAMP,
                                  :S,NULL,0,:PHONE,NULL,
                                  1,NULL,CURRENT_TIMESTAMP,:ORDER_ID);
      END

    END

  END

END

--

ALTER TABLE ZONES
ADD COST_IN NUMERIC(15,2)

--

ALTER TABLE ZONES
ADD COST_OUT NUMERIC(15,2)

--

DROP VIEW S_ZONES

--

CREATE VIEW S_ZONES
AS
SELECT * FROM ZONES

--

CREATE OR ALTER PROCEDURE D_ZONE
(
  OLD_ZONE_ID VARCHAR(32)
)
AS
BEGIN
  DELETE FROM ZONES
        WHERE ZONE_ID=:OLD_ZONE_ID;
END

--

CREATE OR ALTER PROCEDURE I_ZONE
(
  ZONE_ID VARCHAR(32),
  NAME VARCHAR(100),
  DESCRIPTION VARCHAR(250),
  PRIORITY INTEGER,
  COST_IN NUMERIC(15,2),
  COST_OUT NUMERIC(15,2)
)
AS
BEGIN
  INSERT INTO ZONES (ZONE_ID,NAME,DESCRIPTION,PRIORITY,COST_IN,COST_OUT)
       VALUES (:ZONE_ID,:NAME,:DESCRIPTION,:PRIORITY,:COST_IN,:COST_OUT);
END

--

CREATE OR ALTER PROCEDURE U_ZONE
(
  ZONE_ID VARCHAR(32),
  NAME VARCHAR(100),
  DESCRIPTION VARCHAR(250),
  PRIORITY INTEGER,
  COST_IN NUMERIC(15,2),
  COST_OUT NUMERIC(15,2),
  OLD_ZONE_ID VARCHAR(32)
)
AS
BEGIN
  UPDATE ZONES
     SET ZONE_ID=:ZONE_ID,
         NAME=:NAME,
         DESCRIPTION=:DESCRIPTION,
         PRIORITY=:PRIORITY,
         COST_IN=:COST_IN,
         COST_OUT=:COST_OUT
   WHERE ZONE_ID=:OLD_ZONE_ID;
END;

--
