--

CREATE OR ALTER PROCEDURE GET_MESSAGE_COUNT (
  DATE_BEGIN TIMESTAMP,
  DATE_END TIMESTAMP) 
RETURNS (
  DATE_OUT DATE,
  FIRM_SMALL_NAME VARCHAR(250),
  MESSAGE_COUNT INTEGER)
AS
DECLARE SQL VARCHAR(4000);
BEGIN
  SQL='SELECT T.DATE_OUT,CASE WHEN F.SMALL_NAME IS NULL THEN ''-----'' ELSE F.SMALL_NAME END,T.MESSAGE_COUNT ';
  SQL=SQL||'FROM (SELECT CAST(DATE_OUT AS DATE) AS DATE_OUT, FIRM_ID, COUNT(*) AS MESSAGE_COUNT ';
  SQL=SQL||'FROM OUT_MESSAGES ';
  SQL=SQL||'WHERE DATE_OUT IS NOT NULL ';
  SQL=SQL||'AND TYPE_MESSAGE=0 ';

  IF (DATE_BEGIN IS NOT NULL) THEN
    SQL=SQL||'AND DATE_OUT>='''||FORMAT_DATETIME('dd.mm.yyyy hh:nn:ss',DATE_BEGIN)||''' ';

  IF (DATE_END IS NOT NULL) THEN
    SQL=SQL||'AND DATE_OUT<'''||FORMAT_DATETIME('dd.mm.yyyy hh:nn:ss',DATE_END)||''' ';

  SQL=SQL||'GROUP BY CAST(DATE_OUT AS DATE), FIRM_ID) T ';
  SQL=SQL||'LEFT JOIN FIRMS F ON F.FIRM_ID=T.FIRM_ID ';
  SQL=SQL||'ORDER BY T.DATE_OUT, F.SMALL_NAME ';

  FOR EXECUTE STATEMENT SQL
                   INTO :DATE_OUT, :FIRM_SMALL_NAME, :MESSAGE_COUNT DO BEGIN
    SUSPEND;
  END

END

--

CREATE OR ALTER PROCEDURE GET_RECEIPT_SUM 
(
  DATE_BEGIN TIMESTAMP,
  DATE_END TIMESTAMP,
  FIRM_ID VARCHAR(32)) 
RETURNS (
  RECEIPT_TYPE_NAME VARCHAR(100),
  FIRM_SMALL_NAME VARCHAR(250),
  RECEIPT_SUM INTEGER)
AS
DECLARE SQL VARCHAR(4000);
BEGIN
  IF (FIRM_ID IS NOT NULL) THEN BEGIN

    SQL='SELECT RT.NAME,F.SMALL_NAME,T.SUM_RECEIPT ';
    SQL=SQL||'FROM (SELECT R.RECEIPT_TYPE_ID,A.FIRM_ID,SUM(R.SUM_RECEIPT) AS SUM_RECEIPT ';
    SQL=SQL||'FROM RECEIPTS R ';
    SQL=SQL||'JOIN DRIVERS D ON D.DRIVER_ID=R.ACCOUNT_ID ';
    SQL=SQL||'JOIN ACCOUNTS A ON A.ACCOUNT_ID=D.DRIVER_ID ';
    SQL=SQL||'WHERE R.FIRM_ID='''||FIRM_ID||''' ';

    IF (DATE_BEGIN IS NOT NULL) THEN
      SQL=SQL||'AND R.DATE_RECEIPT>='''||FORMAT_DATETIME('dd.mm.yyyy hh:nn:ss',DATE_BEGIN)||''' ';

    IF (DATE_END IS NOT NULL) THEN
      SQL=SQL||'AND R.DATE_RECEIPT<'''||FORMAT_DATETIME('dd.mm.yyyy hh:nn:ss',DATE_END)||''' ';

    SQL=SQL||'GROUP BY R.RECEIPT_TYPE_ID,A.FIRM_ID ';
    SQL=SQL||') T ';
    SQL=SQL||'JOIN FIRMS F ON F.FIRM_ID=T.FIRM_ID ';
    SQL=SQL||'JOIN RECEIPT_TYPES RT ON RT.RECEIPT_TYPE_ID=T.RECEIPT_TYPE_ID ';
    SQL=SQL||'ORDER BY RT.NAME, F.SMALL_NAME ';

    FOR EXECUTE STATEMENT SQL
                     INTO :RECEIPT_TYPE_NAME, :FIRM_SMALL_NAME, :RECEIPT_SUM DO BEGIN
      SUSPEND;
    END

  END
END

--

CREATE OR ALTER PROCEDURE GET_CHARGE_SUM
(
  DATE_BEGIN TIMESTAMP,
  DATE_END TIMESTAMP,
  FIRM_ID VARCHAR(32)
)
RETURNS
(
  CHARGE_TYPE_NAME VARCHAR(100),
  FIRM_SMALL_NAME VARCHAR(250),
  CHARGE_SUM INTEGER)
AS
DECLARE SQL VARCHAR(4000);
BEGIN
  IF (FIRM_ID IS NOT NULL) THEN BEGIN

    SQL='SELECT CT.NAME,F.SMALL_NAME,T.SUM_CHARGE ';
    SQL=SQL||'FROM (SELECT C.CHARGE_TYPE_ID,A.FIRM_ID,SUM(C.SUM_CHARGE) AS SUM_CHARGE ';
    SQL=SQL||'FROM CHARGES C ';
    SQL=SQL||'JOIN DRIVERS D ON D.DRIVER_ID=C.ACCOUNT_ID ';
    SQL=SQL||'JOIN ACCOUNTS A ON A.ACCOUNT_ID=D.DRIVER_ID ';
    SQL=SQL||'WHERE C.FIRM_ID='''||FIRM_ID||''' ';

    IF (DATE_BEGIN IS NOT NULL) THEN
      SQL=SQL||'AND C.DATE_CHARGE>='''||FORMAT_DATETIME('dd.mm.yyyy hh:nn:ss',DATE_BEGIN)||''' ';

    IF (DATE_END IS NOT NULL) THEN
      SQL=SQL||'AND C.DATE_CHARGE<'''||FORMAT_DATETIME('dd.mm.yyyy hh:nn:ss',DATE_END)||''' ';

    SQL=SQL||'GROUP BY C.CHARGE_TYPE_ID,A.FIRM_ID ';
    SQL=SQL||') T ';
    SQL=SQL||'JOIN FIRMS F ON F.FIRM_ID=T.FIRM_ID ';
    SQL=SQL||'JOIN CHARGE_TYPES CT ON CT.CHARGE_TYPE_ID=T.CHARGE_TYPE_ID ';
    SQL=SQL||'ORDER BY CT.NAME, F.SMALL_NAME ';

    FOR EXECUTE STATEMENT SQL
                     INTO :CHARGE_TYPE_NAME, :FIRM_SMALL_NAME, :CHARGE_SUM DO BEGIN
      SUSPEND;
    END

  END
END

--

CREATE OR ALTER PROCEDURE GET_HOURS (
  DATE_BEGIN TIMESTAMP,
  DATE_END TIMESTAMP) 
RETURNS (
  DATE_HOUR DATE,
  DAY_HOUR INTEGER,
  SECONDS INTEGER,
  RATIO NUMERIC(15,4),
  DATE_FROM TIMESTAMP,
  DATE_TO TIMESTAMP)
AS
DECLARE TEMP TIMESTAMP;
BEGIN
  DATE_TO=DATE_BEGIN;

  WHILE (DATE_TO<DATE_END) DO BEGIN

    DATE_HOUR=CAST(DATE_TO AS DATE);
    DAY_HOUR=EXTRACT(HOUR FROM DATE_TO);

    DATE_FROM=DATE_TO;

    TEMP=DATE_HOUR;
    TEMP=DATEADD(HOUR,DAY_HOUR+1,TEMP);
    IF (TEMP<=DATE_END) THEN BEGIN

      DATE_TO=TEMP;

    END ELSE BEGIN

      DATE_TO=DATE_END;

    END

    SECONDS=DATEDIFF(SECOND,DATE_FROM,DATE_TO);

    RATIO=CAST(SECONDS AS NUMERIC(15,4))/3600;

    SUSPEND;

  END

END

--

CREATE GLOBAL TEMPORARY TABLE TMP_HOURS
(
  DATE_HOUR DATE NOT NULL,
  DAY_HOUR INTEGER NOT NULL,
  PRIMARY KEY (DATE_HOUR,DAY_HOUR)
)

--

CREATE GLOBAL TEMPORARY TABLE TMP_REAL_COUNT
(
  DATE_ACCEPT DATE NOT NULL,
  DAY_HOUR INTEGER NOT NULL,
  ORDER_COUNT INTEGER,
  PRIMARY KEY (DATE_ACCEPT,DAY_HOUR)
)

--

CREATE GLOBAL TEMPORARY TABLE TMP_DOUBLE_COUNT
(
  DATE_ACCEPT DATE NOT NULL,
  DAY_HOUR INTEGER NOT NULL,
  ORDER_COUNT INTEGER,
  PRIMARY KEY (DATE_ACCEPT,DAY_HOUR)
)

--

CREATE GLOBAL TEMPORARY TABLE TMP_OTHER_COUNT
(
  DATE_ACCEPT DATE NOT NULL,
  DAY_HOUR INTEGER NOT NULL,
  ORDER_COUNT INTEGER,
  PRIMARY KEY (DATE_ACCEPT,DAY_HOUR)
)

--

CREATE GLOBAL TEMPORARY TABLE TMP_SCHEDULE_COUNT
(
  WEEK_DAY INTEGER NOT NULL,
  DAY_HOUR INTEGER NOT NULL,
  SCHEDULE_COUNT INTEGER,
  PRIMARY KEY (WEEK_DAY,DAY_HOUR)
)

--

CREATE GLOBAL TEMPORARY TABLE TMP_SHIFT_COUNT
(
  DATE_SHIFT DATE NOT NULL,
  DAY_HOUR INTEGER NOT NULL,
  SHIFT_COUNT INTEGER,
  PRIMARY KEY (DATE_SHIFT,DAY_HOUR)
)

--

CREATE GLOBAL TEMPORARY TABLE TMP_PARK_COUNT
(
  DATE_PARK DATE NOT NULL,
  DAY_HOUR INTEGER NOT NULL,
  PARK_COUNT INTEGER,
  PRIMARY KEY (DATE_PARK,DAY_HOUR)
)

--

CREATE OR ALTER PROCEDURE GET_SHIFT_COUNT
(
   DATE_BEGIN TIMESTAMP,
   DATE_END TIMESTAMP
)
RETURNS
(
  DRIVER_ID VARCHAR(32),
  DATE_SHIFT DATE,
  DAY_HOUR INTEGER,
  RATIO NUMERIC(15,4)
)
AS
DECLARE DATE_FROM TIMESTAMP;
DECLARE DATE_TO TIMESTAMP;
BEGIN
  FOR SELECT S.ACCOUNT_ID, S.DATE_BEGIN,
             CASE WHEN S.DATE_END IS NULL THEN :DATE_END ELSE S.DATE_END END
        FROM SHIFTS S
        JOIN DRIVERS D ON D.DRIVER_ID=S.ACCOUNT_ID
       WHERE (S.DATE_BEGIN<=:DATE_BEGIN OR (S.DATE_BEGIN>=:DATE_BEGIN AND S.DATE_BEGIN<=:DATE_END))
         AND (S.DATE_END IS NULL OR S.DATE_END>:DATE_BEGIN)
         AND (S.DATE_END-S.DATE_BEGIN)<3.0
       ORDER BY S.DATE_BEGIN, S.DATE_END
        INTO :DRIVER_ID, :DATE_FROM, :DATE_TO DO BEGIN

    FOR SELECT DATE_HOUR, DAY_HOUR, RATIO, DATE_FROM, DATE_TO
          FROM GET_HOURS(:DATE_FROM,:DATE_TO)
          INTO :DATE_SHIFT, :DAY_HOUR, :RATIO, :DATE_FROM, :DATE_TO DO BEGIN

      SUSPEND;
    END
  END
END

--

CREATE OR ALTER PROCEDURE GET_PARK_COUNT
(
   DATE_BEGIN TIMESTAMP,
   DATE_END TIMESTAMP
)
RETURNS
(
  DRIVER_ID VARCHAR(32),
  DATE_PARK DATE,
  DAY_HOUR INTEGER,
  RATIO NUMERIC(15,4)
)
AS
DECLARE DATE_FROM TIMESTAMP;
DECLARE DATE_TO TIMESTAMP;
BEGIN
  FOR SELECT PS.DRIVER_ID, PS.DATE_IN,
             CASE WHEN PS.DATE_OUT IS NULL THEN :DATE_END ELSE PS.DATE_OUT END
        FROM PARK_STATES PS
       WHERE (PS.DATE_IN<=:DATE_BEGIN OR (PS.DATE_IN>=:DATE_BEGIN AND PS.DATE_IN<=:DATE_END))
         AND (PS.DATE_OUT IS NULL OR PS.DATE_OUT>:DATE_BEGIN)
         AND (PS.DATE_OUT-PS.DATE_IN)<3.0
       ORDER BY PS.DATE_IN, PS.DATE_OUT
        INTO :DRIVER_ID, :DATE_FROM, :DATE_TO DO BEGIN

    FOR SELECT DATE_HOUR, DAY_HOUR, RATIO, DATE_FROM, DATE_TO
          FROM GET_HOURS(:DATE_FROM,:DATE_TO)
          INTO :DATE_PARK, :DAY_HOUR, :RATIO, :DATE_FROM, :DATE_TO DO BEGIN

      SUSPEND;
    END
  END
END

--

CREATE OR ALTER PROCEDURE GET_STAT_COUNT
(
  DATE_BEGIN TIMESTAMP,
  DATE_END TIMESTAMP) 
RETURNS (
  DATE_HOUR DATE,
  WEEK_DAY INTEGER,
  WEEK_DAY_NAME VARCHAR(50),
  DAY_HOUR INTEGER,
  REAL_COUNT INTEGER,
  DOUBLE_COUNT INTEGER,
  OTHER_COUNT INTEGER,
  SCHEDULE_COUNT INTEGER,
  SHIFT_COUNT INTEGER,
  PARK_COUNT INTEGER
)
AS
BEGIN
  DELETE FROM TMP_HOURS;
  INSERT INTO TMP_HOURS (DATE_HOUR,DAY_HOUR)
  SELECT DATE_HOUR,
         DAY_HOUR
    FROM GET_HOURS(:DATE_BEGIN,:DATE_END);

  DELETE FROM TMP_REAL_COUNT;
  INSERT INTO TMP_REAL_COUNT (DATE_ACCEPT,DAY_HOUR,ORDER_COUNT)
  SELECT CAST(O.DATE_ACCEPT AS DATE) AS DATE_ACCEPT,
         EXTRACT(HOUR FROM DATE_ACCEPT) AS HOUR_ACCEPT,
         COUNT(*) AS ORDER_COUNT
    FROM ORDERS O
   WHERE O.DATE_ACCEPT>=:DATE_BEGIN AND O.DATE_ACCEPT<:DATE_END
     AND O.WHO_HISTORY_ID IS NULL
     AND O.FINISHED=1
     AND O.ACTION_ID='78A2A547BAB1AE9C48B797E3F90721A3'
     AND O.RESULT_ID='6DD8DFDC671DB9A742E418FD268E7DC4'
   GROUP BY CAST(O.DATE_ACCEPT AS DATE), EXTRACT(HOUR FROM O.DATE_ACCEPT);

  DELETE FROM TMP_DOUBLE_COUNT;
  INSERT INTO TMP_DOUBLE_COUNT (DATE_ACCEPT,DAY_HOUR,ORDER_COUNT)
  SELECT CAST(O.DATE_ACCEPT AS DATE) AS DATE_ACCEPT,
         EXTRACT(HOUR FROM DATE_ACCEPT) AS HOUR_ACCEPT,
         COUNT(*) AS ORDER_COUNT
    FROM ORDERS O
   WHERE O.DATE_ACCEPT>=:DATE_BEGIN AND O.DATE_ACCEPT<:DATE_END
     AND O.WHO_HISTORY_ID IS NULL
     AND O.FINISHED=1
     AND O.RESULT_ID IN ('5F54734558C5857445839E8800947005','25236D63D02FA50F4D39DF1A2F86B6F6','D442C437F10AA16447252BE436C90807',
                         'CCBAB9B83127B43F44F0B5C2708ECF46','44A2C4905136BCFE4C99C718E7FB0052','3C1737139C50A9A84FA5183FEAAEDE8E')
   GROUP BY CAST(O.DATE_ACCEPT AS DATE), EXTRACT(HOUR FROM O.DATE_ACCEPT);

  DELETE FROM TMP_OTHER_COUNT;
  INSERT INTO TMP_OTHER_COUNT (DATE_ACCEPT,DAY_HOUR,ORDER_COUNT)
  SELECT CAST(O.DATE_ACCEPT AS DATE) AS DATE_ACCEPT,
         EXTRACT(HOUR FROM DATE_ACCEPT) AS HOUR_ACCEPT,
         COUNT(*) AS ORDER_COUNT
    FROM ORDERS O
   WHERE O.DATE_ACCEPT>=:DATE_BEGIN AND O.DATE_ACCEPT<:DATE_END
     AND O.WHO_HISTORY_ID IS NULL
     AND O.FINISHED=1
     AND O.RESULT_ID NOT IN ('6DD8DFDC671DB9A742E418FD268E7DC4','5F54734558C5857445839E8800947005','25236D63D02FA50F4D39DF1A2F86B6F6',
                             'D442C437F10AA16447252BE436C90807','CCBAB9B83127B43F44F0B5C2708ECF46',
                             '44A2C4905136BCFE4C99C718E7FB0052','3C1737139C50A9A84FA5183FEAAEDE8E')
   GROUP BY CAST(O.DATE_ACCEPT AS DATE), EXTRACT(HOUR FROM O.DATE_ACCEPT);

  DELETE FROM TMP_SCHEDULE_COUNT;
  INSERT INTO TMP_SCHEDULE_COUNT (WEEK_DAY,DAY_HOUR,SCHEDULE_COUNT)
  SELECT (CASE WHEN DWS.WEEK_DAY=6 THEN 0 ELSE DWS.WEEK_DAY+1 END) AS WEEK_DAY,
         DWS.DAY_HOUR,
         COUNT(*) AS SCHEDULE_COUNT
    FROM DRIVER_WEEK_SCHEDULES DWS
    JOIN ACCOUNTS A ON A.ACCOUNT_ID=DWS.DRIVER_ID
   WHERE A.LOCKED=0
   GROUP BY DWS.WEEK_DAY, DWS.DAY_HOUR;

  DELETE FROM TMP_SHIFT_COUNT;
  INSERT INTO TMP_SHIFT_COUNT (DATE_SHIFT,DAY_HOUR,SHIFT_COUNT)
  SELECT DATE_SHIFT, DAY_HOUR, ROUND(SUM(RATIO),0)
    FROM GET_SHIFT_COUNT(:DATE_BEGIN,:DATE_END)
   GROUP BY DATE_SHIFT, DAY_HOUR;

  DELETE FROM TMP_PARK_COUNT;
  INSERT INTO TMP_PARK_COUNT (DATE_PARK,DAY_HOUR,PARK_COUNT)
  SELECT DATE_PARK, DAY_HOUR, ROUND(SUM(RATIO),0)
    FROM GET_PARK_COUNT(:DATE_BEGIN,:DATE_END)
   GROUP BY DATE_PARK, DAY_HOUR;

  FOR SELECT TH.DATE_HOUR,
             EXTRACT(WEEKDAY FROM TH.DATE_HOUR),
             DECODE(EXTRACT(WEEKDAY FROM TH.DATE_HOUR),
                    1,'понедельник',
                    2,'вторник',
                    3,'среда',
                    4,'четверг',
                    5,'пятница',
                    6,'суббота',
                    0,'воскресенье'),
             TH.DAY_HOUR,
             CASE WHEN TRC.ORDER_COUNT IS NULL THEN 0 ELSE TRC.ORDER_COUNT END,
             CASE WHEN TDC.ORDER_COUNT IS NULL THEN 0 ELSE TDC.ORDER_COUNT END,
             CASE WHEN TOC.ORDER_COUNT IS NULL THEN 0 ELSE TOC.ORDER_COUNT END,
             CASE WHEN TSC.SCHEDULE_COUNT IS NULL THEN 0 ELSE TSC.SCHEDULE_COUNT END,
             CASE WHEN THC.SHIFT_COUNT IS NULL THEN 0 ELSE THC.SHIFT_COUNT END,
             CASE WHEN TPC.PARK_COUNT IS NULL THEN 0 ELSE TPC.PARK_COUNT END
        FROM TMP_HOURS TH
        LEFT JOIN TMP_REAL_COUNT TRC ON TRC.DATE_ACCEPT=TH.DATE_HOUR AND TRC.DAY_HOUR=TH.DAY_HOUR
        LEFT JOIN TMP_DOUBLE_COUNT TDC ON TDC.DATE_ACCEPT=TH.DATE_HOUR AND TDC.DAY_HOUR=TH.DAY_HOUR
        LEFT JOIN TMP_OTHER_COUNT TOC ON TOC.DATE_ACCEPT=TH.DATE_HOUR AND TOC.DAY_HOUR=TH.DAY_HOUR
        LEFT JOIN TMP_SCHEDULE_COUNT TSC ON TSC.WEEK_DAY=EXTRACT(WEEKDAY FROM TH.DATE_HOUR) AND TSC.DAY_HOUR=TH.DAY_HOUR
        LEFT JOIN TMP_SHIFT_COUNT THC ON THC.DATE_SHIFT=TH.DATE_HOUR AND THC.DAY_HOUR=TH.DAY_HOUR
        LEFT JOIN TMP_PARK_COUNT TPC ON TPC.DATE_PARK=TH.DATE_HOUR AND TPC.DAY_HOUR=TH.DAY_HOUR
       ORDER BY TH.DATE_HOUR, TH.DAY_HOUR 
        INTO :DATE_HOUR, :WEEK_DAY, :WEEK_DAY_NAME, :DAY_HOUR,
             :REAL_COUNT, :DOUBLE_COUNT, :OTHER_COUNT,
             :SCHEDULE_COUNT, :SHIFT_COUNT, :PARK_COUNT DO BEGIN
    SUSPEND;
  END
END

--

CREATE OR ALTER PROCEDURE GET_ORDER_DAY_COUNT
(
  DATE_BEGIN TIMESTAMP,
  DATE_END TIMESTAMP,
  FIRM_ID VARCHAR(32)
)
RETURNS
(
  DATE_GRAPH DATE,
  FIRM_SMALL_NAME VARCHAR(100),
  ORDER_COUNT INTEGER,
  ORDER_SUM NUMERIC(15,2),
  ORDER_AVERAGE NUMERIC(15,2)
--  ,SQL VARCHAR(4000)
)
AS
DECLARE SQL VARCHAR(4000);
BEGIN
  SQL='SELECT T.DG, F.SMALL_NAME, T.OC, T.OS, T.OS/T.OC ';
  SQL=SQL||'FROM (SELECT CAST(O.DATE_ACCEPT AS DATE) AS DG, O.FIRM_ID, COUNT(*) AS OC, SUM(C.SUM_CHARGE) AS OS ';
  SQL=SQL||'FROM ORDERS O ';
  SQL=SQL||'LEFT JOIN CHARGES C ON C.ORDER_ID=O.ORDER_ID AND C.FIRM_ID=O.FIRM_ID ';
  SQL=SQL||'WHERE O.WHO_HISTORY_ID IS NULL AND O.FINISHED=1 ';
  SQL=SQL||'AND O.RESULT_ID=''6DD8DFDC671DB9A742E418FD268E7DC4'' ';

  IF (FIRM_ID IS NOT NULL) THEN
    SQL=SQL||'AND O.FIRM_ID='''||FIRM_ID||''' ';

  IF (DATE_BEGIN IS NOT NULL) THEN
    SQL=SQL||'AND O.DATE_ACCEPT>='''||FORMAT_DATETIME('dd.mm.yyyy hh:nn:ss',DATE_BEGIN)||''' ';

  IF (DATE_END IS NOT NULL) THEN
    SQL=SQL||'AND O.DATE_ACCEPT<'''||FORMAT_DATETIME('dd.mm.yyyy hh:nn:ss',DATE_END)||''' ';

  SQL=SQL||'GROUP BY CAST(O.DATE_ACCEPT AS DATE), O.FIRM_ID) T ';

  SQL=SQL||'JOIN FIRMS F ON F.FIRM_ID=T.FIRM_ID ';
  SQL=SQL||'ORDER BY T.DG, F.SMALL_NAME ';


  FOR EXECUTE STATEMENT SQL
                   INTO :DATE_GRAPH, :FIRM_SMALL_NAME, :ORDER_COUNT, :ORDER_SUM, :ORDER_AVERAGE DO BEGIN
    SUSPEND;
  END

END

--

CREATE OR ALTER PROCEDURE GET_ORDER_WEEK_COUNT
(
  DATE_BEGIN TIMESTAMP,
  FIRM_ID VARCHAR(32),
  WEEK_OFFSET INTEGER

)
RETURNS
(
  DATE_DAY DATE,
  WEEK_DAY INTEGER,
  WEEK_DAY_NANE VARCHAR(100),
  FIRM_SMALL_NAME VARCHAR(100),
  ORDER_COUNT INTEGER,
  ORDER_SUM NUMERIC(15,2),
  ORDER_AVERAGE NUMERIC(15,2)
--  , SQL VARCHAR(4000)
)
AS
DECLARE SQL VARCHAR(4000);
BEGIN
  SQL='SELECT T.DG, F.SMALL_NAME, T.OC, T.OS, T.OS/T.OC, ';
  SQL=SQL||'EXTRACT(WEEKDAY FROM T.DG), ';
  SQL=SQL||'DECODE(EXTRACT(WEEKDAY FROM T.DG),1,''пн'',2,''вт'',3,''ср'',4,''чт'',5,''пт'',6,''сб'',0,''вс'') ';
  SQL=SQL||'FROM (SELECT CAST(O.DATE_ACCEPT AS DATE) AS DG, O.FIRM_ID, COUNT(*) AS OC, SUM(C.SUM_CHARGE) AS OS ';
  SQL=SQL||'FROM ORDERS O ';
  SQL=SQL||'LEFT JOIN CHARGES C ON C.ORDER_ID=O.ORDER_ID AND C.FIRM_ID=O.FIRM_ID ';
  SQL=SQL||'WHERE O.WHO_HISTORY_ID IS NULL AND O.FINISHED=1 ';
  SQL=SQL||'AND O.RESULT_ID=''6DD8DFDC671DB9A742E418FD268E7DC4'' ';

  IF (FIRM_ID IS NOT NULL) THEN
    SQL=SQL||'AND O.FIRM_ID='''||FIRM_ID||''' ';

  IF (DATE_BEGIN IS NOT NULL) THEN BEGIN
    SQL=SQL||'AND O.DATE_ACCEPT<DATEADD(DAY,'||CAST(WEEK_OFFSET*7+1 AS VARCHAR(5))||',CAST('''||FORMAT_DATETIME('dd.mm.yyyy hh:nn:ss',DATE_BEGIN)||''' AS TIMESTAMP)) ';
    SQL=SQL||'AND O.DATE_ACCEPT>=DATEADD(DAY,'||CAST(WEEK_OFFSET*7-6 AS VARCHAR(5))||',CAST('''||FORMAT_DATETIME('dd.mm.yyyy hh:nn:ss',DATE_BEGIN)||''' AS TIMESTAMP)) ';
  END

  SQL=SQL||'GROUP BY CAST(O.DATE_ACCEPT AS DATE), O.FIRM_ID) T ';

  SQL=SQL||'JOIN FIRMS F ON F.FIRM_ID=T.FIRM_ID ';
  SQL=SQL||'ORDER BY T.DG, F.SMALL_NAME ';


  FOR EXECUTE STATEMENT SQL
                   INTO :DATE_DAY, :FIRM_SMALL_NAME,
                        :ORDER_COUNT, :ORDER_SUM, :ORDER_AVERAGE,
                        :WEEK_DAY, :WEEK_DAY_NANE DO BEGIN
    SUSPEND;
  END

END

--

CREATE OR ALTER PROCEDURE GET_ORDER_HOUR_COUNT
(
  DATE_BEGIN TIMESTAMP,
  DATE_END TIMESTAMP,
  FIRM_ID VARCHAR(32)
)
RETURNS
(
  DATE_DAY DATE,
  DAY_HOUR INTEGER,
  FIRM_SMALL_NAME VARCHAR(100),
  ORDER_COUNT INTEGER,
  ORDER_SUM NUMERIC(15,2),
  ORDER_AVERAGE NUMERIC(15,2)
--  , SQL VARCHAR(4000)
)
AS
DECLARE SQL VARCHAR(4000);
BEGIN
  SQL='SELECT T.DG, T.DH, F.SMALL_NAME, T.OC, T.OS, T.OS/T.OC ';
  SQL=SQL||'FROM (SELECT CAST(O.DATE_ACCEPT AS DATE) AS DG, EXTRACT(HOUR FROM O.DATE_ACCEPT) AS DH, O.FIRM_ID, COUNT(*) AS OC, SUM(C.SUM_CHARGE) AS OS ';
  SQL=SQL||'FROM ORDERS O ';
  SQL=SQL||'LEFT JOIN CHARGES C ON C.ORDER_ID=O.ORDER_ID AND C.FIRM_ID=O.FIRM_ID ';
  SQL=SQL||'WHERE O.WHO_HISTORY_ID IS NULL AND O.FINISHED=1 ';
  SQL=SQL||'AND O.RESULT_ID=''6DD8DFDC671DB9A742E418FD268E7DC4'' ';

  IF (FIRM_ID IS NOT NULL) THEN
    SQL=SQL||'AND O.FIRM_ID='''||FIRM_ID||''' ';

  IF (DATE_BEGIN IS NOT NULL) THEN
    SQL=SQL||'AND O.DATE_ACCEPT>='''||FORMAT_DATETIME('dd.mm.yyyy hh:nn:ss',DATE_BEGIN)||''' ';

  IF (DATE_BEGIN IS NOT NULL) THEN
    SQL=SQL||'AND O.DATE_ACCEPT<'''||FORMAT_DATETIME('dd.mm.yyyy hh:nn:ss',DATE_END)||''' ';

  SQL=SQL||'GROUP BY CAST(O.DATE_ACCEPT AS DATE), EXTRACT(HOUR FROM O.DATE_ACCEPT), O.FIRM_ID) T ';

  SQL=SQL||'JOIN FIRMS F ON F.FIRM_ID=T.FIRM_ID ';
  SQL=SQL||'ORDER BY T.DG, T.DH, F.SMALL_NAME ';


  FOR EXECUTE STATEMENT SQL
                   INTO :DATE_DAY, :DAY_HOUR, :FIRM_SMALL_NAME,
                        :ORDER_COUNT, :ORDER_SUM, :ORDER_AVERAGE DO BEGIN
    SUSPEND;
  END

END


--




