DECLARE EXTERNAL FUNCTION RANDOM_STRING
    INTEGER,
    CSTRING(32767)
RETURNS PARAMETER 2
ENTRY_POINT 'RANDOM_STRING' MODULE_NAME 'udfibase.dll';

--

DECLARE EXTERNAL FUNCTION CHR
    INTEGER,
    CSTRING(1)
RETURNS PARAMETER 2
ENTRY_POINT 'CHR' MODULE_NAME 'udfibase.dll';

--

DECLARE EXTERNAL FUNCTION BLOB_TO_STRING
    BLOB,
    INTEGER,
    INTEGER,
    CSTRING(32767)
RETURNS PARAMETER 4
ENTRY_POINT 'BLOB_TO_STRING' MODULE_NAME 'udfibase.dll';

--

