CREATE OR ALTER PROCEDURE GET_ROUTE_DISTANCE 
(
  LAT1 DOUBLE PRECISION,
  LON1 DOUBLE PRECISION,
  LAT2 DOUBLE PRECISION,
  LON2 DOUBLE PRECISION
) 
RETURNS (
  DISTANCE DOUBLE PRECISION)
AS
BEGIN
  DISTANCE=0.0;
/*  DISTANCE=MAP_DISTANCE('C:\GWX6\MAPS\KRSNJRSK.chart',LAT1,LON1,LAT2,LON2);*/
END

--

DROP EXTERNAL FUNCTION MAP_DISTANCE

--

DECLARE EXTERNAL FUNCTION HTTP_POST
    CSTRING(32767),
    CSTRING(32767),
    CSTRING(32767),
    CSTRING(32767)
RETURNS CSTRING(32767)
ENTRY_POINT 'HTTP_POST' MODULE_NAME 'udfibase.dll';

--

DECLARE EXTERNAL FUNCTION HTTP_GET
    CSTRING(32767),
    CSTRING(32767),
    CSTRING(32767),
    CSTRING(32767)
RETURNS CSTRING(32767)
ENTRY_POINT 'HTTP_GET' MODULE_NAME 'udfibase.dll';

--

CREATE OR ALTER PROCEDURE GET_ROUTE_DISTANCE
(
  LAT1 DOUBLE PRECISION,
  LON1 DOUBLE PRECISION,
  LAT2 DOUBLE PRECISION,
  LON2 DOUBLE PRECISION) 
RETURNS (
  DISTANCE DOUBLE PRECISION)
AS
DECLARE RET VARCHAR(100);
DECLARE PARAMS VARCHAR(250);
BEGIN
  DISTANCE=0.0;

  PARAMS='?Lat1='||CAST(CAST(LAT1 AS NUMERIC(12,9)) AS VARCHAR(30))||
         '&Lon1='||CAST(CAST(LON1 AS NUMERIC(12,9)) AS VARCHAR(30))||
         '&Lat2='||CAST(CAST(LAT2 AS NUMERIC(12,9)) AS VARCHAR(30))||
         '&Lon2='||CAST(CAST(LON2 AS NUMERIC(12,9)) AS VARCHAR(30));

  RET=HTTP_GET('192.168.1.3','80','/ingitmap',PARAMS);

  IF (RET IS NOT NULL) THEN
    DISTANCE=CAST(RET AS NUMERIC(15,2));

END


--

