ALTER TABLE SESSIONS
ADD QUERY_TEXT BLOB

--

ALTER TABLE SESSIONS
ADD DURATION INTEGER

--

CREATE OR ALTER VIEW S_SESSIONS
(
    SESSION_ID,
    ACCOUNT_ID,
    APPLICATION_ID,
    DATE_CREATE,
    DATE_CHANGE,
    PARAMS,
    QUERY_TEXT,
    DURATION,
    USER_NAME,
    APPLICATION_NAME
)
AS
SELECT S.*, 
       AC.USER_NAME AS USER_NAME,
       AP.NAME AS APPLICATION_NAME
  FROM SESSIONS S
  JOIN ACCOUNTS AC ON AC.ACCOUNT_ID=S.ACCOUNT_ID
  JOIN APPLICATIONS AP ON AP.APPLICATION_ID=S.APPLICATION_ID

--

CREATE OR ALTER PROCEDURE I_SESSION
(
  SESSION_ID VARCHAR(32),
  ACCOUNT_ID VARCHAR(32),
  APPLICATION_ID VARCHAR(32),
  DATE_CREATE TIMESTAMP,
  DATE_CHANGE TIMESTAMP,
  PARAMS BLOB,
  QUERY_TEXT BLOB,
  DURATION INTEGER
)
AS
BEGIN
  INSERT INTO SESSIONS (SESSION_ID,ACCOUNT_ID,APPLICATION_ID,DATE_CREATE,DATE_CHANGE,
                        PARAMS,QUERY_TEXT,DURATION)
       VALUES (:SESSION_ID,:ACCOUNT_ID,:APPLICATION_ID,:DATE_CREATE,:DATE_CHANGE,
               :PARAMS,:QUERY_TEXT,:DURATION);
END

--

CREATE OR ALTER PROCEDURE U_SESSION
(
  SESSION_ID VARCHAR(32),
  ACCOUNT_ID VARCHAR(32),
  APPLICATION_ID VARCHAR(32),
  DATE_CREATE TIMESTAMP,
  DATE_CHANGE TIMESTAMP,
  PARAMS BLOB,
  QUERY_TEXT BLOB,
  DURATION INTEGER,
  OLD_SESSION_ID VARCHAR(32)
)
AS
BEGIN
  UPDATE SESSIONS
     SET SESSION_ID=:SESSION_ID,
         ACCOUNT_ID=:ACCOUNT_ID,
         APPLICATION_ID=:APPLICATION_ID,
         DATE_CREATE=:DATE_CREATE,
         DATE_CHANGE=:DATE_CHANGE,
         PARAMS=:PARAMS,
         QUERY_TEXT=:QUERY_TEXT,
         DURATION=:DURATION
   WHERE SESSION_ID=:OLD_SESSION_ID;
END

--

CREATE OR ALTER PROCEDURE TASK_DELETE_QUERIES
(
  SESSION_ID VARCHAR(32),
  TASK_ID VARCHAR(32)
)
AS
BEGIN
  DELETE FROM MON$STATEMENTS
   WHERE DATEADD(10 SECOND TO MON$TIMESTAMP)<CURRENT_TIMESTAMP
     AND MON$STATE<>0;
END

--

CREATE OR ALTER PROCEDURE GET_EVENT_PARAMS
(
  SESSION_ID VARCHAR(32),
  PROTOCOL INTEGER
)
RETURNS (
  IP VARCHAR(20),
  PORT VARCHAR(10),
  LISTEN_IP VARCHAR(20),
  HOST VARCHAR(100),
  PATH VARCHAR(100),
  USE_CRYPTER INTEGER,
  CRYPTER_ALGORITHM INTEGER,
  CRYPTER_MODE INTEGER,
  CRYPTER_KEY VARCHAR(100),
  USE_COMPRESSOR INTEGER,
  COMPRESSOR_LEVEL INTEGER)
AS
DECLARE PARAMS BLOB;
DECLARE SECTION VARCHAR(100);
DECLARE S VARCHAR(1000);
BEGIN
  SELECT PARAMS
    FROM SESSIONS
   WHERE SESSION_ID=:SESSION_ID
    INTO :PARAMS;

  IF ((PROTOCOL=0) OR (PROTOCOL IS NULL)) THEN
    SECTION='ExternalUdpEventServer';
  ELSE
    SECTION='FirstHttpServerHandlerEvent';

  IF (CONFIG_EXISTS(PARAMS,SECTION)=1) THEN BEGIN

    S=CONFIG_READ(PARAMS,SECTION,'IP','');
    IP=SUB_STRING(CASE WHEN POSITION(';',S)>0 THEN SUBSTRING(S FROM 1 FOR POSITION(';',S)-1) ELSE S END,1,20);
    S=CONFIG_READ(PARAMS,SECTION,'Port','');
    PORT=SUB_STRING(CASE WHEN POSITION(';',S)>0 THEN SUBSTRING(S FROM 1 FOR POSITION(';',S)-1) ELSE S END,1,10);
    S=CONFIG_READ(PARAMS,SECTION,'ListenIP','');
    LISTEN_IP=SUB_STRING(CASE WHEN POSITION(';',S)>0 THEN SUBSTRING(S FROM 1 FOR POSITION(';',S)-1) ELSE S END,1,20);
    HOST=SUB_STRING(CONFIG_READ(PARAMS,SECTION,'Host',''),1,100);
    PATH=SUB_STRING(CONFIG_READ(PARAMS,SECTION,'Path',''),1,100);
    USE_CRYPTER=CAST(CONFIG_READ(PARAMS,SECTION,'UseCrypter','0') AS INTEGER);
    CRYPTER_ALGORITHM=CAST(CONFIG_READ(PARAMS,SECTION,'CrypterAlgorithm','0') AS INTEGER);
    CRYPTER_MODE=CAST(CONFIG_READ(PARAMS,SECTION,'CrypterMode','0') AS INTEGER);
    CRYPTER_KEY=CONFIG_READ(PARAMS,SECTION,'CrypterKey','');
    USE_COMPRESSOR=CAST(CONFIG_READ(PARAMS,SECTION,'UseCompressor','0') AS INTEGER);
    COMPRESSOR_LEVEL=CAST(CONFIG_READ(PARAMS,SECTION,'CompressorLevel','0') AS INTEGER);

  END

END

--

CREATE TABLE OPERATORS
(
  OPERATOR_ID VARCHAR(32) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(250),
  RANGES BLOB NOT NULL,
  ENABLED INTEGER NOT NULL,
  PRIORITY INTEGER
  PRIMARY KEY (OPERATOR_ID)
)

--

CREATE OR ALTER VIEW S_OPERATORS
AS
SELECT O.*
  FROM OPERATORS O

--

CREATE OR ALTER PROCEDURE I_OPERATOR
(
  OPERATOR_ID VARCHAR(32),
  NAME VARCHAR(100),
  DESCRIPTION VARCHAR(250),
  RANGES BLOB,
  ENABLED INTEGER,
  PRIORITY INTEGER
)
AS
BEGIN
  INSERT INTO OPERATORS (OPERATOR_ID,NAME,DESCRIPTION,RANGES,ENABLED,PRIORITY)
       VALUES (:OPERATOR_ID,:NAME,:DESCRIPTION,:RANGES,:ENABLED,:PRIORITY);
END

--

CREATE OR ALTER PROCEDURE U_OPERATOR
(
  OPERATOR_ID VARCHAR(32),
  NAME VARCHAR(100),
  DESCRIPTION VARCHAR(250),
  RANGES BLOB,
  ENABLED INTEGER,
  PRIORITY INTEGER,
  OLD_OPERATOR_ID VARCHAR(32)
)
AS
BEGIN
  UPDATE OPERATORS
     SET OPERATOR_ID=:OPERATOR_ID,
         NAME=:NAME,
         DESCRIPTION=:DESCRIPTION,
         RANGES=:RANGES,
         ENABLED=:ENABLED,
         PRIORITY=:PRIORITY
   WHERE OPERATOR_ID=:OLD_OPERATOR_ID;
END;

--

CREATE PROCEDURE D_OPERATOR
(
  OLD_OPERATOR_ID VARCHAR(32)
)
AS
BEGIN
  DELETE FROM OPERATORS
        WHERE OPERATOR_ID=:OLD_OPERATOR_ID;
END; 

--

ALTER TABLE OUT_MESSAGES
ADD OPERATOR_ID VARCHAR(32)

--

ALTER TABLE OUT_MESSAGES
ADD FOREIGN KEY (OPERATOR_ID) REFERENCES OPERATORS (OPERATOR_ID)

--

CREATE OR ALTER VIEW S_OUT_MESSAGES
(
    OUT_MESSAGE_ID,
    CREATOR_ID,
    RECIPIENT_ID,
    DATE_CREATE,
    TEXT_OUT,
    DATE_OUT,
    TYPE_MESSAGE,
    CONTACT,
    DESCRIPTION,
    PRIORITY,
    LOCKED,
    DATE_BEGIN,
    DATE_END,
    ORDER_ID,
    CHANNEL,
    DELIVERY,
    DATE_DELIVERY,
    FLASH,
    DEST_PORT,
    FIRM_ID,
    OPERATOR_ID,
    CREATOR_NAME,
    RECIPIENT_USER_NAME,
    RECIPIENT_SURNAME,
    RECIPIENT_NAME,
    RECIPIENT_PATRONYMIC,
    RECIPIENT_PHONE,
    RECIPIENT_EMAIL,
    FIRM_SMALL_NAME,
    OPERATOR_NAME
)
AS
SELECT OM.*,
       A1.USER_NAME AS CREATOR_NAME,
       A2.USER_NAME AS RECIPIENT_USER_NAME,
       A2.SURNAME AS RECIPIENT_SURNAME,
       A2.NAME AS RECIPIENT_NAME,
       A2.PATRONYMIC AS RECIPIENT_PATRONYMIC,
       A2.PHONE AS RECIPIENT_PHONE,
       A2.EMAIL AS RECIPIENT_EMAIL,
       F.SMALL_NAME AS FIRM_SMALL_NAME,
       O.NAME AS OPERATOR_NAME
  FROM OUT_MESSAGES OM
  JOIN ACCOUNTS A1 ON A1.ACCOUNT_ID=OM.CREATOR_ID
  LEFT JOIN ACCOUNTS A2 ON A2.ACCOUNT_ID=OM.RECIPIENT_ID
  LEFT JOIN FIRMS F ON F.FIRM_ID=OM.FIRM_ID
  LEFT JOIN OPERATORS O ON O.OPERATOR_ID=OM.OPERATOR_ID

--

CREATE OR ALTER VIEW S_DRIVER_OUT_MESSAGES
(
    OUT_MESSAGE_ID,
    CREATOR_ID,
    RECIPIENT_ID,
    DATE_CREATE,
    TEXT_OUT,
    DATE_OUT,
    TYPE_MESSAGE,
    CONTACT,
    DESCRIPTION,
    PRIORITY,
    LOCKED,
    DATE_BEGIN,
    DATE_END,
    ORDER_ID,
    CHANNEL,
    DELIVERY,
    DATE_DELIVERY,
    FLASH,
    DEST_PORT,
    FIRM_ID,
    OPERATOR_ID,
    CREATOR_NAME,
    RECIPIENT_USER_NAME,
    RECIPIENT_SURNAME,
    RECIPIENT_NAME,
    RECIPIENT_PATRONYMIC,
    RECIPIENT_PHONE,
    RECIPIENT_EMAIL,
    CAR_STATE_NUM,
    CAR_BRAND,
    CAR_COLOR,
    CAR_CALLSIGN,
    FIRM_SMALL_NAME,
    OPERATOR_NAME)
AS
SELECT OM.*,
       A1.USER_NAME AS CREATOR_NAME,
       A2.USER_NAME AS RECIPIENT_USER_NAME,
       A2.SURNAME AS RECIPIENT_SURNAME,
       A2.NAME AS RECIPIENT_NAME,
       A2.PATRONYMIC AS RECIPIENT_PATRONYMIC,
       A2.PHONE AS RECIPIENT_PHONE,
       A2.EMAIL AS RECIPIENT_EMAIL,
       CR.STATE_NUM AS CAR_STATE_NUM,
       CR.BRAND AS CAR_BRAND,
       CR.COLOR AS CAR_COLOR,
       CR.CALLSIGN AS CAR_CALLSIGN,
       F.SMALL_NAME AS FIRM_SMALL_NAME,
       O.NAME AS OPERATOR_NAME
  FROM OUT_MESSAGES OM
  JOIN DRIVERS D ON D.DRIVER_ID=OM.RECIPIENT_ID
  JOIN CARS CR ON CR.CAR_ID=D.CAR_ID
  JOIN ACCOUNTS A1 ON A1.ACCOUNT_ID=OM.CREATOR_ID
  LEFT JOIN ACCOUNTS A2 ON A2.ACCOUNT_ID=OM.RECIPIENT_ID
  LEFT JOIN FIRMS F ON F.FIRM_ID=OM.FIRM_ID
  LEFT JOIN OPERATORS O ON O.OPERATOR_ID=OM.OPERATOR_ID

--

CREATE OR ALTER PROCEDURE I_OUT_MESSAGE
(
  OUT_MESSAGE_ID VARCHAR(32),
  CREATOR_ID VARCHAR(32),
  RECIPIENT_ID VARCHAR(32),
  DATE_CREATE TIMESTAMP,
  TEXT_OUT VARCHAR(4000),
  DATE_OUT TIMESTAMP,
  TYPE_MESSAGE INTEGER,
  CONTACT VARCHAR(100),
  DESCRIPTION VARCHAR(250),
  PRIORITY INTEGER,
  LOCKED VARCHAR(32),
  DATE_BEGIN TIMESTAMP,
  DATE_END TIMESTAMP,
  ORDER_ID VARCHAR(32),
  CHANNEL VARCHAR(100),
  DELIVERY INTEGER,
  DATE_DELIVERY TIMESTAMP,
  FLASH INTEGER,
  DEST_PORT INTEGER,
  FIRM_ID VARCHAR(32),
  OPERATOR_ID VARCHAR(32)
)
AS
BEGIN
  INSERT INTO OUT_MESSAGES (OUT_MESSAGE_ID,CREATOR_ID,RECIPIENT_ID,DATE_CREATE,
                                      TEXT_OUT,DATE_OUT,TYPE_MESSAGE,CONTACT,DESCRIPTION,
                                      PRIORITY,DATE_BEGIN,DATE_END,ORDER_ID,CHANNEL,
                                      DELIVERY,DATE_DELIVERY,FLASH,DEST_PORT,FIRM_ID,OPERATOR_ID)
       VALUES (:OUT_MESSAGE_ID,:CREATOR_ID,:RECIPIENT_ID,:DATE_CREATE,
               :TEXT_OUT,:DATE_OUT,:TYPE_MESSAGE,:CONTACT,:DESCRIPTION,
               :PRIORITY,:DATE_BEGIN,:DATE_END,:ORDER_ID,:CHANNEL,
               :DELIVERY,:DATE_DELIVERY,:FLASH,:DEST_PORT,:FIRM_ID,:OPERATOR_ID);
END

--

CREATE OR ALTER PROCEDURE U_OUT_MESSAGE
(
  OUT_MESSAGE_ID VARCHAR(32),
  CREATOR_ID VARCHAR(32),
  RECIPIENT_ID VARCHAR(32),
  DATE_CREATE TIMESTAMP,
  TEXT_OUT VARCHAR(4000),
  DATE_OUT TIMESTAMP,
  TYPE_MESSAGE INTEGER,
  CONTACT VARCHAR(100),
  DESCRIPTION VARCHAR(250),
  PRIORITY INTEGER,
  LOCKED VARCHAR(32),
  DATE_BEGIN TIMESTAMP,
  DATE_END TIMESTAMP,
  ORDER_ID VARCHAR(32),
  CHANNEL VARCHAR(100),
  DELIVERY INTEGER,
  DATE_DELIVERY TIMESTAMP,
  FLASH INTEGER,
  DEST_PORT INTEGER,
  FIRM_ID VARCHAR(32),
  OPERATOR_ID VARCHAR(32),
  OLD_OUT_MESSAGE_ID VARCHAR(32)
)
AS
BEGIN
  UPDATE OUT_MESSAGES
     SET OUT_MESSAGE_ID=:OUT_MESSAGE_ID,
         CREATOR_ID=:CREATOR_ID,
         RECIPIENT_ID=:RECIPIENT_ID,
         DATE_CREATE=:DATE_CREATE,
         TEXT_OUT=:TEXT_OUT,
         DATE_OUT=:DATE_OUT,
         TYPE_MESSAGE=:TYPE_MESSAGE,
         CONTACT=:CONTACT,
         DESCRIPTION=:DESCRIPTION,
         PRIORITY=:PRIORITY,
         LOCKED=:LOCKED,
         DATE_BEGIN=:DATE_BEGIN,
         DATE_END=:DATE_END,
         ORDER_ID=:ORDER_ID,
         CHANNEL=:CHANNEL,
         DELIVERY=:DELIVERY,
         DATE_DELIVERY=:DATE_DELIVERY,
         FLASH=:FLASH,
         DEST_PORT=:DEST_PORT,
         FIRM_ID=:FIRM_ID,
         OPERATOR_ID=:OPERATOR_ID
   WHERE OUT_MESSAGE_ID=:OLD_OUT_MESSAGE_ID;
END

--

ALTER TABLE IN_MESSAGES
ADD OPERATOR_ID VARCHAR(32)

--

ALTER TABLE IN_MESSAGES
ADD FOREIGN KEY (OPERATOR_ID) REFERENCES OPERATORS (OPERATOR_ID)

--

CREATE OR ALTER VIEW S_IN_MESSAGES
(
    IN_MESSAGE_ID,
    SENDER_ID,
    CODE_MESSAGE_ID,
    DATE_SEND,
    TEXT_IN,
    DATE_IN,
    TYPE_MESSAGE,
    CONTACT,
    ORDER_ID,
    CHANNEL,
    DESCRIPTION,
    FIRM_ID,
    OPERATOR_ID,
    SENDER_USER_NAME,
    SENDER_SURNAME,
    SENDER_NAME,
    SENDER_PATRONYMIC,
    CODE,
    FIRM_SMALL_NAME,
    OPERATOR_NAME
)
AS
SELECT IM.*,
       A.USER_NAME AS SENDER_USER_NAME,
       A.SURNAME AS SENDER_SURNAME,
       A.NAME AS SENDER_NAME,
       A.PATRONYMIC AS SENDER_PATRONYMIC,
       CM.CODE,
       F.SMALL_NAME AS FIRM_SMALL_NAME,
       O.NAME AS OPERATOR_NAME
  FROM IN_MESSAGES IM
  LEFT JOIN ACCOUNTS A ON A.ACCOUNT_ID=IM.SENDER_ID
  LEFT JOIN CODE_MESSAGES CM ON CM.CODE_MESSAGE_ID=IM.CODE_MESSAGE_ID
  LEFT JOIN FIRMS F ON F.FIRM_ID=IM.FIRM_ID
  LEFT JOIN OPERATORS O ON O.OPERATOR_ID=IM.OPERATOR_ID

--

CREATE OR ALTER VIEW S_DRIVER_IN_MESSAGES
(
    IN_MESSAGE_ID,
    SENDER_ID,
    CODE_MESSAGE_ID,
    DATE_SEND,
    TEXT_IN,
    DATE_IN,
    TYPE_MESSAGE,
    CONTACT,
    ORDER_ID,
    CHANNEL,
    DESCRIPTION,
    FIRM_ID,
    OPERATOR_ID,
    SENDER_USER_NAME,
    SENDER_SURNAME,
    SENDER_NAME,
    SENDER_PATRONYMIC,
    CODE,
    CAR_STATE_NUM,
    CAR_BRAND,
    CAR_COLOR,
    CAR_CALLSIGN,
    FIRM_SMALL_NAME,
    OPERATOR_NAME)
AS
SELECT IM.*,
       A.USER_NAME AS SENDER_USER_NAME,
       A.SURNAME AS SENDER_SURNAME,
       A.NAME AS SENDER_NAME,
       A.PATRONYMIC AS SENDER_PATRONYMIC,
       CM.CODE,
       CR.STATE_NUM AS CAR_STATE_NUM,
       CR.BRAND AS CAR_BRAND,
       CR.COLOR AS CAR_COLOR,
       CR.CALLSIGN AS CAR_CALLSIGN,
       F.SMALL_NAME AS FIRM_SMALL_NAME,
       O.NAME AS OPERATOR_NAME
  FROM IN_MESSAGES IM
  JOIN DRIVERS D ON D.DRIVER_ID=IM.SENDER_ID
  JOIN CARS CR ON CR.CAR_ID=D.CAR_ID
  LEFT JOIN ACCOUNTS A ON A.ACCOUNT_ID=IM.SENDER_ID
  LEFT JOIN CODE_MESSAGES CM ON CM.CODE_MESSAGE_ID=IM.CODE_MESSAGE_ID
  LEFT JOIN FIRMS F ON F.FIRM_ID=IM.FIRM_ID
  LEFT JOIN OPERATORS O ON O.OPERATOR_ID=IM.OPERATOR_ID

--

CREATE OR ALTER PROCEDURE I_IN_MESSAGE
(
  IN_MESSAGE_ID VARCHAR(32),
  SENDER_ID VARCHAR(32),
  CODE_MESSAGE_ID VARCHAR(32),
  DATE_SEND TIMESTAMP,
  TEXT_IN VARCHAR(4000),
  DATE_IN TIMESTAMP,
  TYPE_MESSAGE INTEGER,
  CONTACT VARCHAR(100),
  ORDER_ID VARCHAR(32),
  CHANNEL VARCHAR(100),
  DESCRIPTION VARCHAR(250),
  FIRM_ID VARCHAR(32),
  OPERATOR_ID VARCHAR(32)
)
AS
DECLARE CNT INTEGER;
BEGIN
  IF (DATE_IN IS NULL) THEN BEGIN
    DATE_IN=CURRENT_TIMESTAMP;
  END

  IF (SENDER_ID IS NOT NULL) THEN BEGIN

    IF (FIRM_ID IS NOT NULL) THEN BEGIN

      SELECT COUNT(*)
        FROM CLIENTS
       WHERE CLIENT_ID=:SENDER_ID
        INTO :CNT;

      IF (CNT>0) THEN
        FIRM_ID=NULL; /* Не понятно чьё сообщение */

    END

  END

  INSERT INTO IN_MESSAGES (IN_MESSAGE_ID,SENDER_ID,CODE_MESSAGE_ID,DATE_SEND,
                           TEXT_IN,DATE_IN,TYPE_MESSAGE,CONTACT,ORDER_ID,CHANNEL,
                           DESCRIPTION,FIRM_ID,OPERATOR_ID)
       VALUES (:IN_MESSAGE_ID,:SENDER_ID,:CODE_MESSAGE_ID,:DATE_SEND,
               :TEXT_IN,:DATE_IN,:TYPE_MESSAGE,:CONTACT,:ORDER_ID,:CHANNEL,
               :DESCRIPTION,:FIRM_ID,:OPERATOR_ID);
END

--

CREATE OR ALTER PROCEDURE U_IN_MESSAGE
(
  IN_MESSAGE_ID VARCHAR(32),
  SENDER_ID VARCHAR(32),
  CODE_MESSAGE_ID VARCHAR(32),
  DATE_SEND TIMESTAMP,
  TEXT_IN VARCHAR(4000),
  DATE_IN TIMESTAMP,
  TYPE_MESSAGE INTEGER,
  CONTACT VARCHAR(100),
  ORDER_ID VARCHAR(32),
  CHANNEL VARCHAR(100),
  DESCRIPTION VARCHAR(250),
  FIRM_ID VARCHAR(32),
  OPERATOR_ID VARCHAR(32),
  OLD_IN_MESSAGE_ID VARCHAR(32)
)
AS
BEGIN
  UPDATE IN_MESSAGES
     SET IN_MESSAGE_ID=:IN_MESSAGE_ID,
         SENDER_ID=:SENDER_ID,
         CODE_MESSAGE_ID=:CODE_MESSAGE_ID,
         DATE_SEND=:DATE_SEND,
         TEXT_IN=:TEXT_IN,
         DATE_IN=:DATE_IN,
         TYPE_MESSAGE=:TYPE_MESSAGE,
         CONTACT=:CONTACT,
         ORDER_ID=:ORDER_ID,
         CHANNEL=:CHANNEL,
         DESCRIPTION=:DESCRIPTION,
         FIRM_ID=:FIRM_ID,
         OPERATOR_ID=:OPERATOR_ID
   WHERE IN_MESSAGE_ID=:OLD_IN_MESSAGE_ID;
END

--

CREATE OR ALTER PROCEDURE UNLOCK_OUT_MESSAGE
(
  OUT_MESSAGE_ID VARCHAR(32),
  SENDED INTEGER,
  DATE_OUT TIMESTAMP
)
AS
BEGIN
  IF (SENDED IS NULL) THEN
    SENDED=0;
  IF (SENDED<>0) THEN BEGIN

    IF (DATE_OUT IS NULL) THEN
      DATE_OUT=CURRENT_TIMESTAMP;

    UPDATE OUT_MESSAGES
       SET DATE_OUT=:DATE_OUT,
           LOCKED=NULL
     WHERE OUT_MESSAGE_ID=:OUT_MESSAGE_ID;

  END ELSE BEGIN

    UPDATE OUT_MESSAGES
       SET LOCKED=NULL,
           CHANNEL=NULL,
           OPERATOR_ID=NULL
     WHERE OUT_MESSAGE_ID=:OUT_MESSAGE_ID;

  END

END

--

CREATE OR ALTER PROCEDURE GET_RANGE
(
  RANGE VARCHAR(1000)
)
RETURNS
(
  RANGE_MIN BIGINT,
  RANGE_MAX BIGINT
)
AS
DECLARE CNT_POS INTEGER;
DECLARE CNT_S VARCHAR(100);
DECLARE CNT INTEGER;
DECLARE RANGE_MIN_S VARCHAR(100);
DECLARE RANGE_MAX_S VARCHAR(100);
BEGIN
  IF ((RANGE IS NOT NULL) AND (TRIM(RANGE)<>'')) THEN BEGIN
    RANGE=REPLACE_STRING(RANGE,'+','');
    IF (TRIM(RANGE)<>'') THEN BEGIN
      CNT_POS=POSITION('/',RANGE);
      IF (CNT_POS>0) THEN BEGIN
        CNT_S=TRIM(SUB_STRING(RANGE,CNT_POS+1,100));
        CNT=CAST(CNT_S AS INTEGER);
        RANGE_MIN_S=SUB_STRING(RANGE,1,CNT_POS-1);
        RANGE_MIN=CAST(RANGE_MIN_S AS BIGINT);
        RANGE_MAX=RANGE_MIN+CNT-1;
      END ELSE BEGIN
        RANGE_MIN_S=TRIM(REPLACE_STRING(RANGE,'*','0'));
        RANGE_MIN=CAST(RANGE_MIN_S AS BIGINT);
        RANGE_MAX_S=TRIM(REPLACE_STRING(RANGE,'*','9'));
        RANGE_MAX=CAST(RANGE_MAX_S AS BIGINT);
      END
    END
  END
END

--

CREATE OR ALTER PROCEDURE GET_OPERATOR
(
  PHONE VARCHAR(100)
)
RETURNS
(
  OPERATOR_ID VARCHAR(32),
  RANGE_MIN BIGINT,
  RANGE_MAX BIGINT,
  PHONE_NUM BIGINT
--  ,RANGE VARCHAR(1000)
--  ,RANGES VARCHAR(32000)
)
AS
DECLARE RANGES VARCHAR(32000);
DECLARE RANGE VARCHAR(1000);
DECLARE POS INTEGER;
DECLARE FLAG INTEGER;
BEGIN
  OPERATOR_ID=NULL;
  FLAG=0;
  IF (PHONE IS NOT NULL) THEN BEGIN

    PHONE=TRIM(REPLACE_STRING(PHONE,'+',''));
    PHONE_NUM=CAST(PHONE AS BIGINT);

    FOR SELECT OPERATOR_ID, CAST(BLOB_TO_STRING(RANGES,1,32000) AS VARCHAR(32000))
          FROM OPERATORS
         WHERE ENABLED=1
         ORDER BY PRIORITY
          INTO :OPERATOR_ID, :RANGES DO BEGIN

      IF (RANGES IS NOT NULL) THEN BEGIN

        POS=-1;
        WHILE (POS<>0) DO BEGIN

          POS=POSITION(CHR(13)||CHR(10),RANGES);
          IF (POS>0) THEN BEGIN
            RANGE=SUB_STRING(RANGES,1,POS-1);
            RANGES=SUB_STRING(RANGES,POS+2,32000);
          END ELSE
            RANGE=SUB_STRING(RANGES,1,1000);

          EXECUTE PROCEDURE GET_RANGE(RANGE)
           RETURNING_VALUES RANGE_MIN, RANGE_MAX;

          IF ((PHONE_NUM>=RANGE_MIN) AND (PHONE_NUM<=RANGE_MAX)) THEN BEGIN
            FLAG=1;
            BREAK;
          END

        END
        
      END

      IF (FLAG=1) THEN BEGIN
        SUSPEND;
        BREAK;
      END

    END

  END

END

--

CREATE OR ALTER PROCEDURE GET_OPERATORS
RETURNS
(
  OPERATOR_ID VARCHAR(32),
  RANGE_MIN BIGINT,
  RANGE_MAX BIGINT
)
AS
DECLARE RANGES VARCHAR(32000);
DECLARE RANGE VARCHAR(1000);
DECLARE POS INTEGER;
DECLARE FLAG INTEGER;
BEGIN
  OPERATOR_ID=NULL;
  FLAG=0;

  FOR SELECT OPERATOR_ID, CAST(BLOB_TO_STRING(RANGES,1,32000) AS VARCHAR(32000))
        FROM OPERATORS
       WHERE ENABLED=1
       ORDER BY PRIORITY
        INTO :OPERATOR_ID, :RANGES DO BEGIN

    IF (RANGES IS NOT NULL) THEN BEGIN

      FLAG=0;

      POS=-1;
      WHILE (POS<>0) DO BEGIN

        POS=POSITION(CHR(13)||CHR(10),RANGES);
        IF (POS>0) THEN BEGIN
          RANGE=SUB_STRING(RANGES,1,POS-1);
          RANGES=SUB_STRING(RANGES,POS+2,32000);
        END ELSE
          RANGE=SUB_STRING(RANGES,1,1000);

        EXECUTE PROCEDURE GET_RANGE(RANGE)
         RETURNING_VALUES RANGE_MIN, RANGE_MAX;

        IF ((RANGE_MIN IS NOT NULL) AND (RANGE_MAX IS NOT NULL)) THEN BEGIN
          SUSPEND;
        END

      END
        
    END

  END

END

--

CREATE GLOBAL TEMPORARY TABLE TMP_OPERATORS
(
  RANGE_MIN BIGINT NOT NULL,
  RANGE_MAX BIGINT NOT NULL,
  OPERATOR_ID VARCHAR(32) NOT NULL,
  PRIMARY KEY (RANGE_MIN,RANGE_MAX)
) ON COMMIT DELETE ROWS

--

CREATE INDEX IDX_TMP_OPERATORS_RANGE_MIN
ON TMP_OPERATORS (RANGE_MIN)

--

CREATE INDEX IDX_TMP_OPERATORS_RANGE_MAX
ON TMP_OPERATORS (RANGE_MAX)

--

CREATE OR ALTER PROCEDURE LOCK_OUT_MESSAGES
(
  MAX_COUNT INTEGER,
  LOCKED VARCHAR(32),
  TYPE_MESSAGE INTEGER,
  PERIOD INTEGER,
  CHANNEL VARCHAR(100),
  OPERATOR_ID VARCHAR(32)
)
RETURNS
(
  LOCK_COUNT INTEGER
)
AS
DECLARE OUT_MESSAGE_ID VARCHAR(32);
BEGIN
  LOCK_COUNT=0;

  DELETE FROM TMP_OPERATORS;
  INSERT INTO TMP_OPERATORS (RANGE_MIN,RANGE_MAX,OPERATOR_ID)
  SELECT RANGE_MIN,RANGE_MAX,OPERATOR_ID
    FROM GET_OPERATORS;

  FOR SELECT T2.OUT_MESSAGE_ID
        FROM (SELECT T.OUT_MESSAGE_ID, O.OPERATOR_ID
                FROM (SELECT OUT_MESSAGE_ID,
                             CAST(TRIM(REPLACE_STRING(CONTACT,'+','')) AS BIGINT) AS CONTACT
                        FROM OUT_MESSAGES
                       WHERE DATE_OUT IS NULL
                         AND LOCKED IS NULL
                         AND TYPE_MESSAGE=:TYPE_MESSAGE
                         AND DATE_BEGIN<=CURRENT_TIMESTAMP
                         AND ((DATE_END IS NOT NULL AND DATE_END>=CURRENT_TIMESTAMP) OR
                              (DATE_END IS NULL AND DATEADD(SECOND,:PERIOD,DATE_BEGIN)>=CURRENT_TIMESTAMP))
                       ORDER BY PRIORITY, DATE_BEGIN) T
                LEFT JOIN TMP_OPERATORS O ON O.RANGE_MIN<=T.CONTACT AND O.RANGE_MAX>=T.CONTACT) T2
       WHERE (T2.OPERATOR_ID=:OPERATOR_ID AND :OPERATOR_ID IS NOT NULL)
          OR (T2.OPERATOR_ID IS NULL AND :OPERATOR_ID IS NULL)
        ROWS :MAX_COUNT
        INTO :OUT_MESSAGE_ID DO BEGIN

     UPDATE OUT_MESSAGES
        SET LOCKED=:LOCKED,
            CHANNEL=:CHANNEL,
            OPERATOR_ID=:OPERATOR_ID
      WHERE OUT_MESSAGE_ID=:OUT_MESSAGE_ID;

    LOCK_COUNT=LOCK_COUNT+1;

  END

END

--


