{ *********************************************************************** }
{                                                                         }
{ Delphi DBX Framework                                                    }
{                                                                         }
{ Copyright (c) 1997-2007 Borland Software Corporation                    }
{                                                                         }
{ *********************************************************************** }

unit DBXDb2MetaDataWriter;
interface
uses
  DBXMetaDataWriter;
type
  TDBXDb2MetaDataWriter = class(TDBXBaseMetaDataWriter)
  public
    constructor Create;
    procedure Open; override;
  protected
    function IsSerializedIsolationSupported: Boolean; override;
    function IsIndexNamesGlobal: Boolean; override;
    function IsDescendingIndexConstraintsSupported: Boolean; override;
    function GetSqlAutoIncrementKeyword: WideString; override;
  end;

implementation
uses
  DBXDb2MetaDataReader,
  DBXPlatformUtil;

constructor TDBXDb2MetaDataWriter.Create;
begin
  inherited Create;
  Open;
end;

procedure TDBXDb2MetaDataWriter.Open;
begin
  if FReader = nil then
    FReader := TDBXDb2MetaDataReader.Create;
end;

function TDBXDb2MetaDataWriter.IsSerializedIsolationSupported: Boolean;
begin
  Result := False;
end;

function TDBXDb2MetaDataWriter.IsIndexNamesGlobal: Boolean;
begin
  Result := True;
end;

function TDBXDb2MetaDataWriter.IsDescendingIndexConstraintsSupported: Boolean;
begin
  Result := False;
end;

function TDBXDb2MetaDataWriter.GetSqlAutoIncrementKeyword: WideString;
begin
  Result := 'GENERATED BY DEFAULT AS IDENTITY';
end;

end.
