// DO NOT EDIT THIS FILE - WARNING WARNING - Generated file
unit DBXErrorHandler;
interface
uses
  SysUtils;
type
  TDBXErrorHandler = class abstract
  public
    procedure HandleError(ErrorCode: Integer; ErrorMessage: WideString; Ex: Exception); virtual; abstract;
  end;

implementation

end.
