// DO NOT EDIT THIS FILE - WARNING WARNING - Generated file
unit DBXFieldHeader;
interface
type
  TDBXFieldHeader = class
  public
    const FNullValue = 128;
    const FAssignedNull = (FNullValue or 64);
    const FNullMask = (FNullValue or FAssignedNull);
    const FPositive = Byte(64);
    const FNullTermStringField = Byte(0);
    const FTinyField = Byte(32);
    const FBigField = Byte(16);
    const FBlobHeader = Byte(8);
    const FBlobRefHeader = Byte((FBlobHeader or 4));
    const FBlobMask = Byte((FPositive or FTinyField or FBigField or FBlobHeader));
    const FTinyHeaderLength = 1;
    const FNullTermLength = 4;
    const FOldNullTermLength = 2;
    const FNullTermOverHead = FNullTermLength + FTinyHeaderLength;
    const FOldNullTermOverHead = FOldNullTermLength + FTinyHeaderLength;
    const FTinyHeaderLengthMask = 31;
    const FBigHeaderLength = 3;
    const FSmallBlobHeaderLength = 5;
    const FMaxHeaderLength = FSmallBlobHeaderLength + 9;
  end;

implementation

end.
