// DO NOT EDIT THIS FILE - WARNING WARNING - Generated file
unit DBXRpcErrorCodes;
interface
type
  TDBXRpcErrorCodes = class
  public
    
    /// <summary> A general error occurred on the server prior to procedure invocation on the service.
    /// </summary>
    const ServerError = 1;
    
    /// <summary> An error occurred on the server while parsing the JSON text comprising the procedure call.
    /// </summary>
    const ParseError = 2;
    
    /// <summary> The procedure call is not valid.
    /// </summary>
    const BadCall = 3;
    
    /// <summary> The server refuses to process the call because a member is not in the required sequence.
    /// </summary>
    /// <remarks> For example, the params member of the Procedure Call object appeared before version or method members.
    /// </remarks>
    const MemberOutOfSequence = 4;
    
    /// <summary> The call is valid, but a general error occurred during the procedure invocation.
    /// </summary>
    const ServiceError = 5;
    
    /// <summary> The call is valid but the procedure identified by the call could not be located on the service.
    /// </summary>
    const ProcedureNotFound = 7;
  end;

implementation

end.
