// DO NOT EDIT THIS FILE - WARNING WARNING - Generated file
unit DBXStringCodes;
interface
type
  TDBXStringCodes = class
  public
    const Unknown = 1;
    const Result = 2;
    const Error = 3;
    const Connect = 4;
    const Disconnect = 5;
    const Prepare = 7;
    const Execute = 8;
    const CommandClose = 9;
    const ReaderClose = 10;
    const Rows = 11;
    const Table = 12;
    const Columns = 13;
    const Session = 14;
    const Data = 15;
    const Next = 16;
    const Handle = 17;
    const Fields = 18;
    const Parameters = 19;
    const Txbegin = 20;
    const Txend = 21;
    const MoreBlob = 22;
    const NextResult = 23;
    const VendorProperty = 24;
  end;

implementation

//  public static final int COMMAND_CREATE  =   6;
end.
