// DO NOT EDIT THIS FILE - WARNING WARNING - Generated file
unit DBXTokens;
interface
type
  TDBXTokens = class
  public
    const ErrorToken = 1;
    const ObjectStartToken = 2;
    const ObjectEndToken = 3;
    const ArrayStartToken = 4;
    const ArrayEndToken = 5;
    const TrueToken = 6;
    const FalseToken = 7;
    const NullToken = 8;
    const NumberStartToken = 9;
    const NumberEndToken = 9;
    const StringStartToken = 10;
    const StringEndToken = 11;
    const NameSeparatorToken = 12;
    const ValueSeparatorToken = 13;
  end;

implementation

end.
